src/ckb/animsettingdialog.cpp
NAME
src/ckb/animsettingdialog.cpp -
SYNOPSIS
#include <cstdio>
#include <QDial>
#include <QDoubleSpinBox>
#include <QLineEdit>
#include <QComboBox>
#include 'animsettingdialog.h'
#include 'ui_animsettingdialog.h'
#include 'colorbutton.h'
#include 'gradientbutton.h'
Functions
static int angleFlip (int angle)
Function Documentation
static int angleFlip (intangle) [inline], [static]
Definition at line 12 of file animsettingdialog.cpp.
References angle.
Referenced by AnimSettingDialog::angleDialChanged(), AnimSettingDialog::angleSpinnerChanged(), AnimSettingDialog::AnimSettingDialog(), and AnimSettingDialog::updateParam().
                                      {
    if(angle <= 180)
        return 180 - angle;
    else
       return 360 - (angle - 180);
}
Author
Generated automatically by Doxygen for ckb-next from the source code.