src/ckb-daemon/devnode.h
NAME
src/ckb-daemon/devnode.h -
SYNOPSIS
#include 'includes.h'
#include 'usb.h'
Macros
#define S_READDIR (S_IRWXU | S_IRGRP | S_IROTH | S_IXGRP | S_IXOTH)
#define S_READ (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR)
#define S_READWRITE (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR | S_IWGRP | S_IWOTH)
#define S_CUSTOM (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP)
#define S_CUSTOM_R (S_IRUSR | S_IWUSR | S_IRGRP)
Typedefs
typedef struct _readlines_ctx * readlines_ctx
Custom readline is needed for FIFOs. fopen()/getline() will die if the data is sent in too fast.
Functions
void updateconnected ()
Update the list of connected devices.
int mkdevpath (usbdevice *kb)
Create a dev path for the keyboard at index. Returns 0 on success.
int rmdevpath (usbdevice *kb)
Remove the dev path for the keyboard at index. Returns 0 on success.
int mknotifynode (usbdevice *kb, int notify)
Creates a notification node for the specified keyboard.
int rmnotifynode (usbdevice *kb, int notify)
Removes a notification node for the specified keyboard.
int mkfwnode (usbdevice *kb)
Writes a keyboard's firmware version and poll rate to its device node.
void readlines_ctx_init (readlines_ctx *ctx)
void readlines_ctx_free (readlines_ctx ctx)
unsigned readlines (int fd, readlines_ctx ctx, const char **input)
Variables
const char *const devpath
Device path base ('/dev/input/ckb' or '/var/run/ckb')
long gid
Group ID for the control nodes. -1 to give read/write access to everybody.
Macro Definition Documentation
#define S_CUSTOM (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP)
Definition at line 17 of file devnode.h.
Referenced by _mkdevpath().
#define S_CUSTOM_R (S_IRUSR | S_IWUSR | S_IRGRP)
Definition at line 18 of file devnode.h.
#define S_READ (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR)
Definition at line 15 of file devnode.h.
Referenced by _mkdevpath().
#define S_READDIR (S_IRWXU | S_IRGRP | S_IROTH | S_IXGRP | S_IXOTH)
Definition at line 14 of file devnode.h.
Referenced by _mkdevpath().
#define S_READWRITE (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR | S_IWGRP | S_IWOTH)
Definition at line 16 of file devnode.h.
Referenced by _mkdevpath().
Typedef Documentation
typedef struct _readlines_ctx* readlines_ctx
Definition at line 39 of file devnode.h.
Function Documentation
int mkdevpath (usbdevice *kb)
Definition at line 268 of file devnode.c.
References _mkdevpath(), euid_guard_start, and euid_guard_stop.
Referenced by _setupusb(), and main().
                            {
    euid_guard_start;
    int res = _mkdevpath(kb);
    euid_guard_stop;
    return res;
}
int mkfwnode (usbdevice *kb)
Definition at line 299 of file devnode.c.
References ckb_warn, devpath, usbdevice::fwversion, gid, INDEX_OF, keyboard, usbdevice::pollrate, usbdevice::product, S_GID_READ, and usbdevice::vendor.
Referenced by _mkdevpath(), and fwupdate().
                           {
    int index = INDEX_OF(kb, keyboard);
    char fwpath[strlen(devpath) + 12];
    snprintf(fwpath, sizeof(fwpath), "%s%d/fwversion", devpath, index);
    FILE* fwfile = fopen(fwpath, "w");
    if(fwfile){
        fprintf(fwfile, "%04x:0x%04x:0x%04x", kb->fwversion, kb->vendor, kb->product);
        fputc('\n', fwfile);
        fclose(fwfile);
        chmod(fwpath, S_GID_READ);
        if(gid >= 0)
            chown(fwpath, 0, gid);
    } else {
        ckb_warn("Unable to create %s: %s\n", fwpath, strerror(errno));
        remove(fwpath);
        return -1;
    }
    char ppath[strlen(devpath) + 11];
    snprintf(ppath, sizeof(ppath), "%s%d/pollrate", devpath, index);
    FILE* pfile = fopen(ppath, "w");
    if(pfile){
        fprintf(pfile, "%d ms", kb->pollrate);
        fputc('\n', pfile);
        fclose(pfile);
        chmod(ppath, S_GID_READ);
        if(gid >= 0)
            chown(ppath, 0, gid);
    } else {
        ckb_warn("Unable to create %s: %s\n", fwpath, strerror(errno));
        remove(ppath);
        return -2;
    }
    return 0;
}
int mknotifynode (usbdevice *kb, intnotify)
Definition at line 108 of file devnode.c.
References _mknotifynode(), euid_guard_start, and euid_guard_stop.
Referenced by readcmd().
                                           {
    euid_guard_start;
    int res = _mknotifynode(kb, notify);
    euid_guard_stop;
    return res;
}
unsigned readlines (intfd, readlines_ctxctx, const char **input)
Definition at line 353 of file devnode.c.
References _readlines_ctx::buffer, _readlines_ctx::buffersize, ckb_warn, _readlines_ctx::leftover, _readlines_ctx::leftoverlen, and MAX_BUFFER.
Referenced by devmain().
                                                                 {
    // Move any data left over from a previous read to the start of the buffer
    char* buffer = ctx->buffer;
    int buffersize = ctx->buffersize;
    int leftover = ctx->leftover, leftoverlen = ctx->leftoverlen;
    memcpy(buffer, buffer + leftover, leftoverlen);
    // Read data from the file
    ssize_t length = read(fd, buffer + leftoverlen, buffersize - leftoverlen);
    length = (length < 0 ? 0 : length) + leftoverlen;
    leftover = ctx->leftover = leftoverlen = ctx->leftoverlen = 0;
    if(length <= 0){
        *input = 0;
        return 0;
    }
    // Continue buffering until all available input is read or there's no room left
    while(length == buffersize){
        if(buffersize == MAX_BUFFER)
            break;
        int oldsize = buffersize;
        buffersize += 4096;
        ctx->buffersize = buffersize;
        buffer = ctx->buffer = realloc(buffer, buffersize + 1);
        ssize_t length2 = read(fd, buffer + oldsize, buffersize - oldsize);
        if(length2 <= 0)
            break;
        length += length2;
    }
    buffer[length] = 0;
    // Input should be issued one line at a time and should end with a newline.
    char* lastline = memrchr(buffer, '\n', length);
    if(lastline == buffer + length - 1){
        // If the buffer ends in a newline, process the whole string
        *input = buffer;
        return length;
    } else if(lastline){
        // Otherwise, chop off the last line but process everything else
        *lastline = 0;
        leftover = ctx->leftover = lastline + 1 - buffer;
        leftoverlen = ctx->leftoverlen = length - leftover;
        *input = buffer;
        return leftover - 1;
    } else {
        // If a newline wasn't found at all, process the whole buffer next time
        *input = 0;
        if(length == MAX_BUFFER){
            // Unless the buffer is completely full, in which case discard it
            ckb_warn("Too much input (1MB). Dropping.\n");
            return 0;
        }
        leftoverlen = ctx->leftoverlen = length;
        return 0;
    }
}
void readlines_ctx_free (readlines_ctxctx)
Definition at line 348 of file devnode.c.
References _readlines_ctx::buffer.
Referenced by devmain().
                                          {
    free(ctx->buffer);
    free(ctx);
}
void readlines_ctx_init (readlines_ctx *ctx)
Definition at line 341 of file devnode.c.
Referenced by devmain().
                                           {
    // Allocate buffers to store data
    *ctx = calloc(1, sizeof(struct _readlines_ctx));
    int buffersize = (*ctx)->buffersize = 4095;
    (*ctx)->buffer = malloc(buffersize + 1);
}
int rmdevpath (usbdevice *kb)
Definition at line 275 of file devnode.c.
References _rmnotifynode(), ckb_info, ckb_warn, devpath, euid_guard_start, euid_guard_stop, INDEX_OF, usbdevice::infifo, keyboard, OUTFIFO_MAX, and rm_recursive().
Referenced by closeusb(), and quitWithLock().
                            {
    euid_guard_start;
    int index = INDEX_OF(kb, keyboard);
    if(kb->infifo != 0){
#ifdef OS_LINUX
        write(kb->infifo - 1, "\n", 1); // hack to prevent the FIFO thread from perma-blocking
#endif
        close(kb->infifo - 1);
        kb->infifo = 0;
    }
    for(int i = 0; i < OUTFIFO_MAX; i++)
        _rmnotifynode(kb, i);
    char path[strlen(devpath) + 2];
    snprintf(path, sizeof(path), "%s%d", devpath, index);
    if(rm_recursive(path) != 0 && errno != ENOENT){
        ckb_warn("Unable to delete %s: %s\n", path, strerror(errno));
        euid_guard_stop;
        return -1;
    }
    ckb_info("Removed device path %s\n", path);
    euid_guard_stop;
    return 0;
}
int rmnotifynode (usbdevice *kb, intnotify)
Definition at line 129 of file devnode.c.
References _rmnotifynode(), euid_guard_start, and euid_guard_stop.
Referenced by readcmd().
                                           {
    euid_guard_start;
    int res = _rmnotifynode(kb, notify);
    euid_guard_stop;
    return res;
}
void updateconnected ()
Definition at line 81 of file devnode.c.
References _updateconnected(), euid_guard_start, and euid_guard_stop.
Referenced by _setupusb(), and closeusb().
                      {
    euid_guard_start;
    _updateconnected();
    euid_guard_stop;
}
Variable Documentation
const char* const devpath
Definition at line 8 of file devnode.h.
long gid
Definition at line 16 of file devnode.c.
Referenced by _mkdevpath(), _mknotifynode(), _updateconnected(), main(), and mkfwnode().
Author
Generated automatically by Doxygen for ckb-next from the source code.