KbLight
NAME
KbLight -
SYNOPSIS
#include <src/ckb/kblight.h>
Inherits QObject.
Public Types
typedef QList< KbAnim * > AnimList
Signals
void didLoad ()
void updated ()
void frameDisplayed (const ColorMap &animatedColors, const QSet< QString > &indicatorList)
Public Member Functions
KbLight (KbMode *parent, const KeyMap &keyMap)
KbLight (KbMode *parent, const KeyMap &keyMap, const KbLight &other)
~KbLight ()
const KeyMap & map ()
void map (const KeyMap &map)
const QColorMap & colorMap ()
void color (const QString &key, const QColor &newColor)
void color (const QColor &newColor)
int dimming ()
void dimming (int newDimming)
KbAnim * addAnim (const AnimScript *base, const QStringList &keys, const QString &name, const QMap< QString, QVariant > &preset)
KbAnim * duplicateAnim (KbAnim *oldAnim)
const AnimList & animList ()
void animList (const AnimList &newAnimList)
KbAnim * findAnim (const QUuid &guid) const
int findAnimIdx (const QUuid &guid) const
void previewAnim (const AnimScript *base, const QStringList &keys, const QMap< QString, QVariant > &preset)
void stopPreview ()
void restartAnimation ()
void animKeypress (const QString &key, bool down)
void open ()
bool isStarted ()
void close ()
void resetIndicators ()
void setIndicator (const char *name, QRgb argb)
void frameUpdate (QFile &cmd, bool monochrome=false)
void base (QFile &cmd, bool ignoreDim=false, bool monochrome=false)
void load (CkbSettings &settings)
void save (CkbSettings &settings)
bool needsSave () const
Static Public Member Functions
static int shareDimming ()
static void shareDimming (int newShareDimming)
Static Public Attributes
static const int MAX_DIM = 3
Private Member Functions
void rebuildBaseMap ()
void printRGB (QFile &cmd, const ColorMap &animMap)
Private Attributes
AnimList _animList
KbAnim * _previewAnim
KeyMap _map
QColorMap _qColorMap
ColorMap _colorMap
ColorMap _animMap
ColorMap _indicatorMap
QSet< QString > _indicatorList
quint64 lastFrameSignal
int _dimming
bool _start
bool _needsSave
bool _needsMapRefresh
Detailed Description
Definition at line 17 of file kblight.h.
Member Typedef Documentation
typedef QList<KbAnim*> KbLight::AnimList
Definition at line 46 of file kblight.h.
Constructor & Destructor Documentation
KbLight::KbLight (KbMode *parent, const KeyMap &keyMap)
Definition at line 10 of file kblight.cpp.
References map().
                                                     :
    QObject(parent), _previewAnim(0), lastFrameSignal(0), _dimming(0), _start(false), _needsSave(true), _needsMapRefresh(true)
{
    map(keyMap);
}
KbLight::KbLight (KbMode *parent, const KeyMap &keyMap, const KbLight &other)
Definition at line 16 of file kblight.cpp.
References _animList, and map().
                                                                           :
    QObject(parent), _previewAnim(0), _map(other._map), _qColorMap(other._qColorMap), lastFrameSignal(0), _dimming(other._dimming), _start(false), _needsSave(true), _needsMapRefresh(true)
{
    map(keyMap);
    // Duplicate animations
    foreach(KbAnim* animation, other._animList)
        _animList.append(new KbAnim(this, keyMap, *animation));
}
KbLight::~KbLight ()
Definition at line 45 of file kblight.cpp.
References activeLights.
                 {
    activeLights.remove(this);
}
Member Function Documentation
KbAnim * KbLight::addAnim (const AnimScript *base, const QStringList &keys, const QString &name, const QMap< QString, QVariant > &preset)
Definition at line 100 of file kblight.cpp.
References _animList, _map, _needsSave, _start, anim, KbAnim::commitParams(), KbAnim::parameter(), KbAnim::stop(), stopPreview(), and KbAnim::trigger().
Referenced by KbAnimWidget::addAnim().
                                                                                                                                   {
    // Stop and restart all existing animations
    stopPreview();
    quint64 timestamp = QDateTime::currentMSecsSinceEpoch();
    foreach(KbAnim* anim, _animList){
        anim->stop();
        anim->trigger(timestamp);
    }
    // Load the new animation and set preset parameters
    KbAnim* anim = new KbAnim(this, _map, name, keys, base);
    QMapIterator<QString, QVariant> i(preset);
    while(i.hasNext()){
        i.next();
        anim->parameter(i.key(), i.value());
    }
    anim->commitParams();
    // Add the animation and start it
    _animList.append(anim);
    anim->trigger(timestamp);
    _start = true;
    _needsSave = true;
    return anim;
}
void KbLight::animKeypress (const QString &key, booldown)
Definition at line 189 of file kblight.cpp.
References _animList, _previewAnim, anim, KbAnim::keypress(), and KbAnim::keys().
Referenced by Kb::readNotify().
                                                       {
    foreach(KbAnim* anim, _animList){
        if(anim->keys().contains(key))
            anim->keypress(key, down, QDateTime::currentMSecsSinceEpoch());
    }
    if(_previewAnim){
        if(_previewAnim->keys().contains(key))
            _previewAnim->keypress(key, down, QDateTime::currentMSecsSinceEpoch());
    }
}
const AnimList& KbLight::animList () [inline]
Definition at line 49 of file kblight.h.
References _animList.
Referenced by RebindWidget::applyChanges(), KbAnimWidget::duplicateAnim(), KbMode::newId(), KbAnimWidget::on_deleteButton_clicked(), KbAnimWidget::refreshList(), KbAnimWidget::reorderAnims(), and RebindWidget::setSelection().
{ return _animList; }
void KbLight::animList (const AnimList &newAnimList) [inline]
Definition at line 50 of file kblight.h.
References _animList, and _needsSave.
{ _needsSave = true; _animList = newAnimList; }
void KbLight::base (QFile &cmd, boolignoreDim = false, boolmonochrome = false)
Definition at line 371 of file kblight.cpp.
References _animMap, _colorMap, _dimming, close(), ColorMap::colorForName(), ColorMap::colors(), ColorMap::count(), MAX_DIM, monoRgb(), printRGB(), and rebuildBaseMap().
Referenced by Kb::hwSave().
                                                             {
    close();
    if(_dimming == MAX_DIM && !ignoreDim){
        cmd.write(QString().sprintf("rgb 000000").toLatin1());
        return;
    }
    // Set just the background color, ignoring any animation
    rebuildBaseMap();
    _animMap = _colorMap;
    // If monochrome is active, create grayscale
    if(monochrome){
        int count = _animMap.count();
        QRgb* colors = _animMap.colors();
        for(int i = 0; i < count; i++){
            QRgb& rgb = colors[i];
            rgb = monoRgb(qRed(rgb), qGreen(rgb), qBlue(rgb));
        }
    }
    // Set a few indicators to black as the hardware handles them differently
    QRgb* mr = _animMap.colorForName("mr"), *m1 = _animMap.colorForName("m1"), *m2 = _animMap.colorForName("m2"), *m3 = _animMap.colorForName("m3"), *lock = _animMap.colorForName("lock");
    if(mr) *mr = 0;
    if(m1) *m1 = 0;
    if(m2) *m2 = 0;
    if(m3) *m3 = 0;
    if(lock) *lock = 0;
    // Send to driver
    cmd.write("rgb");
    printRGB(cmd, _animMap);
}
void KbLight::close ()
Definition at line 215 of file kblight.cpp.
References _animList, _start, activeLights, anim, KbAnim::stop(), and stopPreview().
Referenced by base(), Kb::frameUpdate(), Kb::hwSave(), and Kb::updateLayout().
                   {
    activeLights.remove(this);
    foreach(KbAnim* anim, _animList)
        anim->stop();
    stopPreview();
    _start = false;
}
void KbLight::color (const QString &key, const QColor &newColor)
Definition at line 49 of file kblight.cpp.
References _colorMap, _needsMapRefresh, _needsSave, _qColorMap, and ColorMap::colorForName().
Referenced by KbLightWidget::changeColor(), load(), printRGB(), Kb::readNotify(), rebuildBaseMap(), and KbLightWidget::toggleSidelight().
                                                             {
    QRgb newRgb = newColor.rgb();
    _qColorMap[key] = newRgb;
    _needsSave = true;
    if(!_needsMapRefresh){
        // Update flat map if we're not scheduled to rebuild it
        QByteArray rawName = key.toLatin1();
        QRgb* rawRgb = _colorMap.colorForName(rawName.data());
        if(rawRgb)
            *rawRgb = newRgb;
    }
}
void KbLight::color (const QColor &newColor)
Definition at line 62 of file kblight.cpp.
References _colorMap, _needsMapRefresh, _needsSave, _qColorMap, ColorMap::colors(), and ColorMap::count().
                                         {
    QRgb newRgb = newColor.rgb();
    QMutableColorMapIterator i(_qColorMap);
    while(i.hasNext()){
        i.next();
        i.value() = newRgb;
    }
    _needsSave = true;
    // Reset flat map
    _needsMapRefresh = false;
    int mapCount = _colorMap.count();
    QRgb* flat = _colorMap.colors();
    for(int i = 0; i < mapCount; i++)
        flat[i] = mapCount;
}
const QColorMap& KbLight::colorMap () [inline]
Definition at line 31 of file kblight.h.
References _qColorMap.
Referenced by KbLightWidget::changeColor(), KbLightWidget::newSelection(), KbLightWidget::toggleSidelight(), and KbLightWidget::updateLight().
{ return _qColorMap; }
void KbLight::didLoad () [signal]
Definition at line 162 of file moc_kblight.cpp.
Referenced by load().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
int KbLight::dimming () [inline]
Definition at line 39 of file kblight.h.
References _dimming.
Referenced by KeyAction::keyEvent(), KbLightWidget::on_brightnessBox_activated(), open(), shareDimming(), and KbLightWidget::updateLight().
{ return _dimming; }
void KbLight::dimming (intnewDimming)
Definition at line 92 of file kblight.cpp.
References _dimming, _needsSave, _shareDimming, shareDimming(), and updated().
                                   {
    if(_shareDimming != -1)
        shareDimming(newDimming);
    _needsSave = true;
    _dimming = newDimming;
    emit updated();
}
KbAnim * KbLight::duplicateAnim (KbAnim *oldAnim)
Definition at line 148 of file kblight.cpp.
References _animList, _map, _needsSave, _start, anim, KbAnim::newId(), KbAnim::stop(), and KbAnim::trigger().
Referenced by KbAnimWidget::duplicateAnim().
                                             {
    // Stop and restart all existing animations
    quint64 timestamp = QDateTime::currentMSecsSinceEpoch();
    foreach(KbAnim* anim, _animList){
        anim->stop();
        anim->trigger(timestamp);
    }
    // Same as addAnim, just duplicate the existing one
    KbAnim* anim = new KbAnim(this, _map, *oldAnim);
    anim->newId();
    int index = _animList.indexOf(oldAnim);
    if(index < 0)
        _animList.append(anim);
    else
        _animList.insert(index + 1, anim);
    anim->trigger(timestamp);
    _start = true;
    _needsSave = true;
    return anim;
}
KbAnim* KbLight::findAnim (const QUuid &guid) const [inline]
Definition at line 51 of file kblight.h.
References _animList, anim, and KbAnim::guid().
Referenced by findAnimIdx(), and KeyAction::keyEvent().
{ foreach(KbAnim* anim, _animList) { if(anim->guid() == guid) return anim; } return 0; }
int KbLight::findAnimIdx (const QUuid &guid) const [inline]
Definition at line 52 of file kblight.h.
References _animList, and findAnim().
Referenced by RebindWidget::setSelection().
{ return _animList.indexOf(findAnim(guid)); }
void KbLight::frameDisplayed (const ColorMap &animatedColors, const QSet< QString > &indicatorList) [signal]
Definition at line 174 of file moc_kblight.cpp.
Referenced by frameUpdate().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 2, _a);
}
void KbLight::frameUpdate (QFile &cmd, boolmonochrome = false)
Definition at line 296 of file kblight.cpp.
References _animList, _animMap, _colorMap, _dimming, _indicatorList, _indicatorMap, _previewAnim, anim, KbAnim::blend(), ColorMap::colors(), ColorMap::count(), frameDisplayed(), lastFrameSignal, lToS(), monoRgb(), printRGB(), rebuildBaseMap(), and sToL().
Referenced by Kb::frameUpdate().
                                                    {
    rebuildBaseMap();
    _animMap = _colorMap;
    // Advance animations
    quint64 timestamp = QDateTime::currentMSecsSinceEpoch();
    foreach(KbAnim* anim, _animList)
        anim->blend(_animMap, timestamp);
    if(_previewAnim)
        _previewAnim->blend(_animMap, timestamp);
    int count = _animMap.count();
    QRgb* colors = _animMap.colors();
    // Apply active indicators and/or perform monochrome conversion
    if(monochrome || !_indicatorList.isEmpty()){
        QRgb* indicators = _indicatorMap.colors();
        for(int i = 0; i < count; i++){
            QRgb& rgb = colors[i];
            float r = qRed(rgb);
            float g = qGreen(rgb);
            float b = qBlue(rgb);
            // Apply indicators
            QRgb rgb2 = indicators[i];
            if(qAlpha(rgb2) != 0){
                float r2 = qRed(rgb2);
                float g2 = qGreen(rgb2);
                float b2 = qBlue(rgb2);
                float a2 = qAlpha(rgb2) / 255.f;
                r = round(r2 * a2 + r * (1.f - a2));
                g = round(g2 * a2 + g * (1.f - a2));
                b = round(b2 * a2 + b * (1.f - a2));
            }
            // If monochrome mode is active, average the channels to get a grayscale image
            if(monochrome)
                rgb = monoRgb(r, g, b);
            else
                rgb = qRgb(r, g, b);
        }
    }
    // Emit signals for the animation (only do this every 50ms - it can cause a lot of CPU usage)
    if(timestamp >= lastFrameSignal + 50){
        emit frameDisplayed(_animMap, _indicatorList);
        lastFrameSignal = timestamp;
    }
    // If brightness is at 0%, turn off lighting entirely
    if(_dimming == 3){
        cmd.write("rgb 000000");
        return;
    }
    float light = (3 - _dimming) / 3.f;
    // Apply global dimming
    if(light != 1.f || monochrome){
        for(int i = 0; i < count; i++){
            QRgb& rgb = colors[i];
            // Like the monochrome conversion, this should be done in a linear colorspace
            float r = sToL(qRed(rgb));
            float g = sToL(qGreen(rgb));
            float b = sToL(qBlue(rgb));
            r *= light;
            g *= light;
            b *= light;
            r = round(lToS(r));
            g = round(lToS(g));
            b = round(lToS(b));
            rgb = qRgb(r, g, b);
        }
    }
    // Apply light
    cmd.write("rgb");
    printRGB(cmd, _animMap);
}
bool KbLight::isStarted ()
Definition at line 169 of file kblight.cpp.
References _animList, _start, and KbAnim::isRunning().
Referenced by Kb::frameUpdate().
                       {
    if(!_start)
        return false;
    foreach(KbAnim* animation, _animList){
        if(!animation->isRunning())
            return false;
    }
    return true;
}
void KbLight::load (CkbSettings &settings)
Definition at line 401 of file kblight.cpp.
References _animList, _dimming, _map, _needsMapRefresh, _needsSave, _qColorMap, anim, CkbSettings::childKeys(), color(), didLoad(), KeyMap::fromName(), KeyMap::fromStorage(), map(), MAX_DIM, and CkbSettings::value().
Referenced by KbMode::KbMode().
                                       {
    // Load light settings
    _needsSave = false;
    SGroup group(settings, "Lighting");
    KeyMap currentMap = _map;
    _map = KeyMap::fromName(settings.value("KeyMap").toString());
    _dimming = settings.value("Brightness").toUInt();
    if(_dimming > MAX_DIM)
        _dimming = MAX_DIM;
    // Load RGB settings
    bool useReal = settings.value("UseRealNames").toBool();
    {
        SGroup group(settings, "Keys");
        foreach(QString key, settings.childKeys()){
            QString name = key.toLower();
            if(!useReal)
                name = _map.fromStorage(name);
            QColor color = settings.value(key).toString();
            if(!color.isValid())
                color = QColor(255, 255, 255);
            _qColorMap[name] = color.rgb();
        }
        _needsMapRefresh = true;
    }
    // Load animations
    foreach(KbAnim* anim, _animList)
        anim->deleteLater();
    _animList.clear();
    {
        SGroup group(settings, "Animations");
        foreach(QString anim, settings.value("List").toStringList()){
            QUuid id = anim;
            _animList.append(new KbAnim(this, _map, id, settings));
        }
    }
    emit didLoad();
    map(currentMap);
}
const KeyMap& KbLight::map () [inline]
Definition at line 28 of file kblight.h.
References _map.
Referenced by KbLight(), KbMode::keyMap(), load(), map(), KbLightWidget::newSelection(), KbAnimWidget::on_keyButton_clicked(), and KbLightWidget::updateLight().
{ return _map; }
void KbLight::map (const KeyMap &map)
Definition at line 25 of file kblight.cpp.
References _animList, _animMap, _colorMap, _indicatorMap, _map, _needsMapRefresh, _needsSave, _qColorMap, anim, ColorMap::init(), map(), KbAnim::map(), and updated().
                                  {
    // If any of the keys are missing from the color map, set them to white
    QHashIterator<QString, Key> i(map);
    while(i.hasNext()){
        i.next();
        const QString& key = i.key();
        if(!_qColorMap.contains(key))
            _qColorMap[key] = 0xFFFFFFFF;
    }
    // Set the new map
    _map = map;
    foreach(KbAnim* anim, _animList)
        anim->map(map);
    _colorMap.init(_map);
    _animMap.init(_map);
    _indicatorMap.init(_map);
    _needsSave = _needsMapRefresh = true;
    emit updated();
}
bool KbLight::needsSave () const
Definition at line 467 of file kblight.cpp.
References _animList, _needsSave, anim, and KbAnim::needsSave().
Referenced by KbMode::needsSave().
                              {
    if(_needsSave)
        return true;
    foreach(KbAnim* anim, _animList){
        if(anim->needsSave())
            return true;
    }
    return false;
}
void KbLight::open ()
Definition at line 200 of file kblight.cpp.
References _animList, _dimming, _previewAnim, _shareDimming, _start, activeLights, anim, dimming(), and KbAnim::trigger().
Referenced by Kb::frameUpdate().
                  {
    // Apply shared dimming if needed
    if(_shareDimming != -1 && _shareDimming != _dimming)
        dimming(_shareDimming);
    activeLights.insert(this);
    if(_start)
        return;
    quint64 timestamp = QDateTime::currentMSecsSinceEpoch();
    foreach(KbAnim* anim, _animList)
        anim->trigger(timestamp);
    if(_previewAnim)
        _previewAnim->trigger(timestamp);
    _start = true;
}
void KbLight::previewAnim (const AnimScript *base, const QStringList &keys, const QMap< QString, QVariant > &preset)
Definition at line 124 of file kblight.cpp.
References _map, _previewAnim, _start, anim, KbAnim::commitParams(), KbAnim::parameter(), KbAnim::reInit(), stopPreview(), and KbAnim::trigger().
Referenced by AnimAddDialog::on_presetBox_activated().
                                                                                                               {
    if(_previewAnim)
        stopPreview();
    quint64 timestamp = QDateTime::currentMSecsSinceEpoch();
    // Load the new animation and set preset parameters
    KbAnim* anim = new KbAnim(this, _map, "", keys, base);
    QMapIterator<QString, QVariant> i(preset);
    while(i.hasNext()){
        i.next();
        anim->parameter(i.key(), i.value());
    }
    anim->commitParams();
    anim->reInit();
    // Add the animation and start it
    _previewAnim = anim;
    anim->trigger(timestamp);
    _start = true;
}
void KbLight::printRGB (QFile &cmd, const ColorMap &animMap) [private]
Definition at line 223 of file kblight.cpp.
References color(), ColorMap::colors(), ColorMap::count(), and ColorMap::keyNames().
Referenced by base(), and frameUpdate().
                                                         {
    int count = animMap.count();
    const char* const* names = animMap.keyNames();
    const QRgb* colors = animMap.colors();
    // Print each color and the corresponding RGB value
    for(int i = 0; i < count; i++){
        cmd.write(" ");
        cmd.write(names[i]);
        char output[8];
        QRgb color = colors[i];
        snprintf(output, sizeof(output), ":%02x%02x%02x", qRed(color), qGreen(color), qBlue(color));
        cmd.write(output);
    }
}
void KbLight::rebuildBaseMap () [private]
Definition at line 238 of file kblight.cpp.
References _colorMap, _needsMapRefresh, _qColorMap, color(), and ColorMap::colorForName().
Referenced by base(), and frameUpdate().
                            {
    if(!_needsMapRefresh)
        return;
    _needsMapRefresh = false;
    // Copy RGB values from QColorMap to ColorMap
    QColorMapIterator i(_qColorMap);
    while(i.hasNext()){
        i.next();
        QByteArray rawName = i.key().toLatin1();
        QRgb color = i.value();
        QRgb* rawColor = _colorMap.colorForName(rawName.data());
        if(rawColor)
            *rawColor = color;
    }
}
void KbLight::resetIndicators ()
Definition at line 254 of file kblight.cpp.
References _indicatorList, _indicatorMap, and ColorMap::clear().
Referenced by KbPerf::applyIndicators().
                             {
    _indicatorMap.clear();
    _indicatorList.clear();
}
void KbLight::restartAnimation ()
Definition at line 179 of file kblight.cpp.
References _animList, _start, anim, KbAnim::stop(), stopPreview(), and KbAnim::trigger().
Referenced by KbLightWidget::on_animButton_clicked(), KbAnimWidget::on_deleteButton_clicked(), KbAnimWidget::on_keyButton_clicked(), and KbAnimWidget::on_propertyButton_clicked().
                              {
    quint64 timestamp = QDateTime::currentMSecsSinceEpoch();
    foreach(KbAnim* anim, _animList){
        anim->stop();
        anim->trigger(timestamp);
    }
    stopPreview();
    _start = true;
}
void KbLight::save (CkbSettings &settings)
Definition at line 440 of file kblight.cpp.
References _animList, _dimming, _map, _needsSave, _qColorMap, anim, KbAnim::guid(), KeyMap::name(), KbAnim::save(), and CkbSettings::setValue().
Referenced by KbMode::save().
                                       {
    _needsSave = false;
    SGroup group(settings, "Lighting");
    settings.setValue("KeyMap", _map.name());
    settings.setValue("Brightness", _dimming);
    settings.setValue("UseRealNames", true);
    {
        // Save RGB settings
        SGroup group(settings, "Keys");
        QMutableColorMapIterator i(_qColorMap);
        while(i.hasNext()){
            i.next();
            settings.setValue(i.key(), QColor(i.value()).name());
        }
    }
    {
        // Save animations
        SGroup group(settings, "Animations");
        QStringList aList;
        foreach(KbAnim* anim, _animList){
            aList << anim->guid().toString().toUpper();
            anim->save(settings);
        }
        settings.setValue("List", aList);
    }
}
void KbLight::setIndicator (const char *name, QRgbargb)
Definition at line 259 of file kblight.cpp.
References _indicatorList, _indicatorMap, and ColorMap::colorForName().
Referenced by KbPerf::lightIndicator().
                                                     {
    QRgb* dest = _indicatorMap.colorForName(name);
    if(dest){
        *dest = argb;
        _indicatorList.insert(name);
    }
}
int KbLight::shareDimming () [static]
Definition at line 78 of file kblight.cpp.
References _shareDimming.
Referenced by dimming(), ExtraSettingsWidget::ExtraSettingsWidget(), ExtraSettingsWidget::on_brightnessBox_clicked(), and ExtraSettingsWidget::pollUpdates().
                         {
    return _shareDimming;
}
void KbLight::shareDimming (intnewShareDimming) [static]
Definition at line 82 of file kblight.cpp.
References _shareDimming, activeLights, and dimming().
                                             {
    if(_shareDimming == newShareDimming)
        return;
    _shareDimming = newShareDimming;
    if(newShareDimming != -1){
        foreach(KbLight* light, activeLights)
            light->dimming(newShareDimming);
    }
}
void KbLight::stopPreview ()
Definition at line 143 of file kblight.cpp.
References _previewAnim.
Referenced by addAnim(), close(), AnimAddDialog::on_previewBox_clicked(), previewAnim(), restartAnimation(), and AnimAddDialog::~AnimAddDialog().
                         {
    delete _previewAnim;
    _previewAnim = 0;
}
void KbLight::updated () [signal]
Definition at line 168 of file moc_kblight.cpp.
Referenced by dimming(), and map().
{
    QMetaObject::activate(this, &staticMetaObject, 1, Q_NULLPTR);
}
Field Documentation
AnimList KbLight::_animList [private]
Definition at line 89 of file kblight.h.
Referenced by addAnim(), animKeypress(), animList(), close(), duplicateAnim(), findAnim(), findAnimIdx(), frameUpdate(), isStarted(), KbLight(), load(), map(), needsSave(), open(), restartAnimation(), and save().
ColorMap KbLight::_animMap [private]
Definition at line 93 of file kblight.h.
Referenced by base(), frameUpdate(), and map().
ColorMap KbLight::_colorMap [private]
Definition at line 93 of file kblight.h.
Referenced by base(), color(), frameUpdate(), map(), and rebuildBaseMap().
int KbLight::_dimming [private]
Definition at line 96 of file kblight.h.
Referenced by base(), dimming(), frameUpdate(), load(), open(), and save().
QSet<QString> KbLight::_indicatorList [private]
Definition at line 94 of file kblight.h.
Referenced by frameUpdate(), resetIndicators(), and setIndicator().
ColorMap KbLight::_indicatorMap [private]
Definition at line 93 of file kblight.h.
Referenced by frameUpdate(), map(), resetIndicators(), and setIndicator().
KeyMap KbLight::_map [private]
Definition at line 91 of file kblight.h.
Referenced by addAnim(), duplicateAnim(), load(), map(), previewAnim(), and save().
bool KbLight::_needsMapRefresh [private]
Definition at line 98 of file kblight.h.
Referenced by color(), load(), map(), and rebuildBaseMap().
bool KbLight::_needsSave [private]
Definition at line 98 of file kblight.h.
Referenced by addAnim(), animList(), color(), dimming(), duplicateAnim(), load(), map(), needsSave(), and save().
KbAnim* KbLight::_previewAnim [private]
Definition at line 90 of file kblight.h.
Referenced by animKeypress(), frameUpdate(), open(), previewAnim(), and stopPreview().
QColorMap KbLight::_qColorMap [private]
Definition at line 92 of file kblight.h.
Referenced by color(), colorMap(), load(), map(), rebuildBaseMap(), and save().
bool KbLight::_start [private]
Definition at line 97 of file kblight.h.
Referenced by addAnim(), close(), duplicateAnim(), isStarted(), open(), previewAnim(), and restartAnimation().
quint64 KbLight::lastFrameSignal [private]
Definition at line 95 of file kblight.h.
Referenced by frameUpdate().
const int KbLight::MAX_DIM = 3 [static]
Definition at line 38 of file kblight.h.
Referenced by base(), ExtraSettingsWidget::ExtraSettingsWidget(), KeyAction::keyEvent(), and load().
Author
Generated automatically by Doxygen for ckb-next from the source code.