.TH "src/ckb/release/moc_mperfwidget.cpp" 3 "Mon Jun 5 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2.thread" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/release/moc_mperfwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mperfwidget\&.h'\fP
.br
\fC#include <QtCore/qbytearray\&.h>\fP
.br
\fC#include <QtCore/qmetatype\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqt_meta_stringdata_MPerfWidget_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx, ofs, len)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const 
.br
\fBqt_meta_stringdata_MPerfWidget_t\fP \fBqt_meta_stringdata_MPerfWidget\fP"
.br
.ti -1c
.RI "static const uint \fBqt_meta_data_MPerfWidget\fP []"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct qt_meta_stringdata_MPerfWidget_t"
.PP 
Definition at line 21 of file moc_mperfwidget\&.cpp\&.
.PP
\fBData Fields:\fP
.RS 4
QByteArrayData \fIdata[18]\fP 
.br
.PP
char \fIstringdata0[249]\fP 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
.fi
.PP
Definition at line 25 of file moc_mperfwidget\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const uint qt_meta_data_MPerfWidget[]\fC [static]\fP"

.PP
Definition at line 62 of file moc_mperfwidget\&.cpp\&.
.SS "const \fBqt_meta_stringdata_MPerfWidget_t\fP qt_meta_stringdata_MPerfWidget\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 11 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  0    -  0  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 12 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  12    -  1  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 0 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  25    -  2  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 5 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  26    -  3  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 12 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  32    -  4  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 12 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  45    -  5  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 12 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  58    -  6  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 11 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  71    -  7  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 11 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  83    -  8  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 13 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  95    -  9  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 16 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  109    -  10  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 7 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  126    -  11  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 19 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  134    -  12  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 19 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  154    -  13  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 23 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  174    -  14  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 21 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  198    -  15  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 23 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  220    -  16  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 4 ,   qptrdiff(offsetof(qt_meta_stringdata_MPerfWidget_t, stringdata0) +  244    -  17  * sizeof(QByteArrayData))   ) 

    },
    "MPerfWidget\0colorClicked\0\0index\0"
    "colorChanged\0sliderXMoved\0sliderYMoved\0"
    "boxXChanged\0boxYChanged\0enableChanged\0"
    "on_xyBox_clicked\0checked\0on_indicBox_clicked\0"
    "on_aSnapBox_clicked\0on_lHeightBox_activated\0"
    "on_copyButton_clicked\0on_spinBox_valueChanged\0"
    "arg1"
}
.fi
.PP
Definition at line 30 of file moc_mperfwidget\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
