MPerfWidget
NAME
MPerfWidget -
SYNOPSIS
#include <src/ckb/mperfwidget.h>
Inherits QWidget.
Data Structures
struct DpiUi
Public Member Functions
MPerfWidget (QWidget *parent=0)
~MPerfWidget ()
void setPerf (KbPerf *newPerf, KbProfile *newProfile)
Static Public Attributes
static const int DPI_COUNT = KbPerf::DPI_COUNT
static const int DPI_MIN = KbPerf::DPI_MIN
static const int DPI_MAX = KbPerf::DPI_MAX
Private Slots
void colorClicked (int index)
void colorChanged (int index)
void sliderXMoved (int index)
void sliderYMoved (int index)
void boxXChanged (int index)
void boxYChanged (int index)
void enableChanged (int index)
void on_xyBox_clicked (bool checked)
void on_indicBox_clicked (bool checked)
void on_aSnapBox_clicked (bool checked)
void on_lHeightBox_activated (int index)
void on_copyButton_clicked ()
void on_spinBox_valueChanged (int arg1)
Private Attributes
Ui::MPerfWidget * ui
KbPerf * perf
KbProfile * profile
DpiUi stages [DPI_COUNT]
bool _xyLink
bool colorLink
QSignalMapper buttonMapper1
QSignalMapper buttonMapper2
QSignalMapper sliderXMapper
QSignalMapper sliderYMapper
QSignalMapper boxXMapper
QSignalMapper boxYMapper
QSignalMapper enableMapper
bool isSetting
Detailed Description
Definition at line 18 of file mperfwidget.h.
Data Structure Documentation
struct MPerfWidget::DpiUi
Definition at line 37 of file mperfwidget.h.
Data Fields:
QCheckBox * enableCheck
ColorButton * indicator
QSpinBox * xBox
QSlider * xSlider
QSpinBox * yBox
QSlider * ySlider
Constructor & Destructor Documentation
MPerfWidget::MPerfWidget (QWidget *parent = 0) [explicit]
Definition at line 8 of file mperfwidget.cpp.
References _xyLink, ColorButton::allowAlpha(), ColorButton::bigIcons(), boxXChanged(), boxXMapper, boxYChanged(), boxYMapper, buttonMapper1, buttonMapper2, colorChanged(), colorClicked(), DPI_COUNT, Ui_MPerfWidget::eBox1, Ui_MPerfWidget::eBox2, Ui_MPerfWidget::eBox3, Ui_MPerfWidget::eBox4, Ui_MPerfWidget::eBox5, enableChanged(), MPerfWidget::DpiUi::enableCheck, enableMapper, Ui_MPerfWidget::iButton0, Ui_MPerfWidget::iButton1, Ui_MPerfWidget::iButton2, Ui_MPerfWidget::iButton3, Ui_MPerfWidget::iButton4, Ui_MPerfWidget::iButton5, Ui_MPerfWidget::iButtonO, MPerfWidget::DpiUi::indicator, ColorButton::setLabel(), Ui_MPerfWidget::setupUi(), sliderXMapper, sliderXMoved(), sliderYMapper, sliderYMoved(), stages, ui, MPerfWidget::DpiUi::xBox, Ui_MPerfWidget::xBox0, Ui_MPerfWidget::xBox1, Ui_MPerfWidget::xBox2, Ui_MPerfWidget::xBox3, Ui_MPerfWidget::xBox4, Ui_MPerfWidget::xBox5, MPerfWidget::DpiUi::xSlider, Ui_MPerfWidget::xSlider0, Ui_MPerfWidget::xSlider1, Ui_MPerfWidget::xSlider2, Ui_MPerfWidget::xSlider3, Ui_MPerfWidget::xSlider4, Ui_MPerfWidget::xSlider5, Ui_MPerfWidget::xyBox, MPerfWidget::DpiUi::yBox, Ui_MPerfWidget::yBox0, Ui_MPerfWidget::yBox1, Ui_MPerfWidget::yBox2, Ui_MPerfWidget::yBox3, Ui_MPerfWidget::yBox4, Ui_MPerfWidget::yBox5, MPerfWidget::DpiUi::ySlider, Ui_MPerfWidget::ySlider0, Ui_MPerfWidget::ySlider1, Ui_MPerfWidget::ySlider2, Ui_MPerfWidget::ySlider3, Ui_MPerfWidget::ySlider4, and Ui_MPerfWidget::ySlider5.
                                        :
    QWidget(parent), ui(new Ui::MPerfWidget), perf(0), profile(0), _xyLink(!CkbSettings::get(xyLinkPath).toBool()), colorLink(false), isSetting(false) {
    ui->setupUi(this);
    ui->xyBox->setChecked(!_xyLink);
    // Set up DPI stages
    stages[0].indicator = ui->iButton0; stages[0].xSlider = ui->xSlider0; stages[0].ySlider = ui->ySlider0; stages[0].xBox = ui->xBox0; stages[0].yBox = ui->yBox0; stages[0].enableCheck = 0;
    stages[1].indicator = ui->iButton1; stages[1].xSlider = ui->xSlider1; stages[1].ySlider = ui->ySlider1; stages[1].xBox = ui->xBox1; stages[1].yBox = ui->yBox1; stages[1].enableCheck = ui->eBox1;
    stages[2].indicator = ui->iButton2; stages[2].xSlider = ui->xSlider2; stages[2].ySlider = ui->ySlider2; stages[2].xBox = ui->xBox2; stages[2].yBox = ui->yBox2; stages[2].enableCheck = ui->eBox2;
    stages[3].indicator = ui->iButton3; stages[3].xSlider = ui->xSlider3; stages[3].ySlider = ui->ySlider3; stages[3].xBox = ui->xBox3; stages[3].yBox = ui->yBox3; stages[3].enableCheck = ui->eBox3;
    stages[4].indicator = ui->iButton4; stages[4].xSlider = ui->xSlider4; stages[4].ySlider = ui->ySlider4; stages[4].xBox = ui->xBox4; stages[4].yBox = ui->yBox4; stages[4].enableCheck = ui->eBox4;
    stages[5].indicator = ui->iButton5; stages[5].xSlider = ui->xSlider5; stages[5].ySlider = ui->ySlider5; stages[5].xBox = ui->xBox5; stages[5].yBox = ui->yBox5; stages[5].enableCheck = ui->eBox5;
    ui->iButtonO->setLabel(false);
    ui->iButtonO->bigIcons(true);
    ui->iButtonO->allowAlpha(true);
    for(int i = 0; i < DPI_COUNT; i++){
        stages[i].indicator->setLabel(false);
        stages[i].indicator->bigIcons(true);
        stages[i].indicator->allowAlpha(true);
        // Map signals
        connect(stages[i].indicator, SIGNAL(clicked(bool)), &buttonMapper1, SLOT(map()));
        connect(stages[i].indicator, SIGNAL(colorChanged(QColor)), &buttonMapper2, SLOT(map()));
        connect(stages[i].xSlider, SIGNAL(valueChanged(int)), &sliderXMapper, SLOT(map()));
        connect(stages[i].ySlider, SIGNAL(valueChanged(int)), &sliderYMapper, SLOT(map()));
        connect(stages[i].xBox, SIGNAL(valueChanged(int)), &boxXMapper, SLOT(map()));
        connect(stages[i].yBox, SIGNAL(valueChanged(int)), &boxYMapper, SLOT(map()));
        if(stages[i].enableCheck)
            // Sniper has no enable
            connect(stages[i].enableCheck, SIGNAL(stateChanged(int)), &enableMapper, SLOT(map()));
        // Set names
        buttonMapper1.setMapping(stages[i].indicator, i);
        buttonMapper2.setMapping(stages[i].indicator, i);
        sliderXMapper.setMapping(stages[i].xSlider, i);
        sliderYMapper.setMapping(stages[i].ySlider, i);
        boxXMapper.setMapping(stages[i].xBox, i);
        boxYMapper.setMapping(stages[i].yBox, i);
        if(stages[i].enableCheck)
            enableMapper.setMapping(stages[i].enableCheck, i);
    }
    // Connect to slots
    connect(&buttonMapper1, SIGNAL(mapped(int)), this, SLOT(colorClicked(int)));
    connect(&buttonMapper2, SIGNAL(mapped(int)), this, SLOT(colorChanged(int)));
    connect(&sliderXMapper, SIGNAL(mapped(int)), this, SLOT(sliderXMoved(int)));
    connect(&sliderYMapper, SIGNAL(mapped(int)), this, SLOT(sliderYMoved(int)));
    connect(&boxXMapper, SIGNAL(mapped(int)), this, SLOT(boxXChanged(int)));
    connect(&boxYMapper, SIGNAL(mapped(int)), this, SLOT(boxYChanged(int)));
    connect(&enableMapper, SIGNAL(mapped(int)), this, SLOT(enableChanged(int)));
}
MPerfWidget::~MPerfWidget ()
Definition at line 56 of file mperfwidget.cpp.
References ui.
                         {
    delete ui;
}
Member Function Documentation
void MPerfWidget::boxXChanged (intindex) [private], [slot]
Definition at line 157 of file mperfwidget.cpp.
References _xyLink, KbPerf::dpi(), dpiLog(), perf, SET_END, SET_START, stages, MPerfWidget::DpiUi::xBox, MPerfWidget::DpiUi::xSlider, and MPerfWidget::DpiUi::yBox.
Referenced by MPerfWidget().
                                      {
    SET_START;
    QSpinBox* box = stages[index].xBox;
    QSlider* slider = stages[index].xSlider;
    int value = box->value();
    slider->setValue(dpiLog(value, slider->minimum(), slider->maximum()));
    if(_xyLink)
        perf->dpi(index, value);
    else
        perf->dpi(index, QPoint(value, perf->dpi(index).y()));
    SET_END;
    if(_xyLink)
        stages[index].yBox->setValue(value);
}
void MPerfWidget::boxYChanged (intindex) [private], [slot]
Definition at line 172 of file mperfwidget.cpp.
References _xyLink, KbPerf::dpi(), dpiLog(), perf, SET_END, SET_START, stages, MPerfWidget::DpiUi::xBox, MPerfWidget::DpiUi::yBox, and MPerfWidget::DpiUi::ySlider.
Referenced by MPerfWidget().
                                      {
    SET_START;
    QSpinBox* box = stages[index].yBox;
    QSlider* slider = stages[index].ySlider;
    int value = box->value();
    slider->setValue(dpiLog(value, slider->minimum(), slider->maximum()));
    if(_xyLink)
        perf->dpi(index, value);
    else
        perf->dpi(index, QPoint(perf->dpi(index).x(), value));
    SET_END;
    if(_xyLink)
        stages[index].xBox->setValue(value);
}
void MPerfWidget::colorChanged (intindex) [private], [slot]
Definition at line 86 of file mperfwidget.cpp.
References ColorButton::color(), colorLink, DPI_COUNT, KbPerf::dpiColor(), Ui_MPerfWidget::iButtonO, MPerfWidget::DpiUi::indicator, KbPerf::OTHER, perf, stages, and ui.
Referenced by MPerfWidget().
                                       {
    QColor color = stages[index].indicator->color();
    if(colorLink){
        // Alt was held down - set all
        for(int i = 0; i < DPI_COUNT; i++){
            stages[i].indicator->color(color);
            perf->dpiColor(i, color);
        }
        ui->iButtonO->color(color);
        perf->dpiColor(KbPerf::OTHER, color);
    } else {
        // Set one
        perf->dpiColor(index, color);
    }
    colorLink = false;
}
void MPerfWidget::colorClicked (intindex) [private], [slot]
Definition at line 81 of file mperfwidget.cpp.
References colorLink.
Referenced by MPerfWidget().
                                       {
    // Set all colors at once if Alt is held down
    colorLink = !!(qApp->keyboardModifiers() & Qt::AltModifier);
}
void MPerfWidget::enableChanged (intindex) [private], [slot]
Definition at line 187 of file mperfwidget.cpp.
References KbPerf::dpiEnabled(), perf, and stages.
Referenced by MPerfWidget().
                                        {
    perf->dpiEnabled(index, stages[index].enableCheck->isChecked());
}
void MPerfWidget::on_aSnapBox_clicked (boolchecked) [private], [slot]
Definition at line 201 of file mperfwidget.cpp.
References KbPerf::angleSnap(), and perf.
                                                 {
    perf->angleSnap(checked);
}
void MPerfWidget::on_copyButton_clicked () [private], [slot]
Definition at line 209 of file mperfwidget.cpp.
References KbProfile::currentMode(), KbProfile::modes(), perf, KbMode::perf(), profile, and ModeSelectDialog::selection().
                                       {
    ModeSelectDialog dialog(this, profile->currentMode(), profile->modes(), "Copy performance settings to:");
    if(dialog.exec() != QDialog::Accepted)
        return;
    QList<KbMode*> selectedModes = dialog.selection();
    foreach(KbMode* mode, selectedModes){
        *mode->perf() = *perf;
    }
}
void MPerfWidget::on_indicBox_clicked (boolchecked) [private], [slot]
Definition at line 197 of file mperfwidget.cpp.
References KbPerf::dpiIndicator(), and perf.
                                                 {
    perf->dpiIndicator(checked);
}
void MPerfWidget::on_lHeightBox_activated (intindex) [private], [slot]
Definition at line 205 of file mperfwidget.cpp.
References KbPerf::liftHeight(), and perf.
                                                  {
    perf->liftHeight((KbPerf::height)(index + 1));
}
void MPerfWidget::on_spinBox_valueChanged (intarg1) [private], [slot]
Definition at line 219 of file mperfwidget.cpp.
References KbPerf::iOpacity(), and perf.
                                                 {
    if(!perf)
        return;
    perf->iOpacity(arg1 / 100.f);
}
void MPerfWidget::on_xyBox_clicked (boolchecked) [private], [slot]
Definition at line 191 of file mperfwidget.cpp.
References _xyLink, CkbSettings::set(), and xyLinkPath.
                                              {
    _xyLink = !checked;
    CkbSettings::set(xyLinkPath, checked);
    // FIXME: update other MPerfWidgets, since this is a global setting
}
void MPerfWidget::setPerf (KbPerf *newPerf, KbProfile *newProfile)
Definition at line 60 of file mperfwidget.cpp.
References _xyLink, KbPerf::angleSnap(), Ui_MPerfWidget::aSnapBox, ColorButton::color(), KbPerf::dpi(), DPI_COUNT, KbPerf::dpiColor(), KbPerf::dpiEnabled(), KbPerf::dpiIndicator(), MPerfWidget::DpiUi::enableCheck, Ui_MPerfWidget::iButtonO, MPerfWidget::DpiUi::indicator, Ui_MPerfWidget::indicBox, KbPerf::iOpacity(), Ui_MPerfWidget::lHeightBox, KbPerf::liftHeight(), KbPerf::OTHER, perf, profile, Ui_MPerfWidget::spinBox, stages, ui, MPerfWidget::DpiUi::xBox, and MPerfWidget::DpiUi::yBox.
Referenced by KbWidget::modeChanged().
                                                               {
    perf = newPerf;
    profile = newProfile;
    ui->spinBox->setValue(round(perf->iOpacity() * 100.f));
    for(int i = 0; i < DPI_COUNT; i++){
        stages[i].indicator->color(perf->dpiColor(i));
        bool oldLink = _xyLink;
        // Don't force X/Y to the same value if they were set differently in the past
        _xyLink = false;
        stages[i].xBox->setValue(perf->dpi(i).x());
        stages[i].yBox->setValue(perf->dpi(i).y());
        _xyLink = oldLink;
        if(stages[i].enableCheck)
            stages[i].enableCheck->setChecked(perf->dpiEnabled(i));
    }
    ui->iButtonO->color(perf->dpiColor(KbPerf::OTHER));
    ui->aSnapBox->setChecked(perf->angleSnap());
    ui->lHeightBox->setCurrentIndex(perf->liftHeight() - 1);
    ui->indicBox->setChecked(perf->dpiIndicator());
}
void MPerfWidget::sliderXMoved (intindex) [private], [slot]
Definition at line 128 of file mperfwidget.cpp.
References _xyLink, KbPerf::dpi(), dpiExp(), dpiRound(), perf, SET_END, SET_START, stages, MPerfWidget::DpiUi::xBox, MPerfWidget::DpiUi::xSlider, and MPerfWidget::DpiUi::ySlider.
Referenced by MPerfWidget().
                                       {
    SET_START;
    QSlider* slider = stages[index].xSlider;
    int value = dpiRound(dpiExp(slider->value(), slider->minimum(), slider->maximum()));
    stages[index].xBox->setValue(value);
    if(_xyLink)
        perf->dpi(index, value);
    else
        perf->dpi(index, QPoint(value, perf->dpi(index).y()));
    SET_END;
    if(_xyLink)
        stages[index].ySlider->setValue(slider->value());
}
void MPerfWidget::sliderYMoved (intindex) [private], [slot]
Definition at line 142 of file mperfwidget.cpp.
References _xyLink, KbPerf::dpi(), dpiExp(), dpiRound(), perf, SET_END, SET_START, stages, ui, Ui_MPerfWidget::xyBox, MPerfWidget::DpiUi::yBox, and MPerfWidget::DpiUi::ySlider.
Referenced by MPerfWidget().
                                       {
    SET_START;
    QSlider* slider = stages[index].ySlider;
    int value = dpiRound(dpiExp(slider->value(), slider->minimum(), slider->maximum()));
    stages[index].yBox->setValue(value);
    if(_xyLink)
        perf->dpi(index, value);
    else
        perf->dpi(index, QPoint(perf->dpi(index).x(), value));
    SET_END;
    if(!ui->xyBox->isChecked())
        // X/Y linked?
        stages[index].xSlider->setValue(slider->value());
}
Field Documentation
bool MPerfWidget::_xyLink [private]
Definition at line 44 of file mperfwidget.h.
Referenced by boxXChanged(), boxYChanged(), MPerfWidget(), on_xyBox_clicked(), setPerf(), sliderXMoved(), and sliderYMoved().
QSignalMapper MPerfWidget::boxXMapper [private]
Definition at line 49 of file mperfwidget.h.
Referenced by MPerfWidget().
QSignalMapper MPerfWidget::boxYMapper [private]
Definition at line 49 of file mperfwidget.h.
Referenced by MPerfWidget().
QSignalMapper MPerfWidget::buttonMapper1 [private]
Definition at line 47 of file mperfwidget.h.
Referenced by MPerfWidget().
QSignalMapper MPerfWidget::buttonMapper2 [private]
Definition at line 47 of file mperfwidget.h.
Referenced by MPerfWidget().
bool MPerfWidget::colorLink [private]
Definition at line 45 of file mperfwidget.h.
Referenced by colorChanged(), and colorClicked().
const int MPerfWidget::DPI_COUNT = KbPerf::DPI_COUNT [static]
Definition at line 28 of file mperfwidget.h.
Referenced by colorChanged(), MPerfWidget(), and setPerf().
const int MPerfWidget::DPI_MAX = KbPerf::DPI_MAX [static]
Definition at line 29 of file mperfwidget.h.
const int MPerfWidget::DPI_MIN = KbPerf::DPI_MIN [static]
Definition at line 29 of file mperfwidget.h.
QSignalMapper MPerfWidget::enableMapper [private]
Definition at line 50 of file mperfwidget.h.
Referenced by MPerfWidget().
bool MPerfWidget::isSetting [private]
Definition at line 53 of file mperfwidget.h.
KbPerf* MPerfWidget::perf [private]
Definition at line 34 of file mperfwidget.h.
Referenced by boxXChanged(), boxYChanged(), colorChanged(), enableChanged(), on_aSnapBox_clicked(), on_copyButton_clicked(), on_indicBox_clicked(), on_lHeightBox_activated(), on_spinBox_valueChanged(), setPerf(), sliderXMoved(), and sliderYMoved().
KbProfile* MPerfWidget::profile [private]
Definition at line 35 of file mperfwidget.h.
Referenced by on_copyButton_clicked(), and setPerf().
QSignalMapper MPerfWidget::sliderXMapper [private]
Definition at line 48 of file mperfwidget.h.
Referenced by MPerfWidget().
QSignalMapper MPerfWidget::sliderYMapper [private]
Definition at line 48 of file mperfwidget.h.
Referenced by MPerfWidget().
DpiUi MPerfWidget::stages[DPI_COUNT] [private]
Definition at line 43 of file mperfwidget.h.
Referenced by boxXChanged(), boxYChanged(), colorChanged(), enableChanged(), MPerfWidget(), setPerf(), sliderXMoved(), and sliderYMoved().
Ui::MPerfWidget* MPerfWidget::ui [private]
Definition at line 32 of file mperfwidget.h.
Referenced by colorChanged(), MPerfWidget(), setPerf(), sliderYMoved(), and ~MPerfWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.