.TH "src/ckb/animscript.cpp" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/animscript.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include 'animscript\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBurlParam\fP (const QString &param)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const double \fBONE_DAY\fP = 24\&. * 60\&. * 60\&."
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString urlParam (const QString &param)\fC [inline]\fP"

.PP
Definition at line 71 of file animscript\&.cpp\&.
.PP
Referenced by AnimScript::load()\&.
.PP
.nf
71                                              {
72     return QUrl::fromPercentEncoding(param\&.trimmed()\&.toLatin1())\&.trimmed();
73 }
.fi
.SH "Variable Documentation"
.PP 
.SS "const double ONE_DAY = 24\&. * 60\&. * 60\&.\fC [static]\fP"

.PP
Definition at line 75 of file animscript\&.cpp\&.
.PP
Referenced by AnimScript::load()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
