AnimSettingDialog
NAME
AnimSettingDialog -
SYNOPSIS
#include <src/ckb/animsettingdialog.h>
Inherits QDialog.
Public Member Functions
AnimSettingDialog (QWidget *parent, KbAnim *anim)
~AnimSettingDialog ()
QString name () const
Private Slots
void newDuration (double duration)
void updateStops ()
void angleDialChanged (QString name)
void angleSpinnerChanged (QString name)
void updateParam (QString name)
void on_delayBox_valueChanged (double arg1)
void on_repeatBox_valueChanged (double arg1)
void on_kpDelayBox_valueChanged (double arg1)
void on_kpRepeatBox_valueChanged (double arg1)
void on_kpReleaseBox_stateChanged (int arg1)
Private Member Functions
QFrame * hLine ()
Private Attributes
Ui::AnimSettingDialog * ui
QCheckBox * stopCheck
QCheckBox * kpStopCheck
bool hasRepeat
KbAnim * _anim
double lastDuration
QMap< QString, QWidget * > settingWidgets
QSignalMapper updateMapper
QMap< QString, QSpinBox * > angleSpinners
QSignalMapper angleDialMapper
QSignalMapper angleSpinnerMapper
Detailed Description
Definition at line 15 of file animsettingdialog.h.
Constructor & Destructor Documentation
AnimSettingDialog::AnimSettingDialog (QWidget *parent, KbAnim *anim) [explicit]
Definition at line 19 of file animsettingdialog.cpp.
References AnimScript::Param::AGRADIENT, AnimScript::Param::ANGLE, angleDialChanged(), angleDialMapper, angleFlip(), angleSpinnerChanged(), angleSpinnerMapper, angleSpinners, Ui_AnimSettingDialog::animName, AnimScript::Param::ARGB, AnimScript::author(), AnimScript::Param::BOOL, Ui_AnimSettingDialog::delayBox, AnimScript::description(), AnimScript::Param::DOUBLE, AnimScript::Param::GRADIENT, AnimScript::hasKeypress(), AnimScript::hasParam(), KbAnim::hasParameter(), hasRepeat, hLine(), Ui_AnimSettingDialog::kpDelayBox, Ui_AnimSettingDialog::kpModeStopBox, Ui_AnimSettingDialog::kpReleaseBox, Ui_AnimSettingDialog::kpRepeatBox, Ui_AnimSettingDialog::kpRepeatLabel, Ui_AnimSettingDialog::kpRepeatLabel_2, kpStopCheck, AnimScript::Param::LABEL, lastDuration, AnimScript::license(), AnimScript::Param::LONG, AnimScript::Param::maximum, AnimScript::Param::minimum, AnimScript::Param::name, AnimScript::name(), KbAnim::name(), newDuration(), KbAnim::parameter(), AnimScript::paramIterator(), AnimScript::Param::postfix, AnimScript::Param::prefix, Ui_AnimSettingDialog::repeatBox, Ui_AnimSettingDialog::repeatLabel, Ui_AnimSettingDialog::repeatLabel_2, AnimScript::Param::RGB, Ui_AnimSettingDialog::sAuthorLabel, KbAnim::script(), KbAnim::scriptName(), Ui_AnimSettingDialog::sDescLabel, Ui_AnimSettingDialog::settingsGrid, settingWidgets, Ui_AnimSettingDialog::setupUi(), Ui_AnimSettingDialog::sLicenseLabel, Ui_AnimSettingDialog::sNameLabel, stopCheck, AnimScript::Param::STRING, Ui_AnimSettingDialog::sVerLabel, Ui_AnimSettingDialog::sYearLabel, Ui_AnimSettingDialog::timeGrid, AnimScript::Param::type, ui, updateMapper, updateParam(), updateStops(), AnimScript::version(), and AnimScript::year().
                                                                  :
    QDialog(parent),
    ui(new Ui::AnimSettingDialog), stopCheck(0), kpStopCheck(0),
    _anim(anim), lastDuration(1.0)
{
    ui->setupUi(this);
    setWindowTitle(anim->scriptName() + " Animation");
    ui->animName->setText(anim->name());
    const AnimScript* script = anim->script();
    connect(&updateMapper, SIGNAL(mapped(QString)), this, SLOT(updateParam(QString)));
    connect(&angleDialMapper, SIGNAL(mapped(QString)), this, SLOT(angleDialChanged(QString)));
    connect(&angleSpinnerMapper, SIGNAL(mapped(QString)), this, SLOT(angleSpinnerChanged(QString)));
    // Build settings UI
    int row = 1;
    ui->settingsGrid->addItem(new QSpacerItem(0, 10, QSizePolicy::Fixed, QSizePolicy::Fixed), row++, 6);
    ui->settingsGrid->addWidget(new QLabel("<b>Animation</b>", this), row++, 0, 1, 7);
    ui->settingsGrid->addWidget(hLine(), row++, 0, 1, 7);
    bool rSpacePlaced = false;
    QListIterator<AnimScript::Param> i(script->paramIterator());
    while(i.hasNext()){
        const AnimScript::Param& param = i.next();
        // Skip timing/playback params
        if(param.name == "duration"
                || param.name == "trigger" || param.name == "kptrigger"
                || param.name == "kpmode"
                || param.name == "delay" || param.name == "kpdelay"
                || param.name == "repeat" || param.name == "kprepeat"
                || param.name == "stop" || param.name == "kpstop"
                || param.name == "kpmodestop" || param.name == "kprelease")
            continue;
        QVariant value = anim->parameter(param.name);
        // Display prefix label on the left (except for booleans and labels)
        if(param.type != AnimScript::Param::BOOL && param.type != AnimScript::Param::LABEL)
            ui->settingsGrid->addWidget(new QLabel(param.prefix, this), row, 1);
        // Configure and display main widget
        QWidget* widget = 0;
        int colSpan = 1;
        QString postfix = param.postfix;
        switch(param.type){
        case AnimScript::Param::BOOL:
            widget = new QCheckBox(param.prefix, this);
            ((QCheckBox*)widget)->setChecked(value.toBool());
            colSpan = 4;
            connect(widget, SIGNAL(stateChanged(int)), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::LONG:
            widget = new QSpinBox(this);
            ((QSpinBox*)widget)->setMinimum(param.minimum.toInt());
            ((QSpinBox*)widget)->setMaximum(param.maximum.toInt());
            ((QSpinBox*)widget)->setValue(value.toInt());
            if(postfix.length() <= 3){
                ((QSpinBox*)widget)->setSuffix(postfix);
                postfix = "";
            }
            connect(widget, SIGNAL(valueChanged(int)), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::DOUBLE:
            widget = new QDoubleSpinBox(this);
            ((QDoubleSpinBox*)widget)->setDecimals(1);
            ((QDoubleSpinBox*)widget)->setMinimum(param.minimum.toDouble());
            ((QDoubleSpinBox*)widget)->setMaximum(param.maximum.toDouble());
            ((QDoubleSpinBox*)widget)->setValue(value.toDouble());
            if(postfix.length() <= 3){
                ((QDoubleSpinBox*)widget)->setSuffix(postfix);
                postfix = "";
            }
            connect(widget, SIGNAL(valueChanged(double)), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::RGB:
            widget = new ColorButton(this);
            ((ColorButton*)widget)->color(QColor("#" + value.toString()));
            colSpan = 3;
            connect(widget, SIGNAL(colorChanged(QColor)), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::ARGB:{
            widget = new ColorButton(this, true);
            QString val = value.toString();
            QColor color;
            if(val.length() == 8){
                color = "#" + val.right(6);
                color.setAlpha(val.left(2).toInt(0, 16));
            } else
                color = "#" + val;
            ((ColorButton*)widget)->color(color);
            colSpan = 3;
            connect(widget, SIGNAL(colorChanged(QColor)), &updateMapper, SLOT(map()));
            break;
        }
        case AnimScript::Param::GRADIENT:
            widget = new GradientButton(this);
            ((GradientButton*)widget)->fromString(value.toString());
            colSpan = 3;
            connect(widget, SIGNAL(gradientChanged()), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::AGRADIENT:
            widget = new GradientButton(this, true);
            ((GradientButton*)widget)->fromString(value.toString());
            colSpan = 3;
            connect(widget, SIGNAL(gradientChanged()), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::ANGLE:
            widget = new QDial(this);
            ((QDial*)widget)->setFixedSize(60, 60);
            ((QDial*)widget)->setMinimum(0);
            ((QDial*)widget)->setMaximum(360);
            // this is NOT a typo... ^
            // Even though 360 shouldn't be valid, the wheel/arrow keys will lose 1 degree at the bottom unless 360 is set as max
            ((QDial*)widget)->setSingleStep(5);
            ((QDial*)widget)->setPageStep(15);
            ((QDial*)widget)->setNotchTarget(6);
            ((QDial*)widget)->setNotchesVisible(true);
            ((QDial*)widget)->setWrapping(true);
            ((QDial*)widget)->setInvertedAppearance(true);
            ((QDial*)widget)->setValue(angleFlip(value.toInt()));
            angleDialMapper.setMapping(widget, param.name);
            connect(widget, SIGNAL(valueChanged(int)), &angleDialMapper, SLOT(map()));
            break;
        case AnimScript::Param::STRING:
            widget = new QLineEdit(this);
            ((QLineEdit*)widget)->setText(value.toString());
            colSpan = 3;
            connect(widget, SIGNAL(textEdited(const QString&)), &updateMapper, SLOT(map()));
            break;
        case AnimScript::Param::LABEL:
            widget = new QLabel(this);
            ((QLabel*)widget)->setText(param.prefix);
            colSpan = 4;
            break;
        default:
            break;
        }
        if(widget)
            updateMapper.setMapping(widget, param.name);
        if(param.type == AnimScript::Param::BOOL || param.type == AnimScript::Param::LABEL){
            // Boolean values are placed on the left with no prefix or postfix
            settingWidgets[param.name] = widget;
            ui->settingsGrid->addWidget(widget, row, 3, 1, colSpan);
        } else {
            // Display the widget
            if(widget){
                settingWidgets[param.name] = widget;
                ui->settingsGrid->addWidget(widget, row, 3, 1, colSpan);
            }
            // Angles additionally have a spin box
            if(param.type == AnimScript::Param::ANGLE){
                QSpinBox* spinner = new QSpinBox(this);
                spinner->setMinimum(0);
                spinner->setMaximum(359);
                spinner->setWrapping(true);
                spinner->setSuffix("°");
                spinner->setValue(value.toInt());
                angleSpinners[param.name] = spinner;
                angleSpinnerMapper.setMapping(spinner, param.name);
                connect(spinner, SIGNAL(valueChanged(int)), &angleSpinnerMapper, SLOT(map()));
                ui->settingsGrid->addWidget(spinner, row, 4);
                colSpan = 2;
            }
            // Display postfix label on the right
            ui->settingsGrid->addWidget(new QLabel(postfix, this), row, 3 + colSpan, 1, 4 - colSpan);
            if(colSpan < 3 && !rSpacePlaced){
                // Add a spacer to compress short elements to the left
                ui->settingsGrid->addItem(new QSpacerItem(0, 0, QSizePolicy::Minimum), row, 4 + colSpan);
                rSpacePlaced = true;
            }
        }
        row++;
    }
    // Add playback info at bottom
    ui->settingsGrid->addItem(new QSpacerItem(0, 10, QSizePolicy::Fixed, QSizePolicy::Fixed), row++, 6);
    ui->settingsGrid->addWidget(new QLabel("<b>Playback</b>", this), row++, 0, 1, 7);
    ui->settingsGrid->addWidget(hLine(), row++, 0, 1, 7);
    if(script->hasParam("duration")){
        // Show duration spinner (if allowed)
        lastDuration = anim->parameter("duration").toDouble();
        ui->settingsGrid->addWidget(new QLabel("Duration:", this), row, 1);
        QDoubleSpinBox* spinner = new QDoubleSpinBox(this);
        spinner->setDecimals(1);
        spinner->setMinimum(0.1);
        spinner->setValue(lastDuration);
        connect(spinner, SIGNAL(valueChanged(double)), this, SLOT(newDuration(double)));
        settingWidgets["duration"] = spinner;
        ui->settingsGrid->addWidget(spinner, row, 3, 1, 1);
        ui->settingsGrid->addWidget(new QLabel("seconds", this), row, 4, 1, 2);
        row++;
    }
    // Show boxes for start with mode/with keypress
    QCheckBox* check = new QCheckBox("Start with mode", this);
    check->setChecked(anim->parameter("trigger").toBool());
    ui->settingsGrid->addWidget(check, row, 3, 1, 4);
    settingWidgets["trigger"] = check;
    connect(check, SIGNAL(stateChanged(int)), &updateMapper, SLOT(map()));
    updateMapper.setMapping(check, "trigger");
    row++;
    check = new QCheckBox("Start with key press", this);
    check->setChecked(anim->parameter("kptrigger").toBool());
    ui->settingsGrid->addWidget(check, row, 3, 1, 2);
    settingWidgets["kptrigger"] = check;
    connect(check, SIGNAL(stateChanged(int)), &updateMapper, SLOT(map()));
    updateMapper.setMapping(check, "kptrigger");
    // Add an option allowing the user to select keypress mode
    QComboBox* combo = new QComboBox(this);
    int selected = anim->parameter("kpmode").toInt();
    if(script->hasKeypress()){
        // If the script supports keypresses, show the option to handle them that way (default)
        combo->addItem("on pressed key");
        combo->addItem("on whole keyboard");
        combo->addItem("on keyboard (once)");
    } else {
        selected--;
        // Otherwise, just show the choice of whether to start it every time or just once
        combo->addItem("every time");
        combo->addItem("only once");
    }
    if(selected < 0 || selected > combo->count())
        selected = 0;
    combo->setCurrentIndex(selected);
    ui->settingsGrid->addWidget(combo, row, 5, 1, 2);
    settingWidgets["kpmode"] = combo;
    connect(combo, SIGNAL(activated(int)), &updateMapper, SLOT(map()));
    updateMapper.setMapping(combo, "kpmode");
    row++;
    // Add horizontal spacer to compress content to left
    ui->settingsGrid->addItem(new QSpacerItem(0, 0, QSizePolicy::Expanding), 0, 6);
    // Add vertical spacer to compress content to top
    ui->settingsGrid->addItem(new QSpacerItem(0, 0, QSizePolicy::Minimum, QSizePolicy::Expanding), row, 0);
    // Add timing fields
    settingWidgets["delay"] = ui->delayBox;
    ui->delayBox->setValue(anim->parameter("delay").toDouble());
    settingWidgets["kpdelay"] = ui->kpDelayBox;
    ui->kpDelayBox->setValue(anim->parameter("kpdelay").toDouble());
    settingWidgets["kpmodestop"] = ui->kpModeStopBox;
    ui->kpModeStopBox->setChecked(anim->parameter("kpmodestop").toBool());
    connect(ui->kpModeStopBox, SIGNAL(clicked(bool)), &updateMapper, SLOT(map()));
    updateMapper.setMapping(ui->kpModeStopBox, "kpmodestop");
    settingWidgets["kprelease"] = ui->kpReleaseBox;
    ui->kpReleaseBox->setChecked(anim->parameter("kprelease").toBool());
    if(anim->hasParameter("repeat")){
        hasRepeat = true;
        settingWidgets["repeat"] = ui->repeatBox;
        ui->repeatBox->setValue(anim->parameter("repeat").toDouble());
        settingWidgets["kprepeat"] = ui->kpRepeatBox;
        ui->kpRepeatBox->setValue(anim->parameter("kprepeat").toDouble());
        // If repeat is enabled, add repeat counts as integer values
        // Mode repeat
        ui->timeGrid->addWidget(new QLabel("Repeat:", this), 4, 1);
        QSpinBox* spinner = new QSpinBox(this);
        spinner->setMinimum(0);
        spinner->setMaximum(1000000);
        spinner->setValue(anim->parameter("stop").toInt());
        settingWidgets["stop"] = spinner;
        connect(spinner, SIGNAL(valueChanged(int)), &updateMapper, SLOT(map()));
        updateMapper.setMapping(spinner, "stop");
        ui->timeGrid->addWidget(spinner, 4, 3);
        ui->timeGrid->addWidget(new QLabel("times", this), 4, 4);
        // KP repeat
        ui->timeGrid->addWidget(new QLabel("Repeat:", this), 12, 1);
        spinner = new QSpinBox(this);
        spinner->setMinimum(0);
        spinner->setMaximum(1000000);
        spinner->setValue(anim->parameter("kpstop").toInt());
        settingWidgets["kpstop"] = spinner;
        connect(spinner, SIGNAL(valueChanged(int)), &updateMapper, SLOT(map()));
        updateMapper.setMapping(spinner, "kpstop");
        ui->timeGrid->addWidget(spinner, 12, 3);
        ui->timeGrid->addWidget(new QLabel("times", this), 12, 4);
        // Infinite repeat toggles
        stopCheck = new QCheckBox("Forever", this);
        stopCheck->setChecked(anim->parameter("stop").toInt() < 0);
        ui->timeGrid->addWidget(stopCheck, 4, 5);
        kpStopCheck = new QCheckBox("Forever", this);
        connect(stopCheck, SIGNAL(clicked()), this, SLOT(updateStops()));
        kpStopCheck->setChecked(anim->parameter("kpstop").toInt() < 0);
        ui->timeGrid->addWidget(kpStopCheck, 12, 5);
        connect(kpStopCheck, SIGNAL(clicked()), this, SLOT(updateStops()));
    } else {
        hasRepeat = false;
        // If repeat is not enabled, hide repeat-related fields
        ui->repeatBox->setHidden(true);
        ui->repeatLabel->setHidden(true);
        ui->repeatLabel_2->setHidden(true);
        ui->kpRepeatBox->setHidden(true);
        ui->kpRepeatLabel->setHidden(true);
        ui->kpRepeatLabel_2->setHidden(true);
        // Add stop times as double values
        // Stop time
        QDoubleSpinBox* spinner = new QDoubleSpinBox(this);
        spinner->setDecimals(1);
        spinner->setMinimum(0.1);
        spinner->setMaximum(24. * 60. * 60.);
        double stop = anim->parameter("stop").toDouble();
        if(stop <= 0.)
            spinner->setValue(lastDuration);
        else
            spinner->setValue(stop);
        settingWidgets["stop"] = spinner;
        connect(spinner, SIGNAL(valueChanged(double)), &updateMapper, SLOT(map()));
        updateMapper.setMapping(spinner, "stop");
        ui->timeGrid->addWidget(spinner, 4, 3);
        ui->timeGrid->addWidget(new QLabel("seconds", this), 4, 4);
        // KP stop time
        spinner = new QDoubleSpinBox(this);
        spinner->setDecimals(1);
        spinner->setMinimum(0.1);
        spinner->setMaximum(24. * 60. * 60.);
        double kpstop = anim->parameter("kpstop").toDouble();
        if(kpstop <= 0.)
            spinner->setValue(lastDuration);
        else
            spinner->setValue(kpstop);
        settingWidgets["kpstop"] = spinner;
        connect(spinner, SIGNAL(valueChanged(double)), &updateMapper, SLOT(map()));
        updateMapper.setMapping(spinner, "kpstop");
        ui->timeGrid->addWidget(spinner, 12, 3);
        ui->timeGrid->addWidget(new QLabel("seconds", this), 12, 4);
        // Infinite run toggles
        stopCheck = new QCheckBox("Stop after:", this);
        stopCheck->setChecked(stop > 0.);
        ui->timeGrid->addWidget(stopCheck, 4, 1);
        connect(stopCheck, SIGNAL(clicked()), this, SLOT(updateStops()));
        kpStopCheck = new QCheckBox("Stop after:", this);
        kpStopCheck->setChecked(kpstop > 0.);
        ui->timeGrid->addWidget(kpStopCheck, 12, 1);
        connect(kpStopCheck, SIGNAL(clicked()), this, SLOT(updateStops()));
    }
    updateStops();
    // Set script info UI
    ui->sNameLabel->setText(script->name());
    ui->sVerLabel->setText(script->version());
    ui->sAuthorLabel->setText(script->author());
    ui->sYearLabel->setText(script->year());
    ui->sLicenseLabel->setText(script->license());
    ui->sDescLabel->setText(script->description());
    // Lock dialog size
    setFixedSize(minimumSize());
}
AnimSettingDialog::~AnimSettingDialog ()
Definition at line 476 of file animsettingdialog.cpp.
References ui.
                                     {
    delete ui;
}
Member Function Documentation
void AnimSettingDialog::angleDialChanged (QStringname) [private], [slot]
Definition at line 389 of file animsettingdialog.cpp.
References angleFlip(), angleSpinners, name(), settingWidgets, and updateParam().
Referenced by AnimSettingDialog().
                                                    {
    // Dial changed; update spinner value
    angleSpinners[name]->setValue(angleFlip(((QDial*)settingWidgets[name])->value()));
    updateParam(name);
}
void AnimSettingDialog::angleSpinnerChanged (QStringname) [private], [slot]
Definition at line 395 of file animsettingdialog.cpp.
References angleFlip(), angleSpinners, settingWidgets, and updateParam().
Referenced by AnimSettingDialog().
                                                       {
    // Spinner changed; update dial value
    ((QDial*)settingWidgets[name])->setValue(angleFlip(angleSpinners[name]->value()));
    updateParam(name);
}
QFrame * AnimSettingDialog::hLine () [private]
Definition at line 480 of file animsettingdialog.cpp.
References frame.
Referenced by AnimSettingDialog().
                                {
    QFrame* frame = new QFrame(this);
    frame->setFrameShape(QFrame::HLine);
    frame->setFrameShadow(QFrame::Sunken);
    return frame;
}
QString AnimSettingDialog::name () const
Definition at line 472 of file animsettingdialog.cpp.
References Ui_AnimSettingDialog::animName, and ui.
Referenced by angleDialChanged(), and KbAnimWidget::on_propertyButton_clicked().
                                      {
    return ui->animName->text();
}
void AnimSettingDialog::newDuration (doubleduration) [private], [slot]
Definition at line 361 of file animsettingdialog.cpp.
References lastDuration, settingWidgets, and updateParam().
Referenced by AnimSettingDialog().
                                                  {
    // Duration changed. Automatically fix Repeat and KP Repeat to the same values, if they matched before
    QDoubleSpinBox* rep = (QDoubleSpinBox*)settingWidgets.value("repeat");
    QDoubleSpinBox* kpRep = (QDoubleSpinBox*)settingWidgets.value("kprepeat");
    if(rep && rep->value() == lastDuration)
        rep->setValue(duration);
    if(kpRep && kpRep->value() == lastDuration)
        kpRep->setValue(duration);
    lastDuration = duration;
    updateParam("duration");
    updateParam("repeat");
    updateParam("kprepeat");
}
void AnimSettingDialog::on_delayBox_valueChanged (doublearg1) [private], [slot]
Definition at line 487 of file animsettingdialog.cpp.
References updateParam().
                                                           {
    updateParam("delay");
}
void AnimSettingDialog::on_kpDelayBox_valueChanged (doublearg1) [private], [slot]
Definition at line 495 of file animsettingdialog.cpp.
References updateParam().
                                                             {
    updateParam("kpdelay");
}
void AnimSettingDialog::on_kpReleaseBox_stateChanged (intarg1) [private], [slot]
Definition at line 503 of file animsettingdialog.cpp.
References updateParam().
                                                            {
    updateParam("kprelease");
}
void AnimSettingDialog::on_kpRepeatBox_valueChanged (doublearg1) [private], [slot]
Definition at line 499 of file animsettingdialog.cpp.
References updateParam().
                                                              {
    updateParam("kprepeat");
}
void AnimSettingDialog::on_repeatBox_valueChanged (doublearg1) [private], [slot]
Definition at line 491 of file animsettingdialog.cpp.
References updateParam().
                                                            {
    updateParam("repeat");
}
void AnimSettingDialog::updateParam (QStringname) [private], [slot]
Definition at line 401 of file animsettingdialog.cpp.
References _anim, AnimScript::Param::AGRADIENT, AnimScript::Param::ANGLE, angleFlip(), AnimScript::Param::ARGB, AnimScript::Param::BOOL, ColorButton::color(), AnimScript::Param::DOUBLE, AnimScript::Param::GRADIENT, AnimScript::hasKeypress(), hasRepeat, kpStopCheck, AnimScript::Param::LONG, AnimScript::param(), KbAnim::parameter(), AnimScript::Param::RGB, KbAnim::script(), settingWidgets, stopCheck, AnimScript::Param::STRING, GradientButton::toString(), and AnimScript::Param::type.
Referenced by angleDialChanged(), angleSpinnerChanged(), AnimSettingDialog(), newDuration(), on_delayBox_valueChanged(), on_kpDelayBox_valueChanged(), on_kpReleaseBox_stateChanged(), on_kpRepeatBox_valueChanged(), on_repeatBox_valueChanged(), and updateStops().
                                               {
    if(!settingWidgets.contains(name))
        return;
    // stop and kpstop have defeat switches
    if((name == "stop" && stopCheck->isChecked() == hasRepeat)
            || (name == "kpstop" && kpStopCheck->isChecked() == hasRepeat)){
        _anim->parameter(name, -1);
        return;
    } else if(name == "kpmode"){
        // kpmode uses a drop-down, and selection is inverted
        QComboBox* widget = (QComboBox*)settingWidgets[name];
        int selected = widget->currentIndex();
        if(!_anim->script()->hasKeypress())
            selected++;
        _anim->parameter(name, selected);
        return;
    }
    // Read value based on type
    switch(_anim->script()->param(name).type){
    case AnimScript::Param::BOOL:{
        QCheckBox* widget = (QCheckBox*)settingWidgets[name];
        _anim->parameter(name, (int)widget->isChecked());
        break;
    }
    case AnimScript::Param::LONG:{
        QSpinBox* widget = (QSpinBox*)settingWidgets[name];
        _anim->parameter(name, widget->value());
        break;
    }
    case AnimScript::Param::DOUBLE:{
        QDoubleSpinBox* widget = (QDoubleSpinBox*)settingWidgets[name];
        _anim->parameter(name, widget->value());
        break;
    }
    case AnimScript::Param::RGB:{
        ColorButton* widget = (ColorButton*)settingWidgets[name];
        QColor color = widget->color();
        char hex[7];
        snprintf(hex, sizeof(hex), "%02x%02x%02x", color.red(), color.green(), color.blue());
        _anim->parameter(name, QString(hex));
        break;
    }
    case AnimScript::Param::ARGB:{
        ColorButton* widget = (ColorButton*)settingWidgets[name];
        QColor color = widget->color();
        char hex[9];
        snprintf(hex, sizeof(hex), "%02x%02x%02x%02x", color.alpha(), color.red(), color.green(), color.blue());
        _anim->parameter(name, QString(hex));
        break;
    }
    case AnimScript::Param::GRADIENT:
    case AnimScript::Param::AGRADIENT:{
        GradientButton* widget = (GradientButton*)settingWidgets[name];
        _anim->parameter(name, widget->toString());
        break;
    }
    case AnimScript::Param::ANGLE:{
        QDial* widget = (QDial*)settingWidgets[name];
        _anim->parameter(name, angleFlip(widget->value()));
        break;
    }
    case AnimScript::Param::STRING:{
        QLineEdit* widget = (QLineEdit*)settingWidgets[name];
        _anim->parameter(name, widget->text());
        break;
    }
    default:
        break;
    }
}
void AnimSettingDialog::updateStops () [private], [slot]
Definition at line 375 of file animsettingdialog.cpp.
References hasRepeat, kpStopCheck, settingWidgets, stopCheck, and updateParam().
Referenced by AnimSettingDialog().
                                   {
    if(hasRepeat){
        // When repeat is enabled, the check box is "repeat forever", so disable stop count if checked
        settingWidgets.value("stop")->setDisabled(stopCheck->isChecked());
        settingWidgets.value("kpstop")->setDisabled(kpStopCheck->isChecked());
    } else {
        // When repeat is disabled, the check box is "stop after", so disable stop count UNLESS checked
        settingWidgets.value("stop")->setEnabled(stopCheck->isChecked());
        settingWidgets.value("kpstop")->setEnabled(kpStopCheck->isChecked());
    }
    updateParam("stop");
    updateParam("kpstop");
}
Field Documentation
KbAnim* AnimSettingDialog::_anim [private]
Definition at line 32 of file animsettingdialog.h.
Referenced by updateParam().
QSignalMapper AnimSettingDialog::angleDialMapper [private]
Definition at line 38 of file animsettingdialog.h.
Referenced by AnimSettingDialog().
QSignalMapper AnimSettingDialog::angleSpinnerMapper [private]
Definition at line 38 of file animsettingdialog.h.
Referenced by AnimSettingDialog().
QMap<QString, QSpinBox*> AnimSettingDialog::angleSpinners [private]
Definition at line 37 of file animsettingdialog.h.
Referenced by angleDialChanged(), angleSpinnerChanged(), and AnimSettingDialog().
bool AnimSettingDialog::hasRepeat [private]
Definition at line 30 of file animsettingdialog.h.
Referenced by AnimSettingDialog(), updateParam(), and updateStops().
QCheckBox * AnimSettingDialog::kpStopCheck [private]
Definition at line 29 of file animsettingdialog.h.
Referenced by AnimSettingDialog(), updateParam(), and updateStops().
double AnimSettingDialog::lastDuration [private]
Definition at line 33 of file animsettingdialog.h.
Referenced by AnimSettingDialog(), and newDuration().
QMap<QString, QWidget*> AnimSettingDialog::settingWidgets [private]
Definition at line 34 of file animsettingdialog.h.
Referenced by angleDialChanged(), angleSpinnerChanged(), AnimSettingDialog(), newDuration(), updateParam(), and updateStops().
QCheckBox* AnimSettingDialog::stopCheck [private]
Definition at line 29 of file animsettingdialog.h.
Referenced by AnimSettingDialog(), updateParam(), and updateStops().
Ui::AnimSettingDialog* AnimSettingDialog::ui [private]
Definition at line 28 of file animsettingdialog.h.
Referenced by AnimSettingDialog(), name(), and ~AnimSettingDialog().
QSignalMapper AnimSettingDialog::updateMapper [private]
Definition at line 35 of file animsettingdialog.h.
Referenced by AnimSettingDialog().
Author
Generated automatically by Doxygen for ckb-next from the source code.