.TH "devcmd.__unnamed__" 3 "Mon Jun 5 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
devcmd.__unnamed__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcmdhandler_io\fP \fBhwload\fP"
.br
.ti -1c
.RI "\fBcmdhandler_io\fP \fBhwsave\fP"
.br
.ti -1c
.RI "\fBcmdhandler_io\fP \fBfwupdate\fP"
.br
.ti -1c
.RI "\fBcmdhandler_io\fP \fBpollrate\fP"
.br
.ti -1c
.RI "\fBcmdhandler_io\fP \fBactive\fP"
.br
.ti -1c
.RI "\fBcmdhandler_io\fP \fBidle\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBerase\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBeraseprofile\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBname\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBprofilename\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBid\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBprofileid\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBrgb\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBioff\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBion\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBiauto\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBbind\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBunbind\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBrebind\fP"
.br
.ti -1c
.RI "\fBcmdhandler_mac\fP \fBmacro\fP"
.br
.ti -1c
.RI "\fBcmdhandler_mac\fP \fBdpi\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBdpisel\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBlift\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBsnap\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBnotify\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBinotify\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBget\fP"
.br
.ti -1c
.RI "\fBcmdhandler\fP \fBrestart\fP"
.br
.ti -1c
.RI "int(* \fBstart\fP )(\fBusbdevice\fP *kb, int makeactive)"
.br
.ti -1c
.RI "void(* \fBsetmodeindex\fP )(\fBusbdevice\fP *kb, int index)"
.br
.ti -1c
.RI "void(* \fBallocprofile\fP )(\fBusbdevice\fP *kb)"
.br
.ti -1c
.RI "int(* \fBloadprofile\fP )(\fBusbdevice\fP *kb)"
.br
.ti -1c
.RI "void(* \fBfreeprofile\fP )(\fBusbdevice\fP *kb)"
.br
.ti -1c
.RI "int(* \fBupdatergb\fP )(\fBusbdevice\fP *kb, int force)"
.br
.ti -1c
.RI "void(* \fBupdateindicators\fP )(\fBusbdevice\fP *kb, int force)"
.br
.ti -1c
.RI "int(* \fBupdatedpi\fP )(\fBusbdevice\fP *kb, int force)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file command\&.h\&.
.SH "Field Documentation"
.PP 
.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""

.SS ""


.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
