.TH "src/ckb-daemon/device_vtable.c" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb-daemon/device_vtable.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'command\&.h'\fP
.br
\fC#include 'device\&.h'\fP
.br
\fC#include 'dpi\&.h'\fP
.br
\fC#include 'firmware\&.h'\fP
.br
\fC#include 'input\&.h'\fP
.br
\fC#include 'led\&.h'\fP
.br
\fC#include 'notify\&.h'\fP
.br
\fC#include 'profile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBcmd_none\fP (\fBusbdevice\fP *kb, \fBusbmode\fP *dummy1, int dummy2, int dummy3, const char *dummy4)"
.br
.ti -1c
.RI "static int \fBcmd_io_none\fP (\fBusbdevice\fP *kb, \fBusbmode\fP *dummy1, int dummy2, int dummy3, const char *dummy4)"
.br
.ti -1c
.RI "static void \fBcmd_macro_none\fP (\fBusbdevice\fP *kb, \fBusbmode\fP *dummy1, int dummy2, const char *dummy3, const char *dummy4)"
.br
.ti -1c
.RI "static int \fBloadprofile_none\fP (\fBusbdevice\fP *kb)"
.br
.ti -1c
.RI "static void \fBint1_void_none\fP (\fBusbdevice\fP *kb, int dummy)"
.br
.ti -1c
.RI "static int \fBint1_int_none\fP (\fBusbdevice\fP *kb, int dummy)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBdevcmd\fP \fBvtable_keyboard\fP"
.br
.RI "\fIRGB keyboard vtable holds functions for each device type\&. \fP"
.ti -1c
.RI "const \fBdevcmd\fP \fBvtable_keyboard_nonrgb\fP"
.br
.ti -1c
.RI "const \fBdevcmd\fP \fBvtable_mouse\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static int cmd_io_none (\fBusbdevice\fP *kb, \fBusbmode\fP *dummy1, intdummy2, intdummy3, const char *dummy4)\fC [static]\fP"

.PP
Definition at line 13 of file device_vtable\&.c\&.
.PP
.nf
13                                                                                                   {
14     return 0;
15 }
.fi
.SS "static void cmd_macro_none (\fBusbdevice\fP *kb, \fBusbmode\fP *dummy1, intdummy2, const char *dummy3, const char *dummy4)\fC [static]\fP"

.PP
Definition at line 16 of file device_vtable\&.c\&.
.PP
.nf
16                                                                                                               {
17 }
.fi
.SS "static void cmd_none (\fBusbdevice\fP *kb, \fBusbmode\fP *dummy1, intdummy2, intdummy3, const char *dummy4)\fC [static]\fP"

.PP
Definition at line 11 of file device_vtable\&.c\&.
.PP
.nf
11                                                                                                 {
12 }
.fi
.SS "static int int1_int_none (\fBusbdevice\fP *kb, intdummy)\fC [static]\fP"

.PP
Definition at line 23 of file device_vtable\&.c\&.
.PP
.nf
23                                                   {
24     return 0;
25 }
.fi
.SS "static void int1_void_none (\fBusbdevice\fP *kb, intdummy)\fC [static]\fP"

.PP
Definition at line 21 of file device_vtable\&.c\&.
.PP
.nf
21                                                     {
22 }
.fi
.SS "static int loadprofile_none (\fBusbdevice\fP *kb)\fC [static]\fP"

.PP
Definition at line 18 of file device_vtable\&.c\&.
.PP
.nf
18                                           {
19     return 0;
20 }
.fi
.SH "Variable Documentation"
.PP 
.SS "const \fBdevcmd\fP vtable_keyboard"

.PP
Definition at line 29 of file device_vtable\&.c\&.
.PP
Referenced by get_vtable()\&.
.SS "const \fBdevcmd\fP vtable_keyboard_nonrgb"

.PP
Definition at line 76 of file device_vtable\&.c\&.
.PP
Referenced by get_vtable()\&.
.SS "const \fBdevcmd\fP vtable_mouse"

.PP
Definition at line 123 of file device_vtable\&.c\&.
.PP
Referenced by get_vtable()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
