.TH "src/ckb/firmware_special.h" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/firmware_special.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'keymap\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBfirmwareSpecial\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBV_CORSAIR\fP   0x1b1c"
.br
.RI "\fITo reduce effort, please insert these combinations only, which need really special treatment\&. All other models will further be identified by their feature-lists\&. \fP"
.ti -1c
.RI "#define \fBP_K70_LUX_NRGB\fP   0x1b36"
.br
.RI "\fIEnter the Product ID of your device you want to handle with special treatment\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBfirmwareSpecial\fP \fBspecials\fP []"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct firmwareSpecial"
.PP 
Definition at line 20 of file firmware_special\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
const Model \fImodel\fP 
.br
.PP
const short \fIproduct\fP 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define P_K70_LUX_NRGB   0x1b36"

.PP
Definition at line 18 of file firmware_special\&.h\&.
.PP
Referenced by loadrgb_kb(), and product_str()\&.
.SS "#define V_CORSAIR   0x1b1c"
And - please - add a comment, why this entry is needed\&. Don't change this\&. If Corsair is not corsair any more, we have a different problem\&.\&.\&. 
.PP
Definition at line 15 of file firmware_special\&.h\&.
.PP
Referenced by KeyMap::getModel(), usb_add_device(), and vendor_str()\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBfirmwareSpecial\fP  specials[]"
\fBInitial value:\fP
.PP
.nf
= {

    
    
    
    
    
    
    
    {  0x1b36 , KeyMap::K70 },
}
.fi
.PP
Referenced by KeyMap::getModel()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
