.TH "src/ckb/quazip/JlCompress.h" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/JlCompress.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'quazip\&.h'\fP
.br
\fC#include 'quazipfile\&.h'\fP
.br
\fC#include 'quazipfileinfo\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QFile>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBJlCompress\fP"
.br
.RI "\fIUtility class for typical operations\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
