JlCompress
NAME
JlCompress -
Utility class for typical operations.
SYNOPSIS
#include <src/ckb/quazip/JlCompress.h>
Static Public Member Functions
static bool compressFile (QString fileCompressed, QString file)
Compress a single file.
static bool compressFiles (QString fileCompressed, QStringList files)
Compress a list of files.
static bool compressDir (QString fileCompressed, QString dir=QString(), bool recursive=true)
Compress a whole directory.
static QString extractFile (QString fileCompressed, QString fileName, QString fileDest=QString())
Extract a single file.
static QStringList extractFiles (QString fileCompressed, QStringList files, QString dir=QString())
Extract a list of files.
static QStringList extractDir (QString fileCompressed, QString dir=QString())
Extract a whole archive.
static QStringList getFileList (QString fileCompressed)
Get the file list.
Static Private Member Functions
static bool compressFile (QuaZip *zip, QString fileName, QString fileDest)
Compress a single file.
static bool compressSubDir (QuaZip *parentZip, QString dir, QString parentDir, bool recursive=true)
Compress a subdirectory.
static bool extractFile (QuaZip *zip, QString fileName, QString fileDest)
Extract a single file.
static bool removeFile (QStringList listFile)
Remove some files.
Detailed Description
This class contains a number of useful static functions to perform simple operations, such as mass ZIP packing or extraction.
Definition at line 42 of file JlCompress.h.
Member Function Documentation
bool JlCompress::compressDir (QStringfileCompressed, QStringdir = QString(), boolrecursive = true) [static]
OK Comprime la cartella dir nel file fileCompressed, se recursive e true allora comprime anche le sotto cartelle.
Parameters:
fileCompressed The name of the archive.
dir The directory to compress.
recursive Whether to pack the subdirectories as well, or just regular files.
Returns:
true if success, false otherwise.
Se la funzione fallisce restituisce false e cancella il file che si e tentato di creare.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
la compressione di un file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 338 of file JlCompress.cpp.
References QuaZip::close(), compressSubDir(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
                                                                                {
    // Creo lo zip
    QuaZip zip(fileCompressed);
    QDir().mkpath(QFileInfo(fileCompressed).absolutePath());
    if(!zip.open(QuaZip::mdCreate)) {
        QFile::remove(fileCompressed);
        return false;
    }
    // Aggiungo i file e le sotto cartelle
    if (!compressSubDir(&zip,dir,dir,recursive)) {
        QFile::remove(fileCompressed);
        return false;
    }
    // Chiudo il file zip
    zip.close();
    if(zip.getZipError()!=0) {
        QFile::remove(fileCompressed);
        return false;
    }
    return true;
}
bool JlCompress::compressFile (QuaZip *zip, QStringfileName, QStringfileDest) [static], [private]
OK Comprime il file fileName, nell'oggetto zip, con il nome fileDest.
Parameters:
zip Opened zip to compress the file to.
fileName The full path to the source file.
fileDest The full name of the file inside the archive.
Returns:
true if success, false otherwise.
La funzione fallisce se:
zip==NULL;
l'oggetto zip e stato aperto in una modalita non compatibile con l'aggiunta di file;
non e possibile aprire il file d'origine;
non e possibile creare il file all'interno dell'oggetto zip;
si e rilevato un errore nella copia dei dati;
non e stato possibile chiudere il file all'interno dell'oggetto zip;
Definition at line 53 of file JlCompress.cpp.
References QuaZipFile::close(), copyData(), QuaZip::getMode(), QuaZipFile::getZipError(), QuaZip::mdAdd, QuaZip::mdAppend, QuaZip::mdCreate, QuaZipFile::open(), and UNZ_OK.
Referenced by compressFile(), compressFiles(), and compressSubDir().
                                                                             {
    // zip: oggetto dove aggiungere il file
    // fileName: nome del file reale
    // fileDest: nome del file all'interno del file compresso
    // Controllo l'apertura dello zip
    if (!zip) return false;
    if (zip->getMode()!=QuaZip::mdCreate &&
        zip->getMode()!=QuaZip::mdAppend &&
        zip->getMode()!=QuaZip::mdAdd) return false;
    // Apro il file originale
    QFile inFile;
    inFile.setFileName(fileName);
    if(!inFile.open(QIODevice::ReadOnly)) return false;
    // Apro il file risulato
    QuaZipFile outFile(zip);
    if(!outFile.open(QIODevice::WriteOnly, QuaZipNewInfo(fileDest, inFile.fileName()))) return false;
    // Copio i dati
    if (!copyData(inFile, outFile) || outFile.getZipError()!=UNZ_OK) {
        return false;
    }
    // Chiudo i file
    outFile.close();
    if (outFile.getZipError()!=UNZ_OK) return false;
    inFile.close();
    return true;
}
bool JlCompress::compressFile (QStringfileCompressed, QStringfile) [static]
OK Comprime il file fileName nel file fileCompressed.
Parameters:
fileCompressed The name of the archive.
file The file to compress.
Returns:
true if success, false otherwise.
Se la funzione fallisce restituisce false e cancella il file che si e tentato di creare.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
la compressione del file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 263 of file JlCompress.cpp.
References QuaZip::close(), compressFile(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
                                                                  {
    // Creo lo zip
    QuaZip zip(fileCompressed);
    QDir().mkpath(QFileInfo(fileCompressed).absolutePath());
    if(!zip.open(QuaZip::mdCreate)) {
        QFile::remove(fileCompressed);
        return false;
    }
    // Aggiungo il file
    if (!compressFile(&zip,file,QFileInfo(file).fileName())) {
        QFile::remove(fileCompressed);
        return false;
    }
    // Chiudo il file zip
    zip.close();
    if(zip.getZipError()!=0) {
        QFile::remove(fileCompressed);
        return false;
    }
    return true;
}
bool JlCompress::compressFiles (QStringfileCompressed, QStringListfiles) [static]
OK Comprime i file specificati in files nel file fileCompressed.
Parameters:
fileCompressed The name of the archive.
files The file list to compress.
Returns:
true if success, false otherwise.
Se la funzione fallisce restituisce false e cancella il file che si e tentato di creare.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
la compressione di un file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 298 of file JlCompress.cpp.
References QuaZip::close(), compressFile(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
                                                                        {
    // Creo lo zip
    QuaZip zip(fileCompressed);
    QDir().mkpath(QFileInfo(fileCompressed).absolutePath());
    if(!zip.open(QuaZip::mdCreate)) {
        QFile::remove(fileCompressed);
        return false;
    }
    // Comprimo i file
    QFileInfo info;
    Q_FOREACH (QString file, files) {
        info.setFile(file);
        if (!info.exists() || !compressFile(&zip,file,info.fileName())) {
            QFile::remove(fileCompressed);
            return false;
        }
    }
    // Chiudo il file zip
    zip.close();
    if(zip.getZipError()!=0) {
        QFile::remove(fileCompressed);
        return false;
    }
    return true;
}
bool JlCompress::compressSubDir (QuaZip *zip, QStringdir, QStringorigDir, boolrecursive = true) [static], [private]
OK Comprime la cartella dir nel file fileCompressed, se recursive e true allora comprime anche le sotto cartelle.
Parameters:
parentZip Opened zip containing the parent directory.
dir The full path to the directory to pack.
parentDir The full path to the directory corresponding to the root of the ZIP.
recursive Whether to pack sub-directories as well or only files.
Returns:
true if success, false otherwise.
I nomi dei file preceduti dal path creato togliendo il pat della cartella origDir al path della cartella dir. Se la funzione fallisce restituisce false e cancella il file che si e tentato di creare.
La funzione fallisce se:
zip==NULL;
l'oggetto zip e stato aperto in una modalita non compatibile con l'aggiunta di file;
la cartella dir non esiste;
la compressione di una sotto cartella fallisce (1);
la compressione di un file fallisce; (1) La funzione si richiama in maniera ricorsiva per comprimere le sotto cartelle dunque gli errori di compressione di una sotto cartella sono gli stessi di questa funzione.
Definition at line 103 of file JlCompress.cpp.
References QuaZipFile::close(), compressFile(), QuaZip::getMode(), QuaZip::getZipName(), QuaZip::mdAdd, QuaZip::mdAppend, QuaZip::mdCreate, and QuaZipFile::open().
Referenced by compressDir().
                                                                                         {
    // zip: oggetto dove aggiungere il file
    // dir: cartella reale corrente
    // origDir: cartella reale originale
    // (path(dir)-path(origDir)) = path interno all'oggetto zip
    // Controllo l'apertura dello zip
    if (!zip) return false;
    if (zip->getMode()!=QuaZip::mdCreate &&
        zip->getMode()!=QuaZip::mdAppend &&
        zip->getMode()!=QuaZip::mdAdd) return false;
    // Controllo la cartella
    QDir directory(dir);
    if (!directory.exists()) return false;
    QDir origDirectory(origDir);
    if (dir != origDir) {
        QuaZipFile dirZipFile(zip);
        if (!dirZipFile.open(QIODevice::WriteOnly,
            QuaZipNewInfo(origDirectory.relativeFilePath(dir) + "/", dir), 0, 0, 0)) {
                return false;
        }
        dirZipFile.close();
    }
    // Se comprimo anche le sotto cartelle
    if (recursive) {
        // Per ogni sotto cartella
        QFileInfoList files = directory.entryInfoList(QDir::AllDirs|QDir::NoDotAndDotDot);
        Q_FOREACH (QFileInfo file, files) {
            // Comprimo la sotto cartella
            if(!compressSubDir(zip,file.absoluteFilePath(),origDir,recursive)) return false;
        }
    }
    // Per ogni file nella cartella
    QFileInfoList files = directory.entryInfoList(QDir::Files);
    Q_FOREACH (QFileInfo file, files) {
        // Se non e un file o e il file compresso che sto creando
        if(!file.isFile()||file.absoluteFilePath()==zip->getZipName()) continue;
        // Creo il nome relativo da usare all'interno del file compresso
        QString filename = origDirectory.relativeFilePath(file.absoluteFilePath());
        // Comprimo il file
        if (!compressFile(zip,file.absoluteFilePath(),filename)) return false;
    }
    return true;
}
QStringList JlCompress::extractDir (QStringfileCompressed, QStringdir = QString()) [static]
OK Estrae il file fileCompressed nella cartella dir.
Parameters:
fileCompressed The name of the archive.
dir The directory to extract to, the current directory if left empty.
Returns:
The list of the full paths of the files extracted, empty on failure.
Se dir = '' allora il file viene estratto nella cartella corrente. Se la funzione fallisce cancella i file che si e tentato di estrarre. Restituisce i nomi assoluti dei file estratti.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
la compressione di un file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 451 of file JlCompress.cpp.
References QuaZip::close(), extractFile(), QuaZip::getCurrentFileName(), QuaZip::getZipError(), QuaZip::goToFirstFile(), QuaZip::goToNextFile(), QuaZip::mdUnzip, QuaZip::open(), and removeFile().
                                                                      {
    // Apro lo zip
    QuaZip zip(fileCompressed);
    if(!zip.open(QuaZip::mdUnzip)) {
        return QStringList();
    }
    QDir directory(dir);
    QStringList extracted;
    if (!zip.goToFirstFile()) {
        return QStringList();
    }
    do {
        QString name = zip.getCurrentFileName();
        QString absFilePath = directory.absoluteFilePath(name);
        if (!extractFile(&zip, "", absFilePath)) {
            removeFile(extracted);
            return QStringList();
        }
        extracted.append(absFilePath);
    } while (zip.goToNextFile());
    // Chiudo il file zip
    zip.close();
    if(zip.getZipError()!=0) {
        removeFile(extracted);
        return QStringList();
    }
    return extracted;
}
bool JlCompress::extractFile (QuaZip *zip, QStringfileName, QStringfileDest) [static], [private]
OK Estrae il file fileName, contenuto nell'oggetto zip, con il nome fileDest.
Parameters:
zip The opened zip archive to extract from.
fileName The full name of the file to extract.
fileDest The full path to the destination file.
Returns:
true if success, false otherwise.
Se la funzione fallisce restituisce false e cancella il file che si e tentato di estrarre.
La funzione fallisce se:
zip==NULL;
l'oggetto zip e stato aperto in una modalita non compatibile con l'estrazione di file;
non e possibile aprire il file all'interno dell'oggetto zip;
non e possibile creare il file estratto;
si e rilevato un errore nella copia dei dati (1);
non e stato possibile chiudere il file all'interno dell'oggetto zip (1);
(1): prima di uscire dalla funzione cancella il file estratto.
Definition at line 170 of file JlCompress.cpp.
References QuaZipFile::close(), copyData(), QuaZip::getCurrentFileInfo(), QuaZip::getMode(), QuaZipFileInfo64::getPermissions(), QuaZipFile::getZipError(), QuaZip::mdUnzip, QuaZipFile::open(), removeFile(), QuaZip::setCurrentFile(), and UNZ_OK.
Referenced by extractDir(), extractFile(), and extractFiles().
                                                                            {
    // zip: oggetto dove aggiungere il file
    // filename: nome del file reale
    // fileincompress: nome del file all'interno del file compresso
    // Controllo l'apertura dello zip
    if (!zip) return false;
    if (zip->getMode()!=QuaZip::mdUnzip) return false;
    // Apro il file compresso
    if (!fileName.isEmpty())
        zip->setCurrentFile(fileName);
    QuaZipFile inFile(zip);
    if(!inFile.open(QIODevice::ReadOnly) || inFile.getZipError()!=UNZ_OK) return false;
    // Controllo esistenza cartella file risultato
    QDir curDir;
    if (fileDest.endsWith('/')) {
        if (!curDir.mkpath(fileDest)) {
            return false;
        }
    } else {
        if (!curDir.mkpath(QFileInfo(fileDest).absolutePath())) {
            return false;
        }
    }
    QuaZipFileInfo64 info;
    if (!zip->getCurrentFileInfo(&info))
        return false;
    QFile::Permissions srcPerm = info.getPermissions();
    if (fileDest.endsWith('/') && QFileInfo(fileDest).isDir()) {
        if (srcPerm != 0) {
            QFile(fileDest).setPermissions(srcPerm);
        }
        return true;
    }
    // Apro il file risultato
    QFile outFile;
    outFile.setFileName(fileDest);
    if(!outFile.open(QIODevice::WriteOnly)) return false;
    // Copio i dati
    if (!copyData(inFile, outFile) || inFile.getZipError()!=UNZ_OK) {
        outFile.close();
        removeFile(QStringList(fileDest));
        return false;
    }
    outFile.close();
    // Chiudo i file
    inFile.close();
    if (inFile.getZipError()!=UNZ_OK) {
        removeFile(QStringList(fileDest));
        return false;
    }
    if (srcPerm != 0) {
        outFile.setPermissions(srcPerm);
    }
    return true;
}
QString JlCompress::extractFile (QStringfileCompressed, QStringfileName, QStringfileDest = QString()) [static]
OK Estrae il file fileName, contenuto nel file fileCompressed, con il nome fileDest.
Parameters:
fileCompressed The name of the archive.
fileName The file to extract.
fileDest The destination file, assumed to be identical to file if left empty.
Returns:
The list of the full paths of the files extracted, empty on failure.
Se fileDest = '' allora il file viene estratto con lo stesso nome con cui e stato compresso. Se la funzione fallisce cancella il file che si e tentato di estrarre. Restituisce il nome assoluto del file estratto.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
l'estrazione del file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 377 of file JlCompress.cpp.
References QuaZip::close(), extractFile(), QuaZip::getZipError(), QuaZip::mdUnzip, QuaZip::open(), and removeFile().
                                                                                          {
    // Apro lo zip
    QuaZip zip(fileCompressed);
    if(!zip.open(QuaZip::mdUnzip)) {
        return QString();
    }
    // Estraggo il file
    if (fileDest.isEmpty())
        fileDest = fileName;
    if (!extractFile(&zip,fileName,fileDest)) {
        return QString();
    }
    // Chiudo il file zip
    zip.close();
    if(zip.getZipError()!=0) {
        removeFile(QStringList(fileDest));
        return QString();
    }
    return QFileInfo(fileDest).absoluteFilePath();
}
QStringList JlCompress::extractFiles (QStringfileCompressed, QStringListfiles, QStringdir = QString()) [static]
OK Estrae i file specificati in files, contenuti nel file fileCompressed, nella cartella dir.
Parameters:
fileCompressed The name of the archive.
files The file list to extract.
dir The directory to put the files to, the current directory if left empty.
Returns:
The list of the full paths of the files extracted, empty on failure.
La struttura a cartelle del file compresso viene rispettata. Se dir = '' allora il file viene estratto nella cartella corrente. Se la funzione fallisce cancella i file che si e tentato di estrarre. Restituisce i nomi assoluti dei file estratti.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
l'estrazione di un file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 412 of file JlCompress.cpp.
References QuaZip::close(), extractFile(), QuaZip::getZipError(), QuaZip::mdUnzip, QuaZip::open(), and removeFile().
                                                                                           {
    // Creo lo zip
    QuaZip zip(fileCompressed);
    if(!zip.open(QuaZip::mdUnzip)) {
        return QStringList();
    }
    // Estraggo i file
    QStringList extracted;
    for (int i=0; i<files.count(); i++) {
        QString absPath = QDir(dir).absoluteFilePath(files.at(i));
        if (!extractFile(&zip, files.at(i), absPath)) {
            removeFile(extracted);
            return QStringList();
        }
        extracted.append(absPath);
    }
    // Chiudo il file zip
    zip.close();
    if(zip.getZipError()!=0) {
        removeFile(extracted);
        return QStringList();
    }
    return extracted;
}
QStringList JlCompress::getFileList (QStringfileCompressed) [static]
OK Restituisce la lista dei file resenti nel file compresso fileCompressed.
Returns:
The list of the files in the archive, or, more precisely, the list of the entries, including both files and directories if they are present separately.
Se la funzione fallisce, restituisce un elenco vuoto.
La funzione fallisce se:
non si riesce ad aprire l'oggetto zip;
la richiesta di informazioni di un file fallisce;
non si riesce a chiudere l'oggetto zip;
Definition at line 492 of file JlCompress.cpp.
References QuaZip::close(), QuaZip::getCurrentFileInfo(), QuaZip::getZipError(), QuaZip::goToFirstFile(), QuaZip::goToNextFile(), QuaZip::mdUnzip, QuaZipFileInfo64::name, and QuaZip::open().
                                                          {
    // Apro lo zip
    QuaZip* zip = new QuaZip(QFileInfo(fileCompressed).absoluteFilePath());
    if(!zip->open(QuaZip::mdUnzip)) {
        delete zip;
        return QStringList();
    }
    // Estraggo i nomi dei file
    QStringList lst;
    QuaZipFileInfo64 info;
    for(bool more=zip->goToFirstFile(); more; more=zip->goToNextFile()) {
      if(!zip->getCurrentFileInfo(&info)) {
          delete zip;
          return QStringList();
      }
      lst << info.name;
      //info.name.toLocal8Bit().constData()
    }
    // Chiudo il file zip
    zip->close();
    if(zip->getZipError()!=0) {
        delete zip;
        return QStringList();
    }
    delete zip;
    return lst;
}
bool JlCompress::removeFile (QStringListlistFile) [static], [private]
Rimuove i file il cui nome e specificato all'interno di listFile.
Parameters:
listFile The list of files to remove.
Returns:
true if success, false otherwise.
Restituisce true se tutti i file sono stati cancellati correttamente, attenzione perche puo restituire false anche se alcuni file non esistevano e si e tentato di cancellarli.
Definition at line 241 of file JlCompress.cpp.
Referenced by extractDir(), extractFile(), and extractFiles().
                                                {
    bool ret = true;
    // Per ogni file
    for (int i=0; i<listFile.count(); i++) {
        // Lo elimino
        ret = ret && QFile::remove(listFile.at(i));
    }
    return ret;
}
Author
Generated automatically by Doxygen for ckb-next from the source code.