KbAnimWidget
NAME
KbAnimWidget -
SYNOPSIS
#include <src/ckb/kbanimwidget.h>
Inherits QWidget.
Signals
void animChanged (KbAnim *selection)
void didUpdateSelection (QStringList keys)
Public Member Functions
KbAnimWidget (QWidget *parent=0)
~KbAnimWidget ()
void setLight (KbLight *newLight)
void addAnim (const AnimScript *base, const QStringList &keyList, const QString &name, const QMap< QString, QVariant > &preset)
void duplicateAnim (KbAnim *old)
void clearSelection ()
void setSelectedKeys (const QStringList &keys)
Private Slots
void on_animList_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous)
void on_animList_itemChanged (QListWidgetItem *item)
void on_animList_customContextMenuRequested (const QPoint &pos)
void on_nameBox_textEdited (const QString &arg1)
void on_opacityBox_valueChanged (double arg1)
void on_blendBox_activated (int index)
void on_keyButton_clicked ()
void on_deleteButton_clicked ()
void refreshList ()
void reorderAnims ()
void on_propertyButton_clicked ()
Private Member Functions
void setCurrent (KbAnim *newCurrent)
Private Attributes
KbLight * light
QHash< QUuid, KbAnim * > animations
KbAnim * current
QStringList selectedKeys
bool noReorder
Ui::KbAnimWidget * ui
Detailed Description
Definition at line 15 of file kbanimwidget.h.
Constructor & Destructor Documentation
KbAnimWidget::KbAnimWidget (QWidget *parent = 0) [explicit]
Definition at line 7 of file kbanimwidget.cpp.
References Ui_KbAnimWidget::animList, reorderAnims(), setCurrent(), Ui_KbAnimWidget::setupUi(), and ui.
                                          :
    QWidget(parent), light(0), current(0), noReorder(false),
    ui(new Ui::KbAnimWidget)
{
    ui->setupUi(this);
    ui->animList->setVisible(false);
    setCurrent(0);
    connect(ui->animList, SIGNAL(orderChanged()), this, SLOT(reorderAnims()));
}
KbAnimWidget::~KbAnimWidget ()
Definition at line 17 of file kbanimwidget.cpp.
References ui.
                           {
    delete ui;
}
Member Function Documentation
void KbAnimWidget::addAnim (const AnimScript *base, const QStringList &keyList, const QString &name, const QMap< QString, QVariant > &preset)
Definition at line 82 of file kbanimwidget.cpp.
References KbLight::addAnim(), animations, Ui_KbAnimWidget::animList, KbAnim::guid(), light, KbAnim::name(), Ui_KbAnimWidget::noAnimLabel, noReorder, on_propertyButton_clicked(), setCurrent(), and ui.
Referenced by KbLightWidget::on_animButton_clicked().
                                                                                                                                        {
    if(!light)
        return;
    noReorder = true;
    KbAnim* animation = light->addAnim(base, keyList, name, preset);
    QListWidgetItem* item = new QListWidgetItem(animation->name(), ui->animList);
    item->setData(Qt::UserRole, animation->guid());
    item->setFlags(item->flags() | Qt::ItemIsEditable);
    animations[animation->guid()] = animation;
    ui->animList->addItem(item);
    ui->animList->setCurrentItem(item);
    ui->animList->setVisible(true);
    ui->noAnimLabel->setVisible(false);
    setCurrent(animation);
    noReorder = false;
    // Activate settings dialog
    on_propertyButton_clicked();
}
void KbAnimWidget::animChanged (KbAnim *selection) [signal]
Definition at line 213 of file moc_kbanimwidget.cpp.
Referenced by setCurrent().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
void KbAnimWidget::clearSelection ()
Definition at line 77 of file kbanimwidget.cpp.
References Ui_KbAnimWidget::animList, setCurrent(), and ui.
Referenced by KbLightWidget::setLight().
                                 {
    ui->animList->setCurrentItem(0);
    setCurrent(0);
}
void KbAnimWidget::didUpdateSelection (QStringListkeys) [signal]
Definition at line 220 of file moc_kbanimwidget.cpp.
Referenced by on_keyButton_clicked().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 1, _a);
}
void KbAnimWidget::duplicateAnim (KbAnim *old)
Definition at line 103 of file kbanimwidget.cpp.
References KbLight::animList(), Ui_KbAnimWidget::animList, KbLight::duplicateAnim(), light, Ui_KbAnimWidget::noAnimLabel, noReorder, refreshList(), setCurrent(), and ui.
Referenced by on_animList_customContextMenuRequested().
                                           {
    if(!light)
        return;
    noReorder = true;
    KbAnim* animation = light->duplicateAnim(old);
    // Refresh the list. insertItem doesn't seem to place the item in the correct position on its own...
    refreshList();
    ui->animList->setCurrentRow(light->animList().indexOf(animation));
    ui->animList->setVisible(true);
    ui->noAnimLabel->setVisible(false);
    setCurrent(animation);
    noReorder = false;
}
void KbAnimWidget::on_animList_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous) [private], [slot]
Definition at line 151 of file kbanimwidget.cpp.
References animations, and setCurrent().
                                                                                                    {
    if(!current)
        setCurrent(0);
    else
        setCurrent(animations[current->data(Qt::UserRole).toUuid()]);
}
void KbAnimWidget::on_animList_customContextMenuRequested (const QPoint &pos) [private], [slot]
Definition at line 169 of file kbanimwidget.cpp.
References animations, Ui_KbAnimWidget::animList, current, duplicateAnim(), on_deleteButton_clicked(), setCurrent(), and ui.
                                                                          {
    QListWidgetItem* item = ui->animList->itemAt(pos);
    if(!item)
        return;
    setCurrent(animations[item->data(Qt::UserRole).toUuid()]);
    QMenu menu(this);
    QAction* rename = new QAction("Rename...", this);
    QAction* duplicate = new QAction("Duplicate", this);
    QAction* del = new QAction("Delete", this);
    menu.addAction(rename);
    menu.addAction(duplicate);
    menu.addAction(del);
    QAction* result = menu.exec(QCursor::pos());
    if(result == rename)
        ui->animList->editItem(item);
    else if(result == duplicate)
        duplicateAnim(current);
    else if(result == del)
        on_deleteButton_clicked();
}
void KbAnimWidget::on_animList_itemChanged (QListWidgetItem *item) [private], [slot]
Definition at line 158 of file kbanimwidget.cpp.
References anim, animations, current, KbAnim::name(), Ui_KbAnimWidget::nameBox, noReorder, and ui.
                                                               {
    if(item){
        KbAnim* anim = animations[item->data(Qt::UserRole).toUuid()];
        if(anim){
            anim->name(item->text().trimmed());
            if(anim == current && !noReorder)
                ui->nameBox->setText(anim->name());
        }
    }
}
void KbAnimWidget::on_blendBox_activated (intindex) [private], [slot]
Definition at line 205 of file kbanimwidget.cpp.
References current, and KbAnim::mode().
                                                 {
    if(current)
        current->mode((KbAnim::Mode)index);
}
void KbAnimWidget::on_deleteButton_clicked () [private], [slot]
Definition at line 226 of file kbanimwidget.cpp.
References animations, KbLight::animList(), Ui_KbAnimWidget::animList, current, KbAnim::guid(), light, Ui_KbAnimWidget::noAnimLabel, KbLight::restartAnimation(), setCurrent(), and ui.
Referenced by on_animList_customContextMenuRequested().
                                          {
    if(current){
        animations.remove(current->guid());
        QList<KbAnim*> animList = light->animList();
        animList.removeAll(current);
        light->animList(animList);
        current->deleteLater();
        setCurrent(0);
        delete ui->animList->currentItem();
        if(animations.count() == 0){
            ui->animList->setVisible(false);
            ui->noAnimLabel->setVisible(true);
        }
    }
    light->restartAnimation();
}
void KbAnimWidget::on_keyButton_clicked () [private], [slot]
Definition at line 210 of file kbanimwidget.cpp.
References KeyMap::contains(), current, didUpdateSelection(), KbAnim::keys(), light, KbLight::map(), KbLight::restartAnimation(), and selectedKeys.
                                       {
    if(current){
        QStringList keys = selectedKeys;
        // If any keys were selected previously that aren't in the keymap now, leave them in
        // This is important for layout compatibility - e.g. being able to select both bslash_iso and bslash, because no single layout contains both
        const KeyMap& map = light->map();
        foreach(const QString& key, current->keys()){
            if(!map.contains(key))
                keys << key;
        }
        current->keys(keys);
        emit didUpdateSelection(selectedKeys);
    }
    light->restartAnimation();
}
void KbAnimWidget::on_nameBox_textEdited (const QString &arg1) [private], [slot]
Definition at line 191 of file kbanimwidget.cpp.
References Ui_KbAnimWidget::animList, current, KbAnim::name(), noReorder, and ui.
Referenced by on_propertyButton_clicked().
                                                           {
    if(current){
        noReorder = true;
        current->name(arg1.trimmed());
        ui->animList->currentItem()->setText(current->name());
        noReorder = false;
    }
}
void KbAnimWidget::on_opacityBox_valueChanged (doublearg1) [private], [slot]
Definition at line 200 of file kbanimwidget.cpp.
References current, and KbAnim::opacity().
                                                        {
    if(current)
        current->opacity(arg1 / 100.);
}
void KbAnimWidget::on_propertyButton_clicked () [private], [slot]
Definition at line 243 of file kbanimwidget.cpp.
References KbAnim::commitParams(), current, light, AnimSettingDialog::name(), Ui_KbAnimWidget::nameBox, on_nameBox_textEdited(), KbAnim::reInit(), KbAnim::resetParams(), KbLight::restartAnimation(), and ui.
Referenced by addAnim().
                                            {
    if(!current)
        return;
    // Present animation property popup
    AnimSettingDialog dialog(this, current);
    dialog.exec();
    if(dialog.result() != QDialog::Accepted){
        current->resetParams();
        return;
    }
    // Apply settings and restart all animations
    current->commitParams();
    current->reInit();
    light->restartAnimation();
    // Update name
    ui->nameBox->setText(dialog.name());
    on_nameBox_textEdited(dialog.name());
}
void KbAnimWidget::refreshList () [private], [slot]
Definition at line 32 of file kbanimwidget.cpp.
References anim, animations, KbLight::animList(), Ui_KbAnimWidget::animList, KbAnim::guid(), light, KbAnim::name(), Ui_KbAnimWidget::noAnimLabel, noReorder, setCurrent(), and ui.
Referenced by duplicateAnim(), and setLight().
                              {
    noReorder = true;
    setCurrent(0);
    ui->animList->clear();
    animations.clear();
    // Add the animations from the new lighting mode
    if(!light){
        ui->animList->setVisible(false);
        ui->noAnimLabel->setVisible(true);
        return;
    }
    QList<KbAnim*> newAnimations = light->animList();
    if(newAnimations.count() == 0){
        ui->animList->setVisible(false);
        ui->noAnimLabel->setVisible(true);
        return;
    }
    ui->animList->setVisible(true);
    foreach(KbAnim* anim, newAnimations){
        QListWidgetItem* item = new QListWidgetItem(anim->name(), ui->animList);
        item->setData(Qt::UserRole, anim->guid());
        item->setFlags(item->flags() | Qt::ItemIsEditable);
        animations[anim->guid()] = anim;
        ui->animList->addItem(item);
    }
    ui->noAnimLabel->setVisible(false);
    noReorder = false;
}
void KbAnimWidget::reorderAnims () [private], [slot]
Definition at line 61 of file kbanimwidget.cpp.
References anim, animations, KbLight::animList(), Ui_KbAnimWidget::animList, light, noReorder, and ui.
Referenced by KbAnimWidget().
                               {
    if(light && !noReorder){
        // Clear and rebuild the list of animations in case the animation moved
        int count = ui->animList->count();
        QList<KbAnim*> animList;
        for(int i = 0; i < count; i++){
            QListWidgetItem* item = ui->animList->item(i);
            KbAnim* anim = animations[item->data(Qt::UserRole).toUuid()];
            if(anim && !animList.contains(anim))
                animList.append(anim);
            item->setFlags(item->flags() | Qt::ItemIsEditable);
        }
        light->animList(animList);
    }
}
void KbAnimWidget::setCurrent (KbAnim *newCurrent) [private]
Definition at line 118 of file kbanimwidget.cpp.
References Ui_KbAnimWidget::aCopyLabel, Ui_KbAnimWidget::aMissingLabel, Ui_KbAnimWidget::aNameLabel, animChanged(), Ui_KbAnimWidget::aVerLabel, Ui_KbAnimWidget::blendBox, AnimScript::copyright(), current, KbAnim::keys(), KbAnim::mode(), AnimScript::name(), KbAnim::name(), Ui_KbAnimWidget::nameBox, KbAnim::opacity(), Ui_KbAnimWidget::opacityBox, KbAnim::script(), KbAnim::scriptName(), selectedKeys, Ui_KbAnimWidget::selectionStack, ui, and AnimScript::version().
Referenced by addAnim(), clearSelection(), duplicateAnim(), KbAnimWidget(), on_animList_currentItemChanged(), on_animList_customContextMenuRequested(), on_deleteButton_clicked(), and refreshList().
                                               {
    if(newCurrent != current)
        emit animChanged(current = newCurrent);
    if(!current){
        selectedKeys.clear();
        ui->selectionStack->setCurrentIndex(0);
        return;
    }
    selectedKeys = current->keys();
    const AnimScript* script = current->script();
    if(!script){
        ui->selectionStack->setCurrentIndex(2);
        ui->aMissingLabel->setText("The \"" + current->scriptName() + "\" script could not be loaded. Please check your animation directory.");
        return;
    }
    ui->selectionStack->setCurrentIndex(1);
    ui->aNameLabel->setText(script->name());
    ui->aVerLabel->setText("v" + script->version());
    ui->aCopyLabel->setText(script->copyright());
    ui->nameBox->setText(current->name());
    ui->opacityBox->setValue(current->opacity() * 100.);
    ui->blendBox->setCurrentIndex((int)current->mode());
}
void KbAnimWidget::setLight (KbLight *newLight)
Definition at line 21 of file kbanimwidget.cpp.
References light, and refreshList().
Referenced by KbLightWidget::setLight().
                                            {
    if(light != newLight){
        if(light)
            disconnect(light, SIGNAL(didLoad()), this, SLOT(refreshList()));
        if(newLight)
            connect(newLight, SIGNAL(didLoad()), this, SLOT(refreshList()));
        light = newLight;
    }
    refreshList();
}
void KbAnimWidget::setSelectedKeys (const QStringList &keys)
Definition at line 143 of file kbanimwidget.cpp.
References Ui_KbAnimWidget::keyButton, selectedKeys, and ui.
Referenced by KbLightWidget::newSelection().
                                                         {
    selectedKeys = keys;
    if(keys.count() == 0)
        ui->keyButton->setVisible(false);
    else
        ui->keyButton->setVisible(true);
}
Field Documentation
QHash<QUuid, KbAnim*> KbAnimWidget::animations [private]
Definition at line 53 of file kbanimwidget.h.
Referenced by addAnim(), on_animList_currentItemChanged(), on_animList_customContextMenuRequested(), on_animList_itemChanged(), on_deleteButton_clicked(), refreshList(), and reorderAnims().
KbAnim* KbAnimWidget::current [private]
Definition at line 55 of file kbanimwidget.h.
Referenced by on_animList_customContextMenuRequested(), on_animList_itemChanged(), on_blendBox_activated(), on_deleteButton_clicked(), on_keyButton_clicked(), on_nameBox_textEdited(), on_opacityBox_valueChanged(), on_propertyButton_clicked(), and setCurrent().
KbLight* KbAnimWidget::light [private]
Definition at line 52 of file kbanimwidget.h.
Referenced by addAnim(), duplicateAnim(), on_deleteButton_clicked(), on_keyButton_clicked(), on_propertyButton_clicked(), refreshList(), reorderAnims(), and setLight().
bool KbAnimWidget::noReorder [private]
Definition at line 58 of file kbanimwidget.h.
Referenced by addAnim(), duplicateAnim(), on_animList_itemChanged(), on_nameBox_textEdited(), refreshList(), and reorderAnims().
QStringList KbAnimWidget::selectedKeys [private]
Definition at line 57 of file kbanimwidget.h.
Referenced by on_keyButton_clicked(), setCurrent(), and setSelectedKeys().
Ui::KbAnimWidget* KbAnimWidget::ui [private]
Definition at line 60 of file kbanimwidget.h.
Referenced by addAnim(), clearSelection(), duplicateAnim(), KbAnimWidget(), on_animList_customContextMenuRequested(), on_animList_itemChanged(), on_deleteButton_clicked(), on_nameBox_textEdited(), on_propertyButton_clicked(), refreshList(), reorderAnims(), setCurrent(), setSelectedKeys(), and ~KbAnimWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.