KbAnim
NAME
KbAnim -
SYNOPSIS
#include <src/ckb/kbanim.h>
Inherits QObject.
Public Types
enum Mode { Normal, Add, Subtract, Multiply, Divide }
Public Member Functions
KbAnim (QObject *parent, const KeyMap &map, const QUuid id, CkbSettings &settings)
void save (CkbSettings &settings)
bool needsSave () const
KbAnim (QObject *parent, const KeyMap &map, const QString &name, const QStringList &keys, const AnimScript *script)
KbAnim (QObject *parent, const KeyMap &map, const KbAnim &other)
const KeyMap & map ()
void map (const KeyMap &newMap)
const QStringList & keys ()
void keys (const QStringList &newKeys)
bool hasParameter (const QString &name) const
QVariant parameter (const QString &name) const
void parameter (const QString &name, const QVariant &value)
void commitParams ()
void resetParams ()
void reInit ()
void trigger (quint64 timestamp, bool ignoreParameter=false)
void keypress (const QString &key, bool pressed, quint64 timestamp)
void stop ()
bool isActive () const
bool isRunning () const
void blend (ColorMap &animMap, quint64 timestamp)
const QUuid & guid () const
void newId ()
const QString & name () const
void name (const QString &newName)
float opacity () const
void opacity (float newOpacity)
Mode mode () const
void mode (Mode newMode)
const AnimScript * script () const
const QString & scriptName () const
Private Member Functions
QMap< QString, QVariant > effectiveParams ()
void updateParams ()
void catchUp (quint64 timestamp)
Private Attributes
AnimScript * _script
QUuid _scriptGuid
QString _scriptName
KeyMap _map
QStringList _keys
QMap< QString, QVariant > _parameters
QMap< QString, QVariant > _tempParameters
QString repeatKey
quint64 repeatTime
quint64 kpRepeatTime
quint64 stopTime
quint64 kpStopTime
int repeatMsec
int kpRepeatMsec
QUuid _guid
QString _name
float _opacity
Mode _mode
bool _isActive
bool _isActiveKp
bool _needsSave
Detailed Description
Definition at line 11 of file kbanim.h.
Member Enumeration Documentation
enum KbAnim::Mode
Enumerator
Normal
Add
Subtract
Multiply
Divide
Definition at line 17 of file kbanim.h.
              {
        Normal,
        Add,
        Subtract,
        Multiply,
        Divide
    };
Constructor & Destructor Documentation
KbAnim::KbAnim (QObject *parent, const KeyMap &map, const QUuidid, CkbSettings &settings)
Definition at line 8 of file kbanim.cpp.
References _guid, _keys, _map, _mode, _name, _opacity, _parameters, _script, _scriptGuid, _scriptName, CkbSettings::childKeys(), AnimScript::copy(), AnimScript::Param::defaultValue, KeyMap::fromStorage(), AnimScript::Param::INVALID, AnimScript::Param::LABEL, AnimScript::Param::name, AnimScript::name(), name(), Normal, AnimScript::param(), AnimScript::paramIterator(), reInit(), AnimScript::Param::type, and CkbSettings::value().
                                                                                        :
    QObject(parent), _script(0), _map(map),
    repeatTime(0), kpRepeatTime(0), stopTime(0), kpStopTime(0), repeatMsec(0), kpRepeatMsec(0),
    _guid(id), _isActive(false), _isActiveKp(false), _needsSave(false)
{
    SGroup group(settings, _guid.toString().toUpper());
    _keys = settings.value("Keys").toStringList();
    // Convert key list from storage names if needed
    if(!settings.value("UseRealNames").toBool()){
        QMutableListIterator<QString> i(_keys);
        while(i.hasNext()){
            i.next();
            QString& key = i.value();
            key = _map.fromStorage(key);
        }
    }
    _name = settings.value("Name").toString().trimmed();
    _opacity = settings.value("Opacity").toString().toDouble();
    if(_opacity < 0.)
        _opacity = 0.;
    else if(_opacity > 1.)
        _opacity = 1.;
    bool modeOk = false;
    _mode = (Mode)metaObject()->enumerator(metaObject()->indexOfEnumerator("Mode")).keysToValue(settings.value("BlendMode").toString().toLatin1(), &modeOk);
    if(!modeOk)
        _mode = Normal;
    _scriptName = settings.value("ScriptName").toString().trimmed();
    _scriptGuid = settings.value("ScriptGuid").toString();
    {
        SGroup group(settings, "Parameters");
        foreach(const QString& param, settings.childKeys())
            _parameters[param.toLower()] = settings.value(param);
    }
    if(!_scriptGuid.isNull()){
        _script = AnimScript::copy(this, _scriptGuid);
        if(_script){
            // Remove nonexistant parameters
            foreach(const QString& name, _parameters.keys()){
                AnimScript::Param param = _script->param(name);
                if(param.type == AnimScript::Param::INVALID || param.type == AnimScript::Param::LABEL)
                    _parameters.remove(name);
            }
            // Add defaults for unset parameters
            QListIterator<AnimScript::Param> i = _script->paramIterator();
            while(i.hasNext()){
                AnimScript::Param param = i.next();
                if(!_parameters.contains(param.name) && param.type != AnimScript::Param::LABEL)
                    _parameters[param.name] = param.defaultValue;
            }
            _scriptName = _script->name();
            reInit();
        }
    }
}
KbAnim::KbAnim (QObject *parent, const KeyMap &map, const QString &name, const QStringList &keys, const AnimScript *script)
Definition at line 84 of file kbanim.cpp.
References _parameters, _script, _scriptGuid, _scriptName, AnimScript::Param::defaultValue, AnimScript::guid(), AnimScript::Param::LABEL, AnimScript::Param::name, AnimScript::name(), AnimScript::paramIterator(), reInit(), and AnimScript::Param::type.
                                                                                                                         :
    QObject(parent),
    _script(AnimScript::copy(this, script->guid())), _map(map), _keys(keys),
    repeatTime(0), kpRepeatTime(0), stopTime(0), kpStopTime(0), repeatMsec(0), kpRepeatMsec(0),
    _guid(QUuid::createUuid()), _name(name), _opacity(1.), _mode(Normal), _isActive(false), _isActiveKp(false), _needsSave(true)
{
    if(_script){
        // Set default parameters
        QListIterator<AnimScript::Param> i = _script->paramIterator();
        while(i.hasNext()){
            AnimScript::Param param = i.next();
            if(param.type != AnimScript::Param::LABEL)
                _parameters[param.name] = param.defaultValue;
        }
        _scriptGuid = script->guid();
        _scriptName = script->name();
        reInit();
    }
}
KbAnim::KbAnim (QObject *parent, const KeyMap &map, const KbAnim &other)
Definition at line 104 of file kbanim.cpp.
References reInit().
                                                                      :
    QObject(parent),
    _script(AnimScript::copy(this, other.script()->guid())), _scriptGuid(_script->guid()), _scriptName(_script->name()),
    _map(map), _keys(other._keys), _parameters(other._parameters),
    repeatTime(0), kpRepeatTime(0), stopTime(0), kpStopTime(0), repeatMsec(0), kpRepeatMsec(0),
    _guid(other._guid), _name(other._name), _opacity(other._opacity), _mode(other._mode), _isActive(false), _isActiveKp(false), _needsSave(true)
{
    reInit();
}
Member Function Documentation
void KbAnim::blend (ColorMap &animMap, quint64timestamp)
Definition at line 365 of file kbanim.cpp.
References _mode, _opacity, _script, catchUp(), ColorMap::colors(), AnimScript::colors(), ColorMap::count(), AnimScript::frame(), and functions.
Referenced by KbLight::frameUpdate().
                                                      {
    if(!_script)
        return;
    // Fetch the next frame from the script
    catchUp(timestamp);
    _script->frame(timestamp);
    // Blend the script's map with the current map
    int blendMode = (int)_mode;
    blendFunc blend = functions[blendMode];
    float fOpacity = _opacity / 255.f; // save some math by pre-dividing the 255 for qAlpha
    const ColorMap& scriptMap = _script->colors();
    int count = animMap.count();
    if(scriptMap.count() != count){
        qDebug() << "Script map didn't match base map (" << count << " vs " << scriptMap.count() << "). This should never happen.";
        return;
    }
    QRgb* background = animMap.colors();
    const QRgb* foreground = scriptMap.colors();
    for(int i = 0; i < count; i++){
        // Mix the colors in with the color map according to blend mode and alpha
        QRgb& bg = background[i];
        QRgb fg = foreground[i];
        int alpha = qAlpha(fg);
        if(alpha == 0)
            continue;
        if(blendMode == 0){
            // Blend: normal
            // This is the most common use case and it requires much less arithmetic
            if(alpha == 255){
                bg = fg;
            } else {
                float r = qRed(bg), g = qGreen(bg), b = qBlue(bg);
                float a = alpha * fOpacity;
                r = r * (1.f - a) + qRed(fg) * a;
                g = g * (1.f - a) + qGreen(fg) * a;
                b = b * (1.f - a) + qBlue(fg) * a;
                bg = qRgb(round(r), round(g), round(b));
            }
        } else {
            // Use blend function
            float r = qRed(bg) / 255.f, g = qGreen(bg) / 255.f, b = qBlue(bg) / 255.f;
            float a = alpha * fOpacity;
            r = r * (1.f - a) + blend(r, qRed(fg) / 255.f) * a;
            g = g * (1.f - a) + blend(g, qGreen(fg) / 255.f) * a;
            b = b * (1.f - a) + blend(b, qBlue(fg) / 255.f) * a;
            bg = qRgb(round(r * 255.f), round(g * 255.f), round(b * 255.f));
        }
    }
}
void KbAnim::catchUp (quint64timestamp) [private]
Definition at line 166 of file kbanim.cpp.
References _isActive, _isActiveKp, _script, effectiveParams(), AnimScript::end(), AnimScript::keypress(), kpRepeatMsec, kpRepeatTime, kpStopTime, repeatKey, repeatMsec, repeatTime, AnimScript::retrigger(), and stopTime.
Referenced by blend(), keypress(), and trigger().
                                     {
    QMap<QString, QVariant> parameters = effectiveParams();
    // Stop the animation if its time has run out
    if(stopTime != 0 && timestamp >= stopTime){
        repeatMsec = repeatTime = 0;
        if(!parameters.contains("repeat")){
            // If repeats aren't allowed, stop the animation entirely
            _script->end();
            _isActive = false;
            return;
        } else
            // Otherwise, simply stop repeating
            stopTime = 0;
    }
    if(kpStopTime != 0 && timestamp >= kpStopTime){
        kpRepeatMsec = kpRepeatTime = 0;
        if(!parameters.contains("kprepeat")){
            _script->end();
            _isActiveKp = false;
            return;
        } else
            kpStopTime = 0;
    }
    // Restart (or start, if there was a delay) the animation if its repeat time is up
    while(repeatTime > 0 && timestamp >= repeatTime){
        _script->retrigger(repeatTime);
        if(repeatMsec <= 0){
            repeatTime = 0;
            break;
        }
        repeatTime += repeatMsec;
    }
    while(kpRepeatTime > 0 && timestamp >= kpRepeatTime){
        _script->keypress(repeatKey, 1, kpRepeatTime);
        if(kpRepeatMsec <= 0){
            kpRepeatTime = 0;
            break;
        }
        kpRepeatTime += kpRepeatMsec;
    }
}
void KbAnim::commitParams ()
Definition at line 121 of file kbanim.cpp.
References _needsSave, _parameters, _tempParameters, and effectiveParams().
Referenced by KbLight::addAnim(), KbAnimWidget::on_propertyButton_clicked(), and KbLight::previewAnim().
                         {
    _needsSave = true;
    _parameters = effectiveParams();
    _tempParameters.clear();
}
QMap< QString, QVariant > KbAnim::effectiveParams () [private]
Definition at line 138 of file kbanim.cpp.
References _parameters, and _tempParameters.
Referenced by catchUp(), commitParams(), keypress(), reInit(), trigger(), and updateParams().
                                               {
    QMap<QString, QVariant> res = _parameters;
    // Apply all uncommited parameters
    QMapIterator<QString, QVariant> i(_tempParameters);
    while(i.hasNext()){
        i.next();
        res[i.key()] = i .value();
    }
    return res;
}
const QUuid& KbAnim::guid () const [inline]
Definition at line 71 of file kbanim.h.
References _guid.
Referenced by KbAnimWidget::addAnim(), RebindWidget::applyChanges(), KbLight::findAnim(), KbAnimWidget::on_deleteButton_clicked(), KbAnimWidget::refreshList(), and KbLight::save().
{ return _guid; }
bool KbAnim::hasParameter (const QString &name) const [inline]
Definition at line 44 of file kbanim.h.
References _parameters.
Referenced by AnimSettingDialog::AnimSettingDialog().
{ return _parameters.contains(name); }
bool KbAnim::isActive () const [inline]
Definition at line 63 of file kbanim.h.
References _isActive, and _isActiveKp.
Referenced by KeyAction::keyEvent(), and keypress().
{ return _isActive || _isActiveKp; }
bool KbAnim::isRunning () const
Definition at line 325 of file kbanim.cpp.
References _script, and AnimScript::hasFrame().
Referenced by KbLight::isStarted().
                             {
    if(!_script)
        return true; // If the script wasn't loaded, pretend it's running anyway so it won't lock up
    return _script->hasFrame();
}
void KbAnim::keypress (const QString &key, boolpressed, quint64timestamp)
Definition at line 250 of file kbanim.cpp.
References _isActive, _isActiveKp, _script, catchUp(), effectiveParams(), AnimScript::frame(), isActive(), AnimScript::keypress(), kpRepeatMsec, kpRepeatTime, kpStopTime, repeatKey, repeatMsec, repeatTime, stop(), AnimScript::stop(), and stopTime.
Referenced by KbLight::animKeypress().
                                                                        {
    if(!_script)
        return;
    QMap<QString, QVariant> parameters = effectiveParams();
    if(pressed && parameters.value("kpmodestop").toBool()){
        // If stop on key press is enabled, stop mode-wide animation
        catchUp(timestamp);
        _script->stop(timestamp);
        stopTime = repeatTime = repeatMsec = 0;
        _isActive = false;
    } else {
        if(!parameters.value("kptrigger").toBool())
            return;
        catchUp(timestamp);
    }
    if(pressed){
        // Key pressed
        _isActiveKp = true;
        if(parameters.value("kpmode", 0).toInt() == 2 && isActive())
            // If mode is start once and a key has already been pressed, do nothing
            return;
        int delay = round(parameters.value("kpdelay").toDouble() * 1000.);
        if(delay > 0){
            // If delay is enabled, wait to trigger the event
            timestamp += delay;
            kpRepeatTime = timestamp;
        } else
            _script->keypress(key, pressed, timestamp);
        int repeat = round(parameters.value("kprepeat").toDouble() * 1000.);
        if(repeat <= 0){
            // If no repeat allowed, calculate stop time in seconds
            kpRepeatMsec = -1;
            double stop = parameters.value("kpstop").toDouble();
            if(stop <= 0.)
                kpStopTime = 0;
            else
                kpStopTime = timestamp + round(stop * 1000.);
        } else {
            // If repeat is allowed, calculate stop time in repetitions
            kpRepeatMsec = repeat;
            if(delay <= 0)
                kpRepeatTime = timestamp + repeat;
            int stop = parameters.value("kpstop").toInt();
            if(stop < 0)
                kpStopTime = 0;
            else
                kpStopTime = timestamp + repeat * (1 + stop);
        }
        repeatKey = key;
    } else {
        // Key released
        _isActiveKp = false;
        _script->keypress(key, pressed, timestamp);
        if(parameters.value("kprelease").toBool())
            // Stop repeating keypress if "Stop on key release" is enabled
            kpStopTime = timestamp;
    }
    _script->frame(timestamp);
}
const QStringList& KbAnim::keys () [inline]
Definition at line 40 of file kbanim.h.
References _keys.
Referenced by KbLight::animKeypress(), KbLightWidget::changeAnim(), KbAnimWidget::on_keyButton_clicked(), and KbAnimWidget::setCurrent().
{ return _keys; }
void KbAnim::keys (const QStringList &newKeys)
Definition at line 161 of file kbanim.cpp.
References _keys, and reInit().
                                           {
    _keys = newKeys;
    reInit();
}
const KeyMap& KbAnim::map () [inline]
Definition at line 37 of file kbanim.h.
References _map.
Referenced by KbLight::map().
{ return _map; }
void KbAnim::map (const KeyMap &newMap)
Definition at line 156 of file kbanim.cpp.
References _map, and reInit().
                                    {
    _map = newMap;
    reInit();
}
Mode KbAnim::mode () const [inline]
Definition at line 77 of file kbanim.h.
References _mode.
Referenced by KbAnimWidget::on_blendBox_activated(), and KbAnimWidget::setCurrent().
{ return _mode; }
void KbAnim::mode (ModenewMode) [inline]
Definition at line 78 of file kbanim.h.
References _mode, and _needsSave.
{ _needsSave = true; _mode = newMode; }
const QString& KbAnim::name () const [inline]
Definition at line 73 of file kbanim.h.
References _name.
Referenced by KbAnimWidget::addAnim(), AnimSettingDialog::AnimSettingDialog(), KbAnim(), KbAnimWidget::on_animList_itemChanged(), KbAnimWidget::on_nameBox_textEdited(), parameter(), KbAnimWidget::refreshList(), KbAnimWidget::setCurrent(), and RebindWidget::setSelection().
{ return _name; }
void KbAnim::name (const QString &newName) [inline]
Definition at line 74 of file kbanim.h.
References _name, and _needsSave.
{ _needsSave = true; _name = newName; }
bool KbAnim::needsSave () const [inline]
Definition at line 29 of file kbanim.h.
References _needsSave.
Referenced by KbLight::needsSave().
{ return _needsSave; }
void KbAnim::newId () [inline]
Definition at line 72 of file kbanim.h.
References _guid, and _needsSave.
Referenced by KbLight::duplicateAnim(), and KbMode::newId().
{ _needsSave = true; _guid = QUuid::createUuid(); }
float KbAnim::opacity () const [inline]
Definition at line 75 of file kbanim.h.
References _opacity.
Referenced by KbAnimWidget::on_opacityBox_valueChanged(), and KbAnimWidget::setCurrent().
{ return _opacity; }
void KbAnim::opacity (floatnewOpacity) [inline]
Definition at line 76 of file kbanim.h.
References _needsSave, and _opacity.
{ _needsSave = true; _opacity = newOpacity; }
QVariant KbAnim::parameter (const QString &name) const [inline]
Definition at line 45 of file kbanim.h.
References _parameters.
Referenced by KbLight::addAnim(), AnimSettingDialog::AnimSettingDialog(), KbLight::previewAnim(), and AnimSettingDialog::updateParam().
{ return _parameters.value(name); }
void KbAnim::parameter (const QString &name, const QVariant &value)
Definition at line 114 of file kbanim.cpp.
References _script, _tempParameters, AnimScript::hasParam(), name(), and updateParams().
                                                                {
    if(!_script->hasParam(name))
        return;
    _tempParameters[name] = value;
    updateParams();
}
void KbAnim::reInit ()
Definition at line 149 of file kbanim.cpp.
References _isActive, _isActiveKp, _keys, _map, _script, effectiveParams(), AnimScript::init(), and repeatKey.
Referenced by KbAnim(), keys(), map(), KbAnimWidget::on_propertyButton_clicked(), and KbLight::previewAnim().
                   {
    if(_script)
        _script->init(_map, _keys, effectiveParams());
    repeatKey = "";
    _isActive = _isActiveKp = false;
}
void KbAnim::resetParams ()
Definition at line 127 of file kbanim.cpp.
References _tempParameters, and updateParams().
Referenced by KbAnimWidget::on_propertyButton_clicked().
                        {
    _tempParameters.clear();
    updateParams();
}
void KbAnim::save (CkbSettings &settings)
Definition at line 64 of file kbanim.cpp.
References _guid, _keys, _mode, _name, _needsSave, _opacity, _parameters, _scriptGuid, _scriptName, CkbSettings::beginGroup(), CkbSettings::endGroup(), and CkbSettings::setValue().
Referenced by KbLight::save().
                                      {
    _needsSave = false;
    settings.beginGroup(_guid.toString().toUpper());
    settings.setValue("UseRealNames", true);
    settings.setValue("Keys", _keys);
    settings.setValue("Name", _name);
    settings.setValue("Opacity", QString::number(_opacity));
    settings.setValue("BlendMode", metaObject()->enumerator(metaObject()->indexOfEnumerator("Mode")).valueToKey(_mode));
    settings.setValue("ScriptName", _scriptName);
    settings.setValue("ScriptGuid", _scriptGuid.toString().toUpper());
    settings.beginGroup("Parameters");
    QMapIterator<QString, QVariant> i(_parameters);
    while(i.hasNext()){
        i.next();
        settings.setValue(i.key(), i.value());
    }
    settings.endGroup();
    settings.endGroup();
}
const AnimScript* KbAnim::script () const [inline]
Definition at line 81 of file kbanim.h.
References _script.
Referenced by AnimSettingDialog::AnimSettingDialog(), KbAnimWidget::setCurrent(), and AnimSettingDialog::updateParam().
{ return _script; }
const QString& KbAnim::scriptName () const [inline]
Definition at line 82 of file kbanim.h.
References _scriptName.
Referenced by AnimSettingDialog::AnimSettingDialog(), and KbAnimWidget::setCurrent().
{ return _scriptName; }
void KbAnim::stop ()
Definition at line 312 of file kbanim.cpp.
References _isActive, _isActiveKp, _script, AnimScript::end(), kpRepeatMsec, kpRepeatTime, kpStopTime, repeatKey, repeatMsec, repeatTime, and stopTime.
Referenced by KbLight::addAnim(), KbLight::close(), KbLight::duplicateAnim(), KeyAction::keyEvent(), keypress(), KbLight::restartAnimation(), and trigger().
                 {
    if(_script)
        _script->end();
    repeatTime = 0;
    kpRepeatTime = 0;
    repeatMsec = 0;
    kpRepeatMsec = 0;
    stopTime = 0;
    kpStopTime = 0;
    repeatKey = "";
    _isActive = _isActiveKp = false;
}
void KbAnim::trigger (quint64timestamp, boolignoreParameter = false)
Definition at line 209 of file kbanim.cpp.
References _isActive, _script, catchUp(), effectiveParams(), AnimScript::frame(), repeatMsec, repeatTime, AnimScript::retrigger(), stop(), and stopTime.
Referenced by KbLight::addAnim(), KbLight::duplicateAnim(), KeyAction::keyEvent(), KbLight::open(), KbLight::previewAnim(), and KbLight::restartAnimation().
                                                           {
    if(!_script)
        return;
    QMap<QString, QVariant> parameters = effectiveParams();
    catchUp(timestamp);
    if(parameters.value("trigger").toBool() || ignoreParameter){
        _isActive = true;
        int delay = round(parameters.value("delay").toDouble() * 1000.);
        if(delay > 0){
            // If delay is enabled, wait to trigger the event
            timestamp += delay;
            repeatTime = timestamp;
        } else
            _script->retrigger(timestamp, true);
        int repeat = round(parameters.value("repeat").toDouble() * 1000.);
        if(repeat <= 0){
            // If no repeat allowed, calculate stop time in seconds
            repeatMsec = -1;
            double stop = parameters.value("stop").toDouble();
            if(stop <= 0)
                stopTime = 0;
            else
                stopTime = timestamp + round(stop * 1000.);
        } else {
            // If repeat is allowed, calculate stop time in repetitions
            repeatMsec = repeat;
            if(delay <= 0)
                repeatTime = timestamp + repeat;
            int stop = parameters.value("stop").toInt();
            if(stop < 0)
                stopTime = 0;
            else
                stopTime = timestamp + repeat * (1 + stop);
        }
    }
    // Ask the script for a frame even if we didn't do anything here. This way ckb knows the script is responding.
    _script->frame(timestamp);
}
void KbAnim::updateParams () [private]
Definition at line 132 of file kbanim.cpp.
References _script, effectiveParams(), AnimScript::parameters(), and repeatKey.
Referenced by parameter(), and resetParams().
                         {
    if(_script)
        _script->parameters(effectiveParams());
    repeatKey = "";
}
Field Documentation
QUuid KbAnim::_guid [private]
Definition at line 110 of file kbanim.h.
Referenced by guid(), KbAnim(), newId(), and save().
bool KbAnim::_isActive [private]
Definition at line 114 of file kbanim.h.
Referenced by catchUp(), isActive(), keypress(), reInit(), stop(), and trigger().
bool KbAnim::_isActiveKp [private]
Definition at line 114 of file kbanim.h.
Referenced by catchUp(), isActive(), keypress(), reInit(), and stop().
QStringList KbAnim::_keys [private]
Definition at line 92 of file kbanim.h.
Referenced by KbAnim(), keys(), reInit(), and save().
KeyMap KbAnim::_map [private]
Definition at line 91 of file kbanim.h.
Referenced by KbAnim(), map(), and reInit().
Mode KbAnim::_mode [private]
Definition at line 113 of file kbanim.h.
Referenced by blend(), KbAnim(), mode(), and save().
QString KbAnim::_name [private]
Definition at line 111 of file kbanim.h.
Referenced by KbAnim(), name(), and save().
bool KbAnim::_needsSave [private]
Definition at line 115 of file kbanim.h.
Referenced by commitParams(), mode(), name(), needsSave(), newId(), opacity(), and save().
float KbAnim::_opacity [private]
Definition at line 112 of file kbanim.h.
Referenced by blend(), KbAnim(), opacity(), and save().
QMap<QString, QVariant> KbAnim::_parameters [private]
Definition at line 94 of file kbanim.h.
Referenced by commitParams(), effectiveParams(), hasParameter(), KbAnim(), parameter(), and save().
AnimScript* KbAnim::_script [private]
Definition at line 86 of file kbanim.h.
Referenced by blend(), catchUp(), isRunning(), KbAnim(), keypress(), parameter(), reInit(), script(), stop(), trigger(), and updateParams().
QUuid KbAnim::_scriptGuid [private]
Definition at line 88 of file kbanim.h.
Referenced by KbAnim(), and save().
QString KbAnim::_scriptName [private]
Definition at line 89 of file kbanim.h.
Referenced by KbAnim(), save(), and scriptName().
QMap<QString, QVariant> KbAnim::_tempParameters [private]
Definition at line 96 of file kbanim.h.
Referenced by commitParams(), effectiveParams(), parameter(), and resetParams().
int KbAnim::kpRepeatMsec [private]
Definition at line 106 of file kbanim.h.
Referenced by catchUp(), keypress(), and stop().
quint64 KbAnim::kpRepeatTime [private]
Definition at line 105 of file kbanim.h.
Referenced by catchUp(), keypress(), and stop().
quint64 KbAnim::kpStopTime [private]
Definition at line 105 of file kbanim.h.
Referenced by catchUp(), keypress(), and stop().
QString KbAnim::repeatKey [private]
Definition at line 104 of file kbanim.h.
Referenced by catchUp(), keypress(), reInit(), stop(), and updateParams().
int KbAnim::repeatMsec [private]
Definition at line 106 of file kbanim.h.
Referenced by catchUp(), keypress(), stop(), and trigger().
quint64 KbAnim::repeatTime [private]
Definition at line 105 of file kbanim.h.
Referenced by catchUp(), keypress(), stop(), and trigger().
quint64 KbAnim::stopTime [private]
Definition at line 105 of file kbanim.h.
Referenced by catchUp(), keypress(), stop(), and trigger().
Author
Generated automatically by Doxygen for ckb-next from the source code.