KbBindWidget
NAME
KbBindWidget -
SYNOPSIS
#include <src/ckb/kbbindwidget.h>
Inherits QWidget.
Public Member Functions
KbBindWidget (QWidget *parent=0)
~KbBindWidget ()
void setBind (KbBind *newBind, KbProfile *newProfile)
Private Slots
void updateBind ()
void newLayout ()
void newSelection (QStringList selection)
void updateSelDisplay ()
void on_resetButton_clicked ()
void on_copyButton_clicked ()
Private Attributes
Ui::KbBindWidget * ui
KbBind * bind
KbProfile * profile
QStringList currentSelection
Detailed Description
Definition at line 12 of file kbbindwidget.h.
Constructor & Destructor Documentation
KbBindWidget::KbBindWidget (QWidget *parent = 0) [explicit]
Definition at line 7 of file kbbindwidget.cpp.
References Ui_KbBindWidget::keyWidget, newSelection(), KeyWidget::rgbMode(), Ui_KbBindWidget::setupUi(), and ui.
                                          :
    QWidget(parent),
    ui(new Ui::KbBindWidget), bind(0), profile(0)
{
    ui->setupUi(this);
    ui->keyWidget->rgbMode(false);
    connect(ui->keyWidget, SIGNAL(selectionChanged(QStringList)), this, SLOT(newSelection(QStringList)));
}
KbBindWidget::~KbBindWidget ()
Definition at line 16 of file kbbindwidget.cpp.
References ui.
                           {
    delete ui;
}
Member Function Documentation
void KbBindWidget::newLayout () [private], [slot]
Definition at line 50 of file kbbindwidget.cpp.
References bind, Ui_KbBindWidget::keyWidget, KeyWidget::map(), KbBind::map(), profile, Ui_KbBindWidget::rbWidget, RebindWidget::setBind(), ui, and updateSelDisplay().
Referenced by setBind().
                            {
    ui->keyWidget->map(bind->map());
    ui->rbWidget->setBind(bind, profile);
    updateSelDisplay();
}
void KbBindWidget::newSelection (QStringListselection) [private], [slot]
Definition at line 56 of file kbbindwidget.cpp.
References currentSelection, Ui_KbBindWidget::rbWidget, RebindWidget::setSelection(), ui, and updateSelDisplay().
Referenced by KbBindWidget(), and setBind().
                                                    {
    currentSelection = selection;
    ui->rbWidget->setSelection(selection, true);
    updateSelDisplay();
}
void KbBindWidget::on_copyButton_clicked () [private], [slot]
Definition at line 108 of file kbbindwidget.cpp.
References KbBind::action(), bind, KbMode::bind(), KeyMap::count(), KbProfile::currentMode(), currentSelection, KbBind::isMouse(), KeyMap::keys(), KbBind::map(), KbProfile::modes(), profile, ModeSelectDialog::selection(), KbBind::setAction(), and KeyAction::type().
                                        {
    QStringList selection = currentSelection;
    const KeyMap& map = bind->map();
    int count = selection.count();
    QString type = bind->isMouse() ? "button" : "key";
    QString text = tr("%1 %2").arg(count).arg(type) + (count == 1 ? "" : "s");
    if(count == 0){
        // Copy all keys if none selected
        selection = map.keys();
        text = tr("all %1s").arg(type);
    }
    text = "Copy binding for " + text + " to:";
    // Display popup
    ModeSelectDialog dialog(this, profile->currentMode(), profile->modes(), text);
    if(dialog.exec() != QDialog::Accepted)
        return;
    // Copy selected keys to selected modes
    QList<KbMode*> selectedModes = dialog.selection();
    foreach(KbMode* mode, selectedModes){
        KbBind* modeBind = mode->bind();
        foreach(const QString& key, selection){
            modeBind->setAction(key, bind->action(key));
        }
    }
}
void KbBindWidget::on_resetButton_clicked () [private], [slot]
Definition at line 87 of file kbbindwidget.cpp.
References bind, KeyMap::count(), currentSelection, KbBind::isMouse(), KeyMap::keys(), KbBind::map(), KbBind::resetAction(), KeyAction::type(), and updateBind().
                                         {
    QStringList selection = currentSelection;
    const KeyMap& map = bind->map();
    if(selection.isEmpty())
        // Reset all keys if none selected
        selection = map.keys();
    uint count = selection.count();
    QString type = bind->isMouse() ? "button" : "key";
    QString text;
    if(count == map.count())
        text = "<center>Reset all %1s to default?</center>";
    else if(count == 1)
        text = "<center>Reset this %1 to default?</center>";
    else
        text = tr("<center>Reset %1 %2s to default?</center>").arg(count);
    if(QMessageBox(QMessageBox::NoIcon, "Confirm action", text.arg(type), QMessageBox::Yes | QMessageBox::No, this).exec() != QMessageBox::Yes)
        return;
    bind->resetAction(selection);
    updateBind();
}
void KbBindWidget::setBind (KbBind *newBind, KbProfile *newProfile)
Definition at line 20 of file kbbindwidget.cpp.
References bind, KeyWidget::clearSelection(), Ui_KbBindWidget::keyWidget, newLayout(), newSelection(), profile, Ui_KbBindWidget::rbWidget, RebindWidget::setBind(), ui, and updateBind().
Referenced by KbWidget::modeChanged().
                                                                {
    ui->keyWidget->clearSelection();
    ui->rbWidget->setBind(newBind, newProfile);
    newSelection(QStringList());
    if(bind == newBind)
        return;
    if(bind){
        disconnect(bind, SIGNAL(layoutChanged()), this, SLOT(newLayout()));
        disconnect(bind, SIGNAL(updated()), this, SLOT(updateBind()));
    }
    connect(newBind, SIGNAL(layoutChanged()), this, SLOT(newLayout()));
    connect(newBind, SIGNAL(updated()), this, SLOT(updateBind()));
    bind = newBind;
    profile = newProfile;
    newLayout();
    ui->rbWidget->setBind(bind, profile);
    updateBind();
}
void KbBindWidget::updateBind () [private], [slot]
Definition at line 39 of file kbbindwidget.cpp.
References KbBind::action(), bind, KeyWidget::bindMap(), currentSelection, KeyMap::keys(), Ui_KbBindWidget::keyWidget, KbBind::map(), Ui_KbBindWidget::rbWidget, RebindWidget::setSelection(), ui, and updateSelDisplay().
Referenced by on_resetButton_clicked(), and setBind().
                             {
    const KeyMap& map = bind->map();
    // Build the action list based on the keymap
    QHash<QString, QString> actions;
    foreach(const QString& key, map.keys())
        actions[key] = bind->action(key);
    ui->keyWidget->bindMap(actions);
    ui->rbWidget->setSelection(currentSelection);
    updateSelDisplay();
}
void KbBindWidget::updateSelDisplay () [private], [slot]
Definition at line 62 of file kbbindwidget.cpp.
References bind, currentSelection, KbBind::friendlyActionName(), Key::friendlyName(), KbBind::isMouse(), KbBind::map(), Ui_KbBindWidget::selectLabel, and ui.
Referenced by newLayout(), newSelection(), and updateBind().
                                   {
    int count = currentSelection.count();
    if(count == 0){
        // No keys selected
        ui->selectLabel->setText("Click to select");
        return;
    }
    if(count == 1){
        // Single key selected: show key name and binding
        QString key = currentSelection[0];
        const Key& pos = bind->map()[key];
        if(!pos)
            ui->selectLabel->setText("(Unknown)");
        else
            ui->selectLabel->setText(pos.friendlyName(false).split("\n")[0] + " → " + bind->friendlyActionName(key).split("\n")[0]);
        return;
    }
    ui->selectLabel->setText(QString("%1 %2 selected").arg(count).arg(bind->isMouse() ? "buttons" : "keys"));
}
Field Documentation
KbBind* KbBindWidget::bind [private]
Definition at line 34 of file kbbindwidget.h.
Referenced by newLayout(), on_copyButton_clicked(), on_resetButton_clicked(), setBind(), updateBind(), and updateSelDisplay().
QStringList KbBindWidget::currentSelection [private]
Definition at line 36 of file kbbindwidget.h.
Referenced by newSelection(), on_copyButton_clicked(), on_resetButton_clicked(), updateBind(), and updateSelDisplay().
KbProfile* KbBindWidget::profile [private]
Definition at line 35 of file kbbindwidget.h.
Referenced by newLayout(), on_copyButton_clicked(), and setBind().
Ui::KbBindWidget* KbBindWidget::ui [private]
Definition at line 32 of file kbbindwidget.h.
Referenced by KbBindWidget(), newLayout(), newSelection(), setBind(), updateBind(), updateSelDisplay(), and ~KbBindWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.