.TH "src/ckb/kbbind.h" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbbind.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFile>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include 'ckbsettings\&.h'\fP
.br
\fC#include 'keymap\&.h'\fP
.br
\fC#include 'keyaction\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBKbBind\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
