KbMode
NAME
KbMode -
SYNOPSIS
#include <src/ckb/kbmode.h>
Inherits QObject.
Signals
void updated ()
Public Member Functions
KbMode (Kb *parent, const KeyMap &keyMap, const QString &guid='', const QString &modified='')
KbMode (Kb *parent, const KeyMap &keyMap, CkbSettings &settings)
KbMode (Kb *parent, const KeyMap &keyMap, const KbMode &other)
KbMode::KbMode.
~KbMode ()
KbMode::~KbMode Destructor may be used for Debugging (issue #38 with SIGSEGV). Insert qDebug-statement.
const QString & name () const
void name (const QString &newName)
UsbId & id ()
void id (const UsbId &newId)
void newId ()
void keyMap (const KeyMap &keyMap)
KbLight * light ()
KbBind * bind ()
KbPerf * perf ()
void save (CkbSettings &settings)
bool needsSave () const
void setNeedsSave ()
void setNeedsUpdate ()
Private Slots
void doUpdate ()
Private Attributes
QString _name
UsbId _id
KbLight * _light
KbBind * _bind
KbPerf * _perf
bool _needsSave
Detailed Description
Definition at line 36 of file kbmode.h.
Constructor & Destructor Documentation
KbMode::KbMode (Kb *parent, const KeyMap &keyMap, const QString &guid = '', const QString &modified = '')
Definition at line 4 of file kbmode.cpp.
References _id, _light, doUpdate(), UsbId::guid, and updated().
                                                                                             :
    QObject(parent),
    _name("Unnamed"), _id(guid, modified),
    _light(new KbLight(this, keyMap)), _bind(new KbBind(this, parent, keyMap)), _perf(new KbPerf(this)),
    _needsSave(true)
{
    connect(_light, SIGNAL(updated()), this, SLOT(doUpdate()));
    if(_id.guid.isNull())
        _id.guid = QUuid::createUuid();
}
KbMode::KbMode (Kb *parent, const KeyMap &keyMap, CkbSettings &settings)
Definition at line 30 of file kbmode.cpp.
References _bind, _id, _light, _name, _perf, CkbSettings::contains(), doUpdate(), UsbId::guid, UsbId::hwModified, UsbId::hwModifiedString(), KbPerf::load(), KbBind::load(), KbLight::load(), UsbId::modified, updated(), and CkbSettings::value().
                                                                      :
    QObject(parent),
    _name(settings.value("Name").toString().trimmed()),
    _id(settings.value("GUID").toString().trimmed(), settings.value("Modified").toString().trimmed()),
    _light(new KbLight(this, keyMap)), _bind(new KbBind(this, parent, keyMap)), _perf(new KbPerf(this)),
    _needsSave(false)
{
    if(settings.contains("HwModified"))
        _id.hwModifiedString(settings.value("HwModified").toString());
    else
        _id.hwModified = _id.modified;
    connect(_light, SIGNAL(updated()), this, SLOT(doUpdate()));
    if(_id.guid.isNull())
        _id.guid = QUuid::createUuid();
    if(_name == "")
        _name = "Unnamed";
    _light->load(settings);
    _bind->load(settings);
    _perf->load(settings);
}
KbMode::KbMode (Kb *parent, const KeyMap &keyMap, const KbMode &other)
Parameters:
parent Kb as parent (append to the Keyboard list
keyMap Map to copy from
other Mode to copy from Constructor to copy an existing Keyboard-Mode KbMode &other
Definition at line 21 of file kbmode.cpp.
References _light, doUpdate(), and updated().
                                                                    :
    QObject(parent),
    _name(other._name), _id(other._id),
    _light(new KbLight(this, keyMap, *other._light)), _bind(new KbBind(this, parent, keyMap, *other._bind)), _perf(new KbPerf(this, *other._perf)),
    _needsSave(true)
{
    connect(_light, SIGNAL(updated()), this, SLOT(doUpdate()));
}
KbMode::~KbMode ()
Definition at line 89 of file kbmode.cpp.
                {
}
Member Function Documentation
KbBind* KbMode::bind () [inline]
Definition at line 61 of file kbmode.h.
References _bind.
Referenced by KbPerf::bind(), Kb::currentBind(), Kb::frameUpdate(), KbBindWidget::on_copyButton_clicked(), and Kb::readNotify().
{ return _bind; }
void KbMode::doUpdate () [private], [slot]
Definition at line 82 of file kbmode.cpp.
References updated().
Referenced by KbMode().
                     {
    emit updated();
}
UsbId& KbMode::id () [inline]
Definition at line 52 of file kbmode.h.
References _id.
Referenced by KbProfile::find(), Kb::hwSave(), KbProfile::KbProfile(), KbWidget::on_modesList_customContextMenuRequested(), KbWidget::on_modesList_itemChanged(), KbWidget::on_modesList_itemClicked(), KbWidget::profileChanged(), Kb::readNotify(), and KbProfile::save().
{ return _id; }
void KbMode::id (const UsbId &newId) [inline]
Definition at line 53 of file kbmode.h.
References _id, _needsSave, and newId().
{ _needsSave = true; _id = newId; }
void KbMode::keyMap (const KeyMap &keyMap)
Definition at line 60 of file kbmode.cpp.
References _bind, _light, _needsSave, KbLight::map(), and KbBind::map().
Referenced by KbProfile::keyMap().
                                       {
    _needsSave = true;
    _light->map(keyMap);
    _bind->map(keyMap);
}
KbLight* KbMode::light () [inline]
Definition at line 60 of file kbmode.h.
References _light.
Referenced by Kb::currentLight(), Kb::frameUpdate(), Kb::hwSave(), KbBind::light(), KbPerf::light(), Kb::readNotify(), and Kb::updateLayout().
{ return _light; }
const QString& KbMode::name () const [inline]
Definition at line 50 of file kbmode.h.
References _name.
Referenced by Kb::hwSave(), ModeSelectDialog::ModeSelectDialog(), KbWidget::on_modesList_itemChanged(), KbWidget::profileChanged(), Kb::readNotify(), and RebindWidget::setBind().
{ return _name; }
void KbMode::name (const QString &newName) [inline]
Definition at line 51 of file kbmode.h.
References _name, and _needsSave.
{ _needsSave = true; _name = newName.trimmed(); if(_name == "") _name = "Unnamed"; }
bool KbMode::needsSave () const
Definition at line 78 of file kbmode.cpp.
References _bind, _light, _needsSave, _perf, KbPerf::needsSave(), KbBind::needsSave(), and KbLight::needsSave().
Referenced by KbProfile::needsSave().
                             {
    return _needsSave || _light->needsSave() || _bind->needsSave() || _perf->needsSave();
}
void KbMode::newId ()
Definition at line 52 of file kbmode.cpp.
References _id, _light, _needsSave, anim, KbLight::animList(), and KbAnim::newId().
Referenced by id(), KbProfile::newId(), and KbWidget::on_modesList_customContextMenuRequested().
                  {
    _needsSave = true;
    _id = UsbId();
    // Create new IDs for animations
    foreach(KbAnim* anim, _light->animList())
        anim->newId();
}
KbPerf* KbMode::perf () [inline]
Definition at line 62 of file kbmode.h.
References _perf.
Referenced by Kb::currentPerf(), Kb::frameUpdate(), Kb::hwSave(), KPerfWidget::on_copyButton_clicked(), MPerfWidget::on_copyButton_clicked(), KbBind::perf(), and Kb::readNotify().
{ return _perf; }
void KbMode::save (CkbSettings &settings)
Definition at line 66 of file kbmode.cpp.
References _bind, _id, _light, _name, _needsSave, _perf, UsbId::guidString(), UsbId::hwModifiedString(), UsbId::modifiedString(), UsbId::newModified(), KbPerf::save(), KbBind::save(), KbLight::save(), and CkbSettings::setValue().
Referenced by KbProfile::save().
                                      {
    _needsSave = false;
    _id.newModified();
    settings.setValue("GUID", _id.guidString());
    settings.setValue("Modified", _id.modifiedString());
    settings.setValue("HwModified", _id.hwModifiedString());
    settings.setValue("Name", _name);
    _light->save(settings);
    _bind->save(settings);
    _perf->save(settings);
}
void KbMode::setNeedsSave () [inline]
Definition at line 67 of file kbmode.h.
References _needsSave.
Referenced by Kb::hwSave(), and Kb::readNotify().
{ _needsSave = true; }
void KbMode::setNeedsUpdate () [inline]
Definition at line 68 of file kbmode.h.
References _bind, _perf, KbBind::setNeedsUpdate(), and KbPerf::setNeedsUpdate().
Referenced by KbProfile::setNeedsUpdate().
{ _bind->setNeedsUpdate(); _perf->setNeedsUpdate(); }
void KbMode::updated () [signal]
Definition at line 131 of file moc_kbmode.cpp.
Referenced by doUpdate(), and KbMode().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
Field Documentation
KbBind* KbMode::_bind [private]
Definition at line 78 of file kbmode.h.
Referenced by bind(), KbMode(), keyMap(), needsSave(), save(), and setNeedsUpdate().
UsbId KbMode::_id [private]
Definition at line 75 of file kbmode.h.
Referenced by id(), KbMode(), newId(), and save().
KbLight* KbMode::_light [private]
Definition at line 77 of file kbmode.h.
Referenced by KbMode(), keyMap(), light(), needsSave(), newId(), and save().
QString KbMode::_name [private]
Definition at line 74 of file kbmode.h.
Referenced by KbMode(), name(), and save().
bool KbMode::_needsSave [private]
Definition at line 81 of file kbmode.h.
Referenced by id(), keyMap(), name(), needsSave(), newId(), save(), and setNeedsSave().
KbPerf* KbMode::_perf [private]
Definition at line 79 of file kbmode.h.
Referenced by KbMode(), needsSave(), perf(), save(), and setNeedsUpdate().
Author
Generated automatically by Doxygen for ckb-next from the source code.