.TH "src/ckb/kbwidget.cpp" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include 'ckbsettings\&.h'\fP
.br
\fC#include 'fwupgradedialog\&.h'\fP
.br
\fC#include 'kbfirmware\&.h'\fP
.br
\fC#include 'kbwidget\&.h'\fP
.br
\fC#include 'kblightwidget\&.h'\fP
.br
\fC#include 'kbprofiledialog\&.h'\fP
.br
\fC#include 'ui_kbwidget\&.h'\fP
.br
\fC#include 'ui_kblightwidget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
