KPerfWidget
NAME
KPerfWidget -
SYNOPSIS
#include <src/ckb/kperfwidget.h>
Inherits QWidget.
Data Structures
struct IndicatorUi
Public Types
typedef KbPerf::indicator indicator
typedef KbPerf::i_hw i_hw
Public Member Functions
KPerfWidget (QWidget *parent=0)
KPerfWidget::KPerfWidget sets up the UI for Keyboard Performace panel.
~KPerfWidget ()
KPerfWidget::~KPerfWidget nothing unusual - just delete the ui object.
void setPerf (KbPerf *newPerf, KbProfile *newProfile)
Static Public Attributes
static const int I_COUNT = KbPerf::I_COUNT
static const int HW_I_COUNT = KbPerf::HW_I_COUNT
Private Types
enum HwMode { NORMAL, ALWAYS_ON, ALWAYS_OFF, RGB, BOTH }
Private Slots
void uiUpdated (int index)
void on_intensityBox_valueChanged (int arg1)
void on_copyButton_clicked ()
Private Member Functions
HwMode raw2Mode (bool sw_enable, i_hw hw_enable)
KPerfWidget::raw2Mode return hardware mode depending on setiings in sw_enable and hw_enable.
void mode2Raw (HwMode mode, bool &sw_enable, i_hw &hw_enable)
KPerfWidget::mode2Raw Set values of sw_enable and hw_enable to hte value corresponding to input var mode.
Private Attributes
Ui::KPerfWidget * ui
KbPerf * perf
KbProfile * profile
IndicatorUi indicators [I_COUNT]
QList< QWidget * > k95Widgets
QSignalMapper updateMapper
Detailed Description
Definition at line 16 of file kperfwidget.h.
Data Structure Documentation
struct KPerfWidget::IndicatorUi
Definition at line 54 of file kperfwidget.h.
Data Fields:
ColorButton * color1
ColorButton * color2
ColorButton * color3
QCheckBox * enable
QComboBox * hwEnable
Member Typedef Documentation
typedef KbPerf::i_hw KPerfWidget::i_hw
Definition at line 29 of file kperfwidget.h.
typedef KbPerf::indicator KPerfWidget::indicator
Definition at line 28 of file kperfwidget.h.
Member Enumeration Documentation
enum KPerfWidget::HwMode [private]
Enumerator
NORMAL
ALWAYS_ON
ALWAYS_OFF
RGB
BOTH
Definition at line 38 of file kperfwidget.h.
                {
        NORMAL,
        ALWAYS_ON,
        ALWAYS_OFF,
        RGB,
        BOTH
    };
Constructor & Destructor Documentation
KPerfWidget::KPerfWidget (QWidget *parent = 0) [explicit]
Parameters:
parent
Definition at line 10 of file kperfwidget.cpp.
References ColorButton::allowAlpha(), ColorButton::bigIcons(), Ui_KPerfWidget::capsBox, Ui_KPerfWidget::capsColorOff, Ui_KPerfWidget::capsColorOn, KPerfWidget::IndicatorUi::color1, KPerfWidget::IndicatorUi::color2, KPerfWidget::IndicatorUi::color3, KPerfWidget::IndicatorUi::enable, KPerfWidget::IndicatorUi::hwEnable, I_COUNT, indicators, Ui_KPerfWidget::k95Label1, Ui_KPerfWidget::k95Label2, Ui_KPerfWidget::k95Label3, Ui_KPerfWidget::k95Label4, Ui_KPerfWidget::k95Label5, Ui_KPerfWidget::k95Label6, Ui_KPerfWidget::k95Line, Ui_KPerfWidget::k95Spacer, k95Widgets, Ui_KPerfWidget::lightBox, Ui_KPerfWidget::lightColor1, Ui_KPerfWidget::lightColor2, Ui_KPerfWidget::lightColor3, Ui_KPerfWidget::lockBox, Ui_KPerfWidget::lockColorOff, Ui_KPerfWidget::lockColorOn, Ui_KPerfWidget::macroBox, Ui_KPerfWidget::macroColorOff, Ui_KPerfWidget::macroColorOn, Ui_KPerfWidget::modeBox, Ui_KPerfWidget::modeColorOff, Ui_KPerfWidget::modeColorOn, Ui_KPerfWidget::muteBox, Ui_KPerfWidget::muteColorNA, Ui_KPerfWidget::muteColorOff, Ui_KPerfWidget::muteColorOn, Ui_KPerfWidget::numBox, Ui_KPerfWidget::numColorOff, Ui_KPerfWidget::numColorOn, Ui_KPerfWidget::scrollBox, Ui_KPerfWidget::scrollColorOff, Ui_KPerfWidget::scrollColorOn, ColorButton::setLabel(), Ui_KPerfWidget::setupUi(), ui, uiUpdated(), and updateMapper.
                                        :
    QWidget(parent),
    ui(new Ui::KPerfWidget)
{
    ui->setupUi(this);
    // Set up indicators
    indicators[0].enable = 0; indicators[0].hwEnable = ui->numBox; indicators[0].color1 = ui->numColorOn; indicators[0].color2 = ui->numColorOff; indicators[0].color3 = 0;
    indicators[1].enable = 0; indicators[1].hwEnable = ui->capsBox; indicators[1].color1 = ui->capsColorOn; indicators[1].color2 = ui->capsColorOff; indicators[1].color3 = 0;
    indicators[2].enable = 0; indicators[2].hwEnable = ui->scrollBox; indicators[2].color1 = ui->scrollColorOn; indicators[2].color2 = ui->scrollColorOff; indicators[2].color3 = 0;
    indicators[3].enable = ui->modeBox; indicators[3].hwEnable = 0; indicators[3].color1 = ui->modeColorOn; indicators[3].color2 = ui->modeColorOff; indicators[3].color3 = 0;
    indicators[4].enable = ui->macroBox; indicators[4].hwEnable = 0; indicators[4].color1 = ui->macroColorOn; indicators[4].color2 = ui->macroColorOff; indicators[4].color3 = 0;
    indicators[5].enable = ui->lightBox; indicators[5].hwEnable = 0; indicators[5].color1 = ui->lightColor1; indicators[5].color2 = ui->lightColor2; indicators[5].color3 = ui->lightColor3;
    indicators[6].enable = ui->lockBox; indicators[6].hwEnable = 0; indicators[6].color1 = ui->lockColorOn; indicators[6].color2 = ui->lockColorOff; indicators[6].color3 = 0;
    indicators[7].enable = ui->muteBox; indicators[7].hwEnable = 0; indicators[7].color1 = ui->muteColorOn; indicators[7].color2 = ui->muteColorOff; indicators[7].color3 = ui->muteColorNA;
    for(int i = 0; i < I_COUNT; i++){
        indicators[i].color1->setLabel(false);
        indicators[i].color1->bigIcons(true);
        indicators[i].color1->allowAlpha(true);
        indicators[i].color2->setLabel(false);
        indicators[i].color2->bigIcons(true);
        indicators[i].color2->allowAlpha(true);
        if(indicators[i].color3){
            indicators[i].color3->setLabel(false);
            indicators[i].color3->bigIcons(true);
            indicators[i].color3->allowAlpha(true);
        }
        // Map signals
        if(indicators[i].enable){
            connect(indicators[i].enable, SIGNAL(clicked(bool)), &updateMapper, SLOT(map()));
            updateMapper.setMapping(indicators[i].enable, i);
        }
        if(indicators[i].hwEnable){
            connect(indicators[i].hwEnable, SIGNAL(activated(int)), &updateMapper, SLOT(map()));
            updateMapper.setMapping(indicators[i].hwEnable, i);
        }
        connect(indicators[i].color1, SIGNAL(colorChanged(QColor)), &updateMapper, SLOT(map()));
        updateMapper.setMapping(indicators[i].color1, i);
        connect(indicators[i].color2, SIGNAL(colorChanged(QColor)), &updateMapper, SLOT(map()));
        updateMapper.setMapping(indicators[i].color2, i);
        if(indicators[i].color3){
            connect(indicators[i].color3, SIGNAL(colorChanged(QColor)), &updateMapper, SLOT(map()));
            updateMapper.setMapping(indicators[i].color3, i);
        }
    }
    connect(&updateMapper, SIGNAL(mapped(int)), this, SLOT(uiUpdated(int)));
    k95Widgets << ui->modeBox << ui->modeColorOn << ui->modeColorOff << ui->macroBox << ui->macroColorOn << ui->macroColorOff << ui->k95Label1 << ui->k95Label2 << ui->k95Label3 << ui->k95Label4 << ui->k95Label5 << ui->k95Label6 << ui->k95Line << ui->k95Spacer;
}
KPerfWidget::~KPerfWidget ()
Definition at line 61 of file kperfwidget.cpp.
References ui.
                         {
    delete ui;
}
Member Function Documentation
void KPerfWidget::mode2Raw (HwModemode, bool &sw_enable, i_hw &hw_enable) [private]
Parameters:
[IN] mode
[OUT] sw_enable
[OUT] hw_enable
[IN] mode
[OUT] sw_enable
[OUT] hw_enable mode determines how colors at a key and separate indicators should be handled: Mode | sw | hw _ | _ | _ NORMAL | No color change at the key | use the separate indicator depending on key state ALWAYS_ON | No color change at the key | switch on separate indicator ALWAYS_OFF | No color change at the key | switch off separate indicator RGB | use color change at the key depending on color sliders | switch off separate indicator BOTH | use color change at the key depending on color sliders | use the separate indicator depending on key state
Definition at line 100 of file kperfwidget.cpp.
References ALWAYS_OFF, ALWAYS_ON, BOTH, NORMAL, KbPerf::NORMAL, KbPerf::OFF, KbPerf::ON, and RGB.
Referenced by uiUpdated().
                                                                       {
    switch(mode){
    case NORMAL:
        sw_enable = false;
        hw_enable = KbPerf::NORMAL;
        break;
    case ALWAYS_ON:
        sw_enable = false;
        hw_enable = KbPerf::ON;
        break;
    case ALWAYS_OFF:
        sw_enable = false;
        hw_enable = KbPerf::OFF;
        break;
    case RGB:
        sw_enable = true;
        hw_enable = KbPerf::OFF;
        break;
    case BOTH:
        sw_enable = true;
        hw_enable = KbPerf::NORMAL;
        break;
    }
}
void KPerfWidget::on_copyButton_clicked () [private], [slot]
Definition at line 221 of file kperfwidget.cpp.
References KbProfile::currentMode(), KbProfile::modes(), perf, KbMode::perf(), profile, and ModeSelectDialog::selection().
                                       {
    ModeSelectDialog dialog(this, profile->currentMode(), profile->modes(), "Copy performance settings to:");
    if(dialog.exec() != QDialog::Accepted)
        return;
    QList<KbMode*> selectedModes = dialog.selection();
    foreach(KbMode* mode, selectedModes){
        *mode->perf() = *perf;
    }
}
void KPerfWidget::on_intensityBox_valueChanged (intarg1) [private], [slot]
Definition at line 215 of file kperfwidget.cpp.
References KbPerf::iOpacity(), and perf.
                                                      {
    if(!perf)
        return;
    perf->iOpacity(arg1 / 100.f);
}
KPerfWidget::HwMode KPerfWidget::raw2Mode (boolsw_enable, i_hwhw_enable) [private]
Parameters:
sw_enable
hw_enable
Returns:
the mode of operation for key-coloring and separate indicators.
See Also:
KPerfWidget::mode2Raw for details.
Definition at line 72 of file kperfwidget.cpp.
References ALWAYS_OFF, ALWAYS_ON, BOTH, NORMAL, KbPerf::NORMAL, KbPerf::OFF, KbPerf::ON, and RGB.
Referenced by setPerf().
                                                                     {
    if(sw_enable){
        if(hw_enable == KbPerf::NORMAL)
            return BOTH;
        return RGB;
    } else {
        if(hw_enable == KbPerf::ON)
            return ALWAYS_ON;
        else if(hw_enable == KbPerf::OFF)
            return ALWAYS_OFF;
        return NORMAL;
    }
}
void KPerfWidget::setPerf (KbPerf *newPerf, KbProfile *newProfile)
Definition at line 125 of file kperfwidget.cpp.
References BOTH, ColorButton::color(), KPerfWidget::IndicatorUi::color1, KPerfWidget::IndicatorUi::color2, KPerfWidget::IndicatorUi::color3, KPerfWidget::IndicatorUi::enable, KbPerf::getIndicator(), HW_I_COUNT, KPerfWidget::IndicatorUi::hwEnable, I_COUNT, indicators, Ui_KPerfWidget::intensityBox, KbPerf::iOpacity(), KeyMap::K95, k95Widgets, KbProfile::keyMap(), Ui_KPerfWidget::label_12, Ui_KPerfWidget::label_14, Ui_KPerfWidget::label_17, KeyMap::model(), Ui_KPerfWidget::muteBox, Ui_KPerfWidget::muteColorNA, Ui_KPerfWidget::muteColorOff, Ui_KPerfWidget::muteColorOn, perf, profile, raw2Mode(), RGB, KeyMap::STRAFE, and ui.
Referenced by KbWidget::modeChanged().
                                                               {
    perf = newPerf;
    profile = newProfile;
    // Set intensity
    ui->intensityBox->setValue(round(perf->iOpacity() * 100.f));
    // Set hardware indicator values
    for(int i = 0; i < HW_I_COUNT; i++){
        QColor c1, c2, c3;
        bool software;
        i_hw hardware;
        perf->getIndicator((indicator)i, c1, c2, c3, software, hardware);
        HwMode mode = raw2Mode(software, hardware);
        indicators[i].hwEnable->setCurrentIndex((int)mode);
        indicators[i].color1->color(c1);
        indicators[i].color2->color(c2);
        if(mode == RGB || mode == BOTH){
            indicators[i].color1->setEnabled(true);
            indicators[i].color2->setEnabled(true);
        } else {
            indicators[i].color1->setEnabled(false);
            indicators[i].color2->setEnabled(false);
        }
    }
    // Set software indicators
    for(int i = HW_I_COUNT; i < I_COUNT; i++){
        QColor c1, c2, c3;
        bool software;
        i_hw hardware;
        perf->getIndicator((indicator)i, c1, c2, c3, software, hardware);
        indicators[i].enable->setChecked(software);
        indicators[i].color1->color(c1);
        indicators[i].color2->color(c2);
        if(indicators[i].color3) indicators[i].color3->color(c3);
        if(software){
            indicators[i].color1->setEnabled(true);
            indicators[i].color2->setEnabled(true);
            if(indicators[i].color3) indicators[i].color3->setEnabled(true);
        } else {
            indicators[i].color1->setEnabled(false);
            indicators[i].color2->setEnabled(false);
            if(indicators[i].color3) indicators[i].color3->setEnabled(false);
        }
    }
    // Hide K95 indicators on non-K95s
    if(profile->keyMap().model() == KeyMap::K95){
        foreach(QWidget* w, k95Widgets)
            w->show();
    } else {
        foreach(QWidget* w, k95Widgets)
            w->hide();
        if(profile->keyMap().model() == KeyMap::STRAFE) { // hide indicators unsupported by STRAFE
            ui->muteBox->hide();
            ui->muteColorOn->hide();
            ui->muteColorOff->hide();
            ui->muteColorNA->hide();
            ui->label_12->hide();
            ui->label_14->hide();
            ui->label_17->hide();
       }
    }
}
void KPerfWidget::uiUpdated (intindex) [private], [slot]
Definition at line 187 of file kperfwidget.cpp.
References ColorButton::color(), KPerfWidget::IndicatorUi::color1, KPerfWidget::IndicatorUi::color2, KPerfWidget::IndicatorUi::color3, KPerfWidget::IndicatorUi::enable, indicators, mode2Raw(), KbPerf::NONE, perf, and KbPerf::setIndicator().
Referenced by KPerfWidget().
                                    {
    if(!perf)
        return;
    // Read HW/SW enable state
    bool software;
    i_hw hardware;
    if(indicators[index].enable){
        software = indicators[index].enable->isChecked();
        hardware = KbPerf::NONE;
    } else {
        mode2Raw((HwMode)indicators[index].hwEnable->currentIndex(), software, hardware);
    }
    // Enable/disable color buttons based on whether or not the indicator is turned on
    if(software){
        indicators[index].color1->setEnabled(true);
        indicators[index].color2->setEnabled(true);
        if(indicators[index].color3) indicators[index].color3->setEnabled(true);
    } else {
        indicators[index].color1->setEnabled(false);
        indicators[index].color2->setEnabled(false);
        if(indicators[index].color3) indicators[index].color3->setEnabled(false);
    }
    QColor c1 = indicators[index].color1->color();
    QColor c2 = indicators[index].color2->color();
    QColor c3 = indicators[index].color3 ? indicators[index].color3->color() : QColor();
    perf->setIndicator((indicator)index, c1, c2, c3, software, hardware);
}
Field Documentation
const int KPerfWidget::HW_I_COUNT = KbPerf::HW_I_COUNT [static]
Definition at line 27 of file kperfwidget.h.
Referenced by setPerf().
const int KPerfWidget::I_COUNT = KbPerf::I_COUNT [static]
Definition at line 26 of file kperfwidget.h.
Referenced by KPerfWidget(), and setPerf().
IndicatorUi KPerfWidget::indicators[I_COUNT] [private]
Definition at line 59 of file kperfwidget.h.
Referenced by KPerfWidget(), setPerf(), and uiUpdated().
QList<QWidget*> KPerfWidget::k95Widgets [private]
Definition at line 60 of file kperfwidget.h.
Referenced by KPerfWidget(), and setPerf().
KbPerf* KPerfWidget::perf [private]
Definition at line 34 of file kperfwidget.h.
Referenced by on_copyButton_clicked(), on_intensityBox_valueChanged(), setPerf(), and uiUpdated().
KbProfile* KPerfWidget::profile [private]
Definition at line 35 of file kperfwidget.h.
Referenced by on_copyButton_clicked(), and setPerf().
Ui::KPerfWidget* KPerfWidget::ui [private]
Definition at line 32 of file kperfwidget.h.
Referenced by KPerfWidget(), setPerf(), and ~KPerfWidget().
QSignalMapper KPerfWidget::updateMapper [private]
Definition at line 62 of file kperfwidget.h.
Referenced by KPerfWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.