.TH "QThread" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch macrotime.0.2" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QThread \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKb\fP, \fBMacroReader\fP, and \fBMacroReaderThread\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
