.TH "src/ckb/quazip/quacrc32.cpp" 3 "Sat Jun 3 2017" "Version beta-v0.2.8+testing at branch testing-documentation" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quacrc32.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'quacrc32\&.h'\fP
.br
\fC#include 'zlib\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
