.TH "src/ckb/quazip/quazip_global.h" 3 "Sat Jun 3 2017" "Version beta-v0.2.8+testing at branch testing-documentation" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quazip_global.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUAZIP_EXPORT\fP   Q_DECL_IMPORT"
.br
.RI "\fIThis is automatically defined when building a static library, but when including \fBQuaZip\fP sources directly into a project, QUAZIP_STATIC should be defined explicitly to avoid possible troubles with unnecessary importing/exporting\&. \fP"
.ti -1c
.RI "#define \fBUNUSED\fP"
.br
.ti -1c
.RI "#define \fBQUAZIP_EXTRA_NTFS_MAGIC\fP   0x000Au"
.br
.ti -1c
.RI "#define \fBQUAZIP_EXTRA_NTFS_TIME_MAGIC\fP   0x0001u"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QUAZIP_EXPORT   Q_DECL_IMPORT"
When building a DLL with MSVC, QUAZIP_BUILD must be defined\&. qglobal\&.h takes care of defining Q_DECL_* correctly for msvc/gcc\&. 
.PP
Definition at line 46 of file quazip_global\&.h\&.
.SS "#define QUAZIP_EXTRA_NTFS_MAGIC   0x000Au"

.PP
Definition at line 56 of file quazip_global\&.h\&.
.PP
Referenced by getNTFSTime(), and setNTFSTime()\&.
.SS "#define QUAZIP_EXTRA_NTFS_TIME_MAGIC   0x0001u"

.PP
Definition at line 57 of file quazip_global\&.h\&.
.PP
Referenced by getNTFSTime(), and setNTFSTime()\&.
.SS "#define UNUSED"

.PP
Definition at line 53 of file quazip_global\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
