# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_REF: "github.com/$GH_REPO_ORG/$GH_REPO_NAME.git"
    - DOXYFILE: $TRAVIS_BUILD_DIR/documentation/Doxy-ckb-daemon

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -yq --no-install-suggests --no-install-recommends --force-yes qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install qt5-default qttools5-dev-tools
    - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libudev-dev zlib1g-dev libappindicator-dev

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
language:
    - c++

script:
  - cd $TRAVIS_BUILD_DIR
  - sh -c 'echo "n" | ./quickinstall'

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x documentation/generateDocumentationAndDeploy.sh
  - ./documentation/generateDocumentationAndDeploy.sh
