.TH "src/ckb-daemon Directory Reference" 3 "Sun Jun 18 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb-daemon Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommand\&.c\fP"
.br
.ti -1c
.RI "file \fBcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBdevice\&.c\fP"
.br
.ti -1c
.RI "file \fBdevice\&.h\fP"
.br
.ti -1c
.RI "file \fBdevice_keyboard\&.c\fP"
.br
.ti -1c
.RI "file \fBdevice_mouse\&.c\fP"
.br
.ti -1c
.RI "file \fBdevice_vtable\&.c\fP"
.br
.ti -1c
.RI "file \fBdevnode\&.c\fP"
.br
.ti -1c
.RI "file \fBdevnode\&.h\fP"
.br
.ti -1c
.RI "file \fBdpi\&.c\fP"
.br
.ti -1c
.RI "file \fBdpi\&.h\fP"
.br
.ti -1c
.RI "file \fBextra_mac\&.c\fP"
.br
.ti -1c
.RI "file \fBfirmware\&.c\fP"
.br
.ti -1c
.RI "file \fBfirmware\&.h\fP"
.br
.ti -1c
.RI "file \fBincludes\&.h\fP"
.br
.ti -1c
.RI "file \fBinput\&.c\fP"
.br
.ti -1c
.RI "file \fBinput\&.h\fP"
.br
.ti -1c
.RI "file \fBinput_linux\&.c\fP"
.br
.ti -1c
.RI "file \fBinput_mac\&.c\fP"
.br
.ti -1c
.RI "file \fBinput_mac_mouse\&.c\fP"
.br
.ti -1c
.RI "file \fBkeymap\&.c\fP"
.br
.ti -1c
.RI "file \fBkeymap\&.h\fP"
.br
.ti -1c
.RI "file \fBkeymap_mac\&.h\fP"
.br
.ti -1c
.RI "file \fBled\&.c\fP"
.br
.ti -1c
.RI "file \fBled\&.h\fP"
.br
.ti -1c
.RI "file \fBled_keyboard\&.c\fP"
.br
.ti -1c
.RI "file \fBled_mouse\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBnotify\&.c\fP"
.br
.ti -1c
.RI "file \fBnotify\&.h\fP"
.br
.ti -1c
.RI "file \fBos\&.h\fP"
.br
.ti -1c
.RI "file \fBprofile\&.c\fP"
.br
.ti -1c
.RI "file \fBprofile\&.h\fP"
.br
.ti -1c
.RI "file \fBprofile_keyboard\&.c\fP"
.br
.ti -1c
.RI "file \fBprofile_mouse\&.c\fP"
.br
.ti -1c
.RI "file \fBstructures\&.h\fP"
.br
.ti -1c
.RI "file \fBusb\&.c\fP"
.br
.ti -1c
.RI "file \fBusb\&.h\fP"
.br
.RI "\fIDefinitions for using USB interface\&. \fP"
.ti -1c
.RI "file \fBusb_linux\&.c\fP"
.br
.ti -1c
.RI "file \fBusb_mac\&.c\fP"
.br
.in -1c
