.TH "CkbSettingsWriter" 3 "Tue May 16 2017" "Version beta-v0.2.7 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CkbSettingsWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/ckbsettingswriter\&.h>\fP
.PP
Inherits \fBQObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCkbSettingsWriter\fP (QSettings *backing, const QStringList &removals, const QMap< QString, QVariant > &updates)"
.br
.ti -1c
.RI "\fB~CkbSettingsWriter\fP ()"
.br
.ti -1c
.RI "Q_SLOT void \fBrun\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QSettings * \fB_backing\fP"
.br
.ti -1c
.RI "QStringList \fB_removals\fP"
.br
.ti -1c
.RI "QMap< QString, QVariant > \fB_updates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ckbsettingswriter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CkbSettingsWriter::CkbSettingsWriter (QSettings *backing, const QStringList &removals, const QMap< QString, QVariant > &updates)"

.PP
Definition at line 12 of file ckbsettingswriter\&.cpp\&.
.PP
References cacheWritesInProgress\&.
.PP
.nf
12                                                                                                                             :
13     _backing(backing), _removals(removals), _updates(updates) {
14     cacheWritesInProgress\&.ref();
15 }
.fi
.SS "CkbSettingsWriter::~CkbSettingsWriter ()"

.PP
Definition at line 17 of file ckbsettingswriter\&.cpp\&.
.PP
References cacheWritesInProgress\&.
.PP
.nf
17                                      {
18     cacheWritesInProgress\&.deref();
19 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void CkbSettingsWriter::run ()"

.PP
Definition at line 21 of file ckbsettingswriter\&.cpp\&.
.PP
References _backing, _removals, _updates, and lockMutexStatic\&.
.PP
.nf
21                            {
22     lockMutexStatic;
23     // Process key removals
24     foreach(const QString& rm, _removals){
25         _backing->remove(rm);
26     }
27     // Process writes
28     QMapIterator<QString, QVariant> i(_updates);
29     while(i\&.hasNext()){
30         i\&.next();
31         _backing->setValue(i\&.key(), i\&.value());
32         // Updating the global cache was done above
33     }
34     _backing->sync();
35     deleteLater();
36 }
.fi
.SH "Field Documentation"
.PP 
.SS "QSettings* CkbSettingsWriter::_backing\fC [private]\fP"

.PP
Definition at line 21 of file ckbsettingswriter\&.h\&.
.PP
Referenced by run()\&.
.SS "QStringList CkbSettingsWriter::_removals\fC [private]\fP"

.PP
Definition at line 22 of file ckbsettingswriter\&.h\&.
.PP
Referenced by run()\&.
.SS "QMap<QString, QVariant> CkbSettingsWriter::_updates\fC [private]\fP"

.PP
Definition at line 23 of file ckbsettingswriter\&.h\&.
.PP
Referenced by run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
