.TH "src/ckb/fwupgradedialog.h" 3 "Sun Jun 18 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/fwupgradedialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QCloseEvent>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QEventLoop>\fP
.br
\fC#include 'kb\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFwUpgradeDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
