.TH "src/ckb/gradientdialogwidget.h" 3 "Tue May 16 2017" "Version beta-v0.2.7 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/gradientdialogwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QMouseEvent>\fP
.br
\fC#include <QPaintEvent>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGradientDialogWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
