.TH "src/ckb/gradientdialog.cpp" 3 "Sat Jun 17 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/gradientdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include 'ckbsettings\&.h'\fP
.br
\fC#include 'gradientdialog\&.h'\fP
.br
\fC#include 'ui_gradientdialog\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const QString \fBprefsPath\fP = 'Stored Gradients'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const QString prefsPath = 'Stored Gradients'\fC [static]\fP"

.PP
Definition at line 9 of file gradientdialog\&.cpp\&.
.PP
Referenced by GradientDialog::GradientDialog(), and GradientDialog::~GradientDialog()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
