.TH "src/ckb/gradientdialogwidget.cpp" 3 "Tue Aug 15 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/gradientdialogwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QPropertyAnimation>\fP
.br
\fC#include 'gradientdialogwidget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
