GradientDialogWidget
NAME
GradientDialogWidget -
SYNOPSIS
#include <src/ckb/gradientdialogwidget.h>
Inherits QWidget.
Signals
void currentChanged (QColor color, bool spontaneous, int position)
Public Member Functions
GradientDialogWidget (QWidget *parent=0)
void setStops (const QGradientStops &stops)
QGradientStops stops ()
int stopCount ()
QColor colorAt (int position)
int current ()
int moveCurrent (int to)
void setCurrentColor (const QColor &color)
Private Member Functions
QRect fillRect ()
QRect stopRect (int pos)
int selectedStop ()
QMap< int, QColor > selectionColors ()
void makeStops ()
void paintEvent (QPaintEvent *)
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
Private Attributes
QColor selected
int selectedPos
int selectedOffset
int _current
QMap< int, QColor > _colors
QGradientStops _stops
Detailed Description
Definition at line 8 of file gradientdialogwidget.h.
Constructor & Destructor Documentation
GradientDialogWidget::GradientDialogWidget (QWidget *parent = 0) [explicit]
Definition at line 6 of file gradientdialogwidget.cpp.
                                                          :
    QWidget(parent), selectedPos(-1), _current(-1)
{
    setMouseTracking(true);
}
Member Function Documentation
QColor GradientDialogWidget::colorAt (intposition)
Definition at line 65 of file gradientdialogwidget.cpp.
References _stops.
Referenced by mousePressEvent().
                                                {
    // Find which stops the position is between
    qreal pos = position / 100.;
    QVectorIterator<QGradientStop> i(_stops);
    QGradientStop previous = i.next();
    while(i.hasNext()){
        QGradientStop next = i.next();
        if(next.first >= pos){
            // Get color by linear interpolation. Premultiply the alpha value so that it returns the expected color
            // (i.e. stops with zero opacity won't contribute to color)
            QColor c1 = next.second, c2 = previous.second;
            qreal distance = next.first - previous.first;
            qreal dx = (pos - previous.first) / distance;
            qreal a1 = c1.alphaF(), a2 = c2.alphaF();
            qreal a3 = a1 * dx + a2 * (1.f - dx);
            if(a3 == 0.){
                c2.setAlpha(0);
                return c2;
            }
            qreal r = (c1.redF() * a1 * dx + c2.redF() * a2 * (1.f - dx)) / a3;
            qreal g = (c1.greenF() * a1 * dx + c2.greenF() * a2 * (1.f - dx)) / a3;
            qreal b = (c1.blueF() * a1 * dx + c2.blueF() * a2 * (1.f - dx)) / a3;
            return QColor::fromRgbF(r, g, b, a3);
        }
        previous = next;
    }
    return QColor();
}
int GradientDialogWidget::current () [inline]
Definition at line 20 of file gradientdialogwidget.h.
References _current.
{ return _current; }
void GradientDialogWidget::currentChanged (QColorcolor, boolspontaneous, intposition) [signal]
Definition at line 126 of file moc_gradientdialogwidget.cpp.
Referenced by mouseReleaseEvent(), and setStops().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)), const_cast<void*>(reinterpret_cast<const void*>(&_t3)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
QRect GradientDialogWidget::fillRect () [private]
Definition at line 138 of file gradientdialogwidget.cpp.
References width, x, and y.
Referenced by mouseMoveEvent(), mousePressEvent(), paintEvent(), selectedStop(), and stopRect().
                                    {
    int x = 8, y = 1;
    int w = (width() - x * 2) / 16 * 16, h = (height() - 24) / 16 * 16;
    return QRect(x, y, w, h);
}
void GradientDialogWidget::makeStops () [private]
Definition at line 30 of file gradientdialogwidget.cpp.
References _stops, and selectionColors().
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveCurrent(), and setCurrentColor().
                                    {
    _stops.clear();
    QMap<int, QColor> colors = selectionColors();
    // If there's only a single color, put it at the beginning and end
    if(colors.count() == 1){
#if QT_VERSION >= QT_VERSION_CHECK(5, 2, 0)
        QColor color = colors.first();
#else
        QColor color = colors.value(colors.keys().first());
#endif
        _stops.append(QGradientStop(0., color));
        _stops.append(QGradientStop(1., color));
        update();
        return;
    }
    // Add colors at 0 and 100 if needed
#if QT_VERSION >= QT_VERSION_CHECK(5, 2, 0)
    if(!colors.contains(0))
        colors[0] = colors.first();
    if(!colors.contains(100))
        colors[100] = colors.last();
#else
    if(!colors.contains(0))
        colors[0] = colors.value(colors.keys().first());
    if(!colors.contains(100))
        colors[100] = colors.value(colors.keys().last());
#endif
    QMapIterator<int, QColor> i(colors);
    while(i.hasNext()){
        i.next();
        _stops.append(QGradientStop(i.key() / 100., i.value()));
    }
    update();
}
void GradientDialogWidget::mouseMoveEvent (QMouseEvent *event) [private]
Definition at line 255 of file gradientdialogwidget.cpp.
References _colors, fillRect(), left, makeStops(), right(), selected, selectedOffset, selectedPos, and top.
                                                           {
    if(!selected.isValid()){
        if(event->y() >= height() - 24)
            setCursor(QCursor(Qt::PointingHandCursor));
        else
            setCursor(QCursor(Qt::ArrowCursor));
        return;
    }
    // Move selected point (if any)
    setCursor(QCursor(Qt::ClosedHandCursor));
    selectedPos = event->x() + selectedOffset;
    // Allow the point to be deleted as long as there is at least 1 other point
    bool last = (_colors.count() == 0);
    // Hug the left/right edges
    QRect rect = fillRect();
    int left = rect.left(), right = rect.right();
    if(selectedPos < left && (last || selectedPos >= left - 30))
        selectedPos = left;
    else if(selectedPos > right && (last || selectedPos <= right + 30))
        selectedPos = right;
    // Remove point if it's too far above/below the widget
    int top = -30, bottom = height() + 30;
    if(!last && (event->y() < top || event->y() > bottom))
        selectedPos = -1;
    makeStops();
}
void GradientDialogWidget::mousePressEvent (QMouseEvent *event) [private]
Definition at line 222 of file gradientdialogwidget.cpp.
References _colors, colorAt(), fillRect(), makeStops(), mouseReleaseEvent(), selected, selectedOffset, selectedPos, selectedStop(), stopRect(), x, and y.
                                                            {
    int x = event->x(), y = event->y();
    if(y < height() - 24)
        return;
    QMapIterator<int, QColor> i(_colors);
    while(i.hasNext()){
        i.next();
        // If a point was selected, remove it from the color map and set it as the selected point
        QRect stop = stopRect(i.key());
        if(x >= stop.left() - 1 && x <= stop.right() + 1){
            selected = i.value();
            selectedPos = stop.x() + stop.width() / 2;
            selectedOffset = selectedPos - x;
            _colors.remove(i.key());
            // On right click, delete the point
            if(event->button() == Qt::RightButton && _colors.count() > 1){
                selectedPos = -1;
                mouseReleaseEvent(event);
            } else
                update();
            return;
        }
    }
    // If nothing was selected, create a new point
    QRect fill = fillRect();
    if(x > fill.left() && x < fill.right() && event->button() != Qt::RightButton){
        selectedPos = x;
        selectedOffset = 0;
        selected = colorAt(selectedStop());
        makeStops();
    }
}
void GradientDialogWidget::mouseReleaseEvent (QMouseEvent *event) [private]
Definition at line 282 of file gradientdialogwidget.cpp.
References _colors, _current, currentChanged(), makeStops(), selected, selectedPos, selectedStop(), and selectionColors().
Referenced by mousePressEvent().
                                                              {
    if(selected.isValid()){
        // Rejoin selection with gradient
        _current = selectedStop();
        _colors = selectionColors();
        emit currentChanged(_colors.value(_current), true, _current);
        selectedPos = -1;
        selected = QColor();
        makeStops();
    }
    if(event->y() >= height() - 24)
        setCursor(QCursor(Qt::PointingHandCursor));
    else
        setCursor(QCursor(Qt::ArrowCursor));
}
int GradientDialogWidget::moveCurrent (intto)
Definition at line 94 of file gradientdialogwidget.cpp.
References _colors, _current, makeStops(), and selected.
Referenced by GradientDialog::on_stopPos_valueChanged().
                                           {
    if(_current < 0 || to == _current || selected.isValid())
        return _current;
    // If there's a point in the way, skip past it by continuing in the current direction
    if(_current < to){
        while(_colors.contains(to)){
            to++;
            if(to > 100)
                return _current;
        }
    } else {
        while(_colors.contains(to)){
            to--;
            if(to < 0)
                return _current;
        }
    }
    _colors[to] = _colors.take(_current);
    _current = to;
    makeStops();
    return to;
}
void GradientDialogWidget::paintEvent (QPaintEvent *) [private]
Definition at line 172 of file gradientdialogwidget.cpp.
References _colors, _current, _stops, fillRect(), selected, selectedPos, stopRect(), x, and y.
                                                 {
    QPainter painter(this);
    QRect fill = fillRect();
    int x = fill.x(), y = fill.y(), w = fill.width(), h = fill.height();
    // Draw border around gradient
    painter.setPen(palette().color(QPalette::Dark));
    painter.drawLine(x - 1, y - 1, x + w, y - 1);
    painter.drawLine(x - 1, y - 1, x - 1, y + h);
    painter.setPen(palette().color(QPalette::Light));
    painter.drawLine(x - 1, y + h, x + w, y + h);
    painter.drawLine(x + w, y - 1, x + w, y + h);
    // Draw background grid
    for(int i = 0; i < w; i += 16){
        for(int iy = 0; iy < h; iy += 16){
            if(i % 32 != iy % 32)
                painter.fillRect(x + i, y + iy, 16, 16, QColor(192, 192, 192));
            else
                painter.fillRect(x + i, y + iy, 16, 16, QColor(255, 255, 255));
        }
    }
    // Draw gradient
    painter.setRenderHint(QPainter::Antialiasing);
    QLinearGradient gradient(x, 0, x + w, 0);
    gradient.setStops(_stops);
    painter.fillRect(fill, QBrush(gradient));
    // Draw stops
    QMapIterator<int, QColor> i(_colors);
    painter.setPen(palette().color(QPalette::Shadow));
    while(i.hasNext()){
        i.next();
        painter.setBrush(QBrush(i.value()));
        int index = i.key();
        if(index == _current){
            // Highlight currently-edited stop
            painter.setPen(QPen(palette().color(QPalette::Highlight), 2));
            painter.drawRoundedRect(stopRect(index), 4, 4);
            painter.setPen(palette().color(QPalette::Shadow));
        } else
            painter.drawRoundedRect(stopRect(index), 4, 4);
    }
    // Draw selection (if any)
    if(selected.isValid() && selectedPos >= x && selectedPos <= x + w){
        painter.setPen(QPen(palette().color(QPalette::Highlight), 2.5));
        painter.setBrush(selected);
        painter.drawRoundedRect(selectedPos - 6, height() - 18 - 2, 12, 18, 4, 4);
    }
}
int GradientDialogWidget::selectedStop () [private]
Definition at line 152 of file gradientdialogwidget.cpp.
References fillRect(), and selectedPos.
Referenced by mousePressEvent(), mouseReleaseEvent(), and selectionColors().
                                      {
    QRect rect = fillRect();
    int res = round((selectedPos - rect.x()) * 100. / rect.width());
    if(res < 0 || res > 100)
        return -1;
    return res;
}
QMap< int, QColor > GradientDialogWidget::selectionColors () [private]
Definition at line 160 of file gradientdialogwidget.cpp.
References _colors, selected, and selectedStop().
Referenced by makeStops(), and mouseReleaseEvent().
                                                       {
    if(!selected.isValid())
        return _colors;
    // Determine selected stop position
    int selPos = selectedStop();
    // Re-add if in range
    QMap<int, QColor> res = _colors;
    if(selPos >= 0 && selPos <= 100)
        res[selPos] = selected;
    return res;
}
void GradientDialogWidget::setCurrentColor (const QColor &color)
Definition at line 117 of file gradientdialogwidget.cpp.
References _colors, _current, makeStops(), and selected.
Referenced by GradientDialog::colorChanged().
                                                             {
    if(_current < 0 || selected.isValid())
        return;
    QRgb rgb = _colors.value(_current).rgb();
    _colors[_current] = color;
    // If any points follow with the same color but different opacity, change them to match
    QMutableMapIterator<int, QColor> i(_colors);
    while(i.hasNext()){
        i.next();
        if(i.key() <= _current)
            continue;
        QColor& value = i.value();
        if(value.rgb() != rgb)
            break;
        int alpha = value.alpha();
        value = color;
        value.setAlpha(alpha);
    }
    makeStops();
}
void GradientDialogWidget::setStops (const QGradientStops &stops)
Definition at line 12 of file gradientdialogwidget.cpp.
References _colors, _current, _stops, currentChanged(), and stops().
Referenced by GradientDialog::getGradient(), and GradientDialog::setPreset().
                                                              {
    _stops = stops;
    _colors.clear();
    foreach(const QGradientStop& stop, stops){
        double pos = stop.first;
        if(pos < 0. || pos > 1.)
            continue;
        _colors[round(pos * 100.)] = stop.second;
    }
    _current = 0;
#if QT_VERSION >= QT_VERSION_CHECK(5, 2, 0)
    emit currentChanged(_colors.first(), false, 0);
#else
    emit currentChanged(_colors.value(_colors.keys().first()), false, 0);
#endif
    update();
}
int GradientDialogWidget::stopCount () [inline]
Definition at line 16 of file gradientdialogwidget.h.
References _stops.
Referenced by GradientDialog::currentChanged().
{ return _stops.count(); }
QRect GradientDialogWidget::stopRect (intpos) [private]
Definition at line 144 of file gradientdialogwidget.cpp.
References fillRect().
Referenced by mousePressEvent(), and paintEvent().
                                           {
    QRect fill = fillRect();
    int sx = round(pos / 100. * fill.width()) + fill.x() - 6;
    int sw = 12, sh = 18;
    int sy = height() - sh - 2;
    return QRect(sx, sy, sw, sh);
}
QGradientStops GradientDialogWidget::stops () [inline]
Definition at line 15 of file gradientdialogwidget.h.
References _stops.
Referenced by GradientDialog::getGradient(), GradientDialog::on_presetSave_clicked(), and setStops().
{ return _stops; }
Field Documentation
QMap<int, QColor> GradientDialogWidget::_colors [private]
Definition at line 31 of file gradientdialogwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveCurrent(), paintEvent(), selectionColors(), setCurrentColor(), and setStops().
int GradientDialogWidget::_current [private]
Definition at line 30 of file gradientdialogwidget.h.
Referenced by current(), mouseReleaseEvent(), moveCurrent(), paintEvent(), setCurrentColor(), and setStops().
QGradientStops GradientDialogWidget::_stops [private]
Definition at line 32 of file gradientdialogwidget.h.
Referenced by colorAt(), makeStops(), paintEvent(), setStops(), stopCount(), and stops().
QColor GradientDialogWidget::selected [private]
Definition at line 28 of file gradientdialogwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveCurrent(), paintEvent(), selectionColors(), and setCurrentColor().
int GradientDialogWidget::selectedOffset [private]
Definition at line 29 of file gradientdialogwidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
int GradientDialogWidget::selectedPos [private]
Definition at line 29 of file gradientdialogwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), and selectedStop().
Author
Generated automatically by Doxygen for ckb-next from the source code.