.TH "src/ckb/kbanimwidget.cpp" 3 "Tue Aug 15 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbanimwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDateTime>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include 'animsettingdialog\&.h'\fP
.br
\fC#include 'kbanimwidget\&.h'\fP
.br
\fC#include 'ui_kbanimwidget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
