.TH "src/ckb/kbanim.h" 3 "Sat Feb 3 2018" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbanim.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'ckbsettings\&.h'\fP
.br
\fC#include 'animscript\&.h'\fP
.br
\fC#include 'keymap\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBKbAnim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
