src/ckb/kblight.cpp
NAME
src/ckb/kblight.cpp -
SYNOPSIS
#include <cmath>
#include <QDateTime>
#include <QSet>
#include 'kblight.h'
#include 'kbmode.h'
Functions
static float sToL (float srgb)
static float lToS (float linear)
QRgb monoRgb (float r, float g, float b)
Variables
static int _shareDimming = -1
static QSet< KbLight * > activeLights
Function Documentation
static float lToS (floatlinear) [static]
Definition at line 277 of file kblight.cpp.
Referenced by KbLight::frameUpdate(), and monoRgb().
                               {
    if(linear <= 0.0031308f)
        return 12.92f * linear * 255.f;
    return (1.055f * pow(linear, 1.f / 2.4f) - 0.055f) * 255.f;
}
QRgb monoRgb (floatr, floatg, floatb)
Definition at line 284 of file kblight.cpp.
References lToS(), and sToL().
Referenced by KbLight::base(), KbLight::frameUpdate(), and KeyWidget::paintEvent().
                                       {
    // It's important to use a linear colorspace for this, otherwise the colors will appear inconsistent
    // Note that although we could use linear space for alpha blending or the animation blending functions, we don't.
    // The reason for this is that photo manipulation programs don't do it either, so even though the result would technically be more correct,
    // it would look wrong to most people.
    r = sToL(r);
    g = sToL(g);
    b = sToL(b);
    int value = round(lToS((r + g + b) / 3.f));
    return qRgb(value, value, value);
}
static float sToL (floatsrgb) [static]
Definition at line 270 of file kblight.cpp.
Referenced by KbLight::frameUpdate(), and monoRgb().
                             {
    srgb /= 255.f;
    if(srgb <= 0.04045f)
        return srgb / 12.92f;
    return pow((srgb + 0.055f) / 1.055f, 2.4f);
}
Variable Documentation
int _shareDimming = -1 [static]
Definition at line 7 of file kblight.cpp.
Referenced by KbLight::dimming(), KbLight::open(), and KbLight::shareDimming().
QSet<KbLight*> activeLights [static]
Definition at line 8 of file kblight.cpp.
Referenced by KbLight::close(), KbLight::open(), KbLight::shareDimming(), and KbLight::~KbLight().
Author
Generated automatically by Doxygen for ckb-next from the source code.