.TH "src/ckb/kbperf.h" 3 "Tue May 16 2017" "Version beta-v0.2.7 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbperf.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFile>\fP
.br
\fC#include <QMap>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include 'ckbsettings\&.h'\fP
.br
\fC#include 'keymap\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBKbPerf\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
