.TH "Key" 3 "Sat Jun 17 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Key \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/keymap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBstorageName\fP () const "
.br
.ti -1c
.RI "QString \fBfriendlyName\fP (bool os=true) const "
.br
.ti -1c
.RI "\fBoperator bool\fP () const "
.br
.ti -1c
.RI "bool \fBoperator!\fP () const "
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fB_storageName\fP"
.br
.ti -1c
.RI "const char * \fB_friendlyName\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "short \fBwidth\fP"
.br
.ti -1c
.RI "short \fBheight\fP"
.br
.ti -1c
.RI "bool \fBhasLed\fP"
.br
.ti -1c
.RI "bool \fBhasScan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file keymap\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QString Key::friendlyName (boolos = \fCtrue\fP) const\fC [inline]\fP"

.PP
Definition at line 23 of file keymap\&.h\&.
.PP
References _friendlyName, and name\&.
.PP
Referenced by KbBind::friendlyName(), KeyWidget::mouseMoveEvent(), KeyWidget::paintEvent(), RebindWidget::setBind(), and KbBindWidget::updateSelDisplay()\&.
.PP
.nf
23                                                       {
24         if(os){
25 #ifdef Q_OS_MACX
26             if(!strcmp(name, "lwin")) return "Left Cmd";
27             if(!strcmp(name, "rwin")) return "Right Cmd";
28             if(!strcmp(name, "lalt")) return "Left Option";
29             if(!strcmp(name, "ralt")) return "Right Option";
30             if(!strcmp(name, "prtscn")) return "F13";
31             if(!strcmp(name, "scroll")) return "F14";
32             if(!strcmp(name, "pause")) return "F15";
33             if(!strcmp(name, "ins")) return "Help";
34             if(!strcmp(name, "numlock")) return "Clear";
35 #elif defined(Q_OS_LINUX)
36             if(!strcmp(name, "lwin")) return "Left Super";
37             if(!strcmp(name, "rwin")) return "Right Super";
38 #endif
39         }
40         return _friendlyName ? _friendlyName : QString(name)\&.toUpper();
41     }
.fi
.SS "Key::operator bool () const\fC [inline]\fP"

.PP
Definition at line 44 of file keymap\&.h\&.
.PP
References name\&.
.PP
.nf
44 { return name != 0; }
.fi
.SS "bool Key::operator! () const\fC [inline]\fP"

.PP
Definition at line 45 of file keymap\&.h\&.
.PP
.nf
45 { return !(bool)*this; }
.fi
.SS "const char* Key::storageName () const\fC [inline]\fP"

.PP
Definition at line 11 of file keymap\&.h\&.
.PP
References _storageName, and name\&.
.PP
Referenced by KeyMap::toStorage()\&.
.PP
.nf
11 { return _storageName ? _storageName : name; }
.fi
.SH "Field Documentation"
.PP 
.SS "const char* Key::_friendlyName"

.PP
Definition at line 13 of file keymap\&.h\&.
.PP
Referenced by _patch(), and friendlyName()\&.
.SS "const char* Key::_storageName"

.PP
Definition at line 10 of file keymap\&.h\&.
.PP
Referenced by _patch(), and storageName()\&.
.SS "bool Key::hasLed"

.PP
Definition at line 19 of file keymap\&.h\&.
.PP
Referenced by ColorMap::init(), KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), KeyWidget::paintEvent(), and KeyWidget::selectAll()\&.
.SS "bool Key::hasScan"

.PP
Definition at line 20 of file keymap\&.h\&.
.PP
Referenced by KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), KeyWidget::paintEvent(), and KeyWidget::selectAll()\&.
.SS "short Key::height"

.PP
Definition at line 17 of file keymap\&.h\&.
.PP
Referenced by getMap(), KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), KeyWidget::paintEvent(), and patchANSI()\&.
.SS "const char* Key::name"

.PP
Definition at line 14 of file keymap\&.h\&.
.PP
Referenced by friendlyName(), ColorMap::init(), KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), operator bool(), KeyWidget::paintEvent(), KeyWidget::selectAll(), and storageName()\&.
.SS "short Key::width"

.PP
Definition at line 17 of file keymap\&.h\&.
.PP
Referenced by getMap(), KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), KeyWidget::paintEvent(), and patchANSI()\&.
.SS "short Key::x"

.PP
Definition at line 16 of file keymap\&.h\&.
.PP
Referenced by AnimScript::begin(), KeyMap::byPosition(), getMap(), AnimScript::keypress(), KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), KeyWidget::paintEvent(), and patchANSI()\&.
.SS "short Key::y"

.PP
Definition at line 16 of file keymap\&.h\&.
.PP
Referenced by AnimScript::begin(), KeyMap::byPosition(), getMap(), AnimScript::keypress(), KeyWidget::mouseMoveEvent(), KeyWidget::mousePressEvent(), KeyWidget::paintEvent(), and patchANSI()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
