src/ckb-mviz/kiss_fft.h
NAME
src/ckb-mviz/kiss_fft.h -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
Data Structures
struct kiss_fft_cpx
Macros
#define KISS_FFT_MALLOC malloc
#define KISS_FFT_FREE free
#define kiss_fft_scalar float
#define kiss_fft_free free
#define kiss_fftr_next_fast_size_real(n) (kiss_fft_next_fast_size( ((n)+1)>>1)<<1)
Typedefs
typedef struct kiss_fft_state * kiss_fft_cfg
Functions
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void *mem, size_t *lenmem)
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout)
void kiss_fft_stride (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout, int fin_stride)
void kiss_fft_cleanup (void)
int kiss_fft_next_fast_size (int n)
Data Structure Documentation
struct kiss_fft_cpx
Definition at line 51 of file kiss_fft.h.
Data Fields:
float i
float r
Macro Definition Documentation
#define KISS_FFT_FREE free
Definition at line 33 of file kiss_fft.h.
#define kiss_fft_free free
Definition at line 102 of file kiss_fft.h.
Referenced by getFreqDec().
#define KISS_FFT_MALLOC malloc
Definition at line 32 of file kiss_fft.h.
Referenced by kiss_fft_alloc(), and kiss_fftr_alloc().
#define kiss_fft_scalar float
Definition at line 47 of file kiss_fft.h.
#define kiss_fftr_next_fast_size_real(n) (kiss_fft_next_fast_size( ((n)+1)>>1)<<1)
Definition at line 117 of file kiss_fft.h.
Typedef Documentation
typedef struct kiss_fft_state* kiss_fft_cfg
Definition at line 56 of file kiss_fft.h.
Function Documentation
void kiss_fft (kiss_fft_cfgcfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout)
Definition at line 385 of file kiss_fft.c.
References kiss_fft_stride().
Referenced by getFreqDec(), kiss_fftr(), and kiss_fftri().
{
    kiss_fft_stride(cfg,fin,fout,1);
}
kiss_fft_cfg kiss_fft_alloc (intnfft, intinverse_fft, void *mem, size_t *lenmem)
Definition at line 339 of file kiss_fft.c.
References kiss_fft_state::factors, kiss_fft_state::inverse, kf_cexp, kf_factor(), KISS_FFT_MALLOC, kiss_fft_state::nfft, phase, and kiss_fft_state::twiddles.
Referenced by getFreqDec(), and kiss_fftr_alloc().
{
    kiss_fft_cfg st=NULL;
    size_t memneeded = sizeof(struct kiss_fft_state)
        + sizeof(kiss_fft_cpx)*(nfft-1); /* twiddle factors*/
    if ( lenmem==NULL ) {
        st = ( kiss_fft_cfg)KISS_FFT_MALLOC( memneeded );
    }else{
        if (mem != NULL && *lenmem >= memneeded)
            st = (kiss_fft_cfg)mem;
        *lenmem = memneeded;
    }
    if (st) {
        int i;
        st->nfft=nfft;
        st->inverse = inverse_fft;
        for (i=0;i<nfft;++i) {
            const double pi=3.141592653589793238462643383279502884197169399375105820974944;
            double phase = -2*pi*i / nfft;
            if (st->inverse)
                phase *= -1;
            kf_cexp(st->twiddles+i, phase );
        }
        kf_factor(nfft,st->factors);
    }
    return st;
}
void kiss_fft_cleanup (void)
Definition at line 391 of file kiss_fft.c.
Referenced by getFreqDec().
{
    // nothing needed any more
}
int kiss_fft_next_fast_size (intn)
Definition at line 396 of file kiss_fft.c.
{
    while(1) {
        int m=n;
        while ( (m%2) == 0 ) m/=2;
        while ( (m%3) == 0 ) m/=3;
        while ( (m%5) == 0 ) m/=5;
        if (m<=1)
            break; /* n is completely factorable by twos, threes, and fives */
        n++;
    }
    return n;
}
void kiss_fft_stride (kiss_fft_cfgcfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout, intfin_stride)
Definition at line 371 of file kiss_fft.c.
References kiss_fft_state::factors, kf_work(), KISS_FFT_TMP_ALLOC, KISS_FFT_TMP_FREE, and kiss_fft_state::nfft.
Referenced by kiss_fft().
{
    if (fin == fout) {
        //NOTE: this is not really an in-place FFT algorithm.
        //It just performs an out-of-place FFT into a temp buffer
        kiss_fft_cpx * tmpbuf = (kiss_fft_cpx*)KISS_FFT_TMP_ALLOC( sizeof(kiss_fft_cpx)*st->nfft);
        kf_work(tmpbuf,fin,1,in_stride, st->factors,st);
        memcpy(fout,tmpbuf,sizeof(kiss_fft_cpx)*st->nfft);
        KISS_FFT_TMP_FREE(tmpbuf);
    }else{
        kf_work( fout, fin, 1,in_stride, st->factors,st );
    }
}
Author
Generated automatically by Doxygen for ckb-next from the source code.