.TH "src/ckb/release/moc_extrasettingswidget.cpp" 3 "Tue May 16 2017" "Version beta-v0.2.7 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/release/moc_extrasettingswidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./extrasettingswidget\&.h'\fP
.br
\fC#include <QtCore/qbytearray\&.h>\fP
.br
\fC#include <QtCore/qmetatype\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqt_meta_stringdata_ExtraSettingsWidget_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx, ofs, len)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const 
.br
\fBqt_meta_stringdata_ExtraSettingsWidget_t\fP \fBqt_meta_stringdata_ExtraSettingsWidget\fP"
.br
.ti -1c
.RI "static const uint \fBqt_meta_data_ExtraSettingsWidget\fP []"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct qt_meta_stringdata_ExtraSettingsWidget_t"
.PP 
Definition at line 21 of file moc_extrasettingswidget\&.cpp\&.
.PP
\fBData Fields:\fP
.RS 4
QByteArrayData \fIdata[13]\fP 
.br
.PP
char \fIstringdata0[236]\fP 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
.fi
.PP
Definition at line 25 of file moc_extrasettingswidget\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const uint qt_meta_data_ExtraSettingsWidget[]\fC [static]\fP"

.PP
Definition at line 57 of file moc_extrasettingswidget\&.cpp\&.
.SS "const \fBqt_meta_stringdata_ExtraSettingsWidget_t\fP qt_meta_stringdata_ExtraSettingsWidget\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 19 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  0    -  0  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 18 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  20    -  1  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 0 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  39    -  2  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 7 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  40    -  3  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 24 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  48    -  4  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 25 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  73    -  5  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 22 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  99    -  6  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 4 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  122    -  7  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 20 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  127    -  8  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 20 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  148    -  9  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 20 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  169    -  10  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 25 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  190    -  11  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 19 ,   qptrdiff(offsetof(qt_meta_stringdata_ExtraSettingsWidget_t, stringdata0) +  216    -  12  * sizeof(QByteArrayData))   ) 

    },
    "ExtraSettingsWidget\0on_trayBox_clicked\0"
    "\0checked\0on_brightnessBox_clicked\0"
    "on_animScanButton_clicked\0"
    "on_fpsBox_valueChanged\0arg1\0"
    "on_ditherBox_clicked\0on_mAccelBox_clicked\0"
    "on_sAccelBox_clicked\0on_sSpeedBox_valueChanged\0"
    "on_delayBox_clicked"
}
.fi
.PP
Definition at line 30 of file moc_extrasettingswidget\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
