.TH "src/ckb/release/moc_macroreader.cpp" 3 "Sat Jun 17 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/release/moc_macroreader.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./macroreader\&.h'\fP
.br
\fC#include <QtCore/qbytearray\&.h>\fP
.br
\fC#include <QtCore/qmetatype\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqt_meta_stringdata_MacroReaderThread_t\fP"
.br
.ti -1c
.RI "struct \fBqt_meta_stringdata_MacroReader_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx, ofs, len)"
.br
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx, ofs, len)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const 
.br
\fBqt_meta_stringdata_MacroReaderThread_t\fP \fBqt_meta_stringdata_MacroReaderThread\fP"
.br
.ti -1c
.RI "static const uint \fBqt_meta_data_MacroReaderThread\fP []"
.br
.ti -1c
.RI "static const 
.br
\fBqt_meta_stringdata_MacroReader_t\fP \fBqt_meta_stringdata_MacroReader\fP"
.br
.ti -1c
.RI "static const uint \fBqt_meta_data_MacroReader\fP []"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct qt_meta_stringdata_MacroReaderThread_t"
.PP 
Definition at line 21 of file moc_macroreader\&.cpp\&.
.PP
\fBData Fields:\fP
.RS 4
QByteArrayData \fIdata[4]\fP 
.br
.PP
char \fIstringdata0[34]\fP 
.br
.PP
.RE
.PP
.SH "struct qt_meta_stringdata_MacroReader_t"
.PP 
Definition at line 111 of file moc_macroreader\&.cpp\&.
.PP
\fBData Fields:\fP
.RS 4
QByteArrayData \fIdata[1]\fP 
.br
.PP
char \fIstringdata0[12]\fP 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_MacroReaderThread_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
.fi
.PP
Definition at line 115 of file moc_macroreader\&.cpp\&.
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_MacroReader_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
.fi
.PP
Definition at line 115 of file moc_macroreader\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const uint qt_meta_data_MacroReader[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {

 
       7,       
       0,       
       0,    0, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,       
       0,       

       0        
}
.fi
.PP
Definition at line 129 of file moc_macroreader\&.cpp\&.
.SS "const uint qt_meta_data_MacroReaderThread[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {

 
       7,       
       0,       
       0,    0, 
       1,   14, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,       
       0,       

 
       1,    1,   19,    2, 0x08 ,

 
    QMetaType::Void, QMetaType::QString,    3,

       0        
}
.fi
.PP
Definition at line 42 of file moc_macroreader\&.cpp\&.
.SS "const \fBqt_meta_stringdata_MacroReader_t\fP qt_meta_stringdata_MacroReader\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 11 ,   qptrdiff(offsetof(qt_meta_stringdata_MacroReader_t, stringdata0) +  0    -  0  * sizeof(QByteArrayData))   ) 

    },
    "MacroReader"
}
.fi
.PP
Definition at line 120 of file moc_macroreader\&.cpp\&.
.SS "const \fBqt_meta_stringdata_MacroReaderThread_t\fP qt_meta_stringdata_MacroReaderThread\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 17 ,   qptrdiff(offsetof(qt_meta_stringdata_MacroReaderThread_t, stringdata0) +  0    -  0  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 9 ,   qptrdiff(offsetof(qt_meta_stringdata_MacroReaderThread_t, stringdata0) +  18    -  1  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 0 ,   qptrdiff(offsetof(qt_meta_stringdata_MacroReaderThread_t, stringdata0) +  28    -  2  * sizeof(QByteArrayData))   ), 
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 4 ,   qptrdiff(offsetof(qt_meta_stringdata_MacroReaderThread_t, stringdata0) +  29    -  3  * sizeof(QByteArrayData))   ) 

    },
    "MacroReaderThread\0readMacro\0\0line"
}
.fi
.PP
Definition at line 30 of file moc_macroreader\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
