src/ckb-daemon/notify.h
NAME
src/ckb-daemon/notify.h -
SYNOPSIS
#include 'includes.h'
#include 'device.h'
Functions
void nprintf (usbdevice *kb, int nodenumber, usbmode *mode, const char *format,...)
void nprintkey (usbdevice *kb, int nnumber, int keyindex, int down)
void nprintind (usbdevice *kb, int nnumber, int led, int on)
void cmd_notify (usbdevice *kb, usbmode *mode, int nnumber, int keyindex, const char *toggle)
void cmd_get (usbdevice *kb, usbmode *mode, int nnumber, int dummy, const char *setting)
void cmd_restart (usbdevice *kb, usbmode *mode, int nnumber, int dummy, const char *content)
Function Documentation
void cmd_get (usbdevice *kb, usbmode *mode, intnnumber, intdummy, const char *setting)
Definition at line 215 of file notify.c.
References _cmd_get(), and imutex.
                                                                                       {
    pthread_mutex_lock(imutex(kb));
    _cmd_get(kb, mode, nnumber, setting);
    pthread_mutex_unlock(imutex(kb));
}
void cmd_notify (usbdevice *kb, usbmode *mode, intnnumber, intkeyindex, const char *toggle)
Definition at line 61 of file notify.c.
References CLEAR_KEYBIT, imutex, N_KEYS_INPUT, usbmode::notify, and SET_KEYBIT.
                                                                                            {
    if(keyindex >= N_KEYS_INPUT)
        return;
    pthread_mutex_lock(imutex(kb));
    if(!strcmp(toggle, "on") || *toggle == 0)
        SET_KEYBIT(mode->notify[nnumber], keyindex);
    else if(!strcmp(toggle, "off"))
        CLEAR_KEYBIT(mode->notify[nnumber], keyindex);
    pthread_mutex_unlock(imutex(kb));
}
void cmd_restart (usbdevice *kb, usbmode *mode, intnnumber, intdummy, const char *content)
Definition at line 223 of file notify.c.
References ckb_info, nprintf(), and restart().
                                                                                            {
    ckb_info("RESTART called with %s\n", content);
    nprintf(kb, -1, 0, "RESTART called with %s\n", content);
    restart();
}
void nprintf (usbdevice *kb, intnodenumber, usbmode *mode, const char *format, ...)
Definition at line 8 of file notify.c.
References INDEX_OF, usbprofile::mode, usbdevice::outfifo, OUTFIFO_MAX, and usbdevice::profile.
Referenced by _cmd_get(), cmd_fwupdate(), cmd_restart(), fwupdate(), nprintind(), and nprintkey().
                                                                                   {
    if(!kb)
        return;
    usbprofile* profile = kb->profile;
    va_list va_args;
    int fifo;
    if(nodenumber >= 0){
        // If node number was given, print to that node (if open)
        if((fifo = kb->outfifo[nodenumber] - 1) != -1){
            va_start(va_args, format);
            if(mode)
                dprintf(fifo, "mode %d ", INDEX_OF(mode, profile->mode) + 1);
            vdprintf(fifo, format, va_args);
        }
        return;
    }
    // Otherwise, print to all nodes
    for(int i = 0; i < OUTFIFO_MAX; i++){
        if((fifo = kb->outfifo[i] - 1) != -1){
            va_start(va_args, format);
            if(mode)
                dprintf(fifo, "mode %d ", INDEX_OF(mode, profile->mode) + 1);
            vdprintf(fifo, format, va_args);
        }
    }
}
void nprintind (usbdevice *kb, intnnumber, intled, inton)
Definition at line 43 of file notify.c.
References I_CAPS, I_NUM, I_SCROLL, and nprintf().
Referenced by _cmd_get(), and updateindicators_kb().
                                                           {
    const char* name = 0;
    switch(led){
    case I_NUM:
        name = "num";
        break;
    case I_CAPS:
        name = "caps";
        break;
    case I_SCROLL:
        name = "scroll";
        break;
    default:
        return;
    }
    nprintf(kb, nnumber, 0, "i %c%s\n", on ? '+' : '-', name);
}
void nprintkey (usbdevice *kb, intnnumber, intkeyindex, intdown)
Definition at line 35 of file notify.c.
References keymap, key::name, and nprintf().
Referenced by _cmd_get(), and inputupdate_keys().
                                                                  {
    const key* map = keymap + keyindex;
    if(map->name)
        nprintf(kb, nnumber, 0, "key %c%s\n", down ? '+' : '-', map->name);
    else
        nprintf(kb, nnumber, 0, "key %c#%d\n", down ? '+' : '-', keyindex);
}
Author
Generated automatically by Doxygen for ckb-next from the source code.