.TH "QObject" 3 "Wed May 24 2017" "Version beta-v0.2.8+testing at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAnimScript\fP, \fBCkbSettingsWriter\fP, \fBKbAnim\fP, \fBKbBind\fP, \fBKbFirmware\fP, \fBKbLight\fP, \fBKbManager\fP, \fBKbMode\fP, \fBKbPerf\fP, \fBKbProfile\fP, and \fBKeyAction\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
