.TH "src/ckb/release/qrc_binary.cpp" 3 "Wed May 24 2017" "Version beta-v0.2.8+testing at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/release/qrc_binary.cpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_RCC_PREPEND_NAMESPACE\fP(name)   name"
.br
.ti -1c
.RI "#define \fBQT_RCC_MANGLE_NAMESPACE\fP(name)   name"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBqRegisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "bool \fBqUnregisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "int \fBqInitResources_binary\fP ()"
.br
.ti -1c
.RI "int \fBqCleanupResources_binary\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const unsigned char \fBqt_resource_data\fP []"
.br
.ti -1c
.RI "static const unsigned char \fBqt_resource_name\fP []"
.br
.ti -1c
.RI "static const unsigned char \fBqt_resource_struct\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_RCC_MANGLE_NAMESPACE(name)   name"

.PP
Definition at line 147 of file qrc_binary\&.cpp\&.
.SS "#define QT_RCC_PREPEND_NAMESPACE(name)   name"

.PP
Definition at line 146 of file qrc_binary\&.cpp\&.
.PP
Referenced by qCleanupResources_binary(), and qInitResources_binary()\&.
.SH "Function Documentation"
.PP 
.SS "int qCleanupResources_binary ()"

.PP
Definition at line 171 of file qrc_binary\&.cpp\&.
.PP
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData()\&.
.PP
.nf
172 {
173     QT_RCC_PREPEND_NAMESPACE(qUnregisterResourceData)
174        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
175     return 1;
176 }
.fi
.SS "int qInitResources_binary ()"

.PP
Definition at line 163 of file qrc_binary\&.cpp\&.
.PP
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct\&.
.PP
.nf
164 {
165     QT_RCC_PREPEND_NAMESPACE(qRegisterResourceData)
166         (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
167     return 1;
168 }
.fi
.SS "bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.PP
Referenced by qInitResources_binary()\&.
.SS "bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.PP
Referenced by qCleanupResources_binary()\&.
.SH "Variable Documentation"
.PP 
.SS "const unsigned char qt_resource_data[]\fC [static]\fP"

.PP
Definition at line 9 of file qrc_binary\&.cpp\&.
.PP
Referenced by qCleanupResources_binary(), and qInitResources_binary()\&.
.SS "const unsigned char qt_resource_name[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
  
  0x0,0x3,
  0x0,0x0,0x68,0xfe,
  0x0,0x62,
  0x0,0x69,0x0,0x6e,
    
  0x0,0x10,
  0x9,0x4b,0x25,0x27,
  0x0,0x63,
  0x0,0x6b,0x0,0x62,0x0,0x2d,0x0,0x6e,0x0,0x65,0x0,0x78,0x0,0x74,0x0,0x2d,0x0,0x6b,0x0,0x65,0x0,0x79,0x0,0x2e,0x0,0x67,0x0,0x70,0x0,0x67,
  
}
.fi
.PP
Definition at line 114 of file qrc_binary\&.cpp\&.
.PP
Referenced by qCleanupResources_binary(), and qInitResources_binary()\&.
.SS "const unsigned char qt_resource_struct[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x2,
  
  0x0,0x0,0x0,0xc,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,

}
.fi
.PP
Definition at line 128 of file qrc_binary\&.cpp\&.
.PP
Referenced by qCleanupResources_binary(), and qInitResources_binary()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
