src/ckb/release/qrc_binary.cpp
NAME
src/ckb/release/qrc_binary.cpp -
SYNOPSIS
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int qInitResources_binary ()
int qCleanupResources_binary ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
#define QT_RCC_MANGLE_NAMESPACE(name) name
Definition at line 147 of file qrc_binary.cpp.
#define QT_RCC_PREPEND_NAMESPACE(name) name
Definition at line 146 of file qrc_binary.cpp.
Referenced by qCleanupResources_binary(), and qInitResources_binary().
Function Documentation
int qCleanupResources_binary ()
Definition at line 171 of file qrc_binary.cpp.
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
{
    QT_RCC_PREPEND_NAMESPACE(qUnregisterResourceData)
       (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
int qInitResources_binary ()
Definition at line 163 of file qrc_binary.cpp.
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
{
    QT_RCC_PREPEND_NAMESPACE(qRegisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qInitResources_binary().
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qCleanupResources_binary().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 9 of file qrc_binary.cpp.
Referenced by qCleanupResources_binary(), and qInitResources_binary().
const unsigned char qt_resource_name[] [static]
Initial value:
= {
  
  0x0,0x3,
  0x0,0x0,0x68,0xfe,
  0x0,0x62,
  0x0,0x69,0x0,0x6e,
    
  0x0,0x10,
  0x9,0x4b,0x25,0x27,
  0x0,0x63,
  0x0,0x6b,0x0,0x62,0x0,0x2d,0x0,0x6e,0x0,0x65,0x0,0x78,0x0,0x74,0x0,0x2d,0x0,0x6b,0x0,0x65,0x0,0x79,0x0,0x2e,0x0,0x67,0x0,0x70,0x0,0x67,
  
}
Definition at line 114 of file qrc_binary.cpp.
Referenced by qCleanupResources_binary(), and qInitResources_binary().
const unsigned char qt_resource_struct[] [static]
Initial value:
= {
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x2,
  
  0x0,0x0,0x0,0xc,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
}
Definition at line 128 of file qrc_binary.cpp.
Referenced by qCleanupResources_binary(), and qInitResources_binary().
Author
Generated automatically by Doxygen for ckb-next from the source code.