QuaZipDir
NAME
QuaZipDir -
Provides ZIP archive navigation.
SYNOPSIS
#include <src/ckb/quazip/quazipdir.h>
Public Member Functions
QuaZipDir (const QuaZipDir &that)
The copy constructor.
QuaZipDir (QuaZip *zip, const QString &dir=QString())
Constructs a QuaZipDir instance pointing to the specified directory.
~QuaZipDir ()
Destructor.
bool operator== (const QuaZipDir &that)
The assignment operator.
bool operator!= (const QuaZipDir &that)
operator!=
QuaZipDir & operator= (const QuaZipDir &that)
operator==
QString operator[] (int pos) const
Returns the name of the entry at the specified position.
QuaZip::CaseSensitivity caseSensitivity () const
Returns the current case sensitivity mode.
bool cd (const QString &dirName)
Changes the 'current' directory.
bool cdUp ()
Goes up.
uint count () const
Returns the number of entries in the directory.
QString dirName () const
Returns the current directory name.
QList< QuaZipFileInfo > entryInfoList (const QStringList &nameFilters, QDir::Filters filters=QDir::NoFilter, QDir::SortFlags sort=QDir::NoSort) const
Returns the list of the entries in the directory.
QList< QuaZipFileInfo > entryInfoList (QDir::Filters filters=QDir::NoFilter, QDir::SortFlags sort=QDir::NoSort) const
Returns the list of the entries in the directory.
QList< QuaZipFileInfo64 > entryInfoList64 (const QStringList &nameFilters, QDir::Filters filters=QDir::NoFilter, QDir::SortFlags sort=QDir::NoSort) const
Returns the list of the entries in the directory with zip64 support.
QList< QuaZipFileInfo64 > entryInfoList64 (QDir::Filters filters=QDir::NoFilter, QDir::SortFlags sort=QDir::NoSort) const
Returns the list of the entries in the directory with zip64 support.
QStringList entryList (const QStringList &nameFilters, QDir::Filters filters=QDir::NoFilter, QDir::SortFlags sort=QDir::NoSort) const
Returns the list of the entry names in the directory.
QStringList entryList (QDir::Filters filters=QDir::NoFilter, QDir::SortFlags sort=QDir::NoSort) const
Returns the list of the entry names in the directory.
bool exists (const QString &fileName) const
Returns true if the entry with the specified name exists.
bool exists () const
Return true if the directory pointed by this QuaZipDir exists.
QString filePath (const QString &fileName) const
Returns the full path to the specified file.
QDir::Filters filter ()
Returns the default filter.
bool isRoot () const
Returns if the QuaZipDir points to the root of the archive.
QStringList nameFilters () const
Return the default name filter.
QString path () const
Returns the path to the current dir.
QString relativeFilePath (const QString &fileName) const
Returns the path to the specified file relative to the current dir.
void setCaseSensitivity (QuaZip::CaseSensitivity caseSensitivity)
Sets the default case sensitivity mode.
void setFilter (QDir::Filters filters)
Sets the default filter.
void setNameFilters (const QStringList &nameFilters)
Sets the default name filter.
void setPath (const QString &path)
Goes to the specified path.
void setSorting (QDir::SortFlags sort)
Sets the default sorting mode.
QDir::SortFlags sorting () const
Returns the default sorting mode.
Private Attributes
QSharedDataPointer
< QuaZipDirPrivate > d"
Detailed Description
This class is modelled after QDir, and is designed to provide similar features for ZIP archives.
The only significant difference from QDir is that the root path is not '/', but an empty string since that's how the file paths are stored in the archive. However, QuaZipDir understands the paths starting with '/'. It is important in a few places:
In the cd() function.
In the constructor.
In the exists() function.
In the relativePath() function.
Note that since ZIP uses '/' on all platforms, the '\' separator is not supported.
Definition at line 54 of file quazipdir.h.
Constructor & Destructor Documentation
QuaZipDir::QuaZipDir (const QuaZipDir &that)
Definition at line 50 of file quazipdir.cpp.
Referenced by exists().
                                         :
    d(that.d)
{
}
QuaZipDir::QuaZipDir (QuaZip *zip, const QString &dir = QString())
If dir is not specified, points to the root of the archive. The same happens if the dir is "/".
Definition at line 55 of file quazipdir.cpp.
References d.
                                                   :
    d(new QuaZipDirPrivate(zip, dir))
{
    if (d->dir.startsWith('/'))
        d->dir = d->dir.mid(1);
}
QuaZipDir::~QuaZipDir ()
Definition at line 62 of file quazipdir.cpp.
{
}
Member Function Documentation
QuaZip::CaseSensitivity QuaZipDir::caseSensitivity () const
Definition at line 82 of file quazipdir.cpp.
References d.
Referenced by setCaseSensitivity().
{
    return d->caseSensitivity;
}
bool QuaZipDir::cd (const QString &dirName)
If the path starts with '/', it is interpreted as an absolute path from the root of the archive. Otherwise, it is interpreted as a path relative to the current directory as was set by the previous cd() or the constructor.
Note that the subsequent path() call will not return a path starting with '/' in all cases.
Definition at line 87 of file quazipdir.cpp.
References cd(), d, dirName(), exists(), isRoot(), and path().
Referenced by cd(), and cdUp().
{
    if (directoryName == "/") {
        d->dir = "";
        return true;
    }
    QString dirName = directoryName;
    if (dirName.endsWith('/'))
        dirName.chop(1);
    if (dirName.contains('/')) {
        QuaZipDir dir(*this);
        if (dirName.startsWith('/')) {
#ifdef QUAZIP_QUAZIPDIR_DEBUG
            qDebug("QuaZipDir::cd(%s): going to /",
                    dirName.toUtf8().constData());
#endif
            if (!dir.cd("/"))
                return false;
        }
        QStringList path = dirName.split('/', QString::SkipEmptyParts);
        for (QStringList::const_iterator i = path.constBegin();
                i != path.end();
                ++i) {
            const QString &step = *i;
#ifdef QUAZIP_QUAZIPDIR_DEBUG
            qDebug("QuaZipDir::cd(%s): going to %s",
                    dirName.toUtf8().constData(),
                    step.toUtf8().constData());
#endif
            if (!dir.cd(step))
                return false;
        }
        d->dir = dir.path();
        return true;
    } else { // no '/'
        if (dirName == ".") {
            return true;
        } else if (dirName == "..") {
            if (isRoot()) {
                return false;
            } else {
                int slashPos = d->dir.lastIndexOf('/');
                if (slashPos == -1) {
                    d->dir = "";
                } else {
                    d->dir = d->dir.left(slashPos);
                }
                return true;
            }
        } else { // a simple subdirectory
            if (exists(dirName)) {
                if (isRoot())
                    d->dir = dirName;
                else
                    d->dir += "/" + dirName;
                return true;
            } else {
                return false;
            }
        }
    }
}
bool QuaZipDir::cdUp ()
Definition at line 150 of file quazipdir.cpp.
References cd().
{
    return cd("..");
}
uint QuaZipDir::count () const
Definition at line 155 of file quazipdir.cpp.
References entryList().
{
    return entryList().count();
}
QString QuaZipDir::dirName () const
The name doesn't include the path.
Definition at line 160 of file quazipdir.cpp.
References d.
Referenced by cd().
{
    return QDir(d->dir).dirName();
}
QList< QuaZipFileInfo > QuaZipDir::entryInfoList (const QStringList &nameFilters, QDir::Filtersfilters = QDir::NoFilter, QDir::SortFlagssort = QDir::NoSort) const
Parameters:
nameFilters The list of file patterns to list, uses the same syntax as QDir.
filters The entry type filters, only Files and Dirs are accepted.
sort Sorting mode.
Definition at line 401 of file quazipdir.cpp.
References d.
Referenced by entryInfoList().
{
    QList<QuaZipFileInfo> result;
    if (d->entryInfoList(nameFilters, filters, sort, result))
        return result;
    else
        return QList<QuaZipFileInfo>();
}
QList< QuaZipFileInfo > QuaZipDir::entryInfoList (QDir::Filtersfilters = QDir::NoFilter, QDir::SortFlagssort = QDir::NoSort) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The same as entryInfoList(QStringList(), filters, sort).
Definition at line 411 of file quazipdir.cpp.
References entryInfoList().
{
    return entryInfoList(QStringList(), filters, sort);
}
QList< QuaZipFileInfo64 > QuaZipDir::entryInfoList64 (const QStringList &nameFilters, QDir::Filtersfilters = QDir::NoFilter, QDir::SortFlagssort = QDir::NoSort) const
Parameters:
nameFilters The list of file patterns to list, uses the same syntax as QDir.
filters The entry type filters, only Files and Dirs are accepted.
sort Sorting mode.
Definition at line 417 of file quazipdir.cpp.
References d.
Referenced by entryInfoList64().
{
    QList<QuaZipFileInfo64> result;
    if (d->entryInfoList(nameFilters, filters, sort, result))
        return result;
    else
        return QList<QuaZipFileInfo64>();
}
QList< QuaZipFileInfo64 > QuaZipDir::entryInfoList64 (QDir::Filtersfilters = QDir::NoFilter, QDir::SortFlagssort = QDir::NoSort) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The same as entryInfoList64(QStringList(), filters, sort).
Definition at line 427 of file quazipdir.cpp.
References entryInfoList64().
{
    return entryInfoList64(QStringList(), filters, sort);
}
QStringList QuaZipDir::entryList (const QStringList &nameFilters, QDir::Filtersfilters = QDir::NoFilter, QDir::SortFlagssort = QDir::NoSort) const
The same as entryInfoList(nameFilters, filters, sort), but only returns entry names.
Definition at line 433 of file quazipdir.cpp.
References d.
Referenced by count(), entryList(), exists(), and operator[]().
{
    QStringList result;
    if (d->entryInfoList(nameFilters, filters, sort, result))
        return result;
    else
        return QStringList();
}
QStringList QuaZipDir::entryList (QDir::Filtersfilters = QDir::NoFilter, QDir::SortFlagssort = QDir::NoSort) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The same as entryList(QStringList(), filters, sort).
Definition at line 443 of file quazipdir.cpp.
References entryList().
{
    return entryList(QStringList(), filters, sort);
}
bool QuaZipDir::exists (const QString &fileName) const
The ".." is considered to exist if the current directory is not root. The "." and "/" are considered to always exist. Paths starting with "/" are relative to the archive root, other paths are relative to the current dir.
Definition at line 449 of file quazipdir.cpp.
References QuaZip::convertCaseSensitivity(), d, entryList(), filePath(), and isRoot().
{
    if (filePath == "/" || filePath.isEmpty())
        return true;
    QString fileName = filePath;
    if (fileName.endsWith('/'))
        fileName.chop(1);
    if (fileName.contains('/')) {
        QFileInfo fileInfo(fileName);
#ifdef QUAZIP_QUAZIPDIR_DEBUG
        qDebug("QuaZipDir::exists(): fileName=%s, fileInfo.fileName()=%s, "
                "fileInfo.path()=%s", fileName.toUtf8().constData(),
                fileInfo.fileName().toUtf8().constData(),
                fileInfo.path().toUtf8().constData());
#endif
        QuaZipDir dir(*this);
        return dir.cd(fileInfo.path()) && dir.exists(fileInfo.fileName());
    } else {
        if (fileName == "..") {
            return !isRoot();
        } else if (fileName == ".") {
            return true;
        } else {
            QStringList entries = entryList(QDir::AllEntries, QDir::NoSort);
#ifdef QUAZIP_QUAZIPDIR_DEBUG
            qDebug("QuaZipDir::exists(): looking for %s",
                    fileName.toUtf8().constData());
            for (QStringList::const_iterator i = entries.constBegin();
                    i != entries.constEnd();
                    ++i) {
                qDebug("QuaZipDir::exists(): entry: %s",
                        i->toUtf8().constData());
            }
#endif
            Qt::CaseSensitivity cs = QuaZip::convertCaseSensitivity(
                    d->caseSensitivity);
            if (filePath.endsWith('/')) {
                return entries.contains(filePath, cs);
            } else {
                return entries.contains(fileName, cs)
                    || entries.contains(fileName + "/", cs);
            }
        }
    }
}
bool QuaZipDir::exists () const
Definition at line 495 of file quazipdir.cpp.
References d, and QuaZipDir().
Referenced by cd().
{
    return QuaZipDir(d->zip).exists(d->dir);
}
QString QuaZipDir::filePath (const QString &fileName) const
Doesn't check if the file actually exists.
Definition at line 500 of file quazipdir.cpp.
References d.
Referenced by exists().
{
    return QDir(d->dir).filePath(fileName);
}
QDir::Filters QuaZipDir::filter ()
Definition at line 505 of file quazipdir.cpp.
References d.
{
    return d->filter;
}
bool QuaZipDir::isRoot () const
Not that the root path is the empty string, not '/'.
Definition at line 510 of file quazipdir.cpp.
References d.
Referenced by cd(), and exists().
{
    return d->simplePath().isEmpty();
}
QStringList QuaZipDir::nameFilters () const
Definition at line 515 of file quazipdir.cpp.
References d.
Referenced by setNameFilters().
{
    return d->nameFilters;
}
bool QuaZipDir::operator!= (const QuaZipDir &that) [inline]
Returns:
true if either this and that use different QuaZip instances or if they point to different directories.
Definition at line 75 of file quazipdir.h.
{return !operator==(that);}
QuaZipDir & QuaZipDir::operator= (const QuaZipDir &that)
Returns:
true if both this and that use the same QuaZip instance and point to the same directory.
Definition at line 71 of file quazipdir.cpp.
References d.
{
    this->d = that.d;
    return *this;
}
bool QuaZipDir::operator== (const QuaZipDir &that)
Definition at line 66 of file quazipdir.cpp.
References d.
{
    return d->zip == that.d->zip && d->dir == that.d->dir;
}
QString QuaZipDir::operator[] (intpos) const
Definition at line 77 of file quazipdir.cpp.
References entryList().
{
    return entryList().at(pos);
}
QString QuaZipDir::path () const
The path never starts with '/', and the root path is an empty string.
Definition at line 520 of file quazipdir.cpp.
References d.
Referenced by cd(), and setPath().
{
    return d->dir;
}
QString QuaZipDir::relativeFilePath (const QString &fileName) const
This function is mostly useless, provided only for the sake of completeness.
Parameters:
fileName The path to the file, should start with "/" if relative to the archive root.
Returns:
Path relative to the current dir.
Definition at line 525 of file quazipdir.cpp.
References d.
{
    return QDir("/" + d->dir).relativeFilePath(fileName);
}
void QuaZipDir::setCaseSensitivity (QuaZip::CaseSensitivitycaseSensitivity)
Definition at line 530 of file quazipdir.cpp.
References caseSensitivity(), and d.
{
    d->caseSensitivity = caseSensitivity;
}
void QuaZipDir::setFilter (QDir::Filtersfilters)
Definition at line 535 of file quazipdir.cpp.
References d.
{
    d->filter = filters;
}
void QuaZipDir::setNameFilters (const QStringList &nameFilters)
Definition at line 540 of file quazipdir.cpp.
References d, and nameFilters().
{
    d->nameFilters = nameFilters;
}
void QuaZipDir::setPath (const QString &path)
The difference from cd() is that this function never checks if the path actually exists and doesn't use relative paths, so it's possible to go to the root directory with setPath("").
Note that this function still chops the trailing and/or leading '/' and treats a single '/' as the root path (path() will still return an empty string).
Definition at line 545 of file quazipdir.cpp.
References d, and path().
{
    QString newDir = path;
    if (newDir == "/") {
        d->dir = "";
    } else {
        if (newDir.endsWith('/'))
            newDir.chop(1);
        if (newDir.startsWith('/'))
            newDir = newDir.mid(1);
        d->dir = newDir;
    }
}
void QuaZipDir::setSorting (QDir::SortFlagssort)
Definition at line 559 of file quazipdir.cpp.
References d.
{
    d->sorting = sort;
}
QDir::SortFlags QuaZipDir::sorting () const
Definition at line 564 of file quazipdir.cpp.
References d.
{
    return d->sorting;
}
Field Documentation
QSharedDataPointer<QuaZipDirPrivate> QuaZipDir::d [private]
Definition at line 56 of file quazipdir.h.
Referenced by caseSensitivity(), cd(), dirName(), entryInfoList(), entryInfoList64(), entryList(), exists(), filePath(), filter(), isRoot(), nameFilters(), operator=(), operator==(), path(), QuaZipDir(), relativeFilePath(), setCaseSensitivity(), setFilter(), setNameFilters(), setPath(), setSorting(), and sorting().
Author
Generated automatically by Doxygen for ckb-next from the source code.