.TH "src/ckb/quazip/quazip.h" 3 "Tue Aug 15 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quazip.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QTextCodec>\fP
.br
\fC#include 'zip\&.h'\fP
.br
\fC#include 'unzip\&.h'\fP
.br
\fC#include 'quazip_global\&.h'\fP
.br
\fC#include 'quazipfileinfo\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQuaZip\fP"
.br
.RI "\fIZIP archive\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNZ_OPENERROR\fP   -1000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UNZ_OPENERROR   -1000"

.PP
Definition at line 41 of file quazip\&.h\&.
.PP
Referenced by QuaZip::open()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
