.TH "src/ckb/rebindwidget.h" 3 "Sat Feb 3 2018" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/rebindwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include 'kbbind\&.h'\fP
.br
\fC#include 'kbprofile\&.h'\fP
.br
\fC#include 'macroreader\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBRebindWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
