SettingsWidget
NAME
SettingsWidget -
SYNOPSIS
#include <src/ckb/settingswidget.h>
Inherits QWidget.
Public Member Functions
SettingsWidget (QWidget *parent=0)
~SettingsWidget ()
void setVersion (const QString &version)
void setStatus (const QString &text)
void pollUpdates ()
Private Slots
void on_pushButton_clicked ()
void on_capsBox_activated (int index)
void on_shiftBox_activated (int index)
void on_ctrlBox_activated (int index)
void on_altBox_activated (int index)
void on_winBox_activated (int index)
void on_autoFWBox_clicked (bool checked)
void on_loginItemBox_clicked (bool checked)
void on_layoutBox_activated (int index)
void showLayoutDialog ()
void on_extraButton_clicked ()
Private Member Functions
void updateModifiers ()
Private Attributes
Ui::SettingsWidget * ui
ExtraSettingsWidget * extra
Friends
class MainWindow
Detailed Description
Definition at line 11 of file settingswidget.h.
Constructor & Destructor Documentation
SettingsWidget::SettingsWidget (QWidget *parent = 0) [explicit]
Definition at line 15 of file settingswidget.cpp.
References Ui_SettingsWidget::altBox, Ui_SettingsWidget::autoFWBox, AutoRun::available(), Ui_SettingsWidget::capsBox, Ui_SettingsWidget::ctrlBox, AutoRun::enable(), extra, KeyMap::getLayout(), KbBind::globalRemap(), AutoRun::isEnabled(), Kb::layout(), Ui_SettingsWidget::layoutBox, KeyMap::layoutNames(), KbBind::loadGlobalRemap(), KeyMap::locale(), Ui_SettingsWidget::loginItemBox, modKeys, modNames, KeyMap::NO_LAYOUT, AutoRun::once(), CkbSettings::remove(), Ui_SettingsWidget::setupUi(), CkbSettings::setValue(), Ui_SettingsWidget::shiftBox, showLayoutDialog(), ui, updateModifiers(), CkbSettings::value(), and Ui_SettingsWidget::winBox.
                                              :
    QWidget(parent),
    ui(new Ui::SettingsWidget)
{
    ui->setupUi(this);
    CkbSettings settings("Program");
    // Read keyboard layout
    ui->layoutBox->addItems(KeyMap::layoutNames());
    KeyMap::Layout layout = KeyMap::getLayout(settings.value("KbdLayout").toString());
    if(layout == KeyMap::NO_LAYOUT){
        // If the layout hasn't been set yet, show a dialog to let the user choose it
        layout = KeyMap::locale();
        QTimer::singleShot(1000, this, SLOT(showLayoutDialog())); // Run the function after a delay as the dialog may not appear correctly otherwise
        settings.setValue("KbdLayout", KeyMap::getLayout(layout));
    }
    Kb::layout(layout);
    ui->layoutBox->setCurrentIndex((int)layout);
    // Load modifier remap
    KbBind::loadGlobalRemap();
    if(modKeys.isEmpty()){
        modKeys << "caps" << "lshift" << "lctrl" << "lalt" << "lwin";
#ifdef Q_OS_MACX
        modNames << "Caps Lock" << "Shift" << "Control (⌃)" << "Option (⌥)" << "Command (⌘)";
#else
        modNames << "Caps Lock" << "Shift" << "Control" << "Alt" << "Super";
#endif
    }
    foreach(const QString& name, modNames){
        ui->capsBox->addItem(name);
        ui->shiftBox->addItem(name);
        ui->ctrlBox->addItem(name);
        ui->altBox->addItem(name);
        ui->winBox->addItem(name);
    }
    int idx = modKeys.indexOf(KbBind::globalRemap("caps"));
    if(idx >= 0)
        ui->capsBox->setCurrentIndex(idx);
    idx = modKeys.indexOf(KbBind::globalRemap("lshift"));
    if(idx >= 0)
        ui->shiftBox->setCurrentIndex(idx);
    idx = modKeys.indexOf(KbBind::globalRemap("lctrl"));
    if(idx >= 0)
        ui->ctrlBox->setCurrentIndex(idx);
    idx = modKeys.indexOf(KbBind::globalRemap("lwin"));
    if(idx >= 0)
        ui->winBox->setCurrentIndex(idx);
    idx = modKeys.indexOf(KbBind::globalRemap("lalt"));
    if(idx >= 0)
        ui->altBox->setCurrentIndex(idx);
#ifdef Q_OS_MACX
    if(settings.value("osxCmdSwap").toBool()){
        // ckb <0.0.41
        settings.remove("osxCmdSwap");
        ui->ctrlBox->setCurrentIndex(modKeys.indexOf("lwin"));
        ui->winBox->setCurrentIndex(modKeys.indexOf("lctrl"));
        updateModifiers();
    }
#endif
    // Read auto update settings
    ui->autoFWBox->setChecked(!settings.value("DisableAutoFWCheck").toBool());
    // Read auto run settings
    if(!AutoRun::available())
        ui->loginItemBox->hide();
    else {
        if(!AutoRun::once())
            // If this is the first time running the app, enable auto run by default
            AutoRun::enable();
        ui->loginItemBox->setChecked(AutoRun::isEnabled());
    }
    // Prepare extra settings
    extra = new ExtraSettingsWidget(this);
}
SettingsWidget::~SettingsWidget ()
Definition at line 94 of file settingswidget.cpp.
References ui.
                               {
    delete ui;
}
Member Function Documentation
void SettingsWidget::on_altBox_activated (intindex) [private], [slot]
Definition at line 155 of file settingswidget.cpp.
References updateModifiers().
                                                 {
    updateModifiers();
}
void SettingsWidget::on_autoFWBox_clicked (boolchecked) [private], [slot]
Definition at line 163 of file settingswidget.cpp.
References CkbSettings::set().
                                                     {
    CkbSettings::set("Program/DisableAutoFWCheck", !checked);
}
void SettingsWidget::on_capsBox_activated (intindex) [private], [slot]
Definition at line 143 of file settingswidget.cpp.
References updateModifiers().
                                                  {
    updateModifiers();
}
void SettingsWidget::on_ctrlBox_activated (intindex) [private], [slot]
Definition at line 151 of file settingswidget.cpp.
References updateModifiers().
                                                  {
    updateModifiers();
}
void SettingsWidget::on_extraButton_clicked () [private], [slot]
Definition at line 180 of file settingswidget.cpp.
References extra.
                                           {
    extra->exec();
}
void SettingsWidget::on_layoutBox_activated (intindex) [private], [slot]
Definition at line 174 of file settingswidget.cpp.
References KeyMap::getLayout(), Kb::layout(), and CkbSettings::set().
Referenced by showLayoutDialog().
                                                    {
    KeyMap::Layout layout = (KeyMap::Layout)index;
    CkbSettings::set("Program/KbdLayout", KeyMap::getLayout(layout));
    Kb::layout(layout);
}
void SettingsWidget::on_loginItemBox_clicked (boolchecked) [private], [slot]
Definition at line 167 of file settingswidget.cpp.
References AutoRun::disable(), and AutoRun::enable().
                                                        {
    if(checked)
        AutoRun::enable();
    else
        AutoRun::disable();
}
void SettingsWidget::on_pushButton_clicked () [private], [slot]
Definition at line 139 of file settingswidget.cpp.
                                          {
    qApp->quit();
}
void SettingsWidget::on_shiftBox_activated (intindex) [private], [slot]
Definition at line 147 of file settingswidget.cpp.
References updateModifiers().
                                                   {
    updateModifiers();
}
void SettingsWidget::on_winBox_activated (intindex) [private], [slot]
Definition at line 159 of file settingswidget.cpp.
References updateModifiers().
                                                 {
    updateModifiers();
}
void SettingsWidget::pollUpdates ()
Definition at line 106 of file settingswidget.cpp.
References extra, and ExtraSettingsWidget::pollUpdates().
Referenced by MainWindow::timerTick().
                                {
    extra->pollUpdates();
}
void SettingsWidget::setStatus (const QString &text)
Definition at line 110 of file settingswidget.cpp.
References Ui_SettingsWidget::devicesLabel, and ui.
Referenced by MainWindow::updateVersion().
                                                 {
    ui->devicesLabel->setText(text);
}
void SettingsWidget::setVersion (const QString &version)
Definition at line 114 of file settingswidget.cpp.
References ui, and Ui_SettingsWidget::versionLabel.
Referenced by MainWindow::MainWindow().
                                                     {
    ui->versionLabel->setText(version);
}
void SettingsWidget::showLayoutDialog () [private], [slot]
Definition at line 98 of file settingswidget.cpp.
References Ui_SettingsWidget::layoutBox, on_layoutBox_activated(), LayoutDialog::selected(), and ui.
Referenced by SettingsWidget().
                                     {
    LayoutDialog dialog(this);
    dialog.exec();
    // Set selected layout
    ui->layoutBox->setCurrentIndex((int)dialog.selected());
    on_layoutBox_activated((int)dialog.selected()); // Call activated() signal manually to trigger save
}
void SettingsWidget::updateModifiers () [private]
Definition at line 124 of file settingswidget.cpp.
References Ui_SettingsWidget::altBox, Ui_SettingsWidget::capsBox, Ui_SettingsWidget::ctrlBox, modKeys, right(), KbBind::saveGlobalRemap(), KbBind::setGlobalRemap(), Ui_SettingsWidget::shiftBox, ui, and Ui_SettingsWidget::winBox.
Referenced by on_altBox_activated(), on_capsBox_activated(), on_ctrlBox_activated(), on_shiftBox_activated(), on_winBox_activated(), and SettingsWidget().
                                    {
    QHash<QString, QString> newMods;
    newMods["caps"] = modKeys[ui->capsBox->currentIndex()];
    newMods["lshift"] = modKeys[ui->shiftBox->currentIndex()];
    newMods["rshift"] = right(modKeys[ui->shiftBox->currentIndex()]);
    newMods["lctrl"] = modKeys[ui->ctrlBox->currentIndex()];
    newMods["rctrl"] = right(modKeys[ui->ctrlBox->currentIndex()]);
    newMods["lalt"] = modKeys[ui->altBox->currentIndex()];
    newMods["ralt"] = right(modKeys[ui->altBox->currentIndex()]);
    newMods["lwin"] = modKeys[ui->winBox->currentIndex()];
    newMods["rwin"] = right(modKeys[ui->winBox->currentIndex()]);
    KbBind::setGlobalRemap(newMods);
    KbBind::saveGlobalRemap();
}
Friends And Related Function Documentation
friend class MainWindow [friend]
Definition at line 44 of file settingswidget.h.
Field Documentation
ExtraSettingsWidget* SettingsWidget::extra [private]
Definition at line 46 of file settingswidget.h.
Referenced by on_extraButton_clicked(), pollUpdates(), and SettingsWidget().
Ui::SettingsWidget* SettingsWidget::ui [private]
Definition at line 43 of file settingswidget.h.
Referenced by setStatus(), SettingsWidget(), setVersion(), showLayoutDialog(), updateModifiers(), and ~SettingsWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.