.TH "Ui::KbWidget" 3 "Sun Jun 18 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::KbWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/ui_kbwidget\&.h>\fP
.PP
Inherits \fBUi_KbWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetupUi\fP (\fBQWidget\fP *\fBKbWidget\fP)"
.br
.ti -1c
.RI "void \fBretranslateUi\fP (\fBQWidget\fP *\fBKbWidget\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "QGridLayout * \fBgridLayout\fP"
.br
.ti -1c
.RI "QComboBox * \fBprofileBox\fP"
.br
.ti -1c
.RI "QTabWidget * \fBtabWidget\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBlightTab\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout_2\fP"
.br
.ti -1c
.RI "\fBKbLightWidget\fP * \fBlightWidget\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel_3\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBbindTab\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout_5\fP"
.br
.ti -1c
.RI "\fBKbBindWidget\fP * \fBbindWidget\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBkPerfTab\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout_4\fP"
.br
.ti -1c
.RI "\fBKPerfWidget\fP * \fBkPerfWidget\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBmPerfTab\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout_7\fP"
.br
.ti -1c
.RI "\fBMPerfWidget\fP * \fBmPerfWidget\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBdevTab\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout_3\fP"
.br
.ti -1c
.RI "QLabel * \fBfwUpdLabel\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBverticalSpacer\fP"
.br
.ti -1c
.RI "QLabel * \fBfwLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel_4\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_2\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel_9\fP"
.br
.ti -1c
.RI "QLabel * \fBserialLabel\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBfwUpdLayout\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBfwUpdButton\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_3\fP"
.br
.ti -1c
.RI "QLabel * \fBpollLabel2\fP"
.br
.ti -1c
.RI "QLabel * \fBpollLabel\fP"
.br
.ti -1c
.RI "\fBRListWidget\fP * \fBmodesList\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBhwSaveButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 291 of file ui_kbwidget\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ui_KbWidget::retranslateUi (\fBQWidget\fP *KbWidget)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Definition at line 268 of file ui_kbwidget\&.h\&.
.PP
References Ui_KbWidget::bindTab, Ui_KbWidget::devTab, Ui_KbWidget::fwLabel, Ui_KbWidget::fwUpdButton, Ui_KbWidget::fwUpdLabel, Ui_KbWidget::hwSaveButton, Ui_KbWidget::kPerfTab, Ui_KbWidget::label_3, Ui_KbWidget::label_4, Ui_KbWidget::label_9, Ui_KbWidget::lightTab, Ui_KbWidget::mPerfTab, Ui_KbWidget::pollLabel, Ui_KbWidget::pollLabel2, Ui_KbWidget::serialLabel, and Ui_KbWidget::tabWidget\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.PP
.nf
269     {
270         KbWidget->setWindowTitle(QApplication::translate("KbWidget", "Form", Q_NULLPTR));
271         label_3->setText(QApplication::translate("KbWidget", "Tip: Drag+drop items to reorder\&. Right-click for menu\&.", Q_NULLPTR));
272         tabWidget->setTabText(tabWidget->indexOf(lightTab), QApplication::translate("KbWidget", "Lighting", Q_NULLPTR));
273         tabWidget->setTabText(tabWidget->indexOf(bindTab), QApplication::translate("KbWidget", "Binding", Q_NULLPTR));
274         tabWidget->setTabText(tabWidget->indexOf(kPerfTab), QApplication::translate("KbWidget", "Performance", Q_NULLPTR));
275         tabWidget->setTabText(tabWidget->indexOf(mPerfTab), QApplication::translate("KbWidget", "Performance", Q_NULLPTR));
276         fwUpdLabel->setText(QApplication::translate("KbWidget", "Status:", Q_NULLPTR));
277         fwLabel->setText(QApplication::translate("KbWidget", "N/A", Q_NULLPTR));
278         label_4->setText(QApplication::translate("KbWidget", "USB device ID:", Q_NULLPTR));
279         label_9->setText(QApplication::translate("KbWidget", "Firmware version:", Q_NULLPTR));
280         serialLabel->setText(QApplication::translate("KbWidget", "N/A", Q_NULLPTR));
281         fwUpdButton->setText(QApplication::translate("KbWidget", "Check for updates", Q_NULLPTR));
282         pollLabel2->setText(QApplication::translate("KbWidget", "Poll rate:", Q_NULLPTR));
283         pollLabel->setText(QApplication::translate("KbWidget", "N/A", Q_NULLPTR));
284         tabWidget->setTabText(tabWidget->indexOf(devTab), QApplication::translate("KbWidget", "Device", Q_NULLPTR));
285         hwSaveButton->setText(QApplication::translate("KbWidget", "Save to hardware", Q_NULLPTR));
286     } // retranslateUi
.fi
.SS "void Ui_KbWidget::setupUi (\fBQWidget\fP *KbWidget)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Definition at line 69 of file ui_kbwidget\&.h\&.
.PP
References Ui_KbWidget::bindTab, Ui_KbWidget::bindWidget, Ui_KbWidget::devTab, Ui_KbWidget::fwLabel, Ui_KbWidget::fwUpdButton, Ui_KbWidget::fwUpdLabel, Ui_KbWidget::fwUpdLayout, Ui_KbWidget::gridLayout, Ui_KbWidget::gridLayout_2, Ui_KbWidget::gridLayout_3, Ui_KbWidget::gridLayout_4, Ui_KbWidget::gridLayout_5, Ui_KbWidget::gridLayout_7, Ui_KbWidget::horizontalSpacer_2, Ui_KbWidget::horizontalSpacer_3, Ui_KbWidget::hwSaveButton, Ui_KbWidget::kPerfTab, Ui_KbWidget::kPerfWidget, Ui_KbWidget::label_3, Ui_KbWidget::label_4, Ui_KbWidget::label_9, Ui_KbWidget::lightTab, Ui_KbWidget::lightWidget, Ui_KbWidget::modesList, Ui_KbWidget::mPerfTab, Ui_KbWidget::mPerfWidget, Ui_KbWidget::pollLabel, Ui_KbWidget::pollLabel2, Ui_KbWidget::profileBox, Ui_KbWidget::retranslateUi(), Ui_KbWidget::serialLabel, Ui_KbWidget::tabWidget, and Ui_KbWidget::verticalSpacer\&.
.PP
Referenced by KbWidget::KbWidget()\&.
.PP
.nf
70     {
71         if (KbWidget->objectName()\&.isEmpty())
72             KbWidget->setObjectName(QStringLiteral("KbWidget"));
73         KbWidget->resize(773, 539);
74         gridLayout = new QGridLayout(KbWidget);
75         gridLayout->setSpacing(9);
76         gridLayout->setObjectName(QStringLiteral("gridLayout"));
77         gridLayout->setContentsMargins(9, -1, 9, 9);
78         profileBox = new QComboBox(KbWidget);
79         profileBox->setObjectName(QStringLiteral("profileBox"));
80         QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed);
81         sizePolicy\&.setHorizontalStretch(18);
82         sizePolicy\&.setVerticalStretch(0);
83         sizePolicy\&.setHeightForWidth(profileBox->sizePolicy()\&.hasHeightForWidth());
84         profileBox->setSizePolicy(sizePolicy);
85         profileBox->setIconSize(QSize(24, 24));
86 
87         gridLayout->addWidget(profileBox, 0, 0, 1, 1);
88 
89         tabWidget = new QTabWidget(KbWidget);
90         tabWidget->setObjectName(QStringLiteral("tabWidget"));
91         QSizePolicy sizePolicy1(QSizePolicy::Expanding, QSizePolicy::Expanding);
92         sizePolicy1\&.setHorizontalStretch(82);
93         sizePolicy1\&.setVerticalStretch(0);
94         sizePolicy1\&.setHeightForWidth(tabWidget->sizePolicy()\&.hasHeightForWidth());
95         tabWidget->setSizePolicy(sizePolicy1);
96         lightTab = new QWidget();
97         lightTab->setObjectName(QStringLiteral("lightTab"));
98         gridLayout_2 = new QGridLayout(lightTab);
99         gridLayout_2->setObjectName(QStringLiteral("gridLayout_2"));
100         gridLayout_2->setHorizontalSpacing(0);
101         gridLayout_2->setVerticalSpacing(6);
102         gridLayout_2->setContentsMargins(6, 6, 6, 6);
103         lightWidget = new KbLightWidget(lightTab);
104         lightWidget->setObjectName(QStringLiteral("lightWidget"));
105         QSizePolicy sizePolicy2(QSizePolicy::Preferred, QSizePolicy::Expanding);
106         sizePolicy2\&.setHorizontalStretch(0);
107         sizePolicy2\&.setVerticalStretch(0);
108         sizePolicy2\&.setHeightForWidth(lightWidget->sizePolicy()\&.hasHeightForWidth());
109         lightWidget->setSizePolicy(sizePolicy2);
110 
111         gridLayout_2->addWidget(lightWidget, 0, 0, 1, 1);
112 
113         label_3 = new QLabel(lightTab);
114         label_3->setObjectName(QStringLiteral("label_3"));
115         QSizePolicy sizePolicy3(QSizePolicy::Preferred, QSizePolicy::Minimum);
116         sizePolicy3\&.setHorizontalStretch(0);
117         sizePolicy3\&.setVerticalStretch(0);
118         sizePolicy3\&.setHeightForWidth(label_3->sizePolicy()\&.hasHeightForWidth());
119         label_3->setSizePolicy(sizePolicy3);
120 
121         gridLayout_2->addWidget(label_3, 1, 0, 1, 1);
122 
123         tabWidget->addTab(lightTab, QString());
124         bindTab = new QWidget();
125         bindTab->setObjectName(QStringLiteral("bindTab"));
126         gridLayout_5 = new QGridLayout(bindTab);
127         gridLayout_5->setSpacing(0);
128         gridLayout_5->setObjectName(QStringLiteral("gridLayout_5"));
129         gridLayout_5->setContentsMargins(6, 6, 6, 6);
130         bindWidget = new KbBindWidget(bindTab);
131         bindWidget->setObjectName(QStringLiteral("bindWidget"));
132         sizePolicy2\&.setHeightForWidth(bindWidget->sizePolicy()\&.hasHeightForWidth());
133         bindWidget->setSizePolicy(sizePolicy2);
134 
135         gridLayout_5->addWidget(bindWidget, 0, 0, 1, 1);
136 
137         tabWidget->addTab(bindTab, QString());
138         kPerfTab = new QWidget();
139         kPerfTab->setObjectName(QStringLiteral("kPerfTab"));
140         gridLayout_4 = new QGridLayout(kPerfTab);
141         gridLayout_4->setObjectName(QStringLiteral("gridLayout_4"));
142         gridLayout_4->setContentsMargins(6, 6, 6, 6);
143         kPerfWidget = new KPerfWidget(kPerfTab);
144         kPerfWidget->setObjectName(QStringLiteral("kPerfWidget"));
145 
146         gridLayout_4->addWidget(kPerfWidget, 0, 0, 1, 1);
147 
148         tabWidget->addTab(kPerfTab, QString());
149         mPerfTab = new QWidget();
150         mPerfTab->setObjectName(QStringLiteral("mPerfTab"));
151         gridLayout_7 = new QGridLayout(mPerfTab);
152         gridLayout_7->setObjectName(QStringLiteral("gridLayout_7"));
153         gridLayout_7->setContentsMargins(6, 6, 6, 6);
154         mPerfWidget = new MPerfWidget(mPerfTab);
155         mPerfWidget->setObjectName(QStringLiteral("mPerfWidget"));
156 
157         gridLayout_7->addWidget(mPerfWidget, 0, 0, 1, 1);
158 
159         tabWidget->addTab(mPerfTab, QString());
160         devTab = new QWidget();
161         devTab->setObjectName(QStringLiteral("devTab"));
162         gridLayout_3 = new QGridLayout(devTab);
163         gridLayout_3->setObjectName(QStringLiteral("gridLayout_3"));
164         gridLayout_3->setContentsMargins(6, 6, 6, 6);
165         fwUpdLabel = new QLabel(devTab);
166         fwUpdLabel->setObjectName(QStringLiteral("fwUpdLabel"));
167         fwUpdLabel->setMinimumSize(QSize(0, 34));
168 
169         gridLayout_3->addWidget(fwUpdLabel, 4, 0, 1, 1);
170 
171         verticalSpacer = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);
172 
173         gridLayout_3->addItem(verticalSpacer, 6, 2, 1, 1);
174 
175         fwLabel = new QLabel(devTab);
176         fwLabel->setObjectName(QStringLiteral("fwLabel"));
177         fwLabel->setCursor(QCursor(Qt::IBeamCursor));
178         fwLabel->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByMouse);
179 
180         gridLayout_3->addWidget(fwLabel, 2, 2, 1, 1);
181 
182         label_4 = new QLabel(devTab);
183         label_4->setObjectName(QStringLiteral("label_4"));
184         label_4->setMinimumSize(QSize(0, 34));
185 
186         gridLayout_3->addWidget(label_4, 0, 0, 1, 1);
187 
188         horizontalSpacer_2 = new QSpacerItem(40, 1, QSizePolicy::Fixed, QSizePolicy::Minimum);
189 
190         gridLayout_3->addItem(horizontalSpacer_2, 2, 1, 1, 1);
191 
192         label_9 = new QLabel(devTab);
193         label_9->setObjectName(QStringLiteral("label_9"));
194         label_9->setMinimumSize(QSize(0, 34));
195 
196         gridLayout_3->addWidget(label_9, 2, 0, 1, 1);
197 
198         serialLabel = new QLabel(devTab);
199         serialLabel->setObjectName(QStringLiteral("serialLabel"));
200         serialLabel->setCursor(QCursor(Qt::IBeamCursor));
201         serialLabel->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByMouse);
202 
203         gridLayout_3->addWidget(serialLabel, 0, 2, 1, 1);
204 
205         fwUpdLayout = new QHBoxLayout();
206         fwUpdLayout->setObjectName(QStringLiteral("fwUpdLayout"));
207         fwUpdButton = new QPushButton(devTab);
208         fwUpdButton->setObjectName(QStringLiteral("fwUpdButton"));
209 
210         fwUpdLayout->addWidget(fwUpdButton);
211 
212         horizontalSpacer_3 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
213 
214         fwUpdLayout->addItem(horizontalSpacer_3);
215 
216 
217         gridLayout_3->addLayout(fwUpdLayout, 4, 2, 1, 1);
218 
219         pollLabel2 = new QLabel(devTab);
220         pollLabel2->setObjectName(QStringLiteral("pollLabel2"));
221         pollLabel2->setMinimumSize(QSize(0, 34));
222 
223         gridLayout_3->addWidget(pollLabel2, 1, 0, 1, 1);
224 
225         pollLabel = new QLabel(devTab);
226         pollLabel->setObjectName(QStringLiteral("pollLabel"));
227 
228         gridLayout_3->addWidget(pollLabel, 1, 2, 1, 1);
229 
230         tabWidget->addTab(devTab, QString());
231 
232         gridLayout->addWidget(tabWidget, 0, 1, 3, 1);
233 
234         modesList = new RListWidget(KbWidget);
235         modesList->setObjectName(QStringLiteral("modesList"));
236         QSizePolicy sizePolicy4(QSizePolicy::Expanding, QSizePolicy::Expanding);
237         sizePolicy4\&.setHorizontalStretch(18);
238         sizePolicy4\&.setVerticalStretch(0);
239         sizePolicy4\&.setHeightForWidth(modesList->sizePolicy()\&.hasHeightForWidth());
240         modesList->setSizePolicy(sizePolicy4);
241         modesList->setContextMenuPolicy(Qt::CustomContextMenu);
242         modesList->setFrameShadow(QFrame::Plain);
243         modesList->setDragDropMode(QAbstractItemView::InternalMove);
244         modesList->setIconSize(QSize(24, 24));
245         modesList->setMovement(QListView::Snap);
246 
247         gridLayout->addWidget(modesList, 1, 0, 1, 1);
248 
249         hwSaveButton = new QPushButton(KbWidget);
250         hwSaveButton->setObjectName(QStringLiteral("hwSaveButton"));
251         QSizePolicy sizePolicy5(QSizePolicy::Minimum, QSizePolicy::Fixed);
252         sizePolicy5\&.setHorizontalStretch(18);
253         sizePolicy5\&.setVerticalStretch(0);
254         sizePolicy5\&.setHeightForWidth(hwSaveButton->sizePolicy()\&.hasHeightForWidth());
255         hwSaveButton->setSizePolicy(sizePolicy5);
256 
257         gridLayout->addWidget(hwSaveButton, 2, 0, 1, 1);
258 
259 
260         retranslateUi(KbWidget);
261 
262         tabWidget->setCurrentIndex(0);
263 
264 
265         QMetaObject::connectSlotsByName(KbWidget);
266     } // setupUi
.fi
.SH "Field Documentation"
.PP 
.SS "\fBQWidget\fP* Ui_KbWidget::bindTab\fC [inherited]\fP"

.PP
Definition at line 43 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBKbBindWidget\fP* Ui_KbWidget::bindWidget\fC [inherited]\fP"

.PP
Definition at line 45 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::modeChanged(), and Ui_KbWidget::setupUi()\&.
.SS "\fBQWidget\fP* Ui_KbWidget::devTab\fC [inherited]\fP"

.PP
Definition at line 52 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QLabel* Ui_KbWidget::fwLabel\fC [inherited]\fP"

.PP
Definition at line 56 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::devUpdate(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBQPushButton\fP* Ui_KbWidget::fwUpdButton\fC [inherited]\fP"

.PP
Definition at line 62 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), KbWidget::on_fwUpdButton_clicked(), Ui_KbWidget::retranslateUi(), Ui_KbWidget::setupUi(), and KbWidget::updateFwButton()\&.
.SS "QLabel* Ui_KbWidget::fwUpdLabel\fC [inherited]\fP"

.PP
Definition at line 54 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QHBoxLayout* Ui_KbWidget::fwUpdLayout\fC [inherited]\fP"

.PP
Definition at line 61 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), and Ui_KbWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbWidget::gridLayout\fC [inherited]\fP"

.PP
Definition at line 36 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbWidget::gridLayout_2\fC [inherited]\fP"

.PP
Definition at line 40 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbWidget::gridLayout_3\fC [inherited]\fP"

.PP
Definition at line 53 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbWidget::gridLayout_4\fC [inherited]\fP"

.PP
Definition at line 47 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbWidget::gridLayout_5\fC [inherited]\fP"

.PP
Definition at line 44 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbWidget::gridLayout_7\fC [inherited]\fP"

.PP
Definition at line 50 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QSpacerItem* Ui_KbWidget::horizontalSpacer_2\fC [inherited]\fP"

.PP
Definition at line 58 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "QSpacerItem* Ui_KbWidget::horizontalSpacer_3\fC [inherited]\fP"

.PP
Definition at line 63 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.
.SS "\fBQPushButton\fP* Ui_KbWidget::hwSaveButton\fC [inherited]\fP"

.PP
Definition at line 67 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBQWidget\fP* Ui_KbWidget::kPerfTab\fC [inherited]\fP"

.PP
Definition at line 46 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBKPerfWidget\fP* Ui_KbWidget::kPerfWidget\fC [inherited]\fP"

.PP
Definition at line 48 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::modeChanged(), and Ui_KbWidget::setupUi()\&.
.SS "QLabel* Ui_KbWidget::label_3\fC [inherited]\fP"

.PP
Definition at line 42 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QLabel* Ui_KbWidget::label_4\fC [inherited]\fP"

.PP
Definition at line 57 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QLabel* Ui_KbWidget::label_9\fC [inherited]\fP"

.PP
Definition at line 59 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBQWidget\fP* Ui_KbWidget::lightTab\fC [inherited]\fP"

.PP
Definition at line 39 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBKbLightWidget\fP* Ui_KbWidget::lightWidget\fC [inherited]\fP"

.PP
Definition at line 41 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), KbWidget::modeChanged(), and Ui_KbWidget::setupUi()\&.
.SS "\fBRListWidget\fP* Ui_KbWidget::modesList\fC [inherited]\fP"

.PP
Definition at line 66 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::addNewModeItem(), KbWidget::KbWidget(), KbWidget::modeChanged(), KbWidget::modesList_reordered(), KbWidget::on_modesList_customContextMenuRequested(), KbWidget::on_modesList_itemClicked(), KbWidget::profileChanged(), and Ui_KbWidget::setupUi()\&.
.SS "\fBQWidget\fP* Ui_KbWidget::mPerfTab\fC [inherited]\fP"

.PP
Definition at line 49 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "\fBMPerfWidget\fP* Ui_KbWidget::mPerfWidget\fC [inherited]\fP"

.PP
Definition at line 51 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::modeChanged(), and Ui_KbWidget::setupUi()\&.
.SS "QLabel* Ui_KbWidget::pollLabel\fC [inherited]\fP"

.PP
Definition at line 65 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::devUpdate(), KbWidget::KbWidget(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QLabel* Ui_KbWidget::pollLabel2\fC [inherited]\fP"

.PP
Definition at line 64 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QComboBox* Ui_KbWidget::profileBox\fC [inherited]\fP"

.PP
Definition at line 37 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi(), and KbWidget::updateProfileList()\&.
.SS "QLabel* Ui_KbWidget::serialLabel\fC [inherited]\fP"

.PP
Definition at line 60 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::devUpdate(), Ui_KbWidget::retranslateUi(), and Ui_KbWidget::setupUi()\&.
.SS "QTabWidget* Ui_KbWidget::tabWidget\fC [inherited]\fP"

.PP
Definition at line 38 of file ui_kbwidget\&.h\&.
.PP
Referenced by KbWidget::KbWidget(), KbWidget::on_tabWidget_currentChanged(), Ui_KbWidget::retranslateUi(), Ui_KbWidget::setupUi(), KbWidget::showFirstTab(), and KbWidget::showLastTab()\&.
.SS "QSpacerItem* Ui_KbWidget::verticalSpacer\fC [inherited]\fP"

.PP
Definition at line 55 of file ui_kbwidget\&.h\&.
.PP
Referenced by Ui_KbWidget::setupUi()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
