.TH "src/ckb/ui_layoutdialog.h" 3 "Tue May 16 2017" "Version beta-v0.2.7 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/ui_layoutdialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QComboBox>\fP
.br
\fC#include <QtWidgets/QDialog>\fP
.br
\fC#include <QtWidgets/QDialogButtonBox>\fP
.br
\fC#include <QtWidgets/QGridLayout>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QLabel>\fP
.br
\fC#include <QtWidgets/QSpacerItem>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUi_LayoutDialog\fP"
.br
.ti -1c
.RI "class \fBUi::LayoutDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
