.TH "src/ckb/ui_mainwindow.h" 3 "Sun Jun 18 2017" "Version beta-v0.2.8 at branch testing" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/ui_mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QGridLayout>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br
\fC#include <QtWidgets/QTabWidget>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.ti -1c
.RI "class \fBUi::MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
