UsbId
NAME
UsbId -
SYNOPSIS
#include <src/ckb/kbmode.h>
Public Member Functions
UsbId (const QString &_guid, quint32 _modified)
UsbId (const QString &_guid, const QString &_modified)
UsbId ()
QString guidString () const
void guidString (const QString &newGuid)
QString modifiedString () const
void modifiedString (const QString &newModified)
QString hwModifiedString () const
void hwModifiedString (const QString &newModified)
void newGuid ()
void newModified ()
Data Fields
QUuid guid
quint32 modified
quint32 hwModified
Detailed Description
Definition at line 11 of file kbmode.h.
Constructor & Destructor Documentation
UsbId::UsbId (const QString &_guid, quint32_modified) [inline]
Definition at line 16 of file kbmode.h.
: guid(_guid), modified(_modified), hwModified(_modified) {}
UsbId::UsbId (const QString &_guid, const QString &_modified) [inline]
Definition at line 17 of file kbmode.h.
: guid(_guid), modified(_modified.toUInt(0, 16)), hwModified(modified) {}
UsbId::UsbId () [inline]
Definition at line 18 of file kbmode.h.
: guid(QUuid::createUuid()),modified(0) {}
Member Function Documentation
QString UsbId::guidString () const [inline]
Definition at line 20 of file kbmode.h.
References guid.
Referenced by Kb::hwSave(), KbProfile::save(), KbMode::save(), Kb::save(), and Kb::writeProfileHeader().
{ return guid.toString().toUpper(); }
void UsbId::guidString (const QString &newGuid) [inline]
Definition at line 21 of file kbmode.h.
References guid, and newGuid().
{ guid = newGuid; }
QString UsbId::hwModifiedString () const [inline]
Definition at line 24 of file kbmode.h.
References hwModified.
Referenced by KbMode::KbMode(), KbProfile::KbProfile(), Kb::readNotify(), KbProfile::save(), and KbMode::save().
{ return QString::number(hwModified, 16); }
void UsbId::hwModifiedString (const QString &newModified) [inline]
Definition at line 25 of file kbmode.h.
References hwModified.
{ hwModified = newModified.toUInt(0, 16); }
QString UsbId::modifiedString () const [inline]
Definition at line 22 of file kbmode.h.
References modified.
Referenced by Kb::hwSave(), KbProfile::KbProfile(), Kb::readNotify(), KbProfile::save(), KbMode::save(), and Kb::writeProfileHeader().
{ return QString::number(modified, 16); }
void UsbId::modifiedString (const QString &newModified) [inline]
Definition at line 23 of file kbmode.h.
References modified.
{ modified = newModified.toUInt(0, 16); }
void UsbId::newGuid () [inline]
Definition at line 28 of file kbmode.h.
References guid.
Referenced by guidString().
{ guid = QUuid::createUuid(); }
void UsbId::newModified () [inline]
Definition at line 29 of file kbmode.h.
References modified.
Referenced by KbProfile::save(), and KbMode::save().
{ quint32 newMod; do { newMod = qrand(); } while(newMod == modified); modified = newMod; }
Field Documentation
QUuid UsbId::guid
Definition at line 12 of file kbmode.h.
Referenced by KbProfile::find(), Kb::find(), guidString(), KbMode::KbMode(), KbProfile::KbProfile(), newGuid(), KbWidget::on_modesList_customContextMenuRequested(), KbWidget::on_modesList_itemChanged(), KbWidget::on_modesList_itemClicked(), KbProfileDialog::on_profileList_customContextMenuRequested(), KbProfileDialog::on_profileList_itemChanged(), KbProfileDialog::on_profileList_itemClicked(), KbWidget::profileChanged(), Kb::readNotify(), and KbProfileDialog::repopulate().
quint32 UsbId::hwModified
Definition at line 14 of file kbmode.h.
Referenced by hwModifiedString(), Kb::hwSave(), KbMode::KbMode(), and KbProfile::KbProfile().
quint32 UsbId::modified
Definition at line 13 of file kbmode.h.
Referenced by Kb::hwSave(), KbMode::KbMode(), KbProfile::KbProfile(), modifiedString(), and newModified().
Author
Generated automatically by Doxygen for ckb-next from the source code.