AnimScript
NAME
AnimScript -
SYNOPSIS
#include <src/ckb/animscript.h>
Inherits QObject.
Data Structures
struct Param
Public Types
typedef QMap< QString, QVariant > PresetValue
Public Member Functions
const QUuid & guid () const
const QString & name () const
const QString & version () const
QString copyright () const
const QString & year () const
const QString & author () const
const QString & license () const
const QString & description () const
bool hasKeypress () const
const QStringList & presets () const
const PresetValue & preset (int index) const
QListIterator< Param > paramIterator () const
Param param (const QString &name) const
bool hasParam (const QString &name) const
void init (const KeyMap &map, const QStringList &keys, const QMap< QString, QVariant > &paramValues)
void parameters (const QMap< QString, QVariant > &paramValues)
void retrigger (quint64 timestamp, bool allowPreempt=false)
void stop (quint64 timestamp)
void keypress (const QString &key, bool pressed, quint64 timestamp)
void frame (quint64 timestamp)
void end ()
bool hasFrame () const
const ColorMap & colors () const
~AnimScript ()
Static Public Member Functions
static QString path ()
static void scan ()
static int count ()
static QList< const AnimScript * > list ()
static AnimScript * copy (QObject *parent, const QUuid &id)
Private Slots
void readProcess ()
Private Member Functions
bool load ()
void setDuration ()
void printParams ()
void begin (quint64 timestamp)
void advance (quint64 timestamp)
AnimScript (QObject *parent, const QString &path)
AnimScript (QObject *parent, const AnimScript &base)
Private Attributes
struct {
QUuid guid
QString name
QString version
QString year
QString author
QString license
QString description
QList< Param > params
int kpMode:3
bool absoluteTime:1
bool repeat:1
bool preempt:1
bool liveParams:1
} _info
QStringList _presets
QList< PresetValue > _presetValues
QString _path
KeyMap _map
int minX
int minY
QStringList _keys
ColorMap _colors
PresetValue _paramValues
quint64 lastFrame
int durationMsec
int repeatMsec
bool initialized:1
bool firstFrame:1
bool readFrame:1
bool readAnyFrame:1
bool stopped:1
bool inFrame:1
QProcess * process
ColorMap _colorBuffer
Static Private Attributes
static const int KP_NONE = 0
static const int KP_NAME = 1
static const int KP_POSITION = 2
static QHash< QUuid, AnimScript * > scripts
Detailed Description
Definition at line 16 of file animscript.h.
Data Structure Documentation
struct AnimScript::Param
Definition at line 21 of file animscript.h.
Data Fields:
 Type
Data Fields:
QVariant defaultValue
QVariant maximum
QVariant minimum
QString name
QString postfix
QString prefix
Type type
Member Typedef Documentation
typedef QMap<QString, QVariant> AnimScript::PresetValue
Definition at line 58 of file animscript.h.
Constructor & Destructor Documentation
AnimScript::~AnimScript ()
Definition at line 21 of file animscript.cpp.
References process.
                       {
    if(process){
        process->kill();
        process->waitForFinished(1000);
        delete process;
    }
}
AnimScript::AnimScript (QObject *parent, const QString &path) [private]
Definition at line 11 of file animscript.cpp.
Referenced by copy(), and scan().
                                                           :
    QObject(parent), _path(path), initialized(false), process(0)
{
}
AnimScript::AnimScript (QObject *parent, const AnimScript &base) [private]
Definition at line 16 of file animscript.cpp.
                                                              :
    QObject(parent), _info(base._info), _path(base._path), initialized(false), process(0)
{
}
Member Function Documentation
void AnimScript::advance (quint64timestamp) [private]
Definition at line 445 of file animscript.cpp.
References _info, durationMsec, lastFrame, and process.
Referenced by frame(), keypress(), retrigger(), and stop().
                                         {
    if(timestamp <= lastFrame || !process)
        // Don't do anything if the time hasn't actually advanced.
        return;
    double delta = (timestamp - lastFrame) / (double)durationMsec;
    if(!_info.absoluteTime){
        // Skip any complete durations
        while(delta > 1.){
            process->write("time 1\n");
            delta--;
        }
    }
    process->write(QString("time %1\n").arg(delta).toLatin1());
    lastFrame = timestamp;
}
const QString& AnimScript::author () const [inline]
Definition at line 64 of file animscript.h.
References _info.
Referenced by AnimSettingDialog::AnimSettingDialog().
{ return _info.author; }
void AnimScript::begin (quint64timestamp) [private]
Definition at line 287 of file animscript.cpp.
References _keys, _map, _path, end(), firstFrame, inFrame, initialized, KeyMap::key(), lastFrame, minX, minY, printParams(), process, readAnyFrame, readFrame, readProcess(), stopped, Key::x, and Key::y.
Referenced by frame(), keypress(), retrigger(), and stop().
                                       {
    if(!initialized)
        return;
    end();
    stopped = firstFrame = readFrame = readAnyFrame = inFrame = false;
    // Determine the upper left corner of the given keys
    QStringList keysCopy = _keys;
    minX = INT_MAX;
    minY = INT_MAX;
    foreach(const QString& key, keysCopy){
        const Key& pos = _map.key(key);
        if(!pos){
            keysCopy.removeAll(key);
            continue;
        }
        if(pos.x < minX)
            minX = pos.x;
        if(pos.y < minY)
            minY = pos.y;
    }
    if(keysCopy.isEmpty()){
        // If the key list is empty, don't actually start the animation but pretend it's running anyway
        firstFrame = readFrame = readAnyFrame = true;
        return;
    }
    process = new QProcess(this);
    connect(process, SIGNAL(readyRead()), this, SLOT(readProcess()));
    process->start(_path, QStringList("--ckb-run"));
    qDebug() << "Starting " << _path;
    // Write the keymap to the process
    process->write("begin keymap\n");
    process->write(QString("keycount %1\n").arg(keysCopy.count()).toLatin1());
    foreach(const QString& key, keysCopy){
        const Key& pos = _map.key(key);
        process->write(QString("key %1 %2,%3\n").arg(key).arg(pos.x - minX).arg(pos.y - minY).toLatin1());
    }
    process->write("end keymap\n");
    // Write parameters
    printParams();
    // Begin animating
    process->write("begin run\n");
    lastFrame = timestamp;
}
const ColorMap& AnimScript::colors () const [inline]
Definition at line 99 of file animscript.h.
References _colors.
Referenced by KbAnim::blend().
{ return _colors; }
AnimScript * AnimScript::copy (QObject *parent, const QUuid &id) [static]
Definition at line 67 of file animscript.cpp.
References AnimScript(), and scripts.
Referenced by KbAnim::KbAnim().
                                                            {
     return scripts.contains(id) ? new AnimScript(parent, *scripts.value(id)) : 0;
}
QString AnimScript::copyright () const [inline]
Definition at line 62 of file animscript.h.
References _info.
Referenced by KbAnimWidget::setCurrent().
{ return "Copyright © " + _info.year + " " + _info.author; }
static int AnimScript::count () [inline], [static]
Definition at line 54 of file animscript.h.
References scripts.
Referenced by KbLightWidget::KbLightWidget(), load(), KbLightWidget::on_animButton_clicked(), and ExtraSettingsWidget::on_animScanButton_clicked().
{ return scripts.count(); }
const QString& AnimScript::description () const [inline]
Definition at line 66 of file animscript.h.
References _info.
Referenced by AnimSettingDialog::AnimSettingDialog().
{ return _info.description; }
void AnimScript::end ()
Definition at line 387 of file animscript.cpp.
References _colors, ColorMap::clear(), process, and readProcess().
Referenced by begin(), KbAnim::catchUp(), init(), and KbAnim::stop().
                    {
    _colors.clear();
    if(process){
        process->kill();
        connect(process, SIGNAL(finished(int)), process, SLOT(deleteLater()));
        disconnect(process, SIGNAL(readyRead()), this, SLOT(readProcess()));
        process = 0;
    }
}
void AnimScript::frame (quint64timestamp)
Definition at line 430 of file animscript.cpp.
References advance(), begin(), firstFrame, initialized, process, readFrame, and stopped.
Referenced by KbAnim::blend(), KbAnim::keypress(), and KbAnim::trigger().
                                       {
    if(!initialized || stopped)
        return;
    // Start the animation if it's not running yet
    if(!process)
        begin(timestamp);
    advance(timestamp);
    if((readFrame || !firstFrame) && process)
        // Don't ask for a new frame if the animation hasn't delivered the last one yet
        process->write("frame\n");
    firstFrame = true;
    readFrame = false;
}
const QUuid& AnimScript::guid () const [inline]
Definition at line 59 of file animscript.h.
References _info.
Referenced by KbAnim::KbAnim(), list(), and scan().
{ return _info.guid; }
bool AnimScript::hasFrame () const [inline]
Definition at line 96 of file animscript.h.
References initialized, and readAnyFrame.
Referenced by KbAnim::isRunning().
{ return initialized && readAnyFrame; }
bool AnimScript::hasKeypress () const [inline]
Definition at line 67 of file animscript.h.
References _info, and KP_NONE.
Referenced by AnimSettingDialog::AnimSettingDialog(), and AnimSettingDialog::updateParam().
{ return _info.kpMode != KP_NONE; }
bool AnimScript::hasParam (const QString &name) const [inline]
Definition at line 74 of file animscript.h.
References _info, and name().
Referenced by AnimSettingDialog::AnimSettingDialog(), load(), and KbAnim::parameter().
{ QListIterator<Param> i(_info.params); while(i.hasNext()){ if(i.next().name == name) return true; } return false; }
void AnimScript::init (const KeyMap &map, const QStringList &keys, const QMap< QString, QVariant > &paramValues)
Definition at line 239 of file animscript.cpp.
References _colorBuffer, _colors, _keys, _map, _paramValues, _path, end(), firstFrame, ColorMap::init(), initialized, setDuration(), and stopped.
Referenced by KbAnim::reInit().
                                                                                                           {
    if(_path == "")
        return;
    end();
    _map = map;
    _colors.init(map);
    _colorBuffer.init(map);
    _keys = keys;
    _paramValues = paramValues;
    setDuration();
    stopped = firstFrame = false;
    initialized = true;
}
void AnimScript::keypress (const QString &key, boolpressed, quint64timestamp)
Definition at line 354 of file animscript.cpp.
References _info, _map, _paramValues, advance(), begin(), initialized, KeyMap::key(), KP_NAME, KP_NONE, KP_POSITION, minX, minY, process, retrigger(), stop(), Key::x, and Key::y.
Referenced by KbAnim::catchUp(), and KbAnim::keypress().
                                                                            {
    if(!initialized)
        return;
    if(!process)
        begin(timestamp);
    int kpMode = _info.kpMode;
    if(_paramValues.value("kpmode", 0).toInt() != 0)
        // Disable KP mode according to user preferences
        kpMode = KP_NONE;
    switch(kpMode){
    case KP_NONE:
        // If KPs aren't allowed, call retrigger/stop instead
        if(pressed)
            retrigger(timestamp);
        else if(_paramValues.value("kprelease", false).toBool())
            stop(timestamp);
        break;
    case KP_NAME:
        // Print keypress by name
        advance(timestamp);
        process->write(("key " + key + (pressed ? " down\n" : " up\n")).toLatin1());
        break;
    case KP_POSITION:
        // Print keypress by position
        const Key& kp = _map.key(key);
        if(!kp)
            return;
        advance(timestamp);
        process->write(("key " + QString("%1,%2").arg(kp.x - minX).arg(kp.y - minY) + (pressed ? " down\n" : " up\n")).toLatin1());
        break;
    }
}
const QString& AnimScript::license () const [inline]
Definition at line 65 of file animscript.h.
References _info.
Referenced by AnimSettingDialog::AnimSettingDialog().
{ return _info.license; }
QList< const AnimScript * > AnimScript::list () [static]
Definition at line 51 of file animscript.cpp.
References _info, guid(), name(), and scripts.
Referenced by AnimAddDialog::AnimAddDialog().
                                         {
    // Gather the animations into an alphabetically-sorted list
    QMap<QString, const AnimScript*> result;
    foreach(AnimScript* script, scripts.values()){
        QString name = script->name();
        if(result.contains(name)){
            // If duplicate names exist, make them unique by including their GUIDs
            AnimScript* last = (AnimScript*)result[name];
            last->_info.name += " " + last->guid().toString().toUpper();
            script->_info.name += " " + script->guid().toString().toUpper();
        }
        result[script->name()] = script;
    }
    return result.values();
}
bool AnimScript::load () [private]
Definition at line 77 of file animscript.cpp.
References _info, _path, _presets, _presetValues, AnimScript::Param::AGRADIENT, AnimScript::Param::ANGLE, AnimScript::Param::ARGB, AnimScript::Param::BOOL, count(), AnimScript::Param::defaultValue, AnimScript::Param::DOUBLE, AnimScript::Param::GRADIENT, hasParam(), AnimScript::Param::INVALID, KP_NAME, KP_NONE, KP_POSITION, kprelease, AnimScript::Param::LABEL, AnimScript::Param::LONG, name(), ONE_DAY, param(), preset(), AnimScript::Param::RGB, stop(), AnimScript::Param::STRING, and urlParam().
Referenced by scan().
                     {
    // Run the process to get script info
    QProcess infoProcess;
    infoProcess.start(_path, QStringList("--ckb-info"));
    qDebug() << "Scanning " << _path;
    infoProcess.waitForFinished(1000);
    if(infoProcess.state() == QProcess::Running){
        // Kill the process if it takes more than 1s
        infoProcess.kill();
        return false;
    }
    // Set defaults for performance info
    _info.kpMode = KP_NONE;
    _info.absoluteTime = _info.preempt = _info.liveParams = false;
    _info.repeat = true;
    // Read output
    QString line;
    while((line = infoProcess.readLine()) != ""){
        line = line.trimmed();
        QStringList components = line.split(" ");
        int count = components.count();
        if(count < 2)
            continue;
        QString param = components[0].trimmed();
        if(param == "guid")
            _info.guid = QUuid(urlParam(components[1]));
        else if(param == "name")
            _info.name = urlParam(components[1]);
        else if(param == "version")
            _info.version = urlParam(components[1]);
        else if(param == "year")
            _info.year = urlParam(components[1]);
        else if(param == "author")
            _info.author = urlParam(components[1]);
        else if(param == "license")
            _info.license = urlParam(components[1]);
        else if(param == "description")
            _info.description = urlParam(components[1]);
        else if(param == "kpmode")
            _info.kpMode = (components[1] == "position") ? KP_POSITION : (components[1] == "name") ? KP_NAME : KP_NONE;
        else if(param == "time")
            _info.absoluteTime = (components[1] == "absolute");
        else if(param == "repeat")
            _info.repeat = (components[1] == "on");
        else if(param == "preempt")
            _info.preempt = (components[1] == "on");
        else if(param == "parammode")
            _info.liveParams = (components[1] == "live");
        else if(param == "param"){
            // Read parameter
            if(count < 3)
                continue;
            while(components.count() < 8)
                components.append("");
            Param::Type type = Param::INVALID;
            QString sType = components[1].toLower();
            if(sType == "long")
                type = Param::LONG;
            else if(sType == "double")
                type = Param::DOUBLE;
            else if(sType == "bool")
                type = Param::BOOL;
            else if(sType == "rgb")
                type = Param::RGB;
            else if(sType == "argb")
                type = Param::ARGB;
            else if(sType == "gradient")
                type = Param::GRADIENT;
            else if(sType == "agradient")
                type = Param::AGRADIENT;
            else if(sType == "angle")
                type = Param::ANGLE;
            else if(sType == "string")
                type = Param::STRING;
            else if(sType == "label")
                type = Param::LABEL;
            else
                continue;
            // "param <type> <name> <prefix> <postfix> <default>"
            QString name = components[2].toLower();
            // Make sure it's not present already
            if(hasParam(name))
                continue;
            QString prefix = urlParam(components[3]), postfix = urlParam(components[4]);
            QVariant def = urlParam(components[5]), minimum = urlParam(components[6]), maximum = urlParam(components[7]);
            // Don't allow predefined params
            if(name == "trigger" || name == "kptrigger" || name == "kpmode" || name == "duration" || name == "delay" || name == "kpdelay" || name == "repeat" || name == "kprepeat" || name == "stop" || name == "kpstop" || name == "kpmodestop" || name == "kprelease")
                continue;
            Param param = { type, name, prefix, postfix, def, minimum, maximum };
            _info.params.append(param);
        } else if(param == "preset"){
            // Add preset
            QString name = urlParam(components.at(1));
            QMap<QString, QVariant> preset;
            for(int i = 2; i < count; i++){
                // Scan name/value setting pairs
                QString setting = components.at(i);
                QStringList sComponents = setting.split("=");
                if(sComponents.count() != 2)
                    continue;
                QString param = sComponents.first().trimmed();
                QString value = urlParam(sComponents.last());
                preset[param] = value;
            }
            // If the preset contains a duration, set the repeat time to the same value
            if(preset.contains("duration")){
                QVariant duration = preset.value("duration");
                preset["repeat"] = duration;
                preset["kprepeat"] = duration;
            }
            _presets.append(name);
            _presetValues.append(preset);
        }
    }
    // Make sure the required parameters are filled out
    if(_info.guid.isNull() || _info.name == "" || _info.version == "" || _info.year == "" || _info.author == "" || _info.license == "")
        return false;
    // Add timing parameters
    double defaultDuration = -1.;
    if(!_info.absoluteTime){
        defaultDuration = 1.;
        Param duration = { Param::DOUBLE, "duration", "", "", defaultDuration, 0.1, ONE_DAY };
        _info.params.append(duration);
    }
    Param trigger = { Param::BOOL, "trigger", "", "", true, 0, 0 };
    _info.params.append(trigger);
    Param kptrigger = { Param::BOOL, "kptrigger", "", "", false, 0, 0 };
    _info.params.append(kptrigger);
    if(_info.absoluteTime || !_info.repeat)
        _info.preempt = false;
    Param kpmode = { Param::LONG, "kpmode", "", "", 1, 0, 0 };
    if(_info.kpMode)
        kpmode.defaultValue = 0;
    _info.params.append(kpmode);
    Param delay = { Param::DOUBLE, "delay", "", "", 0., 0., ONE_DAY };
    Param kpdelay = { Param::DOUBLE, "kpdelay", "", "", 0., 0., ONE_DAY };
    _info.params.append(delay);
    _info.params.append(kpdelay);
    Param kpmodestop = { Param::BOOL, "kpmodestop", "", "", false, 0, 0 };
    Param kprelease = { Param::BOOL, "kprelease", "", "", false, 0, 0 };
    _info.params.append(kpmodestop);
    _info.params.append(kprelease);
    if(_info.repeat){
        Param repeat = { Param::DOUBLE, "repeat", "", "", defaultDuration, 0.1, ONE_DAY };
        Param kprepeat = { Param::DOUBLE, "kprepeat", "", "", defaultDuration, 0.1, ONE_DAY };
        // When repeats are enabled, stop and kpstop are LONG values (number of repeats)
        Param stop = { Param::LONG, "stop", "", "", -1, 0, 1000 };
        Param kpstop = { Param::LONG, "kpstop", "", "", 0, 0, 1000 };
        _info.params.append(repeat);
        _info.params.append(kprepeat);
        _info.params.append(stop);
        _info.params.append(kpstop);
    } else {
        // When repeats are disabled, stop and kpstop are DOUBLE values (seconds)
        Param stop = { Param::DOUBLE, "stop", "", "", -1., 0.1, ONE_DAY };
        Param kpstop = { Param::DOUBLE, "kpstop", "", "", -1., 0.1, ONE_DAY };
        _info.params.append(stop);
        _info.params.append(kpstop);
    }
    return true;
}
const QString& AnimScript::name () const [inline]
Definition at line 60 of file animscript.h.
References _info.
Referenced by AnimAddDialog::AnimAddDialog(), AnimSettingDialog::AnimSettingDialog(), hasParam(), KbAnim::KbAnim(), list(), load(), and KbAnimWidget::setCurrent().
{ return _info.name; }
Param AnimScript::param (const QString &name) const [inline]
Definition at line 73 of file animscript.h.
References _info, AnimScript::Param::INVALID, and AnimScript::Param::name.
Referenced by KbAnim::KbAnim(), load(), and AnimSettingDialog::updateParam().
{ QListIterator<Param> i(_info.params); while(i.hasNext()){ Param p = i.next(); if(p.name == name) return p; } return ((Param[]){ { Param::INVALID, "", "", "", 0, 0, 0 } })[0]; }
void AnimScript::parameters (const QMap< QString, QVariant > &paramValues)
Definition at line 265 of file animscript.cpp.
References _info, _paramValues, initialized, printParams(), process, and setDuration().
Referenced by KbAnim::updateParams().
                                                                     {
    if(!initialized || !process || !_info.liveParams)
        return;
    _paramValues = paramValues;
    setDuration();
    printParams();
}
QListIterator<Param> AnimScript::paramIterator () const [inline]
Definition at line 72 of file animscript.h.
References _info.
Referenced by AnimSettingDialog::AnimSettingDialog(), and KbAnim::KbAnim().
{ return _info.params; }
QString AnimScript::path () [static]
Definition at line 29 of file animscript.cpp.
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), and scan().
                        {
#ifdef __APPLE__
    return QDir(QApplication::applicationDirPath() + "/../Resources").absoluteFilePath("ckb-animations");
#else
    return QDir("/usr/lib").absoluteFilePath("ckb-animations");
#endif
}
const PresetValue& AnimScript::preset (intindex) const [inline]
Definition at line 69 of file animscript.h.
References _presetValues.
Referenced by load(), and KbLightWidget::on_animButton_clicked().
{ return _presetValues[index]; }
const QStringList& AnimScript::presets () const [inline]
Definition at line 68 of file animscript.h.
References _presets.
Referenced by KbLightWidget::on_animButton_clicked().
{ return _presets; }
void AnimScript::printParams () [private]
Definition at line 273 of file animscript.cpp.
References _paramValues, and process.
Referenced by begin(), and parameters().
                            {
    process->write("begin params\n");
    QMapIterator<QString, QVariant> i(_paramValues);
    while(i.hasNext()){
        i.next();
        process->write("param ");
        process->write(i.key().toLatin1());
        process->write(" ");
        process->write(QUrl::toPercentEncoding(i.value().toString()));
        process->write("\n");
    }
    process->write("end params\n");
}
void AnimScript::readProcess () [private], [slot]
Definition at line 397 of file animscript.cpp.
References _colorBuffer, _colors, ColorMap::colorForName(), ColorMap::colors(), ColorMap::count(), inFrame, process, readAnyFrame, readFrame, and stopped.
Referenced by begin(), and end().
                            {
    while(process->canReadLine()){
        QByteArray line = process->readLine().trimmed();
        if(!inFrame){
            // Ignore anything not between "begin frame" and "end frame", except for "end run", which indicates that the program is done.
            if(line == "begin frame")
                inFrame = true;
            else if(line == "end run"){
                stopped = true;
                return;
            }
            continue;
        }
        if(line.startsWith("argb ")){
            // Add a color to the buffer
            char keyName[31];
            QRgb keyColor = 0;
            if(sscanf(line, "argb %30s %x", keyName, &keyColor) != 2)
                continue;
            QRgb* inMap = _colorBuffer.colorForName(keyName);
            if(!inMap)
                continue;
            *inMap = keyColor;
        }
        if(line == "end frame"){
            // Frame is finished. Copy color buffer back to the atomic map
            memcpy(_colors.colors(), _colorBuffer.colors(), sizeof(QRgb) * _colors.count());
            inFrame = false;
            readFrame = readAnyFrame = true;
        }
    }
}
void AnimScript::retrigger (quint64timestamp, boolallowPreempt = false)
Definition at line 331 of file animscript.cpp.
References _info, advance(), begin(), initialized, process, and repeatMsec.
Referenced by KbAnim::catchUp(), keypress(), and KbAnim::trigger().
                                                              {
    if(!initialized)
        return;
    if(allowPreempt && _info.preempt && repeatMsec > 0)
        // If preemption is wanted, trigger the animation 1 duration in the past first
        retrigger(timestamp - repeatMsec);
    if(!process)
        begin(timestamp);
    advance(timestamp);
    if(process)
        process->write("start\n");
}
void AnimScript::scan () [static]
Definition at line 37 of file animscript.cpp.
References _info, AnimScript(), guid(), load(), path(), and scripts.
Referenced by ExtraSettingsWidget::on_animScanButton_clicked().
                     {
    QDir dir(path());
    foreach(AnimScript* script, scripts)
        delete script;
    scripts.clear();
    foreach(QString file, dir.entryList(QDir::Files | QDir::Executable)){
        AnimScript* script = new AnimScript(qApp, dir.absoluteFilePath(file));
        if(script->load() && !scripts.contains(script->_info.guid))
            scripts[script->_info.guid] = script;
        else
            delete script;
    }
}
void AnimScript::setDuration () [private]
Definition at line 253 of file animscript.cpp.
References _info, _paramValues, durationMsec, and repeatMsec.
Referenced by init(), and parameters().
                            {
    if(_info.absoluteTime){
        durationMsec = 1000;
        repeatMsec = 0;
    } else {
        durationMsec = round(_paramValues.value("duration").toDouble() * 1000.);
        if(durationMsec <= 0)
            durationMsec = -1;
        repeatMsec = round(_paramValues.value("repeat").toDouble() * 1000.);
    }
}
void AnimScript::stop (quint64timestamp)
Definition at line 344 of file animscript.cpp.
References advance(), begin(), initialized, and process.
Referenced by KbAnim::keypress(), keypress(), and load().
                                      {
    if(!initialized)
        return;
    if(!process)
        begin(timestamp);
    advance(timestamp);
    if(process)
        process->write("stop\n");
}
const QString& AnimScript::version () const [inline]
Definition at line 61 of file animscript.h.
References _info.
Referenced by AnimSettingDialog::AnimSettingDialog(), and KbAnimWidget::setCurrent().
{ return _info.version; }
const QString& AnimScript::year () const [inline]
Definition at line 63 of file animscript.h.
References _info.
Referenced by AnimSettingDialog::AnimSettingDialog().
{ return _info.year; }
Field Documentation
ColorMap AnimScript::_colorBuffer [private]
Definition at line 143 of file animscript.h.
Referenced by init(), and readProcess().
ColorMap AnimScript::_colors [private]
Definition at line 135 of file animscript.h.
Referenced by colors(), end(), init(), and readProcess().
struct { ... } AnimScript::_info [private]
Referenced by advance(), author(), copyright(), description(), guid(), hasKeypress(), hasParam(), keypress(), license(), list(), load(), name(), param(), parameters(), paramIterator(), retrigger(), scan(), setDuration(), version(), and year().
QStringList AnimScript::_keys [private]
Definition at line 133 of file animscript.h.
Referenced by begin(), and init().
KeyMap AnimScript::_map [private]
Definition at line 130 of file animscript.h.
Referenced by begin(), init(), and keypress().
PresetValue AnimScript::_paramValues [private]
Definition at line 136 of file animscript.h.
Referenced by init(), keypress(), parameters(), printParams(), and setDuration().
QString AnimScript::_path [private]
Definition at line 128 of file animscript.h.
Referenced by begin(), init(), and load().
QStringList AnimScript::_presets [private]
Definition at line 125 of file animscript.h.
Referenced by load(), and presets().
QList<PresetValue> AnimScript::_presetValues [private]
Definition at line 126 of file animscript.h.
Referenced by load(), and preset().
int AnimScript::durationMsec [private]
Definition at line 140 of file animscript.h.
Referenced by advance(), and setDuration().
bool AnimScript::firstFrame [private]
Definition at line 141 of file animscript.h.
Referenced by begin(), frame(), and init().
bool AnimScript::inFrame [private]
Definition at line 141 of file animscript.h.
Referenced by begin(), and readProcess().
bool AnimScript::initialized [private]
Definition at line 141 of file animscript.h.
Referenced by begin(), frame(), hasFrame(), init(), keypress(), parameters(), retrigger(), and stop().
const int AnimScript::KP_NAME = 1 [static], [private]
Definition at line 124 of file animscript.h.
Referenced by keypress(), and load().
const int AnimScript::KP_NONE = 0 [static], [private]
Definition at line 124 of file animscript.h.
Referenced by hasKeypress(), keypress(), and load().
const int AnimScript::KP_POSITION = 2 [static], [private]
Definition at line 124 of file animscript.h.
Referenced by keypress(), and load().
quint64 AnimScript::lastFrame [private]
Definition at line 139 of file animscript.h.
Referenced by advance(), and begin().
int AnimScript::minX [private]
Definition at line 131 of file animscript.h.
Referenced by begin(), and keypress().
int AnimScript::minY [private]
Definition at line 131 of file animscript.h.
Referenced by begin(), and keypress().
QProcess* AnimScript::process [private]
Definition at line 142 of file animscript.h.
Referenced by advance(), begin(), end(), frame(), keypress(), parameters(), printParams(), readProcess(), retrigger(), stop(), and ~AnimScript().
bool AnimScript::readAnyFrame [private]
Definition at line 141 of file animscript.h.
Referenced by begin(), hasFrame(), and readProcess().
bool AnimScript::readFrame [private]
Definition at line 141 of file animscript.h.
Referenced by begin(), frame(), and readProcess().
int AnimScript::repeatMsec [private]
Definition at line 140 of file animscript.h.
Referenced by retrigger(), and setDuration().
QHash< QUuid, AnimScript * > AnimScript::scripts [static], [private]
Definition at line 152 of file animscript.h.
Referenced by copy(), count(), list(), and scan().
bool AnimScript::stopped [private]
Definition at line 141 of file animscript.h.
Referenced by begin(), frame(), init(), and readProcess().
Author
Generated automatically by Doxygen for ckb-next from the source code.