AutoRun
NAME
AutoRun -
SYNOPSIS
#include <src/ckb/autorun.h>
Static Public Member Functions
static bool available ()
static bool once ()
static bool isEnabled ()
static void enable ()
static void disable ()
Detailed Description
Definition at line 8 of file autorun.h.
Member Function Documentation
bool AutoRun::available () [static]
Definition at line 20 of file autorun.cpp.
Referenced by disable(), enable(), and SettingsWidget::SettingsWidget().
                       {
    // Allow autostart if the program is located in a system path
#ifdef Q_OS_LINUX
    return QDir::root().absoluteFilePath(QStandardPaths::findExecutable("ckb")) == qApp->applicationFilePath();
#elif defined(Q_OS_MACX)
    return qApp->applicationFilePath().startsWith("/Applications/ckb.app", Qt::CaseInsensitive);
#endif
}
void AutoRun::disable () [static]
Definition at line 53 of file autorun.cpp.
References available().
Referenced by SettingsWidget::on_loginItemBox_clicked().
                     {
    if(!available())
        return;
    // Remove file
    QFile::remove(path.absoluteFilePath(file));
}
void AutoRun::enable () [static]
Definition at line 42 of file autorun.cpp.
References available(), and CkbSettings::set().
Referenced by SettingsWidget::on_loginItemBox_clicked(), and SettingsWidget::SettingsWidget().
                    {
    if(!available())
        return;
    // Copy file into place
    if(!path.exists())
        QDir::home().mkpath(path.absolutePath());
    QFile::copy(internalFile, path.absoluteFilePath(file));
    // Mark once() as done
    CkbSettings::set(settingPath, true);
}
bool AutoRun::isEnabled () [static]
Definition at line 33 of file autorun.cpp.
References CkbSettings::set().
Referenced by SettingsWidget::SettingsWidget().
                       {
    // Check if the file exists. If not, autostart is disabled.
    if(!path.exists() || !path.exists(file))
        return false;
    // If autostart is enabled, set the flag from once() (in case it hasn't been done yet)
    CkbSettings::set(settingPath, true);
    return true;
}
bool AutoRun::once () [static]
Definition at line 29 of file autorun.cpp.
References CkbSettings::get().
Referenced by SettingsWidget::SettingsWidget().
                  {
    return CkbSettings::get(settingPath).toBool();
}
Author
Generated automatically by Doxygen for ckb-next from the source code.