ColorMap
NAME
ColorMap -
SYNOPSIS
#include <src/ckb/colormap.h>
Public Member Functions
ColorMap ()
~ColorMap ()
ColorMap (const ColorMap &rhs)
const ColorMap & operator= (const ColorMap &rhs)
bool operator== (const ColorMap &rhs) const
void init (const KeyMap &map)
void clear ()
int count () const
const char *const * keyNames () const
QRgb * colors ()
const QRgb * colors () const
QRgb * colorForName (const char *name)
const QRgb * colorForName (const char *name) const
Private Member Functions
void alloc (int count)
void deAlloc ()
Private Attributes
const char ** _keyNames
QRgb * _colors
int _count
int _mapCount
Detailed Description
Definition at line 15 of file colormap.h.
Constructor & Destructor Documentation
ColorMap::ColorMap ()
Definition at line 3 of file colormap.cpp.
                   :
    _keyNames(0), _colors(0), _count(0), _mapCount(0)
{
}
ColorMap::~ColorMap ()
Definition at line 8 of file colormap.cpp.
References deAlloc().
                   {
    deAlloc();
}
ColorMap::ColorMap (const ColorMap &rhs)
Definition at line 12 of file colormap.cpp.
                                      :
    _keyNames(0), _colors(0), _count(0), _mapCount(0)
{
    *this = rhs;
}
Member Function Documentation
void ColorMap::alloc (intcount) [private]
Definition at line 43 of file colormap.cpp.
References _colors, _count, _keyNames, _mapCount, clear(), and deAlloc().
Referenced by init(), and operator=().
                                {
    if(newCount > _mapCount){
        // ^ map never shrinks, only expands
        deAlloc();
        _mapCount = newCount;
        _keyNames = new const char*[_mapCount];
        _colors = new QRgb[_mapCount];
    }
    _count = newCount;
    clear();
}
void ColorMap::clear ()
Definition at line 61 of file colormap.cpp.
References _colors, and _count.
Referenced by alloc(), AnimScript::end(), and KbLight::resetIndicators().
                    {
    memset(_colors, 0, _count * sizeof(QRgb));
}
QRgb * ColorMap::colorForName (const char *name)
Definition at line 88 of file colormap.cpp.
References _colors, _count, _keyNames, and qs_strcmp().
Referenced by KbLight::base(), KbLight::color(), KeyWidget::paintEvent(), AnimScript::readProcess(), KbLight::rebuildBaseMap(), and KbLight::setIndicator().
                                            {
    if(!_keyNames)
        return 0;
    const char** namePtr = (const char**)bsearch(&name, _keyNames, _count, sizeof(const char*), qs_strcmp);
    if(!namePtr)
        return 0;
    ptrdiff_t position = namePtr - _keyNames;
    return _colors + position;
}
const QRgb * ColorMap::colorForName (const char *name) const
Definition at line 98 of file colormap.cpp.
References _colors, _count, _keyNames, and qs_strcmp().
                                                         {
    if(!_keyNames)
        return 0;
    const char** namePtr = (const char**)bsearch(&name, _keyNames, _count, sizeof(const char*), qs_strcmp);
    if(!namePtr)
        return 0;
    ptrdiff_t position = namePtr - _keyNames;
    return _colors + position;
}
QRgb* ColorMap::colors () [inline]
Definition at line 33 of file colormap.h.
References _colors.
Referenced by KbLight::base(), KbAnim::blend(), KbLight::color(), KbLight::frameUpdate(), KbLight::printRGB(), and AnimScript::readProcess().
{ return _colors; }
const QRgb* ColorMap::colors () const [inline]
Definition at line 34 of file colormap.h.
References _colors.
{ return _colors; }
int ColorMap::count () const [inline]
Definition at line 31 of file colormap.h.
References _count.
Referenced by KbLight::base(), KbAnim::blend(), KbLight::color(), KbLight::frameUpdate(), KbLight::printRGB(), and AnimScript::readProcess().
{ return _count; }
void ColorMap::deAlloc () [private]
Definition at line 55 of file colormap.cpp.
References _colors, _count, _keyNames, and _mapCount.
Referenced by alloc(), and ~ColorMap().
                      {
    _count = _mapCount = 0;
    if(_keyNames) delete[] _keyNames;
    if(_colors) delete[] _colors;
}
void ColorMap::init (const KeyMap &map)
Definition at line 69 of file colormap.cpp.
References _count, _keyNames, alloc(), Key::hasLed, Key::name, KeyMap::positions(), and qs_strcmp().
Referenced by AnimScript::init(), and KbLight::map().
                                    {
    QList<Key> newKeys = map.positions();
    // There's no point including keys that don't have LEDs, so remove them now
    QMutableListIterator<Key> i(newKeys);
    while(i.hasNext()){
        Key key = i.next();
        if(!key.hasLed)
            i.remove();
    }
    // Now that we know how many keys we'll have, check memory
    alloc(newKeys.count());
    // Copy key names
    int keyPos = 0;
    foreach(const Key& key, newKeys)
        _keyNames[keyPos++] = key.name; // as above, it's safe to copy these since the strings are constants
    // Sort names for quick access
    qsort(_keyNames, _count, sizeof(const char*), qs_strcmp);
}
const char* const* ColorMap::keyNames () const [inline]
Definition at line 32 of file colormap.h.
References _keyNames.
Referenced by KbLight::printRGB().
{ return _keyNames; }
const ColorMap & ColorMap::operator= (const ColorMap &rhs)
Definition at line 18 of file colormap.cpp.
References _colors, _count, _keyNames, and alloc().
                                                      {
    alloc(rhs._count);
    // Copy key names and colors
    // (Note: it's safe to copy the const char*'s because key names are constants and will never move or be deleted)
    memcpy(_keyNames, rhs._keyNames, sizeof(const char*) * _count);
    memcpy(_colors, rhs._colors, sizeof(QRgb) * _count);
    return rhs;
}
bool ColorMap::operator== (const ColorMap &rhs) const
Definition at line 27 of file colormap.cpp.
References _colors, _count, _keyNames, and x.
                                                  {
    if(_count != rhs._count)
        return false;
    // Compare just the pointers because key names are sorted and the strings are constants.
    if(memcmp(_keyNames, rhs._keyNames, sizeof(const char*) * _count) != 0)
        return false;
    for(int x = 0;x < _count;x++){
        if(_colors[x] != rhs._colors[x])
            return false;
    }
    return true;
}
Field Documentation
QRgb* ColorMap::_colors [private]
Definition at line 45 of file colormap.h.
Referenced by alloc(), clear(), colorForName(), colors(), deAlloc(), operator=(), and operator==().
int ColorMap::_count [private]
Definition at line 46 of file colormap.h.
Referenced by alloc(), clear(), colorForName(), count(), deAlloc(), init(), operator=(), and operator==().
const char** ColorMap::_keyNames [private]
Definition at line 44 of file colormap.h.
Referenced by alloc(), colorForName(), deAlloc(), init(), keyNames(), operator=(), and operator==().
int ColorMap::_mapCount [private]
Definition at line 46 of file colormap.h.
Referenced by alloc(), and deAlloc().
Author
Generated automatically by Doxygen for ckb-next from the source code.