.TH "ColorMap" 3 "Tue May 16 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/colormap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorMap\fP ()"
.br
.ti -1c
.RI "\fB~ColorMap\fP ()"
.br
.ti -1c
.RI "\fBColorMap\fP (const \fBColorMap\fP &rhs)"
.br
.ti -1c
.RI "const \fBColorMap\fP & \fBoperator=\fP (const \fBColorMap\fP &rhs)"
.br
.ti -1c
.RI "void \fBinit\fP (const \fBKeyMap\fP &map)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "int \fBcount\fP () const "
.br
.ti -1c
.RI "const char *const * \fBkeyNames\fP () const "
.br
.ti -1c
.RI "QRgb * \fBcolors\fP ()"
.br
.ti -1c
.RI "const QRgb * \fBcolors\fP () const "
.br
.ti -1c
.RI "QRgb * \fBcolorForName\fP (const char *name)"
.br
.ti -1c
.RI "const QRgb * \fBcolorForName\fP (const char *name) const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBalloc\fP (int \fBcount\fP)"
.br
.ti -1c
.RI "void \fBdeAlloc\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char ** \fB_keyNames\fP"
.br
.ti -1c
.RI "QRgb * \fB_colors\fP"
.br
.ti -1c
.RI "int \fB_count\fP"
.br
.ti -1c
.RI "int \fB_mapCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file colormap\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColorMap::ColorMap ()"

.PP
Definition at line 3 of file colormap\&.cpp\&.
.PP
.nf
3                    :
4     _keyNames(0), _colors(0), _count(0), _mapCount(0)
5 {
6 }
.fi
.SS "ColorMap::~ColorMap ()"

.PP
Definition at line 8 of file colormap\&.cpp\&.
.PP
References deAlloc()\&.
.PP
.nf
8                    {
9     deAlloc();
10 }
.fi
.SS "ColorMap::ColorMap (const \fBColorMap\fP &rhs)"

.PP
Definition at line 12 of file colormap\&.cpp\&.
.PP
.nf
12                                       :
13     _keyNames(0), _colors(0), _count(0), _mapCount(0)
14 {
15     *this = rhs;
16 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ColorMap::alloc (intcount)\fC [private]\fP"

.PP
Definition at line 27 of file colormap\&.cpp\&.
.PP
References _colors, _count, _keyNames, _mapCount, clear(), and deAlloc()\&.
.PP
Referenced by init(), and operator=()\&.
.PP
.nf
27                                 {
28     if(newCount > _mapCount){
29         // ^ map never shrinks, only expands
30         deAlloc();
31         _mapCount = newCount;
32         _keyNames = new const char*[_mapCount];
33         _colors = new QRgb[_mapCount];
34     }
35     _count = newCount;
36     clear();
37 }
.fi
.SS "void ColorMap::clear ()"

.PP
Definition at line 45 of file colormap\&.cpp\&.
.PP
References _colors, and _count\&.
.PP
Referenced by alloc(), AnimScript::end(), and KbLight::resetIndicators()\&.
.PP
.nf
45                     {
46     memset(_colors, 0, _count * sizeof(QRgb));
47 }
.fi
.SS "QRgb * ColorMap::colorForName (const char *name)"

.PP
Definition at line 72 of file colormap\&.cpp\&.
.PP
References _colors, _count, _keyNames, and qs_strcmp()\&.
.PP
Referenced by KbLight::base(), KbLight::color(), KeyWidget::paintEvent(), AnimScript::readProcess(), KbLight::rebuildBaseMap(), and KbLight::setIndicator()\&.
.PP
.nf
72                                             {
73     if(!_keyNames)
74         return 0;
75     const char** namePtr = (const char**)bsearch(&name, _keyNames, _count, sizeof(const char*), qs_strcmp);
76     if(!namePtr)
77         return 0;
78     ptrdiff_t position = namePtr - _keyNames;
79     return _colors + position;
80 }
.fi
.SS "const QRgb * ColorMap::colorForName (const char *name) const"

.PP
Definition at line 82 of file colormap\&.cpp\&.
.PP
References _colors, _count, _keyNames, and qs_strcmp()\&.
.PP
.nf
82                                                          {
83     if(!_keyNames)
84         return 0;
85     const char** namePtr = (const char**)bsearch(&name, _keyNames, _count, sizeof(const char*), qs_strcmp);
86     if(!namePtr)
87         return 0;
88     ptrdiff_t position = namePtr - _keyNames;
89     return _colors + position;
90 }
.fi
.SS "QRgb* ColorMap::colors ()\fC [inline]\fP"

.PP
Definition at line 32 of file colormap\&.h\&.
.PP
References _colors\&.
.PP
Referenced by KbLight::base(), KbAnim::blend(), KbLight::color(), KbLight::frameUpdate(), KbLight::printRGB(), and AnimScript::readProcess()\&.
.PP
.nf
32 { return _colors; }
.fi
.SS "const QRgb* ColorMap::colors () const\fC [inline]\fP"

.PP
Definition at line 33 of file colormap\&.h\&.
.PP
References _colors\&.
.PP
.nf
33 { return _colors; }
.fi
.SS "int ColorMap::count () const\fC [inline]\fP"

.PP
Definition at line 30 of file colormap\&.h\&.
.PP
References _count\&.
.PP
Referenced by KbLight::base(), KbAnim::blend(), KbLight::color(), KbLight::frameUpdate(), KbLight::printRGB(), and AnimScript::readProcess()\&.
.PP
.nf
30 { return _count; }
.fi
.SS "void ColorMap::deAlloc ()\fC [private]\fP"

.PP
Definition at line 39 of file colormap\&.cpp\&.
.PP
References _colors, _count, _keyNames, and _mapCount\&.
.PP
Referenced by alloc(), and ~ColorMap()\&.
.PP
.nf
39                       {
40     _count = _mapCount = 0;
41     if(_keyNames) delete[] _keyNames;
42     if(_colors) delete[] _colors;
43 }
.fi
.SS "void ColorMap::init (const \fBKeyMap\fP &map)"

.PP
Definition at line 53 of file colormap\&.cpp\&.
.PP
References _count, _keyNames, alloc(), Key::hasLed, Key::name, KeyMap::positions(), and qs_strcmp()\&.
.PP
Referenced by AnimScript::init(), and KbLight::map()\&.
.PP
.nf
53                                     {
54     QList<Key> newKeys = map\&.positions();
55     // There's no point including keys that don't have LEDs, so remove them now
56     QMutableListIterator<Key> i(newKeys);
57     while(i\&.hasNext()){
58         Key key = i\&.next();
59         if(!key\&.hasLed)
60             i\&.remove();
61     }
62     // Now that we know how many keys we'll have, check memory
63     alloc(newKeys\&.count());
64     // Copy key names
65     int keyPos = 0;
66     foreach(const Key& key, newKeys)
67         _keyNames[keyPos++] = key\&.name;     // as above, it's safe to copy these since the strings are constants
68     // Sort names for quick access
69     qsort(_keyNames, _count, sizeof(const char*), qs_strcmp);
70 }
.fi
.SS "const char* const* ColorMap::keyNames () const\fC [inline]\fP"

.PP
Definition at line 31 of file colormap\&.h\&.
.PP
References _keyNames\&.
.PP
Referenced by KbLight::printRGB()\&.
.PP
.nf
31 { return _keyNames; }
.fi
.SS "const \fBColorMap\fP & ColorMap::operator= (const \fBColorMap\fP &rhs)"

.PP
Definition at line 18 of file colormap\&.cpp\&.
.PP
References _colors, _count, _keyNames, and alloc()\&.
.PP
.nf
18                                                       {
19     alloc(rhs\&._count);
20     // Copy key names and colors
21     // (Note: it's safe to copy the const char*'s because key names are constants and will never move or be deleted)
22     memcpy(_keyNames, rhs\&._keyNames, sizeof(const char*) * _count);
23     memcpy(_colors, rhs\&._colors, sizeof(QRgb) * _count);
24     return rhs;
25 }
.fi
.SH "Field Documentation"
.PP 
.SS "QRgb* ColorMap::_colors\fC [private]\fP"

.PP
Definition at line 44 of file colormap\&.h\&.
.PP
Referenced by alloc(), clear(), colorForName(), colors(), deAlloc(), and operator=()\&.
.SS "int ColorMap::_count\fC [private]\fP"

.PP
Definition at line 45 of file colormap\&.h\&.
.PP
Referenced by alloc(), clear(), colorForName(), count(), deAlloc(), init(), and operator=()\&.
.SS "const char** ColorMap::_keyNames\fC [private]\fP"

.PP
Definition at line 43 of file colormap\&.h\&.
.PP
Referenced by alloc(), colorForName(), deAlloc(), init(), keyNames(), and operator=()\&.
.SS "int ColorMap::_mapCount\fC [private]\fP"

.PP
Definition at line 45 of file colormap\&.h\&.
.PP
Referenced by alloc(), and deAlloc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
