src/ckb/quazip/crypt.h
NAME
src/ckb/quazip/crypt.h -
SYNOPSIS
#include 'quazip_global.h'
Macros
#define CRC32(c, b) ((*(pcrc_32_tab+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
#define zdecode(pkeys, pcrc_32_tab, c) (update_keys(pkeys,pcrc_32_tab,c ^= decrypt_byte(pkeys,pcrc_32_tab)))
#define zencode(pkeys, pcrc_32_tab, c, t) (t=decrypt_byte(pkeys,pcrc_32_tab), update_keys(pkeys,pcrc_32_tab,c), t^(c))
Functions
static int decrypt_byte (unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab)
static int update_keys (unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab, int c)
static void init_keys (const char *passwd, unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab)
Macro Definition Documentation
#define CRC32(c, b) ((*(pcrc_32_tab+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
Definition at line 32 of file crypt.h.
Referenced by update_keys().
#define zdecode(pkeys, pcrc_32_tab, c) (update_keys(pkeys,pcrc_32_tab,c ^= decrypt_byte(pkeys,pcrc_32_tab)))
Definition at line 79 of file crypt.h.
Referenced by unzOpenCurrentFile3(), and unzReadCurrentFile().
#define zencode(pkeys, pcrc_32_tab, c, t) (t=decrypt_byte(pkeys,pcrc_32_tab), update_keys(pkeys,pcrc_32_tab,c), t^(c))
Definition at line 82 of file crypt.h.
Referenced by zip64FlushWriteBuffer().
Function Documentation
static int decrypt_byte (unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab) [static]
Definition at line 37 of file crypt.h.
{
    //(void) pcrc_32_tab; /* avoid "unused parameter" warning */
    unsigned temp; /* POTENTIAL BUG: temp*(temp^1) may overflow in an
                     * unpredictable manner on 16-bit systems; not a problem
                     * with any known compiler so far, though */
    temp = ((unsigned)(*(pkeys+2)) & 0xffff) | 2;
    return (int)(((temp * (temp ^ 1)) >> 8) & 0xff);
}
static void init_keys (const char *passwd, unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab) [static]
Definition at line 68 of file crypt.h.
References update_keys().
Referenced by unzOpenCurrentFile3().
{
    *(pkeys+0) = 305419896L;
    *(pkeys+1) = 591751049L;
    *(pkeys+2) = 878082192L;
    while (*passwd != '\0') {
        update_keys(pkeys,pcrc_32_tab,(int)*passwd);
        passwd++;
    }
}
static int update_keys (unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab, intc) [static]
Definition at line 51 of file crypt.h.
References CRC32.
Referenced by init_keys().
{
    (*(pkeys+0)) = CRC32((*(pkeys+0)), c);
    (*(pkeys+1)) += (*(pkeys+0)) & 0xff;
    (*(pkeys+1)) = (*(pkeys+1)) * 134775813L + 1;
    {
      register int keyshift = (int)((*(pkeys+1)) >> 24);
      (*(pkeys+2)) = CRC32((*(pkeys+2)), keyshift);
    }
    return c;
}
Author
Generated automatically by Doxygen for ckb-next from the source code.