src/ckb-daemon/device_mouse.c
NAME
src/ckb-daemon/device_mouse.c -
SYNOPSIS
#include 'command.h'
#include 'device.h'
#include 'devnode.h'
#include 'firmware.h'
#include 'input.h'
#include 'profile.h'
#include 'usb.h'
Functions
int setactive_mouse (usbdevice *kb, int active)
int cmd_active_mouse (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *dummy4)
int cmd_idle_mouse (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *dummy4)
int cmd_pollrate (usbdevice *kb, usbmode *dummy1, int dummy2, int rate, const char *dummy3)
Function Documentation
int cmd_active_mouse (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *dummy4)
Definition at line 44 of file device_mouse.c.
References setactive_mouse().
                                                                                                {
    return setactive_mouse(kb, 1);
}
int cmd_idle_mouse (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *dummy4)
Definition at line 48 of file device_mouse.c.
References setactive_mouse().
                                                                                              {
    return setactive_mouse(kb, 0);
}
int cmd_pollrate (usbdevice *kb, usbmode *dummy1, intdummy2, intrate, const char *dummy3)
Definition at line 52 of file device_mouse.c.
References MSG_SIZE, usbdevice::pollrate, and usbsend.
                                                                                          {
    uchar msg[MSG_SIZE] = {
        0x07, 0x0a, 0, 0, (uchar)rate
    };
    if(!usbsend(kb, msg, 1))
        return -1;
    // Device should disconnect+reconnect, but update the poll rate field in case it doesn't
    kb->pollrate = rate;
    return 0;
}
int setactive_mouse (usbdevice *kb, intactive)
Definition at line 9 of file device_mouse.c.
References usbdevice::active, lighting::forceupdate, imutex, IN_CORSAIR, IN_HID, usbdevice::input, inputupdate(), usbinput::keys, usbprofile::lastlight, MSG_SIZE, NEEDS_FW_UPDATE, usbdevice::profile, and usbsend.
Referenced by cmd_active_mouse(), and cmd_idle_mouse().
                                              {
    if(NEEDS_FW_UPDATE(kb))
        return 0;
    const int keycount = 20;
    uchar msg[2][MSG_SIZE] = {
        { 0x07, 0x04, 0 }, // Disables or enables HW control for DPI and Sniper button
        { 0x07, 0x40, keycount, 0 }, // Select button input (simlilar to the packet sent to keyboards, but lacks a commit packet)
    };
    if(active)
        // Put the mouse into SW mode
        msg[0][2] = 2;
    else
        // Restore HW mode
        msg[0][2] = 1;
    pthread_mutex_lock(imutex(kb));
    kb->active = !!active;
    kb->profile->lastlight.forceupdate = 1;
    // Clear input
    memset(&kb->input.keys, 0, sizeof(kb->input.keys));
    inputupdate(kb);
    pthread_mutex_unlock(imutex(kb));
    if(!usbsend(kb, msg[0], 1))
        return -1;
    if(active){
        // Set up key input
        if(!usbsend(kb, msg[1], 1))
            return -1;
        for(int i = 0; i < keycount; i++){
            msg[1][i * 2 + 4] = i + 1;
            msg[1][i * 2 + 5] = (i < 6 ? IN_HID : IN_CORSAIR);
        }
    }
    return 0;
}
Author
Generated automatically by Doxygen for ckb-next from the source code.