.TH "src/ckb/extrasettingswidget.cpp" 3 "Fri Nov 3 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/extrasettingswidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'extrasettingswidget\&.h'\fP
.br
\fC#include 'ui_extrasettingswidget\&.h'\fP
.br
\fC#include 'kb\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ckbsettings\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static int \fBlastSharedDimming\fP = -2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int lastSharedDimming = -2\fC [static]\fP"

.PP
Definition at line 8 of file extrasettingswidget\&.cpp\&.
.PP
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), and ExtraSettingsWidget::pollUpdates()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
