ExtraSettingsWidget
NAME
ExtraSettingsWidget -
SYNOPSIS
#include <src/ckb/extrasettingswidget.h>
Inherits QDialog.
Public Member Functions
ExtraSettingsWidget (QWidget *parent=0)
~ExtraSettingsWidget ()
void pollUpdates ()
Private Slots
void on_trayBox_clicked (bool checked)
void on_brightnessBox_clicked (bool checked)
void on_animScanButton_clicked ()
void on_fpsBox_valueChanged (int arg1)
void on_ditherBox_clicked (bool checked)
void on_mAccelBox_clicked (bool checked)
void on_sAccelBox_clicked (bool checked)
void on_sSpeedBox_valueChanged (int arg1)
void on_delayBox_clicked (bool checked)
Private Attributes
Ui::ExtraSettingsWidget * ui
Detailed Description
Definition at line 10 of file extrasettingswidget.h.
Constructor & Destructor Documentation
ExtraSettingsWidget::ExtraSettingsWidget (QWidget *parent = 0) [explicit]
Read Macro Delay setting, update UI and Kb-internal flag
Definition at line 10 of file extrasettingswidget.cpp.
References Ui_ExtraSettingsWidget::animPathLabel, Ui_ExtraSettingsWidget::brightnessBox, Ui_ExtraSettingsWidget::delayBox, Kb::dither(), Ui_ExtraSettingsWidget::ditherBox, Ui_ExtraSettingsWidget::fpsBox, Ui_ExtraSettingsWidget::fpsWarnLabel, Kb::frameRate(), lastSharedDimming, Ui_ExtraSettingsWidget::mAccelBox, Kb::macroDelay(), KbLight::MAX_DIM, Kb::mouseAccel(), on_animScanButton_clicked(), Ui_ExtraSettingsWidget::osxLabel, Ui_ExtraSettingsWidget::osxLine, AnimScript::path(), Ui_ExtraSettingsWidget::sAccelBox, Kb::scrollSpeed(), Ui_ExtraSettingsWidget::setupUi(), KbLight::shareDimming(), Ui_ExtraSettingsWidget::sSpeedBox, Ui_ExtraSettingsWidget::sSpeedWidget, Ui_ExtraSettingsWidget::trayBox, ui, and CkbSettings::value().
                                                        :
    QDialog(parent),
    ui(new Ui::ExtraSettingsWidget)
{
    ui->setupUi(this);
    CkbSettings settings("Program");
    // Read frame rate from settings
    int rate = settings.value("framerate").toInt();
    if(rate <= 0 || rate > 60)
        rate = 30;
    ui->fpsBox->setValue(rate);
    Kb::frameRate(rate);
    ui->fpsWarnLabel->setVisible(rate > 30);
    // Read global brightness setting (default = on, 100% brightness)
    int dimming = settings.value("GlobalBrightness").toInt();
    if(dimming < -1 || dimming > KbLight::MAX_DIM)
        dimming = 0;
    lastSharedDimming = dimming;
    KbLight::shareDimming(dimming);
    // Set checkbox value (-1 = don't share)
    ui->brightnessBox->setChecked(dimming == -1);
    // Read dither
    bool dither = settings.value("Dither").toBool();
    Kb::dither(dither);
    ui->ditherBox->setChecked(dither);
#ifdef Q_OS_MACX
    // Read OSX settings
    bool noAccel = settings.value("DisableMouseAccel").toBool();
    Kb::mouseAccel(!noAccel);
    ui->mAccelBox->setChecked(noAccel);
    bool noScrollAccel = settings.value("DisableScrollAccel").toBool();
    int scrollSpeed = settings.value("ScrollSpeed", 3).toInt();
    ui->sAccelBox->setChecked(noScrollAccel);
    ui->sSpeedBox->setValue(scrollSpeed);
    Kb::scrollSpeed(noScrollAccel ? scrollSpeed : 0);
    if(!noScrollAccel)
        ui->sSpeedWidget->hide();
#else
    // Hide all OSX options on Linux
    ui->osxLabel->hide();
    ui->osxLine->hide();
    ui->mAccelBox->hide();
    ui->sAccelBox->hide();
    ui->sSpeedWidget->hide();
#endif
    // Read tray icon setting
    ui->trayBox->setChecked(settings.value("SuppressTrayIcon").toBool());
    // Update animation info
    ui->animPathLabel->setText(AnimScript::path());
    on_animScanButton_clicked();
    bool macroDelay = settings.value("MacroDelay").toBool();
    Kb::macroDelay(macroDelay);
    ui->delayBox->setChecked(macroDelay);
}
ExtraSettingsWidget::~ExtraSettingsWidget ()
Definition at line 73 of file extrasettingswidget.cpp.
References ui.
                                         {
    delete ui;
}
Member Function Documentation
void ExtraSettingsWidget::on_animScanButton_clicked () [private], [slot]
Definition at line 87 of file extrasettingswidget.cpp.
References Ui_ExtraSettingsWidget::animCountLabel, AnimScript::count(), AnimScript::scan(), and ui.
Referenced by ExtraSettingsWidget().
                                                   {
    AnimScript::scan();
    int count = AnimScript::count();
    if(count == 0)
        ui->animCountLabel->setText("No animations found");
    else if(count == 1)
        ui->animCountLabel->setText("1 animation found");
    else
        ui->animCountLabel->setText(QString("%1 animations found").arg(count));
}
void ExtraSettingsWidget::on_brightnessBox_clicked (boolchecked) [private], [slot]
Definition at line 82 of file extrasettingswidget.cpp.
References pollUpdates(), and KbLight::shareDimming().
                                                              {
    KbLight::shareDimming(checked ? -1 : 0);
    pollUpdates();
}
void ExtraSettingsWidget::on_delayBox_clicked (boolchecked) [private], [slot]
Definition at line 143 of file extrasettingswidget.cpp.
References Kb::macroDelay(), and CkbSettings::set().
                                                          {
    CkbSettings::set("Program/MacroDelay", checked);
    Kb::macroDelay(checked);
}
void ExtraSettingsWidget::on_ditherBox_clicked (boolchecked) [private], [slot]
Definition at line 110 of file extrasettingswidget.cpp.
References Kb::dither(), and CkbSettings::set().
                                                          {
    CkbSettings::set("Program/Dither", checked);
    Kb::dither(checked);
}
void ExtraSettingsWidget::on_fpsBox_valueChanged (intarg1) [private], [slot]
Definition at line 98 of file extrasettingswidget.cpp.
References Ui_ExtraSettingsWidget::fpsWarnLabel, Kb::frameRate(), CkbSettings::setValue(), and ui.
                                                        {
    // Set FPS
    CkbSettings settings("Program");
    settings.setValue("framerate", arg1);
    Kb::frameRate(arg1);
    // Show warning label if FPS is above 30
    if(arg1 > 30)
        ui->fpsWarnLabel->show();
    else
        ui->fpsWarnLabel->hide();
}
void ExtraSettingsWidget::on_mAccelBox_clicked (boolchecked) [private], [slot]
Definition at line 124 of file extrasettingswidget.cpp.
References Kb::mouseAccel(), and CkbSettings::set().
                                                          {
    CkbSettings::set("Program/DisableMouseAccel", checked);
    Kb::mouseAccel(!checked);
}
void ExtraSettingsWidget::on_sAccelBox_clicked (boolchecked) [private], [slot]
Definition at line 129 of file extrasettingswidget.cpp.
References Kb::scrollSpeed(), CkbSettings::set(), Ui_ExtraSettingsWidget::sSpeedBox, Ui_ExtraSettingsWidget::sSpeedWidget, and ui.
                                                          {
    CkbSettings::set("Program/DisableScrollAccel", checked);
    Kb::scrollSpeed(checked ? ui->sSpeedBox->value() : 0);
    if(checked)
        ui->sSpeedWidget->show();
    else
        ui->sSpeedWidget->hide();
}
void ExtraSettingsWidget::on_sSpeedBox_valueChanged (intarg1) [private], [slot]
Definition at line 138 of file extrasettingswidget.cpp.
References Ui_ExtraSettingsWidget::sAccelBox, Kb::scrollSpeed(), CkbSettings::set(), and ui.
                                                           {
    CkbSettings::set("Program/ScrollSpeed", arg1);
    Kb::scrollSpeed(ui->sAccelBox->isChecked() ? arg1 : 0);
}
void ExtraSettingsWidget::on_trayBox_clicked (boolchecked) [private], [slot]
Definition at line 77 of file extrasettingswidget.cpp.
References MainWindow::mainWindow, CkbSettings::set(), and MainWindow::toggleTrayIcon().
                                                        {
    CkbSettings::set("Program/SuppressTrayIcon", checked);
    MainWindow::mainWindow->toggleTrayIcon(!checked);
}
void ExtraSettingsWidget::pollUpdates ()
Definition at line 115 of file extrasettingswidget.cpp.
References CkbSettings::isBusy(), lastSharedDimming, CkbSettings::set(), and KbLight::shareDimming().
Referenced by on_brightnessBox_clicked(), and SettingsWidget::pollUpdates().
                                     {
    // Check for changes to shared brightness setting
    int dimming = KbLight::shareDimming();
    if(dimming != lastSharedDimming && !CkbSettings::isBusy()){
        CkbSettings::set("Program/GlobalBrightness", dimming);
        lastSharedDimming = dimming;
    }
}
Field Documentation
Ui::ExtraSettingsWidget* ExtraSettingsWidget::ui [private]
Definition at line 33 of file extrasettingswidget.h.
Referenced by ExtraSettingsWidget(), on_animScanButton_clicked(), on_fpsBox_valueChanged(), on_sAccelBox_clicked(), on_sSpeedBox_valueChanged(), and ~ExtraSettingsWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.