FwUpgradeDialog
NAME
FwUpgradeDialog -
SYNOPSIS
#include <src/ckb/fwupgradedialog.h>
Inherits QDialog.
Public Member Functions
FwUpgradeDialog (QWidget *parent, float newV, const QByteArray &fwBlob, Kb *device)
~FwUpgradeDialog ()
int exec ()
Private Slots
void fwUpdateProgress (int current, int total)
void fwUpdateFinished (bool succeeded)
void removeDev ()
void on_cancelButton_clicked ()
void on_actionButton_clicked ()
Private Member Functions
void closeEvent (QCloseEvent *event)
const QString & saveBlob ()
void cleanBlob ()
Private Attributes
Ui::FwUpgradeDialog * ui
QString savePath
QByteArray blob
Kb * kb
QEventLoop * evLoop
bool exitSuccess
Detailed Description
Definition at line 13 of file fwupgradedialog.h.
Constructor & Destructor Documentation
FwUpgradeDialog::FwUpgradeDialog (QWidget *parent, floatnewV, const QByteArray &fwBlob, Kb *device)
Definition at line 32 of file fwupgradedialog.cpp.
References Ui_FwUpgradeDialog::curLabel, Ui_FwUpgradeDialog::devLabel, DIALOG_HEIGHT_MIN, DIALOG_WIDTH, Kb::firmware, fwUpdateFinished(), fwUpdateProgress(), kb, Ui_FwUpgradeDialog::newLabel, removeDev(), Ui_FwUpgradeDialog::setupUi(), ui, and Kb::usbModel.
                                                                                                  :
    QDialog(parent),
    ui(new Ui::FwUpgradeDialog),
    blob(fwBlob), kb(device), evLoop(0), exitSuccess(true)
{
    ui->setupUi(this);
    ui->curLabel->setText(kb->firmware);
    ui->newLabel->setText(QString::number(newV, 'f', 2));
    ui->devLabel->setText(kb->usbModel);
    connect(device, SIGNAL(destroyed()), this, SLOT(removeDev()));
    connect(device, SIGNAL(fwUpdateProgress(int,int)), this, SLOT(fwUpdateProgress(int,int)));
    connect(device, SIGNAL(fwUpdateFinished(bool)), this, SLOT(fwUpdateFinished(bool)));
    setFixedSize(DIALOG_WIDTH, DIALOG_HEIGHT_MIN);
}
FwUpgradeDialog::~FwUpgradeDialog ()
Definition at line 49 of file fwupgradedialog.cpp.
References cleanBlob(), and ui.
                                 {
    cleanBlob();
    delete ui;
}
Member Function Documentation
void FwUpgradeDialog::cleanBlob () [private]
Definition at line 78 of file fwupgradedialog.cpp.
References savePath.
Referenced by fwUpdateFinished(), and ~FwUpgradeDialog().
                               {
    if(savePath.isEmpty())
        return;
    QFile(savePath).remove();
    savePath = "";
}
void FwUpgradeDialog::closeEvent (QCloseEvent *event) [private]
Definition at line 54 of file fwupgradedialog.cpp.
                                                  {
    event->ignore();
}
int FwUpgradeDialog::exec ()
Definition at line 108 of file fwupgradedialog.cpp.
References Ui_FwUpgradeDialog::actionButton, blob, Ui_FwUpgradeDialog::cancelButton, KbFirmware::dataForBoard(), DIALOG_HEIGHT_MAX(), DIALOG_WIDTH, evLoop, exitSuccess, Kb::features, kb, Ui_FwUpgradeDialog::newLabel, Ui_FwUpgradeDialog::progressBar, saveBlob(), Ui_FwUpgradeDialog::statusLabel, ui, and verifyFw().
Referenced by KbWidget::on_fwUpdButton_clicked().
                         {
    QString features = kb->features;
    if(!blob.isEmpty()){
        // If a blob was already specified, check its version and validity
        float newV = verifyFw(blob, features);
        if(newV == 0.f){
            QMessageBox::warning(parentWidget(), "Error", "<center>Not a valid firmware for this device.</center>");
            return QDialog::Rejected;
        }
        ui->newLabel->setText(QString::number(newV, 'f', 2));
    } else {
        // Download a new blob file
        ui->progressBar->show();
        ui->cancelButton->setEnabled(false);
        ui->actionButton->setEnabled(false);
        show();
        // This can take a while
        blob = KbFirmware::dataForBoard(features);
        // Check validity
        float newV = verifyFw(blob, features);
        if(newV == 0.f){
            hide();
            QMessageBox::warning(parentWidget(), "Error", "<center>There was a problem with the downloaded file.<br />Please try again later.</center>");
            return QDialog::Rejected;
        }
    }
    // Save temporary file
    if(saveBlob().isEmpty()){
        hide();
        QMessageBox::warning(parentWidget(), "Error", "<center>Unable to save temporary file.</center>");
        return QDialog::Rejected;
    }
    // Set up UI
    ui->progressBar->setValue(0);
    ui->progressBar->setMaximum(1);
    ui->progressBar->setTextVisible(false);
    ui->statusLabel->setText("Ready to install new firmware.<br /><br /><b>Disclaimer:</b> ckb-next is not endorsed by Corsair.<br />This is <i>unlikely</i> to cause any damage, however the developers of this software do not accept any responsibility in such an event.");
    ui->cancelButton->setEnabled(true);
    ui->actionButton->setEnabled(true);
    setFixedSize(DIALOG_WIDTH, DIALOG_HEIGHT_MAX);
    show();
    // Run modal event loop
    evLoop = new QEventLoop(this);
    evLoop->exec();
    delete evLoop;
    hide();
    return exitSuccess ? QDialog::Accepted : QDialog::Rejected;
}
void FwUpgradeDialog::fwUpdateFinished (boolsucceeded) [private], [slot]
Definition at line 171 of file fwupgradedialog.cpp.
References Ui_FwUpgradeDialog::actionButton, cleanBlob(), evLoop, Ui_FwUpgradeDialog::progressBar, quit(), Ui_FwUpgradeDialog::statusLabel, and ui.
Referenced by FwUpgradeDialog(), and removeDev().
                                                    {
    cleanBlob();
    if(succeeded)
        ui->statusLabel->setText("Update successful!");
    else
        ui->statusLabel->setText("Update failed.");
    ui->actionButton->setText("OK");
    ui->actionButton->setEnabled(true);
    ui->progressBar->setMaximum(1);
    ui->progressBar->setValue(1);
    // Exit after 10s
    if(evLoop)
        QTimer::singleShot(10000, evLoop, SLOT(quit()));
}
void FwUpgradeDialog::fwUpdateProgress (intcurrent, inttotal) [private], [slot]
Definition at line 164 of file fwupgradedialog.cpp.
References Ui_FwUpgradeDialog::progressBar, and ui.
Referenced by FwUpgradeDialog().
                                                            {
    if(current > 0 && total > 0){
        ui->progressBar->setMaximum(total);
        ui->progressBar->setValue(current);
    }
}
void FwUpgradeDialog::on_actionButton_clicked () [private], [slot]
Definition at line 192 of file fwupgradedialog.cpp.
References Ui_FwUpgradeDialog::actionButton, Ui_FwUpgradeDialog::cancelButton, DIALOG_HEIGHT_MIN, DIALOG_WIDTH, evLoop, Kb::fwUpdate(), kb, Ui_FwUpgradeDialog::progressBar, savePath, Ui_FwUpgradeDialog::statusLabel, and ui.
                                             {
    if(!savePath.isEmpty() && kb){
        // Start upgrade
        setFixedSize(DIALOG_WIDTH, DIALOG_HEIGHT_MIN);
        ui->progressBar->show();
        ui->progressBar->setValue(0);
        ui->progressBar->setMaximum(0);
        ui->progressBar->setTextVisible(true);
        ui->cancelButton->hide();
        ui->actionButton->setEnabled(false);
        ui->actionButton->setText("Please wait");
        ui->statusLabel->setText("Installing firmware...");
        kb->fwUpdate(savePath);
    } else {
        // Finished, close dialog.
        if(evLoop)
            evLoop->quit();
    }
}
void FwUpgradeDialog::on_cancelButton_clicked () [private], [slot]
Definition at line 186 of file fwupgradedialog.cpp.
References evLoop, and exitSuccess.
                                             {
    exitSuccess = false;
    if(evLoop)
        evLoop->quit();
}
void FwUpgradeDialog::removeDev () [private], [slot]
Definition at line 157 of file fwupgradedialog.cpp.
References fwUpdateFinished(), kb, and savePath.
Referenced by FwUpgradeDialog().
                               {
    kb = 0;
    // Assume success if upgrade in progress
    if(!savePath.isEmpty())
        fwUpdateFinished(true);
}
const QString & FwUpgradeDialog::saveBlob () [private]
Definition at line 58 of file fwupgradedialog.cpp.
References blob, and savePath.
Referenced by exec().
                                        {
    if(!savePath.isEmpty())
        return savePath;
    QDir tmp = QDir::temp();
    qint64 pid = QCoreApplication::applicationPid();
    QString path = tmp.absoluteFilePath(QString("ckb-%1-fwblob.bin").arg(pid));
    QFile output(path);
    if(!output.open(QIODevice::WriteOnly)){
        return savePath;
    }
    if(!output.write(blob)){
        output.close();
        tmp.remove(path);
        return savePath;
    }
    output.close();
    savePath = path;
    return savePath;
}
Field Documentation
QByteArray FwUpgradeDialog::blob [private]
Definition at line 41 of file fwupgradedialog.h.
Referenced by exec(), and saveBlob().
QEventLoop* FwUpgradeDialog::evLoop [private]
Definition at line 45 of file fwupgradedialog.h.
Referenced by exec(), fwUpdateFinished(), on_actionButton_clicked(), and on_cancelButton_clicked().
bool FwUpgradeDialog::exitSuccess [private]
Definition at line 46 of file fwupgradedialog.h.
Referenced by exec(), and on_cancelButton_clicked().
Kb* FwUpgradeDialog::kb [private]
Definition at line 42 of file fwupgradedialog.h.
Referenced by exec(), FwUpgradeDialog(), on_actionButton_clicked(), and removeDev().
QString FwUpgradeDialog::savePath [private]
Definition at line 37 of file fwupgradedialog.h.
Referenced by cleanBlob(), on_actionButton_clicked(), removeDev(), and saveBlob().
Ui::FwUpgradeDialog* FwUpgradeDialog::ui [private]
Definition at line 32 of file fwupgradedialog.h.
Referenced by exec(), fwUpdateFinished(), fwUpdateProgress(), FwUpgradeDialog(), on_actionButton_clicked(), and ~FwUpgradeDialog().
Author
Generated automatically by Doxygen for ckb-next from the source code.