GradientDialog
NAME
GradientDialog -
SYNOPSIS
#include <src/ckb/gradientdialog.h>
Inherits QDialog.
Data Structures
struct Preset
Public Member Functions
GradientDialog (QWidget *parent=0)
~GradientDialog ()
QGradientStops getGradient (const QGradientStops &prevGradient)
Private Slots
void currentChanged (QColor color, bool spontaneous, int position)
void colorChanged (QColor color)
void on_presetList_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous)
void on_presetName_textEdited (const QString &arg1)
void on_presetSave_clicked ()
void on_presetDelete_clicked ()
void on_stopPos_valueChanged (int arg1)
void on_stopOpacity_valueChanged (int arg1)
Private Member Functions
void addPreset (const Preset &preset)
QIcon makeIcon (const Preset &preset)
void updatePresets ()
void setPreset (const QString &newPreset)
Private Attributes
QMap< QString, Preset > presets
QString currentPreset
Ui::GradientDialog * ui
Detailed Description
Definition at line 12 of file gradientdialog.h.
Constructor & Destructor Documentation
GradientDialog::GradientDialog (QWidget *parent = 0) [explicit]
Definition at line 11 of file gradientdialog.cpp.
References addPreset(), CkbSettings::childGroups(), CkbSettings::childKeys(), colorChanged(), currentChanged(), GradientDialog::Preset::gradient, prefsPath, presets, Ui_GradientDialog::setupUi(), Ui_GradientDialog::stopColor, ui, updatePresets(), CkbSettings::value(), and Ui_GradientDialog::widget.
                                              :
    QDialog(parent),
    ui(new Ui::GradientDialog)
{
    ui->setupUi(this);
    connect(ui->widget, SIGNAL(currentChanged(QColor,bool,int)), this, SLOT(currentChanged(QColor,bool,int)));
    connect(ui->stopColor, SIGNAL(colorChanged(QColor)), this, SLOT(colorChanged(QColor)));
    // Add built-in presets
    Preset blackAndWhite("B & W", true);
    blackAndWhite.gradient.append(QGradientStop(0., QColor(0, 0, 0)));
    blackAndWhite.gradient.append(QGradientStop(1., QColor(255, 255, 255)));
    Preset fade("Fade", true);
    fade.gradient.append(QGradientStop(0., QColor(255, 255, 255)));
    fade.gradient.append(QGradientStop(1., QColor(255, 255, 255, 0)));
    Preset rainbow("Rainbow", true);
    rainbow.gradient.append(QGradientStop(0.00, QColor(255, 0, 0)));
    rainbow.gradient.append(QGradientStop(0.17, QColor(255, 255, 0)));
    rainbow.gradient.append(QGradientStop(0.33, QColor(0, 255, 0)));
    rainbow.gradient.append(QGradientStop(0.50, QColor(0, 255, 255)));
    rainbow.gradient.append(QGradientStop(0.67, QColor(0, 0, 255)));
    rainbow.gradient.append(QGradientStop(0.83, QColor(255, 0, 255)));
    rainbow.gradient.append(QGradientStop(1.00, QColor(255, 0, 0)));
    addPreset(blackAndWhite);
    addPreset(fade);
    addPreset(rainbow);
    // Load stored presets
    CkbSettings settings(prefsPath);
    foreach(const QString& name, settings.childGroups()){
        QString pName = name.toLower();
        if(presets.contains(pName))
            continue;
        SGroup group(settings, name);
        // Create keys in a map to ensure correct order and no duplicates
        QMap<int, QColor> colors;
        foreach(const QString& position, settings.childKeys()){
            int pos = position.toInt();
            if(pos < 0 || pos > 100)
                continue;
            colors[pos] = settings.value(position).value<QColor>();
        }
        if(colors.count() < 2)
            continue;
        Preset preset(name);
        QMapIterator<int, QColor> i(colors);
        while(i.hasNext()){
            i.next();
            preset.gradient.append(QGradientStop(i.key() / 100., i.value()));
        }
        presets[pName] = preset;
    }
    updatePresets();
}
GradientDialog::~GradientDialog ()
Definition at line 77 of file gradientdialog.cpp.
References GradientDialog::Preset::builtIn, GradientDialog::Preset::gradient, GradientDialog::Preset::name, prefsPath, presets, CkbSettings::setValue(), and ui.
                               {
    // Save presets
    CkbSettings settings(prefsPath, true);
    QMapIterator<QString, Preset> i(presets);
    while(i.hasNext()){
        Preset preset = i.next().value();
        if(!preset.builtIn){
            SGroup group(settings, preset.name);
            foreach(const QGradientStop& stop, preset.gradient)
                settings.setValue(QString::number((int)(stop.first * 100.)), stop.second);
        }
    }
    delete ui;
}
Member Function Documentation
void GradientDialog::addPreset (const Preset &preset) [inline], [private]
Definition at line 34 of file gradientdialog.h.
References GradientDialog::Preset::name, and presets.
Referenced by GradientDialog().
{ presets[preset.name.toLower()] = preset; }
void GradientDialog::colorChanged (QColorcolor) [private], [slot]
Definition at line 234 of file gradientdialog.cpp.
References GradientDialogWidget::setCurrentColor(), setPreset(), Ui_GradientDialog::stopOpacity, ui, and Ui_GradientDialog::widget.
Referenced by GradientDialog(), and on_stopOpacity_valueChanged().
                                             {
    color.setAlphaF(ui->stopOpacity->value() / 100.f);
    ui->widget->setCurrentColor(color);
    setPreset("");
}
void GradientDialog::currentChanged (QColorcolor, boolspontaneous, intposition) [private], [slot]
Definition at line 128 of file gradientdialog.cpp.
References ColorButton::color(), setPreset(), Ui_GradientDialog::stopBox, Ui_GradientDialog::stopColor, GradientDialogWidget::stopCount(), Ui_GradientDialog::stopOpacity, Ui_GradientDialog::stopPos, ui, and Ui_GradientDialog::widget.
Referenced by GradientDialog().
                                                                               {
    int pCount = ui->widget->stopCount();
    if(pCount == 1)
        ui->stopBox->setTitle("1 point");
    else
        ui->stopBox->setTitle(QString("%1 points").arg(pCount));
    if(!color.isValid()){
        ui->stopBox->setEnabled(false);
        ui->stopPos->setValue(0);
        ui->stopColor->color(QColor(0, 0, 0));
        ui->stopOpacity->setValue(0);
    } else {
        ui->stopBox->setEnabled(true);
        ui->stopPos->setValue(position);
        ui->stopColor->color(color);
        ui->stopOpacity->setValue(round(color.alphaF() * 100.f));
    }
    // Un-set current preset
    if(spontaneous)
        setPreset("");
    setFocus();
}
QGradientStops GradientDialog::getGradient (const QGradientStops &prevGradient)
Definition at line 67 of file gradientdialog.cpp.
References Ui_GradientDialog::presetDelete, Ui_GradientDialog::presetSave, GradientDialogWidget::setStops(), GradientDialogWidget::stops(), ui, and Ui_GradientDialog::widget.
Referenced by GradientButton::pickGradient().
                                                                            {
    ui->presetDelete->setEnabled(false);
    ui->presetSave->setEnabled(true);
    ui->widget->setStops(prevGradient);
    exec();
    if(result() != QDialog::Accepted)
        return prevGradient;
    return ui->widget->stops();
}
QIcon GradientDialog::makeIcon (const Preset &preset) [private]
Definition at line 92 of file gradientdialog.cpp.
References GradientDialog::Preset::gradient, x, and y.
Referenced by updatePresets().
                                                  {
    // Paint gradient into a square
    int w = 60, h = 60;
    QImage image(w, h, QImage::Format_RGB888);
    QPainter painter(&image);
    // Draw background
    for(int x = 0; x < w; x += 30){
        for(int y = 0; y < h; y += 30){
            painter.fillRect(x, y, 15, 15, QColor(255, 255, 255));
            painter.fillRect(x + 15, y, 15, 15, QColor(192, 192, 192));
            painter.fillRect(x, y + 15, 15, 15, QColor(192, 192, 192));
            painter.fillRect(x + 15, y + 15, 15, 15, QColor(255, 255, 255));
        }
    }
    // Draw gradient
    painter.setPen(QColor(0, 0, 0));
    QLinearGradient gradient(1., 1., w - 1., h - 1.);
    gradient.setStops(preset.gradient);
    painter.setBrush(gradient);
    painter.drawRect(0, 0, w - 1, h - 1);
    return QPixmap::fromImage(image);
}
void GradientDialog::on_presetDelete_clicked () [private], [slot]
Definition at line 211 of file gradientdialog.cpp.
References GradientDialog::Preset::builtIn, current, currentPreset, GradientDialog::Preset::name, Ui_GradientDialog::presetDelete, presets, Ui_GradientDialog::presetSave, ui, and updatePresets().
                                            {
    Preset current = presets.value(currentPreset);
    if(current.name == "" || current.builtIn)
        return;
    if(QMessageBox::warning(this, "Warning", QString("Delete preset \"%1\"?").arg(current.name), QMessageBox::StandardButtons(QMessageBox::Yes | QMessageBox::No)) != QMessageBox::Yes){
        setFocus();
        return;
    }
    presets.remove(currentPreset);
    currentPreset = "";
    ui->presetDelete->setEnabled(false);
    ui->presetSave->setEnabled(true);
    updatePresets();
    setFocus();
}
void GradientDialog::on_presetList_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous) [private], [slot]
Definition at line 174 of file gradientdialog.cpp.
References setPreset().
                                                                                                        {
    setPreset(current ? current->text().toLower() : "");
}
void GradientDialog::on_presetName_textEdited (const QString &arg1) [private], [slot]
Definition at line 178 of file gradientdialog.cpp.
References currentPreset, presets, and setPreset().
                                                                {
    if(currentPreset != "" && arg1.trimmed() != presets[currentPreset].name)
        setPreset("");
}
void GradientDialog::on_presetSave_clicked () [private], [slot]
Definition at line 183 of file gradientdialog.cpp.
References GradientDialog::Preset::builtIn, currentPreset, GradientDialog::Preset::name, Ui_GradientDialog::presetDelete, Ui_GradientDialog::presetName, presets, Ui_GradientDialog::presetSave, GradientDialogWidget::stops(), ui, updatePresets(), and Ui_GradientDialog::widget.
                                          {
    if(currentPreset != "")
        return;
    QString name = ui->presetName->text().trimmed();
    if(name == "")
        ui->presetName->setText(name = "Custom");
    QString pName = name.toLower();
    // Make sure not to overwrite a built-in preset
    Preset previous = presets[pName];
    if(previous.builtIn){
        QMessageBox::warning(this, "Error", "Can't overwrite a built-in preset. Please choose a different name.");
        setFocus();
        return;
    } else if(previous.name != ""){
        // Warn when overwriting an existing preset
        if(QMessageBox::warning(this, "Warning", QString("Preset \"%1\" already exists. Replace?").arg(name), QMessageBox::StandardButtons(QMessageBox::Save | QMessageBox::Cancel)) != QMessageBox::Save){
            setFocus();
            return;
        }
    }
    presets[pName] = Preset(name, ui->widget->stops());
    currentPreset = pName;
    ui->presetDelete->setEnabled(true);
    ui->presetSave->setEnabled(false);
    updatePresets();
    setFocus();
}
void GradientDialog::on_stopOpacity_valueChanged (intarg1) [private], [slot]
Definition at line 240 of file gradientdialog.cpp.
References ColorButton::color(), colorChanged(), setPreset(), Ui_GradientDialog::stopColor, and ui.
                                                        {
    colorChanged(ui->stopColor->color());
    setPreset("");
}
void GradientDialog::on_stopPos_valueChanged (intarg1) [private], [slot]
Definition at line 227 of file gradientdialog.cpp.
References GradientDialogWidget::moveCurrent(), setPreset(), Ui_GradientDialog::stopPos, ui, and Ui_GradientDialog::widget.
                                                    {
    int res = ui->widget->moveCurrent(arg1);
    if(res != arg1)
        ui->stopPos->setValue(res);
    setPreset("");
}
void GradientDialog::setPreset (const QString &newPreset) [private]
Definition at line 151 of file gradientdialog.cpp.
References GradientDialog::Preset::builtIn, current, currentPreset, GradientDialog::Preset::gradient, GradientDialog::Preset::name, Ui_GradientDialog::presetDelete, Ui_GradientDialog::presetList, Ui_GradientDialog::presetName, presets, Ui_GradientDialog::presetSave, GradientDialogWidget::setStops(), ui, and Ui_GradientDialog::widget.
Referenced by colorChanged(), currentChanged(), on_presetList_currentItemChanged(), on_presetName_textEdited(), on_stopOpacity_valueChanged(), and on_stopPos_valueChanged().
                                                      {
    if(currentPreset == newPreset)
        return;
    if(newPreset == ""){
        ui->presetList->clearSelection();
        ui->presetList->setCurrentItem(0);
        Preset current = presets.value(currentPreset);
        QString curName = ui->presetName->text().trimmed();
        if(curName == "" || (curName == current.name && current.builtIn))
            ui->presetName->setText("Custom");
        ui->presetDelete->setEnabled(false);
        ui->presetSave->setEnabled(true);
    } else {
        Preset current = presets.value(newPreset);
        ui->presetName->setText(current.name);
        ui->presetDelete->setEnabled(!current.builtIn);
        ui->presetSave->setEnabled(false);
        ui->widget->setStops(current.gradient);
    }
    currentPreset = newPreset;
    setFocus();
}
void GradientDialog::updatePresets () [private]
Definition at line 115 of file gradientdialog.cpp.
References currentPreset, makeIcon(), GradientDialog::Preset::name, Ui_GradientDialog::presetList, presets, and ui.
Referenced by GradientDialog(), on_presetDelete_clicked(), and on_presetSave_clicked().
                                  {
    ui->presetList->clear();
    QMapIterator<QString, Preset> i(presets);
    while(i.hasNext()){
        i.next();
        const Preset& preset = i.value();
        QListWidgetItem* item = new QListWidgetItem(makeIcon(preset), preset.name, ui->presetList);
        if(currentPreset == i.key())
            item->setSelected(true);
        ui->presetList->addItem(item);
    }
}
Field Documentation
QString GradientDialog::currentPreset [private]
Definition at line 32 of file gradientdialog.h.
Referenced by on_presetDelete_clicked(), on_presetName_textEdited(), on_presetSave_clicked(), setPreset(), and updatePresets().
QMap<QString, Preset> GradientDialog::presets [private]
Definition at line 31 of file gradientdialog.h.
Referenced by addPreset(), GradientDialog(), on_presetDelete_clicked(), on_presetName_textEdited(), on_presetSave_clicked(), setPreset(), updatePresets(), and ~GradientDialog().
Ui::GradientDialog* GradientDialog::ui [private]
Definition at line 39 of file gradientdialog.h.
Referenced by colorChanged(), currentChanged(), getGradient(), GradientDialog(), on_presetDelete_clicked(), on_presetSave_clicked(), on_stopOpacity_valueChanged(), on_stopPos_valueChanged(), setPreset(), updatePresets(), and ~GradientDialog().
Author
Generated automatically by Doxygen for ckb-next from the source code.