src/ckb-daemon/input.h
NAME
src/ckb-daemon/input.h -
SYNOPSIS
#include 'includes.h'
#include 'usb.h'
Data Structures
struct parameter
struct parameter contains the values for a fresh started macro_play thread. parameter_t is the typedef for it.
struct ptlist
struct ptlist is one element in the single linked list to store macro_play threads waiting for their execution ptlist_t is the typedef for it.
Macros
#define IS_MOD(s) ((s) == KEY_CAPSLOCK || (s) == KEY_NUMLOCK || (s) == KEY_SCROLLLOCK || (s) == KEY_LEFTSHIFT || (s) == KEY_RIGHTSHIFT || (s) == KEY_LEFTCTRL || (s) == KEY_RIGHTCTRL || (s) == KEY_LEFTMETA || (s) == KEY_RIGHTMETA || (s) == KEY_LEFTALT || (s) == KEY_RIGHTALT || (s) == KEY_FN)
Typedefs
typedef struct parameter parameter_t
struct parameter contains the values for a fresh started macro_play thread. parameter_t is the typedef for it.
typedef struct ptlist ptlist_t
struct ptlist is one element in the single linked list to store macro_play threads waiting for their execution ptlist_t is the typedef for it.
Functions
int os_inputopen (usbdevice *kb)
os_inputopen
void os_inputclose (usbdevice *kb)
void inputupdate (usbdevice *kb)
void updateindicators_kb (usbdevice *kb, int force)
void initbind (binding *bind)
void freebind (binding *bind)
void cmd_bind (usbdevice *kb, usbmode *mode, int dummy, int keyindex, const char *to)
void cmd_unbind (usbdevice *kb, usbmode *mode, int dummy, int keyindex, const char *ignored)
void cmd_rebind (usbdevice *kb, usbmode *mode, int dummy, int keyindex, const char *ignored)
void cmd_macro (usbdevice *kb, usbmode *mode, const int notifynumber, const char *keys, const char *assignment)
void os_keypress (usbdevice *kb, int scancode, int down)
void os_mousemove (usbdevice *kb, int x, int y)
int os_setupindicators (usbdevice *kb)
Data Structure Documentation
struct parameter
Definition at line 54 of file input.h.
Data Fields:
usbdevice * kb
keymacro * macro
struct ptlist
Definition at line 62 of file input.h.
Data Fields:
struct ptlist * next
pthread_t thread_id
Macro Definition Documentation
#define IS_MOD(s) ((s) == KEY_CAPSLOCK || (s) == KEY_NUMLOCK || (s) == KEY_SCROLLLOCK || (s) == KEY_LEFTSHIFT || (s) == KEY_RIGHTSHIFT || (s) == KEY_LEFTCTRL || (s) == KEY_RIGHTCTRL || (s) == KEY_LEFTMETA || (s) == KEY_RIGHTMETA || (s) == KEY_LEFTALT || (s) == KEY_RIGHTALT || (s) == KEY_FN)
Definition at line 34 of file input.h.
Referenced by inputupdate_keys().
Typedef Documentation
typedef struct parameter parameter_t
typedef struct ptlist ptlist_t
Function Documentation
void cmd_bind (usbdevice *kb, usbmode *mode, intdummy, intkeyindex, const char *to)
Definition at line 307 of file input.c.
References binding::base, usbmode::bind, imutex, keymap, N_KEYS_INPUT, and key::scan.
                                                                                    {
    (void)dummy;
    if(keyindex >= N_KEYS_INPUT)
        return;
    // Find the key to bind to
    int tocode = 0;
    if(sscanf(to, "#x%ux", &tocode) != 1 && sscanf(to, "#%u", &tocode) == 1 && tocode < N_KEYS_INPUT){
        pthread_mutex_lock(imutex(kb));
        mode->bind.base[keyindex] = tocode;
        pthread_mutex_unlock(imutex(kb));
        return;
    }
    // If not numeric, look it up
    for(int i = 0; i < N_KEYS_INPUT; i++){
        if(keymap[i].name && !strcmp(to, keymap[i].name)){
            pthread_mutex_lock(imutex(kb));
            mode->bind.base[keyindex] = keymap[i].scan;
            pthread_mutex_unlock(imutex(kb));
            return;
        }
    }
}
void cmd_macro (usbdevice *kb, usbmode *mode, const intnotifynumber, const char *keys, const char *assignment)
Definition at line 475 of file input.c.
References _cmd_macro(), and imutex.
                                                                                                              {
    (void)notifynumber;
    pthread_mutex_lock(imutex(kb));
    _cmd_macro(mode, keys, assignment);
    pthread_mutex_unlock(imutex(kb));
}
void cmd_rebind (usbdevice *kb, usbmode *mode, intdummy, intkeyindex, const char *ignored)
Definition at line 342 of file input.c.
References binding::base, usbmode::bind, imutex, keymap, N_KEYS_INPUT, and key::scan.
                                                                                      {
    (void)dummy;
    (void)to;
    if(keyindex >= N_KEYS_INPUT)
        return;
    pthread_mutex_lock(imutex(kb));
    mode->bind.base[keyindex] = keymap[keyindex].scan;
    pthread_mutex_unlock(imutex(kb));
}
void cmd_unbind (usbdevice *kb, usbmode *mode, intdummy, intkeyindex, const char *ignored)
Definition at line 331 of file input.c.
References binding::base, usbmode::bind, imutex, KEY_UNBOUND, and N_KEYS_INPUT.
                                                                                      {
    (void)dummy;
    (void)to;
    if(keyindex >= N_KEYS_INPUT)
        return;
    pthread_mutex_lock(imutex(kb));
    mode->bind.base[keyindex] = KEY_UNBOUND;
    pthread_mutex_unlock(imutex(kb));
}
void freebind (binding *bind)
Definition at line 300 of file input.c.
References keymacro::actions, binding::macrocount, and binding::macros.
Referenced by freemode().
                            {
    for(int i = 0; i < bind->macrocount; i++)
        free(bind->macros[i].actions);
    free(bind->macros);
    memset(bind, 0, sizeof(*bind));
}
void initbind (binding *bind)
Definition at line 292 of file input.c.
References binding::base, keymap, binding::macrocap, binding::macrocount, binding::macros, N_KEYS_INPUT, and key::scan.
Referenced by initmode().
                            {
    for(int i = 0; i < N_KEYS_INPUT; i++)
        bind->base[i] = keymap[i].scan;
    bind->macros = calloc(32, sizeof(keymacro));
    bind->macrocap = 32;
    bind->macrocount = 0;
}
void inputupdate (usbdevice *kb)
Definition at line 241 of file input.c.
References usbdevice::input, inputupdate_keys(), os_mousemove(), usbdevice::profile, usbinput::rel_x, usbinput::rel_y, usbdevice::uinput_kb, and usbdevice::uinput_mouse.
Referenced by os_inputmain(), setactive_kb(), and setactive_mouse().
                               {
#ifdef OS_LINUX
    if((!kb->uinput_kb || !kb->uinput_mouse)
#else
    if(!kb->event
#endif
            || !kb->profile)
        return;
    // Process key/button input
    inputupdate_keys(kb);
    // Process mouse movement
    usbinput* input = &kb->input;
    if(input->rel_x != 0 || input->rel_y != 0){
        os_mousemove(kb, input->rel_x, input->rel_y);
        input->rel_x = input->rel_y = 0;
    }
    // Finish up
    memcpy(input->prevkeys, input->keys, N_KEYBYTES_INPUT);
}
void os_inputclose (usbdevice *kb)
Definition at line 76 of file input_linux.c.
References ckb_warn, usbdevice::uinput_kb, and usbdevice::uinput_mouse.
Referenced by closeusb().
                                 {
    if(kb->uinput_kb <= 0 || kb->uinput_mouse <= 0)
        return;
    // Set all keys released
    struct input_event event;
    memset(&event, 0, sizeof(event));
    event.type = EV_KEY;
    for(int key = 0; key < KEY_CNT; key++){
        event.code = key;
        if(write(kb->uinput_kb - 1, &event, sizeof(event)) <= 0)
            ckb_warn("uinput write failed: %s\n", strerror(errno));
        if(write(kb->uinput_mouse - 1, &event, sizeof(event)) <= 0)
            ckb_warn("uinput write failed: %s\n", strerror(errno));
    }
    event.type = EV_SYN;
    event.code = SYN_REPORT;
    if(write(kb->uinput_kb - 1, &event, sizeof(event)) <= 0)
        ckb_warn("uinput write failed: %s\n", strerror(errno));
    if(write(kb->uinput_mouse - 1, &event, sizeof(event)) <= 0)
        ckb_warn("uinput write failed: %s\n", strerror(errno));
    // Close the keyboard
    ioctl(kb->uinput_kb - 1, UI_DEV_DESTROY);
    close(kb->uinput_kb - 1);
    kb->uinput_kb = 0;
    // Close the mouse
    ioctl(kb->uinput_mouse - 1, UI_DEV_DESTROY);
    close(kb->uinput_mouse - 1);
    kb->uinput_mouse = 0;
}
int os_inputopen (usbdevice *kb)
Parameters:
kb
Returns:
Some tips on using uinput_user_dev in
Definition at line 55 of file input_linux.c.
References usbdevice::fwversion, INDEX_OF, keyboard, usbdevice::name, usbdevice::product, usbdevice::uinput_kb, usbdevice::uinput_mouse, uinputopen(), and usbdevice::vendor.
Referenced by _setupusb().
                               {
    // Create the new input device
    int index = INDEX_OF(kb, keyboard);
    struct uinput_user_dev indev;
    memset(&indev, 0, sizeof(indev));
    snprintf(indev.name, UINPUT_MAX_NAME_SIZE, "ckb%d: %s", index, kb->name);
    indev.id.bustype = BUS_USB;
    indev.id.vendor = kb->vendor;
    indev.id.product = kb->product;
    indev.id.version = kb->fwversion;
    // Open keyboard
    int fd = uinputopen(&indev, 0);
    kb->uinput_kb = fd;
    if(fd <= 0)
        return 0;
    // Open mouse
    fd = uinputopen(&indev, 1);
    kb->uinput_mouse = fd;
    return fd <= 0;
}
void os_keypress (usbdevice *kb, intscancode, intdown)
Definition at line 118 of file input_linux.c.
References BTN_WHEELDOWN, BTN_WHEELUP, ckb_warn, isync(), SCAN_MOUSE, usbdevice::uinput_kb, and usbdevice::uinput_mouse.
Referenced by inputupdate_keys(), and play_macro().
                                                       {
    struct input_event event;
    memset(&event, 0, sizeof(event));
    int is_mouse = 0;
    if(scancode == BTN_WHEELUP || scancode == BTN_WHEELDOWN){
        // The mouse wheel is a relative axis
        if(!down)
            return;
        event.type = EV_REL;
        event.code = REL_WHEEL;
        event.value = (scancode == BTN_WHEELUP ? 1 : -1);
        is_mouse = 1;
    } else {
        // Mouse buttons and key events are both EV_KEY. The scancodes are already correct, just remove the ckb bit
        event.type = EV_KEY;
        event.code = scancode & ~SCAN_MOUSE;
        event.value = down;
        is_mouse = !!(scancode & SCAN_MOUSE);
    }
    if(write((is_mouse ? kb->uinput_mouse : kb->uinput_kb) - 1, &event, sizeof(event)) <= 0)
        ckb_warn("uinput write failed: %s\n", strerror(errno));
    else
        isync(kb);
}
void os_mousemove (usbdevice *kb, intx, inty)
Definition at line 143 of file input_linux.c.
References ckb_warn, isync(), usbdevice::uinput_mouse, x, and y.
Referenced by inputupdate(), and play_macro().
                                              {
    struct input_event event;
    memset(&event, 0, sizeof(event));
    event.type = EV_REL;
    if(x != 0){
        event.code = REL_X;
        event.value = x;
        if(write(kb->uinput_mouse - 1, &event, sizeof(event)) <= 0)
            ckb_warn("uinput write failed: %s\n", strerror(errno));
        else
            isync(kb);
    }
    if(y != 0){
        event.code = REL_Y;
        event.value = y;
        if(write(kb->uinput_mouse - 1, &event, sizeof(event)) <= 0)
            ckb_warn("uinput write failed: %s\n", strerror(errno));
        else
            isync(kb);
    }
}
int os_setupindicators (usbdevice *kb)
Definition at line 189 of file input_linux.c.
References _ledthread(), usbdevice::hw_ileds, usbdevice::hw_ileds_old, and usbdevice::ileds.
Referenced by _setupusb().
                                     {
    // Initialize LEDs to all off
    kb->hw_ileds = kb->hw_ileds_old = kb->ileds = 0;
    // Create and detach thread to read LED events
    pthread_t thread;
    int err = pthread_create(&thread, 0, _ledthread, kb);
    if(err != 0)
        return err;
    pthread_detach(thread);
    return 0;
}
void updateindicators_kb (usbdevice *kb, intforce)
Definition at line 261 of file input.c.
References usbdevice::active, usbprofile::currentmode, DELAY_SHORT, usbdevice::hw_ileds, usbdevice::hw_ileds_old, I_CAPS, I_NUM, I_SCROLL, usbdevice::ileds, usbmode::inotify, usbmode::ioff, usbmode::ion, nprintind(), os_sendindicators(), OUTFIFO_MAX, and usbdevice::profile.
                                                  {
    // Read current hardware indicator state (set externally)
    uchar old = kb->ileds, hw_old = kb->hw_ileds_old;
    uchar new = kb->hw_ileds, hw_new = new;
    // Update them if needed
    if(kb->active){
        usbmode* mode = kb->profile->currentmode;
        new = (new & ~mode->ioff) | mode->ion;
    }
    kb->ileds = new;
    kb->hw_ileds_old = hw_new;
    if(old != new || force){
        DELAY_SHORT(kb);
        os_sendindicators(kb);
    }
    // Print notifications if desired
    if(!kb->active)
        return;
    usbmode* mode = kb->profile->currentmode;
    uchar indicators[] = { I_NUM, I_CAPS, I_SCROLL };
    for(unsigned i = 0; i < sizeof(indicators) / sizeof(uchar); i++){
        uchar mask = indicators[i];
        if((hw_old & mask) == (hw_new & mask))
            continue;
        for(int notify = 0; notify < OUTFIFO_MAX; notify++){
            if(mode->inotify[notify] & mask)
                nprintind(kb, notify, mask, hw_new & mask);
        }
    }
}
Author
Generated automatically by Doxygen for ckb-next from the source code.