KbManager
NAME
KbManager -
SYNOPSIS
#include <src/ckb/kbmanager.h>
Inherits QObject.
Signals
void kbConnected (Kb *device)
void kbDisconnected (Kb *device)
void versionUpdated ()
Static Public Member Functions
static void init (QString guiVersion)
static void stop ()
static KbManager * kbManager ()
static QString ckbGuiVersion ()
static QString ckbDaemonVersion ()
static float parseVersionString (QString version)
static float ckbGuiVersionF ()
static float ckbDaemonVersionF ()
static const QSet< Kb * > devices ()
static QTimer * eventTimer ()
static void fps (int framerate)
static QTimer * scanTimer ()
Private Slots
void scanKeyboards ()
Private Member Functions
KbManager (QObject *parent=0)
Private Attributes
QSet< Kb * > _devices
QTimer * _eventTimer
QTimer * _scanTimer
Static Private Attributes
static KbManager * _kbManager = 0
static QString _guiVersion
static QString _daemonVersion = '<unavailable>'
Detailed Description
Definition at line 14 of file kbmanager.h.
Constructor & Destructor Documentation
KbManager::KbManager (QObject *parent = 0) [explicit], [private]
Definition at line 26 of file kbmanager.cpp.
References _eventTimer, _scanTimer, and scanKeyboards().
Referenced by init().
                                    : QObject(parent){
    // Set up the timers
    _eventTimer = new QTimer(this);
    _eventTimer->setTimerType(Qt::PreciseTimer);
    _scanTimer = new QTimer(this);
    _scanTimer->start(1000);
    connect(_scanTimer, SIGNAL(timeout()), this, SLOT(scanKeyboards()));
    // Scan for keyboards immediately so they show up as soon as the GUI appears.
    QTimer::singleShot(0,this,SLOT(scanKeyboards()));
}
Member Function Documentation
static QString KbManager::ckbDaemonVersion () [inline], [static]
Definition at line 27 of file kbmanager.h.
References _daemonVersion.
Referenced by MainWindow::updateVersion().
{ return _daemonVersion; }
static float KbManager::ckbDaemonVersionF () [inline], [static]
Definition at line 31 of file kbmanager.h.
References _daemonVersion, DAEMON_UNAVAILABLE_STR, and parseVersionString().
Referenced by KbFirmware::_latestForBoard(), and MainWindow::updateVersion().
{ return _daemonVersion == DAEMON_UNAVAILABLE_STR ? INFINITY : parseVersionString(_daemonVersion); }
static QString KbManager::ckbGuiVersion () [inline], [static]
Definition at line 26 of file kbmanager.h.
References _guiVersion.
{ return _guiVersion; }
static float KbManager::ckbGuiVersionF () [inline], [static]
Definition at line 30 of file kbmanager.h.
References _guiVersion, and parseVersionString().
Referenced by KbFirmware::_latestForBoard(), and MainWindow::updateVersion().
{ return parseVersionString(_guiVersion); }
static const QSet<Kb*> KbManager::devices () [inline], [static]
Definition at line 34 of file kbmanager.h.
References _devices, and _kbManager.
{ return _kbManager ? _kbManager->_devices : QSet<Kb*>(); }
static QTimer* KbManager::eventTimer () [inline], [static]
Definition at line 38 of file kbmanager.h.
References _eventTimer, and _kbManager.
Referenced by fps().
{ return _kbManager ? _kbManager->_eventTimer : 0; }
void KbManager::fps (intframerate) [static]
Definition at line 38 of file kbmanager.cpp.
References eventTimer().
Referenced by Kb::frameRate().
                                {
    QTimer* timer = eventTimer();
    if(!timer)
        return;
    if(timer->isActive())
        timer->setInterval(1000 / framerate);
    else
        timer->start(1000 / framerate);
}
void KbManager::init (QStringguiVersion) [static]
Definition at line 12 of file kbmanager.cpp.
References _guiVersion, _kbManager, and KbManager().
Referenced by MainWindow::MainWindow().
                                      {
    _guiVersion = guiVersion;
    if(_kbManager)
        return;
    _kbManager = new KbManager();
}
void KbManager::kbConnected (Kb *device) [signal]
Definition at line 174 of file moc_kbmanager.cpp.
Referenced by scanKeyboards().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
void KbManager::kbDisconnected (Kb *device) [signal]
Definition at line 181 of file moc_kbmanager.cpp.
Referenced by scanKeyboards().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 1, _a);
}
static KbManager* KbManager::kbManager () [inline], [static]
Definition at line 23 of file kbmanager.h.
References _kbManager.
Referenced by MainWindow::MainWindow().
{ return _kbManager; }
float KbManager::parseVersionString (QStringversion) [static]
Definition at line 48 of file kbmanager.cpp.
Referenced by ckbDaemonVersionF(), ckbGuiVersionF(), and KbFirmware::processDownload().
                                                  {
    // Remove extraneous info (anything after a +, anything non-numeric)
    QStringList dots = version.replace(QRegExp("\+.+"), "").replace(QRegExp("[^\d\.]"), "").split(".");
    float base = 1.f;
    float res = 0.f;
    // A number like "1.2.3" will result in 1.0203
    // NB: will fail if a point version goes over 99 or if using more than two dots. floats can only reliably encode 7 decimal digits.
    foreach(const QString& dot, dots){
        res += dot.toFloat() * base;
        base /= 100.f;
    }
    return res;
}
void KbManager::scanKeyboards () [private], [slot]
Definition at line 62 of file kbmanager.cpp.
References _daemonVersion, _devices, _eventTimer, _scanTimer, DAEMON_UNAVAILABLE_STR, devpath, Kb::isOpen(), kbConnected(), kbDisconnected(), Kb::load(), Kb::matches(), Kb::save(), and versionUpdated().
Referenced by KbManager().
                             {
    QString rootdev = devpath.arg(0);
    QFile connected(rootdev + "/connected");
    if(!connected.open(QIODevice::ReadOnly)){
        // No root controller - remove all keyboards
        foreach(Kb* kb, _devices){
            emit kbDisconnected(kb);
            kb->save();
            delete kb;
        }
        _devices.clear();
        if(_daemonVersion != DAEMON_UNAVAILABLE_STR){
            _daemonVersion = DAEMON_UNAVAILABLE_STR;
            emit versionUpdated();
        }
        return;
    }
    // Check daemon version
    QFile version(rootdev + "/version");
    QString vString;
    if(version.open(QIODevice::ReadOnly)){
        vString = QString::fromUtf8(version.readLine()).trimmed();
        version.close();
    } else
        vString = DAEMON_UNAVAILABLE_STR;
    if(_daemonVersion != vString){
        _daemonVersion = vString;
        emit versionUpdated();
    }
    // Scan connected devices
    QList<QStringList> lines;
    while(1){
        QString line = connected.readLine().trimmed();
        if(line.isEmpty())
            break;
        QStringList components = line.split(" ");
        if(components.length() < 2) // "<path> <serial> <name>" (we're only interested in the first two)
            continue;
        lines.append(components);
    }
    connected.close();
    // Remove any active devices not in the list
    QMutableSetIterator<Kb*> i(_devices);
    while(i.hasNext()){
        Kb* kb = i.next();
        bool matched = false;
        foreach(const QStringList& line, lines){
            if(kb->matches(line[0], line[1])){
                matched = true;
                break;
            }
        }
        if(matched)
            continue;
        // Device not found, remove
        i.remove();
        emit kbDisconnected(kb);
        kb->save();
        delete kb;
    }
    // Add any new devices found in the list
    foreach(const QStringList& line, lines){
        bool matched = false;
        foreach(Kb* kb, _devices){
            if(kb->matches(line[0], line[1])){
                matched = true;
                break;
            }
        }
        if(matched)
            continue;
        // Device not found, create new
        Kb* kb = new Kb(this, line[0]);
        if(!kb->isOpen()){
            delete kb;
            continue;
        }
        _devices.insert(kb);
        // Load preferences and send signal
        emit kbConnected(kb);
        kb->load();
        connect(_eventTimer, SIGNAL(timeout()), kb, SLOT(frameUpdate()));
        connect(_scanTimer, SIGNAL(timeout()), kb, SLOT(autoSave()));
    }
}
static QTimer* KbManager::scanTimer () [inline], [static]
Definition at line 43 of file kbmanager.h.
References _kbManager, and _scanTimer.
Referenced by MainWindow::MainWindow().
{ return _kbManager ? _kbManager->_scanTimer : 0; }
void KbManager::stop () [static]
Definition at line 19 of file kbmanager.cpp.
References _kbManager.
Referenced by MainWindow::cleanup().
                    {
    if(!_kbManager)
        return;
    delete _kbManager;
    _kbManager = 0;
}
void KbManager::versionUpdated () [signal]
Definition at line 188 of file moc_kbmanager.cpp.
Referenced by scanKeyboards().
{
    QMetaObject::activate(this, &staticMetaObject, 2, Q_NULLPTR);
}
Field Documentation
QString KbManager::_daemonVersion = '<unavailable>' [static], [private]
Definition at line 59 of file kbmanager.h.
Referenced by ckbDaemonVersion(), ckbDaemonVersionF(), and scanKeyboards().
QSet<Kb*> KbManager::_devices [private]
Definition at line 63 of file kbmanager.h.
Referenced by devices(), and scanKeyboards().
QTimer* KbManager::_eventTimer [private]
Definition at line 64 of file kbmanager.h.
Referenced by eventTimer(), KbManager(), and scanKeyboards().
QString KbManager::_guiVersion [static], [private]
Definition at line 59 of file kbmanager.h.
Referenced by ckbGuiVersion(), ckbGuiVersionF(), and init().
KbManager * KbManager::_kbManager = 0 [static], [private]
Definition at line 58 of file kbmanager.h.
Referenced by devices(), eventTimer(), init(), kbManager(), scanTimer(), and stop().
QTimer * KbManager::_scanTimer [private]
Definition at line 64 of file kbmanager.h.
Referenced by KbManager(), scanKeyboards(), and scanTimer().
Author
Generated automatically by Doxygen for ckb-next from the source code.