.TH "src/ckb/kbprofiledialog.cpp" 3 "Sat Jan 20 2018" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbprofiledialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMenu>\fP
.br
\fC#include 'kbprofiledialog\&.h'\fP
.br
\fC#include 'ui_kbprofiledialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
