.TH "src/ckb/kbwidget.h" 3 "Sat Jan 20 2018" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFile>\fP
.br
\fC#include <QListWidgetItem>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include 'kb\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBKbWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
