KbWidget
NAME
KbWidget -
SYNOPSIS
#include <src/ckb/kbwidget.h>
Inherits QWidget.
Public Slots
void showFirstTab ()
void showLastTab ()
void showFwUpdate ()
Public Member Functions
KbWidget (QWidget *parent, Kb *_device)
~KbWidget ()
QString name () const
void updateFwButton ()
Data Fields
Kb * device
bool hasShownNewFW
Private Slots
void updateProfileList ()
void profileChanged ()
void on_profileBox_activated (int index)
QIcon modeIcon (int i)
void addNewModeItem ()
void modeChanged (bool spontaneous=true)
void on_modesList_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous)
void modesList_reordered ()
void on_modesList_itemChanged (QListWidgetItem *item)
void on_modesList_itemClicked (QListWidgetItem *item)
void on_modesList_customContextMenuRequested (const QPoint &pos)
KbWidget::on_modesList_customContextMenuRequested.
void devUpdate ()
void modeUpdate ()
void on_hwSaveButton_clicked ()
void on_tabWidget_currentChanged (int index)
void on_fwUpdButton_clicked ()
Private Attributes
Ui::KbWidget * ui
quint64 lastAutoSave
KbMode * currentMode
Static Private Attributes
static const int GUID = Qt::UserRole
static const int NEW_FLAG = Qt::UserRole + 1
Detailed Description
Definition at line 15 of file kbwidget.h.
Constructor & Destructor Documentation
KbWidget::KbWidget (QWidget *parent, Kb *_device) [explicit]
Definition at line 15 of file kbwidget.cpp.
References device, devUpdate(), Kb::features, Ui_KbWidget::fwUpdButton, Ui_KbWidget::fwUpdLabel, Ui_KbWidget::fwUpdLayout, Kb::isKeyboard(), Kb::isMouse(), Ui_KbWidget::kPerfTab, Ui_KbWidget::lightTab, Ui_KbWidget::lightWidget, modeChanged(), Ui_KbWidget::modesList, modesList_reordered(), Kb::monochrome, Ui_KbWidget::mPerfTab, Ui_KbWidget::pollLabel, Ui_KbWidget::pollLabel2, profileChanged(), KbLightWidget::setMonochrome(), Ui_KbWidget::setupUi(), Ui_KbWidget::tabWidget, ui, and updateProfileList().
                                               :
    QWidget(parent),
    device(_device), hasShownNewFW(false),
    ui(new Ui::KbWidget),
    currentMode(0)
{
    ui->setupUi(this);
    connect(ui->modesList, SIGNAL(orderChanged()), this, SLOT(modesList_reordered()));
    connect(device, SIGNAL(infoUpdated()), this, SLOT(devUpdate()));
    connect(device, SIGNAL(profileAdded()), this, SLOT(updateProfileList()));
    connect(device, SIGNAL(profileChanged()), this, SLOT(profileChanged()));
    connect(device, SIGNAL(profileRenamed()), this, SLOT(updateProfileList()));
    connect(device, SIGNAL(modeRenamed()), this, SLOT(profileChanged()));
    connect(device, SIGNAL(modeRenamed()), this, SLOT(modeChanged()));
    connect(device, SIGNAL(modeChanged(bool)), this, SLOT(modeChanged(bool)));
    // Remove the Lighting and Performance tabs from non-RGB keyboards
    if(!device->features.contains("rgb")){
        ui->tabWidget->removeTab(ui->tabWidget->indexOf(ui->lightTab));
        ui->tabWidget->removeTab(ui->tabWidget->indexOf(ui->kPerfTab));
        ui->tabWidget->removeTab(ui->tabWidget->indexOf(ui->mPerfTab));
    } else {
        // Remove mouse Performance tab from non-mice
        if(!device->isMouse())
            ui->tabWidget->removeTab(ui->tabWidget->indexOf(ui->mPerfTab));
        // Remove keyboard Performance tab from non-keyboards
        if(!device->isKeyboard())
            ui->tabWidget->removeTab(ui->tabWidget->indexOf(ui->kPerfTab));
    }
    // Hide poll rate and FW update as appropriate
    if(!device->features.contains("pollrate")){
        ui->pollLabel->hide();
        ui->pollLabel2->hide();
    }
    if(!device->features.contains("fwupdate")){
        ui->fwUpdButton->hide();
        ui->fwUpdLabel->hide();
        ui->fwUpdLayout->removeItem(ui->fwUpdLayout->itemAt(1));
    }
    // Set monochrome mode according to hardware
    if(device->monochrome)
        ui->lightWidget->setMonochrome();
}
KbWidget::~KbWidget ()
Definition at line 60 of file kbwidget.cpp.
References ui.
                   {
    delete ui;
}
Member Function Documentation
void KbWidget::addNewModeItem () [private], [slot]
Definition at line 136 of file kbwidget.cpp.
References Ui_KbWidget::modesList, NEW_FLAG, and ui.
Referenced by on_modesList_itemClicked(), and profileChanged().
                             {
    // Add an item for creating a new mode. Make it editable but not dragable.
    QListWidgetItem* item = new QListWidgetItem("New mode...", ui->modesList);
    item->setFlags((item->flags() | Qt::ItemIsEditable) & ~Qt::ItemIsDragEnabled & ~Qt::ItemIsDropEnabled);
    item->setData(NEW_FLAG, 1);
    QFont font = item->font();
    font.setItalic(true);
    item->setFont(font);
    item->setIcon(QIcon(":/img/icon_plus.png"));
    ui->modesList->addItem(item);
}
void KbWidget::devUpdate () [private], [slot]
Definition at line 300 of file kbwidget.cpp.
References device, Kb::firmware, Ui_KbWidget::fwLabel, Ui_KbWidget::pollLabel, Kb::pollrate, Ui_KbWidget::serialLabel, ui, and Kb::usbSerial.
Referenced by KbWidget().
                        {
    // Update device tab
    ui->serialLabel->setText(device->usbSerial);
    ui->fwLabel->setText(device->firmware);
    ui->pollLabel->setText(device->pollrate);
}
void KbWidget::modeChanged (boolspontaneous = true) [private], [slot]
Definition at line 148 of file kbwidget.cpp.
References Ui_KbWidget::bindWidget, Kb::currentBind(), Kb::currentLight(), currentMode, Kb::currentMode(), Kb::currentPerf(), Kb::currentProfile(), device, KbProfile::indexOf(), Ui_KbWidget::kPerfWidget, Ui_KbWidget::lightWidget, Ui_KbWidget::modesList, modeUpdate(), Ui_KbWidget::mPerfWidget, KbBindWidget::setBind(), KbLightWidget::setLight(), KPerfWidget::setPerf(), MPerfWidget::setPerf(), and ui.
Referenced by KbWidget(), and on_modesList_customContextMenuRequested().
                                          {
    int index = device->currentProfile()->indexOf(device->currentMode());
    if(index < 0)
        return;
    // Update tabs
    ui->lightWidget->setLight(device->currentLight());
    ui->bindWidget->setBind(device->currentBind(), device->currentProfile());
    ui->kPerfWidget->setPerf(device->currentPerf(), device->currentProfile());
    ui->mPerfWidget->setPerf(device->currentPerf(), device->currentProfile());
    // Update selection
    if(spontaneous)
        ui->modesList->setCurrentRow(index);
    // Connect signals
    if(currentMode)
        disconnect(currentMode, SIGNAL(updated()), this, SLOT(modeUpdate()));
    currentMode = device->currentMode();
    connect(currentMode, SIGNAL(updated()), this, SLOT(modeUpdate()));
    modeUpdate();
}
QIcon KbWidget::modeIcon (inti) [private], [slot]
Definition at line 127 of file kbwidget.cpp.
References Kb::currentProfile(), device, Kb::hwModeCount, and Kb::hwProfile().
Referenced by modesList_reordered(), and profileChanged().
                             {
    KbProfile* currentProfile = device->currentProfile(), *hwProfile = device->hwProfile();
    int hwModeCount = device->hwModeCount;
    if(i >= hwModeCount)
        return QIcon(":/img/icon_mode.png");
    else
        return QIcon(QString(currentProfile == hwProfile ? ":/img/icon_mode%1_hardware.png" : ":/img/icon_mode%1.png").arg(i + 1));
}
void KbWidget::modesList_reordered () [private], [slot]
Definition at line 177 of file kbwidget.cpp.
References Kb::currentProfile(), device, KbProfile::find(), GUID, modeIcon(), KbProfile::modes(), Ui_KbWidget::modesList, NEW_FLAG, and ui.
Referenced by KbWidget().
                                  {
    KbProfile* currentProfile = device->currentProfile();
    // Rebuild mode list from items
    QList<KbMode*> newModes;
    int count = ui->modesList->count();
    for(int i = 0; i < count; i++){
        QListWidgetItem* item = ui->modesList->item(i);
        KbMode* mode = currentProfile->find(item->data(GUID).toUuid());
        if(mode && !newModes.contains(mode))
            newModes.append(mode);
        if(item->data(NEW_FLAG).toInt() != 1)
            item->setIcon(modeIcon(i));
        item->setFlags(item->flags() | Qt::ItemIsEditable);
    }
    // Add any missing modes at the end of the list
    foreach(KbMode* mode, currentProfile->modes()){
        if(!newModes.contains(mode))
            newModes.append(mode);
    }
    currentProfile->modes(newModes);
}
void KbWidget::modeUpdate () [private], [slot]
Definition at line 307 of file kbwidget.cpp.
Referenced by modeChanged().
                         {
}
QString KbWidget::name () const [inline]
Definition at line 25 of file kbwidget.h.
References device, and Kb::usbModel.
Referenced by MainWindow::addDevice().
{ return device->usbModel; }
void KbWidget::on_fwUpdButton_clicked () [private], [slot]
Definition at line 339 of file kbwidget.cpp.
References device, FwUpgradeDialog::exec(), Kb::features, Kb::firmware, Ui_KbWidget::fwUpdButton, KbFirmware::hasDownloaded(), ui, updateFwButton(), and KbFirmware::versionForBoard().
Referenced by showFwUpdate().
                                     {
    // If alt is pressed, ignore upgrades and go straight to the manual prompt
    if(!(qApp->keyboardModifiers() & Qt::AltModifier)){
        // Check version numbers
        if(!KbFirmware::hasDownloaded()){
            ui->fwUpdButton->setText("Checking...");
            ui->fwUpdButton->setEnabled(false);
        }
        float newVersion = KbFirmware::versionForBoard(device->features, true);
        float oldVersion = device->firmware.toFloat();
        ui->fwUpdButton->setEnabled(true);
        updateFwButton();
        if(newVersion == -1.f){
            QMessageBox::information(this, "Firmware update", "<center>There is a new firmware available for this device.<br />However, it requires a newer version of ckb.<br />Please upgrade ckb and try again.</center>");
            return;
        } else if(newVersion == 0.f){
            if(QMessageBox::question(this, "Firmware update", "<center>There was a problem getting the status for this device.<br />Would you like to select a file manually?</center>") != QMessageBox::Yes)
                return;
            // "Yes" -> fall through to browse file
        } else if(newVersion <= oldVersion){
            if(QMessageBox::question(this, "Firmware update", "<center>Your firmware is already up to date.<br />Would you like to select a file manually?</center>") != QMessageBox::Yes)
                return;
            // "Yes" -> fall through to browse file
        } else {
            // Automatic upgrade. Fetch file from web.
            // FwUpgradeDialog can't be parented to KbWidget because KbWidget may be deleted before the dialog exits
            FwUpgradeDialog dialog(parentWidget(), newVersion, "", device);
            dialog.exec();
            return;
        }
    }
    // Browse for file
    QString path = QFileDialog::getOpenFileName(this, "Select firmware file", QStandardPaths::writableLocation(QStandardPaths::DownloadLocation), "Firmware blobs (*.bin)");
    if(path.isEmpty())
        return;
    QFile file(path);
    if(!file.open(QIODevice::ReadOnly)){
        QMessageBox::warning(parentWidget(), "Error", "<center>File could not be read.</center>");
        return;
    }
    QByteArray blob = file.readAll();
    FwUpgradeDialog dialog(parentWidget(), 0.f, blob, device);
    dialog.exec();
}
void KbWidget::on_hwSaveButton_clicked () [private], [slot]
Definition at line 310 of file kbwidget.cpp.
References device, Kb::hwSave(), profileChanged(), Kb::save(), and updateProfileList().
                                      {
    device->save();
    device->hwSave();
    updateProfileList();
    profileChanged();
}
void KbWidget::on_modesList_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous) [private], [slot]
Definition at line 168 of file kbwidget.cpp.
References Kb::currentProfile(), device, KbProfile::find(), GUID, and Kb::setCurrentMode().
                                                                                                 {
    if(!current)
        return;
    KbMode* mode = device->currentProfile()->find(current->data(GUID).toUuid());
    if(!mode)
        return;
    device->setCurrentMode(mode, false);
}
void KbWidget::on_modesList_customContextMenuRequested (const QPoint &pos) [private], [slot]
Parameters:
pos Opens on right click in the profiles list a context sensitive menue at position pos.
When clicking on a command it is located and executed.
Definition at line 236 of file kbwidget.cpp.
References currentMode, Kb::currentProfile(), device, UsbId::guid, GUID, Kb::hwModeCount, KbMode::id(), KbProfile::indexOf(), KbProfile::insert(), modeChanged(), KbProfile::modeCount(), KbProfile::modes(), Ui_KbWidget::modesList, KbMode::newId(), Kb::newMode(), profileChanged(), KbProfile::removeAll(), Kb::setCurrentMode(), and ui.
                                                                       {
    QListWidgetItem* item = ui->modesList->itemAt(pos);
    if(!item || !currentMode || item->data(GUID).toUuid() != currentMode->id().guid)
        return;
    KbProfile* currentProfile = device->currentProfile();
    int index = currentProfile->indexOf(currentMode);
    QMenu menu(this);
    QAction* rename = new QAction("Rename...", this);
    QAction* duplicate = new QAction("Duplicate", this);
    QAction* del = new QAction("Delete", this);
    bool canDelete = (device->currentProfile()->modeCount() > device->hwModeCount);
    if(!canDelete)
        // Can't delete modes if they're required by hardware
        del->setEnabled(false);
    QAction* moveup = new QAction("Move Up", this);
    if(index == 0)
        moveup->setEnabled(false);
    QAction* movedown = new QAction("Move Down", this);
    if(index >= currentProfile->modeCount() - 1)
        movedown->setEnabled(false);
    menu.addAction(rename);
    menu.addAction(duplicate);
    menu.addAction(del);
    menu.addSeparator();
    menu.addAction(moveup);
    menu.addAction(movedown);
    QAction* result = menu.exec(QCursor::pos());
    if(result == rename){
        ui->modesList->editItem(item);
    } else if(result == duplicate){
        KbMode* newMode = device->newMode(currentMode);
        newMode->newId();
        currentProfile->insert(index + 1, newMode);
        // Update UI
        profileChanged();
        device->setCurrentMode(newMode);
    } else if(result == del){
        if(!canDelete)
            return;
        currentProfile->removeAll(currentMode);
        currentMode->deleteLater();
        currentMode = 0;
        // Select next mode
        profileChanged();
        if(index < currentProfile->modeCount())
            device->setCurrentMode(currentProfile->modes()[index]);
        else
            device->setCurrentMode(currentProfile->modes().last());
    } else if(result == moveup){
        currentProfile->removeAll(currentMode);
        currentProfile->insert(index - 1, currentMode);
        // Update UI
        profileChanged();
        modeChanged(true);
    } else if(result == movedown){
        currentProfile->removeAll(currentMode);
        currentProfile->insert(index + 1, currentMode);
        // Update UI
        profileChanged();
        modeChanged(true);
    }
}
void KbWidget::on_modesList_itemChanged (QListWidgetItem *item) [private], [slot]
Definition at line 199 of file kbwidget.cpp.
References currentMode, UsbId::guid, GUID, KbMode::id(), and KbMode::name().
                                                            {
    if(!item || !currentMode || item->data(GUID).toUuid() != currentMode->id().guid)
        return;
    currentMode->name(item->text());
    // Set the text to the actual name (trimmed, "" replaced with "Unnamed")
    item->setText(currentMode->name());
}
void KbWidget::on_modesList_itemClicked (QListWidgetItem *item) [private], [slot]
Definition at line 207 of file kbwidget.cpp.
References addNewModeItem(), KbProfile::append(), Kb::currentProfile(), device, UsbId::guid, GUID, KbMode::id(), Ui_KbWidget::modesList, NEW_FLAG, Kb::newMode(), Kb::setCurrentMode(), and ui.
                                                            {
    QUuid guid = item->data(GUID).toUuid();
    if(guid.isNull() && item->data(NEW_FLAG).toInt() == 1){
        // "New mode" item. Clear text and start editing
        item->setText("");
        ui->modesList->editItem(item);
        item->setFlags(item->flags() | Qt::ItemIsEditable | Qt::ItemIsDragEnabled | Qt::ItemIsDropEnabled);
        QFont font = item->font();
        font.setItalic(false);
        item->setFont(font);
        item->setIcon(QIcon(":/img/icon_mode.png"));
        // Add the new mode and assign it to this item
        KbMode* newMode = device->newMode();
        device->currentProfile()->append(newMode);
        item->setData(GUID, newMode->id().guid);
        item->setData(NEW_FLAG, 0);
        device->setCurrentMode(newMode, false);
        // Create another "new mode" item to replace this one
        addNewModeItem();
    }
}
void KbWidget::on_profileBox_activated (intindex) [private], [slot]
Definition at line 113 of file kbwidget.cpp.
References device, Kb::profiles(), Kb::setCurrentProfile(), and updateProfileList().
                                               {
    if(index < 0)
        return;
    if(index >= device->profiles().count()){
        // "Manage profiles" option
        KbProfileDialog dialog(this);
        dialog.exec();
        updateProfileList();
        return;
    }
    device->setCurrentProfile(device->profiles()[index]);
    // Device will emit profileChanged() and modeChanged() signals to update UI
}
void KbWidget::on_tabWidget_currentChanged (intindex) [private], [slot]
Definition at line 317 of file kbwidget.cpp.
References device, Ui_KbWidget::tabWidget, ui, and updateFwButton().
                                                   {
    if(!device)
        return;
    if(index == ui->tabWidget->count() - 1){
        // Device tab
        updateFwButton();
    }
}
void KbWidget::profileChanged () [private], [slot]
Definition at line 91 of file kbwidget.cpp.
References addNewModeItem(), current, currentMode, Kb::currentProfile(), device, UsbId::guid, GUID, KbMode::id(), modeIcon(), KbProfile::modes(), Ui_KbWidget::modesList, KbMode::name(), and ui.
Referenced by KbWidget(), on_hwSaveButton_clicked(), and on_modesList_customContextMenuRequested().
                             {
    // Rebuild mode list
    ui->modesList->clear();
    int i = 0;
    QListWidgetItem* current = 0;
    foreach(KbMode* mode, device->currentProfile()->modes()){
        QListWidgetItem* item = new QListWidgetItem(modeIcon(i), mode->name(), ui->modesList);
        item->setData(GUID, mode->id().guid);
        item->setFlags(item->flags() | Qt::ItemIsEditable);
        if(mode == currentMode){
            item->setSelected(true);
            current = item;
        }
        ui->modesList->addItem(item);
        i++;
    }
    if(current)
        ui->modesList->setCurrentItem(current);
    addNewModeItem();
    // Wait for modeChanged() to refresh the rest of the UI
}
void KbWidget::showFirstTab () [slot]
Definition at line 64 of file kbwidget.cpp.
References Ui_KbWidget::tabWidget, and ui.
                           {
    ui->tabWidget->setCurrentIndex(0);
}
void KbWidget::showFwUpdate () [inline], [slot]
Definition at line 38 of file kbwidget.h.
References on_fwUpdButton_clicked().
Referenced by MainWindow::showFwUpdateNotification().
{ on_fwUpdButton_clicked(); }
void KbWidget::showLastTab () [slot]
Definition at line 68 of file kbwidget.cpp.
References Ui_KbWidget::tabWidget, and ui.
Referenced by MainWindow::showFwUpdateNotification().
                          {
    ui->tabWidget->setCurrentIndex(ui->tabWidget->count() - 1);
}
void KbWidget::updateFwButton ()
Definition at line 326 of file kbwidget.cpp.
References device, Kb::features, Kb::firmware, Ui_KbWidget::fwUpdButton, KbFirmware::hasDownloaded(), ui, and KbFirmware::versionForBoard().
Referenced by MainWindow::checkFwUpdates(), on_fwUpdButton_clicked(), and on_tabWidget_currentChanged().
                             {
    if(!KbFirmware::hasDownloaded())
        ui->fwUpdButton->setText("Check for updates");
    else {
        float newVersion = KbFirmware::versionForBoard(device->features);
        float oldVersion = device->firmware.toFloat();
        if(newVersion <= 0.f || newVersion <= oldVersion)
            ui->fwUpdButton->setText("Up to date");
        else
            ui->fwUpdButton->setText(tr("Upgrade to v%1").arg(QString::number(newVersion, 'f', 2)));
    }
}
void KbWidget::updateProfileList () [private], [slot]
Definition at line 73 of file kbwidget.cpp.
References Kb::currentProfile(), device, Kb::hwProfile(), KbProfile::name(), Ui_KbWidget::profileBox, Kb::profiles(), and ui.
Referenced by KbWidget(), on_hwSaveButton_clicked(), and on_profileBox_activated().
                                {
    // Clear profile list and rebuild
    KbProfile* hwProfile = device->hwProfile(), *currentProfile = device->currentProfile();
    ui->profileBox->clear();
    int i = 0;
    foreach(KbProfile* profile, device->profiles()){
        ui->profileBox->addItem((profile == hwProfile) ? QIcon(":/img/icon_profile_hardware.png") : QIcon(":/img/icon_profile.png"),
                                profile->name());
        if(profile == currentProfile)
            ui->profileBox->setCurrentIndex(i);
        i++;
    }
    ui->profileBox->addItem(QIcon(":/img/icon_blank.png"), "Manage profiles...");
    QFont font = ui->profileBox->font();
    font.setItalic(true);
    ui->profileBox->setItemData(ui->profileBox->count() - 1, font, Qt::FontRole);
}
Field Documentation
KbMode* KbWidget::currentMode [private]
Definition at line 44 of file kbwidget.h.
Referenced by modeChanged(), on_modesList_customContextMenuRequested(), on_modesList_itemChanged(), and profileChanged().
Kb* KbWidget::device
Definition at line 24 of file kbwidget.h.
Referenced by MainWindow::addDevice(), MainWindow::checkFwUpdates(), devUpdate(), KbWidget(), modeChanged(), modeIcon(), modesList_reordered(), name(), on_fwUpdButton_clicked(), on_hwSaveButton_clicked(), on_modesList_currentItemChanged(), on_modesList_customContextMenuRequested(), on_modesList_itemClicked(), on_profileBox_activated(), on_tabWidget_currentChanged(), profileChanged(), MainWindow::removeDevice(), MainWindow::showFwUpdateNotification(), updateFwButton(), and updateProfileList().
const int KbWidget::GUID = Qt::UserRole [static], [private]
Definition at line 46 of file kbwidget.h.
Referenced by modesList_reordered(), on_modesList_currentItemChanged(), on_modesList_customContextMenuRequested(), on_modesList_itemChanged(), on_modesList_itemClicked(), and profileChanged().
bool KbWidget::hasShownNewFW
Definition at line 28 of file kbwidget.h.
Referenced by MainWindow::checkFwUpdates().
quint64 KbWidget::lastAutoSave [private]
Definition at line 42 of file kbwidget.h.
const int KbWidget::NEW_FLAG = Qt::UserRole + 1 [static], [private]
Definition at line 47 of file kbwidget.h.
Referenced by addNewModeItem(), modesList_reordered(), and on_modesList_itemClicked().
Ui::KbWidget* KbWidget::ui [private]
Definition at line 41 of file kbwidget.h.
Referenced by addNewModeItem(), devUpdate(), KbWidget(), modeChanged(), modesList_reordered(), on_fwUpdButton_clicked(), on_modesList_customContextMenuRequested(), on_modesList_itemClicked(), on_tabWidget_currentChanged(), profileChanged(), showFirstTab(), showLastTab(), updateFwButton(), updateProfileList(), and ~KbWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.