KeyAction
NAME
KeyAction -
SYNOPSIS
#include <src/ckb/keyaction.h>
Inherits QObject.
Public Types
enum Type { UNBOUND, NORMAL, SPECIAL }
Public Member Functions
KeyAction (const QString &action, QObject *parent=0)
QString value () const
operator QString () const
KeyAction (QObject *parent=0)
QString friendlyName (const KeyMap &map) const
QString driverName () const
QString macroFullLine () const
macroFullLine If a macro command and a macro definition exists for the given key, returns the complete string except the leading '$' (the $ may confuse some caller).
bool isValidMacro () const
isValidMacro checks whether a keyAction contains a valid macro. This is done easily: If the macro action starts with $macro: and has five elements, delimited by ':', we may assume, that is a structural correct macro action. If it has 4 entries only, it is an older definition and ok also.
QStringList macroLine () const
macroLine returns all interresting content for a macro definition.
QString macroContent () const
macroContent returns the macro key definition only (the second part of the macro action).
QString macroTiming () const
macroTiming returns the macro key definition with original timing infos (the fifth and up to now last part of the macro action). If the implementation does not know anything about delays and has no 5th part, return first part.
void macroDisplay ()
Debug output for invalid macro Definitions.
Type type () const
bool isUnbound () const
bool isNormal () const
bool isSpecial () const
bool isMedia () const
bool isProgram () const
bool isAnim () const
bool isMacro () const
bool isDPI () const
bool isMouse () const
QString specialInfo (int &parameter) const
int programInfo (QString &onPress, QString &onRelease) const
int dpiInfo (QPoint &custom) const
QUuid animInfo (bool &onlyOnce, bool &stopOnRelease) const
void keyEvent (KbBind *bind, bool down)
void keyRelease (KbBind *bind)
void adjustDisplay ()
~KeyAction ()
Static Public Member Functions
static QString noAction ()
static QString defaultAction (const QString &key, KeyMap::Model model)
static QString modeAction (int mode)
static QString dpiAction (int level, int customX=0, int customY=0)
static QString lightAction (int type=LIGHT_UP_WRAP)
static QString lockAction (int type=LOCK_TOGGLE)
static QString programAction (const QString &onPress, const QString &onRelease, int stop)
static QString animAction (const QUuid &guid, bool onlyOnce, bool stopOnRelease)
static QString macroAction (QString macroDef)
well documented in cpp file
Static Public Attributes
static const int MODE_PREV = -2
static const int MODE_NEXT = -1
static const int MODE_PREV_WRAP = -4
static const int MODE_NEXT_WRAP = -3
static const int DPI_CYCLE_UP = -4
static const int DPI_CYCLE_DOWN = -3
static const int DPI_UP = -2
static const int DPI_DOWN = -1
static const int DPI_SNIPER = 0
static const int DPI_CUSTOM = 6
static const int LIGHT_UP = 0
static const int LIGHT_DOWN = 1
static const int LIGHT_UP_WRAP = 2
static const int LIGHT_DOWN_WRAP = 3
static const int LOCK_TOGGLE = 0
static const int LOCK_ON = 1
static const int LOCK_OFF = 2
static const int PROGRAM_PR_MULTI = 0x04
static const int PROGRAM_PR_INDEF = 0x00
static const int PROGRAM_PR_KRSTOP = 0x01
static const int PROGRAM_PR_KPSTOP = 0x02
static const int PROGRAM_RE_MULTI = 0x40
static const int PROGRAM_RE_INDEF = 0x00
static const int PROGRAM_RE_KPSTOP = 0x20
Private Member Functions
void operator= (const KeyAction &rhs)
ccMSC: Don't copy key actions (the old one needs to be deleted first) frickler24: statement left as described, but copying is done in KbBind copy constructor
KeyAction (const KeyAction &rhs)
Private Attributes
QString _value
QProcess * preProgram
QProcess * relProgram
quint64 sniperValue
Detailed Description
Definition at line 13 of file keyaction.h.
Member Enumeration Documentation
enum KeyAction::Type
Enumerator
UNBOUND
NORMAL
SPECIAL
Definition at line 146 of file keyaction.h.
              {
        UNBOUND,
        NORMAL,
        SPECIAL,
    };
Constructor & Destructor Documentation
KeyAction::KeyAction (const QString &action, QObject *parent = 0)
Definition at line 22 of file keyaction.cpp.
    : QObject(parent), _value(action), preProgram(0), relProgram(0), sniperValue(0)
{
}
KeyAction::KeyAction (QObject *parent = 0) [explicit]
Definition at line 27 of file keyaction.cpp.
    : QObject(parent), _value(""), preProgram(0), relProgram(0), sniperValue(0)
{
}
KeyAction::~KeyAction ()
Definition at line 32 of file keyaction.cpp.
References preProgram, and relProgram.
                     {
    // Clean up processes
    if(preProgram){
        preProgram->kill();
        delete preProgram;
    }
    if(relProgram){
        relProgram->kill();
        delete relProgram;
    }
}
KeyAction::KeyAction (const KeyAction &rhs) [inline], [private]
Definition at line 187 of file keyaction.h.
: QObject() {}
Member Function Documentation
void KeyAction::adjustDisplay ()
Definition at line 464 of file keyaction.cpp.
Referenced by keyEvent().
                             {
#ifdef USE_LIBX11
    // Try to get the current display from the X server
    char* display_name = XDisplayName(NULL);
    if(!display_name)
        return;
    Display* display = XOpenDisplay(display_name);
    if(!display)
        return;
    char* display_string = DisplayString(display);
    if(!display_string || strlen(display_string) == 0){
        XCloseDisplay(display);
        return;
    }
    size_t envstr_size = strlen(display_string) + 4;
    char* envstr = new char[envstr_size];
    strncpy(envstr, display_string, envstr_size);
    envstr[envstr_size - 1] = 0;
    Window root_window = XRootWindow(display, DefaultScreen(display));
    Window root_window_ret, child_window_ret, window;
    XWindowAttributes attr;
    int root_x, root_y, win_x, win_y;
    unsigned int mask_ret;
    // Find the screen which currently has the mouse
    XQueryPointer(display, root_window, &root_window_ret, &child_window_ret, &root_x, &root_y, &win_x, &win_y, &mask_ret);
    if(child_window_ret == (Window)NULL)
        window = root_window_ret;
    else
        window = child_window_ret;
    XGetWindowAttributes(display, window, &attr);
    char* ptr = strchr(envstr, ':');
    if(ptr){
        ptr = strchr(ptr, '.');
        if(ptr)
            *ptr = '\0';
        char buf[16];
        snprintf(buf, sizeof(buf), ".%i", XScreenNumberOfScreen(attr.screen));
        strncat(envstr, buf, envstr_size - 1 - strlen(envstr));
        // Update environment variable
        setenv("DISPLAY", envstr, 1);
    }
    delete[] envstr;
    XCloseDisplay(display);
#endif
}
QString KeyAction::animAction (const QUuid &guid, boolonlyOnce, boolstopOnRelease) [static]
Definition at line 184 of file keyaction.cpp.
References ANIM_KRSTOP, and ANIM_ONCE.
Referenced by RebindWidget::applyChanges().
                                                                                 {
    int flags = (onlyOnce ? ANIM_ONCE : 0) | (stopOnRelease ? ANIM_KRSTOP : 0);
    return "$anim:" + guid.toString() + QString("+%1").arg(flags);
}
QUuid KeyAction::animInfo (bool &onlyOnce, bool &stopOnRelease) const
Definition at line 225 of file keyaction.cpp.
References _value, ANIM_KRSTOP, ANIM_ONCE, and isAnim().
Referenced by keyEvent(), and RebindWidget::setSelection().
                                                                   {
    if(!isAnim())
        return QUuid();
    QString param = _value.mid(6);
    QStringList split = param.split("+");
    if(split.length() < 2)
        return QUuid();
    QUuid id = split[0];
    int flags = split[1].toInt();
    onlyOnce = !!(flags & ANIM_ONCE);
    stopOnRelease = !!(flags & ANIM_KRSTOP);
    return id;
}
QString KeyAction::defaultAction (const QString &key, KeyMap::Modelmodel) [static]
Definition at line 44 of file keyaction.cpp.
References KeyMap::GLAIVE, and KeyMap::HARPOON.
Referenced by KbBind::bindAction(), KbBind::defaultAction(), and KbBind::save().
                                                                     {
    // G1-G18 are unbound by default
    if(key.length() >= 2 && key[0] == 'g'
        && ((key.length() == 2 && key[1] >= '0' && key[1] <= '9')
        || (key.length() == 3 && key[1] == '1' && key[2] >= '0' && key[2] <= '8')))
        return "";
    // So are thumbgrid buttons
    if(key.startsWith("thumb"))
        return "";
    // TODO: default action for MR
    if(key == "mr")
        return "";
    // M1-M3 switch modes
    if(key == "m1")
        return "$mode:0";
    if(key == "m2")
        return "$mode:1";
    if(key == "m3")
        return "$mode:2";
    // Brightness and Win Lock are their own functions
    if(key == "light")
        return "$light:2";
    if(key == "lock")
        return "$lock:0";
    // DPI buttons
    if(key == "dpiup"){
        if(model == KeyMap::HARPOON ||
       model == KeyMap::GLAIVE){
        return "$dpi:-4";
        }
    return "$dpi:-2";
    }
    if(key == "dpidn")
        return "$dpi:-1";
    if(key == "sniper")
        return "$dpi:0";
    // Everything else is a standard keypress
    return key;
}
QString KeyAction::dpiAction (intlevel, intcustomX = 0, intcustomY = 0) [static]
Definition at line 162 of file keyaction.cpp.
References DPI_CUSTOM.
Referenced by RebindWidget::applyChanges().
                                                               {
    QString action = tr("$dpi:%1").arg(level);
    if(level == DPI_CUSTOM)
        action += tr("+%1+%2").arg(customX).arg(customY);
    return action;
}
int KeyAction::dpiInfo (QPoint &custom) const
Definition at line 211 of file keyaction.cpp.
References _value, DPI_CUSTOM, and isDPI().
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
                                           {
    if(!isDPI())
        return 0;
    QString param = _value.mid(5);
    QStringList lxy = param.split("+");
    int level = lxy[0].toInt();
    if(level == DPI_CUSTOM){
        if(lxy.length() != 3)
            return 0;
        custom = QPoint(lxy[1].toInt(), lxy[2].toInt());
    }
    return level;
}
QString KeyAction::driverName () const
Definition at line 239 of file keyaction.cpp.
References _value, and isSpecial().
Referenced by KbBind::update().
                                    {
    if(isSpecial())
        return "";
    return _value;
}
QString KeyAction::friendlyName (const KeyMap &map) const
Definition at line 84 of file keyaction.cpp.
References _value, DPI_CUSTOM, DPI_CYCLE_DOWN, DPI_CYCLE_UP, DPI_DOWN, DPI_SNIPER, DPI_UP, dpiInfo(), KeyMap::friendlyName(), KeyMap::layout(), LIGHT_DOWN, LIGHT_DOWN_WRAP, LIGHT_UP, LIGHT_UP_WRAP, LOCK_OFF, LOCK_ON, LOCK_TOGGLE, MODE_NEXT, MODE_NEXT_WRAP, MODE_PREV, and MODE_PREV_WRAP.
                                                       {
    if(_value.isEmpty())
        return "Unbound";
    QStringList parts = _value.split(":");
    QString prefix = parts[0];
    if(parts.length() < 2){
        KeyMap::Layout layout = map.layout();
        QString name = KeyMap::friendlyName(_value, layout);
        if(name.isEmpty())
            return "(Unknown)";
        return name;
    }
    int suffix = parts[1].toInt();
    if(prefix == "$mode"){
        switch(suffix){
        case MODE_PREV:
        case MODE_PREV_WRAP:
            return "Switch to previous mode";
        case MODE_NEXT:
        case MODE_NEXT_WRAP:
            return "Switch to next mode";
        default:
            return tr("Switch to mode %1").arg(suffix + 1);
        }
    } else if(prefix == "$dpi"){
        // Split off custom parameters (if any)
        int level = parts[1].split("+")[0].toInt();
        switch(level){
        case DPI_CYCLE_UP:
            return "DPI cycle up";
        case DPI_CYCLE_DOWN:
            return "DPI cycle down";
        case DPI_UP:
            return "DPI up";
        case DPI_DOWN:
            return "DPI down";
        case DPI_SNIPER:
            return "Sniper";
        case DPI_CUSTOM:{
            QPoint xy;
            dpiInfo(xy);
            return tr("DPI: %1, %2").arg(xy.x()).arg(xy.y());
        }
        default:
            return tr("DPI stage %1").arg(level);
        }
    } else if(prefix == "$light"){
        switch(suffix){
        case LIGHT_UP:
        case LIGHT_UP_WRAP:
            return "Brightness up";
        case LIGHT_DOWN:
        case LIGHT_DOWN_WRAP:
            return "Brightness down";
        }
    } else if(prefix == "$lock"){
        switch(suffix){
        case LOCK_TOGGLE:
            return "Toggle Windows lock";
        case LOCK_ON:
            return "Windows lock on";
        case LOCK_OFF:
            return "Windows lock off";
        }
    } else if(prefix == "$anim"){
        return "Start animation";
    } else if(prefix == "$program"){
        return "Launch program";
    } else if(prefix == "$macro"){
        return "Send G-key macro";
    }
    return "(Unknown)";
}
bool KeyAction::isAnim () const [inline]
Definition at line 159 of file keyaction.h.
References _value.
Referenced by animInfo(), and RebindWidget::setSelection().
{ return _value.startsWith("$anim:"); }
bool KeyAction::isDPI () const [inline]
Definition at line 162 of file keyaction.h.
References _value.
Referenced by dpiInfo(), isMouse(), and RebindWidget::setSelection().
{ return _value.startsWith("$dpi:"); }
bool KeyAction::isMacro () const [inline]
Definition at line 160 of file keyaction.h.
References _value.
Referenced by isValidMacro(), macroDisplay(), and macroFullLine().
{ return _value.startsWith("$macro:"); }
bool KeyAction::isMedia () const [inline]
Definition at line 156 of file keyaction.h.
References _value.
{ return _value == "mute" || _value == "volup" || _value == "voldn" || _value == "stop" || _value == "prev" || _value == "play" || _value == "next"; }
bool KeyAction::isMouse () const [inline]
Definition at line 163 of file keyaction.h.
References _value, isDPI(), and isNormal().
Referenced by RebindWidget::setSelection().
{ return (isNormal() && (_value.startsWith("mouse") || _value.startsWith("wheel"))) || isDPI(); }
bool KeyAction::isNormal () const [inline]
Definition at line 153 of file keyaction.h.
References NORMAL, and type().
Referenced by isMouse(), and RebindWidget::setSelection().
{ return type() == NORMAL; }
bool KeyAction::isProgram () const [inline]
Definition at line 158 of file keyaction.h.
References _value.
Referenced by programInfo(), and RebindWidget::setSelection().
{ return _value.startsWith("$program:"); }
bool KeyAction::isSpecial () const [inline]
Definition at line 154 of file keyaction.h.
References SPECIAL, and type().
Referenced by driverName(), keyEvent(), and RebindWidget::setSelection().
{ return type() == SPECIAL; }
bool KeyAction::isUnbound () const [inline]
Definition at line 152 of file keyaction.h.
References type(), and UNBOUND.
{ return type() == UNBOUND; }
bool KeyAction::isValidMacro () const [inline]
Returns:
bool as true iff the macro definition contains all four elements.
Definition at line 55 of file keyaction.h.
References _value, and isMacro().
Referenced by macroContent(), macroDisplay(), macroLine(), macroTiming(), RebindWidget::setSelection(), and KbBind::update().
                                      {
        if (isMacro()) {
            QStringList ret;
            ret =_value.split(":");
            return ((ret.count() >= 4) && (ret.count() <= 5));
        } else {
            return false;
        }
    }
void KeyAction::keyEvent (KbBind *bind, booldown)
Definition at line 245 of file keyaction.cpp.
References _value, adjustDisplay(), anim, animInfo(), KbPerf::baseDpiIdx(), KbProfile::currentMode(), Kb::currentProfile(), KbBind::devParent(), KbLight::dimming(), KbPerf::DPI_COUNT, DPI_CUSTOM, DPI_CYCLE_DOWN, DPI_CYCLE_UP, DPI_DOWN, DPI_SNIPER, DPI_UP, KbPerf::dpiCycleDown(), KbPerf::dpiCycleUp(), KbPerf::dpiDown(), dpiInfo(), KbPerf::dpiUp(), KbLight::findAnim(), KbProfile::indexOf(), KbAnim::isActive(), isSpecial(), KbBind::light(), LIGHT_DOWN, LIGHT_DOWN_WRAP, LIGHT_UP, LIGHT_UP_WRAP, LOCK_OFF, LOCK_ON, LOCK_TOGGLE, KbLight::MAX_DIM, MODE_NEXT, MODE_NEXT_WRAP, MODE_PREV, MODE_PREV_WRAP, KbProfile::modeCount(), KbProfile::modes(), KbBind::perf(), KbPerf::popDpi(), preProgram, PROGRAM_PR_KPSTOP, PROGRAM_PR_KRSTOP, PROGRAM_PR_MULTI, PROGRAM_RE_KPSTOP, PROGRAM_RE_MULTI, programInfo(), KbPerf::pushDpi(), KbPerf::pushSniper(), relProgram, Kb::setCurrentMode(), sniperValue, KbAnim::stop(), KbAnim::trigger(), and KbBind::winLock().
Referenced by KbBind::keyEvent().
                                               {
    // No need to respond to standard actions
    if(!isSpecial())
        return;
    QStringList parts = _value.split(":");
    if(parts.length() < 2)
        return;
    QString prefix = parts[0];
    int suffix = parts[1].toInt();
    if(prefix == "$mode"){
        if(!down)
            return;
        // Change mode
        Kb* device = bind->devParent();
        KbProfile* currentProfile = device->currentProfile();
        int mode = currentProfile->indexOf(currentProfile->currentMode());
        int modeCount = currentProfile->modeCount();
        switch(suffix){
        case MODE_PREV_WRAP:
            mode--;
            if(mode < 0)
                mode = modeCount - 1;
            break;
        case MODE_NEXT_WRAP:
            mode++;
            if(mode >= modeCount)
                mode = 0;
            break;
        case MODE_PREV:
            mode--;
            break;
        case MODE_NEXT:
            mode++;
            break;
        default:
            // Absolute
            mode = suffix;
            break;
        }
        if(mode < 0 || mode >= modeCount)
            return;
        device->setCurrentMode(currentProfile->modes()[mode]);
    } else if(prefix == "$dpi"){
        KbPerf* perf = bind->perf();
        int level = parts[1].split("+")[0].toInt();
        switch(level){
        case DPI_CYCLE_UP:
            if(!down)
                return;
            perf->dpiCycleUp();
            break;
        case DPI_CYCLE_DOWN:
            if(!down)
                return;
            perf->dpiCycleDown();
            break;
        case DPI_UP:
            if(!down)
                return;
            perf->dpiUp();
            break;
        case DPI_DOWN:
            if(!down)
                return;
            perf->dpiDown();
            break;
        case DPI_SNIPER:
            if(down)
                sniperValue = perf->pushSniper();
            else {
                perf->popDpi(sniperValue);
                sniperValue = 0;
            }
            break;
        case DPI_CUSTOM:{
            QPoint xy;
            dpiInfo(xy);
            if(xy.x() <= 0 || xy.y() <= 0)
                break;
            if(down)
                sniperValue = perf->pushDpi(xy);
            else {
                perf->popDpi(sniperValue);
                sniperValue = 0;
            }
            break;
        }
        default:
            if(level < 1 || level >= KbPerf::DPI_COUNT
                    || !down)
                return;
            perf->baseDpiIdx(level);
            break;
        }
    } else if(prefix == "$light"){
        if(!down)
            return;
        // Change brightness
        KbLight* light = bind->light();
        int dim = light->dimming();
        switch(suffix){
        case LIGHT_UP:
            if(dim > 0)
                dim--;
            break;
        case LIGHT_DOWN:
            if(dim < KbLight::MAX_DIM)
                dim++;
            break;
        case LIGHT_UP_WRAP:
            dim--;
            if(dim < 0)
                dim = KbLight::MAX_DIM;
            break;
        case LIGHT_DOWN_WRAP:
            dim++;
            if(dim > KbLight::MAX_DIM)
                dim = 0;
            break;
        }
        light->dimming(dim);
    } else if(prefix == "$lock"){
        if(!down)
            return;
        // Change win lock
        switch(suffix){
        case LOCK_TOGGLE:
            bind->winLock(!bind->winLock());
            break;
        case LOCK_ON:
            bind->winLock(true);
            break;
        case LOCK_OFF:
            bind->winLock(false);
            break;
        }
    } else if(prefix == "$anim"){
        // Start animation
        bool onlyOnce = false, stopOnRelease = false;
        QUuid id = animInfo(onlyOnce, stopOnRelease);
        KbAnim* anim = bind->light()->findAnim(id);
        if(!anim)
            return;
        if(down){
            if(!onlyOnce || !anim->isActive())
                // If "only once" is enabled, don't start the animation when it's already running
                anim->trigger(QDateTime::currentMSecsSinceEpoch(), true);
        } else if(stopOnRelease){
            // Key released - stop animation
            anim->stop();
        }
    } else if(prefix == "$program"){
        // Launch program
        QString onPress, onRelease;
        int stop = programInfo(onPress, onRelease);
        // Stop running programs based on setting
        QProcess* process = 0;
        if(down){
            if(stop & PROGRAM_PR_KPSTOP){
                process = preProgram;
                if(process)
                    process->kill();
                process = 0;
            }
            if(stop & PROGRAM_RE_KPSTOP)
                process = relProgram;
        } else {
            if(stop & PROGRAM_PR_KRSTOP)
                process = preProgram;
        }
        if(process)
            process->kill();
        // Launch new process if requested
        QString& program = down ? onPress : onRelease;
        if(program.isEmpty())
            return;
        // Check if the program is running already. If so, don't start it again.
        process = down ? preProgram : relProgram;
        if(process){
            if(process->state() == QProcess::NotRunning)
                delete process;
            else
                return;
        }
        // Adjust the selected display.
        adjustDisplay();
        // Start the program. Wrap it around sh to parse arguments.
        if((down && (stop & PROGRAM_PR_MULTI))
                || (!down && (stop & PROGRAM_RE_MULTI))){
            // Multiple instances allowed? Start detached process
            QProcess::startDetached("sh", QStringList() << "-c" << program);
        } else {
            process = new QProcess(this);
            process->start("sh", QStringList() << "-c" << program);
            if(down)
                preProgram = process;
            else
                relProgram = process;
        }
    } else if (prefix == "$macro") {
        // Do nothing, because all work is done by the keyboard itself.
        // For now, there is no reason to react on G-key press or release.
        // If u find some reason, then here is the place for it.
    }
}
void KeyAction::keyRelease (KbBind *bind)
QString KeyAction::lightAction (inttype = LIGHT_UP_WRAP) [static]
Definition at line 169 of file keyaction.cpp.
Referenced by RebindWidget::applyChanges().
                                      {
    return QString("$light:%1").arg(type);
}
QString KeyAction::lockAction (inttype = LOCK_TOGGLE) [static]
Definition at line 173 of file keyaction.cpp.
Referenced by RebindWidget::applyChanges().
                                     {
    return QString("$lock:%1").arg(type);
}
QString KeyAction::macroAction (QStringmacroDef) [static]
KeyAction::macroAction is called when applying changes on a macro definition. macroAction ist called while being in the macro pane and clicking Apply with something in the Macro Text Box. It tags that input with '$macro:' for further recognition.
Parameters:
macroDef holds the String containing parts 2-5 of a complete macro definition.
Returns:
QString holding the complete G-Key macro definition (parts 1-5)
Definition at line 523 of file keyaction.cpp.
Referenced by RebindWidget::applyChanges().
                                               {
    return QString ("$macro:%1").arg(macroDef);
}
QString KeyAction::macroContent () const [inline]
Returns:
QString macroContent
Definition at line 86 of file keyaction.h.
References _value, and isValidMacro().
Referenced by RebindWidget::setSelection(), and KbBind::update().
                                        {
        // return isValidMacro() ? _value.split(":")[1].replace(QRegExp("=\d+"), "") : ""; ///< Is used if we have ckb without delay handling
        return isValidMacro() ? _value.split(":")[1] : "";
    }
void KeyAction::macroDisplay ()
KeyAction::macroDisplay is just for debugging. It shows the content of the key action and some other info.
General Info on KeyAction::_value for macros: That string consists of 4 elements, all delimited by ':'.
1.
Macro command indicator '$macro:'
2.
Macro Key Definition (coming from pteMacroBox): This sequence will program the keyboard and is hardly readable
3.
Readable Macro String: This is displayed in pteMacroText
4.
Readable Macro Comment:This is displayed in pteMacroComment
5.
completely unreadable original macro information with timing values
Definition at line 456 of file keyaction.cpp.
References _value, isMacro(), and isValidMacro().
Referenced by RebindWidget::setSelection().
                             {
    qDebug() << "isMacro returns" << (isMacro() ? "true" : "false");
    qDebug() << "isValidMacro returns" << (isValidMacro() ? "true" : "false");
    QStringList ret =_value.split(":");
    qDebug() << "Macro definition conains" << ret.count() << "elements";
    qDebug() << "Macro definition is" << _value;
}
QString KeyAction::macroFullLine () const [inline]
Returns:
QString All 5 parts are returned in one QString. If no definition exists, return ''
Definition at line 43 of file keyaction.h.
References _value, and isMacro().
                                         {
        return isMacro() ? _value.right(_value.length()-1) : "";
    }
QStringList KeyAction::macroLine () const [inline]
Returns:
QStringList returns the Macro Key Definition, Readble Macro String, Readable Macro Comment and the original timing information (if it exists as a 5th part) as QStringList.
Definition at line 73 of file keyaction.h.
References _value, and isValidMacro().
Referenced by RebindWidget::setSelection().
                                         {
        if (isValidMacro()) {
            QStringList ret =_value.split(":");
            ret.removeFirst();
            return ret;
        } else return QStringList();
    }
QString KeyAction::macroTiming () const [inline]
Returns:
QString macroTiming
Definition at line 98 of file keyaction.h.
References _value, and isValidMacro().
Referenced by RebindWidget::setSelection().
                                       {
        if (isValidMacro()) {
            QStringList rval = _value.split(":");
            return (rval.length() == 4)? rval[1] : rval[4];
        }
        return QString("");
    }
QString KeyAction::modeAction (intmode) [static]
Definition at line 158 of file keyaction.cpp.
Referenced by RebindWidget::applyChanges().
                                     {
    return QString("$mode:%1").arg(mode);
}
static QString KeyAction::noAction () [inline], [static]
Definition at line 25 of file keyaction.h.
{ return ""; }
KeyAction::operator QString () const [inline]
Definition at line 20 of file keyaction.h.
References _value.
{ return _value; }
void KeyAction::operator= (const KeyAction &rhs) [inline], [private]
Definition at line 186 of file keyaction.h.
{}
QString KeyAction::programAction (const QString &onPress, const QString &onRelease, intstop) [static]
Definition at line 177 of file keyaction.cpp.
Referenced by RebindWidget::applyChanges().
                                                                                          {
    // URL-encode the commands and place them in the string (":" and "+" are both replaced, so they won't interfere)
    return "$program:" + QString::fromUtf8(QUrl::toPercentEncoding(onPress.trimmed())) + "+" + QString::fromUtf8(QUrl::toPercentEncoding(onRelease.trimmed())) + QString("+%1").arg(stop);
}
int KeyAction::programInfo (QString &onPress, QString &onRelease) const
Definition at line 199 of file keyaction.cpp.
References _value, and isProgram().
Referenced by keyEvent(), and RebindWidget::setSelection().
                                                                     {
    if(!isProgram())
        return 0;
    QString param = _value.mid(9);
    QStringList programs = param.split("+");
    if(programs.length() != 3)
        return 0;
    onPress = QUrl::fromPercentEncoding(programs[0].toUtf8());
    onRelease = QUrl::fromPercentEncoding(programs[1].toUtf8());
    return programs[2].toInt();
}
QString KeyAction::specialInfo (int &parameter) const
Definition at line 189 of file keyaction.cpp.
References _value.
Referenced by RebindWidget::setSelection().
                                                   {
    QStringList list = _value.split(":");
    if(list.length() < 2){
        parameter = INT_MIN;
        return "";
    }
    parameter = list[1].toInt();
    return list[0].replace("$", "");
}
KeyAction::Type KeyAction::type () const
Definition at line 14 of file keyaction.cpp.
References _value, NORMAL, SPECIAL, and UNBOUND.
Referenced by isNormal(), isSpecial(), isUnbound(), KbBindWidget::on_copyButton_clicked(), and KbBindWidget::on_resetButton_clicked().
                                    {
    if(_value.isEmpty())
        return UNBOUND;
    if(_value.at(0) == '$')
        return SPECIAL;
    return NORMAL;
}
QString KeyAction::value () const [inline]
Definition at line 19 of file keyaction.h.
References _value.
Referenced by KbBind::action(), KbBind::KbBind(), KbBind::save(), and KbBind::update().
{ return _value; }
Field Documentation
QString KeyAction::_value [private]
Definition at line 189 of file keyaction.h.
Referenced by animInfo(), dpiInfo(), driverName(), friendlyName(), isAnim(), isDPI(), isMacro(), isMedia(), isMouse(), isProgram(), isValidMacro(), keyEvent(), macroContent(), macroDisplay(), macroFullLine(), macroLine(), macroTiming(), operator QString(), programInfo(), specialInfo(), type(), and value().
const int KeyAction::DPI_CUSTOM = 6 [static]
Definition at line 128 of file keyaction.h.
Referenced by dpiAction(), dpiInfo(), friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::DPI_CYCLE_DOWN = -3 [static]
Definition at line 126 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::DPI_CYCLE_UP = -4 [static]
Definition at line 126 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::DPI_DOWN = -1 [static]
Definition at line 127 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::DPI_SNIPER = 0 [static]
Definition at line 128 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::DPI_UP = -2 [static]
Definition at line 127 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::LIGHT_DOWN = 1 [static]
Definition at line 131 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::LIGHT_DOWN_WRAP = 3 [static]
Definition at line 132 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::LIGHT_UP = 0 [static]
Definition at line 131 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::LIGHT_UP_WRAP = 2 [static]
Definition at line 132 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::LOCK_OFF = 2 [static]
Definition at line 135 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::LOCK_ON = 1 [static]
Definition at line 135 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::LOCK_TOGGLE = 0 [static]
Definition at line 135 of file keyaction.h.
Referenced by friendlyName(), and keyEvent().
const int KeyAction::MODE_NEXT = -1 [static]
Definition at line 122 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::MODE_NEXT_WRAP = -3 [static]
Definition at line 123 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::MODE_PREV = -2 [static]
Definition at line 122 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::MODE_PREV_WRAP = -4 [static]
Definition at line 123 of file keyaction.h.
Referenced by friendlyName(), keyEvent(), and RebindWidget::setSelection().
QProcess* KeyAction::preProgram [private]
Definition at line 192 of file keyaction.h.
Referenced by keyEvent(), and ~KeyAction().
const int KeyAction::PROGRAM_PR_INDEF = 0x00 [static]
Definition at line 138 of file keyaction.h.
const int KeyAction::PROGRAM_PR_KPSTOP = 0x02 [static]
Definition at line 138 of file keyaction.h.
Referenced by keyEvent().
const int KeyAction::PROGRAM_PR_KRSTOP = 0x01 [static]
Definition at line 138 of file keyaction.h.
Referenced by keyEvent().
const int KeyAction::PROGRAM_PR_MULTI = 0x04 [static]
Definition at line 138 of file keyaction.h.
Referenced by RebindWidget::applyChanges(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::PROGRAM_RE_INDEF = 0x00 [static]
Definition at line 139 of file keyaction.h.
Referenced by RebindWidget::applyChanges(), and RebindWidget::setSelection().
const int KeyAction::PROGRAM_RE_KPSTOP = 0x20 [static]
Definition at line 139 of file keyaction.h.
Referenced by RebindWidget::applyChanges(), keyEvent(), and RebindWidget::setSelection().
const int KeyAction::PROGRAM_RE_MULTI = 0x40 [static]
Definition at line 139 of file keyaction.h.
Referenced by RebindWidget::applyChanges(), keyEvent(), and RebindWidget::setSelection().
QProcess* KeyAction::relProgram [private]
Definition at line 193 of file keyaction.h.
Referenced by keyEvent(), and ~KeyAction().
quint64 KeyAction::sniperValue [private]
Definition at line 196 of file keyaction.h.
Referenced by keyEvent().
Author
Generated automatically by Doxygen for ckb-next from the source code.