src/ckb/keywidget.cpp
NAME
src/ckb/keywidget.cpp -
SYNOPSIS
#include <cmath>
#include <QGraphicsDropShadowEffect>
#include <QGraphicsPixmapItem>
#include <QGraphicsScene>
#include <QPainter>
#include 'keywidget.h'
#include 'keyaction.h'
#include 'kbbind.h'
Functions
QRgb monoRgb (float r, float g, float b)
Variables
static const int KEY_SIZE = 12
static QImage * m65Overlay = 0
static QImage * sabOverlay = 0
static QImage * scimOverlay = 0
Function Documentation
QRgb monoRgb (floatr, floatg, floatb)
Definition at line 284 of file kblight.cpp.
References lToS(), and sToL().
Referenced by KbLight::base(), KbLight::frameUpdate(), and KeyWidget::paintEvent().
                                       {
    // It's important to use a linear colorspace for this, otherwise the colors will appear inconsistent
    // Note that although we could use linear space for alpha blending or the animation blending functions, we don't.
    // The reason for this is that photo manipulation programs don't do it either, so even though the result would technically be more correct,
    // it would look wrong to most people.
    r = sToL(r);
    g = sToL(g);
    b = sToL(b);
    int value = round(lToS((r + g + b) / 3.f));
    return qRgb(value, value, value);
}
Variable Documentation
const int KEY_SIZE = 12 [static]
Definition at line 10 of file keywidget.cpp.
Referenced by KeyWidget::drawInfo(), and KeyWidget::map().
QImage* m65Overlay = 0 [static]
Definition at line 12 of file keywidget.cpp.
Referenced by KeyWidget::paintEvent().
QImage * sabOverlay = 0 [static]
Definition at line 12 of file keywidget.cpp.
Referenced by KeyWidget::paintEvent().
QImage * scimOverlay = 0 [static]
Definition at line 12 of file keywidget.cpp.
Referenced by KeyWidget::paintEvent().
Author
Generated automatically by Doxygen for ckb-next from the source code.