.TH "src/ckb/layoutdialog.cpp" 3 "Thu Nov 2 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/layoutdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'layoutdialog\&.h'\fP
.br
\fC#include 'kb\&.h'\fP
.br
\fC#include 'ui_layoutdialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
