MainWindow
NAME
MainWindow -
SYNOPSIS
#include <src/ckb/mainwindow.h>
Inherits QMainWindow.
Public Slots
void showWindow ()
void stateChange (Qt::ApplicationState state)
void quitApp ()
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
void toggleTrayIcon (bool visible)
Static Public Attributes
static MainWindow * mainWindow = 0
Private Slots
void addDevice (Kb *device)
void removeDevice (Kb *device)
void updateVersion ()
void checkFwUpdates ()
void timerTick ()
void iconClicked (QSystemTrayIcon::ActivationReason reason)
void cleanup ()
void showFwUpdateNotification (QWidget *widget, float version)
Private Member Functions
void closeEvent (QCloseEvent *event)
Private Attributes
SettingsWidget * settingsWidget
QList< KbWidget * > kbWidgets
QAction * restoreAction
QAction * closeAction
QMenu * trayIconMenu
QSystemTrayIcon * trayIcon
Ui::MainWindow * ui
Detailed Description
Definition at line 27 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget *parent = 0) [explicit]
Definition at line 49 of file mainwindow.cpp.
References Ui_MainWindow::actionExit, addDevice(), cleanup(), closeAction, configLabel, daemonDialogText, devpath, CkbSettings::get(), iconClicked(), KbManager::init(), KbManager::kbManager(), mainWindow, quitApp(), removeDevice(), restoreAction, KbManager::scanTimer(), SettingsWidget::setStatus(), settingsWidget, Ui_MainWindow::setupUi(), SettingsWidget::setVersion(), showWindow(), stateChange(), Ui_MainWindow::tabWidget, timerTick(), toggleTrayIcon(), trayIcon, trayIconMenu, ui, and updateVersion().
                                      :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    mainWindow = this;
    // Start device manager
    KbManager::init(CKB_VERSION_STR);
    connect(KbManager::kbManager(), SIGNAL(kbConnected(Kb*)), this, SLOT(addDevice(Kb*)));
    connect(KbManager::kbManager(), SIGNAL(kbDisconnected(Kb*)), this, SLOT(removeDevice(Kb*)));
    connect(KbManager::kbManager(), SIGNAL(versionUpdated()), this, SLOT(updateVersion()));
    connect(KbManager::scanTimer(), SIGNAL(timeout()), this, SLOT(timerTick()));
    // Set up tray icon
    restoreAction = new QAction(tr("Restore"), this);
    closeAction = new QAction(tr("Quit ckb"), this);
#ifdef USE_LIBAPPINDICATOR
    QString desktop = std::getenv("XDG_CURRENT_DESKTOP");
    unityDesktop = (desktop.toLower() == "unity");
    if(unityDesktop){
        trayIcon = 0;
        indicatorMenu = gtk_menu_new();
        indicatorMenuRestoreItem = gtk_menu_item_new_with_label("Restore");
        indicatorMenuQuitItem = gtk_menu_item_new_with_label("Quit ckb");
        gtk_menu_shell_append(GTK_MENU_SHELL(indicatorMenu), indicatorMenuRestoreItem);
        gtk_menu_shell_append(GTK_MENU_SHELL(indicatorMenu), indicatorMenuQuitItem);
        g_signal_connect(indicatorMenuQuitItem, "activate",
            G_CALLBACK(quitIndicator), this);
        g_signal_connect(indicatorMenuRestoreItem, "activate",
            G_CALLBACK(restoreIndicator), this);
        gtk_widget_show(indicatorMenuRestoreItem);
        gtk_widget_show(indicatorMenuQuitItem);
        indicator = app_indicator_new("ckb", "indicator-messages", APP_INDICATOR_CATEGORY_APPLICATION_STATUS);
        app_indicator_set_status(indicator, APP_INDICATOR_STATUS_ACTIVE);
        app_indicator_set_menu(indicator, GTK_MENU(indicatorMenu));
        app_indicator_set_icon(indicator, "ckb");
    } else
#endif // USE_LIBAPPINDICATOR
    {
        trayIconMenu = new QMenu(this);
        trayIconMenu->addAction(restoreAction);
        trayIconMenu->addAction(closeAction);
        trayIcon = new QSystemTrayIcon(QIcon(":/img/ckb-logo.png"), this);
        trayIcon->setContextMenu(trayIconMenu);
        connect(trayIcon, SIGNAL(activated(QSystemTrayIcon::ActivationReason)), this, SLOT(iconClicked(QSystemTrayIcon::ActivationReason)));
     }
     toggleTrayIcon(!CkbSettings::get("Program/SuppressTrayIcon").toBool());
#ifdef Q_OS_MACX
    // Make a custom "Close" menu action for OSX, as the default one brings up the "still running" popup unnecessarily
    QMenuBar* menuBar = new QMenuBar(this);
    setMenuBar(menuBar);
    this->menuBar()->addMenu("ckb")->addAction(closeAction);
#else
    // On linux, add a handler for Ctrl+Q
    new QShortcut(QKeySequence("Ctrl+Q"), this, SLOT(quitApp()));
#endif
    connect(ui->actionExit, SIGNAL(triggered()), this, SLOT(quitApp()));
    connect(closeAction, SIGNAL(triggered()), this, SLOT(quitApp()));
    connect(restoreAction, SIGNAL(triggered()), this, SLOT(showWindow()));
    connect(qApp, SIGNAL(applicationStateChanged(Qt::ApplicationState)), this, SLOT(stateChange(Qt::ApplicationState)));
    connect(qApp, SIGNAL(aboutToQuit()), this, SLOT(cleanup()));
    ui->tabWidget->addTab(settingsWidget = new SettingsWidget(this), configLabel);
    settingsWidget->setVersion("ckb-next " CKB_VERSION_STR);
    // create daemon dialog as a QMessageBox
    // this will create a focussed dialog, that has to be interacted with,
    // if the daemon is not running
    // set the main and informative text to tell the user about the issue
    QMessageBox dialog;
    dialog.setText(tr("The ckb-next daemon is not running. This program will <b>not</b> work without it!"));
    dialog.setInformativeText(daemonDialogText);
    dialog.setIcon(QMessageBox::Critical);
    // check, whether daemon is running
    // the daemon creates the root device path on initialization and thus it
    // can be assumed, that the daemon is not running if doesn't exist
    // `.arg(0)` is necessary to interpolate the correct suffix into the path
    // see `./kbmanager.cpp` for details
    QFileInfo rootDevPath(devpath.arg(0));
    if (!rootDevPath.exists()) {
        // set settings widget's status
        // show the main window (otherwise only the dialog will be visible)
        // finally show the dialog
        settingsWidget->setStatus(tr("The ckb-next daemon is not running."));
        showWindow();
        dialog.exec();
    }
}
MainWindow::~MainWindow ()
Definition at line 341 of file mainwindow.cpp.
References cleanup(), and ui.
                       {
    cleanup();
    delete ui;
}
Member Function Documentation
void MainWindow::addDevice (Kb *device) [private], [slot]
Definition at line 159 of file mainwindow.cpp.
References KbWidget::device, kbWidgets, KbWidget::name(), Ui_MainWindow::tabWidget, ui, and updateVersion().
Referenced by MainWindow().
                                    {
    // Connected already?
    foreach(KbWidget* w, kbWidgets){
        if(w->device == device)
            return;
    }
    // Add the keyboard
    KbWidget* widget = new KbWidget(this, device);
    kbWidgets.append(widget);
    // Add to tabber; switch to this device if the user is on the settings screen
    int count = ui->tabWidget->count();
    ui->tabWidget->insertTab(count - 1, widget, widget->name());
    if(ui->tabWidget->currentIndex() == count)
        ui->tabWidget->setCurrentIndex(count - 1);
    // Update connected device count
    updateVersion();
}
void MainWindow::checkFwUpdates () [private], [slot]
Definition at line 210 of file mainwindow.cpp.
References KbWidget::device, Kb::features, Kb::firmware, KbWidget::hasShownNewFW, kbWidgets, mainWindow, KbWidget::updateFwButton(), and KbFirmware::versionForBoard().
Referenced by timerTick().
                               {
    if(!mainWindow->isVisible())
        return;
    foreach(KbWidget* w, kbWidgets){
        // Display firmware upgrade notification if a new version is available
        float version = KbFirmware::versionForBoard(w->device->features);
        if(version > w->device->firmware.toFloat()){
            if(w->hasShownNewFW)
                continue;
            w->hasShownNewFW = true;
            w->updateFwButton();
            // Don't run this method here because it will lock up the timer and prevent devices from working properly
            // Use a queued invocation instead
            metaObject()->invokeMethod(this, "showFwUpdateNotification", Qt::QueuedConnection, Q_ARG(QWidget*, w), Q_ARG(float, version));
            // Don't display more than one of these at once
            return;
        }
    }
}
void MainWindow::cleanup () [private], [slot]
Definition at line 333 of file mainwindow.cpp.
References CkbSettings::cleanUp(), kbWidgets, and KbManager::stop().
Referenced by MainWindow(), and ~MainWindow().
                        {
    foreach(KbWidget* w, kbWidgets)
        delete w;
    kbWidgets.clear();
    KbManager::stop();
    CkbSettings::cleanUp();
}
void MainWindow::closeEvent (QCloseEvent *event) [private]
Definition at line 247 of file mainwindow.cpp.
References CkbSettings::get(), and CkbSettings::set().
                                             {
    // If the window is hidden already or the event is non-spontaneous (can happen on OSX when using the Quit menu), accept it and close
    if(!event->spontaneous() || isHidden()){
        event->accept();
        return;
    }
    if(!CkbSettings::get("Popups/BGWarning").toBool()){
        QMessageBox::information(this, "ckb", "ckb will still run in the background.\nTo close it, choose Exit from the tray menu\nor click \"Quit ckb\" on the Settings screen.");
        CkbSettings::set("Popups/BGWarning", true);
    }
    hide();
    event->ignore();
}
void MainWindow::iconClicked (QSystemTrayIcon::ActivationReasonreason) [private], [slot]
Definition at line 295 of file mainwindow.cpp.
References showWindow().
Referenced by MainWindow().
                                                                  {
    // On Linux, hide/show the app when the tray icon is clicked
    // On OSX this just shows the menu
#ifndef Q_OS_MACX
    if(reason == QSystemTrayIcon::DoubleClick || reason == QSystemTrayIcon::Trigger){
        if(isVisible())
            hide();
        else
            showWindow();
    }
#endif
}
void MainWindow::quitApp () [slot]
Definition at line 329 of file mainwindow.cpp.
Referenced by MainWindow().
                        {
    qApp->quit();
}
void MainWindow::removeDevice (Kb *device) [private], [slot]
Definition at line 177 of file mainwindow.cpp.
References KbWidget::device, kbWidgets, Ui_MainWindow::tabWidget, ui, and updateVersion().
Referenced by MainWindow().
                                       {
    foreach(KbWidget* w, kbWidgets){
        // Remove this device from the UI
        if(w->device == device){
            int i = kbWidgets.indexOf(w);
            ui->tabWidget->removeTab(i);
            kbWidgets.removeAt(i);
            w->deleteLater();
        }
    }
    // Update connected device count
    updateVersion();
}
void MainWindow::showFwUpdateNotification (QWidget *widget, floatversion) [private], [slot]
Definition at line 230 of file mainwindow.cpp.
References KbWidget::device, kbWidgets, KbWidget::showFwUpdate(), KbWidget::showLastTab(), showWindow(), Ui_MainWindow::tabWidget, ui, and Kb::usbModel.
                                                                       {
    static bool isShowing = false;
    if(isShowing)
        return;
    isShowing = true;
    showWindow();
    KbWidget* w = (KbWidget*)widget;
    // Ask for update
    if(QMessageBox::information(this, "Firmware update", tr("A new firmware is available for your %1 (v%2)\nWould you like to install it now?").arg(w->device->usbModel, QString::number(version, 'f', 2)), QMessageBox::StandardButtons(QMessageBox::Yes | QMessageBox::No), QMessageBox::Yes) == QMessageBox::Yes){
        // If accepted, switch to the firmware tab and bring up the update window
        w->showLastTab();
        ui->tabWidget->setCurrentIndex(kbWidgets.indexOf(w));
        w->showFwUpdate();
    }
    isShowing = false;
}
void MainWindow::showWindow () [slot]
Definition at line 308 of file mainwindow.cpp.
Referenced by iconClicked(), MainWindow(), showFwUpdateNotification(), stateChange(), and timerTick().
                           {
    showNormal();
    raise();
    activateWindow();
}
void MainWindow::stateChange (Qt::ApplicationStatestate) [slot]
Definition at line 314 of file mainwindow.cpp.
References showWindow().
Referenced by MainWindow().
                                                    {
    // On OSX it's possible for the app to be brought to the foreground without the window actually reappearing.
    // We want to make sure it's shown when this happens.
#ifdef Q_OS_MAC
    static quint64 lastStateChange = 0;
    quint64 now = QDateTime::currentMSecsSinceEpoch();
    if(state == Qt::ApplicationActive){
        // This happens once at startup so ignore it. Also don't allow it to be called more than once every 2s.
        if(lastStateChange != 0 && now >= lastStateChange + 2 * 1000)
            showWindow();
        lastStateChange = now;
    }
#endif
}
void MainWindow::timerTick () [private], [slot]
Definition at line 261 of file mainwindow.cpp.
References appShare, checkFwUpdates(), KbFirmware::checkUpdates(), CkbSettings::get(), SettingsWidget::pollUpdates(), settingsWidget, and showWindow().
Referenced by MainWindow().
                          {
    // Check shared memory for changes
    if(appShare.lock()){
        void* data = appShare.data();
        QStringList commands = QString((const char*)data).split("\n");
        // Restore PID, remove all other data
        snprintf((char*)appShare.data(), appShare.size(), "PID %ld", (long)getpid());
        appShare.unlock();
        // Parse commands
        foreach(const QString& line, commands){
            // Old ckb option line - bring application to foreground
            if(line == "Open")
                showWindow();
            if(line.startsWith("Option ")){
                // New ckb option line
                QString option = line.split(" ")[1];
                if(option == "Open")
                    // Bring to foreground
                    showWindow();
                else if(option == "Close")
                    // Quit application
                    qApp->quit();
            }
        }
    }
    // Check for firmware updates (when appropriate)
    if(!CkbSettings::get("Program/DisableAutoFWCheck").toBool()){
        KbFirmware::checkUpdates();
        checkFwUpdates();
    }
    // Poll for setting updates
    settingsWidget->pollUpdates();
}
void MainWindow::toggleTrayIcon (boolvisible)
Definition at line 150 of file mainwindow.cpp.
References trayIcon.
Referenced by MainWindow(), and ExtraSettingsWidget::on_trayBox_clicked().
                                            {
#ifdef USE_LIBAPPINDICATOR
    if(unityDesktop)
        app_indicator_set_status(indicator, visible ? APP_INDICATOR_STATUS_ACTIVE : APP_INDICATOR_STATUS_PASSIVE);
    else
#endif // USE_LIBAPPINDICATOR
        trayIcon->setVisible(visible);
}
void MainWindow::updateVersion () [private], [slot]
Definition at line 191 of file mainwindow.cpp.
References KbManager::ckbDaemonVersion(), KbManager::ckbDaemonVersionF(), KbManager::ckbGuiVersionF(), DAEMON_UNAVAILABLE_STR, kbWidgets, SettingsWidget::setStatus(), and settingsWidget.
Referenced by addDevice(), MainWindow(), and removeDevice().
                              {
    QString daemonVersion = KbManager::ckbDaemonVersion();
    if(daemonVersion == DAEMON_UNAVAILABLE_STR){
        settingsWidget->setStatus("Driver inactive");
        return;
    }
    int count = kbWidgets.count();
    // Warn if the daemon version doesn't match the GUI
    QString daemonWarning;
    if(daemonVersion != CKB_VERSION_STR)
        daemonWarning = "<br /><br /><b>Warning:</b> Driver version mismatch (" + daemonVersion + "). Please upgrade ckb" + QString(KbManager::ckbDaemonVersionF() > KbManager::ckbGuiVersionF() ? "" : "-daemon") + ". If the problem persists, try rebooting.";
    if(count == 0)
        settingsWidget->setStatus("No devices connected" + daemonWarning);
    else if(count == 1)
        settingsWidget->setStatus("1 device connected" + daemonWarning);
    else
        settingsWidget->setStatus(QString("%1 devices connected").arg(count) + daemonWarning);
}
Field Documentation
QAction* MainWindow::closeAction [private]
Definition at line 44 of file mainwindow.h.
Referenced by MainWindow().
QList<KbWidget*> MainWindow::kbWidgets [private]
Definition at line 41 of file mainwindow.h.
Referenced by addDevice(), checkFwUpdates(), cleanup(), removeDevice(), showFwUpdateNotification(), and updateVersion().
MainWindow * MainWindow::mainWindow = 0 [static]
Definition at line 35 of file mainwindow.h.
Referenced by checkFwUpdates(), MainWindow(), and ExtraSettingsWidget::on_trayBox_clicked().
QAction* MainWindow::restoreAction [private]
Definition at line 43 of file mainwindow.h.
Referenced by MainWindow().
SettingsWidget* MainWindow::settingsWidget [private]
Definition at line 40 of file mainwindow.h.
Referenced by MainWindow(), timerTick(), and updateVersion().
QSystemTrayIcon* MainWindow::trayIcon [private]
Definition at line 54 of file mainwindow.h.
Referenced by MainWindow(), and toggleTrayIcon().
QMenu* MainWindow::trayIconMenu [private]
Definition at line 53 of file mainwindow.h.
Referenced by MainWindow().
Ui::MainWindow* MainWindow::ui [private]
Definition at line 75 of file mainwindow.h.
Referenced by addDevice(), MainWindow(), removeDevice(), showFwUpdateNotification(), and ~MainWindow().
Author
Generated automatically by Doxygen for ckb-next from the source code.