ModeSelectDialog
NAME
ModeSelectDialog -
SYNOPSIS
#include <src/ckb/modeselectdialog.h>
Inherits QDialog.
Public Member Functions
ModeSelectDialog (QWidget *parent, KbMode *currentMode, QList< KbMode * > modeList, const QString &textLabel)
~ModeSelectDialog ()
QList< KbMode * > selection ()
Private Slots
void on_selAllButton_clicked ()
void on_selNoneButton_clicked ()
Private Attributes
Ui::ModeSelectDialog * ui
QList< KbMode * > _modeList
Detailed Description
Definition at line 13 of file modeselectdialog.h.
Constructor & Destructor Documentation
ModeSelectDialog::ModeSelectDialog (QWidget *parent, KbMode *currentMode, QList< KbMode * >modeList, const QString &textLabel)
Definition at line 4 of file modeselectdialog.cpp.
References _modeList, Ui_ModeSelectDialog::label, Ui_ModeSelectDialog::modeList, KbMode::name(), Ui_ModeSelectDialog::setupUi(), and ui.
                                                                                                                          :
    QDialog(parent), ui(new Ui::ModeSelectDialog),
    _modeList(modeList)
{
    ui->setupUi(this);
    _modeList.removeAll(currentMode);
    ui->label->setText(textLabel);
    // Populate list
    foreach(KbMode* mode, _modeList)
        ui->modeList->addItem(mode->name());
}
ModeSelectDialog::~ModeSelectDialog ()
Definition at line 16 of file modeselectdialog.cpp.
References ui.
                                   {
    delete ui;
}
Member Function Documentation
void ModeSelectDialog::on_selAllButton_clicked () [private], [slot]
Definition at line 30 of file modeselectdialog.cpp.
References Ui_ModeSelectDialog::modeList, and ui.
                                              {
    int count = ui->modeList->count();
    for(int i = 0; i < count; i++)
        ui->modeList->item(i)->setSelected(true);
}
void ModeSelectDialog::on_selNoneButton_clicked () [private], [slot]
Definition at line 36 of file modeselectdialog.cpp.
References Ui_ModeSelectDialog::modeList, and ui.
                                               {
    int count = ui->modeList->count();
    for(int i = 0; i < count; i++)
        ui->modeList->item(i)->setSelected(false);
}
QList< KbMode * > ModeSelectDialog::selection ()
Definition at line 20 of file modeselectdialog.cpp.
References _modeList, Ui_ModeSelectDialog::modeList, and ui.
Referenced by KbBindWidget::on_copyButton_clicked(), KPerfWidget::on_copyButton_clicked(), and MPerfWidget::on_copyButton_clicked().
                                          {
    QList<KbMode*> res;
    int count = ui->modeList->count();
    for(int i = 0; i < count; i++){
        if(ui->modeList->item(i)->isSelected())
            res.append(_modeList[i]);
    }
    return res;
}
Field Documentation
QList<KbMode*> ModeSelectDialog::_modeList [private]
Definition at line 31 of file modeselectdialog.h.
Referenced by ModeSelectDialog(), and selection().
Ui::ModeSelectDialog* ModeSelectDialog::ui [private]
Definition at line 30 of file modeselectdialog.h.
Referenced by ModeSelectDialog(), on_selAllButton_clicked(), on_selNoneButton_clicked(), selection(), and ~ModeSelectDialog().
Author
Generated automatically by Doxygen for ckb-next from the source code.