.TH "src/ckb/mperfwidget.h" 3 "Tue May 16 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/mperfwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QSlider>\fP
.br
\fC#include <QSpinBox>\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QRadioButton>\fP
.br
\fC#include <QSignalMapper>\fP
.br
\fC#include 'kbperf\&.h'\fP
.br
\fC#include 'kbprofile\&.h'\fP
.br
\fC#include 'colorbutton\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMPerfWidget\fP"
.br
.ti -1c
.RI "struct \fBMPerfWidget::DpiUi\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct MPerfWidget::DpiUi"
.PP 
Definition at line 37 of file mperfwidget\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
QCheckBox * \fIenableCheck\fP 
.br
.PP
\fBColorButton\fP * \fIindicator\fP 
.br
.PP
QSpinBox * \fIxBox\fP 
.br
.PP
QSlider * \fIxSlider\fP 
.br
.PP
QSpinBox * \fIyBox\fP 
.br
.PP
QSlider * \fIySlider\fP 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
