src/ckb-daemon/profile.h
NAME
src/ckb-daemon/profile.h -
SYNOPSIS
#include 'includes.h'
#include 'device.h'
Macros
#define hwloadprofile(kb, apply) (kb)->vtable->hwload(kb, 0, 0, apply, 0)
Functions
void allocprofile (usbdevice *kb)
int loadprofile (usbdevice *kb)
void freeprofile (usbdevice *kb)
void cmd_erase (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *dummy3)
void cmd_eraseprofile (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *dummy4)
void cmd_name (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *name)
void cmd_profilename (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *name)
char * getmodename (usbmode *mode)
char * getprofilename (usbprofile *profile)
char * gethwmodename (hwprofile *profile, int index)
char * gethwprofilename (hwprofile *profile)
int setid (usbid *id, const char *guid)
char * getid (usbid *id)
void hwtonative (usbprofile *profile, hwprofile *hw, int modecount)
void nativetohw (usbprofile *profile, hwprofile *hw, int modecount)
void cmd_id (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *id)
void cmd_profileid (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *id)
int cmd_hwload_kb (usbdevice *kb, usbmode *dummy1, int dummy2, int apply, const char *dummy3)
int cmd_hwload_mouse (usbdevice *kb, usbmode *dummy1, int dummy2, int apply, const char *dummy3)
int cmd_hwsave_kb (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *dummy4)
int cmd_hwsave_mouse (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *dummy4)
Macro Definition Documentation
#define hwloadprofile(kb, apply) (kb)->vtable->hwload(kb, 0, 0, apply, 0)
Definition at line 52 of file profile.h.
Referenced by _start_dev(), and loadprofile().
Function Documentation
void allocprofile (usbdevice *kb)
Definition at line 198 of file profile.c.
References usbprofile::currentmode, dpiset::forceupdate, lighting::forceupdate, initmode(), usbprofile::lastdpi, usbprofile::lastlight, usbprofile::mode, MODE_COUNT, and usbdevice::profile.
Referenced by cmd_eraseprofile().
                                {
    if(kb->profile)
        return;
    usbprofile* profile = kb->profile = calloc(1, sizeof(usbprofile));
    for(int i = 0; i < MODE_COUNT; i++)
        initmode(profile->mode + i);
    profile->currentmode = profile->mode;
    profile->lastlight.forceupdate = profile->lastdpi.forceupdate = 1;
}
void cmd_erase (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *dummy3)
Definition at line 219 of file profile.c.
References freemode(), imutex, and initmode().
                                                                                        {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    pthread_mutex_lock(imutex(kb));
    freemode(mode);
    initmode(mode);
    pthread_mutex_unlock(imutex(kb));
}
void cmd_eraseprofile (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *dummy4)
Definition at line 241 of file profile.c.
References _freeprofile(), allocprofile(), and imutex.
                                                                                                 {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    (void)dummy4;
    pthread_mutex_lock(imutex(kb));
    _freeprofile(kb);
    allocprofile(kb);
    pthread_mutex_unlock(imutex(kb));
}
int cmd_hwload_kb (usbdevice *kb, usbmode *dummy1, intdummy2, intapply, const char *dummy3)
Definition at line 16 of file profile_keyboard.c.
References DELAY_LONG, usbdevice::hw, hwloadmode(), HWMODE_K70, HWMODE_K95, hwtonative(), hwprofile::id, IS_K95, MSG_SIZE, hwprofile::name, PR_NAME_LEN, usbdevice::profile, and usbrecv.
                                                                                            {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    DELAY_LONG(kb);
    hwprofile* hw = calloc(1, sizeof(hwprofile));
    // Ask for profile and mode IDs
    uchar data_pkt[2][MSG_SIZE] = {
        { 0x0e, 0x15, 0x01, 0 },
        { 0x0e, 0x16, 0x01, 0 }
    };
    uchar in_pkt[MSG_SIZE];
    int modes = (IS_K95(kb) ? HWMODE_K95 : HWMODE_K70);
    for(int i = 0; i <= modes; i++){
        data_pkt[0][3] = i;
        if(!usbrecv(kb, data_pkt[0], in_pkt)){
            free(hw);
            return -1;
        }
        memcpy(hw->id + i, in_pkt + 4, sizeof(usbid));
    }
    // Ask for profile name
    if(!usbrecv(kb, data_pkt[1], in_pkt)){
        free(hw);
        return -1;
    }
    memcpy(hw->name[0], in_pkt + 4, PR_NAME_LEN * 2);
    // Load modes
    for(int i = 0; i < modes; i++){
        if(hwloadmode(kb, hw, i)){
            free(hw);
            return -1;
        }
    }
    // Make the profile active (if requested)
    if(apply)
        hwtonative(kb->profile, hw, modes);
    // Free the existing profile (if any)
    free(kb->hw);
    kb->hw = hw;
    DELAY_LONG(kb);
    return 0;
}
int cmd_hwload_mouse (usbdevice *kb, usbmode *dummy1, intdummy2, intapply, const char *dummy3)
Definition at line 6 of file profile_mouse.c.
References DELAY_LONG, hwprofile::dpi, usbdevice::hw, hwtonative(), hwprofile::id, hwprofile::light, loaddpi(), loadrgb_mouse(), MSG_SIZE, hwprofile::name, PR_NAME_LEN, usbdevice::profile, and usbrecv.
                                                                                               {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    DELAY_LONG(kb);
    hwprofile* hw = calloc(1, sizeof(hwprofile));
    // Ask for profile and mode IDs
    uchar data_pkt[2][MSG_SIZE] = {
        { 0x0e, 0x15, 0x01, 0 },
        { 0x0e, 0x16, 0x01, 0 }
    };
    uchar in_pkt[MSG_SIZE];
    for(int i = 0; i <= 1; i++){
        data_pkt[0][3] = i;
        if(!usbrecv(kb, data_pkt[0], in_pkt)){
            free(hw);
            return -1;
        }
        memcpy(hw->id + i, in_pkt + 4, sizeof(usbid));
    }
    // Ask for profile and mode names
    for(int i = 0; i <= 1; i++){
        data_pkt[1][3] = i;
        if(!usbrecv(kb, data_pkt[1],in_pkt)){
            free(hw);
            return -1;
        }
        memcpy(hw->name[i], in_pkt + 4, PR_NAME_LEN * 2);
    }
    // Load the RGB and DPI settings
    if(loadrgb_mouse(kb, hw->light, 0)
            || loaddpi(kb, hw->dpi, hw->light)){
        free(hw);
        return -1;
    }
    // Make the profile active (if requested)
    if(apply)
        hwtonative(kb->profile, hw, 1);
    // Free the existing profile (if any)
    free(kb->hw);
    kb->hw = hw;
    DELAY_LONG(kb);
    return 0;
}
int cmd_hwsave_kb (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *dummy4)
Definition at line 61 of file profile_keyboard.c.
References DELAY_LONG, usbdevice::hw, HWMODE_K70, HWMODE_K95, hwprofile::id, IS_K95, hwprofile::light, MD_NAME_LEN, MSG_SIZE, hwprofile::name, nativetohw(), usbdevice::profile, savergb_kb(), and usbsend.
                                                                                             {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    (void)dummy4;
    DELAY_LONG(kb);
    hwprofile* hw = kb->hw;
    if(!hw)
        hw = kb->hw = calloc(1, sizeof(hwprofile));
    int modes = (IS_K95(kb) ? HWMODE_K95 : HWMODE_K70);
    nativetohw(kb->profile, hw, modes);
    // Save the profile and mode names
    uchar data_pkt[2][MSG_SIZE] = {
        { 0x07, 0x16, 0x01, 0 },
        { 0x07, 0x15, 0x01, 0 },
    };
    // Save the mode names
    for(int i = 0; i <= modes; i++){
        data_pkt[0][3] = i;
        memcpy(data_pkt[0] + 4, hw->name[i], MD_NAME_LEN * 2);
        if(!usbsend(kb, data_pkt[0], 1))
            return -1;
    }
    // Save the IDs
    for(int i = 0; i <= modes; i++){
        data_pkt[1][3] = i;
        memcpy(data_pkt[1] + 4, hw->id + i, sizeof(usbid));
        if(!usbsend(kb, data_pkt[1], 1))
            return -1;
    }
    // Save the RGB data
    for(int i = 0; i < modes; i++){
        if(savergb_kb(kb, hw->light + i, i))
            return -1;
    }
    DELAY_LONG(kb);
    return 0;
}
int cmd_hwsave_mouse (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *dummy4)
Definition at line 54 of file profile_mouse.c.
References DELAY_LONG, hwprofile::dpi, usbdevice::hw, hwprofile::id, hwprofile::light, MD_NAME_LEN, MSG_SIZE, hwprofile::name, nativetohw(), usbdevice::profile, savedpi(), savergb_mouse(), and usbsend.
                                                                                                {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    (void)dummy4;
    DELAY_LONG(kb);
    hwprofile* hw = kb->hw;
    if(!hw)
        hw = kb->hw = calloc(1, sizeof(hwprofile));
    nativetohw(kb->profile, hw, 1);
    // Save the profile and mode names
    uchar data_pkt[2][MSG_SIZE] = {
        { 0x07, 0x16, 0x01, 0 },
        { 0x07, 0x15, 0x01, 0 },
    };
    for(int i = 0; i <= 1; i++){
        data_pkt[0][3] = i;
        memcpy(data_pkt[0] + 4, hw->name[i], MD_NAME_LEN * 2);
        if(!usbsend(kb, data_pkt[0], 1))
            return -1;
    }
    // Save the IDs
    for(int i = 0; i <= 1; i++){
        data_pkt[1][3] = i;
        memcpy(data_pkt[1] + 4, hw->id + i, sizeof(usbid));
        if(!usbsend(kb, data_pkt[1], 1))
            return -1;
    }
    // Save the RGB data for the non-DPI zones
    if(savergb_mouse(kb, hw->light, 0))
        return -1;
    // Save the DPI data (also saves RGB for those states)
    if(savedpi(kb, hw->dpi, hw->light))
        return -1;
    DELAY_LONG(kb);
    return 0;
}
void cmd_id (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *id)
Definition at line 168 of file profile.c.
References usbmode::id, usbid::modified, and setid().
                                                                                 {
    (void)kb;
    (void)dummy1;
    (void)dummy2;
    // ID is either a GUID or an 8-digit hex number
    int newmodified;
    if(!setid(&mode->id, id) && sscanf(id, "%08x", &newmodified) == 1)
        memcpy(mode->id.modified, &newmodified, sizeof(newmodified));
}
void cmd_name (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *name)
Definition at line 117 of file profile.c.
References MD_NAME_LEN, usbmode::name, u16enc(), and urldecode2().
                                                                                     {
    (void)kb;
    (void)dummy1;
    (void)dummy2;
    char decoded[strlen(name) + 1];
    urldecode2(decoded, name);
    size_t srclen = strlen(decoded), dstlen = MD_NAME_LEN;
    u16enc(decoded, mode->name, &srclen, &dstlen);
}
void cmd_profileid (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *id)
Definition at line 179 of file profile.c.
References usbprofile::id, usbid::modified, usbdevice::profile, and setid().
                                                                                        {
    (void)mode;
    (void)dummy1;
    (void)dummy2;
    usbprofile* profile = kb->profile;
    int newmodified;
    if(!setid(&profile->id, id) && sscanf(id, "%08x", &newmodified) == 1)
        memcpy(profile->id.modified, &newmodified, sizeof(newmodified));
}
void cmd_profilename (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *name)
Definition at line 128 of file profile.c.
References usbprofile::name, PR_NAME_LEN, usbdevice::profile, u16enc(), and urldecode2().
                                                                                              {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    usbprofile* profile = kb->profile;
    char decoded[strlen(name) + 1];
    urldecode2(decoded, name);
    size_t srclen = strlen(decoded), dstlen = PR_NAME_LEN;
    u16enc(decoded, profile->name, &srclen, &dstlen);
}
void freeprofile (usbdevice *kb)
Definition at line 253 of file profile.c.
References _freeprofile(), and usbdevice::hw.
                               {
    _freeprofile(kb);
    // Also free HW profile
    free(kb->hw);
    kb->hw = 0;
}
char* gethwmodename (hwprofile *profile, intindex)
Definition at line 160 of file profile.c.
References MD_NAME_LEN, hwprofile::name, and printname().
Referenced by _cmd_get().
                                                  {
    return printname(profile->name[index + 1], MD_NAME_LEN);
}
char* gethwprofilename (hwprofile *profile)
Definition at line 164 of file profile.c.
References MD_NAME_LEN, hwprofile::name, and printname().
Referenced by _cmd_get().
                                          {
    return printname(profile->name[0], MD_NAME_LEN);
}
char* getid (usbid *id)
Definition at line 79 of file profile.c.
References usbid::guid.
Referenced by _cmd_get().
                      {
    int32_t data1;
    int16_t data2, data3, data4a;
    char data4b[6];
    memcpy(&data1, id->guid + 0x0, 4);
    memcpy(&data2, id->guid + 0x4, 2);
    memcpy(&data3, id->guid + 0x6, 2);
    memcpy(&data4a, id->guid + 0x8, 2);
    memcpy(data4b, id->guid + 0xA, 6);
    char* guid = malloc(39);
    snprintf(guid, 39, "{%08X-%04hX-%04hX-%04hX-%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX}",
             data1, data2, data3, data4a, data4b[0], data4b[1], data4b[2], data4b[3], data4b[4], data4b[5]);
    return guid;
}
char* getmodename (usbmode *mode)
Definition at line 152 of file profile.c.
References MD_NAME_LEN, usbmode::name, and printname().
Referenced by _cmd_get().
                                {
    return printname(mode->name, MD_NAME_LEN);
}
char* getprofilename (usbprofile *profile)
Definition at line 156 of file profile.c.
References usbprofile::name, PR_NAME_LEN, and printname().
Referenced by _cmd_get().
                                         {
    return printname(profile->name, PR_NAME_LEN);
}
void hwtonative (usbprofile *profile, hwprofile *hw, intmodecount)
Definition at line 260 of file profile.c.
References usbmode::dpi, hwprofile::dpi, dpiset::forceupdate, lighting::forceupdate, usbmode::id, usbprofile::id, hwprofile::id, usbprofile::lastdpi, usbprofile::lastlight, usbmode::light, hwprofile::light, MD_NAME_LEN, usbprofile::mode, usbmode::name, usbprofile::name, hwprofile::name, and PR_NAME_LEN.
Referenced by cmd_hwload_kb(), and cmd_hwload_mouse().
                                                                  {
    // Copy the profile name and ID
    memcpy(profile->name, hw->name[0], PR_NAME_LEN * 2);
    memcpy(&profile->id, hw->id, sizeof(usbid));
    // Copy the mode settings
    for(int i = 0; i < modecount; i++){
        usbmode* mode = profile->mode + i;
        memcpy(mode->name, hw->name[i + 1], MD_NAME_LEN * 2);
        memcpy(&mode->id, hw->id + i + 1, sizeof(usbid));
        memcpy(&mode->light, hw->light + i, sizeof(lighting));
        memcpy(&mode->dpi, hw->dpi + i, sizeof(dpiset));
        // Set a force update on the light/DPI since they've been overwritten
        mode->light.forceupdate = mode->dpi.forceupdate = 1;
    }
    profile->lastlight.forceupdate = profile->lastdpi.forceupdate = 1;
}
int loadprofile (usbdevice *kb)
Definition at line 208 of file profile.c.
References hwloadprofile.
                              {
    if(hwloadprofile(kb, 1))
        return -1;
    return 0;
}
void nativetohw (usbprofile *profile, hwprofile *hw, intmodecount)
Definition at line 277 of file profile.c.
References usbmode::dpi, hwprofile::dpi, usbmode::id, usbprofile::id, hwprofile::id, usbmode::light, hwprofile::light, MD_NAME_LEN, usbprofile::mode, usbmode::name, usbprofile::name, hwprofile::name, and PR_NAME_LEN.
Referenced by cmd_hwsave_kb(), and cmd_hwsave_mouse().
                                                                  {
    // Copy name and ID
    memcpy(hw->name[0], profile->name, PR_NAME_LEN * 2);
    memcpy(hw->id, &profile->id, sizeof(usbid));
    // Copy the mode settings
    for(int i = 0; i < modecount; i++){
        usbmode* mode = profile->mode + i;
        memcpy(hw->name[i + 1], mode->name, MD_NAME_LEN * 2);
        memcpy(hw->id + i + 1, &mode->id, sizeof(usbid));
        memcpy(hw->light + i, &mode->light, sizeof(lighting));
        memcpy(hw->dpi + i, &mode->dpi, sizeof(dpiset));
    }
}
int setid (usbid *id, const char *guid)
Definition at line 64 of file profile.c.
References usbid::guid.
Referenced by cmd_id(), and cmd_profileid().
                                      {
    int32_t data1;
    int16_t data2, data3, data4a;
    char data4b[6];
    if(sscanf(guid, "{%08X-%04hX-%04hX-%04hX-%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX}",
              &data1, &data2, &data3, &data4a, data4b, data4b + 1, data4b + 2, data4b + 3, data4b + 4, data4b + 5) != 10)
        return 0;
    memcpy(id->guid + 0x0, &data1, 4);
    memcpy(id->guid + 0x4, &data2, 2);
    memcpy(id->guid + 0x6, &data3, 2);
    memcpy(id->guid + 0x8, &data4a, 2);
    memcpy(id->guid + 0xA, data4b, 6);
    return 1;
}
Author
Generated automatically by Doxygen for ckb-next from the source code.