src/ckb-daemon/profile.c
NAME
src/ckb-daemon/profile.c -
SYNOPSIS
#include 'command.h'
#include 'device.h'
#include 'input.h'
#include 'led.h'
#include 'profile.h'
Functions
void urldecode2 (char *dst, const char *src)
void urlencode2 (char *dst, const char *src)
int setid (usbid *id, const char *guid)
char * getid (usbid *id)
void u16enc (char *in, ushort *out, size_t *srclen, size_t *dstlen)
void u16dec (ushort *in, char *out, size_t *srclen, size_t *dstlen)
void cmd_name (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *name)
void cmd_profilename (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *name)
char * printname (ushort *name, int length)
char * getmodename (usbmode *mode)
char * getprofilename (usbprofile *profile)
char * gethwmodename (hwprofile *profile, int index)
char * gethwprofilename (hwprofile *profile)
void cmd_id (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *id)
void cmd_profileid (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *id)
static void initmode (usbmode *mode)
void allocprofile (usbdevice *kb)
int loadprofile (usbdevice *kb)
static void freemode (usbmode *mode)
void cmd_erase (usbdevice *kb, usbmode *mode, int dummy1, int dummy2, const char *dummy3)
static void _freeprofile (usbdevice *kb)
void cmd_eraseprofile (usbdevice *kb, usbmode *dummy1, int dummy2, int dummy3, const char *dummy4)
void freeprofile (usbdevice *kb)
void hwtonative (usbprofile *profile, hwprofile *hw, int modecount)
void nativetohw (usbprofile *profile, hwprofile *hw, int modecount)
Variables
static iconv_t utf8to16 = 0
static iconv_t utf16to8 = 0
Function Documentation
static void _freeprofile (usbdevice *kb) [static]
Definition at line 230 of file profile.c.
References freemode(), usbprofile::mode, MODE_COUNT, and usbdevice::profile.
Referenced by cmd_eraseprofile(), and freeprofile().
                                       {
    usbprofile* profile = kb->profile;
    if(!profile)
        return;
    // Clear all mode data
    for(int i = 0; i < MODE_COUNT; i++)
        freemode(profile->mode + i);
    free(profile);
    kb->profile = 0;
}
void allocprofile (usbdevice *kb)
Definition at line 198 of file profile.c.
References usbprofile::currentmode, dpiset::forceupdate, lighting::forceupdate, initmode(), usbprofile::lastdpi, usbprofile::lastlight, usbprofile::mode, MODE_COUNT, and usbdevice::profile.
Referenced by cmd_eraseprofile().
                                {
    if(kb->profile)
        return;
    usbprofile* profile = kb->profile = calloc(1, sizeof(usbprofile));
    for(int i = 0; i < MODE_COUNT; i++)
        initmode(profile->mode + i);
    profile->currentmode = profile->mode;
    profile->lastlight.forceupdate = profile->lastdpi.forceupdate = 1;
}
void cmd_erase (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *dummy3)
Definition at line 219 of file profile.c.
References freemode(), imutex, and initmode().
                                                                                        {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    pthread_mutex_lock(imutex(kb));
    freemode(mode);
    initmode(mode);
    pthread_mutex_unlock(imutex(kb));
}
void cmd_eraseprofile (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *dummy4)
Definition at line 241 of file profile.c.
References _freeprofile(), allocprofile(), and imutex.
                                                                                                 {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    (void)dummy4;
    pthread_mutex_lock(imutex(kb));
    _freeprofile(kb);
    allocprofile(kb);
    pthread_mutex_unlock(imutex(kb));
}
void cmd_id (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *id)
Definition at line 168 of file profile.c.
References usbmode::id, usbid::modified, and setid().
                                                                                 {
    (void)kb;
    (void)dummy1;
    (void)dummy2;
    // ID is either a GUID or an 8-digit hex number
    int newmodified;
    if(!setid(&mode->id, id) && sscanf(id, "%08x", &newmodified) == 1)
        memcpy(mode->id.modified, &newmodified, sizeof(newmodified));
}
void cmd_name (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *name)
Definition at line 117 of file profile.c.
References MD_NAME_LEN, usbmode::name, u16enc(), and urldecode2().
                                                                                     {
    (void)kb;
    (void)dummy1;
    (void)dummy2;
    char decoded[strlen(name) + 1];
    urldecode2(decoded, name);
    size_t srclen = strlen(decoded), dstlen = MD_NAME_LEN;
    u16enc(decoded, mode->name, &srclen, &dstlen);
}
void cmd_profileid (usbdevice *kb, usbmode *mode, intdummy1, intdummy2, const char *id)
Definition at line 179 of file profile.c.
References usbprofile::id, usbid::modified, usbdevice::profile, and setid().
                                                                                        {
    (void)mode;
    (void)dummy1;
    (void)dummy2;
    usbprofile* profile = kb->profile;
    int newmodified;
    if(!setid(&profile->id, id) && sscanf(id, "%08x", &newmodified) == 1)
        memcpy(profile->id.modified, &newmodified, sizeof(newmodified));
}
void cmd_profilename (usbdevice *kb, usbmode *dummy1, intdummy2, intdummy3, const char *name)
Definition at line 128 of file profile.c.
References usbprofile::name, PR_NAME_LEN, usbdevice::profile, u16enc(), and urldecode2().
                                                                                              {
    (void)dummy1;
    (void)dummy2;
    (void)dummy3;
    usbprofile* profile = kb->profile;
    char decoded[strlen(name) + 1];
    urldecode2(decoded, name);
    size_t srclen = strlen(decoded), dstlen = PR_NAME_LEN;
    u16enc(decoded, profile->name, &srclen, &dstlen);
}
static void freemode (usbmode *mode) [static]
Definition at line 214 of file profile.c.
References usbmode::bind, and freebind().
Referenced by _freeprofile(), and cmd_erase().
                                   {
    freebind(&mode->bind);
    memset(mode, 0, sizeof(*mode));
}
void freeprofile (usbdevice *kb)
Definition at line 253 of file profile.c.
References _freeprofile(), and usbdevice::hw.
                               {
    _freeprofile(kb);
    // Also free HW profile
    free(kb->hw);
    kb->hw = 0;
}
char* gethwmodename (hwprofile *profile, intindex)
Definition at line 160 of file profile.c.
References MD_NAME_LEN, hwprofile::name, and printname().
Referenced by _cmd_get().
                                                  {
    return printname(profile->name[index + 1], MD_NAME_LEN);
}
char* gethwprofilename (hwprofile *profile)
Definition at line 164 of file profile.c.
References MD_NAME_LEN, hwprofile::name, and printname().
Referenced by _cmd_get().
                                          {
    return printname(profile->name[0], MD_NAME_LEN);
}
char* getid (usbid *id)
Definition at line 79 of file profile.c.
References usbid::guid.
Referenced by _cmd_get().
                      {
    int32_t data1;
    int16_t data2, data3, data4a;
    char data4b[6];
    memcpy(&data1, id->guid + 0x0, 4);
    memcpy(&data2, id->guid + 0x4, 2);
    memcpy(&data3, id->guid + 0x6, 2);
    memcpy(&data4a, id->guid + 0x8, 2);
    memcpy(data4b, id->guid + 0xA, 6);
    char* guid = malloc(39);
    snprintf(guid, 39, "{%08X-%04hX-%04hX-%04hX-%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX}",
             data1, data2, data3, data4a, data4b[0], data4b[1], data4b[2], data4b[3], data4b[4], data4b[5]);
    return guid;
}
char* getmodename (usbmode *mode)
Definition at line 152 of file profile.c.
References MD_NAME_LEN, usbmode::name, and printname().
Referenced by _cmd_get().
                                {
    return printname(mode->name, MD_NAME_LEN);
}
char* getprofilename (usbprofile *profile)
Definition at line 156 of file profile.c.
References usbprofile::name, PR_NAME_LEN, and printname().
Referenced by _cmd_get().
                                         {
    return printname(profile->name, PR_NAME_LEN);
}
void hwtonative (usbprofile *profile, hwprofile *hw, intmodecount)
Definition at line 260 of file profile.c.
References usbmode::dpi, hwprofile::dpi, dpiset::forceupdate, lighting::forceupdate, usbmode::id, usbprofile::id, hwprofile::id, usbprofile::lastdpi, usbprofile::lastlight, usbmode::light, hwprofile::light, MD_NAME_LEN, usbprofile::mode, usbmode::name, usbprofile::name, hwprofile::name, and PR_NAME_LEN.
Referenced by cmd_hwload_kb(), and cmd_hwload_mouse().
                                                                  {
    // Copy the profile name and ID
    memcpy(profile->name, hw->name[0], PR_NAME_LEN * 2);
    memcpy(&profile->id, hw->id, sizeof(usbid));
    // Copy the mode settings
    for(int i = 0; i < modecount; i++){
        usbmode* mode = profile->mode + i;
        memcpy(mode->name, hw->name[i + 1], MD_NAME_LEN * 2);
        memcpy(&mode->id, hw->id + i + 1, sizeof(usbid));
        memcpy(&mode->light, hw->light + i, sizeof(lighting));
        memcpy(&mode->dpi, hw->dpi + i, sizeof(dpiset));
        // Set a force update on the light/DPI since they've been overwritten
        mode->light.forceupdate = mode->dpi.forceupdate = 1;
    }
    profile->lastlight.forceupdate = profile->lastdpi.forceupdate = 1;
}
static void initmode (usbmode *mode) [static]
Definition at line 191 of file profile.c.
References usbmode::bind, usbmode::dpi, dpiset::forceupdate, lighting::forceupdate, initbind(), and usbmode::light.
Referenced by allocprofile(), and cmd_erase().
                                   {
    memset(mode, 0, sizeof(*mode));
    mode->light.forceupdate = 1;
    mode->dpi.forceupdate = 1;
    initbind(&mode->bind);
}
int loadprofile (usbdevice *kb)
Definition at line 208 of file profile.c.
References hwloadprofile.
                              {
    if(hwloadprofile(kb, 1))
        return -1;
    return 0;
}
void nativetohw (usbprofile *profile, hwprofile *hw, intmodecount)
Definition at line 277 of file profile.c.
References usbmode::dpi, hwprofile::dpi, usbmode::id, usbprofile::id, hwprofile::id, usbmode::light, hwprofile::light, MD_NAME_LEN, usbprofile::mode, usbmode::name, usbprofile::name, hwprofile::name, and PR_NAME_LEN.
Referenced by cmd_hwsave_kb(), and cmd_hwsave_mouse().
                                                                  {
    // Copy name and ID
    memcpy(hw->name[0], profile->name, PR_NAME_LEN * 2);
    memcpy(hw->id, &profile->id, sizeof(usbid));
    // Copy the mode settings
    for(int i = 0; i < modecount; i++){
        usbmode* mode = profile->mode + i;
        memcpy(hw->name[i + 1], mode->name, MD_NAME_LEN * 2);
        memcpy(hw->id + i + 1, &mode->id, sizeof(usbid));
        memcpy(hw->light + i, &mode->light, sizeof(lighting));
        memcpy(hw->dpi + i, &mode->dpi, sizeof(dpiset));
    }
}
char* printname (ushort *name, intlength)
Definition at line 140 of file profile.c.
References u16dec(), and urlencode2().
Referenced by gethwmodename(), gethwprofilename(), getmodename(), and getprofilename().
                                         {
    // Convert the name to UTF-8
    char* buffer = calloc(1, length * 4 - 3);
    size_t srclen = length, dstlen = length * 4 - 4;
    u16dec(name, buffer, &srclen, &dstlen);
    // URL-encode it
    char* buffer2 = malloc(strlen(buffer) * 3 + 1);
    urlencode2(buffer2, buffer);
    free(buffer);
    return buffer2;
}
int setid (usbid *id, const char *guid)
Definition at line 64 of file profile.c.
References usbid::guid.
Referenced by cmd_id(), and cmd_profileid().
                                      {
    int32_t data1;
    int16_t data2, data3, data4a;
    char data4b[6];
    if(sscanf(guid, "{%08X-%04hX-%04hX-%04hX-%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX}",
              &data1, &data2, &data3, &data4a, data4b, data4b + 1, data4b + 2, data4b + 3, data4b + 4, data4b + 5) != 10)
        return 0;
    memcpy(id->guid + 0x0, &data1, 4);
    memcpy(id->guid + 0x4, &data2, 2);
    memcpy(id->guid + 0x6, &data3, 2);
    memcpy(id->guid + 0x8, &data4a, 2);
    memcpy(id->guid + 0xA, data4b, 6);
    return 1;
}
void u16dec (ushort *in, char *out, size_t *srclen, size_t *dstlen)
Definition at line 105 of file profile.c.
References utf16to8.
Referenced by printname().
                                                                  {
    if(!utf16to8)
        utf16to8 = iconv_open("UTF-8", "UTF-16LE");
    size_t srclen2 = 0, srclenmax = *srclen;
    for(; srclen2 < srclenmax; srclen2++){
        if(!in[srclen2])
            break;
    }
    *srclen = srclen2 * 2;
    iconv(utf16to8, (char**)&in, srclen, &out, dstlen);
}
void u16enc (char *in, ushort *out, size_t *srclen, size_t *dstlen)
Definition at line 97 of file profile.c.
References utf8to16.
Referenced by cmd_name(), and cmd_profilename().
                                                                  {
    if(!utf8to16)
        utf8to16 = iconv_open("UTF-16LE", "UTF-8");
    memset(out, 0, *dstlen * 2);
    *dstlen = *dstlen * 2 - 2;
    iconv(utf8to16, &in, srclen, (char**)&out, dstlen);
}
void urldecode2 (char *dst, const char *src)
Definition at line 8 of file profile.c.
Referenced by cmd_name(), and cmd_profilename().
                                           {
    char a, b;
    char s;
    while((s = *src)){
        if((s == '%') &&
                ((a = src[1]) && (b = src[2])) &&
                (isxdigit(a) && isxdigit(b))){
            if(a >= 'a')
                a -= 'a'-'A';
            if(a >= 'A')
                a -= 'A' - 10;
            else
                a -= '0';
            if(b >= 'a')
                b -= 'a'-'A';
            if(b >= 'A')
                b -= 'A' - 10;
            else
                b -= '0';
            *dst++ = 16 * a + b;
            src += 3;
        } else {
            *dst++ = s;
            src++;
        }
    }
    *dst = '\0';
}
void urlencode2 (char *dst, const char *src)
Definition at line 37 of file profile.c.
Referenced by printname().
                                           {
    char s;
    while((s = *src++)){
        if(s <= ',' || s == '/' ||
                (s >= ':' && s <= '@') ||
                s == '[' || s == ']' ||
                s >= 0x7F){
            char a = s >> 4, b = s & 0xF;
            if(a >= 10)
                a += 'A' - 10;
            else
                a += '0';
            if(b >= 10)
                b += 'A' - 10;
            else
                b += '0';
            dst[0] = '%';
            dst[1] = a;
            dst[2] = b;
            dst += 3;
        } else
            *dst++ = s;
    }
    *dst = '\0';
}
Variable Documentation
iconv_t utf16to8 = 0 [static]
Definition at line 95 of file profile.c.
Referenced by u16dec().
iconv_t utf8to16 = 0 [static]
Definition at line 95 of file profile.c.
Referenced by u16enc().
Author
Generated automatically by Doxygen for ckb-next from the source code.