src/ckb/release/qrc_image.cpp
NAME
src/ckb/release/qrc_image.cpp -
SYNOPSIS
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int qInitResources_image ()
int qCleanupResources_image ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
#define QT_RCC_MANGLE_NAMESPACE(name) name
Definition at line 14160 of file qrc_image.cpp.
#define QT_RCC_PREPEND_NAMESPACE(name) name
Definition at line 14159 of file qrc_image.cpp.
Referenced by qCleanupResources_image(), and qInitResources_image().
Function Documentation
int qCleanupResources_image ()
Definition at line 14184 of file qrc_image.cpp.
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
{
    QT_RCC_PREPEND_NAMESPACE(qUnregisterResourceData)
       (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
int qInitResources_image ()
Definition at line 14176 of file qrc_image.cpp.
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
{
    QT_RCC_PREPEND_NAMESPACE(qRegisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qInitResources_image().
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qCleanupResources_image().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 9 of file qrc_image.cpp.
Referenced by qCleanupResources_image(), and qInitResources_image().
const unsigned char qt_resource_name[] [static]
Definition at line 14007 of file qrc_image.cpp.
Referenced by qCleanupResources_image(), and qInitResources_image().
const unsigned char qt_resource_struct[] [static]
Definition at line 14109 of file qrc_image.cpp.
Referenced by qCleanupResources_image(), and qInitResources_image().
Author
Generated automatically by Doxygen for ckb-next from the source code.