.TH "QThread" 3 "Fri Nov 3 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QThread \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKb\fP, \fBMacroReader\fP, and \fBMacroReaderThread\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
