.TH "QuaAdler32" 3 "Wed May 24 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuaAdler32 \- 
.PP
Adler32 checksum\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <quazip/quaadler32\&.h>\fP
.PP
Inherits \fBQuaChecksum32\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaAdler32\fP ()"
.br
.ti -1c
.RI "quint32 \fBcalculate\fP (const QByteArray &data)"
.br
.RI "\fICalculates the checksum for data\&. \fP"
.ti -1c
.RI "void \fBreset\fP ()"
.br
.RI "\fIResets the calculation on a checksun for a stream\&. \fP"
.ti -1c
.RI "void \fBupdate\fP (const QByteArray &buf)"
.br
.RI "\fIUpdates the calculated checksum for the stream\&. \fP"
.ti -1c
.RI "quint32 \fBvalue\fP ()"
.br
.RI "\fIValue of the checksum calculated for the stream passed throw \fBupdate()\fP\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "quint32 \fBchecksum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class wrappers the adler32 function with the \fBQuaChecksum32\fP interface\&. See \fBQuaChecksum32\fP for more info\&. 
.PP
Definition at line 38 of file quaadler32\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QuaAdler32::QuaAdler32 ()"

.PP
Definition at line 30 of file quaadler32\&.cpp\&.
.PP
References reset()\&.
.PP
.nf
31 {
32     reset();
33 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "quint32 QuaAdler32::calculate (const QByteArray &data)\fC [virtual]\fP"
\fIdata\fP source data 
.PP
\fBReturns:\fP
.RS 4
data checksum
.RE
.PP
This function has no efect on the value returned by \fBvalue()\fP\&. 
.PP
Implements \fBQuaChecksum32\fP\&.
.PP
Definition at line 35 of file quaadler32\&.cpp\&.
.PP
.nf
36 {
37     return adler32( adler32(0L, Z_NULL, 0), (const Bytef*)data\&.data(), data\&.size() );
38 }
.fi
.SS "void QuaAdler32::reset ()\fC [virtual]\fP"

.PP
Implements \fBQuaChecksum32\fP\&.
.PP
Definition at line 40 of file quaadler32\&.cpp\&.
.PP
References checksum\&.
.PP
Referenced by QuaAdler32()\&.
.PP
.nf
41 {
42     checksum = adler32(0L, Z_NULL, 0);
43 }
.fi
.SS "void QuaAdler32::update (const QByteArray &buf)\fC [virtual]\fP"
\fIbuf\fP next portion of data from the stream 
.PP
Implements \fBQuaChecksum32\fP\&.
.PP
Definition at line 45 of file quaadler32\&.cpp\&.
.PP
References checksum\&.
.PP
.nf
46 {
47     checksum = adler32( checksum, (const Bytef*)buf\&.data(), buf\&.size() );
48 }
.fi
.SS "quint32 QuaAdler32::value ()\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
checksum 
.RE
.PP

.PP
Implements \fBQuaChecksum32\fP\&.
.PP
Definition at line 50 of file quaadler32\&.cpp\&.
.PP
References checksum\&.
.PP
.nf
51 {
52     return checksum;
53 }
.fi
.SH "Field Documentation"
.PP 
.SS "quint32 QuaAdler32::checksum\fC [private]\fP"

.PP
Definition at line 51 of file quaadler32\&.h\&.
.PP
Referenced by reset(), update(), and value()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
