.TH "src/ckb/quazip/quagzipfile.h" 3 "Thu Nov 2 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quagzipfile.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QIODevice>\fP
.br
\fC#include 'quazip_global\&.h'\fP
.br
\fC#include <zlib\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQuaGzipFile\fP"
.br
.RI "\fIGZIP file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
