.TH "src/ckb/quazip/quaziodevice.h" 3 "Sat Jan 20 2018" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quaziodevice.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QIODevice>\fP
.br
\fC#include 'quazip_global\&.h'\fP
.br
\fC#include <zlib\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQuaZIODevice\fP"
.br
.RI "\fIA class to compress/decompress \fBQIODevice\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
