.TH "src/ckb/quazip/quazipdir.h" 3 "Tue May 16 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quazipdir.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'quazip\&.h'\fP
.br
\fC#include 'quazipfileinfo\&.h'\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QSharedDataPointer>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQuaZipDir\fP"
.br
.RI "\fIProvides ZIP archive navigation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
