QuaZipFile
NAME
QuaZipFile -
A file inside ZIP archive.
SYNOPSIS
#include <quazip/quazipfile.h>
Inherits QIODevice.
Public Member Functions
QuaZipFile ()
Constructs a QuaZipFile instance.
QuaZipFile (QObject *parent)
Constructs a QuaZipFile instance.
QuaZipFile (const QString &zipName, QObject *parent=NULL)
Constructs a QuaZipFile instance.
QuaZipFile (const QString &zipName, const QString &fileName, QuaZip::CaseSensitivity cs=QuaZip::csDefault, QObject *parent=NULL)
Constructs a QuaZipFile instance.
QuaZipFile (QuaZip *zip, QObject *parent=NULL)
Constructs a QuaZipFile instance.
virtual ~QuaZipFile ()
Destroys a QuaZipFile instance.
QString getZipName () const
Returns the ZIP archive file name.
QuaZip * getZip () const
Returns a pointer to the associated QuaZip object.
QString getFileName () const
Returns file name.
QuaZip::CaseSensitivity getCaseSensitivity () const
Returns case sensitivity of the file name.
QString getActualFileName () const
Returns the actual file name in the archive.
void setZipName (const QString &zipName)
Sets the ZIP archive file name.
bool isRaw () const
Returns true if the file was opened in raw mode.
void setZip (QuaZip *zip)
Binds to the existing QuaZip instance.
void setFileName (const QString &fileName, QuaZip::CaseSensitivity cs=QuaZip::csDefault)
Sets the file name.
virtual bool open (OpenMode mode)
Opens a file for reading.
bool open (OpenMode mode, const char *password)
Opens a file for reading.
bool open (OpenMode mode, int *method, int *level, bool raw, const char *password=NULL)
Opens a file for reading.
bool open (OpenMode mode, const QuaZipNewInfo &info, const char *password=NULL, quint32 crc=0, int method=Z_DEFLATED, int level=Z_DEFAULT_COMPRESSION, bool raw=false, int windowBits=-MAX_WBITS, int memLevel=MAX_MEM_LEVEL, int strategy=Z_DEFAULT_STRATEGY)
Opens a file for writing.
virtual bool isSequential () const
Returns true, but beware!
virtual qint64 pos () const
Returns current position in the file.
virtual bool atEnd () const
Returns true if the end of file was reached.
virtual qint64 size () const
Returns file size.
qint64 csize () const
Returns compressed file size.
qint64 usize () const
Returns uncompressed file size.
bool getFileInfo (QuaZipFileInfo *info)
Gets information about current file.
bool getFileInfo (QuaZipFileInfo64 *info)
Gets information about current file with zip64 support.
virtual void close ()
Closes the file.
int getZipError () const
Returns the error code returned by the last ZIP/UNZIP API call.
virtual qint64 bytesAvailable () const
Returns the number of bytes available for reading.
Protected Member Functions
qint64 readData (char *data, qint64 maxSize)
Implementation of the QIODevice::readData().
qint64 writeData (const char *data, qint64 maxSize)
Implementation of the QIODevice::writeData().
Private Member Functions
QuaZipFile (const QuaZipFile &that)
QuaZipFile & operator= (const QuaZipFile &that)
Private Attributes
QuaZipFilePrivate * p
Friends
class QuaZipFilePrivate
Detailed Description
This is the most interesting class. Not only it provides C++ interface to the ZIP/UNZIP package, but also integrates it with Qt by subclassing QIODevice. This makes possible to access files inside ZIP archive using QTextStream or QDataStream, for example. Actually, this is the main purpose of the whole QuaZIP library.
You can either use existing QuaZip instance to create instance of this class or pass ZIP archive file name to this class, in which case it will create internal QuaZip object. See constructors' descriptions for details. Writing is only possible with the existing instance.
Note that due to the underlying library's limitation it is not possible to use multiple QuaZipFile instances to open several files in the same archive at the same time. If you need to write to multiple files in parallel, then you should write to temporary files first, then pack them all at once when you have finished writing. If you need to read multiple files inside the same archive in parallel, you should extract them all into a temporary directory first.
Sequential or random-access?
At the first thought, QuaZipFile has fixed size, the start and the end and should be therefore considered random-access device. But there is one major obstacle to making it random-access: ZIP/UNZIP API does not support seek() operation and the only way to implement it is through reopening the file and re-reading to the required position, but this is prohibitively slow.
Therefore, QuaZipFile is considered to be a sequential device. This has advantage of availability of the ungetChar() operation (QIODevice does not implement it properly for non-sequential devices unless they support seek()). Disadvantage is a somewhat strange behaviour of the size() and pos() functions. This should be kept in mind while using this class.
Definition at line 74 of file quazipfile.h.
Constructor & Destructor Documentation
QuaZipFile::QuaZipFile (const QuaZipFile &that) [private]
QuaZipFile::QuaZipFile ()
You should use setZipName() and setFileName() or setZip() before trying to call open() on the constructed object.
Definition at line 108 of file quazipfile.cpp.
                      :
  p(new QuaZipFilePrivate(this))
{
}
QuaZipFile::QuaZipFile (QObject *parent)
parent argument specifies this object's parent object.
You should use setZipName() and setFileName() or setZip() before trying to call open() on the constructed object.
Definition at line 113 of file quazipfile.cpp.
                                     :
  QIODevice(parent),
  p(new QuaZipFilePrivate(this))
{
}
QuaZipFile::QuaZipFile (const QString &zipName, QObject *parent = NULL)
parent argument specifies this object's parent object and zipName specifies ZIP archive file name.
You should use setFileName() before trying to call open() on the constructed object.
QuaZipFile constructed by this constructor can be used for read only access. Use QuaZipFile(QuaZip*,QObject*) for writing.
Definition at line 119 of file quazipfile.cpp.
                                                             :
  QIODevice(parent),
  p(new QuaZipFilePrivate(this, zipName))
{
}
QuaZipFile::QuaZipFile (const QString &zipName, const QString &fileName, QuaZip::CaseSensitivitycs = QuaZip::csDefault, QObject *parent = NULL)
parent argument specifies this object's parent object, zipName specifies ZIP archive file name and fileName and cs specify a name of the file to open inside archive.
QuaZipFile constructed by this constructor can be used for read only access. Use QuaZipFile(QuaZip*,QObject*) for writing.
See Also:
QuaZip::setCurrentFile()
Definition at line 125 of file quazipfile.cpp.
                                              :
  QIODevice(parent),
  p(new QuaZipFilePrivate(this, zipName, fileName, cs))
{
}
QuaZipFile::QuaZipFile (QuaZip *zip, QObject *parent = NULL)
parent argument specifies this object's parent object.
zip is the pointer to the existing QuaZip object. This QuaZipFile object then can be used to read current file in the zip or to write to the file inside it.
Warning:
Using this constructor for reading current file can be tricky. Let's take the following example:
QuaZip zip("archive.zip");
zip.open(QuaZip::mdUnzip);
zip.setCurrentFile("file-in-archive");
QuaZipFile file(&zip);
file.open(QIODevice::ReadOnly);
// ok, now we can read from the file
file.read(somewhere, some);
zip.setCurrentFile("another-file-in-archive"); // oops...
QuaZipFile anotherFile(&zip);
anotherFile.open(QIODevice::ReadOnly);
anotherFile.read(somewhere, some); // this is still ok...
file.read(somewhere, some); // and this is NOT
 So, what exactly happens here? When we change current file in the zip archive, file that references it becomes invalid (actually, as far as I understand ZIP/UNZIP sources, it becomes closed, but QuaZipFile has no means to detect it).
Summary: do not close zip object or change its current file as long as QuaZipFile is open. Even better - use another constructors which create internal QuaZip instances, one per object, and therefore do not cause unnecessary trouble. This constructor may be useful, though, if you already have a QuaZip instance and do not want to access several files at once. Good example:
QuaZip zip("archive.zip");
zip.open(QuaZip::mdUnzip);
// first, we need some information about archive itself
QByteArray comment=zip.getComment();
// and now we are going to access files inside it
QuaZipFile file(&zip);
for(bool more=zip.goToFirstFile(); more; more=zip.goToNextFile()) {
  file.open(QIODevice::ReadOnly);
  // do something cool with file here
  file.close(); // do not forget to close!
}
zip.close();
Definition at line 132 of file quazipfile.cpp.
                                                  :
  QIODevice(parent),
  p(new QuaZipFilePrivate(this, zip))
{
}
QuaZipFile::~QuaZipFile () [virtual]
Closes file if open, destructs internal QuaZip object (if it exists and is internal, of course).
Definition at line 138 of file quazipfile.cpp.
References close(), and p.
{
  if (isOpen())
    close();
  delete p;
}
Member Function Documentation
bool QuaZipFile::atEnd () const [virtual]
This function returns false in the case of error. This means that you called this function on either not open file, or a file in the not open archive or even on a QuaZipFile instance that does not even have QuaZip instance associated. Do not do that because there is no means to determine whether false is returned because of error or because end of file was reached. Well, on the other side you may interpret false return value as 'there is no file open to check for end of file and there is
no end of file therefore'.
When writing, this function always returns true (because you are always writing to the end of file).
Error code returned by getZipError() is not affected by this function call.
Definition at line 361 of file quazipfile.cpp.
References QuaZip::getUnzFile(), p, unzeof(), and QuaZipFilePrivate::zip.
{
  if(p->zip==NULL) {
    qWarning("QuaZipFile::atEnd(): call setZipName() or setZip() first");
    return false;
  }
  if(!isOpen()) {
    qWarning("QuaZipFile::atEnd(): file is not open");
    return false;
  }
  if(openMode()&ReadOnly)
      // the same problem as with pos()
    return QIODevice::bytesAvailable() == 0
        && unzeof(p->zip->getUnzFile())==1;
  else
    return true;
}
qint64 QuaZipFile::bytesAvailable () const [virtual]
Definition at line 499 of file quazipfile.cpp.
References pos(), and size().
{
    return size() - pos();
}
void QuaZipFile::close () [virtual]
Call getZipError() to determine if the close was successful.
Definition at line 432 of file quazipfile.cpp.
References QuaZip::close(), QuaZipFilePrivate::crc, QuaZip::getUnzFile(), QuaZip::getZipError(), QuaZip::getZipFile(), QuaZipFilePrivate::internal, QuaZip::isOpen(), isRaw(), p, QuaZipFilePrivate::resetZipError(), QuaZipFilePrivate::setZipError(), QuaZipFilePrivate::uncompressedSize, UNZ_OK, unzCloseCurrentFile(), QuaZipFilePrivate::zip, zipCloseFileInZip(), zipCloseFileInZipRaw64(), and QuaZipFilePrivate::zipError.
Referenced by JlCompress::compressFile(), JlCompress::compressSubDir(), JlCompress::extractFile(), and ~QuaZipFile().
{
  p->resetZipError();
  if(p->zip==NULL||!p->zip->isOpen()) return;
  if(!isOpen()) {
    qWarning("QuaZipFile::close(): file isn't open");
    return;
  }
  if(openMode()&ReadOnly)
    p->setZipError(unzCloseCurrentFile(p->zip->getUnzFile()));
  else if(openMode()&WriteOnly)
    if(isRaw()) p->setZipError(zipCloseFileInZipRaw64(p->zip->getZipFile(), p->uncompressedSize, p->crc));
    else p->setZipError(zipCloseFileInZip(p->zip->getZipFile()));
  else {
    qWarning("Wrong open mode: %d", (int)openMode());
    return;
  }
  if(p->zipError==UNZ_OK) setOpenMode(QIODevice::NotOpen);
  else return;
  if(p->internal) {
    p->zip->close();
    p->setZipError(p->zip->getZipError());
  }
}
qint64 QuaZipFile::csize () const
Equivalent to calling getFileInfo() and then getting compressedSize field, but more convenient and faster.
File must be open for reading before calling this function.
Returns -1 on error, call getZipError() to get error code.
Definition at line 391 of file quazipfile.cpp.
References unz_file_info64_s::compressed_size, QuaZip::getMode(), QuaZip::getUnzFile(), QuaZip::mdUnzip, p, QuaZipFilePrivate::setZipError(), UNZ_OK, unzGetCurrentFileInfo64(), QuaZipFilePrivate::zip, and QuaZipFilePrivate::zipError.
Referenced by size().
{
  unz_file_info64 info_z;
  p->setZipError(UNZ_OK);
  if(p->zip==NULL||p->zip->getMode()!=QuaZip::mdUnzip) return -1;
  p->setZipError(unzGetCurrentFileInfo64(p->zip->getUnzFile(), &info_z, NULL, 0, NULL, 0, NULL, 0));
  if(p->zipError!=UNZ_OK)
    return -1;
  return info_z.compressed_size;
}
QString QuaZipFile::getActualFileName () const
This is not a ZIP archive file name, but a name of file inside archive. It is not necessary the same name that you have passed to the QuaZipFile(const QString&,const QString&,QuaZip::CaseSensitivity,QObject*), setFileName() or QuaZip::setCurrentFile() - this is the real file name inside archive, so it may differ in case if the file name search was case-insensitive.
Equivalent to calling getCurrentFileName() on the associated QuaZip object. Returns null string if there is no associated QuaZip object or if it does not have a current file yet. And this is the case if you called setFileName() but did not open the file yet. So this is perfectly fine:
QuaZipFile file("somezip.zip");
file.setFileName("somefile");
QString name=file.getName(); // name=="somefile"
QString actual=file.getActualFileName(); // actual is null string
file.open(QIODevice::ReadOnly);
QString actual=file.getActualFileName(); // actual can be "SoMeFiLe" on Windows
See Also:
getZipName(), getFileName(), QuaZip::CaseSensitivity
Definition at line 155 of file quazipfile.cpp.
References QuaZip::getCurrentFileName(), QuaZip::getZipError(), p, QuaZipFilePrivate::setZipError(), UNZ_OK, and QuaZipFilePrivate::zip.
{
  p->setZipError(UNZ_OK);
  if (p->zip == NULL || (openMode() & WriteOnly))
    return QString();
  QString name=p->zip->getCurrentFileName();
  if(name.isNull())
    p->setZipError(p->zip->getZipError());
  return name;
}
QuaZip::CaseSensitivity QuaZipFile::getCaseSensitivity () const
This function returns case sensitivity argument you passed to this object either by using QuaZipFile(const QString&,const QString&,QuaZip::CaseSensitivity,QObject*) or by calling setFileName().
Returns unpredictable value if getFileName() returns null string (this is the case when you did not used setFileName() or constructor above).
See Also:
getFileName
Definition at line 484 of file quazipfile.cpp.
References QuaZipFilePrivate::caseSensitivity, and p.
{
  return p->caseSensitivity;
}
bool QuaZipFile::getFileInfo (QuaZipFileInfo *info)
This function does the same thing as calling QuaZip::getCurrentFileInfo() on the associated QuaZip object, but you can not call getCurrentFileInfo() if the associated QuaZip is internal (because you do not have access to it), while you still can call this function in that case.
File must be open for reading before calling this function.
Returns:
false in the case of an error.
This function doesn't support zip64, but will still work fine on zip64 archives if file sizes are below 4 GB, otherwise the values will be set as if converted using QuaZipFileInfo64::toQuaZipFileInfo().
See Also:
getFileInfo(QuaZipFileInfo64*)
Definition at line 413 of file quazipfile.cpp.
References QuaZipFileInfo64::toQuaZipFileInfo().
{
    QuaZipFileInfo64 info64;
    if (getFileInfo(&info64)) {
        info64.toQuaZipFileInfo(*info);
        return true;
    } else {
        return false;
    }
}
bool QuaZipFile::getFileInfo (QuaZipFileInfo64 *info)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See Also:
getFileInfo(QuaZipFileInfo*)
Definition at line 424 of file quazipfile.cpp.
References QuaZip::getCurrentFileInfo(), QuaZip::getMode(), QuaZip::getZipError(), QuaZip::mdUnzip, p, QuaZipFilePrivate::setZipError(), UNZ_OK, QuaZipFilePrivate::zip, and QuaZipFilePrivate::zipError.
{
    if(p->zip==NULL||p->zip->getMode()!=QuaZip::mdUnzip) return false;
    p->zip->getCurrentFileInfo(info);
    p->setZipError(p->zip->getZipError());
    return p->zipError==UNZ_OK;
}
QString QuaZipFile::getFileName () const
This function returns file name you passed to this object either by using QuaZipFile(const QString&,const QString&,QuaZip::CaseSensitivity,QObject*) or by calling setFileName(). Real name of the file may differ in case if you used case-insensitivity.
Returns null string if there is no file name set yet. This is the case when this QuaZipFile operates on the existing QuaZip object (constructor QuaZipFile(QuaZip*,QObject*) or setZip() was used).
See Also:
getActualFileName
Definition at line 479 of file quazipfile.cpp.
References QuaZipFilePrivate::fileName, and p.
{
  return p->fileName;
}
QuaZip * QuaZipFile::getZip () const
Returns NULL if there is no associated QuaZip or it is internal (so you will not mess with it).
Definition at line 150 of file quazipfile.cpp.
References QuaZipFilePrivate::internal, p, and QuaZipFilePrivate::zip.
{
    return p->internal ? NULL : p->zip;
}
int QuaZipFile::getZipError () const
Definition at line 494 of file quazipfile.cpp.
References p, and QuaZipFilePrivate::zipError.
Referenced by JlCompress::compressFile(), and JlCompress::extractFile().
{
  return p->zipError;
}
QString QuaZipFile::getZipName () const
If this object was created by passing QuaZip pointer to the constructor, this function will return that QuaZip's file name (or null string if that object does not have file name yet).
Otherwise, returns associated ZIP archive file name or null string if there are no name set yet.
See Also:
setZipName() getFileName()
Definition at line 145 of file quazipfile.cpp.
References QuaZip::getZipName(), p, and QuaZipFilePrivate::zip.
{
  return p->zip==NULL ? QString() : p->zip->getZipName();
}
bool QuaZipFile::isRaw () const
If the file is not open, the returned value is undefined.
See Also:
open(OpenMode,int*,int*,bool,const char*)
Definition at line 489 of file quazipfile.cpp.
References p, and QuaZipFilePrivate::raw.
Referenced by close().
{
  return p->raw;
}
bool QuaZipFile::isSequential () const [virtual]
Definition at line 337 of file quazipfile.cpp.
{
  return true;
}
bool QuaZipFile::open (OpenModemode) [virtual]
Returns true on success, false otherwise. Call getZipError() to get error code.
Note:
Since ZIP/UNZIP API provides buffered reading only, QuaZipFile does not support unbuffered reading. So do not pass QIODevice::Unbuffered flag in mode, or open will fail.
Definition at line 221 of file quazipfile.cpp.
Referenced by KbFirmware::_fileForBoard(), JlCompress::compressFile(), JlCompress::compressSubDir(), and JlCompress::extractFile().
{
  return open(mode, NULL);
}
bool QuaZipFile::open (OpenModemode, const char *password) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Argument password specifies a password to decrypt the file. If it is NULL then this function behaves just like open(OpenMode).
Definition at line 298 of file quazipfile.h.
    {return open(mode, NULL, NULL, false, password);}
bool QuaZipFile::open (OpenModemode, int *method, int *level, boolraw, const char *password = NULL)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Argument password specifies a password to decrypt the file.
An integers pointed by method and level will receive codes of the compression method and level used. See unzip.h.
If raw is true then no decompression is performed.
method should not be NULL. level can be NULL if you don't want to know the compression level.
Definition at line 226 of file quazipfile.cpp.
References QuaZipFilePrivate::caseSensitivity, QuaZip::close(), QuaZipFilePrivate::fileName, QuaZip::getMode(), QuaZip::getUnzFile(), QuaZip::getZipError(), QuaZip::hasCurrentFile(), QuaZipFilePrivate::internal, QuaZip::mdUnzip, QuaZip::open(), p, QuaZipFilePrivate::raw, QuaZipFilePrivate::resetZipError(), QuaZip::setCurrentFile(), QuaZipFilePrivate::setZipError(), UNZ_OK, unzOpenCurrentFile3(), QuaZipFilePrivate::zip, and QuaZipFilePrivate::zipError.
{
  p->resetZipError();
  if(isOpen()) {
    qWarning("QuaZipFile::open(): already opened");
    return false;
  }
  if(mode&Unbuffered) {
    qWarning("QuaZipFile::open(): Unbuffered mode is not supported");
    return false;
  }
  if((mode&ReadOnly)&&!(mode&WriteOnly)) {
    if(p->internal) {
      if(!p->zip->open(QuaZip::mdUnzip)) {
        p->setZipError(p->zip->getZipError());
        return false;
      }
      if(!p->zip->setCurrentFile(p->fileName, p->caseSensitivity)) {
        p->setZipError(p->zip->getZipError());
        p->zip->close();
        return false;
      }
    } else {
      if(p->zip==NULL) {
        qWarning("QuaZipFile::open(): zip is NULL");
        return false;
      }
      if(p->zip->getMode()!=QuaZip::mdUnzip) {
        qWarning("QuaZipFile::open(): file open mode %d incompatible with ZIP open mode %d",
            (int)mode, (int)p->zip->getMode());
        return false;
      }
      if(!p->zip->hasCurrentFile()) {
        qWarning("QuaZipFile::open(): zip does not have current file");
        return false;
      }
    }
    p->setZipError(unzOpenCurrentFile3(p->zip->getUnzFile(), method, level, (int)raw, password));
    if(p->zipError==UNZ_OK) {
      setOpenMode(mode);
      p->raw=raw;
      return true;
    } else
      return false;
  }
  qWarning("QuaZipFile::open(): open mode %d not supported by this function", (int)mode);
  return false;
}
bool QuaZipFile::open (OpenModemode, const QuaZipNewInfo &info, const char *password = NULL, quint32crc = 0, intmethod = Z_DEFLATED, intlevel = Z_DEFAULT_COMPRESSION, boolraw = false, intwindowBits = -MAX_WBITS, intmemLevel = MAX_MEM_LEVEL, intstrategy = Z_DEFAULT_STRATEGY)
info argument specifies information about file. It should at least specify a correct file name. Also, it is a good idea to specify correct timestamp (by default, current time will be used). See QuaZipNewInfo.
The password argument specifies the password for crypting. Pass NULL if you don't need any crypting. The crc argument was supposed to be used for crypting too, but then it turned out that it's false information, so you need to set it to 0 unless you want to use the raw mode (see below).
Arguments method and level specify compression method and level. The only method supported is Z_DEFLATED, but you may also specify 0 for no compression. If all of the files in the archive use both method 0 and either level 0 is explicitly specified or data descriptor writing is disabled with QuaZip::setDataDescriptorWritingEnabled(), then the resulting archive is supposed to be compatible with the 1.0 ZIP format version, should you need that. Except for this, level has no other effects with method 0.
If raw is true, no compression is performed. In this case, crc and uncompressedSize field of the info are required.
Arguments windowBits, memLevel, strategy provide zlib algorithms tuning. See deflateInit2() in zlib.
Definition at line 275 of file quazipfile.cpp.
References QuaZipNewInfo::comment, QuaZipFilePrivate::crc, QuaZipNewInfo::dateTime, zip_fileinfo::dosDate, zip_fileinfo::external_fa, QuaZipNewInfo::externalAttr, QuaZipNewInfo::extraGlobal, QuaZipNewInfo::extraLocal, QuaZip::getCommentCodec(), QuaZip::getFileNameCodec(), QuaZip::getMode(), QuaZip::getZipFile(), QuaZipFilePrivate::internal, zip_fileinfo::internal_fa, QuaZipNewInfo::internalAttr, QuaZip::isDataDescriptorWritingEnabled(), QuaZip::isZip64Enabled(), QuaZip::mdAdd, QuaZip::mdAppend, QuaZip::mdCreate, QuaZipNewInfo::name, p, QuaZipFilePrivate::raw, QuaZipFilePrivate::resetZipError(), QuaZipFilePrivate::setZipError(), tm_zip_s::tm_hour, tm_zip_s::tm_mday, tm_zip_s::tm_min, tm_zip_s::tm_mon, tm_zip_s::tm_sec, tm_zip_s::tm_year, zip_fileinfo::tmz_date, QuaZipFilePrivate::uncompressedSize, QuaZipNewInfo::uncompressedSize, UNZ_OK, QuaZipFilePrivate::writePos, QuaZipFilePrivate::zip, ZIP_WRITE_DATA_DESCRIPTOR, zipClearFlags(), QuaZipFilePrivate::zipError, zipOpenNewFileInZip3_64(), and zipSetFlags().
{
  zip_fileinfo info_z;
  p->resetZipError();
  if(isOpen()) {
    qWarning("QuaZipFile::open(): already opened");
    return false;
  }
  if((mode&WriteOnly)&&!(mode&ReadOnly)) {
    if(p->internal) {
      qWarning("QuaZipFile::open(): write mode is incompatible with internal QuaZip approach");
      return false;
    }
    if(p->zip==NULL) {
      qWarning("QuaZipFile::open(): zip is NULL");
      return false;
    }
    if(p->zip->getMode()!=QuaZip::mdCreate&&p->zip->getMode()!=QuaZip::mdAppend&&p->zip->getMode()!=QuaZip::mdAdd) {
      qWarning("QuaZipFile::open(): file open mode %d incompatible with ZIP open mode %d",
          (int)mode, (int)p->zip->getMode());
      return false;
    }
    info_z.tmz_date.tm_year=info.dateTime.date().year();
    info_z.tmz_date.tm_mon=info.dateTime.date().month() - 1;
    info_z.tmz_date.tm_mday=info.dateTime.date().day();
    info_z.tmz_date.tm_hour=info.dateTime.time().hour();
    info_z.tmz_date.tm_min=info.dateTime.time().minute();
    info_z.tmz_date.tm_sec=info.dateTime.time().second();
    info_z.dosDate = 0;
    info_z.internal_fa=(uLong)info.internalAttr;
    info_z.external_fa=(uLong)info.externalAttr;
    if (p->zip->isDataDescriptorWritingEnabled())
        zipSetFlags(p->zip->getZipFile(), ZIP_WRITE_DATA_DESCRIPTOR);
    else
        zipClearFlags(p->zip->getZipFile(), ZIP_WRITE_DATA_DESCRIPTOR);
    p->setZipError(zipOpenNewFileInZip3_64(p->zip->getZipFile(),
          p->zip->getFileNameCodec()->fromUnicode(info.name).constData(), &info_z,
          info.extraLocal.constData(), info.extraLocal.length(),
          info.extraGlobal.constData(), info.extraGlobal.length(),
          p->zip->getCommentCodec()->fromUnicode(info.comment).constData(),
          method, level, (int)raw,
          windowBits, memLevel, strategy,
          password, (uLong)crc, p->zip->isZip64Enabled()));
    if(p->zipError==UNZ_OK) {
      p->writePos=0;
      setOpenMode(mode);
      p->raw=raw;
      if(raw) {
        p->crc=crc;
        p->uncompressedSize=info.uncompressedSize;
      }
      return true;
    } else
      return false;
  }
  qWarning("QuaZipFile::open(): open mode %d not supported by this function", (int)mode);
  return false;
}
QuaZipFile& QuaZipFile::operator= (const QuaZipFile &that) [private]
qint64 QuaZipFile::pos () const [virtual]
Implementation of the QIODevice::pos(). When reading, this function is a wrapper to the ZIP/UNZIP unztell(), therefore it is unable to keep track of the ungetChar() calls (which is non-virtual and therefore is dangerous to reimplement). So if you are using ungetChar() feature of the QIODevice, this function reports incorrect value until you get back characters which you ungot.
When writing, pos() returns number of bytes already written (uncompressed unless you use raw mode).
Note:
Although QuaZipFile is a sequential device and therefore pos() should always return zero, it does not, because it would be misguiding. Keep this in mind.
This function returns -1 if the file or archive is not open.
Error code returned by getZipError() is not affected by this function call.
Definition at line 342 of file quazipfile.cpp.
References QuaZip::getUnzFile(), p, unztell(), QuaZipFilePrivate::writePos, and QuaZipFilePrivate::zip.
Referenced by bytesAvailable().
{
  if(p->zip==NULL) {
    qWarning("QuaZipFile::pos(): call setZipName() or setZip() first");
    return -1;
  }
  if(!isOpen()) {
    qWarning("QuaZipFile::pos(): file is not open");
    return -1;
  }
  if(openMode()&ReadOnly)
      // QIODevice::pos() is broken for sequential devices,
      // but thankfully bytesAvailable() returns the number of
      // bytes buffered, so we know how far ahead we are.
    return unztell(p->zip->getUnzFile()) - QIODevice::bytesAvailable();
  else
    return p->writePos;
}
qint64 QuaZipFile::readData (char *data, qint64maxSize) [protected]
Definition at line 457 of file quazipfile.cpp.
References QuaZip::getUnzFile(), p, QuaZipFilePrivate::setZipError(), UNZ_OK, unzReadCurrentFile(), and QuaZipFilePrivate::zip.
{
  p->setZipError(UNZ_OK);
  qint64 bytesRead=unzReadCurrentFile(p->zip->getUnzFile(), data, (unsigned)maxSize);
  if (bytesRead < 0) {
    p->setZipError((int) bytesRead);
    return -1;
  }
  return bytesRead;
}
void QuaZipFile::setFileName (const QString &fileName, QuaZip::CaseSensitivitycs = QuaZip::csDefault)
Will do nothing if at least one of the following conditions is met:
ZIP name has not been set yet (getZipName() returns null string).
This QuaZipFile is associated with external QuaZip. In this case you should call that QuaZip's setCurrentFile() function instead!
File is already open so setting the name is meaningless.
See Also:
QuaZip::setCurrentFile
Definition at line 191 of file quazipfile.cpp.
References QuaZipFilePrivate::caseSensitivity, QuaZipFilePrivate::fileName, QuaZipFilePrivate::internal, p, and QuaZipFilePrivate::zip.
{
  if(p->zip==NULL) {
    qWarning("QuaZipFile::setFileName(): call setZipName() first");
    return;
  }
  if(!p->internal) {
    qWarning("QuaZipFile::setFileName(): should not be used when not using internal QuaZip");
    return;
  }
  if(isOpen()) {
    qWarning("QuaZipFile::setFileName(): can not set file name for already opened file");
    return;
  }
  p->fileName=fileName;
  if (p->fileName.startsWith('/'))
      p->fileName = p->fileName.mid(1);
  p->caseSensitivity=cs;
}
void QuaZipFile::setZip (QuaZip *zip)
This function destroys internal QuaZip object, if any, and makes this QuaZipFile to use current file in the zip object for any further operations. See QuaZipFile(QuaZip*,QObject*) for the possible pitfalls.
Will do nothing if the file is currently open. You must close() it first.
Definition at line 178 of file quazipfile.cpp.
References QuaZipFilePrivate::fileName, QuaZipFilePrivate::internal, p, and QuaZipFilePrivate::zip.
{
  if(isOpen()) {
    qWarning("QuaZipFile::setZip(): file is already open - can not set ZIP");
    return;
  }
  if(p->zip!=NULL && p->internal)
    delete p->zip;
  p->zip=zip;
  p->fileName=QString();
  p->internal=false;
}
void QuaZipFile::setZipName (const QString &zipName)
Automatically creates internal QuaZip object and destroys previously created internal QuaZip object, if any.
Will do nothing if this file is already open. You must close() it first.
Definition at line 166 of file quazipfile.cpp.
References QuaZipFilePrivate::internal, p, and QuaZipFilePrivate::zip.
{
  if(isOpen()) {
    qWarning("QuaZipFile::setZipName(): file is already open - can not set ZIP name");
    return;
  }
  if(p->zip!=NULL && p->internal)
    delete p->zip;
  p->zip=new QuaZip(zipName);
  p->internal=true;
}
qint64 QuaZipFile::size () const [virtual]
This function returns csize() if the file is open for reading in raw mode, usize() if it is open for reading in normal mode and pos() if it is open for writing.
Returns -1 on error, call getZipError() to get error code.
Note:
This function returns file size despite that QuaZipFile is considered to be sequential device, for which size() should return bytesAvailable() instead. But its name would be very misguiding otherwise, so just keep in mind this inconsistence.
Definition at line 379 of file quazipfile.cpp.
References csize(), p, QuaZipFilePrivate::raw, usize(), and QuaZipFilePrivate::writePos.
Referenced by bytesAvailable().
{
  if(!isOpen()) {
    qWarning("QuaZipFile::atEnd(): file is not open");
    return -1;
  }
  if(openMode()&ReadOnly)
    return p->raw?csize():usize();
  else
    return p->writePos;
}
qint64 QuaZipFile::usize () const
Equivalent to calling getFileInfo() and then getting uncompressedSize field, but more convenient and faster. See getFileInfo() for a warning.
File must be open for reading before calling this function.
Returns -1 on error, call getZipError() to get error code.
Definition at line 402 of file quazipfile.cpp.
References QuaZip::getMode(), QuaZip::getUnzFile(), QuaZip::mdUnzip, p, QuaZipFilePrivate::setZipError(), unz_file_info64_s::uncompressed_size, UNZ_OK, unzGetCurrentFileInfo64(), QuaZipFilePrivate::zip, and QuaZipFilePrivate::zipError.
Referenced by size().
{
  unz_file_info64 info_z;
  p->setZipError(UNZ_OK);
  if(p->zip==NULL||p->zip->getMode()!=QuaZip::mdUnzip) return -1;
  p->setZipError(unzGetCurrentFileInfo64(p->zip->getUnzFile(), &info_z, NULL, 0, NULL, 0, NULL, 0));
  if(p->zipError!=UNZ_OK)
    return -1;
  return info_z.uncompressed_size;
}
qint64 QuaZipFile::writeData (const char *data, qint64maxSize) [protected]
Definition at line 468 of file quazipfile.cpp.
References QuaZip::getZipFile(), p, QuaZipFilePrivate::setZipError(), QuaZipFilePrivate::writePos, QuaZipFilePrivate::zip, ZIP_OK, QuaZipFilePrivate::zipError, and zipWriteInFileInZip().
{
  p->setZipError(ZIP_OK);
  p->setZipError(zipWriteInFileInZip(p->zip->getZipFile(), data, (uint)maxSize));
  if(p->zipError!=ZIP_OK) return -1;
  else {
    p->writePos+=maxSize;
    return maxSize;
  }
}
Friends And Related Function Documentation
friend class QuaZipFilePrivate [friend]
Definition at line 75 of file quazipfile.h.
Field Documentation
QuaZipFilePrivate* QuaZipFile::p [private]
Definition at line 78 of file quazipfile.h.
Referenced by atEnd(), close(), csize(), getActualFileName(), getCaseSensitivity(), getFileInfo(), getFileName(), getZip(), getZipError(), getZipName(), isRaw(), open(), pos(), readData(), setFileName(), setZip(), setZipName(), size(), usize(), writeData(), and ~QuaZipFile().
Author
Generated automatically by Doxygen for ckb-next from the source code.