src/ckb/quazip/quazip.cpp
NAME
src/ckb/quazip/quazip.cpp -
SYNOPSIS
#include <QFile>
#include <QFlags>
#include <QHash>
#include 'quazip.h'
Data Structures
class QuaZipPrivate
All the internal stuff for the QuaZip class.
Functions
template<typename TFileInfo > TFileInfo QuaZip_getFileInfo (QuaZip *zip, bool *ok)
template<> QuaZipFileInfo QuaZip_getFileInfo (QuaZip *zip, bool *ok)
template<> QuaZipFileInfo64 QuaZip_getFileInfo (QuaZip *zip, bool *ok)
template<> QString QuaZip_getFileInfo (QuaZip *zip, bool *ok)
Function Documentation
template<typename TFileInfo > TFileInfo QuaZip_getFileInfo (QuaZip *zip, bool *ok)
Definition at line 663 of file quazip.cpp.
References QuaZip::getCurrentFileInfo(), and QuaZip::getCurrentFileName().
{
    QuaZipFileInfo info;
    *ok = zip->getCurrentFileInfo(&info);
    return info;
}
template<> QuaZipFileInfo QuaZip_getFileInfo (QuaZip *zip, bool *ok)
Definition at line 663 of file quazip.cpp.
References QuaZip::getCurrentFileInfo().
{
    QuaZipFileInfo info;
    *ok = zip->getCurrentFileInfo(&info);
    return info;
}
template<> QuaZipFileInfo64 QuaZip_getFileInfo (QuaZip *zip, bool *ok)
Definition at line 671 of file quazip.cpp.
References QuaZip::getCurrentFileInfo().
{
    QuaZipFileInfo64 info;
    *ok = zip->getCurrentFileInfo(&info);
    return info;
}
template<> QString QuaZip_getFileInfo (QuaZip *zip, bool *ok)
Definition at line 679 of file quazip.cpp.
References QuaZip::getCurrentFileName().
{
    QString name = zip->getCurrentFileName();
    *ok = !name.isEmpty();
    return name;
}
Author
Generated automatically by Doxygen for ckb-next from the source code.