.TH "Ui" 3 "Wed May 24 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAnimAddDialog\fP"
.br
.ti -1c
.RI "class \fBAnimSettingDialog\fP"
.br
.ti -1c
.RI "class \fBExtraSettingsWidget\fP"
.br
.ti -1c
.RI "class \fBFwUpgradeDialog\fP"
.br
.ti -1c
.RI "class \fBGradientDialog\fP"
.br
.ti -1c
.RI "class \fBKbAnimWidget\fP"
.br
.ti -1c
.RI "class \fBKbBindWidget\fP"
.br
.ti -1c
.RI "class \fBKbLightWidget\fP"
.br
.ti -1c
.RI "class \fBKbProfileDialog\fP"
.br
.ti -1c
.RI "class \fBKbWidget\fP"
.br
.ti -1c
.RI "class \fBKPerfWidget\fP"
.br
.ti -1c
.RI "class \fBLayoutDialog\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.ti -1c
.RI "class \fBModeSelectDialog\fP"
.br
.ti -1c
.RI "class \fBMPerfWidget\fP"
.br
.ti -1c
.RI "class \fBRebindWidget\fP"
.br
.ti -1c
.RI "class \fBSettingsWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
