.TH "Ui::FwUpgradeDialog" 3 "Wed May 24 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::FwUpgradeDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/ui_fwupgradedialog\&.h>\fP
.PP
Inherits \fBUi_FwUpgradeDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetupUi\fP (\fBQDialog\fP *\fBFwUpgradeDialog\fP)"
.br
.ti -1c
.RI "void \fBretranslateUi\fP (\fBQDialog\fP *\fBFwUpgradeDialog\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "QGridLayout * \fBgridLayout_2\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_3\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel_4\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_4\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel_2\fP"
.br
.ti -1c
.RI "QLabel * \fBcurLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBnewLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBstatusLabel\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_2\fP"
.br
.ti -1c
.RI "QLabel * \fBdevLabel\fP"
.br
.ti -1c
.RI "QProgressBar * \fBprogressBar\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBactionButton\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBcancelButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 171 of file ui_fwupgradedialog\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ui_FwUpgradeDialog::retranslateUi (\fBQDialog\fP *FwUpgradeDialog)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Definition at line 155 of file ui_fwupgradedialog\&.h\&.
.PP
References Ui_FwUpgradeDialog::actionButton, Ui_FwUpgradeDialog::cancelButton, Ui_FwUpgradeDialog::curLabel, Ui_FwUpgradeDialog::devLabel, Ui_FwUpgradeDialog::label_2, Ui_FwUpgradeDialog::label_4, Ui_FwUpgradeDialog::newLabel, and Ui_FwUpgradeDialog::statusLabel\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.PP
.nf
156     {
157         FwUpgradeDialog->setWindowTitle(QApplication::translate("FwUpgradeDialog", "Firmware update", Q_NULLPTR));
158         label_4->setText(QApplication::translate("FwUpgradeDialog", "New:", Q_NULLPTR));
159         label_2->setText(QApplication::translate("FwUpgradeDialog", "Current:", Q_NULLPTR));
160         curLabel->setText(QApplication::translate("FwUpgradeDialog", "0\&.00", Q_NULLPTR));
161         newLabel->setText(QApplication::translate("FwUpgradeDialog", "0\&.00", Q_NULLPTR));
162         statusLabel->setText(QApplication::translate("FwUpgradeDialog", "Downloading new firmware, please wait\&.\&.\&.", Q_NULLPTR));
163         devLabel->setText(QApplication::translate("FwUpgradeDialog", "Device", Q_NULLPTR));
164         actionButton->setText(QApplication::translate("FwUpgradeDialog", "Start", Q_NULLPTR));
165         cancelButton->setText(QApplication::translate("FwUpgradeDialog", "Cancel", Q_NULLPTR));
166     } // retranslateUi
.fi
.SS "void Ui_FwUpgradeDialog::setupUi (\fBQDialog\fP *FwUpgradeDialog)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Definition at line 45 of file ui_fwupgradedialog\&.h\&.
.PP
References Ui_FwUpgradeDialog::actionButton, Ui_FwUpgradeDialog::cancelButton, Ui_FwUpgradeDialog::curLabel, Ui_FwUpgradeDialog::devLabel, Ui_FwUpgradeDialog::gridLayout, Ui_FwUpgradeDialog::gridLayout_2, Ui_FwUpgradeDialog::horizontalSpacer, Ui_FwUpgradeDialog::horizontalSpacer_2, Ui_FwUpgradeDialog::horizontalSpacer_3, Ui_FwUpgradeDialog::horizontalSpacer_4, Ui_FwUpgradeDialog::label_2, Ui_FwUpgradeDialog::label_4, Ui_FwUpgradeDialog::newLabel, Ui_FwUpgradeDialog::progressBar, Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::statusLabel\&.
.PP
Referenced by FwUpgradeDialog::FwUpgradeDialog()\&.
.PP
.nf
46     {
47         if (FwUpgradeDialog->objectName()\&.isEmpty())
48             FwUpgradeDialog->setObjectName(QStringLiteral("FwUpgradeDialog"));
49         FwUpgradeDialog->resize(420, 240);
50         QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
51         sizePolicy\&.setHorizontalStretch(0);
52         sizePolicy\&.setVerticalStretch(0);
53         sizePolicy\&.setHeightForWidth(FwUpgradeDialog->sizePolicy()\&.hasHeightForWidth());
54         FwUpgradeDialog->setSizePolicy(sizePolicy);
55         gridLayout_2 = new QGridLayout(FwUpgradeDialog);
56         gridLayout_2->setObjectName(QStringLiteral("gridLayout_2"));
57         horizontalSpacer = new QSpacerItem(127, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
58 
59         gridLayout_2->addItem(horizontalSpacer, 1, 0, 1, 1);
60 
61         gridLayout = new QGridLayout();
62         gridLayout->setObjectName(QStringLiteral("gridLayout"));
63         horizontalSpacer_3 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
64 
65         gridLayout->addItem(horizontalSpacer_3, 1, 0, 1, 1);
66 
67         label_4 = new QLabel(FwUpgradeDialog);
68         label_4->setObjectName(QStringLiteral("label_4"));
69         QFont font;
70         font\&.setBold(true);
71         font\&.setWeight(75);
72         label_4->setFont(font);
73 
74         gridLayout->addWidget(label_4, 1, 4, 1, 1);
75 
76         horizontalSpacer_4 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
77 
78         gridLayout->addItem(horizontalSpacer_4, 1, 6, 1, 1);
79 
80         label_2 = new QLabel(FwUpgradeDialog);
81         label_2->setObjectName(QStringLiteral("label_2"));
82         label_2->setFont(font);
83 
84         gridLayout->addWidget(label_2, 1, 1, 1, 1);
85 
86         curLabel = new QLabel(FwUpgradeDialog);
87         curLabel->setObjectName(QStringLiteral("curLabel"));
88 
89         gridLayout->addWidget(curLabel, 1, 2, 1, 1);
90 
91         newLabel = new QLabel(FwUpgradeDialog);
92         newLabel->setObjectName(QStringLiteral("newLabel"));
93 
94         gridLayout->addWidget(newLabel, 1, 5, 1, 1);
95 
96         statusLabel = new QLabel(FwUpgradeDialog);
97         statusLabel->setObjectName(QStringLiteral("statusLabel"));
98         QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Expanding);
99         sizePolicy1\&.setHorizontalStretch(0);
100         sizePolicy1\&.setVerticalStretch(0);
101         sizePolicy1\&.setHeightForWidth(statusLabel->sizePolicy()\&.hasHeightForWidth());
102         statusLabel->setSizePolicy(sizePolicy1);
103         statusLabel->setAlignment(Qt::AlignCenter);
104         statusLabel->setWordWrap(true);
105 
106         gridLayout->addWidget(statusLabel, 2, 0, 1, 7);
107 
108         horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
109 
110         gridLayout->addItem(horizontalSpacer_2, 1, 3, 1, 1);
111 
112         devLabel = new QLabel(FwUpgradeDialog);
113         devLabel->setObjectName(QStringLiteral("devLabel"));
114         QSizePolicy sizePolicy2(QSizePolicy::Preferred, QSizePolicy::Minimum);
115         sizePolicy2\&.setHorizontalStretch(0);
116         sizePolicy2\&.setVerticalStretch(0);
117         sizePolicy2\&.setHeightForWidth(devLabel->sizePolicy()\&.hasHeightForWidth());
118         devLabel->setSizePolicy(sizePolicy2);
119         devLabel->setFont(font);
120         devLabel->setAlignment(Qt::AlignCenter);
121 
122         gridLayout->addWidget(devLabel, 0, 0, 1, 7);
123 
124         progressBar = new QProgressBar(FwUpgradeDialog);
125         progressBar->setObjectName(QStringLiteral("progressBar"));
126         progressBar->setMaximum(0);
127         progressBar->setValue(0);
128 
129         gridLayout->addWidget(progressBar, 3, 0, 1, 7);
130 
131 
132         gridLayout_2->addLayout(gridLayout, 0, 0, 1, 3);
133 
134         actionButton = new QPushButton(FwUpgradeDialog);
135         actionButton->setObjectName(QStringLiteral("actionButton"));
136         actionButton->setEnabled(false);
137 
138         gridLayout_2->addWidget(actionButton, 1, 2, 1, 1);
139 
140         cancelButton = new QPushButton(FwUpgradeDialog);
141         cancelButton->setObjectName(QStringLiteral("cancelButton"));
142         cancelButton->setEnabled(false);
143 
144         gridLayout_2->addWidget(cancelButton, 1, 1, 1, 1);
145 
146 
147         retranslateUi(FwUpgradeDialog);
148 
149         actionButton->setDefault(true);
150 
151 
152         QMetaObject::connectSlotsByName(FwUpgradeDialog);
153     } // setupUi
.fi
.SH "Field Documentation"
.PP 
.SS "\fBQPushButton\fP* Ui_FwUpgradeDialog::actionButton\fC [inherited]\fP"

.PP
Definition at line 42 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::exec(), FwUpgradeDialog::fwUpdateFinished(), FwUpgradeDialog::on_actionButton_clicked(), Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "\fBQPushButton\fP* Ui_FwUpgradeDialog::cancelButton\fC [inherited]\fP"

.PP
Definition at line 43 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::exec(), FwUpgradeDialog::on_actionButton_clicked(), Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QLabel* Ui_FwUpgradeDialog::curLabel\fC [inherited]\fP"

.PP
Definition at line 36 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::FwUpgradeDialog(), Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QLabel* Ui_FwUpgradeDialog::devLabel\fC [inherited]\fP"

.PP
Definition at line 40 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::FwUpgradeDialog(), Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QGridLayout* Ui_FwUpgradeDialog::gridLayout\fC [inherited]\fP"

.PP
Definition at line 31 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.SS "QGridLayout* Ui_FwUpgradeDialog::gridLayout_2\fC [inherited]\fP"

.PP
Definition at line 29 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.SS "QSpacerItem* Ui_FwUpgradeDialog::horizontalSpacer\fC [inherited]\fP"

.PP
Definition at line 30 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.SS "QSpacerItem* Ui_FwUpgradeDialog::horizontalSpacer_2\fC [inherited]\fP"

.PP
Definition at line 39 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.SS "QSpacerItem* Ui_FwUpgradeDialog::horizontalSpacer_3\fC [inherited]\fP"

.PP
Definition at line 32 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.SS "QSpacerItem* Ui_FwUpgradeDialog::horizontalSpacer_4\fC [inherited]\fP"

.PP
Definition at line 34 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::setupUi()\&.
.SS "QLabel* Ui_FwUpgradeDialog::label_2\fC [inherited]\fP"

.PP
Definition at line 35 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QLabel* Ui_FwUpgradeDialog::label_4\fC [inherited]\fP"

.PP
Definition at line 33 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QLabel* Ui_FwUpgradeDialog::newLabel\fC [inherited]\fP"

.PP
Definition at line 37 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::exec(), FwUpgradeDialog::FwUpgradeDialog(), Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QProgressBar* Ui_FwUpgradeDialog::progressBar\fC [inherited]\fP"

.PP
Definition at line 41 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::exec(), FwUpgradeDialog::fwUpdateFinished(), FwUpgradeDialog::fwUpdateProgress(), FwUpgradeDialog::on_actionButton_clicked(), and Ui_FwUpgradeDialog::setupUi()\&.
.SS "QLabel* Ui_FwUpgradeDialog::statusLabel\fC [inherited]\fP"

.PP
Definition at line 38 of file ui_fwupgradedialog\&.h\&.
.PP
Referenced by FwUpgradeDialog::exec(), FwUpgradeDialog::fwUpdateFinished(), FwUpgradeDialog::on_actionButton_clicked(), Ui_FwUpgradeDialog::retranslateUi(), and Ui_FwUpgradeDialog::setupUi()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
