.TH "src/ckb/ui_kbprofiledialog.h" 3 "Thu Nov 2 2017" "Version v0.2.8 at branch master" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/ui_kbprofiledialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QDialog>\fP
.br
\fC#include <QtWidgets/QDialogButtonBox>\fP
.br
\fC#include <QtWidgets/QGridLayout>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QSpacerItem>\fP
.br
\fC#include 'rlistwidget\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUi_KbProfileDialog\fP"
.br
.ti -1c
.RI "class \fBUi::KbProfileDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
