AnimAddDialog
NAME
AnimAddDialog -
SYNOPSIS
#include <src/ckb/animadddialog.h>
Inherits QDialog.
Public Member Functions
AnimAddDialog (QWidget *parent, KbLight *light, const QStringList &keys)
~AnimAddDialog ()
const AnimScript * chosenScript ()
int chosenPreset ()
Private Slots
void on_animBox_activated (int index)
void on_presetBox_activated (int index)
void on_previewBox_clicked (bool checked)
Private Attributes
Ui::AnimAddDialog * ui
QList< const AnimScript * > scripts
KbLight * _light
QStringList _keys
bool showPreview
Detailed Description
Definition at line 12 of file animadddialog.h.
Constructor & Destructor Documentation
AnimAddDialog::AnimAddDialog (QWidget *parent, KbLight *light, const QStringList &keys) [explicit]
Definition at line 4 of file animadddialog.cpp.
References Ui_AnimAddDialog::animBox, AnimScript::list(), AnimScript::name(), on_animBox_activated(), scripts, Ui_AnimAddDialog::setupUi(), and ui.
                                                                                     :
    QDialog(parent),
    ui(new Ui::AnimAddDialog), _light(light), _keys(keys), showPreview(true)
{
    ui->setupUi(this);
    scripts = AnimScript::list();
    foreach(const AnimScript* script, scripts)
        ui->animBox->addItem(script->name());
    on_animBox_activated(0);
}
AnimAddDialog::~AnimAddDialog ()
Definition at line 15 of file animadddialog.cpp.
References _light, KbLight::stopPreview(), and ui.
                             {
    delete ui;
    _light->stopPreview();
}
Member Function Documentation
int AnimAddDialog::chosenPreset ()
Definition at line 24 of file animadddialog.cpp.
References Ui_AnimAddDialog::presetBox, and ui.
Referenced by KbLightWidget::on_animButton_clicked().
                               {
    return ui->presetBox->currentIndex();
}
const AnimScript * AnimAddDialog::chosenScript ()
Definition at line 20 of file animadddialog.cpp.
References Ui_AnimAddDialog::animBox, scripts, and ui.
Referenced by on_animBox_activated(), KbLightWidget::on_animButton_clicked(), and on_presetBox_activated().
                                             {
    return scripts[ui->animBox->currentIndex()];
}
void AnimAddDialog::on_animBox_activated (intindex) [private], [slot]
Definition at line 28 of file animadddialog.cpp.
References chosenScript(), on_presetBox_activated(), Ui_AnimAddDialog::presetBox, and ui.
Referenced by AnimAddDialog().
                                                 {
    // Update preset list
    ui->presetBox->clear();
    foreach(const QString& preset, chosenScript()->presets())
        ui->presetBox->addItem(preset);
    ui->presetBox->setCurrentIndex(0);
    on_presetBox_activated(0);
}
void AnimAddDialog::on_presetBox_activated (intindex) [private], [slot]
Definition at line 37 of file animadddialog.cpp.
References _keys, _light, chosenScript(), KbLight::previewAnim(), and showPreview.
Referenced by on_animBox_activated(), and on_previewBox_clicked().
                                                   {
    // Update preview
    if(showPreview)
        _light->previewAnim(chosenScript(), _keys, chosenScript()->preset(index));
}
void AnimAddDialog::on_previewBox_clicked (boolchecked) [private], [slot]
Definition at line 43 of file animadddialog.cpp.
References _light, on_presetBox_activated(), Ui_AnimAddDialog::presetBox, showPreview, KbLight::stopPreview(), and ui.
                                                     {
    showPreview = checked;
    if(showPreview)
        on_presetBox_activated(ui->presetBox->currentIndex());
    else
        _light->stopPreview();
}
Field Documentation
QStringList AnimAddDialog::_keys [private]
Definition at line 33 of file animadddialog.h.
Referenced by on_presetBox_activated().
KbLight* AnimAddDialog::_light [private]
Definition at line 32 of file animadddialog.h.
Referenced by on_presetBox_activated(), on_previewBox_clicked(), and ~AnimAddDialog().
QList<const AnimScript*> AnimAddDialog::scripts [private]
Definition at line 30 of file animadddialog.h.
Referenced by AnimAddDialog(), and chosenScript().
bool AnimAddDialog::showPreview [private]
Definition at line 34 of file animadddialog.h.
Referenced by on_presetBox_activated(), and on_previewBox_clicked().
Ui::AnimAddDialog* AnimAddDialog::ui [private]
Definition at line 29 of file animadddialog.h.
Referenced by AnimAddDialog(), chosenPreset(), chosenScript(), on_animBox_activated(), on_previewBox_clicked(), and ~AnimAddDialog().
Author
Generated automatically by Doxygen for ckb-next from the source code.