src/ckb/ckb-anim.h
NAME
src/ckb/ckb-anim.h -
SYNOPSIS
#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct ckb_key
struct ckb_runctx
struct ckb_gradient
Macros
#define M_PI 3.14159265358979323846
#define TRUE 1
#define FALSE 0
#define CKB_DOWN 1
#define CKB_UP 0
#define CKB_CONTAINER(macro) do { macro } while(0)
#define CKB_GUID(guid) CKB_CONTAINER( printf('guid '); printurl(guid); printf('\n'); )
#define CKB_NAME(name) CKB_CONTAINER( printf('name '); printurl(name); printf('\n'); )
#define CKB_VERSION(version) CKB_CONTAINER( printf('version '); printurl(version); printf('\n'); )
#define CKB_COPYRIGHT(year, author) CKB_CONTAINER( printf('author '); printurl(author); printf('\nyear %s\n', year); )
#define CKB_LICENSE(license) CKB_CONTAINER( printf('license '); printurl(license); printf('\n'); )
#define CKB_DESCRIPTION(description) CKB_CONTAINER( printf('description '); printurl(description); printf('\n'); )
#define CKB_PARAM(type, name, prefix, postfix, extra) CKB_CONTAINER( printf('param %s %s ', type, name); printurl(prefix); printf(' '); printurl(postfix); printf(' '); extra; printf('\n'); )
#define CKB_PARAM_LONG(name, prefix, postfix, default, min, max) CKB_PARAM('long', name, prefix, postfix, printf('%ld %ld %ld', (long)(default), (long)(min), (long)(max)))
#define CKB_PARAM_DOUBLE(name, prefix, postfix, default, min, max) CKB_PARAM('double', name, prefix, postfix, printf('%lf %lf %lf', (double)(default), (double)(min), (double)(max)))
#define CKB_PARAM_BOOL(name, text, default) CKB_PARAM('bool', name, text, '', printf((default) ? '1' : '0'))
#define CKB_PARAM_RGB(name, prefix, postfix, r, g, b) CKB_PARAM('rgb', name, prefix, postfix, printf('%02x%02x%02x', (unsigned char)(r), (unsigned char)(g), (unsigned char)(b)))
#define CKB_PARAM_ARGB(name, prefix, postfix, a, r, g, b) CKB_PARAM('argb', name, prefix, postfix, printf('%02x%02x%02x%02x', (unsigned char)(a), (unsigned char)(r), (unsigned char)(g), (unsigned char)(b)))
#define CKB_PARAM_GRADIENT(name, prefix, postfix, default) CKB_PARAM('gradient', name, prefix, postfix, printurl(default))
#define CKB_PARAM_AGRADIENT(name, prefix, postfix, default) CKB_PARAM('agradient', name, prefix, postfix, printurl(default))
#define CKB_PARAM_ANGLE(name, prefix, postfix, default) CKB_PARAM('angle', name, prefix, postfix, printf('%ld', (long)(default)))
#define CKB_PARAM_STRING(name, prefix, postfix, default) CKB_PARAM('string', name, prefix, postfix, printurl(default))
#define CKB_PARAM_LABEL(name, text) CKB_PARAM('label', name, text, '', )
#define CKB_PRESET_START(name) CKB_CONTAINER( printf('preset '); printurl(name); )
#define CKB_PRESET_PARAM(name, value) CKB_CONTAINER( printf(' %s=', name); printurl(value); )
#define CKB_PRESET_END CKB_CONTAINER( printf('\n'); )
#define CKB_KP_NONE 'none'
#define CKB_KP_NAME 'name'
#define CKB_KP_POSITION 'position'
#define CKB_KPMODE(mode) CKB_CONTAINER( printf('kpmode %s\n', mode); )
#define CKB_TIME_DURATION 'duration'
#define CKB_TIME_ABSOLUTE 'absolute'
#define CKB_TIMEMODE(mode) CKB_CONTAINER( printf('time %s\n', mode); )
#define CKB_REPEAT(enable) CKB_CONTAINER( printf('repeat %s\n', (enable) ? 'on' : 'off'); )
#define CKB_PREEMPT(enable) CKB_CONTAINER( printf('preempt %s\n', (enable) ? 'on' : 'off'); )
#define CKB_LIVEPARAMS(enable) CKB_CONTAINER( printf('parammode %s\n', (enable) ? 'live' : 'static'); )
#define CKB_PARSE_LONG(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%ld', value_ptr) == 1)
#define CKB_PARSE_DOUBLE(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%lf', value_ptr) == 1)
#define CKB_PARSE_BOOL(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%u', value_ptr) == 1)
#define CKB_PARSE_RGB(param_name, r_ptr, g_ptr, b_ptr) if(!strcmp(name, param_name) && sscanf(value, '%2hhx%2hhx%2hhx', r_ptr, g_ptr, b_ptr) == 3)
#define CKB_PARSE_ARGB(param_name, a_ptr, r_ptr, g_ptr, b_ptr) if(!strcmp(name, param_name) && sscanf(value, '%2hhx%2hhx%2hhx%2hhx', a_ptr, r_ptr, g_ptr, b_ptr) == 4)
#define CKB_PARSE_GRADIENT(param_name, gradient_ptr) if(!strcmp(name, param_name) && ckb_scan_grad(value, gradient_ptr, 0))
#define CKB_PARSE_AGRADIENT(param_name, gradient_ptr) if(!strcmp(name, param_name) && ckb_scan_grad(value, gradient_ptr, 1))
#define CKB_PARSE_ANGLE(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%ld', value_ptr) == 1)
#define CKB_PARSE_STRING(param_name) if(!strcmp(name, param_name))
#define CKB_REAL_ANGLE(angle) fmod((-(angle) + 90.) * M_PI / 180. + M_PI * 2., M_PI * 2.)
#define CKB_KEYNAME_MAX 12
#define CKB_KEYCLEAR(context) CKB_CONTAINER( ckb_key* key = context->keys; unsigned count = context->keycount; unsigned i = 0; for(; i < count; i++) key[i].a = key[i].r = key[i].g = key[i].b = 0; )
#define CKB_GRAD_MAX 100
#define CKB_MAX_WORD (4 * 1024)
Functions
int ckb_scan_grad (const char *string, ckb_gradient *gradient, int alpha)
void ckb_grad_color (float *a, float *r, float *g, float *b, const ckb_gradient *grad, float pos)
void ckb_alpha_blend (ckb_key *key, float a, float r, float g, float b)
void printurl (const char *src)
void urldecode (char *dst, const char *src)
void ckb_getline (char word1[(4 *1024)], char word2[(4 *1024)], char word3[(4 *1024)])
void ckb_info ()
void ckb_init (ckb_runctx *context)
void ckb_parameter (ckb_runctx *, const char *, const char *)
void ckb_keypress (ckb_runctx *, ckb_key *, int, int, int)
void ckb_start (ckb_runctx *, int)
void ckb_time (ckb_runctx *, double)
int ckb_frame (ckb_runctx *)
void ckb_read_params (ckb_runctx *ctx)
int main (int argc, char *argv[])
Data Structure Documentation
struct ckb_key
Definition at line 131 of file ckb-anim.h.
Data Fields:
unsigned char a
unsigned char b
unsigned char g
char name[12]
unsigned char r
int x
int y
struct ckb_runctx
Definition at line 138 of file ckb-anim.h.
Data Fields:
unsigned height
unsigned keycount
ckb_key * keys
unsigned width
struct ckb_gradient
Definition at line 152 of file ckb-anim.h.
Data Fields:
unsigned char a[100]
unsigned char b[100]
unsigned char g[100]
int ptcount
char pts[100]
unsigned char r[100]
Macro Definition Documentation
#define CKB_CONTAINER(macro) do { macro } while(0)
Definition at line 57 of file ckb-anim.h.
#define CKB_COPYRIGHT(year, author) CKB_CONTAINER( printf('author '); printurl(author); printf('\nyear %s\n', year); )
Definition at line 66 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_DESCRIPTION(description) CKB_CONTAINER( printf('description '); printurl(description); printf('\n'); )
Definition at line 70 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_DOWN 1
Definition at line 52 of file ckb-anim.h.
#define CKB_GRAD_MAX 100
Definition at line 151 of file ckb-anim.h.
#define CKB_GUID(guid) CKB_CONTAINER( printf('guid '); printurl(guid); printf('\n'); )
Definition at line 60 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_KEYCLEAR(context) CKB_CONTAINER( ckb_key* key = context->keys; unsigned count = context->keycount; unsigned i = 0; for(; i < count; i++) key[i].a = key[i].r = key[i].g = key[i].b = 0; )
Definition at line 148 of file ckb-anim.h.
Referenced by ckb_frame().
#define CKB_KEYNAME_MAX 12
Definition at line 130 of file ckb-anim.h.
Referenced by main().
#define CKB_KP_NAME 'name'
Definition at line 91 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_KP_NONE 'none'
Definition at line 90 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_KP_POSITION 'position'
Definition at line 92 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_KPMODE(mode) CKB_CONTAINER( printf('kpmode %s\n', mode); )
Definition at line 93 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_LICENSE(license) CKB_CONTAINER( printf('license '); printurl(license); printf('\n'); )
Definition at line 68 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_LIVEPARAMS(enable) CKB_CONTAINER( printf('parammode %s\n', (enable) ? 'live' : 'static'); )
Definition at line 104 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_MAX_WORD (4 * 1024)
Definition at line 238 of file ckb-anim.h.
Referenced by ckb_read_params(), and main().
#define CKB_NAME(name) CKB_CONTAINER( printf('name '); printurl(name); printf('\n'); )
Definition at line 62 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM(type, name, prefix, postfix, extra) CKB_CONTAINER( printf('param %s %s ', type, name); printurl(prefix); printf(' '); printurl(postfix); printf(' '); extra; printf('\n'); )
Definition at line 73 of file ckb-anim.h.
#define CKB_PARAM_AGRADIENT(name, prefix, postfix, default) CKB_PARAM('agradient', name, prefix, postfix, printurl(default))
Definition at line 80 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM_ANGLE(name, prefix, postfix, default) CKB_PARAM('angle', name, prefix, postfix, printf('%ld', (long)(default)))
Definition at line 81 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM_ARGB(name, prefix, postfix, a, r, g, b) CKB_PARAM('argb', name, prefix, postfix, printf('%02x%02x%02x%02x', (unsigned char)(a), (unsigned char)(r), (unsigned char)(g), (unsigned char)(b)))
Definition at line 78 of file ckb-anim.h.
#define CKB_PARAM_BOOL(name, text, default) CKB_PARAM('bool', name, text, '', printf((default) ? '1' : '0'))
Definition at line 76 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM_DOUBLE(name, prefix, postfix, default, min, max) CKB_PARAM('double', name, prefix, postfix, printf('%lf %lf %lf', (double)(default), (double)(min), (double)(max)))
Definition at line 75 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM_GRADIENT(name, prefix, postfix, default) CKB_PARAM('gradient', name, prefix, postfix, printurl(default))
Definition at line 79 of file ckb-anim.h.
#define CKB_PARAM_LABEL(name, text) CKB_PARAM('label', name, text, '', )
Definition at line 83 of file ckb-anim.h.
#define CKB_PARAM_LONG(name, prefix, postfix, default, min, max) CKB_PARAM('long', name, prefix, postfix, printf('%ld %ld %ld', (long)(default), (long)(min), (long)(max)))
Definition at line 74 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM_RGB(name, prefix, postfix, r, g, b) CKB_PARAM('rgb', name, prefix, postfix, printf('%02x%02x%02x', (unsigned char)(r), (unsigned char)(g), (unsigned char)(b)))
Definition at line 77 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PARAM_STRING(name, prefix, postfix, default) CKB_PARAM('string', name, prefix, postfix, printurl(default))
Definition at line 82 of file ckb-anim.h.
#define CKB_PARSE_AGRADIENT(param_name, gradient_ptr) if(!strcmp(name, param_name) && ckb_scan_grad(value, gradient_ptr, 1))
Definition at line 121 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_PARSE_ANGLE(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%ld', value_ptr) == 1)
Definition at line 122 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_PARSE_ARGB(param_name, a_ptr, r_ptr, g_ptr, b_ptr) if(!strcmp(name, param_name) && sscanf(value, '%2hhx%2hhx%2hhx%2hhx', a_ptr, r_ptr, g_ptr, b_ptr) == 4)
Definition at line 119 of file ckb-anim.h.
#define CKB_PARSE_BOOL(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%u', value_ptr) == 1)
Definition at line 117 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_PARSE_DOUBLE(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%lf', value_ptr) == 1)
Definition at line 116 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_PARSE_GRADIENT(param_name, gradient_ptr) if(!strcmp(name, param_name) && ckb_scan_grad(value, gradient_ptr, 0))
Definition at line 120 of file ckb-anim.h.
#define CKB_PARSE_LONG(param_name, value_ptr) if(!strcmp(name, param_name) && sscanf(value, '%ld', value_ptr) == 1)
Definition at line 115 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_PARSE_RGB(param_name, r_ptr, g_ptr, b_ptr) if(!strcmp(name, param_name) && sscanf(value, '%2hhx%2hhx%2hhx', r_ptr, g_ptr, b_ptr) == 3)
Definition at line 118 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_PARSE_STRING(param_name) if(!strcmp(name, param_name))
Definition at line 123 of file ckb-anim.h.
#define CKB_PREEMPT(enable) CKB_CONTAINER( printf('preempt %s\n', (enable) ? 'on' : 'off'); )
Definition at line 102 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PRESET_END CKB_CONTAINER( printf('\n'); )
Definition at line 87 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PRESET_PARAM(name, value) CKB_CONTAINER( printf(' %s=', name); printurl(value); )
Definition at line 86 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_PRESET_START(name) CKB_CONTAINER( printf('preset '); printurl(name); )
Definition at line 85 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_REAL_ANGLE(angle) fmod((-(angle) + 90.) * M_PI / 180. + M_PI * 2., M_PI * 2.)
Definition at line 127 of file ckb-anim.h.
Referenced by ckb_parameter().
#define CKB_REPEAT(enable) CKB_CONTAINER( printf('repeat %s\n', (enable) ? 'on' : 'off'); )
Definition at line 99 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_TIME_ABSOLUTE 'absolute'
Definition at line 96 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_TIME_DURATION 'duration'
Definition at line 95 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_TIMEMODE(mode) CKB_CONTAINER( printf('time %s\n', mode); )
Definition at line 97 of file ckb-anim.h.
Referenced by ckb_info().
#define CKB_UP 0
Definition at line 53 of file ckb-anim.h.
#define CKB_VERSION(version) CKB_CONTAINER( printf('version '); printurl(version); printf('\n'); )
Definition at line 64 of file ckb-anim.h.
Referenced by ckb_info().
#define FALSE 0
Definition at line 49 of file ckb-anim.h.
Referenced by ckb_info().
#define M_PI 3.14159265358979323846
Definition at line 42 of file ckb-anim.h.
Referenced by ckb_frame(), and ckb_parameter().
#define TRUE 1
Definition at line 46 of file ckb-anim.h.
Referenced by ckb_info().
Function Documentation
void ckb_alpha_blend (ckb_key *key, floata, floatr, floatg, floatb)
Definition at line 283 of file ckb-anim.h.
References ckb_key::a, ckb_key::b, ckb_key::g, and ckb_key::r.
Referenced by ckb_frame().
                                                                      {
    a /= 255.f;
    float ka = key->a / 255.f;
    float a2 = a + (1.f - a) * ka;
    if(a2 == 0.f){
        key->a = key->r = key->g = key->b = 0;
        return;
    }
    key->a = round(a2 * 255.f);
    key->r = round((r * a + key->r * ka * (1.f - a)) / a2);
    key->g = round((g * a + key->g * ka * (1.f - a)) / a2);
    key->b = round((b * a + key->b * ka * (1.f - a)) / a2);
}
int ckb_frame (ckb_runctx *)
Definition at line 137 of file main.c.
References ckb_key::a, aa, ab, ag, angle, ANGLE, anim, ANIM_MAX, animcolor, animlength, ar, ckb_key::b, ckb_alpha_blend(), ckb_grad_color(), CKB_KEYCLEAR, counter_clock, drop, DROP_MAX, ffade, frame, ckb_key::g, getFreqDec(), keyAnim::gradient, ckb_runctx::height, HOLD, ckb_runctx::keycount, ckb_runctx::keys, M_PI, max(), min(), phase, power, powers, pressestofull, ckb_key::r, randomBright, randomize, symmetric, keyAnim::target, width, ckb_runctx::width, x, and y.
Referenced by main().
                                  {
    // Draw key colors
    unsigned count = context->keycount;
    for(unsigned i = 0; i < count; i++){
        float phase = anim[i].target;
        if(phase == HOLD)
            phase = 0.f;
        else if(phase < 0.f)
            phase = 1.f;
        ckb_key* key = context->keys + i;
        float a, r, g, b;
        ckb_gradient thisGradient;
        if (randomize) {
            thisGradient = anim[i].gradient;
        } else {
            thisGradient = animcolor;
        }
        ckb_grad_color(&a, &r, &g, &b, &thisGradient, phase * 100.);
        key->a = a;
        key->r = r;
        key->g = g;
        key->b = b;
    }
    return 0;
}
void ckb_getline (charword1[(4 *1024)], charword2[(4 *1024)], charword3[(4 *1024)])
Definition at line 239 of file ckb-anim.h.
References urldecode().
Referenced by ckb_read_params(), and main().
                                                                                              {
    char line[CKB_MAX_WORD * 3 + 3];
    fgets(line, sizeof(line), stdin);
    word1[0] = word1[1] = word1[2] = 0;
    int res = sscanf(line, "%s %s %s", word1, word2, word3);
    if(res >= 1)
        urldecode(word1, word1);
    if(res >= 2)
        urldecode(word2, word2);
    if(res >= 3)
        urldecode(word3, word3);
    line[strlen(line) - 1] = 0;
}
void ckb_grad_color (float *a, float *r, float *g, float *b, const ckb_gradient *grad, floatpos)
Definition at line 254 of file ckb-anim.h.
References ckb_gradient::a, ckb_gradient::b, ckb_gradient::g, ckb_gradient::ptcount, ckb_gradient::pts, and ckb_gradient::r.
Referenced by ckb_frame(), and ckb_keypress().
                                                                                                {
    // Find the points surrounding this position
    int count = grad->ptcount;
    if(count == 0){
        *a = *r = *g = *b = 0.f;
        return;
    }
    int i = 1;
    for(; i < count; i++){
        if(grad->pts[i] >= pos)
            break;
    }
    // Get color by linear interpolation. Premultiply the alpha value so that it returns the expected color
    // (i.e. stops with zero opacity won't contribute to color)
    float distance = grad->pts[i] - grad->pts[i - 1];
    float dx = (pos - grad->pts[i - 1]) / distance;
    float a1 = grad->a[i] / 255., a2 = grad->a[i - 1] / 255.;
    float a3 = *a = a1 * dx + a2 * (1.f - dx);
    if(a3 == 0.){
        *a = *r = *g = *b = 0.f;
        return;
    }
    *a *= 255.f;
    *r = (grad->r[i] * a1 * dx + grad->r[i - 1] * a2 * (1.f - dx)) / a3;
    *g = (grad->g[i] * a1 * dx + grad->g[i - 1] * a2 * (1.f - dx)) / a3;
    *b = (grad->b[i] * a1 * dx + grad->b[i - 1] * a2 * (1.f - dx)) / a3;
}
void ckb_info ()
Definition at line 5 of file main.c.
References CKB_COPYRIGHT, CKB_DESCRIPTION, CKB_GUID, CKB_KP_NAME, CKB_KP_NONE, CKB_KP_POSITION, CKB_KPMODE, CKB_LICENSE, CKB_LIVEPARAMS, CKB_NAME, CKB_PARAM_AGRADIENT, CKB_PARAM_ANGLE, CKB_PARAM_BOOL, CKB_PARAM_DOUBLE, CKB_PARAM_LONG, CKB_PARAM_RGB, CKB_PREEMPT, CKB_PRESET_END, CKB_PRESET_PARAM, CKB_PRESET_START, CKB_REPEAT, CKB_TIME_ABSOLUTE, CKB_TIME_DURATION, CKB_TIMEMODE, CKB_VERSION, FALSE, and TRUE.
Referenced by main(), and quitWithLock().
               {
    // Plugin info
    CKB_NAME("Gradient");
    CKB_VERSION("0.9");
    CKB_COPYRIGHT("2014-2016", "MSC");
    CKB_LICENSE("GPLv2");
    CKB_GUID("{54DD2975-E192-457D-BCFC-D912A24E33B4}");
    CKB_DESCRIPTION("A transition from one color to another.");
    // Effect parameters
    CKB_PARAM_AGRADIENT("color", "Color:", "", "ffffffff");
    CKB_PARAM_BOOL("kphold", "Freeze until key is released", TRUE);
    CKB_PARAM_BOOL("randomize", "Randomly select from gradient", 0);
    // Timing/input parameters
    CKB_KPMODE(CKB_KP_NAME);
    CKB_TIMEMODE(CKB_TIME_DURATION);
    CKB_LIVEPARAMS(TRUE);
    // Presets
    CKB_PRESET_START("Fade in");
    CKB_PRESET_PARAM("color", "ff000000");
    CKB_PRESET_PARAM("duration", "1.0");
    CKB_PRESET_PARAM("stop", "0");
    CKB_PRESET_PARAM("kpstop", "0");
    CKB_PRESET_END;
    CKB_PRESET_START("Rainbow");
    CKB_PRESET_PARAM("color", "0:ffff0000 17:ffffff00 33:ff00ff00 50:ff00ffff 67:ff0000ff 83:ffff00ff 100:ffff0000");
    CKB_PRESET_PARAM("duration", "2.0");
    CKB_PRESET_END;
    CKB_PRESET_START("Type lighting");
    CKB_PRESET_PARAM("duration", "1.0");
    CKB_PRESET_PARAM("trigger", "0");
    CKB_PRESET_PARAM("kptrigger", "1");
    CKB_PRESET_END;
}
void ckb_init (ckb_runctx *context)
Definition at line 57 of file main.c.
References ckb_runctx::height, kbsize, ckb_runctx::keycount, ckb_runctx::keys, NONE, pas, ckb_runctx::width, keyanim::x, ckb_key::x, keyanim::y, and ckb_key::y.
Referenced by main().
                                  {
    // Initialize all keys to 100% (animation over)
    srand((unsigned)time(NULL));
    unsigned count = context->keycount;
    anim = malloc(count * sizeof *anim);
    for(unsigned i = 0; i < count; i++) {
        anim[i].target = NONE;
    }
}
void ckb_keypress (ckb_runctx *, ckb_key *, int, int, int)
Definition at line 75 of file main.c.
References ckb_gradient::a, anim_add(), anim_remove(), ckb_gradient::b, ckb_grad_color(), drop_add(), ckb_gradient::g, keyAnim::gradient, ckb_runctx::height, HOLD, ckb_runctx::keys, kphold, kprelease, NONE, ckb_gradient::ptcount, ckb_gradient::pts, ckb_gradient::r, randomize, keyAnim::target, and ckb_runctx::width.
Referenced by main().
                                                                             {
    // Start or stop animation on key
    int i = key - context->keys;
    if(state){
        if (randomize) {
            float a, r, g, b;
            float colorChoice = (float)rand()/(float)(RAND_MAX);
            ckb_grad_color(&a, &r, &g, &b, &animcolor, colorChoice * 100.);
            ckb_gradient newGradient = { 0 };
            newGradient.ptcount = 2;
            newGradient.pts[0] = 0;
            newGradient.pts[1] = 100;
            newGradient.a[0] = 255;
            newGradient.b[0] = b;
            newGradient.g[0] = g;
            newGradient.r[0] = r;
            newGradient.a[1] = 0;
            newGradient.b[1] = b;
            newGradient.g[1] = g;
            newGradient.r[1] = r;
            anim[i].gradient = newGradient;
        }
        if(kphold) {
            anim[i].target = HOLD;
        } else {
            anim[i].target = 0.f;
        }
    } else {
        if(kprelease) {
            anim[i].target = NONE;
        }
        else if(kphold) {
            anim[i].target = 0.f;
        }
    }
}
void ckb_parameter (ckb_runctx *, const char *, const char *)
Definition at line 68 of file main.c.
References aa, ab, ag, angle, animlength, ar, CKB_PARSE_AGRADIENT, CKB_PARSE_ANGLE, CKB_PARSE_BOOL, CKB_PARSE_DOUBLE, CKB_PARSE_LONG, CKB_PARSE_RGB, CKB_REAL_ANGLE, counter_clock, fadein, ffade, ckb_runctx::height, kphold, kprelease, left, M_PI, maxsize, period, power, pressestofull, randomBright, randomize, spawn, speed, symmetric, top, useopacity, width, ckb_runctx::width, x, x_offset, y, and y_offset.
Referenced by ckb_read_params().
                                                                            {
    CKB_PARSE_AGRADIENT("color", &animcolor){}
    CKB_PARSE_BOOL("kphold", &kphold){}
    CKB_PARSE_BOOL("kprelease", &kprelease){}
    CKB_PARSE_BOOL("randomize", &randomize){}
}
void ckb_read_params (ckb_runctx *ctx)
Definition at line 349 of file ckb-anim.h.
References ckb_getline(), CKB_MAX_WORD, and ckb_parameter().
Referenced by main().
                                     {
    char cmd[CKB_MAX_WORD], param[CKB_MAX_WORD], value[CKB_MAX_WORD];
    do {
        ckb_getline(cmd, param, value);
        if(!*cmd){
            printf("Error [ckb-main]: Reached EOF reading parameters");
            return;
        }
        if(!strcmp(cmd, "end") && !strcmp(param, "params"))
            break;
        if(strcmp(cmd, "param"))
            continue;
        ckb_parameter(ctx, param, value);
    } while(1);
}
int ckb_scan_grad (const char *string, ckb_gradient *gradient, intalpha)
Definition at line 298 of file ckb-anim.h.
References ckb_gradient::a, ckb_gradient::b, ckb_gradient::g, ckb_gradient::ptcount, ckb_gradient::pts, and ckb_gradient::r.
                                                                        {
    char pos = -1;
    unsigned char a = 255, r, g, b;
    int count = 0;
    while(1){
        int scanned = 0;
        char newpos;
        if(sscanf(string, "%hhd:%2hhx%2hhx%2hhx%2hhx%n", &newpos, &a, &r, &g, &b, &scanned) != 5)
            break;
        string += scanned;
        // Don't allow stops out-of-order or past 100
        if(newpos <= pos || newpos > 100)
            return 0;
        pos = newpos;
        if(!alpha)
            a = 255;
        gradient->pts[count] = pos;
        gradient->a[count] = a;
        gradient->r[count] = r;
        gradient->g[count] = g;
        gradient->b[count] = b;
        count++;
    }
    if(count == 0){
        // If nothing was read, try a single ARGB constant.
        if(sscanf(string, "%2hhx%2hhx%2hhx%2hhx", &a, &r, &g, &b) != 4)
            return 0;
        count = 2;
        gradient->pts[0] = 0;
        gradient->pts[1] = 100;
        gradient->a[0] = a;
        gradient->a[1] = 0;
        gradient->r[0] = gradient->r[1] = r;
        gradient->g[0] = gradient->g[1] = g;
        gradient->b[0] = gradient->b[1] = b;
    }
    if(count < 2)
        return 0;
    gradient->ptcount = count;
    return 1;
}
void ckb_start (ckb_runctx *, int)
Definition at line 114 of file main.c.
References rgb::a, ckb_key::a, anim_add(), anim_remove(), rgb::b, ckb_key::b, fadein, frame, rgb::g, ckb_key::g, ckb_runctx::height, ckb_runctx::keycount, ckb_runctx::keys, kprelease, left, newtarget(), NONE, phase, rgb::r, ckb_key::r, keyAnim::target, tick, top, ckb_runctx::width, x, x_offset, y, and y_offset.
Referenced by main().
                                              {
    // Start/stop all keys
    unsigned count = context->keycount;
    if(state) {
        memset(anim, 0, count * sizeof *anim);
    } else {
        for(unsigned i = 0; i < count; i++) {
            anim[i].target = NONE;
        }
    }
}
void ckb_time (ckb_runctx *, double)
Definition at line 126 of file main.c.
References anim, ANIM_MAX, animlength, current, drop, drop_add(), DROP_MAX, frame, ckb_runctx::height, kbsize, ckb_runctx::keycount, maxsize, newtarget(), period, phase, spawn, speed, target, keyAnim::target, tick, keyanim::timing, keyanim::usages, width, and ckb_runctx::width.
Referenced by main().
                                                {
    // Advance animation on each key
    unsigned count = context->keycount;
    for(unsigned i = 0; i < count; i++){
        float phase = anim[i].target;
        if(phase > 1.f || phase < 0.f)
            continue;
        anim[i].target = phase + delta;
    }
}
int main (intargc, char *argv[])
Definition at line 365 of file ckb-anim.h.
References ckb_key::a, ckb_key::b, ckb_frame(), ckb_getline(), ckb_info(), ckb_init(), CKB_KEYNAME_MAX, ckb_keypress(), CKB_MAX_WORD, ckb_read_params(), ckb_start(), ckb_time(), ckb_key::g, ckb_runctx::height, ckb_runctx::keycount, ckb_runctx::keys, ckb_key::name, ckb_key::r, ckb_runctx::width, x, ckb_key::x, y, and ckb_key::y.
                                {
    if(argc == 2){
        if(!strcmp(argv[1], "--ckb-info")){
            ckb_info();
            fflush(stdout);
            return 0;
        } else if(!strcmp(argv[1], "--ckb-run")){
            ckb_runctx ctx;
            // Read the keymap lines
            char cmd[CKB_MAX_WORD], param[CKB_MAX_WORD], value[CKB_MAX_WORD];
            // Skip anything up until "begin keymap"
            do {
                ckb_getline(cmd, param, value);
                if(!*cmd){
                    // If end-of-file is reached, abort
                    printf("Error [ckb-main]: Reached EOF looking for \"begin keymap\"");
                    return -2;
                }
            } while(strcmp(cmd, "begin") || strcmp(param, "keymap"));
            ckb_getline(cmd, param, value);
            unsigned keycount;
            if(strcmp(cmd, "keycount") || sscanf(param, "%u", &keycount) != 1 || keycount == 0){
                // If keycount isn't the next line, something is wrong
                printf("Error [ckb-main]: \"begin keymap\" not followed with \"keycount\"");
                return -3;
            }
            ctx.keys = (ckb_key*)calloc(keycount, sizeof(ckb_key));
            ctx.keycount = keycount;
            unsigned max_x = 0, max_y = 0;
            unsigned i = 0;
            for(; i < ctx.keycount; i++){
                ckb_getline(cmd, param, value);
                unsigned x, y;
                if(strcmp(cmd, "key") || !*param || !sscanf(value, "%u,%u", &x, &y)){
                    i--;
                    continue;
                }
                ckb_key* key = ctx.keys + i;
                strncpy(key->name, param, CKB_KEYNAME_MAX);
                key->x = x;
                key->y = y;
                if(x > max_x)
                    max_x = x;
                if(y > max_y)
                    max_y = y;
            }
            ctx.width = max_x + 1;
            ctx.height = max_y + 1;
            // Skip anything else until "end keymap"
            do {
                ckb_getline(cmd, param, value);
                if(!*cmd){
                    printf("Error [ckb-main]: Reached EOF looking for \"end keymap\"");
                    return -2;
                }
            } while(strcmp(cmd, "end") || strcmp(param, "keymap"));
            // Run init function
            ckb_init(&ctx);
            // Skip anything else until "begin params"
            do {
                ckb_getline(cmd, param, value);
                if(!*cmd){
                    printf("Error [ckb-main]: Reached EOF looking for \"begin params\"");
                    return -2;
                }
            } while(strcmp(cmd, "begin") || strcmp(param, "params"));
            // Parse parameters
            ckb_read_params(&ctx);
            // Skip anything else until "begin run"
            do {
                ckb_getline(cmd, param, value);
                if(!*cmd){
                    printf("Error [ckb-main]: Reached EOF looking for \"begin run\"");
                    return -2;
                }
            } while(strcmp(cmd, "begin") || strcmp(param, "run"));
            // Run the main loop
            printf("begin run\n");
            fflush(stdout);
            while(1){
                ckb_getline(cmd, param, value);
                if(!*cmd || (!strcmp(cmd, "end") && !strcmp(param, "run")))
                    break;
                // Parse input
                if(!strcmp(cmd, "start"))
                    ckb_start(&ctx, 1);
                else if(!strcmp(cmd, "stop"))
                    ckb_start(&ctx, 0);
                else if(!strcmp(cmd, "begin") && !strcmp(param, "params"))
                    ckb_read_params(&ctx);
                else if(!strcmp(cmd, "key")){
                    int x, y;
                    if(sscanf(param, "%d,%d", &x, &y) == 2){
                        // Find a key with this position
                        ckb_key* key = 0;
                        for(i = 0; i < keycount; i++){
                            if(ctx.keys[i].x == x && ctx.keys[i].y == y){
                                key = ctx.keys + i;
                                break;
                            }
                        }
                        if(key)
                            ckb_keypress(&ctx, key, key->x, key->y, !strcmp(value, "down"));
                        else
                            ckb_keypress(&ctx, 0, x, y, !strcmp(value, "down"));
                    } else {
                        // Find a key with this name
                        ckb_key* key = 0;
                        for(i = 0; i < keycount; i++){
                            if(!strcmp(ctx.keys[i].name, param)){
                                key = ctx.keys + i;
                                break;
                            }
                        }
                        if(key)
                            ckb_keypress(&ctx, key, key->x, key->y, !strcmp(value, "down"));
                    }
                } else if(!strcmp(cmd, "frame")){
                    int end = ckb_frame(&ctx);
                    // Output the frame
                    printf("begin frame\n");
                    for(i = 0; i < ctx.keycount; i++){
                        ckb_key* key = ctx.keys + i;
                        printf("argb %s %02hhx%02hhx%02hhx%02hhx\n", key->name, key->a, key->r, key->g, key->b);
                    }
                    printf("end frame\n");
                    if(end)
                        break;
                    fflush(stdout);
                } else {
                    double delta = 0.;
                    if(!strcmp(cmd, "time") && sscanf(param, "%lf", &delta) == 1)
                        ckb_time(&ctx, delta);
                }
            }
            printf("end run\n");
            fflush(stdout);
            free(ctx.keys);
            return 0;
        }
    }
    printf("This program must be run from within ckb\n");
    return -1;
}
void printurl (const char *src)
Definition at line 178 of file ckb-anim.h.
                              {
    char out[strlen(src) * 3 + 1];
    char* dst = out;
    char s;
    while((s = *src++)){
        if(s <= ',' || s == '/' ||
                (s >= ':' && s <= '@') ||
                s == '[' || s == ']' ||
                s >= 0x7F){
            char a = s >> 4, b = s & 0xF;
            if(a >= 10)
                a += 'A' - 10;
            else
                a += '0';
            if(b >= 10)
                b += 'A' - 10;
            else
                b += '0';
            dst[0] = '%';
            dst[1] = a;
            dst[2] = b;
            dst += 3;
        } else
            *dst++ = s;
    }
    *dst = '\0';
    printf("%s", out);
}
void urldecode (char *dst, const char *src)
Definition at line 208 of file ckb-anim.h.
Referenced by ckb_getline().
                                          {
    char a, b;
    char s;
    while((s = *src)){
        if((s == '%') &&
                ((a = src[1]) && (b = src[2])) &&
                (isxdigit(a) && isxdigit(b))){
            if(a >= 'a')
                a -= 'a'-'A';
            if(a >= 'A')
                a -= 'A' - 10;
            else
                a -= '0';
            if(b >= 'a')
                b -= 'a'-'A';
            if(b >= 'A')
                b -= 'A' - 10;
            else
                b -= '0';
            *dst++ = 16*a + b;
            src += 3;
        } else {
            *dst++ = s;
            src++;
        }
    }
    *dst = '\0';
}
Author
Generated automatically by Doxygen for ckb-next from the source code.