.TH "CkbSettings" 3 "Sun Jun 4 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CkbSettings \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/ckbsettings\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCkbSettings\fP ()"
.br
.ti -1c
.RI "\fBCkbSettings\fP (const QString &basePath, bool eraseExisting=false)"
.br
.ti -1c
.RI "\fBCkbSettings\fP (QSettings &settings)"
.br
.ti -1c
.RI "\fB~CkbSettings\fP ()"
.br
.ti -1c
.RI "void \fBbeginGroup\fP (const QString &prefix)"
.br
.ti -1c
.RI "void \fBendGroup\fP ()"
.br
.ti -1c
.RI "QStringList \fBchildGroups\fP () const "
.br
.ti -1c
.RI "QStringList \fBchildKeys\fP () const "
.br
.ti -1c
.RI "bool \fBcontains\fP (const QString &\fBkey\fP) const "
.br
.ti -1c
.RI "bool \fBcontainsGroup\fP (const QString &group)"
.br
.ti -1c
.RI "QVariant \fBvalue\fP (const QString &\fBkey\fP, const QVariant &defaultValue=QVariant()) const "
.br
.ti -1c
.RI "void \fBsetValue\fP (const QString &\fBkey\fP, const QVariant &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBremove\fP (const QString &\fBkey\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QVariant \fBget\fP (const QString &\fBkey\fP, const QVariant &defaultValue=QVariant())"
.br
.ti -1c
.RI "static void \fBset\fP (const QString &\fBkey\fP, const QVariant &\fBvalue\fP)"
.br
.ti -1c
.RI "static bool \fBinformIfNonWritable\fP ()"
.br
.RI "\fIIf config files are writable, return false\&. Otherwise give the user a pop up and return true\&. \fP"
.ti -1c
.RI "static bool \fBisWritable\fP ()"
.br
.RI "\fISetter & getter for it\&. \fP"
.ti -1c
.RI "static void \fBsetWritable\fP (bool v)"
.br
.RI "\fI\fBCkbSettings::setWritable\fP Remember if the config files are writable (setter) \fP"
.ti -1c
.RI "static bool \fBisBusy\fP ()"
.br
.ti -1c
.RI "static void \fBcleanUp\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "QString \fBpwd\fP () const "
.br
.ti -1c
.RI "QString \fBpwd\fP (const QString &\fBkey\fP) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QSettings * \fBbacking\fP"
.br
.ti -1c
.RI "QStringList \fBgroups\fP"
.br
.ti -1c
.RI "QStringList \fBremoveCache\fP"
.br
.ti -1c
.RI "QMap< QString, QVariant > \fBwriteCache\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static bool \fB_writable\fP = false"
.br
.RI "\fIRemember, whether the Config files are writable or not\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ckbsettings\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CkbSettings::CkbSettings ()"

.PP
Definition at line 147 of file ckbsettings\&.cpp\&.
.PP
.nf
147                          :
148     backing(globalSettings()) {
149 }
.fi
.SS "CkbSettings::CkbSettings (const QString &basePath, booleraseExisting = \fCfalse\fP)"

.PP
Definition at line 151 of file ckbsettings\&.cpp\&.
.PP
References beginGroup()\&.
.PP
.nf
151                                                                     :
152     backing(globalSettings()) {
153     if(basePath\&.isEmpty()){
154         if(eraseExisting)
155             qDebug() << "CkbSettings created with basePath = \"\" and eraseExisting = true\&. This is a mistake\&.";
156         return;
157     }
158     if(eraseExisting)
159         remove(basePath);
160     beginGroup(basePath);
161 }
.fi
.SS "CkbSettings::CkbSettings (QSettings &settings)"

.PP
Definition at line 163 of file ckbsettings\&.cpp\&.
.PP
.nf
163                                             :
164     backing(&settings) {
165 }
.fi
.SS "CkbSettings::~CkbSettings ()"

.PP
Definition at line 231 of file ckbsettings\&.cpp\&.
.PP
References backing, removeCache, and writeCache\&.
.PP
.nf
231                          {
232     if(removeCache\&.isEmpty() && writeCache\&.isEmpty())
233         return;
234     // Save the settings from the settings thread\&.
235     // They have to be saved from that thread specifically to avoid performance issues
236     CkbSettingsWriter* writer = new CkbSettingsWriter(backing, removeCache, writeCache);
237     writer->moveToThread(globalThread);
238     QObject::staticMetaObject\&.invokeMethod(writer, "run", Qt::QueuedConnection);
239 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void CkbSettings::beginGroup (const QString &prefix)"

.PP
Definition at line 167 of file ckbsettings\&.cpp\&.
.PP
References groups\&.
.PP
Referenced by CkbSettings(), KbAnim::save(), and SGroup::SGroup()\&.
.PP
.nf
167                                                  {
168     groups\&.append(prefix);
169 }
.fi
.SS "QStringList CkbSettings::childGroups () const"

.PP
Definition at line 175 of file ckbsettings\&.cpp\&.
.PP
References backing, current, lockMutex, and pwd()\&.
.PP
Referenced by containsGroup(), and GradientDialog::GradientDialog()\&.
.PP
.nf
175                                            {
176     QString current = pwd();
177     lockMutex;
178     if(!current\&.isEmpty())
179         backing->beginGroup(current);
180     QStringList res = backing->childGroups();
181     if(!current\&.isEmpty())
182         backing->endGroup();
183     return res;
184 }
.fi
.SS "QStringList CkbSettings::childKeys () const"

.PP
Definition at line 186 of file ckbsettings\&.cpp\&.
.PP
References backing, current, lockMutex, and pwd()\&.
.PP
Referenced by GradientDialog::GradientDialog(), KbAnim::KbAnim(), KbBind::load(), KbLight::load(), and KbBind::loadGlobalRemap()\&.
.PP
.nf
186                                          {
187     QString current = pwd();
188     lockMutex;
189     if(!current\&.isEmpty())
190         backing->beginGroup(current);
191     QStringList res = backing->childKeys();
192     if(!current\&.isEmpty())
193         backing->endGroup();
194     return res;
195 }
.fi
.SS "void CkbSettings::cleanUp ()\fC [static]\fP"

.PP
Definition at line 132 of file ckbsettings\&.cpp\&.
.PP
References _globalSettings, cacheWritesInProgress(), and globalThread\&.
.PP
Referenced by MainWindow::cleanup()\&.
.PP
.nf
132                          {
133     if(!_globalSettings)
134         return;
135     // Wait for all writers to finish
136     while(cacheWritesInProgress\&.load() > 0)
137         QThread::yieldCurrentThread();
138     // Stop thread and delete objects
139     globalThread->quit();
140     globalThread->wait();
141     delete globalThread;
142     delete _globalSettings;
143     globalThread = 0;
144     _globalSettings = 0;
145 }
.fi
.SS "bool CkbSettings::contains (const QString &key) const"

.PP
Definition at line 197 of file ckbsettings\&.cpp\&.
.PP
References backing, lockMutex, and pwd()\&.
.PP
Referenced by KbMode::KbMode(), KbProfile::KbProfile(), and KbPerf::load()\&.
.PP
.nf
197                                                    {
198     lockMutex;
199     return backing->contains(pwd(key));
200 }
.fi
.SS "bool CkbSettings::containsGroup (const QString &group)"

.PP
Definition at line 202 of file ckbsettings\&.cpp\&.
.PP
References childGroups()\&.
.PP
Referenced by KbPerf::load()\&.
.PP
.nf
202                                                    {
203     QStringList components = group\&.split("/");
204     if(components\&.length() > 1){
205         // Find sub-group
206         SGroup group(*this, components[0]);
207         return containsGroup(QStringList(components\&.mid(1))\&.join('/'));
208     }
209     return childGroups()\&.contains(group);
210 }
.fi
.SS "void CkbSettings::endGroup ()"

.PP
Definition at line 171 of file ckbsettings\&.cpp\&.
.PP
References groups\&.
.PP
Referenced by KbAnim::save(), and SGroup::~SGroup()\&.
.PP
.nf
171                           {
172     groups\&.removeLast();
173 }
.fi
.SS "QVariant CkbSettings::get (const QString &key, const QVariant &defaultValue = \fCQVariant()\fP)\fC [static]\fP"

.PP
Definition at line 241 of file ckbsettings\&.cpp\&.
.PP
References globalCache, globalSettings(), lockMutexCache, and lockMutexStatic2\&.
.PP
Referenced by MainWindow::closeEvent(), KbLightWidget::KbLightWidget(), MainWindow::MainWindow(), AutoRun::once(), and MainWindow::timerTick()\&.
.PP
.nf
241                                                                          {
242     // Store these settings in a memory cache
243     lockMutexCache;
244     if(globalCache\&.contains(key))
245         return globalCache\&.value(key);
246     // If it wasn't found in the memory cache, look for it in QSettings
247     lockMutexStatic2;
248     QSettings* settings = globalSettings();
249     return globalCache[key] = settings->value(key, defaultValue);
250 }
.fi
.SS "bool CkbSettings::informIfNonWritable ()\fC [static]\fP"
CkbSettings::checkIfWritable If the local implementation of the config database is not yet writable, bring up a popup to the user to informhim about it\&. Bring up the information where he can find the info\&. 
.PP
Definition at line 113 of file ckbsettings\&.cpp\&.
.PP
References _globalSettings, and isWritable()\&.
.PP
Referenced by MainWindow::MainWindow()\&.
.PP
.nf
113                                       {
114     if (isWritable()) return false;
115     QMessageBox msgBox;
116     msgBox\&.setIcon(QMessageBox::Warning);
117     msgBox\&.setProperty("Title", "Profile is read only");
118     msgBox\&.setText("Your profile information for ckb-next is nonwritable\&.");
119     QString info = "This might happen if you did start the ckb-next program with root privileges earlier\&.\n\nOr did you copy it from somewhere?\n\nPlease have a look at\n"
120             + _globalSettings->fileName();
121     msgBox\&.setInformativeText(info);
122     msgBox\&.exec();
123     qDebug() << "Profile information for ckb-next is nonwritable\&. It is located at" << _globalSettings->fileName();
124     return true;
125 }
.fi
.SS "bool CkbSettings::isBusy ()\fC [static]\fP"

.PP
Definition at line 128 of file ckbsettings\&.cpp\&.
.PP
References cacheWritesInProgress()\&.
.PP
Referenced by Kb::autoSave(), and ExtraSettingsWidget::pollUpdates()\&.
.PP
.nf
128                         {
129     return cacheWritesInProgress\&.load() > 0;
130 }
.fi
.SS "bool CkbSettings::isWritable ()\fC [static]\fP"
\fBCkbSettings::isWritable\fP Remember if the config files are writable (boolean getter)
.PP
\fBReturns:\fP
.RS 4
the value of CkbSettings::writable 
.RE
.PP

.PP
Definition at line 99 of file ckbsettings\&.cpp\&.
.PP
References _writable\&.
.PP
Referenced by informIfNonWritable(), and main()\&.
.PP
.nf
99 { return _writable; }
.fi
.SS "QString CkbSettings::pwd () const\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 61 of file ckbsettings\&.h\&.
.PP
References groups\&.
.PP
Referenced by childGroups(), childKeys(), contains(), remove(), setValue(), and value()\&.
.PP
.nf
61 { return groups\&.join("/"); }
.fi
.SS "QString CkbSettings::pwd (const QString &key) const\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 62 of file ckbsettings\&.h\&.
.PP
References groups, and pwd()\&.
.PP
Referenced by pwd()\&.
.PP
.nf
62 { return pwd() + (groups\&.isEmpty() ? "" : "/") + key; }
.fi
.SS "void CkbSettings::remove (const QString &key)"

.PP
Definition at line 227 of file ckbsettings\&.cpp\&.
.PP
References pwd(), and removeCache\&.
.PP
Referenced by SettingsWidget::SettingsWidget()\&.
.PP
.nf
227                                           {
228     removeCache\&.append(pwd(key));
229 }
.fi
.SS "void CkbSettings::set (const QString &key, const QVariant &value)\fC [static]\fP"

.PP
Definition at line 252 of file ckbsettings\&.cpp\&.
.PP
References globalCache, globalSettings(), lockMutexCache, lockMutexStatic, and value()\&.
.PP
Referenced by MainWindow::closeEvent(), AutoRun::enable(), AutoRun::isEnabled(), SettingsWidget::on_autoFWBox_clicked(), ExtraSettingsWidget::on_delayBox_clicked(), ExtraSettingsWidget::on_ditherBox_clicked(), SettingsWidget::on_layoutBox_activated(), ExtraSettingsWidget::on_mAccelBox_clicked(), ExtraSettingsWidget::on_sAccelBox_clicked(), KbLightWidget::on_showAnimBox_clicked(), ExtraSettingsWidget::on_sSpeedBox_valueChanged(), ExtraSettingsWidget::on_trayBox_clicked(), MPerfWidget::on_xyBox_clicked(), and ExtraSettingsWidget::pollUpdates()\&.
.PP
.nf
252                                                               {
253     {
254         lockMutexCache;
255         if(globalCache\&.value(key) == value)
256             return;
257         globalCache[key] = value;
258     }
259     lockMutexStatic;
260     globalSettings()->setValue(key, value);
261 }
.fi
.SS "void CkbSettings::setValue (const QString &key, const QVariant &value)"

.PP
Definition at line 217 of file ckbsettings\&.cpp\&.
.PP
References globalCache, lockMutexCache, pwd(), value(), and writeCache\&.
.PP
Referenced by ExtraSettingsWidget::on_fpsBox_valueChanged(), KbProfile::save(), KbPerf::save(), KbAnim::save(), KbBind::save(), KbMode::save(), KbLight::save(), Kb::save(), KbBind::saveGlobalRemap(), SettingsWidget::SettingsWidget(), and GradientDialog::~GradientDialog()\&.
.PP
.nf
217                                                                    {
218     // Cache the write values, save them when the object is destroyed
219     QString realKey = pwd(key);
220     writeCache[realKey] = value;
221     // Update global cache if needed
222     lockMutexCache;
223     if(globalCache\&.contains(realKey))
224         globalCache[realKey] = value;
225 }
.fi
.SS "void CkbSettings::setWritable (boolv)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIv\fP Set the value of CkbSettings::writable 
.RE
.PP

.PP
Definition at line 106 of file ckbsettings\&.cpp\&.
.PP
References _writable\&.
.PP
Referenced by globalSettings()\&.
.PP
.nf
106 { _writable = v; }
.fi
.SS "QVariant CkbSettings::value (const QString &key, const QVariant &defaultValue = \fCQVariant()\fP) const"

.PP
Definition at line 212 of file ckbsettings\&.cpp\&.
.PP
References backing, lockMutex, and pwd()\&.
.PP
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), GradientDialog::GradientDialog(), KbAnim::KbAnim(), KbMode::KbMode(), KbProfile::KbProfile(), KbPerf::load(), KbBind::load(), KbLight::load(), Kb::load(), KbBind::loadGlobalRemap(), set(), SettingsWidget::SettingsWidget(), and setValue()\&.
.PP
.nf
212                                                                                   {
213     lockMutex;
214     return backing->value(pwd(key), defaultValue);
215 }
.fi
.SH "Field Documentation"
.PP 
.SS "bool CkbSettings::_writable = false\fC [static]\fP, \fC [private]\fP"
\fBCkbSettings::_writable\fP\&. 
.PP
Definition at line 59 of file ckbsettings\&.h\&.
.PP
Referenced by isWritable(), and setWritable()\&.
.SS "QSettings* CkbSettings::backing\fC [private]\fP"

.PP
Definition at line 54 of file ckbsettings\&.h\&.
.PP
Referenced by childGroups(), childKeys(), contains(), value(), and ~CkbSettings()\&.
.SS "QStringList CkbSettings::groups\fC [private]\fP"

.PP
Definition at line 55 of file ckbsettings\&.h\&.
.PP
Referenced by beginGroup(), endGroup(), and pwd()\&.
.SS "QStringList CkbSettings::removeCache\fC [private]\fP"

.PP
Definition at line 56 of file ckbsettings\&.h\&.
.PP
Referenced by remove(), and ~CkbSettings()\&.
.SS "QMap<QString, QVariant> CkbSettings::writeCache\fC [private]\fP"

.PP
Definition at line 57 of file ckbsettings\&.h\&.
.PP
Referenced by setValue(), and ~CkbSettings()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
