CkbSettings
NAME
CkbSettings -
SYNOPSIS
#include <src/ckb/ckbsettings.h>
Public Member Functions
CkbSettings ()
CkbSettings (const QString &basePath, bool eraseExisting=false)
CkbSettings (QSettings &settings)
~CkbSettings ()
void beginGroup (const QString &prefix)
void endGroup ()
QStringList childGroups () const
QStringList childKeys () const
bool contains (const QString &key) const
bool containsGroup (const QString &group)
QVariant value (const QString &key, const QVariant &defaultValue=QVariant()) const
void setValue (const QString &key, const QVariant &value)
void remove (const QString &key)
Static Public Member Functions
static QVariant get (const QString &key, const QVariant &defaultValue=QVariant())
static void set (const QString &key, const QVariant &value)
static bool informIfNonWritable ()
If config files are writable, return false. Otherwise give the user a pop up and return true.
static bool isWritable ()
Setter & getter for it.
static void setWritable (bool v)
CkbSettings::setWritable Remember if the config files are writable (setter)
static bool isBusy ()
static void cleanUp ()
Private Member Functions
QString pwd () const
QString pwd (const QString &key) const
Private Attributes
QSettings * backing
QStringList groups
QStringList removeCache
QMap< QString, QVariant > writeCache
Static Private Attributes
static bool _writable = false
Remember, whether the Config files are writable or not.
Detailed Description
Definition at line 12 of file ckbsettings.h.
Constructor & Destructor Documentation
CkbSettings::CkbSettings ()
Definition at line 147 of file ckbsettings.cpp.
                         :
    backing(globalSettings()) {
}
CkbSettings::CkbSettings (const QString &basePath, booleraseExisting = false)
Definition at line 151 of file ckbsettings.cpp.
References beginGroup().
                                                                    :
    backing(globalSettings()) {
    if(basePath.isEmpty()){
        if(eraseExisting)
            qDebug() << "CkbSettings created with basePath = \"\" and eraseExisting = true. This is a mistake.";
        return;
    }
    if(eraseExisting)
        remove(basePath);
    beginGroup(basePath);
}
CkbSettings::CkbSettings (QSettings &settings)
Definition at line 163 of file ckbsettings.cpp.
                                            :
    backing(&settings) {
}
CkbSettings::~CkbSettings ()
Definition at line 231 of file ckbsettings.cpp.
References backing, removeCache, and writeCache.
                         {
    if(removeCache.isEmpty() && writeCache.isEmpty())
        return;
    // Save the settings from the settings thread.
    // They have to be saved from that thread specifically to avoid performance issues
    CkbSettingsWriter* writer = new CkbSettingsWriter(backing, removeCache, writeCache);
    writer->moveToThread(globalThread);
    QObject::staticMetaObject.invokeMethod(writer, "run", Qt::QueuedConnection);
}
Member Function Documentation
void CkbSettings::beginGroup (const QString &prefix)
Definition at line 167 of file ckbsettings.cpp.
References groups.
Referenced by CkbSettings(), KbAnim::save(), and SGroup::SGroup().
                                                 {
    groups.append(prefix);
}
QStringList CkbSettings::childGroups () const
Definition at line 175 of file ckbsettings.cpp.
References backing, current, lockMutex, and pwd().
Referenced by containsGroup(), and GradientDialog::GradientDialog().
                                           {
    QString current = pwd();
    lockMutex;
    if(!current.isEmpty())
        backing->beginGroup(current);
    QStringList res = backing->childGroups();
    if(!current.isEmpty())
        backing->endGroup();
    return res;
}
QStringList CkbSettings::childKeys () const
Definition at line 186 of file ckbsettings.cpp.
References backing, current, lockMutex, and pwd().
Referenced by GradientDialog::GradientDialog(), KbAnim::KbAnim(), KbBind::load(), KbLight::load(), and KbBind::loadGlobalRemap().
                                         {
    QString current = pwd();
    lockMutex;
    if(!current.isEmpty())
        backing->beginGroup(current);
    QStringList res = backing->childKeys();
    if(!current.isEmpty())
        backing->endGroup();
    return res;
}
void CkbSettings::cleanUp () [static]
Definition at line 132 of file ckbsettings.cpp.
References _globalSettings, cacheWritesInProgress(), and globalThread.
Referenced by MainWindow::cleanup().
                         {
    if(!_globalSettings)
        return;
    // Wait for all writers to finish
    while(cacheWritesInProgress.load() > 0)
        QThread::yieldCurrentThread();
    // Stop thread and delete objects
    globalThread->quit();
    globalThread->wait();
    delete globalThread;
    delete _globalSettings;
    globalThread = 0;
    _globalSettings = 0;
}
bool CkbSettings::contains (const QString &key) const
Definition at line 197 of file ckbsettings.cpp.
References backing, lockMutex, and pwd().
Referenced by KbMode::KbMode(), KbProfile::KbProfile(), and KbPerf::load().
                                                   {
    lockMutex;
    return backing->contains(pwd(key));
}
bool CkbSettings::containsGroup (const QString &group)
Definition at line 202 of file ckbsettings.cpp.
References childGroups().
Referenced by KbPerf::load().
                                                   {
    QStringList components = group.split("/");
    if(components.length() > 1){
        // Find sub-group
        SGroup group(*this, components[0]);
        return containsGroup(QStringList(components.mid(1)).join('/'));
    }
    return childGroups().contains(group);
}
void CkbSettings::endGroup ()
Definition at line 171 of file ckbsettings.cpp.
References groups.
Referenced by KbAnim::save(), and SGroup::~SGroup().
                          {
    groups.removeLast();
}
QVariant CkbSettings::get (const QString &key, const QVariant &defaultValue = QVariant()) [static]
Definition at line 241 of file ckbsettings.cpp.
References globalCache, globalSettings(), lockMutexCache, and lockMutexStatic2.
Referenced by MainWindow::closeEvent(), KbLightWidget::KbLightWidget(), MainWindow::MainWindow(), AutoRun::once(), and MainWindow::timerTick().
                                                                         {
    // Store these settings in a memory cache
    lockMutexCache;
    if(globalCache.contains(key))
        return globalCache.value(key);
    // If it wasn't found in the memory cache, look for it in QSettings
    lockMutexStatic2;
    QSettings* settings = globalSettings();
    return globalCache[key] = settings->value(key, defaultValue);
}
bool CkbSettings::informIfNonWritable () [static]
CkbSettings::checkIfWritable If the local implementation of the config database is not yet writable, bring up a popup to the user to informhim about it. Bring up the information where he can find the info.
Definition at line 113 of file ckbsettings.cpp.
References _globalSettings, and isWritable().
Referenced by MainWindow::MainWindow().
                                      {
    if (isWritable()) return false;
    QMessageBox msgBox;
    msgBox.setIcon(QMessageBox::Warning);
    msgBox.setProperty("Title", "Profile is read only");
    msgBox.setText("Your profile information for ckb-next is nonwritable.");
    QString info = "This might happen if you did start the ckb-next program with root privileges earlier.\n\nOr did you copy it from somewhere?\n\nPlease have a look at\n"
            + _globalSettings->fileName();
    msgBox.setInformativeText(info);
    msgBox.exec();
    qDebug() << "Profile information for ckb-next is nonwritable. It is located at" << _globalSettings->fileName();
    return true;
}
bool CkbSettings::isBusy () [static]
Definition at line 128 of file ckbsettings.cpp.
References cacheWritesInProgress().
Referenced by Kb::autoSave(), and ExtraSettingsWidget::pollUpdates().
                        {
    return cacheWritesInProgress.load() > 0;
}
bool CkbSettings::isWritable () [static]
CkbSettings::isWritable Remember if the config files are writable (boolean getter)
Returns:
the value of CkbSettings::writable
Definition at line 99 of file ckbsettings.cpp.
References _writable.
Referenced by informIfNonWritable(), and main().
{ return _writable; }
QString CkbSettings::pwd () const [inline], [private]
Definition at line 61 of file ckbsettings.h.
References groups.
Referenced by childGroups(), childKeys(), contains(), remove(), setValue(), and value().
{ return groups.join("/"); }
QString CkbSettings::pwd (const QString &key) const [inline], [private]
Definition at line 62 of file ckbsettings.h.
References groups, and pwd().
Referenced by pwd().
{ return pwd() + (groups.isEmpty() ? "" : "/") + key; }
void CkbSettings::remove (const QString &key)
Definition at line 227 of file ckbsettings.cpp.
References pwd(), and removeCache.
Referenced by SettingsWidget::SettingsWidget().
                                          {
    removeCache.append(pwd(key));
}
void CkbSettings::set (const QString &key, const QVariant &value) [static]
Definition at line 252 of file ckbsettings.cpp.
References globalCache, globalSettings(), lockMutexCache, lockMutexStatic, and value().
Referenced by MainWindow::closeEvent(), AutoRun::enable(), AutoRun::isEnabled(), SettingsWidget::on_autoFWBox_clicked(), ExtraSettingsWidget::on_delayBox_clicked(), ExtraSettingsWidget::on_ditherBox_clicked(), SettingsWidget::on_layoutBox_activated(), ExtraSettingsWidget::on_mAccelBox_clicked(), ExtraSettingsWidget::on_sAccelBox_clicked(), KbLightWidget::on_showAnimBox_clicked(), ExtraSettingsWidget::on_sSpeedBox_valueChanged(), ExtraSettingsWidget::on_trayBox_clicked(), MPerfWidget::on_xyBox_clicked(), and ExtraSettingsWidget::pollUpdates().
                                                              {
    {
        lockMutexCache;
        if(globalCache.value(key) == value)
            return;
        globalCache[key] = value;
    }
    lockMutexStatic;
    globalSettings()->setValue(key, value);
}
void CkbSettings::setValue (const QString &key, const QVariant &value)
Definition at line 217 of file ckbsettings.cpp.
References globalCache, lockMutexCache, pwd(), value(), and writeCache.
Referenced by ExtraSettingsWidget::on_fpsBox_valueChanged(), KbProfile::save(), KbPerf::save(), KbAnim::save(), KbBind::save(), KbMode::save(), KbLight::save(), Kb::save(), KbBind::saveGlobalRemap(), SettingsWidget::SettingsWidget(), and GradientDialog::~GradientDialog().
                                                                   {
    // Cache the write values, save them when the object is destroyed
    QString realKey = pwd(key);
    writeCache[realKey] = value;
    // Update global cache if needed
    lockMutexCache;
    if(globalCache.contains(realKey))
        globalCache[realKey] = value;
}
void CkbSettings::setWritable (boolv) [static]
Parameters:
v Set the value of CkbSettings::writable
Definition at line 106 of file ckbsettings.cpp.
References _writable.
Referenced by globalSettings().
{ _writable = v; }
QVariant CkbSettings::value (const QString &key, const QVariant &defaultValue = QVariant()) const
Definition at line 212 of file ckbsettings.cpp.
References backing, lockMutex, and pwd().
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), GradientDialog::GradientDialog(), KbAnim::KbAnim(), KbMode::KbMode(), KbProfile::KbProfile(), KbPerf::load(), KbBind::load(), KbLight::load(), Kb::load(), KbBind::loadGlobalRemap(), set(), SettingsWidget::SettingsWidget(), and setValue().
                                                                                  {
    lockMutex;
    return backing->value(pwd(key), defaultValue);
}
Field Documentation
bool CkbSettings::_writable = false [static], [private]
CkbSettings::_writable.
Definition at line 59 of file ckbsettings.h.
Referenced by isWritable(), and setWritable().
QSettings* CkbSettings::backing [private]
Definition at line 54 of file ckbsettings.h.
Referenced by childGroups(), childKeys(), contains(), value(), and ~CkbSettings().
QStringList CkbSettings::groups [private]
Definition at line 55 of file ckbsettings.h.
Referenced by beginGroup(), endGroup(), and pwd().
QStringList CkbSettings::removeCache [private]
Definition at line 56 of file ckbsettings.h.
Referenced by remove(), and ~CkbSettings().
QMap<QString, QVariant> CkbSettings::writeCache [private]
Definition at line 57 of file ckbsettings.h.
Referenced by setValue(), and ~CkbSettings().
Author
Generated automatically by Doxygen for ckb-next from the source code.