.TH "src/ckb/colorbutton.h" 3 "Sat Jun 3 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/colorbutton.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QPushButton>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBColorButton\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
