ColorButton
NAME
ColorButton -
SYNOPSIS
#include <src/ckb/colorbutton.h>
Inherits QPushButton.
Signals
void colorChanged (QColor newColor)
Public Member Functions
ColorButton (QWidget *parent=0, bool allowAlpha=false)
const QColor & color () const
void color (const QColor &newColor)
bool allowAlpha () const
void allowAlpha (bool newAllowAlpha)
bool setLabel () const
void setLabel (bool newSetLabel)
bool bigIcons () const
void bigIcons (bool newBigIcons)
Private Slots
void pickColor ()
Private Member Functions
void updateImage ()
Private Attributes
QColor _color
bool _alpha
bool _setLabel
bool _bigIcons
Detailed Description
Definition at line 6 of file colorbutton.h.
Constructor & Destructor Documentation
ColorButton::ColorButton (QWidget *parent = 0, boolallowAlpha = false) [explicit]
Definition at line 5 of file colorbutton.cpp.
References pickColor(), and updateImage().
                                                         :
    QPushButton(parent), _alpha(allowAlpha), _setLabel(true), _bigIcons(false)
{
    setAutoDefault(false);
    setDefault(false);
    updateImage();
    // Pick color on click (use queued connection so that any on_*_clicked() events can be processed first)
    connect(this, SIGNAL(clicked()), this, SLOT(pickColor()), Qt::QueuedConnection);
}
Member Function Documentation
bool ColorButton::allowAlpha () const [inline]
Definition at line 17 of file colorbutton.h.
References _alpha.
Referenced by KPerfWidget::KPerfWidget(), and MPerfWidget::MPerfWidget().
{ return _alpha; }
void ColorButton::allowAlpha (boolnewAllowAlpha)
Definition at line 22 of file colorbutton.cpp.
References _alpha, and updateImage().
                                              {
    _alpha = newAllowAlpha;
    updateImage();
}
bool ColorButton::bigIcons () const [inline]
Definition at line 23 of file colorbutton.h.
References _bigIcons.
Referenced by KPerfWidget::KPerfWidget(), and MPerfWidget::MPerfWidget().
{ return _bigIcons; }
void ColorButton::bigIcons (boolnewBigIcons)
Definition at line 27 of file colorbutton.cpp.
References _bigIcons, and updateImage().
                                          {
    _bigIcons = newBigIcons;
    updateImage();
}
const QColor& ColorButton::color () const [inline]
Definition at line 13 of file colorbutton.h.
References _color.
Referenced by MPerfWidget::colorChanged(), GradientDialog::currentChanged(), KbLightWidget::newSelection(), GradientDialog::on_stopOpacity_valueChanged(), KPerfWidget::setPerf(), MPerfWidget::setPerf(), KPerfWidget::uiUpdated(), and AnimSettingDialog::updateParam().
{ return _color; }
void ColorButton::color (const QColor &newColor)
Definition at line 15 of file colorbutton.cpp.
References _alpha, _color, and updateImage().
                                             {
    _color = newColor;
    if(!_alpha)
        _color.setAlpha(255);
    updateImage();
}
void ColorButton::colorChanged (QColornewColor) [signal]
Definition at line 132 of file moc_colorbutton.cpp.
Referenced by pickColor().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
void ColorButton::pickColor () [private], [slot]
Definition at line 60 of file colorbutton.cpp.
References _alpha, _color, colorChanged(), and updateImage().
Referenced by ColorButton().
                           {
    QColor newColor = QColorDialog::getColor(_color, this, QString(), QColorDialog::ColorDialogOptions(_alpha ? QColorDialog::ShowAlphaChannel : 0));
    if(newColor.isValid()){
        _color = newColor;
        updateImage();
        emit colorChanged(_color);
    }
}
bool ColorButton::setLabel () const [inline]
Definition at line 20 of file colorbutton.h.
References _setLabel.
Referenced by KPerfWidget::KPerfWidget(), and MPerfWidget::MPerfWidget().
{ return _setLabel; }
void ColorButton::setLabel (boolnewSetLabel) [inline]
Definition at line 21 of file colorbutton.h.
References _setLabel.
{ _setLabel = newSetLabel; }
void ColorButton::updateImage () [private]
Definition at line 32 of file colorbutton.cpp.
References _alpha, _bigIcons, _color, and _setLabel.
Referenced by allowAlpha(), bigIcons(), color(), ColorButton(), and pickColor().
                             {
    if(!_color.isValid()){
        setIcon(QIcon());
        if(_setLabel)
            setText("Change color...");
        return;
    }
    const int w = 24, h = _bigIcons ? 24 : 12;
    QImage image(w, h, QImage::Format_RGB888);
    QPainter painter(&image);
    painter.setPen(Qt::NoPen);
    painter.fillRect(0, 0, w, h, QColor(0, 0, 0));
    if(_alpha && _color.alpha() != 255){
        painter.fillRect(1, 1, w / 2 - 1, h / 2 - 1, QColor(255, 255, 255));
        painter.fillRect(w / 2, 1, w / 2 - 1, h / 2 - 1, QColor(192, 192, 192));
        painter.fillRect(1, h / 2, w / 2 - 1, h / 2 - 1, QColor(192, 192, 192));
        painter.fillRect(w / 2, h / 2, w / 2 - 1, h / 2 - 1, QColor(255, 255, 255));
    }
    painter.fillRect(1, 1, w - 2, h - 2, _color);
    setIcon(QIcon(QPixmap::fromImage(image)));
    if(_setLabel){
        QString text = QString(" (%1, %2, %3)").arg(_color.red()).arg(_color.green()).arg(_color.blue());
        if(_alpha)
            text += QString(", %4%").arg(QString::number(_color.alphaF() * 100., 'f', 0));
        setText(text);
    }
}
Field Documentation
bool ColorButton::_alpha [private]
Definition at line 34 of file colorbutton.h.
Referenced by allowAlpha(), color(), pickColor(), and updateImage().
bool ColorButton::_bigIcons [private]
Definition at line 34 of file colorbutton.h.
Referenced by bigIcons(), and updateImage().
QColor ColorButton::_color [private]
Definition at line 33 of file colorbutton.h.
Referenced by color(), pickColor(), and updateImage().
bool ColorButton::_setLabel [private]
Definition at line 34 of file colorbutton.h.
Referenced by setLabel(), and updateImage().
Author
Generated automatically by Doxygen for ckb-next from the source code.