.TH "deprecated" 3 "Tue May 16 2017" "Version beta-v0.2.7 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBClass \fBQuaZipFileInfo\fP \fP" 1c
Use \fBQuaZipFileInfo64\fP instead\&. Not only it supports large files, but also more convenience methods as well\&.
.PP

