.TH "src/ckb-daemon/devnode.h" 3 "Sun Jun 4 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb-daemon/devnode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'includes\&.h'\fP
.br
\fC#include 'usb\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS_READDIR\fP   (S_IRWXU | S_IRGRP | S_IROTH | S_IXGRP | S_IXOTH)"
.br
.ti -1c
.RI "#define \fBS_READ\fP   (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR)"
.br
.ti -1c
.RI "#define \fBS_READWRITE\fP   (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR | S_IWGRP | S_IWOTH)"
.br
.ti -1c
.RI "#define \fBS_CUSTOM\fP   (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP)"
.br
.ti -1c
.RI "#define \fBS_CUSTOM_R\fP   (S_IRUSR | S_IWUSR | S_IRGRP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_readlines_ctx\fP * \fBreadlines_ctx\fP"
.br
.RI "\fICustom readline is needed for FIFOs\&. fopen()/getline() will die if the data is sent in too fast\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupdateconnected\fP ()"
.br
.RI "\fIUpdate the list of connected devices\&. \fP"
.ti -1c
.RI "int \fBmkdevpath\fP (\fBusbdevice\fP *kb)"
.br
.RI "\fICreate a dev path for the keyboard at index\&. Returns 0 on success\&. \fP"
.ti -1c
.RI "int \fBrmdevpath\fP (\fBusbdevice\fP *kb)"
.br
.RI "\fIRemove the dev path for the keyboard at index\&. Returns 0 on success\&. \fP"
.ti -1c
.RI "int \fBmknotifynode\fP (\fBusbdevice\fP *kb, int notify)"
.br
.RI "\fICreates a notification node for the specified keyboard\&. \fP"
.ti -1c
.RI "int \fBrmnotifynode\fP (\fBusbdevice\fP *kb, int notify)"
.br
.RI "\fIRemoves a notification node for the specified keyboard\&. \fP"
.ti -1c
.RI "int \fBmkfwnode\fP (\fBusbdevice\fP *kb)"
.br
.RI "\fIWrites a keyboard's firmware version and poll rate to its device node\&. \fP"
.ti -1c
.RI "void \fBreadlines_ctx_init\fP (\fBreadlines_ctx\fP *ctx)"
.br
.ti -1c
.RI "void \fBreadlines_ctx_free\fP (\fBreadlines_ctx\fP ctx)"
.br
.ti -1c
.RI "unsigned \fBreadlines\fP (int fd, \fBreadlines_ctx\fP ctx, const char **input)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBdevpath\fP"
.br
.RI "\fIDevice path base ('/dev/input/ckb' or '/var/run/ckb') \fP"
.ti -1c
.RI "long \fBgid\fP"
.br
.RI "\fIGroup ID for the control nodes\&. -1 to give read/write access to everybody\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S_CUSTOM   (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP)"

.PP
Definition at line 17 of file devnode\&.h\&.
.PP
Referenced by _mkdevpath()\&.
.SS "#define S_CUSTOM_R   (S_IRUSR | S_IWUSR | S_IRGRP)"

.PP
Definition at line 18 of file devnode\&.h\&.
.SS "#define S_READ   (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR)"

.PP
Definition at line 15 of file devnode\&.h\&.
.PP
Referenced by _mkdevpath()\&.
.SS "#define S_READDIR   (S_IRWXU | S_IRGRP | S_IROTH | S_IXGRP | S_IXOTH)"

.PP
Definition at line 14 of file devnode\&.h\&.
.PP
Referenced by _mkdevpath()\&.
.SS "#define S_READWRITE   (S_IRUSR | S_IRGRP | S_IROTH | S_IWUSR | S_IWGRP | S_IWOTH)"

.PP
Definition at line 16 of file devnode\&.h\&.
.PP
Referenced by _mkdevpath()\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_readlines_ctx\fP* \fBreadlines_ctx\fP"

.PP
Definition at line 39 of file devnode\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int mkdevpath (\fBusbdevice\fP *kb)"

.PP
Definition at line 283 of file devnode\&.c\&.
.PP
References _mkdevpath(), euid_guard_start, and euid_guard_stop\&.
.PP
Referenced by _setupusb(), and main()\&.
.PP
.nf
283                             {
284     euid_guard_start;
285     int res = _mkdevpath(kb);
286     euid_guard_stop;
287     return res;
288 }
.fi
.SS "int mkfwnode (\fBusbdevice\fP *kb)"

.PP
Definition at line 314 of file devnode\&.c\&.
.PP
References ckb_warn, devpath, usbdevice::fwversion, gid, INDEX_OF, keyboard, usbdevice::pollrate, and S_GID_READ\&.
.PP
Referenced by _mkdevpath(), and fwupdate()\&.
.PP
.nf
314                            {
315     int index = INDEX_OF(kb, keyboard);
316     char fwpath[strlen(devpath) + 12];
317     snprintf(fwpath, sizeof(fwpath), "%s%d/fwversion", devpath, index);
318     FILE* fwfile = fopen(fwpath, "w");
319     if(fwfile){
320         fprintf(fwfile, "%04x", kb->fwversion);
321         fputc('\n', fwfile);
322         fclose(fwfile);
323         chmod(fwpath, S_GID_READ);
324         if(gid >= 0)
325             chown(fwpath, 0, gid);
326     } else {
327         ckb_warn("Unable to create %s: %s\n", fwpath, strerror(errno));
328         remove(fwpath);
329         return -1;
330     }
331     char ppath[strlen(devpath) + 11];
332     snprintf(ppath, sizeof(ppath), "%s%d/pollrate", devpath, index);
333     FILE* pfile = fopen(ppath, "w");
334     if(pfile){
335         fprintf(pfile, "%d ms", kb->pollrate);
336         fputc('\n', pfile);
337         fclose(pfile);
338         chmod(ppath, S_GID_READ);
339         if(gid >= 0)
340             chown(ppath, 0, gid);
341     } else {
342         ckb_warn("Unable to create %s: %s\n", fwpath, strerror(errno));
343         remove(ppath);
344         return -2;
345     }
346     return 0;
347 }
.fi
.SS "int mknotifynode (\fBusbdevice\fP *kb, intnotify)"

.PP
Definition at line 108 of file devnode\&.c\&.
.PP
References _mknotifynode(), euid_guard_start, and euid_guard_stop\&.
.PP
Referenced by readcmd()\&.
.PP
.nf
108                                            {
109     euid_guard_start;
110     int res = _mknotifynode(kb, notify);
111     euid_guard_stop;
112     return res;
113 }
.fi
.SS "unsigned readlines (intfd, \fBreadlines_ctx\fPctx, const char **input)"

.PP
Definition at line 368 of file devnode\&.c\&.
.PP
References _readlines_ctx::buffer, _readlines_ctx::buffersize, ckb_warn, _readlines_ctx::leftover, _readlines_ctx::leftoverlen, and MAX_BUFFER\&.
.PP
Referenced by devmain()\&.
.PP
.nf
368                                                                  {
369     // Move any data left over from a previous read to the start of the buffer
370     char* buffer = ctx->buffer;
371     int buffersize = ctx->buffersize;
372     int leftover = ctx->leftover, leftoverlen = ctx->leftoverlen;
373     memcpy(buffer, buffer + leftover, leftoverlen);
374     // Read data from the file
375     ssize_t length = read(fd, buffer + leftoverlen, buffersize - leftoverlen);
376     length = (length < 0 ? 0 : length) + leftoverlen;
377     leftover = ctx->leftover = leftoverlen = ctx->leftoverlen = 0;
378     if(length <= 0){
379         *input = 0;
380         return 0;
381     }
382     // Continue buffering until all available input is read or there's no room left
383     while(length == buffersize){
384         if(buffersize == MAX_BUFFER)
385             break;
386         int oldsize = buffersize;
387         buffersize += 4096;
388         ctx->buffersize = buffersize;
389         buffer = ctx->buffer = realloc(buffer, buffersize + 1);
390         ssize_t length2 = read(fd, buffer + oldsize, buffersize - oldsize);
391         if(length2 <= 0)
392             break;
393         length += length2;
394     }
395     buffer[length] = 0;
396     // Input should be issued one line at a time and should end with a newline\&.
397     char* lastline = memrchr(buffer, '\n', length);
398     if(lastline == buffer + length - 1){
399         // If the buffer ends in a newline, process the whole string
400         *input = buffer;
401         return length;
402     } else if(lastline){
403         // Otherwise, chop off the last line but process everything else
404         *lastline = 0;
405         leftover = ctx->leftover = lastline + 1 - buffer;
406         leftoverlen = ctx->leftoverlen = length - leftover;
407         *input = buffer;
408         return leftover - 1;
409     } else {
410         // If a newline wasn't found at all, process the whole buffer next time
411         *input = 0;
412         if(length == MAX_BUFFER){
413             // Unless the buffer is completely full, in which case discard it
414             ckb_warn("Too much input (1MB)\&. Dropping\&.\n");
415             return 0;
416         }
417         leftoverlen = ctx->leftoverlen = length;
418         return 0;
419     }
420 }
.fi
.SS "void readlines_ctx_free (\fBreadlines_ctx\fPctx)"

.PP
Definition at line 363 of file devnode\&.c\&.
.PP
References _readlines_ctx::buffer\&.
.PP
Referenced by devmain()\&.
.PP
.nf
363                                           {
364     free(ctx->buffer);
365     free(ctx);
366 }
.fi
.SS "void readlines_ctx_init (\fBreadlines_ctx\fP *ctx)"

.PP
Definition at line 356 of file devnode\&.c\&.
.PP
Referenced by devmain()\&.
.PP
.nf
356                                            {
357     // Allocate buffers to store data
358     *ctx = calloc(1, sizeof(struct _readlines_ctx));
359     int buffersize = (*ctx)->buffersize = 4095;
360     (*ctx)->buffer = malloc(buffersize + 1);
361 }
.fi
.SS "int rmdevpath (\fBusbdevice\fP *kb)"

.PP
Definition at line 290 of file devnode\&.c\&.
.PP
References _rmnotifynode(), ckb_info, ckb_warn, devpath, euid_guard_start, euid_guard_stop, INDEX_OF, usbdevice::infifo, keyboard, OUTFIFO_MAX, and rm_recursive()\&.
.PP
Referenced by closeusb(), and quitWithLock()\&.
.PP
.nf
290                             {
291     euid_guard_start;
292     int index = INDEX_OF(kb, keyboard);
293     if(kb->infifo != 0){
294 #ifdef OS_LINUX
295         write(kb->infifo - 1, "\n", 1); // hack to prevent the FIFO thread from perma-blocking
296 #endif
297         close(kb->infifo - 1);
298         kb->infifo = 0;
299     }
300     for(int i = 0; i < OUTFIFO_MAX; i++)
301         _rmnotifynode(kb, i);
302     char path[strlen(devpath) + 2];
303     snprintf(path, sizeof(path), "%s%d", devpath, index);
304     if(rm_recursive(path) != 0 && errno != ENOENT){
305         ckb_warn("Unable to delete %s: %s\n", path, strerror(errno));
306         euid_guard_stop;
307         return -1;
308     }
309     ckb_info("Removed device path %s\n", path);
310     euid_guard_stop;
311     return 0;
312 }
.fi
.SS "int rmnotifynode (\fBusbdevice\fP *kb, intnotify)"

.PP
Definition at line 129 of file devnode\&.c\&.
.PP
References _rmnotifynode(), euid_guard_start, and euid_guard_stop\&.
.PP
Referenced by readcmd()\&.
.PP
.nf
129                                            {
130     euid_guard_start;
131     int res = _rmnotifynode(kb, notify);
132     euid_guard_stop;
133     return res;
134 }
.fi
.SS "void updateconnected ()"

.PP
Definition at line 81 of file devnode\&.c\&.
.PP
References _updateconnected(), euid_guard_start, and euid_guard_stop\&.
.PP
Referenced by _setupusb(), and closeusb()\&.
.PP
.nf
81                       {
82     euid_guard_start;
83     _updateconnected();
84     euid_guard_stop;
85 }
.fi
.SH "Variable Documentation"
.PP 
.SS "const char* const devpath"

.PP
Definition at line 8 of file devnode\&.h\&.
.SS "long gid"

.PP
Definition at line 16 of file devnode\&.c\&.
.PP
Referenced by _mkdevpath(), _mknotifynode(), _updateconnected(), main(), and mkfwnode()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
