Kb
NAME
Kb -
SYNOPSIS
#include <src/ckb/kb.h>
Inherits QThread.
Public Slots
void frameUpdate ()
void autoSave ()
Signals
void infoUpdated ()
void profileAdded ()
void profileRenamed ()
void modeRenamed ()
void profileChanged ()
void modeChanged (bool spontaneous)
void fwUpdateProgress (int current, int total)
void fwUpdateFinished (bool succeeded)
Public Member Functions
KeyMap::Model model () const
bool isKeyboard () const
bool isMouse () const
KbProfile * hwProfile ()
void hwProfile (KbProfile *newHwProfile)
void fwUpdate (const QString &path)
KbProfile * currentProfile ()
const QList< KbProfile * > & profiles () const
void profiles (const QList< KbProfile * > &newProfiles)
void appendProfile (KbProfile *newProfile)
int indexOf (KbProfile *profile)
KbProfile * find (const QUuid &id)
KbMode * currentMode ()
KbLight * currentLight ()
KbBind * currentBind ()
KbPerf * currentPerf ()
void setCurrentProfile (KbProfile *profile, bool spontaneous=true)
void setCurrentMode (KbProfile *profile, KbMode *mode, bool spontaneous=true)
void setCurrentMode (KbProfile *profile, int index, bool spontaneous=true)
void setCurrentMode (KbMode *mode, bool spontaneous=true)
KbProfile * newProfile ()
KbProfile * newProfile (KbProfile *other)
KbMode * newMode ()
KbMode * newMode (KbMode *other)
void load ()
void save ()
bool needsSave () const
void hwSave ()
int getMacroNumber ()
For usage with macro definions, these two params must only be readable. So there are no setters.
QString getMacroPath ()
getMacroPath returns the macroPath (e.g. /dev/input/ckb1/notify), which we have saved in the constructor. For usage with macro definions, this param must only be readable. So there is no setter.
~Kb ()
Static Public Member Functions
static int frameRate ()
static void frameRate (int newFrameRate)
static KeyMap::Layout layout ()
static void layout (KeyMap::Layout newLayout)
static bool dither ()
static void dither (bool newDither)
static bool macroDelay ()
static void macroDelay (bool flag)
Kb::macroDelay handles the UI-Element macroBox. Sends a command to the keyboard to switch on or off the delay function on very large macros.
static bool mouseAccel ()
static void mouseAccel (bool newAccel)
static int scrollSpeed ()
static void scrollSpeed (int newSpeed)
Data Fields
QString usbModel
QString usbSerial
QString features
QString firmware
QString pollrate
bool monochrome
int hwModeCount
Static Public Attributes
static const int HWMODE_MAX = 3
Private Slots
void readNotify (QString line)
void deleteHw ()
void deletePrevious ()
Private Member Functions
Kb (QObject *parent, const QString &path)
is invalid also.
"
bool isOpen () const
bool matches (const QString &path, const QString &serial)
void updateLayout ()
void writeProfileHeader ()
KeyMap getKeyMap ()
void run ()
Private Attributes
QString devpath
pathVars devpath is the device root path (e.g. /dev/device/ckb1), cmdpath leads to the daemon input pipe for daemon commands, notifyPath is the standard input monitor for general purpose.
QString cmdpath
QString notifyPath
KbProfile * _currentProfile
QList< KbProfile * > _profiles
KbMode * _currentMode
KeyMap::Model _model
bool iState [KbPerf::HW_I_COUNT]
QString prefsPath
quint64 lastAutoSave
QString fwUpdPath
KbProfile * _hwProfile
KbProfile * prevProfile
KbMode * prevMode
QFile cmd
int notifyNumber
notifyNumber is the trailing number in the device path.
bool _needsSave
bool hwLoading [HWMODE_MAX+1]
Static Private Attributes
static QString macroPath = ''
macroPath added for a second thread to read macro input. Must be static, because there is only one keyboard but multiple devices.
static KeyMap::Layout _layout = KeyMap::NO_LAYOUT
static int _frameRate = 30
static int _scrollSpeed = 0
static bool _dither = false
static bool _mouseAccel = true
static int macroNumber = -1
Macro Number to notify macro definition events. As macroPath, macroNumber must be static, because only keyboard may set this value and others (eg mice) needs to read it.
static bool _delay = false
flag if macro delay hast to be switched on
Friends
class KbManager
Detailed Description
Definition at line 11 of file kb.h.
Constructor & Destructor Documentation
Kb::~Kb ()
<
Todo
I don't think, that notifypaths is used somewhere. So why do we have it? If we do not need it, searching for an ununsed notify channel can easy be refactored to a private member function.
Definition at line 192 of file kb.cpp.
References activeDevices, isOpen(), macroPath, notifyNumber, notifyPaths, and save().
       {
    // Save settings first
    save();
    // remove the notify channel from the list of notifyPaths.
    notifyPaths.remove(macroPath);
    // Kill notification thread and remove node
    activeDevices.remove(this);
    if(!isOpen()){
        terminate();
        wait(1000);
        return;
    }
    if(notifyNumber > 0)
        cmd.write(QString("idle\nnotifyoff %1\n").arg(notifyNumber).toLatin1());
    cmd.flush();
    terminate();
    wait(1000);
    cmd.close();
}
Kb::Kb (QObject *parent, const QString &path) [private]
< Firmware Info is now current fw-number:vendor:model Look for special entries (newest models)
< perhaps we have found something, perhaps not.
< If nothing found in the special firmware search, try here.
Last chance gone to get a valid firmware information.
Handle inputs
< This is the normal case if we have a new daemon and a running device
< That means we have an older daemon which does not write three infos into the file
Open cmd in non-blocking mode so that it doesn't lock up if nothing is reading (e.g. if the daemon crashed and didn't clean up the node)
Find an available notification node (if none is found, take notify1)
Again, find an available notification node for macro definition if we handle a keyboard. (if none is found, take notify2)
Block ist used to have QMutexLocker as an auto var.
<
Todo
Is adding notifyX to the notifypaths neccessary?
Definition at line 23 of file kb.cpp.
References _delay, _dither, _frameRate, _layout, _model, _mouseAccel, _scrollSpeed, activeDevices, cmdpath, features, firmware, KeyMap::getModel(), hwLoading, hwModeCount, infoUpdated(), KeyMap::isISO(), isKeyboard(), iState, KeyMap::K95, macroNumber, macroPath, monochrome, KeyMap::NO_MODEL, notifyNumber, notifyPath, notifyPathMutex, notifyPaths, pollrate, prefsPath, usbModel, and usbSerial.
                                           :
    QThread(parent), features("N/A"), firmware("N/A"), pollrate("N/A"), monochrome(false),
    devpath(path), cmdpath(path + "/cmd"), notifyPath(path + "/notify1"),
    _currentProfile(0), _currentMode(0), _model(KeyMap::NO_MODEL),
    lastAutoSave(QDateTime::currentMSecsSinceEpoch()),
    _hwProfile(0), prevProfile(0), prevMode(0),
    cmd(cmdpath), notifyNumber(1), _needsSave(false)
{
    memset(iState, 0, sizeof(iState));
    memset(hwLoading, 0, sizeof(hwLoading));
    // Get the features, model, serial number, FW version (if available), and poll rate (if available) from /dev nodes
    QFile ftpath(path + "/features"), mpath(path + "/model"), spath(path + "/serial"), fwpath(path + "/fwversion"), ppath(path + "/pollrate");
    if(fwpath.open(QIODevice::ReadOnly)){
        QString fwString = fwpath.read(1000);
        fwString = fwString.trimmed();
        fwpath.close();
        QStringList list = fwString.split(":");
        if(list.length() == 3) {
            bool okVendor, okProduct;
            const uint vendor = list[1].toUInt(&okVendor, 16);
            const uint product = list[2].toUInt(&okProduct, 16);
            if (okVendor && okProduct) _model = KeyMap::getModel(vendor, product);
            qInfo() << "first look for special firmware returned" << _model;
        } else qWarning() << "Expected 3 entries in file" << fwpath.fileName() << "but reading" << list.length();
    }
    if(ftpath.open(QIODevice::ReadOnly)){
        features = ftpath.read(1000);
        features = features.trimmed();
        ftpath.close();
        // Read model from features (first word: vendor, second word: product)
        QStringList list = features.split(" ");
        if(list.length() < 2) {
            qDebug() << "Kb::Kb() Error in reading features, read" << list.length() << "entries, 2 expected.";
            return;
        }
        if (_model == KeyMap::NO_MODEL) {
            _model = KeyMap::getModel(list[1]);
        }
        if (_model == KeyMap::NO_MODEL) {
            qCritical() << "Neither firmware-special-search nor feature file analysis resulted in valid firmware information.";
            return;
        }
    } else
        // Bail if features aren't readable
        return;
    if(features.contains("monochrome"))
        monochrome = true;
    if(mpath.open(QIODevice::ReadOnly)){
        usbModel = mpath.read(100);
        usbModel = usbModel.remove("Corsair").remove("Gaming").remove("Keyboard").remove("Mouse").remove("Bootloader").trimmed();
        mpath.close();
    }
    if(usbModel == "")
        usbModel = "Keyboard";
    if(spath.open(QIODevice::ReadOnly)){
        usbSerial = spath.read(100);
        usbSerial = usbSerial.trimmed().toUpper();
        spath.close();
    }
    if(usbSerial == "")
        usbSerial = "Unknown-" + usbModel;
    if(features.contains("fwversion") && fwpath.open(QIODevice::ReadOnly)){
        QString firmwareString = fwpath.read(100);
        fwpath.close();
        QStringList firmwareList = firmwareString.remove("\n").split(":");
        switch (firmwareList.length()) {
        case 3:
            qInfo() << "Reading 3 entries from fwversion file, VID=" << firmwareList.at(1) << ", PID=" << firmwareList.at(2);
        case 1:
            firmware = QString::number(firmwareList.at(0).trimmed().toInt() / 100., 'f', 2);
            qInfo() << "Firmware version read from ckb-daemon in fwversion file is" << firmwareList.at(0);
            break;
        default:
            qCritical() << "Firware version file is invalid. Number of entries is" << firmwareList.length();
            break;
        }
    }
    if(features.contains("pollrate") && ppath.open(QIODevice::ReadOnly)){
        pollrate = ppath.read(100);
        pollrate = pollrate.trimmed();
        ppath.close();
    }
    prefsPath = "Devices/" + usbSerial;
    qDebug() << "Features =" << features;
    hwModeCount = (_model == KeyMap::K95) ? 3 : 1;
    int fd = open(cmdpath.toLatin1().constData(), O_WRONLY | O_NONBLOCK);
    if(!cmd.open(fd, QIODevice::WriteOnly, QFileDevice::AutoCloseHandle))
        return;
    {
        QMutexLocker locker(&notifyPathMutex);
        for (int i = 1; i < 10; i++) {
            QString notify = QString(path + "/notify%1").arg(i);
            if(!QFile::exists(notify) && !notifyPaths.contains(notify)){
                notifyNumber = i;
                notifyPath = notify;
                break;
            }
        }
        notifyPaths.insert(notifyPath);
    }
    cmd.write(QString("notifyon %1\n").arg(notifyNumber).toLatin1());
    cmd.flush();
    if (isKeyboard()) {
        qDebug() << "Keyboard detected, setting macroPath and macroNumber";
        if (macroPath != "") {
            qDebug() << "Warning: Redefinition of macroPath. Value was" << macroPath;
        }
        {
            QMutexLocker locker(&notifyPathMutex);
            int i;
            for (i = 1; i < 10; i++) {
                QString notify = QString(path + "/notify%1").arg(i);
                if(!QFile::exists(notify) && !notifyPaths.contains(notify)){
                    macroNumber = i;
                    break;
                }
            }
            if (i == 10) {
                macroNumber = 2;
            }
            macroPath = path;
            notifyPaths.insert(QString(macroPath + "/notify%1").arg(macroNumber));
            qDebug() << "new macroPath =" << macroPath << "and macroNumber =" << macroNumber;
        }
    } else {
        qDebug() << "No Keyboard detected, leaving macroPath as is:" << macroPath << "and macroNumber as" << macroNumber;
    }
    // Activate device, apply settings, and ask for hardware profile
    cmd.write(QString("fps %1\n").arg(_frameRate).toLatin1());
    cmd.write(QString("dither %1\n").arg(static_cast<int>(_dither)).toLatin1());
    cmd.write(QString("\ndelay %1\n").arg(_delay? "on" : "off").toLatin1());
#ifdef Q_OS_MACX
    // Write ANSI/ISO flag to daemon (OSX only)
    cmd.write("layout ");
    cmd.write(KeyMap::isISO(_layout) ? "iso" : "ansi");
    // Also OSX only: scroll speed and mouse acceleration
    cmd.write(QString("accel %1\n").arg(QString(_mouseAccel ? "on" : "off")).toLatin1());
    cmd.write(QString("scrollspeed %1\n").arg(_scrollSpeed).toLatin1());
#endif
    cmd.write(QString("\nactive\n@%1 get :hwprofileid").arg(notifyNumber).toLatin1());
    hwLoading[0] = true;
    for(int i = 0; i < hwModeCount; i++){
        cmd.write(QString(" mode %1 get :hwid").arg(i + 1).toLatin1());
        hwLoading[i + 1] = true;
    }
    // Ask for current indicator and key state
    cmd.write(" get :i :keys\n");
    cmd.flush();
    emit infoUpdated();
    activeDevices.insert(this);
    // Start a separate thread to read from the notification node
    start();
}
Member Function Documentation
void Kb::appendProfile (KbProfile *newProfile) [inline]
Definition at line 60 of file kb.h.
References _needsSave, and _profiles.
Referenced by KbProfileDialog::on_profileList_itemClicked().
{ _needsSave = true; _profiles.append(newProfile); }
void Kb::autoSave () [slot]
Definition at line 340 of file kb.cpp.
References CkbSettings::isBusy(), lastAutoSave, needsSave(), and save().
                 {
    quint64 now = QDateTime::currentMSecsSinceEpoch();
    if(needsSave() && now >= lastAutoSave + 15 * 1000 && !CkbSettings::isBusy()){
        save();
        lastAutoSave = now;
    }
}
KbBind* Kb::currentBind () [inline]
Definition at line 67 of file kb.h.
References _currentMode, and KbMode::bind().
Referenced by KbWidget::modeChanged().
{ return !_currentMode ? 0 : _currentMode->bind(); }
KbLight* Kb::currentLight () [inline]
Definition at line 66 of file kb.h.
References _currentMode, and KbMode::light().
Referenced by KbWidget::modeChanged().
{ return !_currentMode ? 0 : _currentMode->light(); }
KbMode* Kb::currentMode () [inline]
Definition at line 65 of file kb.h.
References _currentMode.
Referenced by KbWidget::modeChanged().
{ return _currentMode; }
KbPerf* Kb::currentPerf () [inline]
Definition at line 68 of file kb.h.
References _currentMode, and KbMode::perf().
Referenced by KbWidget::modeChanged().
{ return !_currentMode ? 0 : _currentMode->perf(); }
KbProfile* Kb::currentProfile () [inline]
Definition at line 56 of file kb.h.
References _currentProfile.
Referenced by KeyAction::keyEvent(), KbWidget::modeChanged(), KbWidget::modeIcon(), KbWidget::modesList_reordered(), KbWidget::on_modesList_currentItemChanged(), KbWidget::on_modesList_customContextMenuRequested(), KbWidget::on_modesList_itemClicked(), KbProfileDialog::on_profileList_customContextMenuRequested(), KbProfileDialog::on_profileList_itemChanged(), KbWidget::profileChanged(), KbProfileDialog::repopulate(), and KbWidget::updateProfileList().
{ return _currentProfile; }
void Kb::deleteHw () [private], [slot]
Definition at line 492 of file kb.cpp.
References _hwProfile.
Referenced by hwProfile().
                 {
    disconnect(_hwProfile, SIGNAL(destroyed()), this, SLOT(deleteHw()));
    _hwProfile = 0;
}
void Kb::deletePrevious () [private], [slot]
Definition at line 477 of file kb.cpp.
References prevMode.
Referenced by frameUpdate(), and hwSave().
                       {
    disconnect(prevMode, SIGNAL(destroyed()), this, SLOT(deletePrevious()));
    prevMode = 0;
}
static bool Kb::dither () [inline], [static]
Definition at line 33 of file kb.h.
References _dither.
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), and ExtraSettingsWidget::on_ditherBox_clicked().
{ return _dither; }
void Kb::dither (boolnewDither) [static]
Definition at line 255 of file kb.cpp.
References _dither, activeDevices, and cmd.
                             {
    if(newDither == _dither)
        return;
    _dither = newDither;
    // Update all devices
    foreach(Kb* kb, activeDevices){
        kb->cmd.write(QString("dither %1\n").arg(static_cast<int>(newDither)).toLatin1());
        kb->cmd.flush();
    }
}
KbProfile* Kb::find (const QUuid &id) [inline]
Definition at line 62 of file kb.h.
References _profiles, UsbId::guid, and KbProfile::id().
Referenced by KbProfileDialog::on_profileList_currentItemChanged(), KbProfileDialog::on_profileList_customContextMenuRequested(), and KbProfileDialog::profileList_reordered().
{ foreach(KbProfile* profile, _profiles) { if(profile->id().guid == id) return profile; } return 0; }
static int Kb::frameRate () [inline], [static]
Definition at line 27 of file kb.h.
References _frameRate.
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), and ExtraSettingsWidget::on_fpsBox_valueChanged().
{ return _frameRate; }
void Kb::frameRate (intnewFrameRate) [static]
Definition at line 216 of file kb.cpp.
References _frameRate, activeDevices, cmd, and KbManager::fps().
                                  {
    KbManager::fps(newFrameRate);
    // If the rate has changed, send to all devices
    if(newFrameRate == _frameRate)
        return;
    _frameRate = newFrameRate;
    foreach(Kb* kb, activeDevices){
        kb->cmd.write(QString("fps %1\n").arg(newFrameRate).toLatin1());
        kb->cmd.flush();
    }
}
void Kb::frameUpdate () [slot]
Definition at line 426 of file kb.cpp.
References _currentMode, _currentProfile, KbPerf::applyIndicators(), KbMode::bind(), KbLight::close(), deletePrevious(), KbLight::frameUpdate(), KbProfile::indexOf(), KbLight::isStarted(), iState, KbMode::light(), monochrome, notifyNumber, KbLight::open(), KbMode::perf(), prevMode, prevProfile, KbBind::update(), KbPerf::update(), and writeProfileHeader().
                    {
    // Advance animation frame
    if(!_currentMode)
        return;
    KbLight* light = _currentMode->light();
    KbBind* bind = _currentMode->bind();
    KbPerf* perf = _currentMode->perf();
    if(!light->isStarted()){
        // Don't do anything until the animations are started
        light->open();
        return;
    }
    // Stop animations on the previously active mode (if any)
    bool changed = false;
    if(prevMode != _currentMode){
        if(prevMode){
            prevMode->light()->close();
            disconnect(prevMode, SIGNAL(destroyed()), this, SLOT(deletePrevious()));
        }
        prevMode = _currentMode;
        connect(prevMode, SIGNAL(destroyed()), this, SLOT(deletePrevious()));
        changed = true;
    }
    // If the profile has changed, update it
    if(prevProfile != _currentProfile){
        writeProfileHeader();
        cmd.write(" ");
        prevProfile = _currentProfile;
    }
    // Update current mode
    int index = _currentProfile->indexOf(_currentMode);
    // ckb-daemon only has 6 modes: 3 hardware, 3 non-hardware. Beyond mode six, switch back to four.
    // e.g. 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6 ...
    if(index >= 6)
        index = 3 + index % 3;
    // Send lighting/binding to driver
    cmd.write(QString("mode %1 switch ").arg(index + 1).toLatin1());
    perf->applyIndicators(index, iState);
    light->frameUpdate(cmd, monochrome);
    cmd.write(QString("\n@%1 ").arg(notifyNumber).toLatin1());
    bind->update(cmd, changed);
    cmd.write(" ");
    perf->update(cmd, notifyNumber, changed);
    cmd.write("\n");
    cmd.flush();
}
void Kb::fwUpdate (const QString &path)
Definition at line 416 of file kb.cpp.
References fwUpdPath, and notifyNumber.
Referenced by FwUpgradeDialog::on_actionButton_clicked().
                                    {
    fwUpdPath = path;
    // Write the active command to ensure it's not ignored
    cmd.write("active");
    cmd.write(QString(" @%1 ").arg(notifyNumber).toLatin1());
    cmd.write("fwupdate ");
    cmd.write(path.toLatin1());
    cmd.write("\n");
}
void Kb::fwUpdateFinished (boolsucceeded) [signal]
Definition at line 277 of file moc_kb.cpp.
Referenced by readNotify().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 7, _a);
}
void Kb::fwUpdateProgress (intcurrent, inttotal) [signal]
Definition at line 270 of file moc_kb.cpp.
Referenced by readNotify().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 6, _a);
}
KeyMap Kb::getKeyMap () [private]
Definition at line 807 of file kb.cpp.
References _layout.
Referenced by hwSave(), load(), newMode(), newProfile(), readNotify(), setCurrentProfile(), and updateLayout().
                    {
    return KeyMap(_model, _layout);
}
int Kb::getMacroNumber () [inline]
getMacroNumber returns the macroNumber, which we have saved in the constructor. For usage with macro definions, this param must only be readable. So there is no setter.
Returns:
The Number is returned as int.
Definition at line 97 of file kb.h.
References macroNumber.
Referenced by KbBind::getMacroNumber().
{ return macroNumber; }
QString Kb::getMacroPath () [inline]
Returns:
The absolute path as String
Definition at line 106 of file kb.h.
References macroPath.
Referenced by KbBind::getMacroPath().
{ return macroPath; }
KbProfile* Kb::hwProfile () [inline]
Definition at line 46 of file kb.h.
References _hwProfile.
Referenced by hwSave(), KbWidget::modeIcon(), KbProfileDialog::on_profileList_customContextMenuRequested(), readNotify(), KbProfileDialog::repopulate(), and KbWidget::updateProfileList().
{ return _hwProfile; }
void Kb::hwProfile (KbProfile *newHwProfile)
Definition at line 482 of file kb.cpp.
References _hwProfile, and deleteHw().
                                         {
    if(_hwProfile == newHwProfile)
        return;
    if(_hwProfile)
        disconnect(_hwProfile, SIGNAL(destroyed()), this, SLOT(deleteHw()));
    _hwProfile = newHwProfile;
    if(_hwProfile)
        connect(_hwProfile, SIGNAL(destroyed()), this, SLOT(deleteHw()));
}
void Kb::hwSave ()
Definition at line 348 of file kb.cpp.
References _currentMode, _currentProfile, _hwProfile, KbProfile::append(), KbLight::base(), KbLight::close(), deletePrevious(), getKeyMap(), UsbId::guidString(), hwModeCount, UsbId::hwModified, hwProfile(), KbProfile::id(), KbMode::id(), KbMode::light(), KbProfile::modeCount(), KbProfile::modes(), UsbId::modified, UsbId::modifiedString(), monochrome, KbMode::name(), KbMode::perf(), prevMode, KbProfile::setNeedsSave(), KbMode::setNeedsSave(), KbPerf::update(), and writeProfileHeader().
Referenced by KbWidget::on_hwSaveButton_clicked(), and KbProfileDialog::on_profileList_customContextMenuRequested().
               {
    if(!_currentProfile)
        return;
    // Close active lighting (if any)
    if(prevMode){
        prevMode->light()->close();
        deletePrevious();
    }
    hwProfile(_currentProfile);
    _hwProfile->id().hwModified = _hwProfile->id().modified;
    _hwProfile->setNeedsSave();
    // Re-send the current profile from scratch to ensure consistency
    writeProfileHeader();
    // Make sure there are enough modes
    while(_currentProfile->modeCount() < hwModeCount)
        _currentProfile->append(new KbMode(this, getKeyMap()));
    // Write only the base colors of each mode, no animations
    for(int i = 0; i < hwModeCount; i++){
        KbMode* mode = _currentProfile->modes()[i];
        cmd.write(QString("\nmode %1").arg(i + 1).toLatin1());
        KbLight* light = mode->light();
        KbPerf* perf = mode->perf();
        if(mode == _currentMode)
            cmd.write(" switch");
        // Write the mode name and ID
        cmd.write(" name ");
        cmd.write(QUrl::toPercentEncoding(mode->name()));
        cmd.write(" id ");
        cmd.write(mode->id().guidString().toLatin1());
        cmd.write(" ");
        cmd.write(mode->id().modifiedString().toLatin1());
        cmd.write(" ");
        // Write lighting and performance
        light->base(cmd, true, monochrome);
        cmd.write(" ");
        perf->update(cmd, true, false);
        // Update mode ID
        mode->id().hwModified = mode->id().modified;
        mode->setNeedsSave();
    }
    cmd.write("\n");
    // Save the profile to memory
    cmd.write("hwsave\n");
    cmd.flush();
}
int Kb::indexOf (KbProfile *profile) [inline]
Definition at line 61 of file kb.h.
References _profiles.
Referenced by KbProfileDialog::on_profileList_customContextMenuRequested().
{ return _profiles.indexOf(profile); }
void Kb::infoUpdated () [signal]
Definition at line 233 of file moc_kb.cpp.
Referenced by Kb(), load(), and updateLayout().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
bool Kb::isKeyboard () const [inline]
Definition at line 23 of file kb.h.
References KeyMap::isKeyboard().
Referenced by Kb(), and KbWidget::KbWidget().
{ return KeyMap::isKeyboard(_model); }
bool Kb::isMouse () const [inline]
Definition at line 24 of file kb.h.
References KeyMap::isMouse().
Referenced by KbWidget::KbWidget(), and readNotify().
{ return KeyMap::isMouse(_model); }
bool Kb::isOpen () const [inline], [private]
Definition at line 147 of file kb.h.
Referenced by KbManager::scanKeyboards(), and ~Kb().
{ return cmd.isOpen(); }
static KeyMap::Layout Kb::layout () [inline], [static]
Definition at line 30 of file kb.h.
References _layout.
Referenced by LayoutDialog::LayoutDialog(), SettingsWidget::on_layoutBox_activated(), and SettingsWidget::SettingsWidget().
{ return _layout; }
void Kb::layout (KeyMap::LayoutnewLayout) [static]
Definition at line 228 of file kb.cpp.
References _layout, activeDevices, KeyMap::NO_LAYOUT, and updateLayout().
                                     {
    if(newLayout == KeyMap::NO_LAYOUT || newLayout == _layout)
        return;
    _layout = newLayout;
    // Update all devices
    foreach(Kb* kb, activeDevices)
        kb->updateLayout();
}
void Kb::load ()
Definition at line 292 of file kb.cpp.
References _needsSave, _profiles, current, getKeyMap(), infoUpdated(), prefsPath, profileAdded(), setCurrentProfile(), and CkbSettings::value().
Referenced by KbManager::scanKeyboards().
             {
    if(prefsPath.isEmpty())
        return;
    _needsSave = false;
    CkbSettings settings(prefsPath);
    // Read profiles
    KbProfile* newCurrentProfile = 0;
    QString current = settings.value("CurrentProfile").toString().trimmed().toUpper();
    foreach(QString guid, settings.value("Profiles").toString().split(" ")){
        guid = guid.trimmed().toUpper();
        if(guid != ""){
            KbProfile* profile = new KbProfile(this, getKeyMap(), settings, guid);
            _profiles.append(profile);
            if(guid == current || !newCurrentProfile)
                newCurrentProfile = profile;
        }
    }
    if(newCurrentProfile)
        setCurrentProfile(newCurrentProfile);
    else {
        // If nothing was loaded, load the demo profile
        QSettings demoSettings(":/txt/demoprofile.conf", QSettings::IniFormat, this);
        CkbSettings cSettings(demoSettings);
        KbProfile* demo = new KbProfile(this, getKeyMap(), cSettings, "{BA7FC152-2D51-4C26-A7A6-A036CC93D924}");
        _profiles.append(demo);
        setCurrentProfile(demo);
    }
    emit infoUpdated();
    emit profileAdded();
}
static bool Kb::macroDelay () [inline], [static]
Definition at line 36 of file kb.h.
References _delay.
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), and ExtraSettingsWidget::on_delayBox_clicked().
{ return _delay; }
void Kb::macroDelay (boolflag) [static]
Parameters:
flag true: Switch on delay function, else switch off
Definition at line 838 of file kb.cpp.
References _delay, activeDevices, and cmd.
                             {
   _delay = flag;
   foreach(Kb* kb, activeDevices){
       kb->cmd.write(QString("\ndelay %1\n").arg(flag? "on" : "off").toLatin1());
   }
}
bool Kb::matches (const QString &path, const QString &serial) [inline], [private]
Definition at line 161 of file kb.h.
References devpath, and usbSerial.
Referenced by KbManager::scanKeyboards().
{ return path.trimmed() == devpath.trimmed() && usbSerial == serial.trimmed().toUpper(); }
void Kb::modeChanged (boolspontaneous) [signal]
Definition at line 263 of file moc_kb.cpp.
Referenced by setCurrentMode().
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 5, _a);
}
KeyMap::Model Kb::model () const [inline]
Definition at line 22 of file kb.h.
References _model.
{ return _model; }
void Kb::modeRenamed () [signal]
Definition at line 251 of file moc_kb.cpp.
Referenced by readNotify().
{
    QMetaObject::activate(this, &staticMetaObject, 3, Q_NULLPTR);
}
static bool Kb::mouseAccel () [inline], [static]
Definition at line 39 of file kb.h.
References _mouseAccel.
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), and ExtraSettingsWidget::on_mAccelBox_clicked().
{ return _mouseAccel; }
void Kb::mouseAccel (boolnewAccel) [static]
Definition at line 266 of file kb.cpp.
References _mouseAccel, activeDevices, and cmd.
                                {
    if(newAccel == _mouseAccel)
        return;
    _mouseAccel = newAccel;
#ifdef Q_OS_MACX
    // Update all devices
    foreach(Kb* kb, activeDevices){
        kb->cmd.write(QString("accel %1\n").arg(QString(newAccel ? "on" : "off")).toLatin1());
        kb->cmd.flush();
    }
#endif
}
bool Kb::needsSave () const
Definition at line 395 of file kb.cpp.
References _needsSave, _profiles, and KbProfile::needsSave().
Referenced by autoSave().
                         {
    if(_needsSave)
        return true;
    foreach(const KbProfile* profile, _profiles){
        if(profile->needsSave())
            return true;
    }
    return false;
}
KbMode* Kb::newMode () [inline]
Definition at line 79 of file kb.h.
References getKeyMap().
Referenced by KbWidget::on_modesList_customContextMenuRequested(), and KbWidget::on_modesList_itemClicked().
{ return new KbMode(this, getKeyMap()); }
KbMode* Kb::newMode (KbMode *other) [inline]
Definition at line 80 of file kb.h.
References getKeyMap().
{ return new KbMode(this, getKeyMap(), *other); }
KbProfile* Kb::newProfile () [inline]
Definition at line 77 of file kb.h.
References getKeyMap().
Referenced by KbProfileDialog::on_profileList_customContextMenuRequested(), KbProfileDialog::on_profileList_itemClicked(), and readNotify().
{ return new KbProfile(this, getKeyMap()); }
KbProfile* Kb::newProfile (KbProfile *other) [inline]
Definition at line 78 of file kb.h.
References getKeyMap().
{ return new KbProfile(this, getKeyMap(), *other); }
void Kb::profileAdded () [signal]
Definition at line 239 of file moc_kb.cpp.
Referenced by load(), and readNotify().
{
    QMetaObject::activate(this, &staticMetaObject, 1, Q_NULLPTR);
}
void Kb::profileChanged () [signal]
Definition at line 257 of file moc_kb.cpp.
Referenced by readNotify(), and setCurrentMode().
{
    QMetaObject::activate(this, &staticMetaObject, 4, Q_NULLPTR);
}
void Kb::profileRenamed () [signal]
Definition at line 245 of file moc_kb.cpp.
Referenced by readNotify().
{
    QMetaObject::activate(this, &staticMetaObject, 2, Q_NULLPTR);
}
const QList<KbProfile*>& Kb::profiles () const [inline]
Definition at line 58 of file kb.h.
References _profiles.
Referenced by KbWidget::on_profileBox_activated(), KbProfileDialog::on_profileList_customContextMenuRequested(), KbProfileDialog::profileList_reordered(), KbProfileDialog::repopulate(), and KbWidget::updateProfileList().
{ return _profiles; }
void Kb::profiles (const QList< KbProfile * > &newProfiles) [inline]
Definition at line 59 of file kb.h.
References _needsSave, and _profiles.
{ _needsSave = true; _profiles = newProfiles; }
void Kb::readNotify (QStringline) [private], [slot]
Definition at line 522 of file kb.cpp.
References _currentMode, _currentProfile, _hwProfile, _needsSave, _profiles, KbPerf::angleSnap(), KbLight::animKeypress(), KbProfile::append(), KbMode::bind(), KbLight::color(), KbPerf::curDpiIdx(), KbPerf::dpi(), KbPerf::DPI_COUNT, KbPerf::dpiColor(), KbPerf::dpiEnabled(), fwUpdateFinished(), fwUpdateProgress(), fwUpdPath, getKeyMap(), UsbId::guid, hwLoading, HWMODE_MAX, hwModeCount, UsbId::hwModifiedString(), hwProfile(), KbProfile::id(), KbMode::id(), KbProfile::indexOf(), isMouse(), iState, KbBind::keyEvent(), KbPerf::liftHeight(), KbMode::light(), KbProfile::modeCount(), modeRenamed(), KbProfile::modes(), UsbId::modifiedString(), KbProfile::move(), KbProfile::name(), KbMode::name(), newProfile(), notifyNumber, KbMode::perf(), profileAdded(), profileChanged(), profileRenamed(), setCurrentProfile(), KbProfile::setNeedsSave(), KbMode::setNeedsSave(), x, and y.
                               {
    QStringList components = line.trimmed().split(" ");
    if(components.count() < 2)
        return;
    if(components[0] == "key"){
        // Key event
        QString key = components[1];
        if(key.length() < 2)
            return;
        QString keyName = key.mid(1);
        bool keyPressed = (key[0] == '+');
        KbMode* mode = _currentMode;
        if(mode){
            mode->light()->animKeypress(keyName, keyPressed);
            mode->bind()->keyEvent(keyName, keyPressed);
        }
    } else if(components[0] == "i"){
        // Indicator event
        QString i = components[1];
        if(i.length() < 2)
            return;
        QString iName = i.mid(1);
        bool on = (i[0] == '+');
        if(iName == "num")
            iState[0] = on;
        else if(iName == "caps")
            iState[1] = on;
        else if(iName == "scroll")
            iState[2] = on;
    } else if(components[0] == "hwprofileid"){
        // Hardware profile ID
        if(components.count() < 3)
            return;
        // Find the hardware profile in the list of profiles
        QString guid = components[1];
        QString modified = components[2];
        KbProfile* newProfile = 0;
        foreach(KbProfile* profile, _profiles){
            if(profile->id().guid == guid){
                newProfile = profile;
                break;
            }
        }
        // If it wasn't found, create it
        if(!newProfile){
            newProfile = new KbProfile(this, getKeyMap(), guid, modified);
            hwLoading[0] = true;
            cmd.write(QString("@%1 get :hwprofilename\n").arg(notifyNumber).toLatin1());
            cmd.flush();
        } else {
            // If it's been updated, fetch its name
            if(newProfile->id().hwModifiedString() != modified){
                newProfile->id().modifiedString(modified);
                newProfile->id().hwModifiedString(modified);
                newProfile->setNeedsSave();
                if(hwLoading[0]){
                    cmd.write(QString("@%1 get :hwprofilename\n").arg(notifyNumber).toLatin1());
                    cmd.flush();
                }
            } else {
                hwLoading[0] = false;
            }
        }
        hwProfile(newProfile);
        emit profileAdded();
        if(_hwProfile == _currentProfile)
            emit profileChanged();
    } else if(components[0] == "hwprofilename"){
        // Hardware profile name
        QString name = QUrl::fromPercentEncoding(components[1].toUtf8());
        if(!_hwProfile || !hwLoading[0])
            return;
        QString oldName = _hwProfile->name();
        if(!(oldName.length() >= name.length() && oldName.left(name.length()) == name)){
            // Don't change the name if it's a truncated version of what we already have
            _hwProfile->name(name);
            emit profileRenamed();
        }
    } else if(components[0] == "mode"){
        // Mode-specific data
        if(components.count() < 4)
            return;
        int mode = components[1].toInt() - 1;
        if(components[2] == "hwid"){
            if(components.count() < 5 || mode >= HWMODE_MAX || !_hwProfile)
                return;
            // Hardware mode ID
            QString guid = components[3];
            QString modified = components[4];
            // Look for this mode in the hardware profile
            KbMode* hwMode = 0;
            bool isUpdated = false;
            foreach(KbMode* kbMode, _hwProfile->modes()){
                if(kbMode->id().guid == guid){
                    hwMode = kbMode;
                    if(kbMode->id().hwModifiedString() != modified){
                        // Update modification time
                        hwMode->id().modifiedString(modified);
                        hwMode->id().hwModifiedString(modified);
                        hwMode->setNeedsSave();
                        isUpdated = true;
                    } else {
                        hwLoading[mode + 1] = false;
                    }
                    break;
                }
            }
            // If it wasn't found, add it
            if(!hwMode){
                isUpdated = true;
                hwMode = new KbMode(this, getKeyMap(), guid, modified);
                _hwProfile->append(hwMode);
                // If the hardware profile now contains enough modes to be added to the list, do so
                if(!_profiles.contains(_hwProfile) && _hwProfile->modeCount() >= hwModeCount){
                    _profiles.append(_hwProfile);
                    _needsSave = true;
                    emit profileAdded();
                    if(!_currentProfile)
                        setCurrentProfile(_hwProfile);
                }
            }
            if(hwLoading[mode + 1] && isUpdated){
                // If the mode isn't in the right place, move it
                int index = _hwProfile->indexOf(hwMode);
                if(mode < _hwProfile->modeCount() && index != mode)
                    _hwProfile->move(index, mode);
                // Fetch the updated data
                cmd.write(QString("@%1 mode %2 get :hwname :hwrgb").arg(notifyNumber).arg(mode + 1).toLatin1());
                if(isMouse())
                    cmd.write(" :hwdpi :hwdpisel :hwlift :hwsnap");
                cmd.write("\n");
                cmd.flush();
            }
        } else if(components[2] == "hwname"){
            // Mode name - update list
            if(!_hwProfile || _hwProfile->modeCount() <= mode || mode >= HWMODE_MAX || !hwLoading[mode + 1])
                return;
            KbMode* hwMode = _hwProfile->modes()[mode];
            QString name = QUrl::fromPercentEncoding(components[3].toUtf8());
            QString oldName = hwMode->name();
            if(!(oldName.length() >= name.length() && oldName.left(name.length()) == name)){
                // Don't change the name if it's a truncated version of what we already have
                hwMode->name(name);
                if(_hwProfile == _currentProfile)
                    emit modeRenamed();
            }
        } else if(components[2] == "hwrgb"){
            // RGB - set mode lighting
            if(!_hwProfile || _hwProfile->modeCount() <= mode || mode >= HWMODE_MAX || !hwLoading[mode + 1])
                return;
            KbMode* kbmode = _hwProfile->modes()[mode];
            KbLight* light = kbmode->light();
            // Scan the input for colors
            QColor lightColor = QColor();
            for(int i = 3; i < components.count(); i++){
                QString comp = components[i];
                if(comp.indexOf(":") < 0){
                    // No ":" - single hex constant
                    bool ok;
                    int rgb = comp.toInt(&ok, 16);
                    if(ok)
                        light->color(QColor::fromRgb((QRgb)rgb));
                } else {
                    // List of keys ("a,b:xxxxxx"). Parse color first
                    QStringList set = comp.split(":");
                    bool ok;
                    int rgb = set[1].toInt(&ok, 16);
                    if(ok){
                        QColor color = QColor::fromRgb((QRgb)rgb);
                        // Parse keys
                        QStringList keys = set[0].split(",");
                        foreach(QString key, keys){
                            if(key == "light")
                                // Extrapolate the Light key to the M-keys and Lock key, since those will be set to black on hwsave
                                lightColor = color;
                            if(key.startsWith("dpi") && key.length() > 3){
                                // DPI levels go to the KbPerf object instead of KbLight
                                bool ok = false;
                                int index = key.mid(3).toInt(&ok);
                                if(ok)
                                    kbmode->perf()->dpiColor(index, color);
                                continue;
                            }
                            light->color(key, color);
                        }
                    }
                }
            }
            if(lightColor.isValid()){
                light->color("mr", lightColor);
                light->color("m1", lightColor);
                light->color("m2", lightColor);
                light->color("m3", lightColor);
                light->color("lock", lightColor);
            }
        } else if(components[2] == "hwdpi"){
            // DPI settings
            if(!_hwProfile || _hwProfile->modeCount() <= mode || mode >= HWMODE_MAX || !hwLoading[mode + 1])
                return;
            KbPerf* perf = _hwProfile->modes()[mode]->perf();
            // Read the rest of the line as stage:x,y
            foreach(QString comp, components.mid(3)){
                QStringList dpi = comp.split(':');
                if(dpi.length() != 2)
                    continue;
                QStringList xy = dpi[1].split(',');
                int x, y;
                bool off = false;
                if(xy.length() < 2){
                    // If the right side only has one parameter, set both X and Y
                    if(xy[0] == "off")
                        off = true;
                    else
                        x = y = xy[0].toInt();
                } else {
                    x = xy[0].toInt();
                    y = xy[1].toInt();
                }
                // Set DPI for this stage
                int index = dpi[0].toInt();
                if(off){
                    perf->dpiEnabled(index, false);
                    // If all DPIs have been disabled, turn them back on
                    bool allOff = true;
                    for(int i = 1; i < KbPerf::DPI_COUNT; i++){
                        if(perf->dpiEnabled(i)){
                            allOff = false;
                            break;
                        }
                    }
                    if(allOff){
                        for(int i = 1; i < KbPerf::DPI_COUNT; i++)
                            perf->dpiEnabled(i, true);
                    }
                } else {
                    perf->dpiEnabled(index, true);
                    perf->dpi(index, QPoint(x, y));
                }
            }
        } else if(components[2] == "hwdpisel"){
            // Hardware DPI selection (0...5)
            if(!_hwProfile || _hwProfile->modeCount() <= mode || mode >= HWMODE_MAX || !hwLoading[mode + 1])
                return;
            KbPerf* perf = _hwProfile->modes()[mode]->perf();
            int idx = components[3].toInt();
            if(idx < 1)
                idx = 1;
            if(idx >= KbPerf::DPI_COUNT)
                idx = KbPerf::DPI_COUNT - 1;
            perf->curDpiIdx(idx);
        } else if(components[2] == "hwlift"){
            // Mouse lift height (1...5)
            if(!_hwProfile || _hwProfile->modeCount() <= mode || mode >= HWMODE_MAX || !hwLoading[mode + 1])
                return;
            KbPerf* perf = _hwProfile->modes()[mode]->perf();
            perf->liftHeight((KbPerf::height)components[3].toInt());
        } else if(components[3] == "hwsnap"){
            // Mouse angle snapping ("on" or "off")
            if(!_hwProfile || _hwProfile->modeCount() <= mode || mode >= HWMODE_MAX || !hwLoading[mode + 1])
                return;
            KbPerf* perf = _hwProfile->modes()[mode]->perf();
            perf->angleSnap(components[3] == "on");
        }
    } else if(components[0] == "fwupdate"){
        // Firmware update progress
        if(components.count() < 3)
            return;
        // Make sure path is the same
        if(components[1] != fwUpdPath)
            return;
        QString res = components[2];
        if(res == "invalid" || res == "fail")
            emit fwUpdateFinished(false);
        else if(res == "ok")
            emit fwUpdateFinished(true);
        else {
            // "xx/yy" indicates progress
            if(!res.contains("/"))
                return;
            QStringList numbers = res.split("/");
            emit fwUpdateProgress(numbers[0].toInt(), numbers[1].toInt());
        }
    }
}
void Kb::run () [private]
Definition at line 497 of file kb.cpp.
References notifyPath, notifyPathMutex, and notifyPaths.
            {
    QFile notify(notifyPath);
    // Wait a small amount of time for the node to open (100ms)
    QThread::usleep(100000);
    if(!notify.open(QIODevice::ReadOnly)){
        // If it's still not open, try again before giving up (1s at a time, 10s total)
        QThread::usleep(900000);
        for(int i = 1; i < 10; i++){
            if(notify.open(QIODevice::ReadOnly))
                break;
            QThread::sleep(1);
        }
        if(!notify.isOpen())
            return;
    }
    // Read data from notification node
    QByteArray line;
    while(notify.isOpen() && (line = notify.readLine()).length() > 0){
        QString text = QString::fromUtf8(line);
        metaObject()->invokeMethod(this, "readNotify", Qt::QueuedConnection, Q_ARG(QString, text));
    }
    QMutexLocker locker(&notifyPathMutex);
    notifyPaths.remove(notifyPath);
}
void Kb::save ()
Definition at line 324 of file kb.cpp.
References _currentProfile, _needsSave, _profiles, UsbId::guidString(), KbProfile::id(), prefsPath, KbProfile::save(), and CkbSettings::setValue().
Referenced by autoSave(), KbWidget::on_hwSaveButton_clicked(), KbManager::scanKeyboards(), and ~Kb().
             {
    if(prefsPath.isEmpty())
        return;
    _needsSave = false;
    CkbSettings settings(prefsPath, true);
    QString guids, currentGuid;
    foreach(KbProfile* profile, _profiles){
        guids.append(" " + profile->id().guidString());
        if(profile == _currentProfile)
            currentGuid = profile->id().guidString();
        profile->save(settings);
    }
    settings.setValue("CurrentProfile", currentGuid);
    settings.setValue("Profiles", guids.trimmed());
}
static int Kb::scrollSpeed () [inline], [static]
Definition at line 42 of file kb.h.
References _scrollSpeed.
Referenced by ExtraSettingsWidget::ExtraSettingsWidget(), ExtraSettingsWidget::on_sAccelBox_clicked(), and ExtraSettingsWidget::on_sSpeedBox_valueChanged().
{ return _scrollSpeed; }
void Kb::scrollSpeed (intnewSpeed) [static]
Definition at line 279 of file kb.cpp.
References _scrollSpeed, activeDevices, and cmd.
                                {
    if(newSpeed == _scrollSpeed)
        return;
    _scrollSpeed = newSpeed;
#ifdef Q_OS_MACX
    // Update all devices
    foreach(Kb* kb, activeDevices){
        kb->cmd.write(QString("scrollspeed %1\n").arg(newSpeed).toLatin1());
        kb->cmd.flush();
    }
#endif
}
void Kb::setCurrentMode (KbProfile *profile, KbMode *mode, boolspontaneous = true)
Definition at line 820 of file kb.cpp.
References _currentMode, _currentProfile, _needsSave, KbProfile::currentMode(), modeChanged(), and profileChanged().
Referenced by KeyAction::keyEvent(), KbWidget::on_modesList_currentItemChanged(), KbWidget::on_modesList_customContextMenuRequested(), KbWidget::on_modesList_itemClicked(), and setCurrentProfile().
                                                                         {
    if(_currentProfile != profile){
        _currentProfile = profile;
        _needsSave = true;
        emit profileChanged();
    }
    if(_currentMode != mode || _currentProfile->currentMode() != mode){
        _currentProfile->currentMode(_currentMode = mode);
        _needsSave = true;
        emit modeChanged(spontaneous);
    }
}
void Kb::setCurrentMode (KbProfile *profile, intindex, boolspontaneous = true) [inline]
Definition at line 73 of file kb.h.
References KbProfile::modes(), and setCurrentMode().
Referenced by setCurrentMode().
{ setCurrentMode(profile, profile->modes()[index], spontaneous); }
void Kb::setCurrentMode (KbMode *mode, boolspontaneous = true) [inline]
Definition at line 74 of file kb.h.
References _currentProfile, and setCurrentMode().
Referenced by setCurrentMode().
{ setCurrentMode(_currentProfile, mode, spontaneous); }
void Kb::setCurrentProfile (KbProfile *profile, boolspontaneous = true)
Definition at line 811 of file kb.cpp.
References KbProfile::append(), KbProfile::currentMode(), getKeyMap(), hwModeCount, KbProfile::modeCount(), KbProfile::modes(), and setCurrentMode().
Referenced by load(), KbWidget::on_profileBox_activated(), KbProfileDialog::on_profileList_currentItemChanged(), KbProfileDialog::on_profileList_customContextMenuRequested(), KbProfileDialog::on_profileList_itemClicked(), and readNotify().
                                                              {
    while(profile->modeCount() < hwModeCount)
        profile->append(new KbMode(this, getKeyMap()));
    KbMode* mode = profile->currentMode();
    if(!mode)
        profile->currentMode(mode = profile->modes().first());
    setCurrentMode(profile, mode, spontaneous);
}
void Kb::updateLayout () [private]
Definition at line 237 of file kb.cpp.
References _currentProfile, _hwProfile, _layout, _profiles, KbLight::close(), getKeyMap(), infoUpdated(), KeyMap::isISO(), KbProfile::keyMap(), KbMode::light(), and KbProfile::modes().
Referenced by layout().
                     {
#ifdef Q_OS_MACX
    // Write ANSI/ISO flag to daemon (OSX only)
    cmd.write("layout ");
    cmd.write(KeyMap::isISO(_layout) ? "iso" : "ansi");
    cmd.write("\n");
    cmd.flush();
#endif
    foreach(KbProfile* profile, _profiles)
        profile->keyMap(getKeyMap());
    if(_hwProfile && !_profiles.contains(_hwProfile))
        _hwProfile->keyMap(getKeyMap());
    // Stop all animations as they'll need to be restarted
    foreach(KbMode* mode, _currentProfile->modes())
        mode->light()->close();
    emit infoUpdated();
}
void Kb::writeProfileHeader () [private]
Definition at line 405 of file kb.cpp.
References _currentProfile, UsbId::guidString(), KbProfile::id(), UsbId::modifiedString(), and KbProfile::name().
Referenced by frameUpdate(), and hwSave().
                           {
    cmd.write("eraseprofile");
    // Write the profile name and ID
    cmd.write(" profilename ");
    cmd.write(QUrl::toPercentEncoding(_currentProfile->name()));
    cmd.write(" profileid ");
    cmd.write(_currentProfile->id().guidString().toLatin1());
    cmd.write(" ");
    cmd.write(_currentProfile->id().modifiedString().toLatin1());
}
Friends And Related Function Documentation
friend class KbManager [friend]
Definition at line 142 of file kb.h.
Field Documentation
KbMode* Kb::_currentMode [private]
Definition at line 173 of file kb.h.
Referenced by currentBind(), currentLight(), currentMode(), currentPerf(), frameUpdate(), hwSave(), readNotify(), and setCurrentMode().
KbProfile* Kb::_currentProfile [private]
Definition at line 171 of file kb.h.
Referenced by currentProfile(), frameUpdate(), hwSave(), readNotify(), save(), setCurrentMode(), updateLayout(), and writeProfileHeader().
bool Kb::_delay = false [static], [private]
Definition at line 204 of file kb.h.
Referenced by Kb(), and macroDelay().
bool Kb::_dither = false [static], [private]
Definition at line 169 of file kb.h.
Referenced by dither(), and Kb().
int Kb::_frameRate = 30 [static], [private]
Definition at line 168 of file kb.h.
Referenced by frameRate(), and Kb().
KbProfile* Kb::_hwProfile [private]
Definition at line 187 of file kb.h.
Referenced by deleteHw(), hwProfile(), hwSave(), readNotify(), and updateLayout().
KeyMap::Layout Kb::_layout = KeyMap::NO_LAYOUT [static], [private]
Definition at line 165 of file kb.h.
Referenced by getKeyMap(), Kb(), layout(), and updateLayout().
KeyMap::Model Kb::_model [private]
Definition at line 175 of file kb.h.
Referenced by Kb(), and model().
bool Kb::_mouseAccel = true [static], [private]
Definition at line 169 of file kb.h.
Referenced by Kb(), and mouseAccel().
bool Kb::_needsSave [private]
Definition at line 207 of file kb.h.
Referenced by appendProfile(), load(), needsSave(), profiles(), readNotify(), save(), and setCurrentMode().
QList<KbProfile*> Kb::_profiles [private]
Definition at line 172 of file kb.h.
Referenced by appendProfile(), find(), indexOf(), load(), needsSave(), profiles(), readNotify(), save(), and updateLayout().
int Kb::_scrollSpeed = 0 [static], [private]
Definition at line 168 of file kb.h.
Referenced by Kb(), and scrollSpeed().
QFile Kb::cmd [private]
Definition at line 195 of file kb.h.
Referenced by dither(), frameRate(), macroDelay(), mouseAccel(), and scrollSpeed().
QString Kb::cmdpath [private]
Definition at line 154 of file kb.h.
Referenced by Kb().
QString Kb::devpath [private]
Definition at line 154 of file kb.h.
Referenced by matches().
QString Kb::features
Definition at line 18 of file kb.h.
Referenced by MainWindow::checkFwUpdates(), FwUpgradeDialog::exec(), Kb(), KbWidget::KbWidget(), KbWidget::on_fwUpdButton_clicked(), and KbWidget::updateFwButton().
QString Kb::firmware
Definition at line 18 of file kb.h.
Referenced by MainWindow::checkFwUpdates(), KbWidget::devUpdate(), FwUpgradeDialog::FwUpgradeDialog(), Kb(), KbWidget::on_fwUpdButton_clicked(), and KbWidget::updateFwButton().
QString Kb::fwUpdPath [private]
Definition at line 185 of file kb.h.
Referenced by fwUpdate(), and readNotify().
bool Kb::hwLoading[HWMODE_MAX+1] [private]
Definition at line 211 of file kb.h.
Referenced by Kb(), and readNotify().
const int Kb::HWMODE_MAX = 3 [static]
Definition at line 50 of file kb.h.
Referenced by KbPerf::applyIndicators(), and readNotify().
int Kb::hwModeCount
Definition at line 49 of file kb.h.
Referenced by hwSave(), Kb(), KbWidget::modeIcon(), KbWidget::on_modesList_customContextMenuRequested(), readNotify(), and setCurrentProfile().
bool Kb::iState[KbPerf::HW_I_COUNT] [private]
Definition at line 178 of file kb.h.
Referenced by frameUpdate(), Kb(), and readNotify().
quint64 Kb::lastAutoSave [private]
Definition at line 182 of file kb.h.
Referenced by autoSave().
int Kb::macroNumber = -1 [static], [private]
is invalid entry.
Definition at line 202 of file kb.h.
Referenced by getMacroNumber(), and Kb().
QString Kb::macroPath = '' [static], [private]
Definition at line 158 of file kb.h.
Referenced by getMacroPath(), Kb(), and ~Kb().
bool Kb::monochrome
Definition at line 19 of file kb.h.
Referenced by frameUpdate(), hwSave(), Kb(), and KbWidget::KbWidget().
int Kb::notifyNumber [private]
Definition at line 198 of file kb.h.
Referenced by frameUpdate(), fwUpdate(), Kb(), readNotify(), and ~Kb().
QString Kb::notifyPath [private]
Definition at line 154 of file kb.h.
Referenced by Kb(), and run().
QString Kb::pollrate
Definition at line 18 of file kb.h.
Referenced by KbWidget::devUpdate(), and Kb().
QString Kb::prefsPath [private]
Definition at line 181 of file kb.h.
Referenced by Kb(), load(), and save().
KbMode* Kb::prevMode [private]
Definition at line 190 of file kb.h.
Referenced by deletePrevious(), frameUpdate(), and hwSave().
KbProfile* Kb::prevProfile [private]
Definition at line 189 of file kb.h.
Referenced by frameUpdate().
QString Kb::usbModel
Definition at line 16 of file kb.h.
Referenced by FwUpgradeDialog::FwUpgradeDialog(), Kb(), KbWidget::name(), and MainWindow::showFwUpdateNotification().
QString Kb::usbSerial
Definition at line 16 of file kb.h.
Referenced by KbWidget::devUpdate(), Kb(), and matches().
Author
Generated automatically by Doxygen for ckb-next from the source code.