.TH "src/ckb/kbanimwidget.h" 3 "Sat May 27 2017" "Version v0.2.8 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbanimwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QListWidgetItem>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include 'animscript\&.h'\fP
.br
\fC#include 'kbanim\&.h'\fP
.br
\fC#include 'kblight\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBKbAnimWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
