KbBind
NAME
KbBind -
SYNOPSIS
#include <src/ckb/kbbind.h>
Inherits QObject.
Public Slots
void keyEvent (const QString &key, bool down)
KbBind::keyEvent.
Signals
void didLoad ()
void layoutChanged ()
void updated ()
Public Member Functions
KbBind (KbMode *modeParent, Kb *devParent, const KeyMap &keyMap)
KbBind (KbMode *modeParent, Kb *devParent, const KeyMap &keyMap, const KbBind &other)
KbBind.
void load (CkbSettings &settings)
void save (CkbSettings &settings)
bool needsSave () const
const KeyMap & map ()
void map (const KeyMap &map)
bool isISO () const
bool isKeyboard () const
bool isMouse () const
KbPerf * perf ()
KbLight * light ()
QString action (const QString &key)
QString friendlyName (const QString &key)
QString friendlyActionName (const QString &key)
void setAction (const QString &key, const QString &action)
void setAction (const QStringList &keys, const QString &action)
void resetAction (const QString &key)
void resetAction (const QStringList &keys)
void noAction (const QString &key)
void noAction (const QStringList &keys)
bool winLock ()
void winLock (bool newWinLock)
void update (QFile &cmd, bool force=false)
void setNeedsUpdate ()
int getMacroNumber ()
KbBind::getMacroNumber.
QString getMacroPath ()
KbBind::getMacroPath.
void handleNotificationChannel (bool start, QString cmdpath)
handleNotificationChannel sends commands to ckb-daemon for (de-) activating the notify channel. Send a notify cmd to the keyboard to set or clear notification for reading macro definition. The file handle for the cmd pipe is stored in lastCmd.
Static Public Member Functions
static QString globalRemap (const QString &key)
static void setGlobalRemap (const QHash< QString, QString > keyToActual)
static void loadGlobalRemap ()
static void saveGlobalRemap ()
static QString defaultAction (const QString &key)
Private Member Functions
Kb * devParent () const
KbMode * modeParent () const
KeyAction * bindAction (const QString &key)
Private Attributes
Kb * _devParent
quint64 lastGlobalRemapTime
QFile * lastCmd
lastCmd is a cache-hack. Because the QFile ist opened in Kb, and we need it in the macro processing functions, we cache the value her in lastCmd.
KeyMap _map
QHash< QString, KeyAction * > _bind
bool _winLock
bool _needsUpdate
bool _needsSave
Static Private Attributes
static QHash< QString, QString > _globalRemap
static quint64 globalRemapTime = 0
Friends
class KeyAction
Detailed Description
Definition at line 20 of file kbbind.h.
Constructor & Destructor Documentation
KbBind::KbBind (KbMode *modeParent, Kb *devParent, const KeyMap &keyMap) [explicit]
Definition at line 13 of file kbbind.cpp.
                                                                        :
    QObject(modeParent), _devParent(parentBoard), lastGlobalRemapTime(globalRemapTime), _map(keyMap),
    _winLock(false), _needsUpdate(true), _needsSave(true) {
}
KbBind::KbBind (KbMode *modeParent, Kb *parentBoard, const KeyMap &keyMap, const KbBind &other)
KbBind::KbBind // copy all existing Key bindings.
Parameters:
modeParent
devParent
keyMap
other This is the KbBind object to copy from Use this constructor to copy an existing Binding
modeParent
parentBoard
keyMap
other
Create a new Hash table and copy all entries
clear the destination list (there are the original KeyActions as references, so do not delete them)
and move the KeyActions we just created
Definition at line 25 of file kbbind.cpp.
References _bind, KeyAction, map(), and KeyAction::value().
                                                                                             :
    QObject(modeParent), _devParent(parentBoard), lastGlobalRemapTime(globalRemapTime), _bind(other._bind),
    _winLock(false), _needsUpdate(true), _needsSave(true) {
    map(keyMap);
    QHash<QString, KeyAction*> newBind;
    foreach(QString key, _bind.keys()) {
        KeyAction* act = _bind.value(key);
        if(act) {
            newBind[key] = new KeyAction(act->value(), this);
        }
    }
    _bind.clear();
    foreach(QString key, newBind.keys()) {
        KeyAction* act = newBind.value(key);
        if(act) {
            _bind[key] = new KeyAction(act->value(), this);
        }
    }
    newBind.clear(); // here we *must not* delete the KeyActions, because they are referenced by _bind now
}
Member Function Documentation
QString KbBind::action (const QString &key)
Definition at line 141 of file kbbind.cpp.
References bindAction(), globalRemap(), and KeyAction::value().
Referenced by friendlyActionName(), KbBindWidget::on_copyButton_clicked(), resetAction(), RebindWidget::setSelection(), and KbBindWidget::updateBind().
                                        {
    QString rKey = globalRemap(key);
    return bindAction(rKey)->value();
}
KeyAction* KbBind::bindAction (const QString &key) [inline], [private]
Definition at line 120 of file kbbind.h.
References _bind, KeyAction::defaultAction(), and KeyAction.
Referenced by action(), keyEvent(), and update().
{ if(!_bind.contains(key)) return _bind[key] = new KeyAction(KeyAction::defaultAction(key), this); return _bind[key]; }
QString KbBind::defaultAction (const QString &key) [static]
Definition at line 146 of file kbbind.cpp.
References KeyAction::defaultAction(), and globalRemap().
Referenced by KeyWidget::paintEvent(), and RebindWidget::setBind().
                                               {
    QString rKey = globalRemap(key);
    return KeyAction::defaultAction(rKey);
}
Kb* KbBind::devParent () const [inline], [private]
Definition at line 117 of file kbbind.h.
References _devParent.
Referenced by getMacroNumber(), getMacroPath(), and KeyAction::keyEvent().
{ return _devParent; }
void KbBind::didLoad () [signal]
Definition at line 155 of file moc_kbbind.cpp.
Referenced by load().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
QString KbBind::friendlyActionName (const QString &key)
Definition at line 158 of file kbbind.cpp.
References _map, action(), and KeyAction.
Referenced by KbBindWidget::updateSelDisplay().
                                                    {
    QString act = action(key);
    return KeyAction(act).friendlyName(_map);
}
QString KbBind::friendlyName (const QString &key)
Definition at line 151 of file kbbind.cpp.
References _map, Key::friendlyName(), and globalRemap().
                                              {
    const Key& pos = _map[globalRemap(key)];
    if(!pos)
        return "(Unknown)";
    return pos.friendlyName();
}
int KbBind::getMacroNumber ()
Returns:
number of notification channel. Use it in combination with notifyon/off-Statement This var holds the number of the notify-channel from the keyboard, because mouse clicks should not be recorded in macros.
number of notification channel. Use it in combination with notifyon/off-Statement
Definition at line 258 of file kbbind.cpp.
References devParent(), and Kb::getMacroNumber().
Referenced by handleNotificationChannel(), and RebindWidget::on_btnStartMacro_clicked().
                           {
    return devParent()->getMacroNumber();
}
QString KbBind::getMacroPath ()
Returns:
Filepath of macro notification pipe. If not set, returns initial value ''
Definition at line 266 of file kbbind.cpp.
References devParent(), and Kb::getMacroPath().
Referenced by RebindWidget::on_btnStartMacro_clicked(), and RebindWidget::on_btnStopMacro_clicked().
                             {
    return devParent()->getMacroPath();
}
QString KbBind::globalRemap (const QString &key) [static]
Definition at line 99 of file kbbind.cpp.
References _globalRemap.
Referenced by action(), defaultAction(), friendlyName(), keyEvent(), noAction(), KeyWidget::paintEvent(), resetAction(), setAction(), and SettingsWidget::SettingsWidget().
                                             {
    if(!_globalRemap.contains(key))
        return key;
    return _globalRemap.value(key);
}
void KbBind::handleNotificationChannel (boolstart, QStringcmdpath)
handleNotificationChannel sends commands to ckb-daemon for (de-) activating the notify channel.
Parameters:
start is boolean. If true, notification channel is opened for all keys, otherwise channel ist closed.
cmdpath holds the path for the notification pipe.
start If true, notification channel is opened for all keys, otherwise channel ist closed.
cmdpath QString sets the first part of the cmd pipe pathname (eg '/dev/input/ckb2') to locate the correct keyboard related cmd pipe.
Definition at line 276 of file kbbind.cpp.
References getMacroNumber().
Referenced by RebindWidget::on_btnStartMacro_clicked(), and RebindWidget::on_btnStopMacro_clicked().
                                                                  {
    if (getMacroNumber() > 0) {
        QFile cmd;
        cmdpath.append("/cmd");
        int fd = open(cmdpath.toLatin1().constData(), O_WRONLY | O_NONBLOCK);
        if(cmd.open(fd, QIODevice::WriteOnly, QFileDevice::AutoCloseHandle)) {
            qDebug() << "Writing to new Notification channel" << cmdpath << "with" << start;
            if (start) {
                cmd.write (QString("\nnotifyon %1\n@%1 notify all:on\n").arg(getMacroNumber()).toLatin1());
            } else {
                cmd.write(QString("\n@%1 notify all:off\nnotifyoff %1\n").arg(getMacroNumber()).toLatin1());
            }
            cmd.flush();
        } else {
            qDebug() << "error while opening" << cmdpath;
        }
        cmd.close();
    } else qDebug() << QString("No cmd or valid handle for notification found, macroNumber = %1, lastCmd = %2")
                       .arg(getMacroNumber()).arg(cmdpath);
}
bool KbBind::isISO () const [inline]
Definition at line 43 of file kbbind.h.
References _map, and KeyMap::isISO().
{ return _map.isISO(); }
bool KbBind::isKeyboard () const [inline]
Definition at line 44 of file kbbind.h.
References _map, and KeyMap::isKeyboard().
{ return _map.isKeyboard(); }
bool KbBind::isMouse () const [inline]
Definition at line 45 of file kbbind.h.
References _map, and KeyMap::isMouse().
Referenced by KbBindWidget::on_copyButton_clicked(), KbBindWidget::on_resetButton_clicked(), RebindWidget::setBind(), and KbBindWidget::updateSelDisplay().
{ return _map.isMouse(); }
void KbBind::keyEvent (const QString &key, booldown) [slot]
Parameters:
key
down
Definition at line 302 of file kbbind.cpp.
References bindAction(), globalRemap(), and KeyAction::keyEvent().
Referenced by Kb::readNotify().
                                                  {
    QString rKey = globalRemap(key);
    KeyAction* act = bindAction(rKey);
    if(act)
        act->keyEvent(this, down);
}
void KbBind::layoutChanged () [signal]
Definition at line 161 of file moc_kbbind.cpp.
Referenced by map().
{
    QMetaObject::activate(this, &staticMetaObject, 1, Q_NULLPTR);
}
KbLight * KbBind::light ()
Definition at line 55 of file kbbind.cpp.
References KbMode::light(), and modeParent().
Referenced by RebindWidget::applyChanges(), KeyAction::keyEvent(), and RebindWidget::setSelection().
                      {
    return modeParent()->light();
}
void KbBind::load (CkbSettings &settings)
Definition at line 59 of file kbbind.cpp.
References _bind, _map, _needsSave, _winLock, CkbSettings::childKeys(), didLoad(), KeyMap::fromName(), KeyMap::fromStorage(), KeyAction, map(), and CkbSettings::value().
Referenced by KbMode::KbMode().
                                      {
    _needsSave = false;
    SGroup group(settings, "Binding");
    KeyMap currentMap = _map;
    _map = KeyMap::fromName(settings.value("KeyMap").toString());
    // Load key settings
    bool useReal = settings.value("UseRealNames").toBool();
    _bind.clear();
    {
        SGroup group(settings, "Keys");
        foreach(QString key, settings.childKeys()){
            QString name = key.toLower();
            if(!useReal)
                name = _map.fromStorage(name);
            QString bind = settings.value(key).toString();
            _bind[name] = new KeyAction(bind, this);
        }
    }
    _winLock = settings.value("WinLock").toBool();
    emit didLoad();
    map(currentMap);
}
void KbBind::loadGlobalRemap () [static]
Definition at line 117 of file kbbind.cpp.
References _globalRemap, CkbSettings::childKeys(), globalRemapTime, and CkbSettings::value().
Referenced by SettingsWidget::SettingsWidget().
                            {
    _globalRemap.clear();
    CkbSettings settings("Program/GlobalRemap");
    foreach(const QString& key, settings.childKeys())
        _globalRemap[key] = settings.value(key).toString();
    globalRemapTime = QDateTime::currentMSecsSinceEpoch();
}
const KeyMap& KbBind::map () [inline]
Definition at line 41 of file kbbind.h.
References _map.
Referenced by KbBind(), KbMode::keyMap(), load(), map(), KbBindWidget::newLayout(), KbBindWidget::on_copyButton_clicked(), KbBindWidget::on_resetButton_clicked(), RebindWidget::setBind(), KbBindWidget::updateBind(), and KbBindWidget::updateSelDisplay().
{ return _map; }
void KbBind::map (const KeyMap &map)
Definition at line 134 of file kbbind.cpp.
References _map, _needsSave, _needsUpdate, layoutChanged(), and map().
                                 {
    _map = map;
    _needsUpdate = true;
    _needsSave = true;
    emit layoutChanged();
}
KbMode* KbBind::modeParent () const [inline], [private]
Definition at line 118 of file kbbind.h.
Referenced by light(), and perf().
{ return (KbMode*)parent(); }
bool KbBind::needsSave () const [inline]
Definition at line 38 of file kbbind.h.
References _needsSave.
Referenced by KbMode::needsSave().
{ return _needsSave; }
void KbBind::noAction (const QString &key)
Definition at line 173 of file kbbind.cpp.
References _bind, _map, globalRemap(), KeyMap::key(), KeyAction, and resetAction().
Referenced by RebindWidget::applyChanges(), and RebindWidget::on_unbindButton_clicked().
                                       {
    resetAction(key);
    QString rKey = globalRemap(key);
    if(!_map.key(rKey))
        return;
    _bind[rKey] = new KeyAction(this);
}
void KbBind::noAction (const QStringList &keys) [inline]
Definition at line 75 of file kbbind.h.
References noAction().
Referenced by noAction().
{ foreach(const QString& key, keys) noAction(key); }
KbPerf * KbBind::perf ()
Definition at line 51 of file kbbind.cpp.
References modeParent(), and KbMode::perf().
Referenced by KeyAction::keyEvent(), and RebindWidget::setBind().
                    {
    return modeParent()->perf();
}
void KbBind::resetAction (const QString &key)
Definition at line 163 of file kbbind.cpp.
References _bind, _needsSave, _needsUpdate, action(), and globalRemap().
Referenced by noAction(), KbBindWidget::on_resetButton_clicked(), RebindWidget::on_resetButton_clicked(), and setAction().
                                          {
    QString rKey = globalRemap(key);
    // Clean up existing action (if any)
    KeyAction* action = _bind.value(rKey);
    delete action;
    _bind.remove(rKey);
    _needsUpdate = true;
    _needsSave = true;
}
void KbBind::resetAction (const QStringList &keys) [inline]
Definition at line 72 of file kbbind.h.
References resetAction().
Referenced by resetAction().
{ foreach(const QString& key, keys) resetAction(key); }
void KbBind::save (CkbSettings &settings)
Definition at line 82 of file kbbind.cpp.
References _bind, _map, _needsSave, _winLock, KeyAction::defaultAction(), KeyMap::name(), CkbSettings::setValue(), and KeyAction::value().
Referenced by KbMode::save().
                                      {
    _needsSave = false;
    SGroup group(settings, "Binding");
    settings.setValue("KeyMap", _map.name());
    // Save key settings
    settings.setValue("UseRealNames", true);
    {
        SGroup group(settings, "Keys");
        foreach(QString key, _bind.keys()){
            KeyAction* act = _bind.value(key);
            if(act && act->value() != KeyAction::defaultAction(key))
                settings.setValue(key, act->value());
        }
    }
    settings.setValue("WinLock", _winLock);
}
void KbBind::saveGlobalRemap () [static]
Definition at line 125 of file kbbind.cpp.
References _globalRemap, and CkbSettings::setValue().
Referenced by SettingsWidget::updateModifiers().
                            {
    CkbSettings settings("Program/GlobalRemap", true);
    QHashIterator<QString, QString> i(_globalRemap);
    while(i.hasNext()){
        i.next();
        settings.setValue(i.key(), i.value());
    }
}
void KbBind::setAction (const QString &key, const QString &action)
Definition at line 181 of file kbbind.cpp.
References _bind, _map, globalRemap(), KeyMap::key(), KeyAction, and resetAction().
Referenced by RebindWidget::applyChanges(), and KbBindWidget::on_copyButton_clicked().
                                                               {
    resetAction(key);
    QString rKey = globalRemap(key);
    if(!_map.key(rKey))
        return;
    _bind[rKey] = new KeyAction(action, this);
}
void KbBind::setAction (const QStringList &keys, const QString &action) [inline]
Definition at line 69 of file kbbind.h.
References setAction().
Referenced by setAction().
{ foreach(const QString& key, keys) setAction(key, action); }
void KbBind::setGlobalRemap (const QHash< QString, QString >keyToActual) [static]
Definition at line 105 of file kbbind.cpp.
References _globalRemap, and globalRemapTime.
Referenced by SettingsWidget::updateModifiers().
                                                                    {
    _globalRemap.clear();
    // Ignore any keys with the standard binding
    QHashIterator<QString, QString> i(keyToActual);
    while(i.hasNext()){
        i.next();
        if(i.key() != i.value())
            _globalRemap[i.key()] = i.value();
    }
    globalRemapTime = QDateTime::currentMSecsSinceEpoch();
}
void KbBind::setNeedsUpdate () [inline]
Definition at line 84 of file kbbind.h.
References _needsUpdate.
Referenced by KbMode::setNeedsUpdate().
{ _needsUpdate = true; }
void KbBind::update (QFile &cmd, boolforce = false)
Definition at line 189 of file kbbind.cpp.
References _bind, _globalRemap, _needsUpdate, _winLock, bindAction(), KeyAction::driverName(), globalRemapTime, KeyAction::isValidMacro(), lastCmd, lastGlobalRemapTime, KeyAction::macroContent(), updated(), and KeyAction::value().
Referenced by Kb::frameUpdate().
                                         {
    if(!force && !_needsUpdate && lastGlobalRemapTime == globalRemapTime)
        return;
    lastGlobalRemapTime = globalRemapTime;
    emit updated();
    _needsUpdate = false;
    // Reset all keys and enable notifications for all
    cmd.write("rebind all notify all");
    // Make sure modifier keys are included as they may be remapped globally
    QHash<QString, KeyAction*> bind(_bind);
    if(!_bind.contains("caps")) bind["caps"] = 0;
    if(!_bind.contains("lshift")) bind["lshift"] = 0;
    if(!_bind.contains("rshift")) bind["rshift"] = 0;
    if(!_bind.contains("lctrl")) bind["lctrl"] = 0;
    if(!_bind.contains("rctrl")) bind["rctrl"] = 0;
    if(!_bind.contains("lwin")) bind["lwin"] = 0;
    if(!_bind.contains("rwin")) bind["rwin"] = 0;
    if(!_bind.contains("lalt")) bind["lalt"] = 0;
    if(!_bind.contains("ralt")) bind["ralt"] = 0;
    if(!_bind.contains("fn")) bind["fn"] = 0;
    QHashIterator<QString, KeyAction*> i(bind);
    // Initialize String buffer for macro Key definitions (G-keys)
    // "macro clear" is neccessary, if an older definition is unbound.
    QString macros = "\nmacro clear\n";
    // Write out rebound keys and collect infos for macro definitions
    while(i.hasNext()){
        i.next();
        QString key = i.key();
        KeyAction* act = i.value();
        if(_globalRemap.contains(key))
            act = bindAction(_globalRemap.value(key));
        if(!act)
            continue;
        QString value = act->driverName();
        if(value.isEmpty()){
            // If the key is unbound or is a special action, unbind it
            cmd.write(" unbind ");
            cmd.write(key.toLatin1());
            // if a macro definiton for the key is given,
            // add the converted string to key-buffer "macro"
            if (act->isValidMacro()) {
                if (act->macroContent().length() > 0) {
                    macros.append("macro " + key.toLatin1() + ":" + act->macroContent().toLatin1() + "\n");
                }
            }
        } else {
            // Otherwise, write the binding
            cmd.write(" bind ");
            cmd.write(key.toLatin1());
            cmd.write(":");
            cmd.write(value.toLatin1());
        }
    }
    // If win lock is enabled, unbind windows keys
    if(_winLock)
        cmd.write(" unbind lwin rwin");
    // At last, send Macro definitions if available.
    // If no definitions are made, clear macro will be sent only to reset all macros,
    cmd.write(macros.toLatin1());
    lastCmd = &cmd;
}
void KbBind::updated () [signal]
Definition at line 167 of file moc_kbbind.cpp.
Referenced by update().
{
    QMetaObject::activate(this, &staticMetaObject, 2, Q_NULLPTR);
}
bool KbBind::winLock () [inline]
Definition at line 78 of file kbbind.h.
References _winLock.
Referenced by KeyAction::keyEvent().
{ return _winLock; }
void KbBind::winLock (boolnewWinLock) [inline]
Definition at line 79 of file kbbind.h.
References _needsUpdate, and _winLock.
{ _winLock = newWinLock; _needsUpdate = true; }
Friends And Related Function Documentation
friend class KeyAction [friend]
Definition at line 139 of file kbbind.h.
Referenced by bindAction(), friendlyActionName(), KbBind(), load(), noAction(), and setAction().
Field Documentation
QHash<QString, KeyAction*> KbBind::_bind [private]
Definition at line 134 of file kbbind.h.
Referenced by bindAction(), KbBind(), load(), noAction(), resetAction(), save(), setAction(), and update().
Kb* KbBind::_devParent [private]
Definition at line 116 of file kbbind.h.
Referenced by devParent().
QHash< QString, QString > KbBind::_globalRemap [static], [private]
Definition at line 122 of file kbbind.h.
Referenced by globalRemap(), loadGlobalRemap(), saveGlobalRemap(), setGlobalRemap(), and update().
KeyMap KbBind::_map [private]
Definition at line 132 of file kbbind.h.
Referenced by friendlyActionName(), friendlyName(), isISO(), isKeyboard(), isMouse(), load(), map(), noAction(), save(), and setAction().
bool KbBind::_needsSave [private]
Definition at line 138 of file kbbind.h.
Referenced by load(), map(), needsSave(), resetAction(), and save().
bool KbBind::_needsUpdate [private]
Definition at line 137 of file kbbind.h.
Referenced by map(), resetAction(), setNeedsUpdate(), update(), and winLock().
bool KbBind::_winLock [private]
Definition at line 136 of file kbbind.h.
Referenced by load(), save(), update(), and winLock().
quint64 KbBind::globalRemapTime = 0 [static], [private]
Definition at line 123 of file kbbind.h.
Referenced by loadGlobalRemap(), setGlobalRemap(), and update().
QFile* KbBind::lastCmd [private]
Definition at line 130 of file kbbind.h.
Referenced by update().
quint64 KbBind::lastGlobalRemapTime [private]
Definition at line 124 of file kbbind.h.
Referenced by update().
Author
Generated automatically by Doxygen for ckb-next from the source code.