.TH "src/ckb/kbfirmware.cpp" 3 "Sun Jun 4 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/kbfirmware.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kbfirmware\&.h'\fP
.br
\fC#include 'kbmanager\&.h'\fP
.br
\fC#include 'quazip/quazip\&.h'\fP
.br
\fC#include 'quazip/quazipfile\&.h'\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const quint64 \fBAUTO_CHECK_TIME\fP = 60 * 60 * 1000"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const quint64 AUTO_CHECK_TIME = 60 * 60 * 1000\fC [static]\fP"

.PP
Definition at line 9 of file kbfirmware\&.cpp\&.
.PP
Referenced by KbFirmware::_checkUpdates()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
