KbFirmware
NAME
KbFirmware -
SYNOPSIS
#include <src/ckb/kbfirmware.h>
Inherits QObject.
Data Structures
struct FW
Signals
void downloaded ()
Static Public Member Functions
static bool checkUpdates ()
static bool hasDownloaded ()
static float versionForBoard (const short productID, bool waitForComplete=false)
static QByteArray dataForBoard (const short productID)
Private Types
enum { UNKNOWN = -1, NO, YES }
Private Slots
void processDownload (QNetworkReply *reply)
void downloadFinished ()
Private Member Functions
KbFirmware ()
~KbFirmware ()
void initManager ()
bool _checkUpdates ()
float _latestForBoard (const short productID, bool waitForComplete)
QByteArray _fileForBoard (const short productID)
Private Attributes
quint64 lastCheck
quint64 lastFinished
QMap< QString, FW > fwTable
QByteArray fwTableHash
QNetworkAccessManager * networkManager
QNetworkReply * tableDownload
enum KbFirmware:: { ... } hasGPG
Static Private Attributes
static KbFirmware instance
Detailed Description
Definition at line 10 of file kbfirmware.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator
UNKNOWN
NO
YES
Definition at line 53 of file kbfirmware.h.
{ UNKNOWN = -1, NO, YES } hasGPG :2;
Constructor & Destructor Documentation
KbFirmware::KbFirmware () [private]
Definition at line 14 of file kbfirmware.cpp.
                       :
    lastCheck(0), lastFinished(0), networkManager(0), tableDownload(0), hasGPG(UNKNOWN)
{
}
KbFirmware::~KbFirmware () [private]
Definition at line 19 of file kbfirmware.cpp.
                       {
    //delete networkManager;
    // ^ This can cause a crash (QT bug?)
}
Member Function Documentation
bool KbFirmware::_checkUpdates () [private]
Definition at line 30 of file kbfirmware.cpp.
References AUTO_CHECK_TIME, downloadFinished(), initManager(), lastCheck, networkManager, and tableDownload.
Referenced by checkUpdates().
                              {
    initManager();
    quint64 now = QDateTime::currentMSecsSinceEpoch();
    if(now < lastCheck + AUTO_CHECK_TIME)
        return false;
    // First location is for debugging only.
    tableDownload = networkManager->get(QNetworkRequest(QUrl("https://raw.githubusercontent.com/frickler24/ckb-next/new-firmware-file-format/FIRMWARE")));
    // This one is the production one.
    // tableDownload = networkManager->get(QNetworkRequest(QUrl("https://raw.githubusercontent.com/mattanger/ckb-next/master/FIRMWARE")));
    connect(tableDownload, SIGNAL(finished()), this, SLOT(downloadFinished()));
    lastCheck = now;
    return true;
}
QByteArray KbFirmware::_fileForBoard (const shortproductID) [private]
Definition at line 177 of file kbfirmware.cpp.
References QuaZip::csInsensitive, KbFirmware::FW::fileName, fwTable, KbFirmware::FW::hash, QuaZip::mdUnzip, networkManager, QuaZip::open(), QuaZipFile::open(), quit(), QuaZip::setCurrentFile(), and KbFirmware::FW::url.
Referenced by dataForBoard().
                                                         {
    FW info = fwTable.value(QString::number(productID));
    if(info.hash.isEmpty())
        return "";
    // Download zip from URL. Wait for it to finish.
    QNetworkReply* reply = networkManager->get(QNetworkRequest(QUrl(info.url)));
    QEventLoop loop(this);
    connect(reply, SIGNAL(finished()), &loop, SLOT(quit()));
    loop.exec();
    // Download finished, process data
    if(reply->error() != QNetworkReply::NoError)
        return "";
    QByteArray zipData = reply->readAll();
    QBuffer buffer(&zipData);
    // Open zip archive
    QuaZip zip(&buffer);
    if(!zip.open(QuaZip::mdUnzip))
        return "";
    // Find the desired file
    if(!zip.setCurrentFile(info.fileName, QuaZip::csInsensitive))
        return "";
    QuaZipFile binFile(&zip);
    if(!binFile.open(QIODevice::ReadOnly))
        return "";
    QByteArray binary = binFile.readAll();
    // Check the hash
    if(QCryptographicHash::hash(binary, QCryptographicHash::Sha256) != info.hash)
        return "";
    return binary;
}
float KbFirmware::_latestForBoard (const shortproductID, boolwaitForComplete) [private]
< Only give an error message if we loaded the FIRMWARE file.
Definition at line 157 of file kbfirmware.cpp.
References checkUpdates(), KbManager::ckbDaemonVersionF(), KbManager::ckbGuiVersionF(), KbFirmware::FW::ckbVersion, downloaded(), fwTable, KbFirmware::FW::fwVersion, KbFirmware::FW::hash, quit(), and tableDownload.
Referenced by versionForBoard().
                                                                             {
    if((tableDownload || checkUpdates()) && waitForComplete){
        // If waiting is desired, enter an event loop and stay here until the download is finished
        QEventLoop loop(this);
        connect(this, SIGNAL(downloaded()), &loop, SLOT(quit()));
        loop.exec();
    }
    // Find this board
    FW info = fwTable.value(QString::number(productID));
    if (info.hash.isEmpty()) {
        if (fwTable.count() > 0)
            qDebug() << "Can't find valid firmware version for device" << productID << QString::number(productID);
        return 0.f;
    }
    // Don't return the new version if the current ckb doesn't support it
    if(info.ckbVersion > KbManager::ckbGuiVersionF() || info.ckbVersion > KbManager::ckbDaemonVersionF())
        return -1.f;
    return info.fwVersion;
}
static bool KbFirmware::checkUpdates () [inline], [static]
Definition at line 15 of file kbfirmware.h.
References _checkUpdates(), and instance.
Referenced by _latestForBoard(), and MainWindow::timerTick().
{ return instance._checkUpdates(); }
static QByteArray KbFirmware::dataForBoard (const shortproductID) [inline], [static]
Definition at line 25 of file kbfirmware.h.
References _fileForBoard(), and instance.
Referenced by FwUpgradeDialog::exec().
{ return instance._fileForBoard(productID); }
void KbFirmware::downloaded () [signal]
Definition at line 148 of file moc_kbfirmware.cpp.
Referenced by _latestForBoard(), and downloadFinished().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
void KbFirmware::downloadFinished () [private], [slot]
Definition at line 148 of file kbfirmware.cpp.
References downloaded(), processDownload(), and tableDownload.
Referenced by _checkUpdates().
                                 {
    if(!tableDownload)
        return;
    processDownload(tableDownload);
    tableDownload->deleteLater();
    tableDownload = 0;
    emit downloaded();
}
static bool KbFirmware::hasDownloaded () [inline], [static]
Definition at line 18 of file kbfirmware.h.
References instance, and lastFinished.
Referenced by KbWidget::on_fwUpdButton_clicked(), and KbWidget::updateFwButton().
{ return instance.lastFinished != 0; }
void KbFirmware::initManager () [private]
Definition at line 24 of file kbfirmware.cpp.
References networkManager.
Referenced by _checkUpdates().
                            {
    if(networkManager)
        return;
    networkManager = new QNetworkAccessManager();
}
void KbFirmware::processDownload (QNetworkReply *reply) [private], [slot]
Definition at line 44 of file kbfirmware.cpp.
References KbFirmware::FW::ckbVersion, KbFirmware::FW::fileName, fwTable, fwTableHash, KbFirmware::FW::fwVersion, hasGPG, KbFirmware::FW::hash, lastCheck, lastFinished, NO, KbManager::parseVersionString(), KbFirmware::FW::productID, UNKNOWN, KbFirmware::FW::url, and YES.
Referenced by downloadFinished().
                                                    {
    if(reply->error() != QNetworkReply::NoError)
        return;
    // Update last check
    lastCheck = lastFinished = QDateTime::currentMSecsSinceEpoch();
    QByteArray data = reply->readAll();
    // Don't do anything if this is the same as the last version downloaded
    QByteArray hash = QCryptographicHash::hash(data, QCryptographicHash::Sha256);
    if(hash == fwTableHash)
        return;
    fwTableHash = hash;
    if(hasGPG == UNKNOWN){
        // Check for a GPG installation
        QProcess gpg;
        gpg.start("gpg", QStringList("--version"));
        gpg.waitForFinished();
        if(gpg.error() == QProcess::FailedToStart)
            // No GPG install
            hasGPG = NO;
        else {
            QString output = QString::fromUtf8(gpg.readAll());
            // Must support RSA keys and SHA256
            if(output.contains("RSA", Qt::CaseInsensitive) && output.contains("SHA256", Qt::CaseInsensitive))
                hasGPG = YES;
            else
                hasGPG = NO;
        }
        if(!hasGPG)
            qDebug() << "No GPG detected, signature verification disabled";
    }
    if(hasGPG){
        // If GPG is available, check the signature on the file before proceeding.
        QDir tmp = QDir::temp();
        // Save file to a temporary path. Include PID to avoid conflicts
        qint64 pid = QCoreApplication::applicationPid();
        QString fwPath = tmp.absoluteFilePath(QString("ckb-%1-firmware").arg(pid));
        QFile firmware(fwPath);
        if(!firmware.open(QIODevice::WriteOnly)
                || firmware.write(data) != data.length()){
            qDebug() << "Failed to write firmware file to temporary location, aborting firmware check";
            return;
        }
        firmware.close();
        // Write GPG key
        QString keyPath = tmp.absoluteFilePath(QString("ckb-%1-key.gpg").arg(pid));
        if(!QFile::copy(":/bin/ckb-next-key.gpg", keyPath)){
            firmware.remove();
            qDebug() << "Failed to write GPG key to temporary location, aborting firmware check";
            return;
        }
        // Check signature
        QProcess gpg;
        gpg.start("gpg", QStringList("--no-default-keyring") << "--keyring" << keyPath << "--verify" << fwPath);
        gpg.waitForFinished();
        // Clean up temp files
        tmp.remove(fwPath);
        tmp.remove(keyPath);
        if(gpg.error() != QProcess::UnknownError || gpg.exitCode() != 0){
            qDebug() << "GPG couldn't verify firmware signature:";
            qDebug() << gpg.readAllStandardOutput();
            qDebug() << gpg.readAllStandardError();
            return;
        }
        // Signature good, proceed to update database
    }
    fwTable.clear();
    QStringList lines = QString::fromUtf8(data).split("\n");
    bool scan = false;
    foreach(QString line, lines){
        // Collapse whitespace
        line.replace(QRegExp("\s+"), " ").remove(QRegExp("^\s")).remove(QRegExp("\s$"));
        // Skip empty or commented-out lines
        if(line.length() == 0 || line.at(0) == '#')
            continue;
        // Don't read anything until the entries begin and don't read anything after they end
        if(!scan){
            if(line == "!BEGIN FW ENTRIES")
                scan = true;
            else
                continue;
        }
        if(line == "!END FW ENTRIES")
            break;
        QStringList components = line.split(" ");
        if(components.length() != 8)
            continue;
        // "VENDOR-PRODUCT"
        QString device = components[0].toUpper() + "-" + components[1].toUpper();
        bool ok;
        FW fw;
        fw.fwVersion = components[2].toFloat(); // Firmware blob version
        fw.url = QUrl::fromPercentEncoding(components[3].toLatin1()); // URL to zip file
        fw.ckbVersion = KbManager::parseVersionString(components[4]); // Minimum ckb version
        fw.fileName = QUrl::fromPercentEncoding(components[5].toLatin1()); // Name of file inside zip
        fw.hash = QByteArray::fromHex(components[6].toLatin1()); // SHA256 of file inside zip
        fw.productID = components[7].toShort(&ok, 16); // Hex productID assigned to this FW
        // Update entry
        fwTable[QString::number(fw.productID)] = fw;
        // qDebug() << "saving fwTabel entry[" << QString::number(fw.productID) << "] for device" << device
        // << fw.fwVersion << fw.fileName << fw.url << "for ckb-next version >=" << fw.ckbVersion;
    }
    qDebug() << "Downloaded new firmware list." << fwTable.count() << "entries found.";
}
static float KbFirmware::versionForBoard (const shortproductID, boolwaitForComplete = false) [inline], [static]
Definition at line 22 of file kbfirmware.h.
References _latestForBoard(), and instance.
Referenced by MainWindow::checkFwUpdates(), KbWidget::on_fwUpdButton_clicked(), and KbWidget::updateFwButton().
{ return instance._latestForBoard(productID, waitForComplete); }
Field Documentation
QMap<QString, FW> KbFirmware::fwTable [private]
Definition at line 41 of file kbfirmware.h.
Referenced by _fileForBoard(), _latestForBoard(), and processDownload().
QByteArray KbFirmware::fwTableHash [private]
Definition at line 43 of file kbfirmware.h.
Referenced by processDownload().
enum { ... } KbFirmware::hasGPG [private]
Referenced by processDownload().
KbFirmware KbFirmware::instance [static], [private]
Definition at line 59 of file kbfirmware.h.
Referenced by checkUpdates(), dataForBoard(), hasDownloaded(), and versionForBoard().
quint64 KbFirmware::lastCheck [private]
Definition at line 32 of file kbfirmware.h.
Referenced by _checkUpdates(), and processDownload().
quint64 KbFirmware::lastFinished [private]
Definition at line 32 of file kbfirmware.h.
Referenced by hasDownloaded(), and processDownload().
QNetworkAccessManager* KbFirmware::networkManager [private]
Definition at line 47 of file kbfirmware.h.
Referenced by _checkUpdates(), _fileForBoard(), and initManager().
QNetworkReply* KbFirmware::tableDownload [private]
Definition at line 50 of file kbfirmware.h.
Referenced by _checkUpdates(), _latestForBoard(), and downloadFinished().
Author
Generated automatically by Doxygen for ckb-next from the source code.