KbLightWidget
NAME
KbLightWidget -
SYNOPSIS
#include <src/ckb/kblightwidget.h>
Inherits QWidget.
Public Member Functions
KbLightWidget (QWidget *parent=0)
~KbLightWidget ()
void setLight (KbLight *newLight)
void setMonochrome ()
Private Slots
void updateLight ()
void newSelection (QStringList selection)
void changeColor (QColor newColor)
void changeAnim (KbAnim *newAnim)
void changeAnimKeys (QStringList keys)
void on_brightnessBox_activated (int index)
void on_animButton_clicked ()
void on_bgButton_clicked ()
void on_showAnimBox_clicked (bool checked)
void toggleSidelight ()
Private Attributes
KbLight * light
QStringList currentSelection
Ui::KbLightWidget * ui
Detailed Description
Definition at line 15 of file kblightwidget.h.
Constructor & Destructor Documentation
KbLightWidget::KbLightWidget (QWidget *parent = 0) [explicit]
Definition at line 6 of file kblightwidget.cpp.
References Ui_KbLightWidget::animButton, Ui_KbLightWidget::animWidget, Ui_KbLightWidget::bgButton, changeAnim(), changeAnimKeys(), changeColor(), AnimScript::count(), CkbSettings::get(), Ui_KbLightWidget::keyWidget, newSelection(), Ui_KbLightWidget::setupUi(), Ui_KbLightWidget::showAnimBox, toggleSidelight(), and ui.
                                            :
    QWidget(parent), light(0),
    ui(new Ui::KbLightWidget)
{
    ui->setupUi(this);
    if(AnimScript::count() == 0)
        ui->animButton->setVisible(false);
    connect(ui->bgButton, SIGNAL(colorChanged(QColor)), this, SLOT(changeColor(QColor)));
    connect(ui->keyWidget, SIGNAL(selectionChanged(QStringList)), this, SLOT(newSelection(QStringList)));
    connect(ui->keyWidget, SIGNAL(sidelightToggled()), this, SLOT(toggleSidelight())); // click on a toggle button, like sidelight
    connect(ui->animWidget, SIGNAL(animChanged(KbAnim*)), this, SLOT(changeAnim(KbAnim*)));
    connect(ui->animWidget, SIGNAL(didUpdateSelection(QStringList)), this, SLOT(changeAnimKeys(QStringList)));
    // Restore "show animated" setting
    ui->showAnimBox->setChecked(!CkbSettings::get("UI/Light/ShowBaseOnly").toBool());
}
KbLightWidget::~KbLightWidget ()
Definition at line 24 of file kblightwidget.cpp.
References ui.
                             {
    delete ui;
}
Member Function Documentation
void KbLightWidget::changeAnim (KbAnim *newAnim) [private], [slot]
Definition at line 121 of file kblightwidget.cpp.
References KeyWidget::clearSelection(), KbAnim::keys(), Ui_KbLightWidget::keyWidget, KeyWidget::setAnimationToSelection(), KeyWidget::setSelection(), and ui.
Referenced by KbLightWidget().
                                             {
    if(newAnim)
        ui->keyWidget->setSelection(newAnim->keys());
    else
        ui->keyWidget->clearSelection();
    ui->keyWidget->setAnimationToSelection();
}
void KbLightWidget::changeAnimKeys (QStringListkeys) [private], [slot]
Definition at line 129 of file kblightwidget.cpp.
References Ui_KbLightWidget::keyWidget, KeyWidget::setAnimation(), and ui.
Referenced by KbLightWidget().
                                                  {
    ui->keyWidget->setAnimation(keys);
}
void KbLightWidget::changeColor (QColornewColor) [private], [slot]
Definition at line 99 of file kblightwidget.cpp.
References KbLight::color(), KeyWidget::colorMap(), KbLight::colorMap(), currentSelection, Ui_KbLightWidget::keyWidget, light, and ui.
Referenced by KbLightWidget().
                                              {
    if(light){
        foreach(QString key, currentSelection)
            light->color(key, newColor);
        ui->keyWidget->colorMap(light->colorMap());
    }
}
void KbLightWidget::newSelection (QStringListselection) [private], [slot]
Definition at line 72 of file kblightwidget.cpp.
References Ui_KbLightWidget::animWidget, Ui_KbLightWidget::bgButton, ColorButton::color(), KbLight::colorMap(), currentSelection, KeyMap::isMouse(), light, KbLight::map(), Ui_KbLightWidget::selLabel, KbAnimWidget::setSelectedKeys(), and ui.
Referenced by KbLightWidget().
                                                     {
    // Determine selected color (invalid color if no selection or if they're not all the same)
    QColor selectedColor;
    const QColorMap& colorMap = light->colorMap();
    foreach(const QString& key, selection){
        QColor color = colorMap.value(key);
        if(!selectedColor.isValid())
            selectedColor = color;
        else if(color != selectedColor){
            selectedColor = QColor();
            break;
        }
    }
    currentSelection = selection;
    ui->animWidget->setSelectedKeys(selection);
    ui->bgButton->color(selectedColor);
    int count = selection.count();
    if(count == 0){
        ui->selLabel->setText("Click to select");
        return;
    } else if(count == 1)
        ui->selLabel->setText(tr("1 %1 selected").arg(light->map().isMouse() ? "zone" : "key"));
    else
        ui->selLabel->setText(tr("%1 %2 selected").arg(count).arg(light->map().isMouse() ? "zones" : "keys"));
}
void KbLightWidget::on_animButton_clicked () [private], [slot]
Definition at line 143 of file kblightwidget.cpp.
References KbAnimWidget::addAnim(), Ui_KbLightWidget::animWidget, AnimAddDialog::chosenPreset(), AnimAddDialog::chosenScript(), AnimScript::count(), currentSelection, Ui_KbLightWidget::keyWidget, light, AnimScript::preset(), AnimScript::presets(), KbLight::restartAnimation(), KeyWidget::selectAll(), and ui.
                                         {
    if(AnimScript::count() == 0)
        return;
    if(currentSelection.isEmpty())
        ui->keyWidget->selectAll();
    AnimAddDialog dialog(this, light, currentSelection);
    dialog.exec();
    if(dialog.result() != QDialog::Accepted)
        return;
    const AnimScript* script = dialog.chosenScript();
    int presetId = dialog.chosenPreset();
    ui->animWidget->addAnim(script, currentSelection, script->presets()[presetId], script->preset(presetId));
    light->restartAnimation();
}
void KbLightWidget::on_bgButton_clicked () [private], [slot]
Definition at line 138 of file kblightwidget.cpp.
References currentSelection, Ui_KbLightWidget::keyWidget, KeyWidget::selectAll(), and ui.
                                       {
    if(currentSelection.isEmpty())
        ui->keyWidget->selectAll();
}
void KbLightWidget::on_brightnessBox_activated (intindex) [private], [slot]
Definition at line 133 of file kblightwidget.cpp.
References KbLight::dimming(), and light.
                                                       {
    if(light)
        light->dimming(index);
}
void KbLightWidget::on_showAnimBox_clicked (boolchecked) [private], [slot]
Definition at line 52 of file kblightwidget.cpp.
References KeyWidget::displayColorMap(), Ui_KbLightWidget::keyWidget, light, CkbSettings::set(), and ui.
Referenced by setLight().
                                                      {
    // FIXME: set globally if there's more than one KbLightWidget active
    // Connect/disconnect animation slot
    if(checked){
        if(light)
            connect(light, SIGNAL(frameDisplayed(const ColorMap&,const QSet<QString>&)), ui->keyWidget, SLOT(displayColorMap(const ColorMap&,const QSet<QString>&)));
    } else {
        if(light)
            disconnect(light, SIGNAL(frameDisplayed(const ColorMap&,const QSet<QString>&)), ui->keyWidget, SLOT(displayColorMap(const ColorMap&,const QSet<QString>&)));
        ui->keyWidget->displayColorMap(ColorMap());
    }
    CkbSettings::set("UI/Light/ShowBaseOnly", !checked);
}
void KbLightWidget::setLight (KbLight *newLight)
Definition at line 28 of file kblightwidget.cpp.
References Ui_KbLightWidget::animWidget, KeyWidget::clearAnimation(), KbAnimWidget::clearSelection(), KeyWidget::clearSelection(), Ui_KbLightWidget::keyWidget, light, on_showAnimBox_clicked(), KeyWidget::setAnimation(), KbAnimWidget::setLight(), Ui_KbLightWidget::showAnimBox, ui, and updateLight().
Referenced by KbWidget::modeChanged().
                                             {
    ui->keyWidget->clearSelection();
    ui->keyWidget->clearAnimation();
    ui->animWidget->clearSelection();
    if(light == newLight)
        return;
    if(light){
        disconnect(light, SIGNAL(updated()), this, SLOT(updateLight()));
        // Disabled animated colors for previous light
        on_showAnimBox_clicked(false);
    }
    connect(newLight, SIGNAL(updated()), this, SLOT(updateLight()));
    light = newLight;
    updateLight();
    ui->keyWidget->setAnimation(QStringList());
    ui->animWidget->setLight(newLight);
    if(ui->showAnimBox->isChecked())
        on_showAnimBox_clicked(true);
}
void KbLightWidget::setMonochrome ()
Definition at line 48 of file kblightwidget.cpp.
References Ui_KbLightWidget::keyWidget, KeyWidget::monochrome(), and ui.
Referenced by KbWidget::KbWidget().
                                 {
    ui->keyWidget->monochrome(true);
}
void KbLightWidget::toggleSidelight () [private], [slot]
Definition at line 107 of file kblightwidget.cpp.
References KbLight::color(), KeyWidget::colorMap(), KbLight::colorMap(), Ui_KbLightWidget::keyWidget, light, and ui.
Referenced by KbLightWidget().
                                   {
    if(light){
        if (light->colorMap()["lsidel"] == 0xFF000000){
                light->color("lsidel",QRgb(0xFFFFFFFF));
                light->color("rsidel",QRgb(0xFFFFFFFF));
        } else {
                light->color("lsidel", QRgb(0xFF000000));
                light->color("rsidel", QRgb(0xFF000000));
        }
        ui->keyWidget->colorMap(light->colorMap());
    }
}
void KbLightWidget::updateLight () [private], [slot]
Definition at line 66 of file kblightwidget.cpp.
References Ui_KbLightWidget::brightnessBox, KeyWidget::colorMap(), KbLight::colorMap(), KbLight::dimming(), Ui_KbLightWidget::keyWidget, light, KeyWidget::map(), KbLight::map(), and ui.
Referenced by setLight().
                               {
    ui->keyWidget->map(light->map());
    ui->keyWidget->colorMap(light->colorMap());
    ui->brightnessBox->setCurrentIndex(light->dimming());
}
Field Documentation
QStringList KbLightWidget::currentSelection [private]
Definition at line 44 of file kblightwidget.h.
Referenced by changeColor(), newSelection(), on_animButton_clicked(), and on_bgButton_clicked().
KbLight* KbLightWidget::light [private]
Definition at line 43 of file kblightwidget.h.
Referenced by changeColor(), newSelection(), on_animButton_clicked(), on_brightnessBox_activated(), on_showAnimBox_clicked(), setLight(), toggleSidelight(), and updateLight().
Ui::KbLightWidget* KbLightWidget::ui [private]
Definition at line 46 of file kblightwidget.h.
Referenced by changeAnim(), changeAnimKeys(), changeColor(), KbLightWidget(), newSelection(), on_animButton_clicked(), on_bgButton_clicked(), on_showAnimBox_clicked(), setLight(), setMonochrome(), toggleSidelight(), updateLight(), and ~KbLightWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.