KbPerf
NAME
KbPerf -
SYNOPSIS
#include <src/ckb/kbperf.h>
Inherits QObject.
Public Types
enum height { LOW = 1, LOWMED, MEDIUM, MEDHIGH, HIGH }
enum indicator { NUM, CAPS, SCROLL, HW_IMAX = SCROLL, MODE, MACRO, LIGHT, LOCK, MUTE }
enum i_hw { NONE = -1, NORMAL, ON, OFF }
Signals
void didLoad ()
void settingsUpdated ()
Public Member Functions
KbPerf (KbMode *parent)
KbPerf (KbMode *parent, const KbPerf &other)
const KbPerf & operator= (const KbPerf &rhs)
void load (CkbSettings &settings)
void save (CkbSettings &settings)
bool needsSave () const
height liftHeight () const
void liftHeight (height newHeight)
bool angleSnap () const
void angleSnap (bool newAngleSnap)
QPoint dpi (int index) const
void dpi (int index, const QPoint &newValue)
QPoint sniperDpi () const
void sniperDpi (const QPoint &newValue)
void dpi (int index, int newValue)
void sniperDpi (int newValue)
QPoint curDpi () const
void curDpi (const QPoint &newDpi)
void curDpi (int newDpi)
int curDpiIdx () const
void curDpiIdx (int newIdx)
void dpiUp ()
void dpiDown ()
bool dpiEnabled (int index) const
void dpiEnabled (int index, bool newEnabled)
quint64 pushDpi (const QPoint &newDpi)
quint64 pushDpi (int newDpi)
quint64 pushSniper ()
void popDpi (quint64 pushIdx)
float iOpacity () const
void iOpacity (float newIOpacity)
bool dpiIndicator () const
void dpiIndicator (bool newDpiIndicator)
QColor dpiColor (int index) const
void dpiColor (int index, const QColor &newColor)
void getIndicator (indicator index, QColor &color1, QColor &color2, QColor &color3, bool &software_enable, i_hw &hardware_enable)
void setIndicator (indicator index, const QColor &color1, const QColor &color2, const QColor &color3=QColor(), bool software_enable=true, i_hw hardware_enable=NORMAL)
void update (QFile &cmd, int notifyNumber, bool force=false, bool saveCustomDpi=true)
void setNeedsUpdate ()
void applyIndicators (int modeIndex, const bool indicatorState[HW_I_COUNT])
Static Public Attributes
static const int DPI_COUNT = 6
static const int SNIPER = 0
static const int DPI_MIN = 100
static const int DPI_MAX = 12000
static const int OTHER = DPI_COUNT
static const int I_COUNT = (int)MUTE + 1
static const int HW_I_COUNT = (int)HW_IMAX + 1
Private Member Functions
KbMode * modeParent () const
KbBind * bind () const
KbLight * light () const
void lightIndicator (const char *name, QRgb rgba)
void _curDpi (const QPoint &newDpi)
Private Attributes
int dpiX [DPI_COUNT]
int dpiY [DPI_COUNT]
int dpiCurX
int dpiCurY
int dpiCurIdx
QColor dpiClr [DPI_COUNT+1]
bool dpiOn [DPI_COUNT]
int dpiLastIdx
QMap< quint64, QPoint > pushedDpis
uint runningPushIdx
float _iOpacity
QColor iColor [I_COUNT][2]
QColor light100Color
QColor muteNAColor
bool iEnable [I_COUNT]
i_hw hwIType [HW_I_COUNT]
bool _dpiIndicator
height _liftHeight
bool _angleSnap
bool _needsUpdate
bool _needsSave
Detailed Description
Definition at line 15 of file kbperf.h.
Member Enumeration Documentation
enum KbPerf::height
Enumerator
LOW
LOWMED
MEDIUM
MEDHIGH
HIGH
Definition at line 31 of file kbperf.h.
                {
        LOW = 1,
        LOWMED,
        MEDIUM,
        MEDHIGH,
        HIGH
    };
enum KbPerf::i_hw
Enumerator
NONE
NORMAL
ON
OFF
Definition at line 98 of file kbperf.h.
              {
        NONE = -1, // For non-hardware indicators
        NORMAL,
        ON,
        OFF
    };
enum KbPerf::indicator
Enumerator
NUM
CAPS
SCROLL
HW_IMAX
MODE
MACRO
LIGHT
LOCK
MUTE
Definition at line 85 of file kbperf.h.
                   {
        // Hardware
        NUM,
        CAPS,
        SCROLL, HW_IMAX = SCROLL,
        // Software
        MODE,
        MACRO,
        LIGHT,
        LOCK,
        MUTE
    };
Constructor & Destructor Documentation
KbPerf::KbPerf (KbMode *parent) [explicit]
Definition at line 13 of file kbperf.cpp.
References CAPS, DPI_COUNT, dpiClr, dpiCurIdx, dpiCurX, dpiCurY, dpiLastIdx, dpiOn, dpiX, dpiY, HW_I_COUNT, hwIType, I_COUNT, iColor, iEnable, LIGHT, light100Color, LOCK, MACRO, MODE, MUTE, muteNAColor, NORMAL, NUM, and SCROLL.
                             :
    QObject(parent), runningPushIdx(1),
    _iOpacity(1.f), _dpiIndicator(true), _liftHeight(MEDIUM), _angleSnap(false),
    _needsUpdate(true), _needsSave(true) {
    // Default DPI settings
    dpiX[0] = dpiY[0] = 400;
    dpiX[1] = dpiY[1] = 450;
    dpiX[2] = dpiY[2] = 800;
    dpiX[3] = dpiY[3] = 1500;
    dpiX[4] = dpiY[4] = 3000;
    dpiX[5] = dpiY[5] = 6000;
    dpiClr[0] = QColor(255, 0, 0);
    dpiClr[1] = QColor(255, 192, 0);
    dpiClr[2] = QColor(255, 255, 0);
    dpiClr[3] = QColor(0, 255, 0);
    dpiClr[4] = QColor(0, 255, 255);
    dpiClr[5] = QColor(255, 255, 255);
    dpiClr[6] = QColor(192, 192, 192);
    for(int i = 0; i < DPI_COUNT; i++)
        dpiOn[i] = true;
    dpiLastIdx = dpiCurIdx = 3;
    dpiCurX = dpiX[dpiCurIdx];
    dpiCurY = dpiY[dpiCurIdx];
    // Default indicators
    iColor[NUM][0] = iColor[CAPS][0] = iColor[SCROLL][0] = QColor(0, 255, 0); // Lock lights: on = green, off = black
    iColor[NUM][1] = iColor[CAPS][1] = iColor[SCROLL][1] = QColor(0, 0, 0);
    iColor[MACRO][0] = QColor(255, 0, 0); // Macro: on = red, off = black
    iColor[LOCK][0] = QColor(255, 255, 255); // Win lock: on = white, off = black
    iColor[MODE][0] = iColor[MUTE][0] = QColor(255, 255, 255, 0); // Mode, mute: on = transparent, off = black
    iColor[MODE][1] = iColor[MACRO][1] = iColor[LOCK][1] = iColor[MUTE][1] = muteNAColor = QColor(0, 0, 0);
    iColor[LIGHT][0] = QColor(255, 0, 0); // Brightness: red, yellow, white
    iColor[LIGHT][1] = QColor(255, 255, 0);
    light100Color = QColor(255, 255, 255);
    for(int i = 0; i < HW_I_COUNT; i++){
        // Set all lock lights to HW mode
        iEnable[i] = false;
        hwIType[i] = NORMAL;
    }
    for(int i = HW_I_COUNT; i < I_COUNT; i++){
        // Turn all other indicators on
        iEnable[i] = true;
    }
}
KbPerf::KbPerf (KbMode *parent, const KbPerf &other)
Definition at line 57 of file kbperf.cpp.
References curDpi(), DPI_COUNT, dpiClr, dpiOn, dpiX, dpiY, hwIType, I_COUNT, iColor, iEnable, and pushedDpis.
                                                  :
    QObject(parent), dpiCurX(other.dpiCurX), dpiCurY(other.dpiCurY), dpiCurIdx(other.dpiCurIdx), dpiLastIdx(other.dpiLastIdx), runningPushIdx(1),
    _iOpacity(other._iOpacity), light100Color(other.light100Color), muteNAColor(other.muteNAColor), _dpiIndicator(other._dpiIndicator),
    _liftHeight(other._liftHeight), _angleSnap(other._angleSnap),
    _needsUpdate(true), _needsSave(true) {
    memcpy(dpiX, other.dpiX, sizeof(dpiX));
    memcpy(dpiY, other.dpiY, sizeof(dpiY));
    for(int i = 0; i < DPI_COUNT + 1; i++)
        dpiClr[i] = other.dpiClr[i];
    memcpy(dpiOn, other.dpiOn, sizeof(dpiOn));
    for(int i = 0; i < I_COUNT; i++){
        iColor[i][0] = other.iColor[i][0];
        iColor[i][1] = other.iColor[i][1];
    }
    memcpy(iEnable, other.iEnable, sizeof(iEnable));
    memcpy(hwIType, other.hwIType, sizeof(hwIType));
    // Don't copy pushed DPI states. If the other mode has any, restore the original DPI
    if(!other.pushedDpis.isEmpty())
        curDpi(other.pushedDpis[0]);
}
Member Function Documentation
void KbPerf::_curDpi (const QPoint &newDpi) [private]
Definition at line 262 of file kbperf.cpp.
References _needsSave, _needsUpdate, DPI_COUNT, dpiCurIdx, dpiCurX, dpiCurY, dpiLastIdx, dpiX, and dpiY.
Referenced by curDpi(), popDpi(), and pushDpi().
                                        {
    dpiCurX = newDpi.x();
    dpiCurY = newDpi.y();
    // Set current/last index
    dpiCurIdx = -1;
    for(int i = 0; i < DPI_COUNT; i++){
        if(dpiCurX == dpiX[i] && dpiCurY == dpiY[i]){
            dpiCurIdx = i;
            if(i != 0)
                dpiLastIdx = i;
            break;
        }
    }
    _needsUpdate = _needsSave = true;
}
bool KbPerf::angleSnap () const [inline]
Definition at line 42 of file kbperf.h.
References _angleSnap.
Referenced by MPerfWidget::on_aSnapBox_clicked(), Kb::readNotify(), and MPerfWidget::setPerf().
{ return _angleSnap; }
void KbPerf::angleSnap (boolnewAngleSnap)
Definition at line 368 of file kbperf.cpp.
References _angleSnap, _needsSave, and _needsUpdate.
                                       {
    _angleSnap = newAngleSnap;
    _needsUpdate = _needsSave = true;
}
void KbPerf::applyIndicators (intmodeIndex, const boolindicatorState[HW_I_COUNT])
Definition at line 432 of file kbperf.cpp.
References _dpiIndicator, _iOpacity, bind(), CAPS, curDpiIdx(), dpiClr, getMuteState(), Kb::HWMODE_MAX, iColor, iEnable, LIGHT, light(), light100Color, lightIndicator(), LOCK, MACRO, MODE, MUTE, MUTED, muteNAColor, NUM, OTHER, KbLight::resetIndicators(), SCROLL, and UNMUTED.
Referenced by Kb::frameUpdate().
                                                                      {
    light()->resetIndicators();
    if(_iOpacity <= 0.f)
        return;
    if(_dpiIndicator){
        // Set DPI indicator according to index
        int index = curDpiIdx();
        if(index == -1 || index > OTHER)
            index = OTHER;
        lightIndicator("dpi", dpiClr[index].rgba());
    }
    // KB indicators
    if(iEnable[MODE]){
        for(int i = 0; i < Kb::HWMODE_MAX; i++){
            char name[4];
            snprintf(name, sizeof(name), "m%d", i + 1);
            if(modeIndex == i)
                lightIndicator(name, iColor[MODE][0].rgba());
            else
                lightIndicator(name, iColor[MODE][1].rgba());
        }
    }
    if(iEnable[MACRO])
        lightIndicator("mr", iColor[MUTE][1].rgba());
    if(iEnable[LIGHT]){
        switch(light()->dimming()){
        case 0: // 100%
            lightIndicator("light", light100Color.rgba());
            break;
        case 1: // 67%
            lightIndicator("light", iColor[LIGHT][1].rgba());
            break;
        case 2: // 33%
        case 3: // light off
            lightIndicator("light", iColor[LIGHT][0].rgba());
            break;
        }
    }
    if(iEnable[LOCK]){
        if(bind()->winLock())
            lightIndicator("lock", iColor[LOCK][0].rgba());
        else
            lightIndicator("lock", iColor[LOCK][1].rgba());
    }
    if(iEnable[MUTE]){
        switch(getMuteState()){
        case MUTED:
            lightIndicator("mute", iColor[MUTE][0].rgba());
            break;
        case UNMUTED:
            lightIndicator("mute", iColor[MUTE][1].rgba());
            break;
        default:
            lightIndicator("mute", muteNAColor.rgba());
            break;
        }
    }
    // Lock lights
    if(iEnable[NUM])
        lightIndicator("numlock", indicatorState[0] ? iColor[NUM][0].rgba() : iColor[NUM][1].rgba());
    if(iEnable[CAPS])
        lightIndicator("caps", indicatorState[1] ? iColor[CAPS][0].rgba() : iColor[CAPS][1].rgba());
    if(iEnable[SCROLL])
        lightIndicator("scroll", indicatorState[2] ? iColor[SCROLL][0].rgba() : iColor[SCROLL][1].rgba());
}
KbBind * KbPerf::bind () const [private]
Definition at line 100 of file kbperf.cpp.
References KbMode::bind(), and modeParent().
Referenced by applyIndicators().
                           {
    return modeParent()->bind();
}
QPoint KbPerf::curDpi () const [inline]
Definition at line 57 of file kbperf.h.
References dpiCurX, and dpiCurY.
Referenced by curDpiIdx(), KbPerf(), load(), operator=(), and pushDpi().
{ return QPoint(dpiCurX, dpiCurY); }
void KbPerf::curDpi (const QPoint &newDpi)
Definition at line 278 of file kbperf.cpp.
References _curDpi(), popDpi(), and pushedDpis.
                                       {
    while(pushedDpis.count() > 0)
        popDpi(pushedDpis.keys().last());
    _curDpi(newDpi);
}
void KbPerf::curDpi (intnewDpi) [inline]
Definition at line 59 of file kbperf.h.
References curDpi().
Referenced by curDpi().
{ curDpi(QPoint(newDpi, newDpi)); }
int KbPerf::curDpiIdx () const [inline]
Definition at line 61 of file kbperf.h.
References dpiCurIdx.
Referenced by applyIndicators(), dpiDown(), dpiUp(), and Kb::readNotify().
{ return dpiCurIdx; }
void KbPerf::curDpiIdx (intnewIdx) [inline]
Definition at line 62 of file kbperf.h.
References curDpi(), and dpi().
{ curDpi(dpi(newIdx)); }
void KbPerf::didLoad () [signal]
Definition at line 134 of file moc_kbperf.cpp.
Referenced by load().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
QPoint KbPerf::dpi (intindex) const [inline]
Definition at line 48 of file kbperf.h.
References DPI_COUNT, dpiX, and dpiY.
Referenced by MPerfWidget::boxXChanged(), MPerfWidget::boxYChanged(), curDpiIdx(), KeyAction::keyEvent(), Kb::readNotify(), RebindWidget::setBind(), MPerfWidget::setPerf(), MPerfWidget::sliderXMoved(), MPerfWidget::sliderYMoved(), and sniperDpi().
{ if(index < 0 || index >= DPI_COUNT) return QPoint(); return QPoint(dpiX[index], dpiY[index]); }
void KbPerf::dpi (intindex, const QPoint &newValue)
Definition at line 249 of file kbperf.cpp.
References _needsSave, _needsUpdate, DPI_COUNT, dpiCurIdx, dpiCurX, dpiCurY, dpiX, and dpiY.
                                                 {
    if(index < 0 || index >= DPI_COUNT)
        return;
    dpiX[index] = newValue.x();
    dpiY[index] = newValue.y();
    // Update current DPI if needed
    if(dpiCurIdx == index){
        dpiCurX = newValue.x();
        dpiCurY = newValue.y();
    }
    _needsUpdate = _needsSave = true;
}
void KbPerf::dpi (intindex, intnewValue) [inline]
Definition at line 53 of file kbperf.h.
References dpi().
Referenced by dpi().
{ dpi(index, QPoint(newValue, newValue)); }
QColor KbPerf::dpiColor (intindex) const [inline]
Definition at line 82 of file kbperf.h.
References dpiClr.
Referenced by MPerfWidget::colorChanged(), Kb::readNotify(), MPerfWidget::setPerf(), and update().
{ return dpiClr[index]; }
void KbPerf::dpiColor (intindex, const QColor &newColor) [inline]
Definition at line 83 of file kbperf.h.
References _needsSave, _needsUpdate, and dpiClr.
{ dpiClr[index] = newColor; _needsUpdate = _needsSave = true; }
void KbPerf::dpiDown ()
Definition at line 319 of file kbperf.cpp.
References curDpiIdx(), dpiOn, and SNIPER.
Referenced by KeyAction::keyEvent().
                    {
    int idx = curDpiIdx();
    do {
        idx--;
        if(idx <= SNIPER)
            return;
    } while(!dpiOn[idx]);
    curDpiIdx(idx);
}
bool KbPerf::dpiEnabled (intindex) const [inline]
Definition at line 66 of file kbperf.h.
References dpiOn.
Referenced by MPerfWidget::enableChanged(), Kb::readNotify(), and MPerfWidget::setPerf().
{ return dpiOn[index]; }
void KbPerf::dpiEnabled (intindex, boolnewEnabled) [inline]
Definition at line 67 of file kbperf.h.
References _needsSave, _needsUpdate, and dpiOn.
{ if(index <= 0) return; dpiOn[index] = newEnabled; _needsUpdate = _needsSave = true; }
bool KbPerf::dpiIndicator () const [inline]
Definition at line 79 of file kbperf.h.
References _dpiIndicator.
Referenced by MPerfWidget::on_indicBox_clicked(), and MPerfWidget::setPerf().
{ return _dpiIndicator; }
void KbPerf::dpiIndicator (boolnewDpiIndicator) [inline]
Definition at line 80 of file kbperf.h.
References _dpiIndicator, and _needsSave.
{ _dpiIndicator = newDpiIndicator; _needsSave = true; }
void KbPerf::dpiUp ()
Definition at line 308 of file kbperf.cpp.
References curDpiIdx(), DPI_COUNT, and dpiOn.
Referenced by KeyAction::keyEvent().
                  {
    // Scroll past disabled DPIs and choose the next one up
    int idx = curDpiIdx();
    do {
        idx++;
        if(idx >= DPI_COUNT)
            return;
    } while(!dpiOn[idx]);
    curDpiIdx(idx);
}
void KbPerf::getIndicator (indicatorindex, QColor &color1, QColor &color2, QColor &color3, bool &software_enable, i_hw &hardware_enable)
Definition at line 329 of file kbperf.cpp.
References HW_IMAX, hwIType, I_COUNT, iColor, iEnable, LIGHT, light100Color, MUTE, muteNAColor, and NONE.
Referenced by KPerfWidget::setPerf().
                                                                                                                                      {
    if(index < 0 || index >= I_COUNT)
        return;
    color1 = iColor[index][0];
    color2 = iColor[index][1];
    if(index == LIGHT)
        color3 = light100Color;
    else if(index == MUTE)
        color3 = muteNAColor;
    else
        color3 = QColor();
    software_enable = iEnable[index];
    hardware_enable = (index <= HW_IMAX ? hwIType[index] : NONE);
}
float KbPerf::iOpacity () const [inline]
Definition at line 76 of file kbperf.h.
References _iOpacity.
Referenced by KPerfWidget::on_intensityBox_valueChanged(), MPerfWidget::on_spinBox_valueChanged(), KPerfWidget::setPerf(), and MPerfWidget::setPerf().
{ return _iOpacity; }
void KbPerf::iOpacity (floatnewIOpacity) [inline]
Definition at line 77 of file kbperf.h.
References _iOpacity, and _needsSave.
{ _iOpacity = newIOpacity; _needsSave = true; }
height KbPerf::liftHeight () const [inline]
Definition at line 38 of file kbperf.h.
References _liftHeight.
Referenced by MPerfWidget::on_lHeightBox_activated(), Kb::readNotify(), and MPerfWidget::setPerf().
{ return _liftHeight; }
void KbPerf::liftHeight (heightnewHeight)
Definition at line 361 of file kbperf.cpp.
References _liftHeight, _needsSave, _needsUpdate, and HIGH.
                                       {
    if(newHeight < LOW || newHeight > HIGH)
        return;
    _liftHeight = newHeight;
    _needsUpdate = _needsSave = true;
}
KbLight * KbPerf::light () const [private]
Definition at line 104 of file kbperf.cpp.
References KbMode::light(), and modeParent().
Referenced by applyIndicators(), and lightIndicator().
                             {
    return modeParent()->light();
}
void KbPerf::lightIndicator (const char *name, QRgbrgba) [private]
Definition at line 425 of file kbperf.cpp.
References _iOpacity, light(), and KbLight::setIndicator().
Referenced by applyIndicators().
                                                      {
    int a = round(qAlpha(rgba) * _iOpacity);
    if(a <= 0)
        return;
    light()->setIndicator(name, qRgba(qRed(rgba), qGreen(rgba), qBlue(rgba), a));
}
void KbPerf::load (CkbSettings &settings)
Definition at line 108 of file kbperf.cpp.
References _angleSnap, _dpiIndicator, _iOpacity, _liftHeight, _needsSave, CkbSettings::contains(), CkbSettings::containsGroup(), curDpi(), didLoad(), DPI_COUNT, dpiClr, dpiLastIdx, dpiOn, dpiX, dpiY, HIGH, HW_IMAX, hwIType, I_COUNT, iColor, iEnable, LIGHT, light100Color, LOCK, MACRO, MEDIUM, MODE, MUTE, muteNAColor, NORMAL, OTHER, pushedDpis, runningPushIdx, and CkbSettings::value().
Referenced by KbMode::KbMode().
                                      {
    pushedDpis.clear();
    runningPushIdx = 1;
    _needsSave = false;
    bool readIndicators = true;
    if(!settings.containsGroup("Performance/Indicators")){
        // Read old indicator settings from the lighting group, if present
        // (ckb <= v0.2.0)
        SGroup group(settings, "Lighting");
        if(settings.contains("InactiveIndicators")){
            bool inOk = false;
            int inactive = settings.value("InactiveIndicators").toInt(&inOk);
            if(!inOk || inactive > 2)
                inactive = 2;
            if(inactive == 1)
                _iOpacity = 0.75f;
            else if(inactive == 0)
                _iOpacity = 0.5f;
            else if(inactive < 0){
                // Indicators disabled
                iEnable[MODE] = iEnable[MACRO] = iEnable[LIGHT] = iEnable[LOCK] = iEnable[MUTE] = false;
            }
            bool showMute = (settings.value("ShowMute").toInt(&inOk) != 0);
            if(inOk && !showMute)
                iEnable[MUTE] = false;
            readIndicators = false;
        }
    }
    SGroup group(settings, "Performance");
    // Read DPI settings
    {
        SGroup group(settings, "DPI");
        for(int i = 0; i < DPI_COUNT; i++){
            QString iStr = QString::number(i);
            QPoint value = settings.value(iStr).toPoint();
            if(value.isNull())
                continue;
            dpiX[i] = value.x(); dpiY[i] = value.y();
            QColor color = settings.value(iStr + "RGB").toString();
            if(color.isValid())
                dpiClr[i] = color;
            if(i != 0)
                dpiOn[i] = !settings.value(iStr + "Disabled").toBool();
        }
        QColor color = settings.value("6RGB").toString();
        if(color.isValid())
            dpiClr[OTHER] = color;
        if(settings.contains("LastIdx")){
            dpiLastIdx = settings.value("LastIdx").toInt();
            if(dpiLastIdx >= DPI_COUNT || dpiLastIdx < 0)
                dpiLastIdx = 1;
        }
        QPoint value = settings.value("Current").toPoint();
        if(!value.isNull())
            curDpi(value);
    }
    // Read misc. mouse settings
    _liftHeight = (height)settings.value("LiftHeight").toInt();
    if(_liftHeight < LOW || _liftHeight > HIGH)
        _liftHeight = MEDIUM;
    _angleSnap = settings.value("AngleSnap").toBool();
    if(settings.contains("NoIndicator")){
        // ckb <= v0.2.0
        _dpiIndicator = !settings.value("NoIndicator").toBool();
    } else {
        _dpiIndicator = settings.value("Indicators/DPI", true).toBool();
    }
    // Read indicator settings
    if(readIndicators){
        SGroup group(settings, "Indicators");
        _iOpacity = settings.value("Opacity", 100).toInt() / 100.f;
        for(int i = 0; i < I_COUNT; i++){
            SGroup group(settings, QString::number(i));
            QColor color = settings.value("RGB0").toString();
            if(color.isValid())
                iColor[i][0] = color;
            color = settings.value("RGB1").toString();
            if(color.isValid())
                iColor[i][1] = color;
            if(i == LIGHT){
                color = settings.value("RGB2").toString();
                if(color.isValid())
                    light100Color = color;
            } else if(i == MUTE){
                color = settings.value("RGB2").toString();
                if(color.isValid())
                    muteNAColor = color;
            }
            if(i <= HW_IMAX){
                iEnable[i] = settings.value("Enable", false).toBool();
                hwIType[i] = (i_hw)settings.value("Hardware", (int)NORMAL).toInt();
            } else {
                iEnable[i] = settings.value("Enable", true).toBool();
            }
        }
    }
    emit didLoad();
}
KbMode* KbPerf::modeParent () const [inline], [private]
Definition at line 124 of file kbperf.h.
Referenced by bind(), and light().
{ return (KbMode*)parent(); }
bool KbPerf::needsSave () const [inline]
Definition at line 28 of file kbperf.h.
References _needsSave.
Referenced by KbMode::needsSave().
{ return _needsSave; }
const KbPerf & KbPerf::operator= (const KbPerf &rhs)
Definition at line 78 of file kbperf.cpp.
References _angleSnap, _dpiIndicator, _iOpacity, _liftHeight, _needsSave, _needsUpdate, curDpi(), DPI_COUNT, dpiClr, dpiCurIdx, dpiCurX, dpiCurY, dpiLastIdx, dpiOn, dpiX, dpiY, hwIType, I_COUNT, iColor, iEnable, light100Color, muteNAColor, pushedDpis, and runningPushIdx.
                                                   {
    dpiCurX = other.dpiCurX; dpiCurY = other.dpiCurY; dpiCurIdx = other.dpiCurIdx; dpiLastIdx = other.dpiLastIdx; runningPushIdx = 1;
    _iOpacity = other._iOpacity; light100Color = other.light100Color; muteNAColor = other.muteNAColor; _dpiIndicator = other._dpiIndicator;
    _liftHeight = other._liftHeight; _angleSnap = other._angleSnap;
    _needsUpdate = true; _needsSave = true;
    memcpy(dpiX, other.dpiX, sizeof(dpiX));
    memcpy(dpiY, other.dpiY, sizeof(dpiY));
    for(int i = 0; i < DPI_COUNT + 1; i++)
        dpiClr[i] = other.dpiClr[i];
    memcpy(dpiOn, other.dpiOn, sizeof(dpiOn));
    for(int i = 0; i < I_COUNT; i++){
        iColor[i][0] = other.iColor[i][0];
        iColor[i][1] = other.iColor[i][1];
    }
    memcpy(iEnable, other.iEnable, sizeof(iEnable));
    memcpy(hwIType, other.hwIType, sizeof(hwIType));
    // Don't copy pushed DPI states. If the other mode has any, restore the original DPI
    if(!other.pushedDpis.isEmpty())
        curDpi(other.pushedDpis[0]);
    return other;
}
void KbPerf::popDpi (quint64pushIdx)
Definition at line 296 of file kbperf.cpp.
References _curDpi(), _needsSave, _needsUpdate, map_last, and pushedDpis.
Referenced by curDpi(), and KeyAction::keyEvent().
                                  {
    if(pushIdx == 0 || !pushedDpis.contains(pushIdx))
        return;
    pushedDpis.remove(pushIdx);
    // Set the DPI to the last-pushed value still on the stack
    _curDpi(map_last(pushedDpis));
    // If all values have been popped, remove the original DPI
    if(pushedDpis.count() == 1)
        pushedDpis.clear();
    _needsUpdate = _needsSave = true;
}
quint64 KbPerf::pushDpi (const QPoint &newDpi)
Definition at line 284 of file kbperf.cpp.
References _curDpi(), curDpi(), pushedDpis, and runningPushIdx.
Referenced by KeyAction::keyEvent(), and pushSniper().
                                           {
    if(pushedDpis.isEmpty())
        // Push original DPI
        pushedDpis[0] = curDpi();
    quint64 index = runningPushIdx++;
    if(runningPushIdx == 0)
        runningPushIdx = 1;
    pushedDpis[index] = newDpi;
    _curDpi(newDpi);
    return index;
}
quint64 KbPerf::pushDpi (intnewDpi) [inline]
Definition at line 71 of file kbperf.h.
References pushDpi().
Referenced by pushDpi().
{ return pushDpi(QPoint(newDpi, newDpi)); }
quint64 KbPerf::pushSniper () [inline]
Definition at line 72 of file kbperf.h.
References pushDpi(), and sniperDpi().
Referenced by KeyAction::keyEvent().
{ return pushDpi(sniperDpi()); }
void KbPerf::save (CkbSettings &settings)
Definition at line 207 of file kbperf.cpp.
References _angleSnap, _dpiIndicator, _liftHeight, _needsSave, DPI_COUNT, dpiClr, dpiCurX, dpiCurY, dpiLastIdx, dpiOn, dpiX, dpiY, HW_IMAX, hwIType, I_COUNT, iColor, iEnable, LIGHT, light100Color, MUTE, muteNAColor, OTHER, pushedDpis, and CkbSettings::setValue().
Referenced by KbMode::save().
                                      {
    _needsSave = false;
    SGroup group(settings, "Performance");
    {
        SGroup group(settings, "DPI");
        for(int i = 0; i < DPI_COUNT; i++){
            QString iStr = QString::number(i);
            settings.setValue(iStr, QPoint(dpiX[i], dpiY[i]));
            settings.setValue(iStr + "RGB", dpiClr[i].name(QColor::HexArgb));
            if(i != 0)
                settings.setValue(iStr + "Disabled", !dpiOn[i]);
        }
        settings.setValue("6RGB", dpiClr[OTHER].name(QColor::HexArgb));
        settings.setValue("LastIdx", dpiLastIdx);
        int curX = dpiCurX, curY = dpiCurY;
        // Ignore any pushed modes
        if(pushedDpis.count() > 0){
            curX = pushedDpis.value(0).x();
            curY = pushedDpis.value(0).y();
        }
        settings.setValue("Current", QPoint(curX, curY));
    }
    settings.setValue("LiftHeight", _liftHeight);
    settings.setValue("AngleSnap", _angleSnap);
    {
        SGroup group(settings, "Indicators");
        settings.setValue("DPI", _dpiIndicator);
        for(int i = 0; i < I_COUNT; i++){
            SGroup group(settings, QString::number(i));
            settings.setValue("RGB0", iColor[i][0].name(QColor::HexArgb));
            settings.setValue("RGB1", iColor[i][1].name(QColor::HexArgb));
            if(i == LIGHT)
                settings.setValue("RGB2", light100Color.name(QColor::HexArgb));
            else if(i == MUTE)
                settings.setValue("RGB2", muteNAColor.name(QColor::HexArgb));
            settings.setValue("Enable", iEnable[i]);
            if(i <= HW_IMAX)
                settings.setValue("Hardware", (int)hwIType[i]);
        }
    }
}
void KbPerf::setIndicator (indicatorindex, const QColor &color1, const QColor &color2, const QColor &color3 = QColor(), boolsoftware_enable = true, i_hwhardware_enable = NORMAL)
Definition at line 344 of file kbperf.cpp.
References _needsSave, _needsUpdate, HW_IMAX, hwIType, I_COUNT, iColor, iEnable, LIGHT, light100Color, MUTE, muteNAColor, NONE, and NORMAL.
Referenced by KPerfWidget::uiUpdated().
                                                                                                                                                      {
    if(index < 0 || index >= I_COUNT)
        return;
    iColor[index][0] = color1;
    iColor[index][1] = color2;
    if(index == LIGHT)
        light100Color = color3;
    else if(index == MUTE)
        muteNAColor = color3;
    iEnable[index] = software_enable;
    if(hardware_enable == NONE)
        hardware_enable = NORMAL;
    if(index <= HW_IMAX)
        hwIType[index] = hardware_enable;
    _needsUpdate = _needsSave = true;
}
void KbPerf::setNeedsUpdate () [inline]
Definition at line 113 of file kbperf.h.
References _needsUpdate.
Referenced by KbMode::setNeedsUpdate().
{ _needsUpdate = true; }
void KbPerf::settingsUpdated () [signal]
Definition at line 140 of file moc_kbperf.cpp.
Referenced by update().
{
    QMetaObject::activate(this, &staticMetaObject, 1, Q_NULLPTR);
}
QPoint KbPerf::sniperDpi () const [inline]
Definition at line 50 of file kbperf.h.
References dpi(), and SNIPER.
Referenced by pushSniper().
{ return dpi(SNIPER); }
void KbPerf::sniperDpi (const QPoint &newValue) [inline]
Definition at line 51 of file kbperf.h.
References dpi(), and SNIPER.
{ dpi(SNIPER, newValue); }
void KbPerf::sniperDpi (intnewValue) [inline]
Definition at line 54 of file kbperf.h.
References sniperDpi().
Referenced by sniperDpi().
{ sniperDpi(QPoint(newValue, newValue)); }
void KbPerf::update (QFile &cmd, intnotifyNumber, boolforce = false, boolsaveCustomDpi = true)
Definition at line 373 of file kbperf.cpp.
References _angleSnap, _liftHeight, _needsUpdate, DPI_COUNT, dpiColor(), dpiCurIdx, dpiCurX, dpiCurY, dpiOn, dpiX, dpiY, HW_I_COUNT, hwIType, OFF, ON, and settingsUpdated().
Referenced by Kb::frameUpdate(), and Kb::hwSave().
                                                                               {
    if(!force && !_needsUpdate)
        return;
    emit settingsUpdated();
    _needsUpdate = false;
    // Save DPI stage 0 (sniper)
    cmd.write(QString("dpi 0:%1,%2").arg(dpiX[0]).arg(dpiY[0]).toLatin1());
    // If the mouse is set to a custom DPI, save it in stage 1
    int stage = dpiCurIdx;
    if(stage < 0 && saveCustomDpi){
        stage = 1;
        cmd.write(QString(" 1:%1,%2").arg(dpiCurX).arg(dpiCurY).toLatin1());
    } else {
        // Otherwise, save stage 1 normally
        if(!dpiOn[1] && stage != 1)
            cmd.write(" 1:off");
        else
            cmd.write(QString(" 1:%1,%2").arg(dpiX[1]).arg(dpiY[1]).toLatin1());
    }
    // Save stages 1 - 5
    for(int i = 2; i < DPI_COUNT; i++){
        if(!dpiOn[i] && stage != i)
            cmd.write(QString(" %1:off").arg(i).toLatin1());
        else
        cmd.write(QString(" %1:%2,%3").arg(i).arg(dpiX[i]).arg(dpiY[i]).toLatin1());
    }
    // Save stage selection, lift height, and angle snap
    cmd.write(QString(" dpisel %1 lift %2 snap %3").arg(stage).arg(_liftHeight).arg(_angleSnap ? "on" : "off").toLatin1());
    // Save DPI colors
    cmd.write(" rgb");
    for(int i = 0; i < DPI_COUNT; i++){
        QColor color = dpiColor(i);
        cmd.write(" dpi");
        char output[9];
        snprintf(output, sizeof(output), "%1d:%02x%02x%02x", i, color.red(), color.green(), color.blue());
        cmd.write(output);
    }
    // Enable indicator notifications
    cmd.write(QString("\n@%1 inotify all").arg(notifyNumber).toLatin1());
    // Set indicator state
    const char* iNames[HW_I_COUNT] = { "num", "caps", "scroll" };
    for(int i = 0; i < HW_I_COUNT; i++){
        if(hwIType[i] == ON)
            cmd.write(" ion ");
        else if(hwIType[i] == OFF)
            cmd.write(" ioff ");
        else
            cmd.write(" iauto ");
        cmd.write(iNames[i]);
    }
}
Field Documentation
bool KbPerf::_angleSnap [private]
Definition at line 158 of file kbperf.h.
Referenced by angleSnap(), load(), operator=(), save(), and update().
bool KbPerf::_dpiIndicator [private]
Definition at line 154 of file kbperf.h.
Referenced by applyIndicators(), dpiIndicator(), load(), operator=(), and save().
float KbPerf::_iOpacity [private]
Definition at line 149 of file kbperf.h.
Referenced by applyIndicators(), iOpacity(), lightIndicator(), load(), and operator=().
height KbPerf::_liftHeight [private]
Definition at line 157 of file kbperf.h.
Referenced by liftHeight(), load(), operator=(), save(), and update().
bool KbPerf::_needsSave [private]
Definition at line 160 of file kbperf.h.
Referenced by _curDpi(), angleSnap(), dpi(), dpiColor(), dpiEnabled(), dpiIndicator(), iOpacity(), liftHeight(), load(), needsSave(), operator=(), popDpi(), save(), and setIndicator().
bool KbPerf::_needsUpdate [private]
Definition at line 160 of file kbperf.h.
Referenced by _curDpi(), angleSnap(), dpi(), dpiColor(), dpiEnabled(), liftHeight(), operator=(), popDpi(), setIndicator(), setNeedsUpdate(), and update().
const int KbPerf::DPI_COUNT = 6 [static]
Definition at line 46 of file kbperf.h.
Referenced by _curDpi(), dpi(), dpiUp(), KbPerf(), KeyAction::keyEvent(), load(), operator=(), Kb::readNotify(), save(), RebindWidget::setBind(), and update().
const int KbPerf::DPI_MAX = 12000 [static]
Definition at line 47 of file kbperf.h.
const int KbPerf::DPI_MIN = 100 [static]
Definition at line 47 of file kbperf.h.
Referenced by dpiExp(), and dpiLog().
QColor KbPerf::dpiClr[DPI_COUNT+1] [private]
Definition at line 135 of file kbperf.h.
Referenced by applyIndicators(), dpiColor(), KbPerf(), load(), operator=(), and save().
int KbPerf::dpiCurIdx [private]
Definition at line 134 of file kbperf.h.
Referenced by _curDpi(), curDpiIdx(), dpi(), KbPerf(), operator=(), and update().
int KbPerf::dpiCurX [private]
Definition at line 134 of file kbperf.h.
Referenced by _curDpi(), curDpi(), dpi(), KbPerf(), operator=(), save(), and update().
int KbPerf::dpiCurY [private]
Definition at line 134 of file kbperf.h.
Referenced by _curDpi(), curDpi(), dpi(), KbPerf(), operator=(), save(), and update().
int KbPerf::dpiLastIdx [private]
Definition at line 138 of file kbperf.h.
Referenced by _curDpi(), KbPerf(), load(), operator=(), and save().
bool KbPerf::dpiOn[DPI_COUNT] [private]
Definition at line 136 of file kbperf.h.
Referenced by dpiDown(), dpiEnabled(), dpiUp(), KbPerf(), load(), operator=(), save(), and update().
int KbPerf::dpiX[DPI_COUNT] [private]
Definition at line 132 of file kbperf.h.
Referenced by _curDpi(), dpi(), KbPerf(), load(), operator=(), save(), and update().
int KbPerf::dpiY[DPI_COUNT] [private]
Definition at line 133 of file kbperf.h.
Referenced by _curDpi(), dpi(), KbPerf(), load(), operator=(), save(), and update().
const int KbPerf::HW_I_COUNT = (int)HW_IMAX + 1 [static]
Definition at line 104 of file kbperf.h.
Referenced by KbPerf(), and update().
i_hw KbPerf::hwIType[HW_I_COUNT] [private]
Definition at line 153 of file kbperf.h.
Referenced by getIndicator(), KbPerf(), load(), operator=(), save(), setIndicator(), and update().
const int KbPerf::I_COUNT = (int)MUTE + 1 [static]
Definition at line 104 of file kbperf.h.
Referenced by getIndicator(), KbPerf(), load(), operator=(), save(), and setIndicator().
QColor KbPerf::iColor[I_COUNT][2] [private]
Definition at line 150 of file kbperf.h.
Referenced by applyIndicators(), getIndicator(), KbPerf(), load(), operator=(), save(), and setIndicator().
bool KbPerf::iEnable[I_COUNT] [private]
Definition at line 152 of file kbperf.h.
Referenced by applyIndicators(), getIndicator(), KbPerf(), load(), operator=(), save(), and setIndicator().
QColor KbPerf::light100Color [private]
Definition at line 151 of file kbperf.h.
Referenced by applyIndicators(), getIndicator(), KbPerf(), load(), operator=(), save(), and setIndicator().
QColor KbPerf::muteNAColor [private]
Definition at line 151 of file kbperf.h.
Referenced by applyIndicators(), getIndicator(), KbPerf(), load(), operator=(), save(), and setIndicator().
const int KbPerf::OTHER = DPI_COUNT [static]
Definition at line 81 of file kbperf.h.
Referenced by applyIndicators(), MPerfWidget::colorChanged(), load(), save(), and MPerfWidget::setPerf().
QMap<quint64, QPoint> KbPerf::pushedDpis [private]
Definition at line 142 of file kbperf.h.
Referenced by curDpi(), KbPerf(), load(), operator=(), popDpi(), pushDpi(), and save().
uint KbPerf::runningPushIdx [private]
Definition at line 143 of file kbperf.h.
Referenced by load(), operator=(), and pushDpi().
const int KbPerf::SNIPER = 0 [static]
Definition at line 46 of file kbperf.h.
Referenced by dpiDown(), and sniperDpi().
Author
Generated automatically by Doxygen for ckb-next from the source code.