KbProfile
NAME
KbProfile -
SYNOPSIS
#include <src/ckb/kbprofile.h>
Inherits QObject.
Public Types
typedef QList< KbMode * > ModeList
Public Member Functions
KbProfile (Kb *parent, const KeyMap &keyMap, const KbProfile &other)
KbProfile (Kb *parent, const KeyMap &keyMap, const QString &guid='', const QString &modified='')
KbProfile (Kb *parent, const KeyMap &keyMap, CkbSettings &settings, const QString &guid)
void save (CkbSettings &settings)
bool needsSave () const
void setNeedsSave ()
QString name () const
void name (const QString &newName)
UsbId & id ()
void id (const UsbId &newId)
void newId ()
const KeyMap & keyMap () const
void keyMap (const KeyMap &newKeyMap)
const ModeList & modes () const
void modes (const QList< KbMode * > &newModes)
void append (KbMode *newMode)
void insert (int index, KbMode *newMode)
void removeAll (KbMode *mode)
void move (int from, int to)
int modeCount () const
int indexOf (KbMode *mode) const
KbMode * find (const QUuid &id)
KbMode * currentMode () const
void currentMode (KbMode *newCurrentMode)
Private Member Functions
void setNeedsUpdate ()
Private Attributes
KbMode * _currentMode
QString _name
UsbId _id
KeyMap _keyMap
ModeList _modes
bool _needsSave
Detailed Description
Definition at line 11 of file kbprofile.h.
Member Typedef Documentation
typedef QList<KbMode*> KbProfile::ModeList
Definition at line 41 of file kbprofile.h.
Constructor & Destructor Documentation
KbProfile::KbProfile (Kb *parent, const KeyMap &keyMap, const KbProfile &other) [explicit]
Definition at line 4 of file kbprofile.cpp.
References _currentMode, _modes, and modes().
                                                                             :
    QObject(parent), _currentMode(0), _name(other._name), _id(other._id), _keyMap(keyMap), _needsSave(true)
{
    foreach(KbMode* mode, other.modes()){
        KbMode* newMode = new KbMode(parent, keyMap, *mode);
        if(!_currentMode || mode == other._currentMode)
            _currentMode = newMode;
        _modes.append(newMode);
    }
}
KbProfile::KbProfile (Kb *parent, const KeyMap &keyMap, const QString &guid = '', const QString &modified = '') [explicit]
Definition at line 15 of file kbprofile.cpp.
References _id, and UsbId::guid.
                                                                                                   :
    QObject(parent), _currentMode(0), _id(guid, modified.toUInt(0, 16)), _keyMap(keyMap), _needsSave(true)
{
    if(_id.guid.isNull())
        _id.guid = QUuid::createUuid();
}
KbProfile::KbProfile (Kb *parent, const KeyMap &keyMap, CkbSettings &settings, const QString &guid) [explicit]
Definition at line 22 of file kbprofile.cpp.
References _currentMode, _id, _keyMap, _modes, _name, CkbSettings::contains(), current, UsbId::guid, UsbId::hwModified, UsbId::hwModifiedString(), KbMode::id(), UsbId::modified, UsbId::modifiedString(), and CkbSettings::value().
                                                                                                 :
    QObject(parent), _currentMode(0), _id(guid, 0), _keyMap(keyMap), _needsSave(false)
{
    // Load data from preferences
    SGroup group(settings, guid);
    _name = settings.value("Name").toString().trimmed();
    if(_name == "")
        _name = "Unnamed";
    _id.modifiedString(settings.value("Modified").toString());
    if(settings.contains("HwModified"))
        _id.hwModifiedString(settings.value("HwModified").toString());
    else
        _id.hwModified = _id.modified;
    QUuid current = settings.value("CurrentMode").toString().trimmed();
    // Load modes
    uint count = settings.value("ModeCount").toUInt();
    for(uint i = 0; i < count; i++){
        SGroup group(settings, QString::number(i));
        KbMode* mode = new KbMode(parent, _keyMap, settings);
        _modes.append(mode);
        // Set currentMode to the mode matching the current GUID, or the first mode in case it's not found
        if(current == mode->id().guid || !_currentMode)
            _currentMode = mode;
    }
}
Member Function Documentation
void KbProfile::append (KbMode *newMode) [inline]
Definition at line 44 of file kbprofile.h.
References _modes, and setNeedsUpdate().
Referenced by Kb::hwSave(), KbWidget::on_modesList_itemClicked(), KbProfileDialog::profileList_reordered(), Kb::readNotify(), and Kb::setCurrentProfile().
{ setNeedsUpdate(); _modes.append(newMode); }
KbMode* KbProfile::currentMode () const [inline]
Definition at line 54 of file kbprofile.h.
References _currentMode.
Referenced by KeyAction::keyEvent(), KbBindWidget::on_copyButton_clicked(), KPerfWidget::on_copyButton_clicked(), MPerfWidget::on_copyButton_clicked(), Kb::setCurrentMode(), and Kb::setCurrentProfile().
{ return _currentMode; }
void KbProfile::currentMode (KbMode *newCurrentMode) [inline]
Definition at line 55 of file kbprofile.h.
References _currentMode, and _needsSave.
{ _needsSave = true; _currentMode = newCurrentMode; }
KbMode* KbProfile::find (const QUuid &id) [inline]
Definition at line 51 of file kbprofile.h.
References _modes, UsbId::guid, id(), and KbMode::id().
Referenced by KbWidget::modesList_reordered(), and KbWidget::on_modesList_currentItemChanged().
{ foreach(KbMode* mode, _modes) { if(mode->id().guid == id) return mode; } return 0; }
UsbId& KbProfile::id () [inline]
Definition at line 30 of file kbprofile.h.
References _id.
Referenced by find(), Kb::find(), Kb::hwSave(), KbProfileDialog::on_profileList_customContextMenuRequested(), KbProfileDialog::on_profileList_itemChanged(), KbProfileDialog::on_profileList_itemClicked(), Kb::readNotify(), KbProfileDialog::repopulate(), Kb::save(), and Kb::writeProfileHeader().
{ return _id; }
void KbProfile::id (const UsbId &newId) [inline]
Definition at line 31 of file kbprofile.h.
References _id, _needsSave, and newId().
{ _needsSave = true; _id = newId; }
int KbProfile::indexOf (KbMode *mode) const [inline]
Definition at line 50 of file kbprofile.h.
References _modes.
Referenced by Kb::frameUpdate(), KeyAction::keyEvent(), KbWidget::modeChanged(), KbWidget::on_modesList_customContextMenuRequested(), and Kb::readNotify().
{ return _modes.indexOf(mode); }
void KbProfile::insert (intindex, KbMode *newMode) [inline]
Definition at line 45 of file kbprofile.h.
References _modes, and setNeedsUpdate().
Referenced by KbWidget::on_modesList_customContextMenuRequested().
{ setNeedsUpdate(); _modes.insert(index, newMode); }
const KeyMap& KbProfile::keyMap () const [inline]
Definition at line 37 of file kbprofile.h.
References _keyMap.
Referenced by KPerfWidget::setPerf(), and Kb::updateLayout().
{ return _keyMap; }
void KbProfile::keyMap (const KeyMap &newKeyMap)
Definition at line 85 of file kbprofile.cpp.
References _keyMap, _modes, KbMode::keyMap(), and setNeedsUpdate().
                                             {
    _keyMap = newKeyMap;
    foreach(KbMode* mode, _modes)
        mode->keyMap(newKeyMap);
    setNeedsUpdate();
}
int KbProfile::modeCount () const [inline]
Definition at line 49 of file kbprofile.h.
References _modes.
Referenced by Kb::hwSave(), KeyAction::keyEvent(), KbWidget::on_modesList_customContextMenuRequested(), Kb::readNotify(), save(), and Kb::setCurrentProfile().
{ return _modes.count(); }
const ModeList& KbProfile::modes () const [inline]
Definition at line 42 of file kbprofile.h.
References _modes.
Referenced by Kb::hwSave(), KbProfile(), KeyAction::keyEvent(), KbWidget::modesList_reordered(), KbBindWidget::on_copyButton_clicked(), KPerfWidget::on_copyButton_clicked(), MPerfWidget::on_copyButton_clicked(), KbWidget::on_modesList_customContextMenuRequested(), KbWidget::profileChanged(), Kb::readNotify(), RebindWidget::setBind(), Kb::setCurrentMode(), Kb::setCurrentProfile(), and Kb::updateLayout().
{ return _modes; }
void KbProfile::modes (const QList< KbMode * > &newModes) [inline]
Definition at line 43 of file kbprofile.h.
References _modes, and setNeedsUpdate().
{ setNeedsUpdate(); _modes = newModes; }
void KbProfile::move (intfrom, intto) [inline]
Definition at line 47 of file kbprofile.h.
References _modes, and setNeedsUpdate().
Referenced by Kb::readNotify().
{ setNeedsUpdate(); _modes.move(from, to); }
QString KbProfile::name () const [inline]
Definition at line 28 of file kbprofile.h.
References _name.
Referenced by KbProfileDialog::on_profileList_itemChanged(), Kb::readNotify(), KbProfileDialog::repopulate(), save(), KbWidget::updateProfileList(), and Kb::writeProfileHeader().
{ return _name; }
void KbProfile::name (const QString &newName) [inline]
Definition at line 29 of file kbprofile.h.
References _name, and _needsSave.
{ _needsSave = true; _name = newName.trimmed(); if(_name == "") _name = "Unnamed"; }
bool KbProfile::needsSave () const
Definition at line 68 of file kbprofile.cpp.
References _modes, _needsSave, and KbMode::needsSave().
Referenced by Kb::needsSave().
                                {
    if(_needsSave)
        return true;
    foreach(KbMode* mode, _modes){
        if(mode->needsSave())
            return true;
    }
    return false;
}
void KbProfile::newId ()
Definition at line 78 of file kbprofile.cpp.
References _id, _modes, _needsSave, and KbMode::newId().
Referenced by id(), and KbProfileDialog::on_profileList_customContextMenuRequested().
                     {
    _needsSave = true;
    _id = UsbId();
    foreach(KbMode* mode, _modes)
        mode->newId();
}
void KbProfile::removeAll (KbMode *mode) [inline]
Definition at line 46 of file kbprofile.h.
References _modes, and setNeedsUpdate().
Referenced by KbWidget::on_modesList_customContextMenuRequested(), and KbProfileDialog::on_profileList_customContextMenuRequested().
{ setNeedsUpdate(); _modes.removeAll(mode); }
void KbProfile::save (CkbSettings &settings)
Definition at line 48 of file kbprofile.cpp.
References _currentMode, _id, _modes, _needsSave, UsbId::guidString(), UsbId::hwModifiedString(), KbMode::id(), modeCount(), UsbId::modifiedString(), name(), UsbId::newModified(), KbMode::save(), and CkbSettings::setValue().
Referenced by Kb::save().
                                         {
    _needsSave = false;
    _id.newModified();
    // Save data to preferences
    SGroup group(settings, id().guidString());
    settings.setValue("Name", name());
    settings.setValue("Modified", _id.modifiedString());
    settings.setValue("HwModified", _id.hwModifiedString());
    if(_currentMode)
        settings.setValue("CurrentMode", _currentMode->id().guidString());
    // Save modes
    uint count = modeCount();
    settings.setValue("ModeCount", count);
    for(uint i = 0; i < count; i++){
        SGroup group(settings, QString::number(i));
        KbMode* mode = _modes.at(i);
        mode->save(settings);
    }
}
void KbProfile::setNeedsSave () [inline]
Definition at line 25 of file kbprofile.h.
References _needsSave.
Referenced by Kb::hwSave(), Kb::readNotify(), and setNeedsUpdate().
{ _needsSave = true; }
void KbProfile::setNeedsUpdate () [inline], [private]
Definition at line 66 of file kbprofile.h.
References _modes, setNeedsSave(), and KbMode::setNeedsUpdate().
Referenced by append(), insert(), keyMap(), modes(), move(), and removeAll().
{ setNeedsSave(); foreach(KbMode* mode, _modes){ mode->setNeedsUpdate(); } }
Field Documentation
KbMode* KbProfile::_currentMode [private]
Definition at line 58 of file kbprofile.h.
Referenced by currentMode(), KbProfile(), and save().
UsbId KbProfile::_id [private]
Definition at line 60 of file kbprofile.h.
Referenced by id(), KbProfile(), newId(), and save().
KeyMap KbProfile::_keyMap [private]
Definition at line 61 of file kbprofile.h.
Referenced by KbProfile(), and keyMap().
ModeList KbProfile::_modes [private]
Definition at line 62 of file kbprofile.h.
Referenced by append(), find(), indexOf(), insert(), KbProfile(), keyMap(), modeCount(), modes(), move(), needsSave(), newId(), removeAll(), save(), and setNeedsUpdate().
QString KbProfile::_name [private]
Definition at line 59 of file kbprofile.h.
Referenced by KbProfile(), and name().
bool KbProfile::_needsSave [private]
Definition at line 63 of file kbprofile.h.
Referenced by currentMode(), id(), name(), needsSave(), newId(), save(), and setNeedsSave().
Author
Generated automatically by Doxygen for ckb-next from the source code.