.TH "src/ckb/keyaction.cpp" 3 "Sat May 27 2017" "Version v0.2.8 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/keyaction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <qdebug\&.h>\fP
.br
\fC#include 'keyaction\&.h'\fP
.br
\fC#include 'kb\&.h'\fP
.br
\fC#include 'kbanim\&.h'\fP
.br
\fC#include 'kbprofile\&.h'\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdio>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBANIM_ONCE\fP = 0x1"
.br
.ti -1c
.RI "static const int \fBANIM_KRSTOP\fP = 0x2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int ANIM_KRSTOP = 0x2\fC [static]\fP"

.PP
Definition at line 173 of file keyaction\&.cpp\&.
.PP
Referenced by KeyAction::animAction(), and KeyAction::animInfo()\&.
.SS "const int ANIM_ONCE = 0x1\fC [static]\fP"

.PP
Definition at line 173 of file keyaction\&.cpp\&.
.PP
Referenced by KeyAction::animAction(), and KeyAction::animInfo()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
