src/ckb-daemon/keymap.c
NAME
src/ckb-daemon/keymap.c -
SYNOPSIS
#include 'device.h'
#include 'includes.h'
#include 'keymap.h'
Macros
#define BUTTON_HID_COUNT 5
Functions
void hid_kb_translate (unsigned char *kbinput, int endpoint, int length, const unsigned char *urbinput)
void hid_mouse_translate (unsigned char *kbinput, short *xaxis, short *yaxis, int endpoint, int length, const unsigned char *urbinput)
void corsair_kbcopy (unsigned char *kbinput, int endpoint, const unsigned char *urbinput)
void corsair_mousecopy (unsigned char *kbinput, int endpoint, const unsigned char *urbinput)
Variables
const key keymap [(((152+3+12)+25)+11)]
Macro Definition Documentation
#define BUTTON_HID_COUNT 5
Definition at line 364 of file keymap.c.
Referenced by corsair_mousecopy(), and hid_mouse_translate().
Function Documentation
void corsair_kbcopy (unsigned char *kbinput, intendpoint, const unsigned char *urbinput)
Definition at line 394 of file keymap.c.
References N_KEYBYTES_HW.
Referenced by os_inputmain().
                                                                                        {
    if(endpoint == 2 || endpoint == -2){
        if(urbinput[0] != 3)
            return;
        urbinput++;
    }
    memcpy(kbinput, urbinput, N_KEYBYTES_HW);
}
void corsair_mousecopy (unsigned char *kbinput, intendpoint, const unsigned char *urbinput)
Definition at line 403 of file keymap.c.
References BUTTON_HID_COUNT, CLEAR_KEYBIT, MOUSE_BUTTON_FIRST, N_BUTTONS_HW, and SET_KEYBIT.
Referenced by os_inputmain().
                                                                                           {
    if(endpoint == 2 || endpoint == -2){
        if(urbinput[0] != 3)
            return;
        urbinput++;
    }
    for(int bit = BUTTON_HID_COUNT; bit < N_BUTTONS_HW; bit++){
        int byte = bit / 8;
        uchar test = 1 << (bit % 8);
        if(urbinput[byte] & test)
            SET_KEYBIT(kbinput, MOUSE_BUTTON_FIRST + bit);
        else
            CLEAR_KEYBIT(kbinput, MOUSE_BUTTON_FIRST + bit);
    }
}
void hid_kb_translate (unsigned char *kbinput, intendpoint, intlength, const unsigned char *urbinput)
Definition at line 223 of file keymap.c.
References ckb_warn, CLEAR_KEYBIT, and SET_KEYBIT.
Referenced by os_inputmain().
                                                                                                      {
    if(length < 1)
        return;
    // LUT for HID -> Corsair scancodes (-1 for no scan code, -2 for currently unsupported)
    // Modified from Linux drivers/hid/usbhid/usbkbd.c, key codes replaced with array indices and K95 keys added
    static const short hid_codes[256] = {
        -1, -1, -1, -1, 37, 54, 52, 39, 27, 40, 41, 42, 32, 43, 44, 45,
        56, 55, 33, 34, 25, 28, 38, 29, 31, 53, 26, 51, 30, 50, 13, 14,
        15, 16, 17, 18, 19, 20, 21, 22, 82, 0, 86, 24, 64, 23, 84, 35,
        79, 80, 81, 46, 47, 12, 57, 58, 59, 36, 1, 2, 3, 4, 5, 6,
         7, 8, 9, 10, 11, 72, 73, 74, 75, 76, 77, 78, 87, 88, 89, 95,
        93, 94, 92, 102, 103, 104, 105, 106, 107, 115, 116, 117, 112, 113, 114, 108,
       109, 110, 118, 119, 49, 69, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
        -2, -2, -2, -2, -2, -2, -2, -2, 98, -2, -2, -2, -2, -2, -2, 97,
       130, 131, -1, -1, -1, -2, -1, -2, -2, -2, -2, -2, -2, -1, -1, -1,
        -2, -2, -2, -2, -2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3, -1, -1, -1, // <- -3 = non-RGB program key
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 136, 137, 138, 139, 140, 141,
        60, 48, 62, 61, 91, 90, 67, 68, 142, 143, 99, 101, -2, 130, 131, 97,
        -2, 133, 134, 135, -2, 96, -2, 132, -2, -2, 71, 71, 71, 71, -1, -1,
    };
    switch(endpoint){
    case 1:
    case -1:
        // EP 1: 6KRO input (RGB and non-RGB)
        // Clear previous input
        for(int i = 0; i < 256; i++){
            if(hid_codes[i] >= 0)
                CLEAR_KEYBIT(kbinput, hid_codes[i]);
        }
        // Set new input
        for(int i = 0; i < 8; i++){
            if((urbinput[0] >> i) & 1)
                SET_KEYBIT(kbinput, hid_codes[i + 224]);
        }
        for(int i = 2; i < length; i++){
            if(urbinput[i] > 3){
                int scan = hid_codes[urbinput[i]];
                if(scan >= 0)
                    SET_KEYBIT(kbinput, scan);
                else
                    ckb_warn("Got unknown key press %d on EP 1\n", urbinput[i]);
            }
        }
        break;
    case -2:
        // EP 2 RGB: NKRO input
        if(urbinput[0] == 1){
            // Type 1: standard key
            if(length != 21)
                return;
            for(int bit = 0; bit < 8; bit++){
                if((urbinput[1] >> bit) & 1)
                    SET_KEYBIT(kbinput, hid_codes[bit + 224]);
                else
                    CLEAR_KEYBIT(kbinput, hid_codes[bit + 224]);
            }
            for(int byte = 0; byte < 19; byte++){
                char input = urbinput[byte + 2];
                for(int bit = 0; bit < 8; bit++){
                    int keybit = byte * 8 + bit;
                    int scan = hid_codes[keybit];
                    if((input >> bit) & 1){
                        if(scan >= 0)
                            SET_KEYBIT(kbinput, hid_codes[keybit]);
                        else
                            ckb_warn("Got unknown key press %d on EP 2\n", keybit);
                    } else if(scan >= 0)
                        CLEAR_KEYBIT(kbinput, hid_codes[keybit]);
                }
            }
            break;
        } else if(urbinput[0] == 2)
            ; // Type 2: media key (fall through)
        else
            break; // No other known types
    case 2:
        // EP 2 Non-RGB: media keys
        CLEAR_KEYBIT(kbinput, 97); // mute
        CLEAR_KEYBIT(kbinput, 98); // stop
        CLEAR_KEYBIT(kbinput, 99); // prev
        CLEAR_KEYBIT(kbinput, 100); // play
        CLEAR_KEYBIT(kbinput, 101); // next
        CLEAR_KEYBIT(kbinput, 130); // volup
        CLEAR_KEYBIT(kbinput, 131); // voldn
        for(int i = 0; i < length; i++){
            switch(urbinput[i]){
            case 181:
                SET_KEYBIT(kbinput, 101); // next
                break;
            case 182:
                SET_KEYBIT(kbinput, 99); // prev
                break;
            case 183:
                SET_KEYBIT(kbinput, 98); // stop
                break;
            case 205:
                SET_KEYBIT(kbinput, 100); // play
                break;
            case 226:
                SET_KEYBIT(kbinput, 97); // mute
                break;
            case 233:
                SET_KEYBIT(kbinput, 130); // volup
                break;
            case 234:
                SET_KEYBIT(kbinput, 131); // voldn
                break;
            }
        }
        break;
    case 3:
        // EP 3 non-RGB: NKRO input
        if(length != 15)
            return;
        for(int bit = 0; bit < 8; bit++){
            if((urbinput[0] >> bit) & 1)
                SET_KEYBIT(kbinput, hid_codes[bit + 224]);
            else
                CLEAR_KEYBIT(kbinput, hid_codes[bit + 224]);
        }
        for(int byte = 0; byte < 14; byte++){
            char input = urbinput[byte + 1];
            for(int bit = 0; bit < 8; bit++){
                int keybit = byte * 8 + bit;
                int scan = hid_codes[keybit];
                if((input >> bit) & 1){
                    if(scan >= 0)
                        SET_KEYBIT(kbinput, hid_codes[keybit]);
                    else
                        ckb_warn("Got unknown key press %d on EP 3\n", keybit);
                } else if(scan >= 0)
                    CLEAR_KEYBIT(kbinput, hid_codes[keybit]);
            }
        }
        break;
    }
}
void hid_mouse_translate (unsigned char *kbinput, short *xaxis, short *yaxis, intendpoint, intlength, const unsigned char *urbinput)
Definition at line 366 of file keymap.c.
References BUTTON_HID_COUNT, CLEAR_KEYBIT, MOUSE_BUTTON_FIRST, MOUSE_EXTRA_FIRST, and SET_KEYBIT.
Referenced by os_inputmain().
                                                                                                                                     {
    if((endpoint != 2 && endpoint != -2) || length < 10)
        return;
    // EP 2: mouse input
    if(urbinput[0] != 1)
        return;
    // Byte 1 = mouse buttons (bitfield)
    for(int bit = 0; bit < BUTTON_HID_COUNT; bit++){
        if(urbinput[1] & (1 << bit))
            SET_KEYBIT(kbinput, MOUSE_BUTTON_FIRST + bit);
        else
            CLEAR_KEYBIT(kbinput, MOUSE_BUTTON_FIRST + bit);
    }
    // Bytes 5 - 8: movement
    *xaxis += *(short*)(urbinput + 5);
    *yaxis += *(short*)(urbinput + 7);
    // Byte 9: wheel
    char wheel = urbinput[9];
    if(wheel > 0)
        SET_KEYBIT(kbinput, MOUSE_EXTRA_FIRST); // wheelup
    else
        CLEAR_KEYBIT(kbinput, MOUSE_EXTRA_FIRST);
    if(wheel < 0)
        SET_KEYBIT(kbinput, MOUSE_EXTRA_FIRST + 1); // wheeldn
    else
        CLEAR_KEYBIT(kbinput, MOUSE_EXTRA_FIRST + 1);
}
Variable Documentation
const key keymap[(((152+3+12)+25)+11)]
Definition at line 5 of file keymap.c.
Referenced by _cmd_get(), _cmd_macro(), cmd_bind(), cmd_rebind(), cmd_rgb(), initbind(), inputupdate_keys(), nprintkey(), printrgb(), readcmd(), and setactive_kb().
Author
Generated automatically by Doxygen for ckb-next from the source code.