KeyMap
NAME
KeyMap -
SYNOPSIS
#include <src/ckb/keymap.h>
Public Types
enum Model { NO_MODEL = -1, K65, K70, K95, STRAFE, M65, SABRE, SCIMITAR, _MODEL_MAX }
enum Layout { NO_LAYOUT = -1, DK, EU, EU_DVORAK, GB, GB_DVORAK, US, US_DVORAK, FR, DE, IT, NO, PL, MX, ES, SE, _LAYOUT_MAX }
Public Member Functions
bool isISO () const
bool isKeyboard () const
bool isMouse () const
KeyMap ()
KeyMap (Model _keyModel, Layout _keyLayout)
QString strLayout () const
QString strModel () const
Model model () const
Layout layout () const
QString name () const
uint count () const
uint width () const
uint height () const
Key key (const QString &name) const
Key operator[] (const QString &name) const
bool contains (const QString &name) const
const QHash< QString, Key > & map () const
operator const QHash< QString, Key > & () const
QStringList keys () const
QList< Key > positions () const
QString toStorage (const QString &name)
QString fromStorage (const QString &storage)
QStringList byPosition () const
Static Public Member Functions
static QStringList layoutNames ()
static bool isISO (Layout layout)
static Layout locale ()
static bool isKeyboard (Model model)
static bool isMouse (Model model)
static KeyMap fromName (const QString &name)
static Layout getLayout (const QString &name)
static QString getLayout (Layout layout)
static Model getModel (const short vendor, const short product)
KeyMap::getModel get the KeyMap::Model from the vendor / product special table. Use this function first, if you want to determine the firmware version to load or check.
static Model getModel (const QString &name)
KeyMap::getModel KeyMap model name.
static QString getModel (Model model)
KeyMap::getModel get the KeyMap name from the KeyMap::Model.
static QString friendlyName (const QString &key, Layout layout=US)
Static Private Member Functions
static int modelWidth (Model model)
static int modelHeight (Model model)
Private Attributes
QHash< QString, Key > _keys
short keyWidth
short keyHeight
Model keyModel:8
Layout keyLayout:8
Detailed Description
Definition at line 49 of file keymap.h.
Member Enumeration Documentation
enum KeyMap::Layout
Enumerator
NO_LAYOUT
DK
EU
EU_DVORAK
GB
GB_DVORAK
US
US_DVORAK
FR
DE
IT
NO
PL
MX
ES
SE
_LAYOUT_MAX
Definition at line 65 of file keymap.h.
                {
        NO_LAYOUT = -1,
        DK, // Danish
        EU, // English (EU)
        EU_DVORAK,
        GB, // English (UK)
        GB_DVORAK,
        US, // English (US)
        US_DVORAK,
        FR, // French
        DE, // German
        IT, // Italian
        NO, // Norwegian
        PL, // Polish (identical to US)
        MX, // Spanish (Mexico/Latin America)
        ES, // Spanish (Spain)
        SE, // Swedish
        _LAYOUT_MAX
    };
enum KeyMap::Model
Enumerator
NO_MODEL
K65
K70
K95
STRAFE
M65
SABRE
SCIMITAR
_MODEL_MAX
Definition at line 51 of file keymap.h.
               {
        NO_MODEL = -1,
        // Keyboard models
        K65,
        K70,
        K95,
        STRAFE,
        // Mouse models
        M65,
        SABRE,
        SCIMITAR,
        _MODEL_MAX
    };
Constructor & Destructor Documentation
KeyMap::KeyMap ()
Definition at line 613 of file keymap.cpp.
Referenced by friendlyName(), and fromName().
               :
     keyWidth(0), keyHeight(0),
     keyModel(NO_MODEL), keyLayout(NO_LAYOUT)
{}
KeyMap::KeyMap (Model_keyModel, Layout_keyLayout)
Definition at line 607 of file keymap.cpp.
                                                 :
    _keys(getMap(_keyModel, _keyLayout)),
    keyWidth(modelWidth(_keyModel)), keyHeight(modelHeight(_keyModel)),
    keyModel(_keyModel), keyLayout(_keyLayout)
{}
Member Function Documentation
QStringList KeyMap::byPosition () const
Definition at line 618 of file keymap.cpp.
References Key::x, x, Key::y, and y.
Referenced by RebindWidget::setBind().
                                     {
    // Use QMaps to order the keys
    QMap<int, QMap<int, QString> > ordered;
    QHashIterator<QString, Key> i(*this);
    while(i.hasNext()){
        i.next();
        const Key& key = i.value();
        ordered[key.y][key.x] = i.key();
    }
    // Merge them into a single list
    QStringList result;
    QMapIterator<int, QMap<int, QString> > y(ordered);
    while(y.hasNext()){
        y.next();
        QMapIterator<int, QString> x(y.value());
        while(x.hasNext()){
            x.next();
            result << x.value();
        }
    }
    return result;
}
bool KeyMap::contains (const QString &name) const [inline]
Definition at line 128 of file keymap.h.
References _keys.
Referenced by friendlyName(), and KbAnimWidget::on_keyButton_clicked().
{ return _keys.contains(name); }
uint KeyMap::count () const [inline]
Definition at line 119 of file keymap.h.
References _keys.
Referenced by KeyWidget::map(), KbBindWidget::on_copyButton_clicked(), and KbBindWidget::on_resetButton_clicked().
{ return _keys.count(); }
QString KeyMap::friendlyName (const QString &key, Layoutlayout = US) [static]
Definition at line 641 of file keymap.cpp.
References contains(), K95, KeyMap(), M65, map(), SCIMITAR, and STRAFE.
Referenced by KeyAction::friendlyName(), and RebindWidget::RebindWidget().
                                                             {
    // Try K95 map first
    // FIXME: This is an odd function and probably should be refactored
    // it would probably be best to remove the friendly names from the maps and have a completely separate name->friendlyName store
    KeyMap map(K95, layout);
    if(map.contains(key))
        return map[key].friendlyName();
    // The only key missing from it should be Fn, which is found on STRAFE
    map = KeyMap(STRAFE, layout);
    if(map.contains(key))
        return map[key].friendlyName();
    // Additionally, there are a handful of keys not present on any physical keyboard, but we need names for them
    if(key == "f13" || key == "f14" || key == "f15" || key == "f16" || key == "f17" || key == "f18" || key == "f19" || key == "f20")
        return key.toUpper();
    else if(key == "lightup")
        return "Screen Brightness Up";
    else if(key == "lightdn")
        return "Screen Brightness Down";
    else if(key == "eject" || key == "power")
        return key[0].toUpper() + key.mid(1); // capitalize first letter
    // All other names are found on mice
    map = KeyMap(SCIMITAR, layout);
    if(map.contains(key))
        return map[key].friendlyName();
    map = KeyMap(M65, layout);
    if(map.contains(key))
        return map[key].friendlyName();
    // Not found at all
    return "";
}
KeyMap KeyMap::fromName (const QString &name) [static]
Definition at line 565 of file keymap.cpp.
References getLayout(), getModel(), and KeyMap().
Referenced by KbBind::load(), and KbLight::load().
                                          {
    QStringList list = name.trimmed().split(" ");
    if(list.length() != 2)
        return KeyMap();
    return KeyMap(getModel(list[0]), getLayout(list[1]));
}
QString KeyMap::fromStorage (const QString &storage) [inline]
Definition at line 136 of file keymap.h.
Referenced by KbAnim::KbAnim(), KbBind::load(), and KbLight::load().
{ QHashIterator<QString, Key> i(*this); while(i.hasNext()) { i.next(); const char* s = i.value().storageName(); if(s == storage) return i.value().name; } return storage; }
KeyMap::Layout KeyMap::getLayout (const QString &name) [static]
Definition at line 409 of file keymap.cpp.
References DE, DK, ES, EU, EU_DVORAK, FR, GB, GB_DVORAK, IT, MX, NO, NO_LAYOUT, PL, SE, US, and US_DVORAK.
Referenced by fromName(), SettingsWidget::on_layoutBox_activated(), SettingsWidget::SettingsWidget(), and strLayout().
                                                 {
    QString lower = name.toLower();
    if(lower == "dk")
        return DK;
    if(lower == "eu")
        return EU;
    if(lower == "eu_dvorak")
        return EU_DVORAK;
    if(lower == "gb_dvorak")
        return GB_DVORAK;
    if(lower == "us")
        return US;
    if(lower == "us_dvorak")
        return US_DVORAK;
    if(lower == "fr")
        return FR;
    if(lower == "de")
        return DE;
    if(lower == "it")
        return IT;
    if(lower == "no")
        return NO;
    if(lower == "pl")
        return PL;
    if(lower == "mx")
        return MX;
    if(lower == "es")
        return ES;
    if(lower == "se")
        return SE;
    if(lower == "gb")
        return GB;
    return NO_LAYOUT;
}
QString KeyMap::getLayout (KeyMap::Layoutlayout) [static]
Definition at line 444 of file keymap.cpp.
References DE, DK, ES, EU, EU_DVORAK, FR, GB, GB_DVORAK, IT, MX, NO, PL, SE, US, and US_DVORAK.
                                            {
    switch(layout){
    case DK:
        return "dk";
    case EU:
        return "eu";
    case EU_DVORAK:
        return "eu_dvorak";
    case GB:
        return "gb";
    case GB_DVORAK:
        return "gb_dvorak";
    case US:
        return "us";
    case US_DVORAK:
        return "us_dvorak";
    case FR:
        return "fr";
    case DE:
        return "de";
    case IT:
        return "it";
    case NO:
        return "no";
    case PL:
        return "pl";
    case MX:
        return "mx";
    case ES:
        return "es";
    case SE:
        return "se";
    default:
        return "";
    }
}
KeyMap::Model KeyMap::getModel (const shortvendor, const shortmyProduct) [static]
Parameters:
vendor Corsair's vendor ID V_CORSAIR - just to be sure...
myProduct the productID of your USB device
Returns:
the corresponding KeyMap::Model if the v/p-combination could be found, NO_MODEL else.
Definition at line 504 of file keymap.cpp.
References firmwareSpecial::model, NO_MODEL, specials, and V_CORSAIR.
Referenced by fromName(), Kb::Kb(), and strModel().
                                                                     {
    if (vendor != V_CORSAIR) {
        qCritical() << "Wrong vendor number" << vendor << "with product number" << myProduct;
        return NO_MODEL;
    }
    for (uint i = 0; i < sizeof(specials)/sizeof(struct firmwareSpecial) ; i++) {
        if (specials[i].product == myProduct) return specials[i].model;
    }
    return NO_MODEL;
}
KeyMap::Model KeyMap::getModel (const QString &name) [static]
Parameters:
name QString with the name from 'features' file
Returns:
the corresponding KeyMap::Model or NO_MODEL (-1), if name does not exist.
Definition at line 520 of file keymap.cpp.
References K65, K70, K95, M65, NO_MODEL, SABRE, SCIMITAR, and STRAFE.
                                               {
    QString lower = name.toLower();
    if(lower == "k65")
        return K65;
    if(lower == "k70")
        return K70;
    if(lower == "k95")
        return K95;
    if(lower == "strafe")
        return STRAFE;
    if(lower == "m65")
        return M65;
    if(lower == "sabre")
        return SABRE;
    if(lower == "scimitar")
        return SCIMITAR;
    return NO_MODEL;
}
QString KeyMap::getModel (KeyMap::Modelmodel) [static]
Parameters:
model KeyMap::Model
Returns:
QString with model name or '' if model exceeds boundaries
Definition at line 544 of file keymap.cpp.
References K65, K70, K95, M65, SABRE, SCIMITAR, and STRAFE.
                                         {
    switch(model){
    case K65:
        return "k65";
    case K70:
        return "k70";
    case K95:
        return "k95";
    case STRAFE:
        return "strafe";
    case M65:
        return "m65";
    case SABRE:
        return "sabre";
    case SCIMITAR:
        return "scimitar";
    default:
        return "";
    }
}
uint KeyMap::height () const [inline]
Definition at line 123 of file keymap.h.
References keyHeight.
Referenced by KeyWidget::drawInfo(), and KeyWidget::map().
{ return keyHeight; }
static bool KeyMap::isISO (Layoutlayout) [inline], [static]
Definition at line 87 of file keymap.h.
References PL, US, and US_DVORAK.
Referenced by KbBind::isISO(), and RebindWidget::setBind().
{ return layout != US && layout != US_DVORAK && layout != PL; }
bool KeyMap::isISO () const [inline]
Definition at line 88 of file keymap.h.
References isISO(), and keyLayout.
Referenced by getMap(), isISO(), Kb::Kb(), and Kb::updateLayout().
{ return isISO(keyLayout); }
static bool KeyMap::isKeyboard (Modelmodel) [inline], [static]
Definition at line 93 of file keymap.h.
References isMouse(), and NO_MODEL.
Referenced by KbBind::isKeyboard().
{ return !isMouse(model) && model != NO_MODEL; }
bool KeyMap::isKeyboard () const [inline]
Definition at line 94 of file keymap.h.
References isKeyboard(), and keyModel.
Referenced by Kb::isKeyboard(), and isKeyboard().
{ return isKeyboard(keyModel); }
static bool KeyMap::isMouse (Modelmodel) [inline], [static]
Definition at line 95 of file keymap.h.
References M65, SABRE, and SCIMITAR.
Referenced by KbBind::isMouse(), KeyWidget::map(), KbLightWidget::newSelection(), and KeyWidget::paintEvent().
{ return model == M65 || model == SABRE || model == SCIMITAR; }
bool KeyMap::isMouse () const [inline]
Definition at line 96 of file keymap.h.
References isMouse(), and keyModel.
Referenced by isKeyboard(), Kb::isMouse(), isMouse(), and KeyWidget::paintEvent().
{ return isMouse(keyModel); }
Key KeyMap::key (const QString &name) const [inline]
Definition at line 126 of file keymap.h.
References _keys.
Referenced by AnimScript::begin(), AnimScript::keypress(), KbBind::noAction(), operator[](), KbBind::setAction(), and toStorage().
{ Key empty = {0,0,0,0,0,0,0,0,0}; return _keys.value(name, empty); }
QStringList KeyMap::keys () const [inline]
Definition at line 132 of file keymap.h.
References _keys.
Referenced by KeyWidget::mouseReleaseEvent(), KbBindWidget::on_copyButton_clicked(), KbBindWidget::on_resetButton_clicked(), KeyWidget::setAnimation(), KeyWidget::setSelection(), and KbBindWidget::updateBind().
{ return _keys.keys(); }
Layout KeyMap::layout () const [inline]
Definition at line 115 of file keymap.h.
References keyLayout.
Referenced by KeyAction::friendlyName(), KeyWidget::paintEvent(), and RebindWidget::setBind().
{ return keyLayout; }
QStringList KeyMap::layoutNames () [static]
Definition at line 481 of file keymap.cpp.
Referenced by LayoutDialog::LayoutDialog(), and SettingsWidget::SettingsWidget().
                               {
    return QStringList()
            << "Danish"
            << "English (ISO/European)" << "English (ISO/European, Dvorak)"
            << "English (United Kingdom)" << "English (United Kingdom, Dvorak)"
            << "English (United States)" << "English (United States, Dvorak)"
            << "French"
            << "German"
            << "Italian"
            << "Norwegian"
            << "Polish"
            << "Spanish (Latin America)"
            << "Spanish (Spain)"
            << "Swedish";
}
KeyMap::Layout KeyMap::locale () [static]
Definition at line 377 of file keymap.cpp.
References DE, DK, ES, FR, GB, IT, MX, NO, PL, SE, and US.
Referenced by SettingsWidget::SettingsWidget().
                           {
    setlocale(LC_ALL, "");
    QString loc = setlocale(LC_CTYPE, 0);
    loc = loc.toLower().replace('_', '-');
    if(loc.startsWith("dk-"))
        return KeyMap::DK;
    else if(loc.startsWith("fr-"))
        return KeyMap::FR;
    else if(loc.startsWith("de-"))
        return KeyMap::DE;
    else if(loc.startsWith("it-"))
        return KeyMap::IT;
    else if(loc.startsWith("pl-"))
        return KeyMap::PL;
    else if(loc.startsWith("no-"))
        return KeyMap::NO;
    else if(loc.startsWith("es-es"))
        // Spain uses the ES layout
        return KeyMap::ES;
    else if(loc.startsWith("es-"))
        // Other Spanish locales use MX
        return KeyMap::MX;
    else if(loc.startsWith("se-"))
        return KeyMap::SE;
    else if(loc.startsWith("en-us") || loc.startsWith("en-au") || loc.startsWith("en-ca") || loc.startsWith("en-hk") || loc.startsWith("en-in") || loc.startsWith("en-nz") || loc.startsWith("en-ph") || loc.startsWith("en-sg") || loc.startsWith("en-za"))
        // Most English locales use US
        return KeyMap::US;
    else
        // Default to GB
        return KeyMap::GB;
}
const QHash<QString, Key>& KeyMap::map () const [inline]
Definition at line 130 of file keymap.h.
References _keys.
Referenced by friendlyName().
{ return _keys; }
Model KeyMap::model () const [inline]
Definition at line 114 of file keymap.h.
References keyModel.
Referenced by KeyWidget::mouseMoveEvent(), KeyWidget::paintEvent(), and KPerfWidget::setPerf().
{ return keyModel; }
int KeyMap::modelHeight (Modelmodel) [static], [private]
Definition at line 591 of file keymap.cpp.
References K65, K70, K95, K95_HEIGHT, M65, M65_HEIGHT, SABRE, SCIMITAR, and STRAFE.
                                  {
    switch(model){
    case K65:
    case K70:
    case K95:
    case STRAFE:
        return K95_HEIGHT;
    case M65:
    case SABRE:
    case SCIMITAR:
        return M65_HEIGHT;
    default:
        return 0;
    }
}
int KeyMap::modelWidth (Modelmodel) [static], [private]
Definition at line 572 of file keymap.cpp.
References K65, K65_WIDTH, K70, K70_WIDTH, K95, K95_WIDTH, KSTRAFE_WIDTH, M65, M65_WIDTH, SABRE, SCIMITAR, and STRAFE.
                                 {
    switch(model){
    case K65:
        return K65_WIDTH;
    case K70:
        return K70_WIDTH;
    case K95:
        return K95_WIDTH;
    case STRAFE:
        return KSTRAFE_WIDTH;
    case M65:
    case SABRE:
    case SCIMITAR:
        return M65_WIDTH;
    default:
        return 0;
    }
}
QString KeyMap::name () const [inline]
Definition at line 116 of file keymap.h.
References strLayout(), and strModel().
Referenced by KbBind::save(), KbLight::save(), and toStorage().
{ return (strModel() + " " + strLayout()).toUpper(); }
KeyMap::operator const QHash< QString, Key > & () const [inline]
Definition at line 131 of file keymap.h.
References _keys.
{ return _keys; }
Key KeyMap::operator[] (const QString &name) const [inline]
Definition at line 127 of file keymap.h.
References key().
{ return key(name); }
QList<Key> KeyMap::positions () const [inline]
Definition at line 133 of file keymap.h.
References _keys.
Referenced by ColorMap::init(), and KeyWidget::selectAll().
{ return _keys.values(); }
QString KeyMap::strLayout () const [inline]
Definition at line 106 of file keymap.h.
References getLayout(), and keyLayout.
Referenced by name().
{ return getLayout(keyLayout); }
QString KeyMap::strModel () const [inline]
Definition at line 111 of file keymap.h.
References getModel(), and keyModel.
Referenced by name().
{ return getModel(keyModel); }
QString KeyMap::toStorage (const QString &name) [inline]
Definition at line 135 of file keymap.h.
References key(), name(), and Key::storageName().
{ const char* storage = key(name).storageName(); if(!storage) return name; return storage; }
uint KeyMap::width () const [inline]
Definition at line 121 of file keymap.h.
References keyWidth.
Referenced by KeyWidget::drawInfo(), and KeyWidget::map().
{ return keyWidth; }
Field Documentation
QHash<QString, Key> KeyMap::_keys [private]
Definition at line 148 of file keymap.h.
Referenced by contains(), count(), key(), keys(), map(), operator const QHash< QString, Key > &(), and positions().
short KeyMap::keyHeight [private]
Definition at line 149 of file keymap.h.
Referenced by height().
Layout KeyMap::keyLayout [private]
Definition at line 151 of file keymap.h.
Referenced by isISO(), layout(), and strLayout().
Model KeyMap::keyModel [private]
Definition at line 150 of file keymap.h.
Referenced by isKeyboard(), isMouse(), model(), and strModel().
short KeyMap::keyWidth [private]
Definition at line 149 of file keymap.h.
Referenced by width().
Author
Generated automatically by Doxygen for ckb-next from the source code.