.TH "src/ckb/keywidget.h" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/keywidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QBitArray>\fP
.br
\fC#include <QMouseEvent>\fP
.br
\fC#include <QPaintEvent>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include 'keymap\&.h'\fP
.br
\fC#include 'colormap\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBKeyWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
