.TH "LayoutDialog" 3 "Mon May 22 2017" "Version beta-v0.2.7 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayoutDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/layoutdialog\&.h>\fP
.PP
Inherits \fBQDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayoutDialog\fP (\fBQWidget\fP *parent=0)"
.br
.ti -1c
.RI "\fB~LayoutDialog\fP ()"
.br
.ti -1c
.RI "\fBKeyMap::Layout\fP \fBselected\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUi::LayoutDialog\fP * \fBui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file layoutdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LayoutDialog::LayoutDialog (\fBQWidget\fP *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 5 of file layoutdialog\&.cpp\&.
.PP
References Ui_LayoutDialog::comboBox, Kb::layout(), KeyMap::layoutNames(), Ui_LayoutDialog::setupUi(), and ui\&.
.PP
.nf
5                                           :
6     QDialog(parent),
7     ui(new Ui::LayoutDialog) {
8     ui->setupUi(this);
9     // Populate layout list
10     ui->comboBox->addItems(KeyMap::layoutNames());
11     ui->comboBox->setCurrentIndex((int)Kb::layout());
12 }
.fi
.SS "LayoutDialog::~LayoutDialog ()"

.PP
Definition at line 14 of file layoutdialog\&.cpp\&.
.PP
References ui\&.
.PP
.nf
14                            {
15     delete ui;
16 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBKeyMap::Layout\fP LayoutDialog::selected () const"

.PP
Definition at line 18 of file layoutdialog\&.cpp\&.
.PP
References Ui_LayoutDialog::comboBox, and ui\&.
.PP
Referenced by SettingsWidget::showLayoutDialog()\&.
.PP
.nf
18                                           {
19     return (KeyMap::Layout)ui->comboBox->currentIndex();
20 }
.fi
.SH "Field Documentation"
.PP 
.SS "\fBUi::LayoutDialog\fP* LayoutDialog::ui\fC [private]\fP"

.PP
Definition at line 24 of file layoutdialog\&.h\&.
.PP
Referenced by LayoutDialog(), selected(), and ~LayoutDialog()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
