LayoutDialog
NAME
LayoutDialog -
SYNOPSIS
#include <src/ckb/layoutdialog.h>
Inherits QDialog.
Public Member Functions
LayoutDialog (QWidget *parent=0)
~LayoutDialog ()
KeyMap::Layout selected () const
Private Attributes
Ui::LayoutDialog * ui
Detailed Description
Definition at line 13 of file layoutdialog.h.
Constructor & Destructor Documentation
LayoutDialog::LayoutDialog (QWidget *parent = 0) [explicit]
Definition at line 5 of file layoutdialog.cpp.
References Ui_LayoutDialog::comboBox, Kb::layout(), KeyMap::layoutNames(), Ui_LayoutDialog::setupUi(), and ui.
                                          :
    QDialog(parent),
    ui(new Ui::LayoutDialog) {
    ui->setupUi(this);
    // Populate layout list
    ui->comboBox->addItems(KeyMap::layoutNames());
    ui->comboBox->setCurrentIndex((int)Kb::layout());
}
LayoutDialog::~LayoutDialog ()
Definition at line 14 of file layoutdialog.cpp.
References ui.
                           {
    delete ui;
}
Member Function Documentation
KeyMap::Layout LayoutDialog::selected () const
Definition at line 18 of file layoutdialog.cpp.
References Ui_LayoutDialog::comboBox, and ui.
Referenced by SettingsWidget::showLayoutDialog().
                                          {
    return (KeyMap::Layout)ui->comboBox->currentIndex();
}
Field Documentation
Ui::LayoutDialog* LayoutDialog::ui [private]
Definition at line 24 of file layoutdialog.h.
Referenced by LayoutDialog(), selected(), and ~LayoutDialog().
Author
Generated automatically by Doxygen for ckb-next from the source code.