.TH "src/ckb/layoutdialog.cpp" 3 "Mon May 22 2017" "Version beta-v0.2.7 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/layoutdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'layoutdialog\&.h'\fP
.br
\fC#include 'kb\&.h'\fP
.br
\fC#include 'ui_layoutdialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
