.TH "MacroReaderThread" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MacroReaderThread \- 
.PP
The \fBMacroReaderThread\fP class is responsible for reading Macro \fBKey\fP Values\&. It is created as a separate thread (worker thread) for reading macro commands from an fresh opened notify channel\&. Standard notify channel for macro definitions is number 2\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/macroreader\&.h>\fP
.PP
Inherits \fBQThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMacroReaderThread\fP (int macNum, QString macPath, QPlainTextEdit *macBox, QPlainTextEdit *macText)"
.br
.RI "\fI\fBMacroReaderThread\fP saves the four params to local vars with similar varNames\&. \fP"
.ti -1c
.RI "void \fBrun\fP () Q_DECL_OVERRIDE"
.br
.RI "\fIrun is the notification reader main loop\&. \fP"
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBreadMacro\fP (QString line)"
.br
.RI "\fIreadMacro is called for each line received by the worker thread\&. The method ist called via signal (metaObject) from the worker thread, which reads the keyboard input\&. Just display the key code in the macroBox Widget without he trailing newline and reposition the cursor in the macro pane\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBmacroNumber\fP"
.br
.RI "\fImacroNumber Filenames of nofity channels have the structure <input-device-path>/ckb1/notify<number> First part is hold in macroPath, the number is hold in macroNumber\&. macroNumber may range from 0 to 9\&. \fP"
.ti -1c
.RI "QString \fBmacroPath\fP"
.br
.RI "\fImacroPath holds the path for the notify channel \fP"
.ti -1c
.RI "QPlainTextEdit * \fBmacroBox\fP"
.br
.RI "\fImacroBox will receive the Macro \fBKey\fP Values sent from the keyboard while defining a new macro\&. \fP"
.ti -1c
.RI "QPlainTextEdit * \fBmacroText\fP"
.br
.RI "\fImacroText is the other textpane used in the UI while typing new macros\&. That variable is used for setting the focus to that textpane and to set the cursor at EOT\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
While the worker Thread gets input from the keyboard, the lines are sent via signalling (metaobject) to run a member function in the context of the Qt UI manager\&.
.PP
When the notify channel is closed (that's normally done by pressing 'Stop'-Button in the UI), the worker thread closes the channelFile and leaves\&. 
.PP
\fBSee Also:\fP
.RS 4
\fBMacroReaderThread()\fP, ~MacroReaderThread(), readMaco(), \fBrun()\fP 
.RE
.PP

.PP
Definition at line 22 of file macroreader\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MacroReaderThread::MacroReaderThread (intmacNum, QStringmacPath, QPlainTextEdit *macBox, QPlainTextEdit *macText)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fImacNum\fP 
.br
\fImacPath\fP 
.br
\fImacBox\fP 
.br
\fImacText\fP 
.RE
.PP

.PP
Definition at line 55 of file macroreader\&.h\&.
.PP
References macroBox, macroNumber, macroPath, and macroText\&.
.PP
.nf
55                                                                                                     {
56         macroNumber = macNum;
57         macroPath = macPath;
58         macroBox = macBox;
59         macroText = macText;
60     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void MacroReaderThread::readMacro (QStringline)\fC [private]\fP, \fC [slot]\fP"
This is used, because the worker thread shouldn't get access to the UI elements (and normally has none, because the pointers macroBox and macroText remain on the stack)\&. That mechanism guarantees, that the UI does not freeze if it happens something magic to the reading function\&.
.PP
\fBParameters:\fP
.RS 4
\fIline\fP holds the line just got from keyboard 
.RE
.PP
We want to see the keys as they appear in the macroText Widget\&.
.PP
Because it is possible to change the Focus via keyboard, we must set the focus on each call\&. 
.PP
Definition at line 27 of file macroreader\&.cpp\&.
.PP
References macroBox, and macroText\&.
.PP
.nf
27                                               {
32     macroText->setFocus();
33     QTextCursor c = macroText->textCursor();
34     c\&.setPosition(macroText->toPlainText()\&.length());
35     macroText->setTextCursor(c);
36     macroBox->appendPlainText(line\&.left(line\&.size()-1));
37 }
.fi
.SS "void MacroReaderThread::run ()"
\fBMacroReaderThread::run\fP is the standard main function for a thread\&. Tries to open a file <macroPath><macroNumber> several times (in this case, it should be possible the first time (the code was recycled from \fBkb\&.cpp\fP)\&.
.PP
While the file is open, read lines an signal them via metaObject() to the main thread\&. When the file is closed by the sender, close it as reader and terminate\&. 
.PP
Definition at line 47 of file macroreader\&.cpp\&.
.PP
References macroBox, macroNumber, macroPath, and macroText\&.
.PP
.nf
47                             {
48     qDebug() << "MacroReader::run() started with" << macroNumber << "and" << macroPath << "and" << macroBox << "and" << macroText;
49 
50     QFile macroFile(macroPath);
51     // Wait a small amount of time for the node to open (100ms) (code reused from kb\&.cpp)
52     QThread::usleep(100000);
53     if(!macroFile\&.open(QIODevice::ReadOnly)){
54         // If it's still not open, try again before giving up (1s at a time, 10s total)
55         QThread::usleep(900000);
56         for(int i = 1; i < 10; i++){
57             if(macroFile\&.open(QIODevice::ReadOnly))
58                 break;
59             QThread::sleep(1);
60         }
61         if(!macroFile\&.isOpen()) {
62             qDebug() << QString("unable to open macroFile (%1)")\&.arg(macroPath);
63             return;
64         }
65     }
66     // Read data from notification node macroPath
67     // Count time between lines read from the interface
68     QByteArray line;
69     timeval t;
70     gettimeofday(&t, NULL);
71     double tstart = t\&.tv_sec+(t\&.tv_usec/1000000\&.0);
72     bool firstline = true;
73 
74     while(macroFile\&.isOpen() && (line = macroFile\&.readLine())\&.length() > 0){
75         QString text = QString::fromUtf8(line);
76         gettimeofday(&t, NULL);
77         double tnow = t\&.tv_sec+(t\&.tv_usec/1000000\&.0);
78 
79         // in the first line, there is only a delay "before start"\&. Don't use it\&.
80         if (!firstline) {
81             text\&.prepend ("\n");
82             text\&.prepend (QString::number ((tnow - tstart) * 1000000\&.0, 'f', 0));
83             text\&.prepend ("=");
84         } else firstline = false;
85         tstart = tnow;
86 
87         metaObject()->invokeMethod(this, "readMacro", Qt::QueuedConnection, Q_ARG(QString, text));
88     }
89     qDebug() << "MacroReader::run() ends\&.";
90     macroFile\&.close();
91     QThread::exit ();
92 }
.fi
.SH "Field Documentation"
.PP 
.SS "QPlainTextEdit* MacroReaderThread::macroBox\fC [private]\fP"

.PP
Definition at line 40 of file macroreader\&.h\&.
.PP
Referenced by MacroReaderThread(), readMacro(), and run()\&.
.SS "int MacroReaderThread::macroNumber\fC [private]\fP"

.PP
Definition at line 31 of file macroreader\&.h\&.
.PP
Referenced by MacroReaderThread(), and run()\&.
.SS "QString MacroReaderThread::macroPath\fC [private]\fP"

.PP
\fBSee Also:\fP
.RS 4
\fBmacroNumber\fP 
.RE
.PP

.PP
Definition at line 36 of file macroreader\&.h\&.
.PP
Referenced by MacroReaderThread(), and run()\&.
.SS "QPlainTextEdit* MacroReaderThread::macroText\fC [private]\fP"

.PP
Definition at line 45 of file macroreader\&.h\&.
.PP
Referenced by MacroReaderThread(), readMacro(), and run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
