.TH "md_ROADMAP" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_ROADMAP \- cbk Improvements Roadmap 

.SS "Short term plan "
.PP
.IP "\(bu" 2
merge existing PR submitted to original ckb repo
.IP "\(bu" 2
Contact other developers interested in collaboration on a new and improved version of ckb
.IP "\(bu" 2
Figure out the issues relating to MacOS Sierra and other version
.IP "\(bu" 2
Device support:
.IP "  \(bu" 4
Determine which will need support other than just USB id additions
.PP

.IP "\(bu" 2
Address existing bugs\&. Not help requests\&. 
.PP

