.TH "src/ckb/release/moc_keyaction.cpp" 3 "Sun Jun 4 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/release/moc_keyaction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./keyaction\&.h'\fP
.br
\fC#include <QtCore/qbytearray\&.h>\fP
.br
\fC#include <QtCore/qmetatype\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqt_meta_stringdata_KeyAction_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx, ofs, len)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const 
.br
\fBqt_meta_stringdata_KeyAction_t\fP \fBqt_meta_stringdata_KeyAction\fP"
.br
.ti -1c
.RI "static const uint \fBqt_meta_data_KeyAction\fP []"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct qt_meta_stringdata_KeyAction_t"
.PP 
Definition at line 21 of file moc_keyaction\&.cpp\&.
.PP
\fBData Fields:\fP
.RS 4
QByteArrayData \fIdata[1]\fP 
.br
.PP
char \fIstringdata0[10]\fP 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_KeyAction_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
.fi
.PP
Definition at line 25 of file moc_keyaction\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const uint qt_meta_data_KeyAction[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {

 
       7,       
       0,       
       0,    0, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,       
       0,       

       0        
}
.fi
.PP
Definition at line 39 of file moc_keyaction\&.cpp\&.
.SS "const \fBqt_meta_stringdata_KeyAction_t\fP qt_meta_stringdata_KeyAction\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET( 9 ,   qptrdiff(offsetof(qt_meta_stringdata_KeyAction_t, stringdata0) +  0    -  0  * sizeof(QByteArrayData))   ) 

    },
    "KeyAction"
}
.fi
.PP
Definition at line 30 of file moc_keyaction\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
