src/ckb/mperfwidget.cpp
NAME
src/ckb/mperfwidget.cpp -
SYNOPSIS
#include 'mperfwidget.h'
#include 'ui_mperfwidget.h'
#include 'modeselectdialog.h'
#include <cmath>
Macros
#define SET_START if(isSetting) return; isSetting = true
#define SET_END isSetting = false
Functions
int dpiExp (int value, int min, int max)
int dpiLog (int value, int min, int max)
int dpiRound (int value)
Variables
static const QString xyLinkPath = 'UI/DPI/UnlinkXY'
static const double DPI_BASE = (double)KbPerf::DPI_MAX / (double)KbPerf::DPI_MIN
Macro Definition Documentation
#define SET_END isSetting = false
Definition at line 126 of file mperfwidget.cpp.
Referenced by MPerfWidget::boxXChanged(), MPerfWidget::boxYChanged(), MPerfWidget::sliderXMoved(), and MPerfWidget::sliderYMoved().
#define SET_START if(isSetting) return; isSetting = true
Definition at line 125 of file mperfwidget.cpp.
Referenced by MPerfWidget::boxXChanged(), MPerfWidget::boxYChanged(), MPerfWidget::sliderXMoved(), and MPerfWidget::sliderYMoved().
Function Documentation
int dpiExp (intvalue, intmin, intmax) [inline]
Definition at line 105 of file mperfwidget.cpp.
References DPI_BASE, KbPerf::DPI_MIN, and min().
Referenced by MPerfWidget::sliderXMoved(), and MPerfWidget::sliderYMoved().
                                              {
    double val = (value - min) / (double)(max - min);
    val = pow(DPI_BASE, val);
    return round(KbPerf::DPI_MIN * val);
}
int dpiLog (intvalue, intmin, intmax) [inline]
Definition at line 111 of file mperfwidget.cpp.
References DPI_BASE, and KbPerf::DPI_MIN.
Referenced by MPerfWidget::boxXChanged(), and MPerfWidget::boxYChanged().
                                              {
    double val = value / (double)KbPerf::DPI_MIN;
    val = log(val) / log(DPI_BASE);
    return round(val * (max - min) + min);
}
int dpiRound (intvalue) [inline]
Definition at line 117 of file mperfwidget.cpp.
Referenced by MPerfWidget::sliderXMoved(), and MPerfWidget::sliderYMoved().
                              {
    if(value > 1000)
        return round(value / 100.) * 100;
    else
        return round(value / 50.) * 50;
}
Variable Documentation
const double DPI_BASE = (double)KbPerf::DPI_MAX / (double)KbPerf::DPI_MIN [static]
Definition at line 103 of file mperfwidget.cpp.
Referenced by dpiExp(), and dpiLog().
const QString xyLinkPath = 'UI/DPI/UnlinkXY' [static]
Definition at line 6 of file mperfwidget.cpp.
Referenced by MPerfWidget::on_xyBox_clicked().
Author
Generated automatically by Doxygen for ckb-next from the source code.