src/ckb/release/qrc_text.cpp
NAME
src/ckb/release/qrc_text.cpp -
SYNOPSIS
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int qInitResources_text ()
int qCleanupResources_text ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
#define QT_RCC_MANGLE_NAMESPACE(name) name
Definition at line 350 of file qrc_text.cpp.
#define QT_RCC_PREPEND_NAMESPACE(name) name
Definition at line 349 of file qrc_text.cpp.
Referenced by qCleanupResources_text(), and qInitResources_text().
Function Documentation
int qCleanupResources_text ()
Definition at line 374 of file qrc_text.cpp.
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
{
    QT_RCC_PREPEND_NAMESPACE(qUnregisterResourceData)
       (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
int qInitResources_text ()
Definition at line 366 of file qrc_text.cpp.
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
{
    QT_RCC_PREPEND_NAMESPACE(qRegisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qInitResources_text().
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qCleanupResources_text().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 9 of file qrc_text.cpp.
Referenced by qCleanupResources_text(), and qInitResources_text().
const unsigned char qt_resource_name[] [static]
Initial value:
= {
  
  0x0,0x3,
  0x0,0x0,0x7b,0xf4,
  0x0,0x74,
  0x0,0x78,0x0,0x74,
    
  0x0,0xb,
  0xa,0x1e,0x1,0xe0,
  0x0,0x63,
  0x0,0x6b,0x0,0x62,0x0,0x2e,0x0,0x64,0x0,0x65,0x0,0x73,0x0,0x6b,0x0,0x74,0x0,0x6f,0x0,0x70,
    
  0x0,0x10,
  0xe,0xac,0xaf,0x46,
  0x0,0x64,
  0x0,0x65,0x0,0x6d,0x0,0x6f,0x0,0x70,0x0,0x72,0x0,0x6f,0x0,0x66,0x0,0x69,0x0,0x6c,0x0,0x65,0x0,0x2e,0x0,0x63,0x0,0x6f,0x0,0x6e,0x0,0x66,
    
  0x0,0x11,
  0x0,0xd4,0x25,0xa4,
  0x0,0x63,
  0x0,0x6f,0x0,0x6d,0x0,0x2e,0x0,0x63,0x0,0x6b,0x0,0x62,0x0,0x2e,0x0,0x63,0x0,0x6b,0x0,0x62,0x0,0x2e,0x0,0x70,0x0,0x6c,0x0,0x69,0x0,0x73,0x0,0x74,
  
  
}
Definition at line 302 of file qrc_text.cpp.
Referenced by qCleanupResources_text(), and qInitResources_text().
const unsigned char qt_resource_struct[] [static]
Initial value:
= {
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x2,
  
  0x0,0x0,0x0,0x4e,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0xf,0x74,
  
  0x0,0x0,0x0,0xc,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
  
  0x0,0x0,0x0,0x28,0x0,0x1,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0xc6,
}
Definition at line 327 of file qrc_text.cpp.
Referenced by qCleanupResources_text(), and qInitResources_text().
Author
Generated automatically by Doxygen for ckb-next from the source code.