.TH "src/ckb/quazip/quagzipfile.cpp" 3 "Thu May 25 2017" "Version v0.2.8 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quagzipfile.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFile>\fP
.br
\fC#include 'quagzipfile\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
