.TH "src/ckb/quazip/quazipnewinfo.h" 3 "Sat May 27 2017" "Version v0.2.8 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quazipnewinfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDateTime>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QString>\fP
.br
\fC#include 'quazip_global\&.h'\fP
.br
\fC#include 'quazipfileinfo\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBQuaZipNewInfo\fP"
.br
.RI "\fIInformation about a file to be created\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
