QuaZIODevice
NAME
QuaZIODevice -
A class to compress/decompress QIODevice.
SYNOPSIS
#include <src/ckb/quazip/quaziodevice.h>
Inherits QIODevice.
Public Member Functions
QuaZIODevice (QIODevice *io, QObject *parent=NULL)
Constructor.
~QuaZIODevice ()
Destructor.
virtual bool flush ()
Flushes data waiting to be written.
virtual bool open (QIODevice::OpenMode mode)
Opens the device.
virtual void close ()
Closes this device, but not the underlying one.
QIODevice * getIoDevice () const
Returns the underlying device.
virtual bool isSequential () const
Returns true.
Protected Member Functions
virtual qint64 readData (char *data, qint64 maxSize)
Implementation of QIODevice::readData().
virtual qint64 writeData (const char *data, qint64 maxSize)
Implementation of QIODevice::writeData().
Private Attributes
QuaZIODevicePrivate * d
Detailed Description
This class can be used to compress any data written to QIODevice or decompress it back. Compressing data sent over a QTcpSocket is a good example.
Definition at line 41 of file quaziodevice.h.
Constructor & Destructor Documentation
QuaZIODevice::QuaZIODevice (QIODevice *io, QObject *parent = NULL)
Parameters:
io The QIODevice to read/write.
parent The parent object, as per QObject logic.
Definition at line 123 of file quaziodevice.cpp.
                                                        :
    QIODevice(parent),
    d(new QuaZIODevicePrivate(io))
{
  connect(io, SIGNAL(readyRead()), SIGNAL(readyRead()));
}
QuaZIODevice::~QuaZIODevice ()
Definition at line 130 of file quaziodevice.cpp.
References close(), and d.
{
    if (isOpen())
        close();
    delete d;
}
Member Function Documentation
void QuaZIODevice::close () [virtual]
The underlying QIODevice is not closed in case you want to write something else to it.
Definition at line 169 of file quaziodevice.cpp.
References d, and flush().
Referenced by ~QuaZIODevice().
{
    if ((openMode() & QIODevice::ReadOnly) != 0) {
        if (inflateEnd(&d->zins) != Z_OK) {
            setErrorString(d->zins.msg);
        }
    }
    if ((openMode() & QIODevice::WriteOnly) != 0) {
        flush();
        if (deflateEnd(&d->zouts) != Z_OK) {
            setErrorString(d->zouts.msg);
        }
    }
    QIODevice::close();
}
bool QuaZIODevice::flush () [virtual]
Unfortunately, as QIODevice doesn't support flush() by itself, the only thing this method does is write the compressed data into the device using Z_SYNC_FLUSH mode. If you need the compressed data to actually be flushed from the buffer of the underlying QIODevice, you need to call its flush() method as well, providing it supports it (like QTcpSocket does). Example:
QuaZIODevice dev(&sock);
dev.open(QIODevice::Write);
dev.write(yourDataGoesHere);
dev.flush();
sock->flush(); // this actually sends data to network
This may change in the future versions of QuaZIP by implementing an ugly hack: trying to cast the QIODevice using qobject_cast to known flush()-supporting subclasses, and calling flush if the resulting pointer is not zero.
Definition at line 281 of file quaziodevice.cpp.
References d, and QUAZIO_OUTBUFSIZE.
Referenced by close().
{
    QString error;
    if (d->doFlush(error) < 0) {
        setErrorString(error);
        return false;
    }
    // can't flush buffer, some data is still waiting
    if (d->outBufPos < d->outBufSize)
        return true;
    Bytef c = 0;
    d->zouts.next_in = &c; // fake input buffer
    d->zouts.avail_in = 0; // of zero size
    do {
        d->zouts.next_out = (Bytef *) d->outBuf;
        d->zouts.avail_out = QUAZIO_OUTBUFSIZE;
        switch (deflate(&d->zouts, Z_SYNC_FLUSH)) {
        case Z_OK:
          d->outBufSize = (char *) d->zouts.next_out - d->outBuf;
          if (d->doFlush(error) < 0) {
              setErrorString(error);
              return false;
          }
          if (d->outBufPos < d->outBufSize)
              return true;
          break;
        case Z_BUF_ERROR: // nothing to write?
          return true;
        default:
          setErrorString(QString::fromLocal8Bit(d->zouts.msg));
          return false;
        }
    } while (d->zouts.avail_out == 0);
    return true;
}
QIODevice * QuaZIODevice::getIoDevice () const
Definition at line 137 of file quaziodevice.cpp.
References d.
{
    return d->io;
}
bool QuaZIODevice::isSequential () const [virtual]
Definition at line 317 of file quaziodevice.cpp.
{
  return true;
}
bool QuaZIODevice::open (QIODevice::OpenModemode) [virtual]
Parameters:
mode Neither QIODevice::ReadWrite nor QIODevice::Append are not supported.
Definition at line 142 of file quaziodevice.cpp.
References d.
{
    if ((mode & QIODevice::Append) != 0) {
        setErrorString(trUtf8("QIODevice::Append is not supported for"
                    " QuaZIODevice"));
        return false;
    }
    if ((mode & QIODevice::ReadWrite) == QIODevice::ReadWrite) {
        setErrorString(trUtf8("QIODevice::ReadWrite is not supported for"
                    " QuaZIODevice"));
        return false;
    }
    if ((mode & QIODevice::ReadOnly) != 0) {
        if (inflateInit(&d->zins) != Z_OK) {
            setErrorString(d->zins.msg);
            return false;
        }
    }
    if ((mode & QIODevice::WriteOnly) != 0) {
        if (deflateInit(&d->zouts, Z_DEFAULT_COMPRESSION) != Z_OK) {
            setErrorString(d->zouts.msg);
            return false;
        }
    }
    return QIODevice::open(mode);
}
qint64 QuaZIODevice::readData (char *data, qint64maxSize) [protected], [virtual]
Definition at line 185 of file quaziodevice.cpp.
References d, and QUAZIO_INBUFSIZE.
{
  int read = 0;
  while (read < maxSize) {
    if (d->inBufPos == d->inBufSize) {
      d->inBufPos = 0;
      d->inBufSize = d->io->read(d->inBuf, QUAZIO_INBUFSIZE);
      if (d->inBufSize == -1) {
        d->inBufSize = 0;
        setErrorString(d->io->errorString());
        return -1;
      }
      if (d->inBufSize == 0)
        break;
    }
    while (read < maxSize && d->inBufPos < d->inBufSize) {
      d->zins.next_in = (Bytef *) (d->inBuf + d->inBufPos);
      d->zins.avail_in = d->inBufSize - d->inBufPos;
      d->zins.next_out = (Bytef *) (data + read);
      d->zins.avail_out = (uInt) (maxSize - read); // hope it's less than 2GB
      int more = 0;
      switch (inflate(&d->zins, Z_SYNC_FLUSH)) {
      case Z_OK:
        read = (char *) d->zins.next_out - data;
        d->inBufPos = (char *) d->zins.next_in - d->inBuf;
        break;
      case Z_STREAM_END:
        read = (char *) d->zins.next_out - data;
        d->inBufPos = (char *) d->zins.next_in - d->inBuf;
        return read;
      case Z_BUF_ERROR: // this should never happen, but just in case
        if (!d->zBufError) {
          qWarning("Z_BUF_ERROR detected with %d/%d in/out, weird",
              d->zins.avail_in, d->zins.avail_out);
          d->zBufError = true;
        }
        memmove(d->inBuf, d->inBuf + d->inBufPos, d->inBufSize - d->inBufPos);
        d->inBufSize -= d->inBufPos;
        d->inBufPos = 0;
        more = d->io->read(d->inBuf + d->inBufSize, QUAZIO_INBUFSIZE - d->inBufSize);
        if (more == -1) {
          setErrorString(d->io->errorString());
          return -1;
        }
        if (more == 0)
          return read;
        d->inBufSize += more;
        break;
      default:
        setErrorString(QString::fromLocal8Bit(d->zins.msg));
        return -1;
      }
    }
  }
#ifdef QUAZIP_ZIODEVICE_DEBUG_INPUT
  indebug.write(data, read);
#endif
  return read;
}
qint64 QuaZIODevice::writeData (const char *data, qint64maxSize) [protected], [virtual]
Definition at line 245 of file quaziodevice.cpp.
References d, and QUAZIO_OUTBUFSIZE.
{
  int written = 0;
  QString error;
  if (d->doFlush(error) == -1) {
    setErrorString(error);
    return -1;
  }
  while (written < maxSize) {
      // there is some data waiting in the output buffer
    if (d->outBufPos < d->outBufSize)
      return written;
    d->zouts.next_in = (Bytef *) (data + written);
    d->zouts.avail_in = (uInt) (maxSize - written); // hope it's less than 2GB
    d->zouts.next_out = (Bytef *) d->outBuf;
    d->zouts.avail_out = QUAZIO_OUTBUFSIZE;
    switch (deflate(&d->zouts, Z_NO_FLUSH)) {
    case Z_OK:
      written = (char *) d->zouts.next_in - data;
      d->outBufSize = (char *) d->zouts.next_out - d->outBuf;
      break;
    default:
      setErrorString(QString::fromLocal8Bit(d->zouts.msg));
      return -1;
    }
    if (d->doFlush(error) == -1) {
      setErrorString(error);
      return -1;
    }
  }
#ifdef QUAZIP_ZIODEVICE_DEBUG_OUTPUT
  debug.write(data, written);
#endif
  return written;
}
Field Documentation
QuaZIODevicePrivate* QuaZIODevice::d [private]
Definition at line 96 of file quaziodevice.h.
Referenced by close(), flush(), getIoDevice(), open(), readData(), writeData(), and ~QuaZIODevice().
Author
Generated automatically by Doxygen for ckb-next from the source code.