QuaZipNewInfo
NAME
QuaZipNewInfo -
Information about a file to be created.
SYNOPSIS
#include <src/ckb/quazip/quazipnewinfo.h>
Public Member Functions
QuaZipNewInfo (const QString &name)
Constructs QuaZipNewInfo instance.
QuaZipNewInfo (const QString &name, const QString &file)
Constructs QuaZipNewInfo instance.
QuaZipNewInfo (const QuaZipFileInfo &existing)
Initializes the new instance from existing file info.
QuaZipNewInfo (const QuaZipFileInfo64 &existing)
Initializes the new instance from existing file info.
void setFileDateTime (const QString &file)
Sets the file timestamp from the existing file.
void setFilePermissions (const QString &file)
Sets the file permissions from the existing file.
void setPermissions (QFile::Permissions permissions)
Sets the file permissions.
void setFileNTFSTimes (const QString &fileName)
Sets the NTFS times from an existing file.
void setFileNTFSmTime (const QDateTime &mTime, int fineTicks=0)
Sets the NTFS modification time.
void setFileNTFSaTime (const QDateTime &aTime, int fineTicks=0)
Sets the NTFS access time.
void setFileNTFScTime (const QDateTime &cTime, int fineTicks=0)
Sets the NTFS creation time.
Data Fields
QString name
File name.
QDateTime dateTime
File timestamp.
quint16 internalAttr
File internal attributes.
quint32 externalAttr
File external attributes.
QString comment
File comment.
QByteArray extraLocal
File local extra field.
QByteArray extraGlobal
File global extra field.
ulong uncompressedSize
Uncompressed file size.
Detailed Description
This structure holds information about a file to be created inside ZIP archive. At least name should be set to something correct before passing this structure to QuaZipFile::open(OpenMode,const QuaZipNewInfo&,int,int,bool).
Zip64 support of this structure is slightly limited: in the raw mode (when a pre-compressed file is written into a ZIP file as-is), it is necessary to specify the uncompressed file size and the appropriate field is 32 bit. Since the raw mode is used extremely rare, there is no real need to have a separate QuaZipNewInfo64 structure like QuaZipFileInfo64. It may be added in the future though, if there is a demand for the raw mode with zip64 archives.
Definition at line 50 of file quazipnewinfo.h.
Constructor & Destructor Documentation
QuaZipNewInfo::QuaZipNewInfo (const QString &name)
Initializes name with name, dateTime with current date and time. Attributes are initialized with zeros, comment and extra field with null values.
Definition at line 79 of file quazipnewinfo.cpp.
                                               :
  name(name), dateTime(QDateTime::currentDateTime()), internalAttr(0), externalAttr(0),
  uncompressedSize(0)
{
}
QuaZipNewInfo::QuaZipNewInfo (const QString &name, const QString &file)
Initializes name with name. Timestamp and permissions are taken from the specified file. If the file does not exists or its timestamp is inaccessible (e. g. you do not have read permission for the directory file in), uses current time and zero permissions. Other attributes are initialized with zeros, comment and extra field with null values.
See Also:
setFileDateTime()
Definition at line 85 of file quazipnewinfo.cpp.
References dateTime, and QuaZipNewInfo_setPermissions().
                                                                    :
  name(name), internalAttr(0), externalAttr(0), uncompressedSize(0)
{
  QFileInfo info(file);
  QDateTime lm = info.lastModified();
  if (!info.exists()) {
    dateTime = QDateTime::currentDateTime();
  } else {
    dateTime = lm;
    QuaZipNewInfo_setPermissions(this, info.permissions(), info.isDir());
  }
}
QuaZipNewInfo::QuaZipNewInfo (const QuaZipFileInfo &existing)
Mainly used when copying files between archives.
Both extra fields are initialized to existing.extra. QuaZipNewInfo
Parameters:
existing
Definition at line 69 of file quazipnewinfo.cpp.
References QuaZipNewInfo_init().
{
    QuaZipNewInfo_init(*this, existing);
}
QuaZipNewInfo::QuaZipNewInfo (const QuaZipFileInfo64 &existing)
Mainly used when copying files between archives.
Both extra fields are initialized to existing.extra. QuaZipNewInfo
Parameters:
existing
Definition at line 74 of file quazipnewinfo.cpp.
References QuaZipNewInfo_init().
{
    QuaZipNewInfo_init(*this, existing);
}
Member Function Documentation
void QuaZipNewInfo::setFileDateTime (const QString &file)
Use this function to set the file timestamp from the existing file. Use it like this:
QuaZipFile zipFile(&zip);
QFile file("file-to-add");
file.open(QIODevice::ReadOnly);
QuaZipNewInfo info("file-name-in-archive");
info.setFileDateTime("file-to-add"); // take the timestamp from file
zipFile.open(QIODevice::WriteOnly, info);
This function does not change dateTime if some error occured (e. g. file is inaccessible).
Definition at line 98 of file quazipnewinfo.cpp.
References dateTime.
{
  QFileInfo info(file);
  QDateTime lm = info.lastModified();
  if (info.exists())
    dateTime = lm;
}
void QuaZipNewInfo::setFileNTFSaTime (const QDateTime &aTime, intfineTicks = 0)
The time is written into the NTFS record in both the local and the global extra fields, updating the existing record if there is one, or creating a new one and appending it to the end of each extra field. When updating an existing record, all other fields are left intact.
Parameters:
aTime The new access time.
fineTicks The fractional part of milliseconds, in 100-nanosecond ticks (i. e. 9999 ticks = 999.9 microsecond). Values greater than 9999 will add milliseconds or even seconds, but this can be confusing and therefore is discouraged.
Definition at line 267 of file quazipnewinfo.cpp.
References extraGlobal, extraLocal, and setNTFSTime().
Referenced by setFileNTFSTimes().
{
    setNTFSTime(extraLocal, aTime, 8, fineTicks);
    setNTFSTime(extraGlobal, aTime, 8, fineTicks);
}
void QuaZipNewInfo::setFileNTFScTime (const QDateTime &cTime, intfineTicks = 0)
The time is written into the NTFS record in both the local and the global extra fields, updating the existing record if there is one, or creating a new one and appending it to the end of each extra field. When updating an existing record, all other fields are left intact.
Parameters:
cTime The new creation time.
fineTicks The fractional part of milliseconds, in 100-nanosecond ticks (i. e. 9999 ticks = 999.9 microsecond). Values greater than 9999 will add milliseconds or even seconds, but this can be confusing and therefore is discouraged.
Definition at line 273 of file quazipnewinfo.cpp.
References extraGlobal, extraLocal, and setNTFSTime().
Referenced by setFileNTFSTimes().
{
    setNTFSTime(extraLocal, cTime, 16, fineTicks);
    setNTFSTime(extraGlobal, cTime, 16, fineTicks);
}
void QuaZipNewInfo::setFileNTFSmTime (const QDateTime &mTime, intfineTicks = 0)
The time is written into the NTFS record in both the local and the global extra fields, updating the existing record if there is one, or creating a new one and appending it to the end of each extra field. When updating an existing record, all other fields are left intact.
Parameters:
mTime The new modification time.
fineTicks The fractional part of milliseconds, in 100-nanosecond ticks (i. e. 9999 ticks = 999.9 microsecond). Values greater than 9999 will add milliseconds or even seconds, but this can be confusing and therefore is discouraged.
Definition at line 261 of file quazipnewinfo.cpp.
References extraGlobal, extraLocal, and setNTFSTime().
Referenced by setFileNTFSTimes().
{
    setNTFSTime(extraLocal, mTime, 0, fineTicks);
    setNTFSTime(extraGlobal, mTime, 0, fineTicks);
}
void QuaZipNewInfo::setFileNTFSTimes (const QString &fileName)
If the file doesn't exist, a warning is printed to the stderr and nothing is done. Otherwise, all three times, as reported by QFileInfo::lastModified(), QFileInfo::lastRead() and QFileInfo::created(), are written to the NTFS extra field record.
The NTFS record is written to both the local and the global extra fields, updating the existing record if there is one, or creating a new one and appending it to the end of each extra field.
The microseconds will be zero, as they aren't reported by QFileInfo.
Parameters:
fileName
Definition at line 118 of file quazipnewinfo.cpp.
References setFileNTFSaTime(), setFileNTFScTime(), and setFileNTFSmTime().
{
    QFileInfo fi(fileName);
    if (!fi.exists()) {
        qWarning("QuaZipNewInfo::setFileNTFSTimes(): '%s' doesn't exist",
                 fileName.toUtf8().constData());
        return;
    }
    setFileNTFSmTime(fi.lastModified());
    setFileNTFSaTime(fi.lastRead());
    setFileNTFScTime(fi.created());
}
void QuaZipNewInfo::setFilePermissions (const QString &file)
Takes permissions from the file and sets the high 16 bits of external attributes. Uses QFileInfo to get permissions on all platforms.
Definition at line 106 of file quazipnewinfo.cpp.
References QuaZipNewInfo_setPermissions().
{
    QFileInfo info = QFileInfo(file);
    QFile::Permissions perm = info.permissions();
    QuaZipNewInfo_setPermissions(this, perm, info.isDir());
}
void QuaZipNewInfo::setPermissions (QFile::Permissionspermissions)
Modifies the highest 16 bits of external attributes. The type part is set to dir if the name ends with a slash, and to regular file otherwise.
Definition at line 113 of file quazipnewinfo.cpp.
References name, and QuaZipNewInfo_setPermissions().
{
    QuaZipNewInfo_setPermissions(this, permissions, name.endsWith('/'));
}
Field Documentation
QString QuaZipNewInfo::comment
Will be encoded using QuaZip::getCommentCodec().
Definition at line 75 of file quazipnewinfo.h.
Referenced by QuaZipFile::open().
QDateTime QuaZipNewInfo::dateTime
This is the last file modification date and time. Will be stored in the archive central directory. It is a good practice to set it to the source file timestamp instead of archive creating time. Use setFileDateTime() or QuaZipNewInfo(const QString&, const QString&).
Definition at line 62 of file quazipnewinfo.h.
Referenced by QuaZipFile::open(), QuaZipNewInfo(), and setFileDateTime().
quint32 QuaZipNewInfo::externalAttr
The highest 16 bits contain Unix file permissions and type (dir or file). The constructor QuaZipNewInfo(const QString&, const QString&) takes permissions from the provided file.
Definition at line 71 of file quazipnewinfo.h.
Referenced by QuaZipFile::open(), and QuaZipNewInfo_setPermissions().
QByteArray QuaZipNewInfo::extraGlobal
Definition at line 79 of file quazipnewinfo.h.
Referenced by QuaZipFile::open(), setFileNTFSaTime(), setFileNTFScTime(), and setFileNTFSmTime().
QByteArray QuaZipNewInfo::extraLocal
Definition at line 77 of file quazipnewinfo.h.
Referenced by QuaZipFile::open(), setFileNTFSaTime(), setFileNTFScTime(), and setFileNTFSmTime().
quint16 QuaZipNewInfo::internalAttr
Definition at line 64 of file quazipnewinfo.h.
Referenced by QuaZipFile::open().
QString QuaZipNewInfo::name
This field holds file name inside archive, including path relative to archive root.
Definition at line 55 of file quazipnewinfo.h.
Referenced by QuaZipFile::open(), and setPermissions().
ulong QuaZipNewInfo::uncompressedSize
This is only needed if you are using raw file zipping mode, i. e. adding precompressed file in the zip archive.
Definition at line 84 of file quazipnewinfo.h.
Referenced by QuaZipFile::open().
Author
Generated automatically by Doxygen for ckb-next from the source code.