.TH "src/ckb/quazip/quaziodevice.cpp" 3 "Mon May 22 2017" "Version beta-v0.2.7 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/quazip/quaziodevice.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'quaziodevice\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUAZIO_INBUFSIZE\fP   4096"
.br
.ti -1c
.RI "#define \fBQUAZIO_OUTBUFSIZE\fP   4096"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QUAZIO_INBUFSIZE   4096"

.PP
Definition at line 27 of file quaziodevice\&.cpp\&.
.PP
Referenced by QuaZIODevice::readData()\&.
.SS "#define QUAZIO_OUTBUFSIZE   4096"

.PP
Definition at line 28 of file quaziodevice\&.cpp\&.
.PP
Referenced by QuaZIODevice::flush(), and QuaZIODevice::writeData()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
