.TH "src/ckb/rebindwidget.cpp" 3 "Mon May 22 2017" "Version beta-v0.2.7 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/rebindwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QStandardPaths>\fP
.br
\fC#include 'rebindwidget\&.h'\fP
.br
\fC#include 'ui_rebindwidget\&.h'\fP
.br
\fC#include <qdebug\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBDPI_OFFSET\fP = -\fBKeyAction::DPI_UP\fP + 1"
.br
.ti -1c
.RI "static const int \fBDPI_CUST_IDX\fP = \fBKeyAction::DPI_CUSTOM\fP + \fBDPI_OFFSET\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int DPI_CUST_IDX = \fBKeyAction::DPI_CUSTOM\fP + \fBDPI_OFFSET\fP\fC [static]\fP"

.PP
Definition at line 7 of file rebindwidget\&.cpp\&.
.PP
Referenced by RebindWidget::on_dpiBox_currentIndexChanged()\&.
.SS "const int DPI_OFFSET = -\fBKeyAction::DPI_UP\fP + 1\fC [static]\fP"

.PP
Definition at line 6 of file rebindwidget\&.cpp\&.
.PP
Referenced by RebindWidget::applyChanges(), and RebindWidget::setSelection()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
