RListWidget
NAME
RListWidget -
SYNOPSIS
#include <src/ckb/rlistwidget.h>
Inherits QListWidget.
Signals
void orderChanged ()
Public Member Functions
RListWidget (QWidget *parent=0)
Private Slots
void timerTick ()
void enter (QListWidgetItem *item)
void change (QListWidgetItem *item)
Private Member Functions
void rescanItems ()
Private Attributes
QVariant currentData
QList< QVariant > previousItems
QVariant dragged
QTimer reorderTimer
Static Private Attributes
static const int DATA_ROLE = Qt::UserRole + 100
Detailed Description
Definition at line 9 of file rlistwidget.h.
Constructor & Destructor Documentation
RListWidget::RListWidget (QWidget *parent = 0) [explicit]
Definition at line 4 of file rlistwidget.cpp.
References change(), enter(), reorderTimer, and timerTick().
                                        :
    QListWidget(parent)
{
    setDragDropMode(QAbstractItemView::InternalMove);
    setMovement(QListView::Snap);
    reorderTimer.setSingleShot(true);
    reorderTimer.setInterval(100);
    connect(&reorderTimer, SIGNAL(timeout()), this, SLOT(timerTick()));
    connect(this, SIGNAL(itemEntered(QListWidgetItem*)), this, SLOT(enter(QListWidgetItem*)));
    connect(this, SIGNAL(itemChanged(QListWidgetItem*)), this, SLOT(change(QListWidgetItem*)));
}
Member Function Documentation
void RListWidget::change (QListWidgetItem *item) [private], [slot]
Definition at line 54 of file rlistwidget.cpp.
References reorderTimer.
Referenced by RListWidget().
                                             {
    reorderTimer.stop();
    reorderTimer.start();
}
void RListWidget::enter (QListWidgetItem *item) [private], [slot]
Definition at line 47 of file rlistwidget.cpp.
References DATA_ROLE, dragged, and rescanItems().
Referenced by RListWidget().
                                            {
    rescanItems();
    // Check for drag+drop setup
    if(item)
        dragged = item->data(DATA_ROLE);
}
void RListWidget::orderChanged () [signal]
Definition at line 141 of file moc_rlistwidget.cpp.
Referenced by timerTick().
{
    QMetaObject::activate(this, &staticMetaObject, 0, Q_NULLPTR);
}
void RListWidget::rescanItems () [private]
Definition at line 59 of file rlistwidget.cpp.
References DATA_ROLE, and previousItems.
Referenced by enter().
                             {
    QList<QVariant> newItems;
    int c = count();
    for(int i = 0; i < c; i++){
        QVariant data = this->item(i)->data(DATA_ROLE);
        if(data.isNull()){
            // Generate the ID for this item if it doesn't already exist
            data = QUuid::createUuid();
            this->item(i)->setData(DATA_ROLE, data);
        }
        newItems.append(data);
    }
    previousItems = newItems;
}
void RListWidget::timerTick () [private], [slot]
Definition at line 18 of file rlistwidget.cpp.
References DATA_ROLE, dragged, orderChanged(), and previousItems.
Referenced by RListWidget().
                           {
    bool reordered = false;
    QListWidgetItem* reselect = 0;
    QList<QVariant> newItems;
    // Scan the item list to see if they changed
    int c = count();
    for(int i = 0; i < c; i++){
        QListWidgetItem* itm = item(i);
        QVariant data = itm->data(DATA_ROLE);
        newItems.append(data);
        if(i >= previousItems.count() || data != previousItems[i])
            reordered = true;
        // Re-select the dragged item (if any)
        if(data == dragged)
            reselect = itm;
    }
    if(previousItems.length() != newItems.length())
        return;
    if(reordered){
        previousItems = newItems;
        emit orderChanged();
        if(reselect){
            reselect->setSelected(true);
            setCurrentItem(reselect);
            dragged = QVariant();
        }
    }
}
Field Documentation
QVariant RListWidget::currentData [private]
Definition at line 24 of file rlistwidget.h.
const int RListWidget::DATA_ROLE = Qt::UserRole + 100 [static], [private]
Definition at line 29 of file rlistwidget.h.
Referenced by enter(), rescanItems(), and timerTick().
QVariant RListWidget::dragged [private]
Definition at line 26 of file rlistwidget.h.
Referenced by enter(), and timerTick().
QList<QVariant> RListWidget::previousItems [private]
Definition at line 25 of file rlistwidget.h.
Referenced by rescanItems(), and timerTick().
QTimer RListWidget::reorderTimer [private]
Definition at line 27 of file rlistwidget.h.
Referenced by change(), and RListWidget().
Author
Generated automatically by Doxygen for ckb-next from the source code.