.TH "src/ckb/ui_animadddialog.h" 3 "Tue Jun 6 2017" "Version beta-v0.2.8+testing at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckb/ui_animadddialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QCheckBox>\fP
.br
\fC#include <QtWidgets/QComboBox>\fP
.br
\fC#include <QtWidgets/QDialog>\fP
.br
\fC#include <QtWidgets/QDialogButtonBox>\fP
.br
\fC#include <QtWidgets/QGridLayout>\fP
.br
\fC#include <QtWidgets/QHBoxLayout>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QLabel>\fP
.br
\fC#include <QtWidgets/QSpacerItem>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUi_AnimAddDialog\fP"
.br
.ti -1c
.RI "class \fBUi::AnimAddDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
