.TH "Ui::KbBindWidget" 3 "Thu May 25 2017" "Version v0.2.8 at branch all-mine" "ckb-next" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::KbBindWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <src/ckb/ui_kbbindwidget\&.h>\fP
.PP
Inherits \fBUi_KbBindWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetupUi\fP (\fBQWidget\fP *\fBKbBindWidget\fP)"
.br
.ti -1c
.RI "void \fBretranslateUi\fP (\fBQWidget\fP *\fBKbBindWidget\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "QVBoxLayout * \fBverticalLayout\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel\fP"
.br
.ti -1c
.RI "QFrame * \fBline\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_2\fP"
.br
.ti -1c
.RI "\fBKeyWidget\fP * \fBkeyWidget\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBhorizontalLayout_2\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBcopyButton\fP"
.br
.ti -1c
.RI "QLabel * \fBselectLabel\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBresetButton\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBverticalSpacer\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel_2\fP"
.br
.ti -1c
.RI "QFrame * \fBline_2\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwidget\fP"
.br
.ti -1c
.RI "QGridLayout * \fBgridLayout_2\fP"
.br
.ti -1c
.RI "\fBRebindWidget\fP * \fBrbWidget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 195 of file ui_kbbindwidget\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ui_KbBindWidget::retranslateUi (\fBQWidget\fP *KbBindWidget)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Definition at line 182 of file ui_kbbindwidget\&.h\&.
.PP
References Ui_KbBindWidget::copyButton, Ui_KbBindWidget::label, Ui_KbBindWidget::label_2, Ui_KbBindWidget::resetButton, and Ui_KbBindWidget::selectLabel\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.PP
.nf
183     {
184         KbBindWidget->setWindowTitle(QApplication::translate("KbBindWidget", "Form", Q_NULLPTR));
185         label->setText(QApplication::translate("KbBindWidget", "Keys", Q_NULLPTR));
186         copyButton->setText(QApplication::translate("KbBindWidget", "Copy to mode\&.\&.\&.", Q_NULLPTR));
187         selectLabel->setText(QApplication::translate("KbBindWidget", "Click to select keys", Q_NULLPTR));
188         resetButton->setText(QApplication::translate("KbBindWidget", "Reset", Q_NULLPTR));
189         label_2->setText(QApplication::translate("KbBindWidget", "Binding", Q_NULLPTR));
190     } // retranslateUi
.fi
.SS "void Ui_KbBindWidget::setupUi (\fBQWidget\fP *KbBindWidget)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Definition at line 51 of file ui_kbbindwidget\&.h\&.
.PP
References Ui_KbBindWidget::copyButton, Ui_KbBindWidget::gridLayout, Ui_KbBindWidget::gridLayout_2, Ui_KbBindWidget::horizontalLayout_2, Ui_KbBindWidget::horizontalSpacer, Ui_KbBindWidget::horizontalSpacer_2, Ui_KbBindWidget::keyWidget, Ui_KbBindWidget::label, Ui_KbBindWidget::label_2, Ui_KbBindWidget::line, Ui_KbBindWidget::line_2, Ui_KbBindWidget::rbWidget, Ui_KbBindWidget::resetButton, Ui_KbBindWidget::retranslateUi(), Ui_KbBindWidget::selectLabel, Ui_KbBindWidget::verticalLayout, Ui_KbBindWidget::verticalSpacer, and Ui_KbBindWidget::widget\&.
.PP
Referenced by KbBindWidget::KbBindWidget()\&.
.PP
.nf
52     {
53         if (KbBindWidget->objectName()\&.isEmpty())
54             KbBindWidget->setObjectName(QStringLiteral("KbBindWidget"));
55         KbBindWidget->resize(533, 230);
56         QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
57         sizePolicy\&.setHorizontalStretch(0);
58         sizePolicy\&.setVerticalStretch(0);
59         sizePolicy\&.setHeightForWidth(KbBindWidget->sizePolicy()\&.hasHeightForWidth());
60         KbBindWidget->setSizePolicy(sizePolicy);
61         verticalLayout = new QVBoxLayout(KbBindWidget);
62         verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
63         verticalLayout->setContentsMargins(0, 0, 0, -1);
64         label = new QLabel(KbBindWidget);
65         label->setObjectName(QStringLiteral("label"));
66         QFont font;
67         font\&.setBold(true);
68         font\&.setWeight(75);
69         label->setFont(font);
70 
71         verticalLayout->addWidget(label);
72 
73         line = new QFrame(KbBindWidget);
74         line->setObjectName(QStringLiteral("line"));
75         line->setFrameShape(QFrame::HLine);
76         line->setFrameShadow(QFrame::Sunken);
77 
78         verticalLayout->addWidget(line);
79 
80         gridLayout = new QGridLayout();
81         gridLayout->setObjectName(QStringLiteral("gridLayout"));
82         horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
83 
84         gridLayout->addItem(horizontalSpacer_2, 0, 4, 1, 1);
85 
86         keyWidget = new KeyWidget(KbBindWidget);
87         keyWidget->setObjectName(QStringLiteral("keyWidget"));
88         sizePolicy\&.setHeightForWidth(keyWidget->sizePolicy()\&.hasHeightForWidth());
89         keyWidget->setSizePolicy(sizePolicy);
90 
91         gridLayout->addWidget(keyWidget, 0, 1, 1, 3);
92 
93         horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
94 
95         gridLayout->addItem(horizontalSpacer, 0, 0, 1, 1);
96 
97         horizontalLayout_2 = new QHBoxLayout();
98         horizontalLayout_2->setSpacing(0);
99         horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
100         horizontalLayout_2->setSizeConstraint(QLayout::SetDefaultConstraint);
101         copyButton = new QPushButton(KbBindWidget);
102         copyButton->setObjectName(QStringLiteral("copyButton"));
103         copyButton->setEnabled(true);
104         QSizePolicy sizePolicy1(QSizePolicy::Expanding, QSizePolicy::Fixed);
105         sizePolicy1\&.setHorizontalStretch(0);
106         sizePolicy1\&.setVerticalStretch(0);
107         sizePolicy1\&.setHeightForWidth(copyButton->sizePolicy()\&.hasHeightForWidth());
108         copyButton->setSizePolicy(sizePolicy1);
109         copyButton->setMinimumSize(QSize(140, 0));
110 
111         horizontalLayout_2->addWidget(copyButton);
112 
113         selectLabel = new QLabel(KbBindWidget);
114         selectLabel->setObjectName(QStringLiteral("selectLabel"));
115         sizePolicy1\&.setHeightForWidth(selectLabel->sizePolicy()\&.hasHeightForWidth());
116         selectLabel->setSizePolicy(sizePolicy1);
117         selectLabel->setLineWidth(1);
118         selectLabel->setAlignment(Qt::AlignCenter);
119         selectLabel->setMargin(10);
120         selectLabel->setIndent(-1);
121 
122         horizontalLayout_2->addWidget(selectLabel);
123 
124         resetButton = new QPushButton(KbBindWidget);
125         resetButton->setObjectName(QStringLiteral("resetButton"));
126         sizePolicy1\&.setHeightForWidth(resetButton->sizePolicy()\&.hasHeightForWidth());
127         resetButton->setSizePolicy(sizePolicy1);
128         resetButton->setMinimumSize(QSize(140, 0));
129 
130         horizontalLayout_2->addWidget(resetButton);
131 
132 
133         gridLayout->addLayout(horizontalLayout_2, 1, 1, 1, 3);
134 
135 
136         verticalLayout->addLayout(gridLayout);
137 
138         verticalSpacer = new QSpacerItem(0, 20, QSizePolicy::Minimum, QSizePolicy::Fixed);
139 
140         verticalLayout->addItem(verticalSpacer);
141 
142         label_2 = new QLabel(KbBindWidget);
143         label_2->setObjectName(QStringLiteral("label_2"));
144         label_2->setFont(font);
145 
146         verticalLayout->addWidget(label_2);
147 
148         line_2 = new QFrame(KbBindWidget);
149         line_2->setObjectName(QStringLiteral("line_2"));
150         line_2->setFrameShape(QFrame::HLine);
151         line_2->setFrameShadow(QFrame::Sunken);
152 
153         verticalLayout->addWidget(line_2);
154 
155         widget = new QWidget(KbBindWidget);
156         widget->setObjectName(QStringLiteral("widget"));
157         sizePolicy\&.setHeightForWidth(widget->sizePolicy()\&.hasHeightForWidth());
158         widget->setSizePolicy(sizePolicy);
159         gridLayout_2 = new QGridLayout(widget);
160         gridLayout_2->setSpacing(0);
161         gridLayout_2->setObjectName(QStringLiteral("gridLayout_2"));
162         gridLayout_2->setContentsMargins(0, 0, 0, 0);
163         rbWidget = new RebindWidget(widget);
164         rbWidget->setObjectName(QStringLiteral("rbWidget"));
165         QSizePolicy sizePolicy2(QSizePolicy::MinimumExpanding, QSizePolicy::MinimumExpanding);
166         sizePolicy2\&.setHorizontalStretch(0);
167         sizePolicy2\&.setVerticalStretch(0);
168         sizePolicy2\&.setHeightForWidth(rbWidget->sizePolicy()\&.hasHeightForWidth());
169         rbWidget->setSizePolicy(sizePolicy2);
170 
171         gridLayout_2->addWidget(rbWidget, 0, 0, 1, 1);
172 
173 
174         verticalLayout->addWidget(widget);
175 
176 
177         retranslateUi(KbBindWidget);
178 
179         QMetaObject::connectSlotsByName(KbBindWidget);
180     } // setupUi
.fi
.SH "Field Documentation"
.PP 
.SS "\fBQPushButton\fP* Ui_KbBindWidget::copyButton\fC [inherited]\fP"

.PP
Definition at line 41 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::retranslateUi(), and Ui_KbBindWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbBindWidget::gridLayout\fC [inherited]\fP"

.PP
Definition at line 36 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "QGridLayout* Ui_KbBindWidget::gridLayout_2\fC [inherited]\fP"

.PP
Definition at line 48 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "QHBoxLayout* Ui_KbBindWidget::horizontalLayout_2\fC [inherited]\fP"

.PP
Definition at line 40 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "QSpacerItem* Ui_KbBindWidget::horizontalSpacer\fC [inherited]\fP"

.PP
Definition at line 39 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "QSpacerItem* Ui_KbBindWidget::horizontalSpacer_2\fC [inherited]\fP"

.PP
Definition at line 37 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "\fBKeyWidget\fP* Ui_KbBindWidget::keyWidget\fC [inherited]\fP"

.PP
Definition at line 38 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by KbBindWidget::KbBindWidget(), KbBindWidget::newLayout(), KbBindWidget::setBind(), Ui_KbBindWidget::setupUi(), and KbBindWidget::updateBind()\&.
.SS "QLabel* Ui_KbBindWidget::label\fC [inherited]\fP"

.PP
Definition at line 34 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::retranslateUi(), and Ui_KbBindWidget::setupUi()\&.
.SS "QLabel* Ui_KbBindWidget::label_2\fC [inherited]\fP"

.PP
Definition at line 45 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::retranslateUi(), and Ui_KbBindWidget::setupUi()\&.
.SS "QFrame* Ui_KbBindWidget::line\fC [inherited]\fP"

.PP
Definition at line 35 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "QFrame* Ui_KbBindWidget::line_2\fC [inherited]\fP"

.PP
Definition at line 46 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "\fBRebindWidget\fP* Ui_KbBindWidget::rbWidget\fC [inherited]\fP"

.PP
Definition at line 49 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by KbBindWidget::newLayout(), KbBindWidget::newSelection(), KbBindWidget::setBind(), Ui_KbBindWidget::setupUi(), and KbBindWidget::updateBind()\&.
.SS "\fBQPushButton\fP* Ui_KbBindWidget::resetButton\fC [inherited]\fP"

.PP
Definition at line 43 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::retranslateUi(), and Ui_KbBindWidget::setupUi()\&.
.SS "QLabel* Ui_KbBindWidget::selectLabel\fC [inherited]\fP"

.PP
Definition at line 42 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::retranslateUi(), Ui_KbBindWidget::setupUi(), and KbBindWidget::updateSelDisplay()\&.
.SS "QVBoxLayout* Ui_KbBindWidget::verticalLayout\fC [inherited]\fP"

.PP
Definition at line 33 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "QSpacerItem* Ui_KbBindWidget::verticalSpacer\fC [inherited]\fP"

.PP
Definition at line 44 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.
.SS "\fBQWidget\fP* Ui_KbBindWidget::widget\fC [inherited]\fP"

.PP
Definition at line 47 of file ui_kbbindwidget\&.h\&.
.PP
Referenced by Ui_KbBindWidget::setupUi()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ckb-next from the source code\&.
